CGAL/cgal

- Combinatorial_map/include/CGAL/Cell_iterators.h
- Combinatorial_map/include/CGAL/Combinatorial_map.h
- Combinatorial_map/include/CGAL/Combinatorial_map_iterators_base.h
- Combinatorial_map/test/Combinatorial_map/Combinatorial_map_3_test.h
Bug fix for iterator.
Add some tests in Combinatorial_map_3_test.h to test more cases for the iterators.
Test in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.6-Ic-158.shtml
> C map iterator bug gdamiand

- Algebraic_foundations/doc/Algebraic_foundations/Concepts/FieldNumberType.h
- Algebraic_foundations/doc/Algebraic_foundations/Concepts/RingNumberType.h
- Nef_2/doc/Nef_2/CGAL/Extended_cartesian.h
- Nef_2/doc/Nef_2/CGAL/Extended_homogeneous.h
- Nef_2/doc/Nef_2/CGAL/Filtered_extended_homogeneous.h
- Number_types/doc/Number_types/CGAL/leda_rational.h
trivial fixes in the documentation of Nef_2 and Algebraic_foundations
> fix documentation in Nef_2

- Documentation/header.html
- Documentation/header_package.html
We checked that the doc builds and looks good
> Add a link to www.cgal.org in the horizontal menu

- Kernel_d/doc/Kernel_d/CGAL/Epick_d.h
- Kernel_d/doc/Kernel_d/Concepts/Kernel--Construct_max_vertex_d.h
- Kernel_d/doc/Kernel_d/Concepts/Kernel--Construct_min_vertex_d.h
- Kernel_d/doc/Kernel_d/PackageDescription.txt
- NewKernel_d/include/CGAL/NewKernel_d/Kernel_d_interface.h
- NewKernel_d/include/CGAL/NewKernel_d/Types/Iso_box.h
- NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Point_d.h
- NewKernel_d/include/CGAL/NewKernel_d/functor_tags.h
- NewKernel_d/test/NewKernel_d/Epick_d.cpp
- Spatial_searching/benchmark/Spatial_searching/CMakeLists.txt
- Spatial_searching/doc/Spatial_searching/Spatial_searching.txt
- Spatial_searching/examples/Spatial_searching/CMakeLists.txt
- Spatial_searching/examples/Spatial_searching/fuzzy_range_query.cpp
- Spatial_searching/examples/Spatial_searching/general_neighbor_searching.cpp
- Spatial_searching/examples/Spatial_searching/iso_rectangle_2_query.cpp
- Spatial_searching/examples/Spatial_searching/searching_sphere_orthogonally.cpp
- Spatial_searching/examples/Spatial_searching/searching_with_circular_query.cpp
- Spatial_searching/examples/Spatial_searching/searching_with_point_with_info.cpp
- Spatial_searching/examples/Spatial_searching/searching_with_point_with_info_inplace.cpp
- Spatial_searching/examples/Spatial_searching/searching_with_point_with_info_pmap.cpp
- Spatial_searching/include/CGAL/Manhattan_distance_iso_box_point.h
- Triangulation/doc/Triangulation/Doxyfile.in
- Triangulation/doc/Triangulation/PackageDescription.txt
- Triangulation/doc/Triangulation/Triangulation.txt
- Triangulation/doc/Triangulation/dependencies
Branch from Andreas Fabri, with constributions from Marc Glisse and Clément Jamin.
Adds new functors to `Epick_d`, so that `Epick_d` can be used with Spatial Searching.
For the moment, the branch is still under testing.
> New kernel_d isobox

- Generator/doc/Generator/CGAL/point_generators_2.h
- Generator/doc/Generator/CGAL/point_generators_3.h
- Generator/doc/Generator/Concepts/PointGenerator.h
- Generator/doc/Generator/Generator.txt
- Generator/doc/Generator/PackageDescription.txt
- Generator/doc/Generator/examples.txt
- Generator/examples/Generator/random_points_tetrahedron_and_triangle_3.cpp
- Generator/examples/Generator/random_points_triangle_2.cpp
- Generator/include/CGAL/point_generators_2.h
- Generator/include/CGAL/point_generators_3.h
- Generator/package_info/Generator/copyright
- Generator/package_info/Generator/long_description.txt
- Generator/test/Generator/test_tetrahedron_3.cpp
- Generator/test/Generator/test_triangle_2.cpp
- Generator/test/Generator/test_triangle_3.cpp
- Installation/changes.html
Successfully tested in 4.7-Ic-5
Small feature pre-approved:
Features/Small_Features/More_point_generators_gsoc2013
> Generator more point generators pmachado

- CGAL_ipelets/demo/CGAL_ipelets/distance.cpp
- CGAL_ipelets/demo/CGAL_ipelets/hyperbolic.cpp
the member function is specific to a few number types
> using the free function to_double instead of the member function

- Convex_hull_3/doc/Convex_hull_3/CGAL/Convex_hull_3/dual/halfspace_intersection_3.h
- Convex_hull_3/doc/Convex_hull_3/CGAL/Convex_hull_3/dual/halfspace_intersection_with_constructions_3.h
- Convex_hull_3/examples/Convex_hull_3/halfspace_intersection_3.cpp
- Convex_hull_3/include/CGAL/Convex_hull_3/dual/halfspace_intersection_3.h
- Convex_hull_3/include/CGAL/Convex_hull_3/dual/halfspace_intersection_with_constructions_3.h
- Convex_hull_3/test/Convex_hull_3/test_halfspace_intersections.cpp
Merged into CGAL-4.7-Ic-30
The branch is based on releases/CGAL-4.6-branch
It fixes #76 and #75
Previously submitted as #81
> Convex hull 3 fix halfspace intersections sloriot

- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Polyhedron_demo_selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Selection_widget.ui
Improvement of the selection plugin of the polyhedron demo
> make the selection plugin exporting selected edges as a polyline item

- Convex_hull_3/doc/Convex_hull_3/CGAL/Convex_hull_3/dual/halfspace_intersection_3.h
- Convex_hull_3/doc/Convex_hull_3/CGAL/Convex_hull_3/dual/halfspace_intersection_with_constructions_3.h
- Convex_hull_3/examples/Convex_hull_3/halfspace_intersection_3.cpp
- Convex_hull_3/include/CGAL/Convex_hull_3/dual/halfspace_intersection_3.h
- Convex_hull_3/include/CGAL/Convex_hull_3/dual/halfspace_intersection_with_constructions_3.h
- Convex_hull_3/include/CGAL/Convex_hull_3/dual/interior_polyhedron_3.h
- Convex_hull_3/test/Convex_hull_3/test_halfspace_intersections.cpp
A few commits cleaning the code
Depends on #82
> Convex hull 3 clean halfspace intersection sloriot

- Installation/CMakeLists.txt
> Add -frounding-math for gcc 4 *and later*

- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
Merged into [CGAL-4.7-Ic-51](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-51.shtml).
This branch only changes the polyhedron demo.
> Before trying to orient a soup, start by removing degenerate polygons

- Number_types/include/CGAL/Mpzf.h
> Emulate mpn_sqr on old versions of GMP.

- Polyhedron/demo/Polyhedron/Polyhedron_demo_join_and_split_polyhedra_plugin.cpp
Merged into [CGAL-4.7-Ic-51](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-51.shtml).
This branch only changes the polyhedron demo.
> add an action to assign a color per cc of a polyhedron

- Triangulation/doc/Triangulation/Concepts/DelaunayTriangulationTraits.h
- Triangulation/doc/Triangulation/Concepts/TriangulationTraits.h
> Document that Triangulation only works with Epick_d.

- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
> Fix a bug in CDT_plus_2

- Mesh_3/demo/Mesh_3/Volume_planes_plugin.cpp
> Fix for libQGLViewer>=2.6.0

- Installation/changes.html
As asked in the last comment of https://github.com/CGAL/cgal/pull/84
> Announce new functors for alpha-shapes

- Installation/changes.html
These place holders should go into master
The four branches of @cjamin @sloriot  @mhsaar should also merge them, and the authors should move the change text between the begi/end block. This will avoid merge conflicts when the packages go into integration.
> Add place holders for the packages to be integrated

- Installation/changes.html
- Polyhedron/demo/Polyhedron/Polyhedron_demo_mean_curvature_flow_skeleton_plugin.cpp
- Solver_interface/include/CGAL/Eigen_solver_traits.h
- Surface_mesh_parameterization/doc/Surface_mesh_parameterization/dependencies
- Surface_mesh_parameterization/doc/Surface_mesh_parameterization/include/CGAL/Eigen_solver_traits.h
- Surface_mesh_skeletonization/doc/Surface_mesh_skeletonization/Concepts/NormalEquationSparseLinearAlgebraTraitsWithFactor_d.h
- Surface_mesh_skeletonization/doc/Surface_mesh_skeletonization/PackageDescription.txt
- Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Mean_curvature_flow_skeleton
Feature developed by Xiang Gao, Sébastien Loriot (@sloriot), and Andreas Fabri (@afabri).
> Triangulated Surface Mesh Skeletonization, new package, GSoC 2013

- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
- STL_Extension/include/CGAL/vector.h
> Fix a miscompilation by clang-3.6.x

- NewKernel_d/include/CGAL/NewKernel_d/Types/Hyperplane.h
- NewKernel_d/test/NewKernel_d/Epick_d.cpp
Bug-fix
I merged it to integration today, it might end up being tested in
https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-86.shtml
(sorry for the early pull request, but I am leaving for almost a month)
> Epick_d, fix hyperplane

- Polygon_mesh_processing/test/Polygon_mesh_processing/self_intersection_surface_mesh_test.cpp
- Polygon_mesh_processing/test/Polygon_mesh_processing/triangulate_hole_Polyhedron_3_no_delaunay_test.cpp
- Polygon_mesh_processing/test/Polygon_mesh_processing/triangulate_hole_Polyhedron_3_test.cpp
- Polyhedron/demo/Polyhedron/Polyhedron_demo_hole_filling_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
> Fix warnings in Polygon_mesh_processing

- Kernel_d/include/CGAL/Kernel_d/function_objectsHd.h
- Point_set_shape_detection_3/doc/Point_set_shape_detection_3/Concepts/EfficientRANSACTraits.h
- Point_set_shape_detection_3/examples/Point_set_shape_detection_3/efficient_RANSAC_custom_shape.h
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Cone.h
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Cylinder.h
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Plane.h
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Shape_base.h
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Sphere.h
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Torus.h
- Point_set_shape_detection_3/test/Point_set_shape_detection_3/test_scene.cpp
> Fix a bug and warnings in Point_set_shape_detection_3

- Triangulation/doc/Triangulation/CGAL/Triangulation.h
See https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/hash#Status
Completes PR #179
> Add sentence about hashable handles

- Installation/changes.html
3D periodic triangulations changes were badly located.
> Fix changes.html

- Documentation/doc/Documentation/Installation.txt
> document the list of qt5 modules used

- Documentation/doc/Documentation/Installation.txt
> Fix versions of support compilers

- NewKernel_d/include/CGAL/NewKernel_d/Vector/array.h
> fix warning

- Intersections_2/include/CGAL/Triangle_2_Iso_rectangle_2_intersection.h
- Intersections_2/test/Intersections_2/test_intersections_2.cpp
> Fix do_intersect(Triangle_2,Iso_rectangle_2) in case no vertex is on bounded side

- Boolean_set_operations_2/demo/Boolean_set_operations_2_GraphicsView/CMakeLists.txt
- GraphicsView/demo/Polygon/Polygon_2.cpp
- GraphicsView/demo/Segment_Delaunay_graph_2/Segment_voronoi_2.cpp
- GraphicsView/demo/Segment_Delaunay_graph_2/Segment_voronoi_2.ui
- GraphicsView/demo/Segment_Delaunay_graph_2/about_Segment_voronoi_2.html
- GraphicsView/demo/Segment_Delaunay_graph_Linf_2/Segment_voronoi_linf_2.cpp
- GraphicsView/demo/Triangulation_2/Constrained_Delaunay_triangulation_2.cpp
- GraphicsView/demo/Triangulation_2/TriangulationPointInputAndConflictZone.h
- GraphicsView/include/CGAL/Qt/PolygonGraphicsItem.h
- GraphicsView/include/CGAL/Qt/SegmentDelaunayGraphGraphicsItem.h
- GraphicsView/include/CGAL/Qt/TriangulationGraphicsItem.h
I at the same time cleaned up the UI of a demo, and fixed an about.html
> fix line width in demos using GraphicsView

- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Point_set_selection_widget.ui
- Polyhedron/demo/Polyhedron/Polyhedron_demo_point_set_selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h
- Polyhedron/demo/Polyhedron/cgal_test_with_cmake
- Polyhedron/demo/Polyhedron/include/Point_set_3.h
The branch was made by Simon Giraudot (@sgiraudot), and tested in [CGAL-4.7-Ic-102](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-102.shtml#Polyhedron_Demo). The plugin was also manually tested on Linux and Windows by Simon and Andreas fabri (@afabri).
> Polyhedron demo, add a demo point set selection plugin

- Alpha_shapes_3/demo/Alpha_shapes_3/MainWindow.cpp
- Alpha_shapes_3/demo/Alpha_shapes_3/Viewer.cpp
- GraphicsView/demo/Triangulation_2/Constrained_Delaunay_triangulation_2.cpp
- Linear_cell_complex/demo/Linear_cell_complex/MainWindow.cpp
- Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp
- Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/MainWindow.cpp
- Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/Viewer.cpp
- Surface_mesher/demo/Surface_mesher/Raw_image_dialog.cpp
- Surface_mesher/demo/Surface_mesher/colorlisteditor.cpp
- Surface_mesher/demo/Surface_mesher/mainwindow.cpp
- Surface_mesher/demo/Surface_mesher/values_list.cpp
- Surface_mesher/demo/Surface_mesher/viewer.cpp
- Surface_mesher/demo/Surface_mesher/volume.cpp
- Triangulation_3/demo/Triangulation_3/MainWindow.cpp
- Triangulation_3/demo/Triangulation_3/PreferenceDlg.cpp
- Triangulation_3/demo/Triangulation_3/Viewer.cpp
> Remove warnings about unused moc files

- GraphicsView/demo/Segment_Delaunay_graph_2/Segment_voronoi_2.cpp
- GraphicsView/demo/Segment_Delaunay_graph_Linf_2/Segment_voronoi_linf_2.cpp
- GraphicsView/demo/Stream_lines_2/Stream_lines_2.cpp
> Graphics View demos: remove unwanted slots

- Polyline_simplification_2/include/CGAL/Polyline_simplification_2/simplify.h
See #282 
(cherry picked from commit dcbab4e0d4ebf709e78688ef5407527fa02831a0)
> use CGAL_assert and assertion_code (version for 4.6)

- Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_2_iterators.h
- BGL/include/CGAL/boost/graph/graph_traits_HalfedgeDS.h
- BGL/include/CGAL/boost/graph/graph_traits_Triangulation_2.h
- Installation/include/CGAL/config.h
- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/In_place_list.h
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
I at the same time moved the popping of pragmas
> No longer forward declare struct std:hash

- Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h
- Cartesian_kernel/include/CGAL/Cartesian/Sphere_3.h
- Circular_kernel_3/test/Circular_kernel_3/include/CGAL/_test_sphere_constructions.h
- Homogeneous_kernel/include/CGAL/Homogeneous/Aff_transformationH3.h
- Installation/CHANGES
- Installation/changes.html
- Kernel_23/include/CGAL/internal/Projection_traits_3.h
- Kernel_23/test/Kernel_23/issue_129.cpp
- Nef_2/include/CGAL/Nef_2/Polynomial.h
- Number_types/test/Number_types/bench_interval.cpp
- Polynomial/include/CGAL/Polynomial/Polynomial_type.h
- STL_Extension/include/CGAL/internal/boost/array_binary_tree.hpp
This branch implements some compilation fixes for CGAL to support MSVC 2015.
I am not sure yet whether it is complete, because of some infrastructure problems, but I would already like to test it in integration.
> Support MSVC 2015

- Circulator/doc/Circulator/Concepts/ConstHandle.h
- Combinatorial_map/doc/Combinatorial_map/Concepts/Dart.h
Update documentation of XXX handle (in Dart concept) following @lrineau comment.
Require to add ConstHandle concept.
> CMap docfix gdamiand

- Point_set_processing_3/include/CGAL/IO/write_xyz_points.h
It seems so small that I didn't merge it into integration.
> fixed a typo

- Advancing_front_surface_reconstruction/examples/Advancing_front_surface_reconstruction/reconstruction_fct.cpp
> Add the maximal perimeter as an argument to the executable

- Spatial_searching/include/CGAL/Incremental_neighbor_search.h
- Spatial_searching/include/CGAL/Orthogonal_incremental_neighbor_search.h
> make (Orthogonal_)incremental_nearest_neighbor a valid range

- Nef_3/doc/Nef_3/CGAL/Nef_polyhedron_3.h
- Nef_3/include/CGAL/Nef_polyhedron_3.h
- Nef_3/test/Nef_3/nef_3_from_points.cpp
See the [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/new_constructor_for_nef)
> add constructor from point, point range and segment

- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/Scene.h
- Polyhedron/demo/Polyhedron/Scene_draw_interface.h
- Polyhedron/demo/Polyhedron/Viewer.cpp
- Polyhedron/demo/Polyhedron/Viewer.h
A small axis system is displayed in the top right corner of the viewer, allowing to quickly know the orientation of the camera at any time. It is displayed by default but can be hidden with the A key. The colors are :
X in red
Y in green
Z in blue
so that x,y,z is r,g,b.
> Polyhedron demo : Addition of a small axis system in a corner 

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Polyhedron_demo_off_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_item.h
- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Addition of the extremities of the bounding box and the
number of isolated vertices.
> Addition of some informations about the items

- Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.cpp
This pull request fixes some problems with the nef item, like the selection that still called invalidate_buffers or the color of the facets that weren't right.
> Polyhedron demo: fix nef item

- Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polylines_item.h
- The polyline item was not computed. I passed the computing function const to
call it the same way initialize_buffers is called, from draw.
> Hole_filling fix

- Installation/changes.html
- Spatial_searching/doc/Spatial_searching/CGAL/Kd_tree.h
- Spatial_searching/doc/Spatial_searching/CGAL/Kd_tree_node.h
- Spatial_searching/examples/Spatial_searching/searching_with_circular_query.cpp
- Spatial_searching/include/CGAL/Kd_tree.h
- Spatial_searching/include/CGAL/Kd_tree_node.h
tested, documented, small feature.
> Add function Kd_tree::find_any_point(Query)

- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
The branch has the wrong name as it concerns a concept uin Kernel_23
> Prefix cpp11::result_of() with CGAL::

- Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/Segment_Delaunay_graph_2.txt
So it makes no sense to explain it in the User Manual.
> The class Segment_Delaunay_graph_without_intersections_2 does not exist

- Kernel_23/include/CGAL/Bbox_2.h
- Kernel_23/include/CGAL/Bbox_3.h
Added simple initialisation to silence warnings.
> Silence for warnings

- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
- When hitting the "select all" button with "edges" selected, nothing happened.
I fixed it by adding a call to invalidate_buffers and viewer->update.
> Selection tool edges fix

- Installation/include/CGAL/config.h
- Installation/include/CGAL/gl.h
Added arm and aarch64 to config.h file to be able make a build for arm based devices.
> Changes for arm devices

- Polyhedron/demo/Polyhedron/Viewer.cpp
- addition of casts to silence warnings in Viewer.
> Warning fix

- Polyhedron/demo/Polyhedron/Polyhedron_demo_mesh_3_plugin.cpp
- Polyhedron/demo/Polyhedron/Polyhedron_demo_mesh_3_plugin_cgal_code.cpp
- Displays the item after its creation without having to move the manipulated frame.
- Enhances the performance when moving the manipulated frame.
> Tetrahedral mesh fix

- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Polyhedron_demo_vtk_plugin.cpp
this PR introduces Polyhedron_demo_vtk_plugin to load .vtk and .vtp files in a Scene_polyhedron_item
> Polyhedron demo : add vtk_plugin

- BGL/include/CGAL/boost/graph/helpers.h
- Installation/changes.html
- Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/connected_components_example.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/connected_component_surface_mesh.cpp
Add a function that keeps components with a number of faces above a threshold.
I added code, doc, and a test
> Add keep_large_connected_components ()

- Polyhedron/demo/Polyhedron/GlSplat/GlSplat.h
- Addition of a typedef for glFramebufferTexture2D.
> Compilation error fix

- Triangulation_3/include/CGAL/Delaunay_triangulation_3.h
- Triangulation_3/include/CGAL/Regular_triangulation_3.h
- Triangulation_3/test/Triangulation_3/test_regular_insert_range_with_info.cpp
Bug-fix: same as PR #58, but for Regular_triangulation_3 (instead of Delaunay_triangulation_3).
Tested in [CGAL-4.8-Ic-33](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-33.shtml)
> Enable parallel insertion of points with info in Regular_triangulation_3

- Polyhedron/demo/Polyhedron/Add_point_set_dialog.ui
- Polyhedron/demo/Polyhedron/Add_polylines_dialog.ui
- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Io_implicit_function_plugin.cpp
- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/MainWindow.ui
- Polyhedron/demo/Polyhedron/Polyhedron_demo_polylines_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Polyhedron_demo_xyz_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
- Three/doc/Three/Three.txt
This creates a Dialog to add a polyline by entering coordinates, and another one to do the same with a point set.
> Polyhedron demo: add polylines/point sets, on the fly

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h
Related to #467 
Merged in 4.8-Ic-41
> Pmp compute normal epec

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h
This PR proposes some improvements for the documentation of triangulate_hole_polyline().
It intends to fix issue #465
> PMP triangulate_hole_polyline documentation

- NewKernel_d/include/CGAL/NewKernel_d/LA_eigen/constructors.h
- NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Cartesian_wrap.h
- NewKernel_d/include/CGAL/NewKernel_d/utils.h
As pointed out [here](http://lists.boost.org/boost-users/2014/11/83291.php) it is a false positive.
> suppress warning concerning macro 'BOOST_PP_EXPAND_I'

- Polyhedron/demo/Polyhedron/Polyhedron_demo_isotropic_remeshing_plugin.cpp
border_halfedges internal implementation needs the face index map to be properly filled
with indices
> Polyhedron demo : fix the isotropic remeshing plugin

- Polyhedron/include/CGAL/Polyhedron_3.h
Discussed in much detail on cgal-develop
> include the file that provides IO stream operators

- BGL/include/CGAL/boost/graph/iterator.h
Must I merge this into integration?
> add const qualifier

- Polyhedron/demo/Polyhedron/MainWindow.cpp
The update of the plugin system was not appropriate for Windows, this is a fix for it.
> Polyhedron demo fix plugin loading

- Installation/changes.html
- Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/border.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
This PR introduces new utility functions to the PMP package.
It implements the [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/add_PMP_utility_functions), pre-approved on Nov 12th
> PMP : add utility functions

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Shortest_path_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Volume_planes_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Fairing_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Hole_filling_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Point_inside_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Polyhedron_slicer_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_segmentation_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_modeling/Edit_polyhedron_plugin.cpp
- Three/demo/Three/Example_plugin/Polyhedron_demo_example_plugin.cpp
- Three/doc/Three/Three.txt
- Three/include/CGAL/Three/Polyhedron_demo_plugin_interface.h
This PR hides the controls widget when it is created.
>  Volume_planes_plugin fix

- Polygon_mesh_processing/doc/Polygon_mesh_processing/NamedParameters.txt
doc built locally, and reviewed by Jane.
> fix a type

- Number_types/doc/Number_types/CGAL/Sqrt_extension.h
> document explicit constructor

- Documentation/doc/Documentation/Developer_manual/Chapter_portability.txt
> list reasonnable boost libs we can use in CGAL

- Surface_mesher/demo/Surface_mesher/CMakeLists.txt
Svg was missing from the CMakeLists.txt.
> Added Svg to the CMakeLists.txt

- Kernel_23/doc/Kernel_23/Kernel_23.txt
The variable names in the example do not make sense, hope my changes are correct.
> Fixed code example for Upgrading intersection

- Three/include/CGAL/Three/Polyhedron_demo_io_plugin_interface.h
- moved forward declaration of scene_item in the namespace CGAL::Three
> IO_plugin_interface fix

- Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Polycurve_2.h
> fix IO of polycurves

- Mesh_3/doc/Mesh_3/CGAL/Labeled_image_mesh_domain_3.h
> document the need to link with ImageIO

- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
This PR makes the selected points inside a polyhedron red instead of black.
> Selection color fix

- Installation/doc_html/index.html
- wininst/developer_scripts/script_cgal.nsi
> Install fix nsi

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/MainWindow.ui
- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/Scene.h
- Polyhedron/demo/Polyhedron/Scene_group_item.cpp
- Three/include/CGAL/Three/Scene_group_item.h
This PR allows to move items up and down inside their group, if they have one, in the Polyhedron_demo.
> Moving items in the list

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/Scene.h
This PR makes the list of items scroll when a user performs a picking.
> Scrolls the sceneView when a picking is performed.

- NewKernel_d/include/CGAL/NewKernel_d/function_objects_cartesian.h
- Number_types/include/CGAL/Mpzf.h
Handle mpq_class.
Make Mpzf fail noisily with Eigen.
This will hopefully be tested Saturday night, or the first time integration is tested after that.
> Number type TLC for NewKernel_d

- Installation/changes.html
- Polygon_mesh_processing/examples/Polygon_mesh_processing/triangulate_faces_example.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_faces.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/CMakeLists.txt
- Polygon_mesh_processing/test/Polygon_mesh_processing/triangulate_faces_test.cpp
Adds a function to triangulate a single face and a function to triangulate a FaceRange for consistency with other parts of this package.
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Triangulate_face
> Add triangulate_face and triangulate_faces range overload

- Three/doc/Three/Three.txt
backquote classes, capitalize words in \sections
@maxGimeno todo: move Useful Classes to PackageDescription.txt
> Cosmetic Changes

- Polyhedron/demo/Polyhedron/Scene.cpp
With this PR, when an item is loaded, if a group was selected, the new item is automatically added to it.
> Group_item update

- Convex_hull_2/include/CGAL/Convex_hull_2/ch_melkman_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/measure.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h
- Polygon_mesh_processing/include/CGAL/polygon_mesh_processing.h
- STL_Extension/include/CGAL/Iterator_range.h
Small fixes discovered while writing PMP bindings
> Pmp enhancement from bindings

- Polyhedron/demo/Polyhedron/Plugins/Point_set/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Merge_point_sets_plugin.cpp
New plugin designed to merge several point set items into one.
Merged in [4.8-Ic-95](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-95.shtml).
> Polyhedron demo: merge point sets

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Io_image_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Raw_image_dialog.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Raw_image_dialog.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/raw_image.ui
I copied and adapted code from the Surface_mesher demo.
We should check what else is missing (e.g. VTK)
> Add reading a raw image to the io_image_plugin

- Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
A file `polylines.cgal.txt` was created during the computation.
> Remove debug ouput

- Combinatorial_map/include/CGAL/Combinatorial_map_iterators_base.h
- Combinatorial_map/include/CGAL/Dart_iterators.h
- Combinatorial_map/test/Combinatorial_map/Combinatorial_map_2_test.h
- Combinatorial_map/test/Combinatorial_map/Combinatorial_map_3_test.h
- Combinatorial_map/test/Combinatorial_map/Combinatorial_map_copy_test.cpp
- Combinatorial_map/test/Combinatorial_map/Combinatorial_map_test_iterators.h
Bug fix in CMap_extend_iterator class and in CMap_dart_iterator_basic_of_two_beta classes.
Add several tests in test/Combinatorial_map/ in order to be able to detect such a bug.
Tested in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-97.shtml.
> CMap bugfix iterator gdamiand

- Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp
- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene.cpp
- The AABB_Tree is displayed again
- The edges of the AABB_Tree and the cut_object are in the right color
- The Scene is not decentered by the creation of the cutting plane.
> Fixes for the cut_plugin :

- Three/demo/Three/Example_plugin/Polyhedron_demo_example_plugin.cpp
- Three/doc/Three/Three.txt
This PR corrects some errors in the doc of Three about the plugins creation.
> Doc update

- Documentation/doc/Documentation/Developer_manual/Chapter_testing.txt
- Documentation/doc/Documentation/Developer_manual/developer_manual.txt
> add a page on how to run the testsuite

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
In this PR I moved the call of does_self_intersect to the compute_stats function.
> Moving the self-intersecting test

- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
> Use std::set instead of boost::flat_set in case of VC++ and boost 1.55

- BGL/doc/BGL/Doxyfile.in
- BGL/doc/BGL/PackageDescription.txt
- BGL/doc/BGL/examples.txt
- BGL/include/CGAL/boost/graph/split_graph_into_polylines.h
- Installation/changes.html
- Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt
- Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Polyhedron_stitching_plugin.cpp
- Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/simple_mcfskel_example.cpp
- Surface_mesh_skeletonization/include/CGAL/internal/Surface_mesh_skeletonization/Detect_degeneracy.h
Small feature [page](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Split_graph_into_polylines).
> BGL: document split in polylines

- BGL/doc/BGL/Doxyfile.in
- BGL/doc/BGL/PackageDescription.txt
- BGL/include/CGAL/boost/graph/selection.h
- Installation/changes.html
- Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt
- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_widget.ui
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item_k_ring_selection.h
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
Small feature [page](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/BGL_selection).
> BGL: document selection functions

- Scripts/developer_scripts/create_internal_release
> Improve create_internal_release

- BGL/examples/BGL_polyhedron_3/range.cpp
- Installation/include/CGAL/config.h
- Surface_mesh/examples/Surface_mesh/sm_iterators.cpp
> Fix macro name 

- Polyhedron/demo/Polyhedron/Plugins/Camera_position/Camera_positions_list.cpp
- Polyhedron/demo/Polyhedron/Viewer.cpp
- Reverts a commit about the axis that didn't work and broke several features
- Fixes a warning from libQGLViewer about a deprecated function.
> Viewer fixes gf

- Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h
- Polyhedron/demo/Polyhedron/Plugins/PCA/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/PCA/Create_bbox_mesh_plugin.cpp
- Polyhedron/demo/Polyhedron/cgal_test_with_cmake
Add a new plugin to compute bounding polyhedra.
Maybe the trivial plugin should be removed.
@afabri @sloriot @janetournois
> Add the Create_bbox_mesh_plugin

- Documentation/doc/Documentation/Installation.txt
> Do not document EIGEN3_DIR as it is identical to EIGEN3_INC_DIR

- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/CMakeLists.txt
- Surface_mesh_parameterization/test/Surface_mesh_parameterization/CMakeLists.txt
> No need for -fno-strict-aliasing

- Surface_mesh/doc/Surface_mesh/Surface_mesh.txt
> Explain why num_vertices(Surface_mesh&) also counts deleted vertices

- Polyhedron/demo/Polyhedron/Plugins/Surface_modeling/Edit_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_modeling/Scene_edit_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_modeling/Scene_edit_polyhedron_item.h
- Added a function to update the plane's data, called when the plane constrained option is set,
so that the plane is always where it should be.
> Polyhedron_demo : Fix for the mesh deformation

- Arrangement_on_surface_2/include/CGAL/Arr_Bezier_curve_traits_2.h
> Arrangement: add missing const qualifiers

- Generator/examples/Generator/random_polygon.cpp
so that we can reproduce a testcase
> Print out the seed.

- Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt
Add text; Add an \ingroup; Capitalize
> Polish PMP PackageDescription

- Periodic_2_triangulation_2/test/Periodic_2_triangulation_2/test_p2t2_performance_gredner.cpp
- Periodic_2_triangulation_2/test/Periodic_2_triangulation_2/test_p2t2_performance_test.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_alpha_shape_3.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_delaunay_3.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_delaunay_3_bc.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_delaunay_hierarchy_3.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_offset_3.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_triangulation_3.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_triangulation_3_bc.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_triangulation_tds.cpp
This should fix [this testcase](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-117/Periodic_2_triangulation_2/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Debug-64bits.gz)
> In debug mode it makes no sense to run a performance test

- Combinatorial_map/include/CGAL/Combinatorial_map.h
I did not test it as I do not have access to the platform.
> Disable a warning on the Intel  compiler 

- Three/include/CGAL/Three/Scene_item.h
- Three/include/CGAL/Three/Viewer_interface.h
- Documents the shader programs and explains in what situation they must be used.
> Polyhedron_Demo : Documentation update

- AABB_tree/demo/AABB_tree/Viewer.cpp
- Alpha_shapes_3/demo/Alpha_shapes_3/Viewer.cpp
- Circular_kernel_3/demo/Circular_kernel_3/Viewer.cpp
- GraphicsView/include/CGAL/Qt/CreateOpenGLContext.h
- Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp
- Linear_cell_complex/examples/Linear_cell_complex/CMakeLists.txt
- Linear_cell_complex/examples/Linear_cell_complex/linear_cell_complex_3_viewer_qt.h
- Mesh_3/demo/Mesh_3/src/CGAL_demo/Viewer.cpp
- Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Viewer.cpp
- Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/Viewer.h
- Polyhedron/demo/Polyhedron/Scene_item.cpp
- Three/include/CGAL/Three/Viewer_interface.h
- Triangulation_3/demo/Triangulation_3/Viewer.h
This is a fix for #756. It fixes memory leaks in the 3D demos.
> Three : Fix for 756

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Volume_plane.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Volume_plane_interface.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Volume_plane_thread.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Volume_planes_plugin.cpp
- Moved the item creation out of the threads so that the context is valid when their VAOs and VBOs are created.
> Polyhedron_demo Volume_plane fix 

- GraphicsView/include/CGAL/Qt/debug.h
- GraphicsView/include/CGAL/Qt/debug_impl.h
- Mesh_3/demo/Mesh_3/Volume_plane.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Volume_plane.h
- Surface_mesher/demo/Surface_mesher/polyhedral_surface.h
- Surface_mesher/demo/Surface_mesher/volume.cpp
- Surface_mesher/demo/Surface_mesher/volume.h
> Surface_mesher : Glu removal 

- GraphicsView/demo/Largest_empty_rect_2/Largest_empty_rectangle_2.cpp
- GraphicsView/demo/Periodic_2_triangulation_2/Periodic_2_Delaunay_triangulation_2.cpp
- GraphicsView/demo/Periodic_2_triangulation_2/TriangulationConflictZone.h
- GraphicsView/demo/Periodic_2_triangulation_2/TriangulationPointInputAndConflictZone.h
- GraphicsView/demo/Periodic_2_triangulation_2/include/CGAL/Qt/PeriodicTriangulationGraphicsItem.h
This PR fixes the QPen related problems in the GraphicsView 2D demos
> Graphics view demo pen fix

- GraphicsView/include/CGAL/Qt/CreateOpenGLContext.h
- Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp
This PR disables the MultiSampling AntiAliasing from the LCC demo to fix a bug on certain machines.
> Removal of the MSAA in LCC

- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/Polygon_offset_builder_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/Polygon_offset_builder_traits_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/Straight_skeleton_builder_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/Straight_skeleton_builder_traits_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/Straight_skeleton_converter_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/Straight_skeleton_face_base_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/Straight_skeleton_halfedge_base_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/Straight_skeleton_vertex_base_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/arrange_offset_polygons_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/compute_outer_frame_margin.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/create_offset_polygons_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/create_offset_polygons_from_polygon_with_holes_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/create_straight_skeleton_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/create_straight_skeleton_from_polygon_with_holes_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/PackageDescription.txt
> Straight skeleton 2: doc fixes

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Parameterization_plugin.cpp
- Surface_mesh_parameterization/doc/Surface_mesh_parameterization/PackageDescription.txt
- Surface_mesh_segmentation/doc/Surface_mesh_segmentation/PackageDescription.txt
Planar Parameterization of Triangulated Surfaces   ->  Triangulated Surface Mesh Parameterization
> Unify chapter names

- Triangulation_3/include/CGAL/Triangulation_3.h
this should even go into 4.7.1
> Accelerete 3D version of inexact_locate as we do it for 2D

- Nef_3/include/CGAL/Nef_3/SNC_external_structure.h
Patch for Plane_lt to recognise proportional planes as the same plane.
> Plane_3-Plane_lt-map-patch

- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
> Protect against inserting a zero length constraint 

- Triangulation/doc/Triangulation/Concepts/TriangulationDataStructure.h
- Triangulation/doc/Triangulation/PackageDescription.txt
- Triangulation/doc/Triangulation/Triangulation.txt
- Triangulation/doc/Triangulation/dependencies
> Fix typos and add a dependency

- Surface_mesher/demo/Surface_mesher/CMakeLists.txt
in order to fix the testsuite of the [Surface_mesher_demo](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-140/Surface_mesher_Demo/TestReport_lrineau_CentOS6-32.gz)
> Test for OPENGL_FOUND

- Polyhedron/demo/Polyhedron/Plugins/PCA/Create_bbox_mesh_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Triangulate_facets_plugin.cpp
Fixes the applicable() function :
- For create_bbox
- For triangulate_facets
> Polyhedron_demo : Fix applicable

- Polyhedron/demo/Polyhedron/Plugins/IO/GOCAD_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/Nef_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/OFF_to_xyz_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/PLY_to_xyz_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/Polylines_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/XYZ_io_plugin.cpp
Fix following this comment: https://github.com/CGAL/cgal/pull/823/files#r54407595
> Fix max precision for ofstream: digits10 + 2 instead of digits10 + 1

- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
> Polyhedron_demo : Fix for the polyhedron_item's colors

- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/Scene.h
> Polyhedron demo :  Fix reload item

- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
- Three/include/CGAL/Three/Scene_item.h
This is a fix for #773 : it makes the color of the facets of a selection_item editable.
> Polyhedron_demo : Fix for 773

- Periodic_2_triangulation_2/include/CGAL/internal/Static_filters/Periodic_2_orientation_2.h
- Periodic_2_triangulation_2/include/CGAL/internal/Static_filters/Periodic_2_side_of_oriented_circle_2.h
> Call init_double in Periodic_T2 static filters

- Triangulation/doc/Triangulation/Triangulation.txt
Add a small sentence saying Clément Jamin's work was supported by the Advanced Grant of the ERC GUDHI.
> dD Triangulations: update "Design and Implementation History" section (ERC GUDHI support)

- Installation/changes.html
The line in changes.html was not properly updated with the new name (cf https://github.com/CGAL/cgal/pull/804#issuecomment-198325289).
> Update name of 2D reconstruction in changes.html

- Documentation/doc/Documentation/Developer_manual/Chapter_portability.txt
> Update doc boost requirements 

- Maintenance/test_handling/testresult.css
Can we give this a try, to see if the table builds up faster?
[Source](https://css-tricks.com/fixing-tables-long-strings/)
Is this enough or does someone have to copy the file somewhere by hand?
> fix table layout of the result table

- BGL/include/CGAL/boost/graph/Euler_operations.h
> Forgot to set the halfedge of the face

- BGL/doc/BGL/Doxyfile.in
- BGL/doc/BGL/PackageDescription.txt
- BGL/doc/BGL/examples.txt
- BGL/dont_submit
- BGL/examples/BGL_surface_mesh/surface_mesh_dual.cpp
- BGL/include/CGAL/boost/graph/Dual.h
- BGL/test/BGL/CMakeLists.txt
- BGL/test/BGL/graph_concept_Dual.cpp
- BGL/test/BGL/graph_concept_OpenMesh.cpp
- BGL/test/BGL/graph_concept_Polyhedron_3.cpp
- BGL/test/BGL/graph_concept_Triangulation_2.cpp
- Installation/changes.html
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/BGL_Dual
Document the Dual class
> BGL: document Dual

- Surface_mesh_shortest_path/package_info/Surface_mesh_shortest_path/copyright.txt
- Surface_mesh_shortest_path/package_info/Surface_mesh_shortest_path/description.txt
- Surface_mesh_shortest_path/package_info/Surface_mesh_shortest_path/maintainer
> Shortest Path: update package info

- BGL/include/CGAL/boost/graph/properties_PolyMesh_ArrayKernelT.h
- BGL/include/CGAL/boost/graph/properties_TriMesh_ArrayKernelT.h
> BGL functions must be in OpenMesh namespace

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
This PR fixes the case where both faces incident to h are degenerate before the flip
and none of them is degenerate after the flip
it fixes issue #927
> PMP isotropic_remeshing : fix assertion failure

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/remeshing_test.cpp
> PMP : improve remeshing_test (bis)

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Scene_group_item.cpp
- Polyhedron/demo/Polyhedron/Scene_item.cpp
- Three/include/CGAL/Three/Scene_group_item.h
- Three/include/CGAL/Three/Scene_item.h
> Polyhedron_demo : Fix for the Ctrl+space shortcut

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
> Fix the point_set selection polylines.

- AABB_tree/demo/AABB_tree/CMakeLists.txt
- Alpha_shapes_3/demo/Alpha_shapes_3/CMakeLists.txt
- Circular_kernel_3/demo/Circular_kernel_3/CMakeLists.txt
- Mesh_3/demo/Mesh_3/CMakeLists.txt
- Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/CMakeLists.txt
- Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/CMakeLists.txt
- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/CMakeLists.txt
- Principal_component_analysis/demo/Principal_component_analysis/CMakeLists.txt
- Surface_mesher/demo/Surface_mesher/CMakeLists.txt
- Triangulation_3/demo/Triangulation_3/CMakeLists.txt
This PR Removes GLU from the CMakeLists of the Mesh_3 demo.
> Mesh_3 Demo : Removes GLU from the CMakeLists.txt

- Kernel_d/include/CGAL/Kernel_d/Iso_box_d.h
I did not run the tests because I don't know how, but I don't think that this change will break anything. Can you instruct me how to run the tests so that the build does not crash in case where the tests would fail? Thank you.
> Adding const to the rhs of equality check of Iso_box_d

- Polyhedron/demo/Polyhedron/Plugins/PMP/Self_intersection_plugin.cpp
Adds edges to the self_selection item.
> Polyhedron_demo : adding edges to the self selection item

- NewKernel_d/include/CGAL/NewKernel_d/LA_eigen/LA.h
- NewKernel_d/include/CGAL/NewKernel_d/function_objects_cartesian.h
> NewKernel_d solve check glisse

- Mesh_3/include/CGAL/IO/File_medit.h
- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/Time_stamper.h
- STL_Extension/include/CGAL/utility.h
- Triangulation_3/include/CGAL/Triangulation_3.h
> Accelerate vertex removal in a 3D triangulation and saving a mesh

- Surface_mesh_deformation/test/Surface_mesh_deformation/Cactus_deformation_session.cpp
- Surface_mesh_deformation/test/Surface_mesh_deformation/Cactus_deformation_session_OpenMesh.cpp
This should fix this [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-22/Surface_mesh_deformation/TestReport_jtournois_x64_Cygwin-Windows8_MSVC2015-Release-64bits.gz)
> static_cast to avoid warning

- Polyhedron/demo/Polyhedron/Plugins/PMP/Point_inside_polyhedron_plugin.cpp
This is a fix for #985 
Makes the last point_set made from BBox the default point_set if none is selected.
> Polyhedron_demo : Improvements for Points_set_inside_polyhedron

- Installation/changes.html
See the following comment: https://github.com/CGAL/cgal/pull/914/files/662efa2c8ee38b912a839d9658c6d7c75f1bfa23#r61916685
> Fix changes.html (item in 4.8 should be in 4.9)

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
This PR allows the display of the cells that are not in the complex in the c3t3_item.
> Polyhedron demo : display all cells in c3t3_item

- Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
- Polyhedron/demo/Polyhedron/Scene_implicit_function_item.cpp
- Polyhedron/demo/Polyhedron/Scene_implicit_function_item.h
fixes #970
- Makes use of singleShots instead of timerEvents.
> Polyhedron demo : Fix for busy waiting

- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
After isotropic remeshing of a mesh with selected edges, saving and loading of the mesh and the selection was not correct, as after the loading the edges are not in the same order as in the remeshed mesh.
> Store the indices of source and target of a selected edge

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.ui
- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/Scene.h
This PR fixes bugs from the hierarchy and the selection that were broken.
> Polyhedron demo : Multiple bug fixes

- Polyhedron/demo/Polyhedron/Plugins/IO/Implicit_function_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/Polylines_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/XYZ_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Polyhedron_stitching_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Repair_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Features_detection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_average_spacing_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_bilateral_smoothing_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_normal_estimation_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_outliers_removal_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_simplification_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_smoothing_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_upsampling_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_wlop_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Subdivision_methods/Subdivision_methods_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_segmentation_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Parameterization_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Shortest_path_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Polyhedron_demo_plugin_helper.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Three/include/CGAL/Three/Polyhedron_demo_plugin_helper.h
(fixes #1077)
This PR re-connects the disconnected actions in some plugins.
> Polyhedron demo : Re-connect plugins actions

- Boolean_set_operations_2/doc/Boolean_set_operations_2/CGAL/Boolean_set_operations_2.h
- Boolean_set_operations_2/doc/Boolean_set_operations_2/PackageDescription.txt
> fix link issues

- Kernel_d/doc/Kernel_d/CGAL/Kernel_d/Point_d.h
- Kernel_d/include/CGAL/Kernel_d/Point_d.h
This is a new commit to replace the pull request https://github.com/CGAL/cgal/pull/1074.
> Adding less-than operator (<) to Point_d

- Surface_mesh/examples/Surface_mesh/sm_properties.cpp
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
> Cast constness away as the function Surface_mesh::properties() is const

- Nef_S2/include/CGAL/Nef_S2/SM_checker.h
> Comment doc in code

- Surface_mesh_segmentation/doc/Surface_mesh_segmentation/Concepts/SegmentationGeomTraits.h
- Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/SDF_calculation.h
> AABB_Tree ignores degenerated faces in SDF_Calculation

- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item_k_ring_selection.h
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
This PR is the new #1099. It only keeps the useful fixes for the Selection_tool.
> Fix selection tool

- Polyhedron/demo/Polyhedron/MainWindow.cpp
This PR fixes a bug in the hierarchy.
> Polyhedron_demo : fix the context menu of the children of a group

- BGL/include/CGAL/boost/graph/copy_face_graph.h
> Document that vertex and face type must be Hashable

- Nef_3/include/CGAL/Nef_polyhedron_3.h
> handle isolated vertices in change_orientation

- Spatial_searching/include/CGAL/Kd_tree.h
- Spatial_searching/include/CGAL/Kd_tree_node.h
- Spatial_searching/include/CGAL/Orthogonal_incremental_neighbor_search.h
- Spatial_searching/include/CGAL/Orthogonal_k_neighbor_search.h
- Spatial_searching/test/Spatial_searching/Orthogonal_incremental_neighbor_search.cpp
- Spatial_searching/test/Spatial_searching/Orthogonal_k_neighbor_search.cpp
Fixes #953 
Highlight a regression introduced in CGAL 4.6 about  further neighbor search
> Make test correctly report errors

- BGL/examples/BGL_polyhedron_3/copy_polyhedron.cpp
- BGL/include/CGAL/boost/graph/graph_traits_PolyMesh_ArrayKernelT.h
- BGL/include/CGAL/boost/graph/graph_traits_TriMesh_ArrayKernelT.h
- STL_Extension/doc/STL_Extension/Concepts/Hashable.h
- STL_Extension/include/CGAL/hash_openmesh.h
> Add hash_value and specialization of hash for OpenMesh

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
We now consider that MESH halfedges are the ones that are not in the patch; i.e. not in the status map
halfedges with the MESH status are not used, apart from close to PATCH_BOUNDARY edges.
this speeds up the isotropic remeshing algorithm, in particular when only
a small patch is remeshed
> PMP isotropic_remeshing speedup. Don't use the MESH Halfedge_status

- Polyhedron/demo/Polyhedron/CMakeLists.txt
> Do not cache CGAL_THREE_SCENE_ITEM_H_PATH ; Simplify CMakeLists.txt

- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
- Add the connect() to the new_item_created() function so the loaded selection_items can work.
> Polyhedron_demo: Fix Selection_io_plugin

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane_intersection.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane_intersection.h
- Polyhedron/demo/Polyhedron/Scene.h
- Polyhedron/demo/Polyhedron/Viewer.cpp
This PR fixes some problems in the UI. It also fixes the picking for the whole demo.
> Polyhedron_demo : Fix gray images UI

- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
This PR fixes the Create_point_set_from_selection operation in the Selection tool.
> Polyhedron_demo : Fix the Create_point_set_from_selection operation

- Polyhedron/demo/Polyhedron/Plugins/PCA/Create_bbox_mesh_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Trivial_plugin.cpp
(fixes #1158 )
This PR fixes the Trivial_plugin and the Create_bbox_mesh_plugin.
> Polyhedron_demo : Fix bbox plugins

- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
This PR fixes errors base on multicolor items.
> Polyhedron_demo : Fix the multicolor_items

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Scene_polyhedron_shortest_path_item.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Shortest_path_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Shortest_path_widget.ui
This Pr :
- Changes the UI to make it more explicit.
- Put the items created by the plugin in a group_item
- Fixes the color of the points
> Polyhedron_Demo: Enhance Shortest Path Plugin

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane_intersection.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_polyhedron_transform_item.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_implicit_function_item.cpp
- Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
- Polyhedron/demo/Polyhedron/Scene_spheres_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- Polyhedron/demo/Polyhedron/Scene_textured_polyhedron_item.cpp
- Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
This PR fixes display bugs in some plugins like surface_reconstruction or affine_transformation.
> Polyhedron_demo: Fix the display

- Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
Fixes #1179
@Hippocrates comments welcome!
> Fix for source on edge

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Deform_mesh.ui
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h
This PR fixes some bugs in the Edit_polyhedron_plugin (fixes #1193, fixes #1194 and fixes #1197 ).
> Polyhedron_demo : Fix deformation

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_normal_estimation_plugin.ui
> Polyhedron_demo: Add spaces and change Dialog name.

- Polyhedron/demo/Polyhedron/Plugins/Point_set/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_interference_plugin.cpp
This PR proposes a new plugin that allows to create noise in a point set.
@afabri if this is what you wanted, please confirm this is OK for merging.
> Polyhedron_demo: Point_set_interference_plugin

- Polyhedron/demo/Polyhedron/Scene.cpp
> Polyhedron_demo: Fix the selection after reloading an item.

- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
This PR fixes #1232 .
It sets a maximum value for the normal lengths that is the average spacing of the points set.
> Polyhedron_demo: Fix the Normal Drawing

- AABB_tree/demo/AABB_tree/Scene.cpp
- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Color_ramp.cpp
- Polyhedron/demo/Polyhedron/Color_ramp.h
- Polyhedron/demo/Polyhedron/Plugins/AABB_tree/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_plane_item.cpp
- Polyhedron/demo/Polyhedron/Scene_plane_item.h
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h
This PR adds distance functions visualization to the Cut_plugin. This feature is taken from the AABB_Tree demo.
It also fixes #1228 .
> Polyhedron_Demo: Import AABB_Tree demo

- BGL/include/CGAL/boost/graph/copy_face_graph.h
> Add missing requirements

- Spatial_searching/doc/Spatial_searching/CGAL/Search_traits_2.h
- Spatial_searching/doc/Spatial_searching/CGAL/Search_traits_3.h
- Spatial_searching/doc/Spatial_searching/Concepts/RangeSearchTraits.h
The code is using Compute_* and the doc Construct_*, change the doc.
> Typo Construct_squared_radius_d

- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/doc/Kernel_23/PackageDescription.txt
- Kernel_23/include/CGAL/Kernel/global_functions_2.h
- Kernel_23/include/CGAL/Kernel/global_functions_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_vector_2.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_vector_3.h
We have  operator* and a kernel functor, but not the free function.
> Add free function scalar_product(Vector_{2,3}, Vector_{2,3})

- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- Polyhedron/demo/Polyhedron/triangulate_primitive.h
This PR fixes #1262 
Replacing the flat_maps used for the vertex normal map and the face normal map by another type of map fixes the problem.
> Polyhedron_demo: Fix reload item

- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
Fixes #1275 
This PR adds a slider to the Scene_points_with_normals_item's context menu that changes the normals length, if the item has normals.
> Polyhedron_demo: Editable normals length

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.cpp
This PR puts the point sets and polyhedrons generated by the shape_detection_plugin in sub-groups  so the results  are easier to deal with.
> Polyhedron_demo: sub-groups for shape detection

- README.md
- Scripts/developer_scripts/run_doxygen_testsuite
@afabri @sloriot Please review the patch
Current version at https://github.com/CGAL/cgal/blob/6390951138b817a43780f57c1103cb911f24ce73/README.md
> Add links: testsuite and documentation of `master`

- Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Convex_decomposition/Nef_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Convex_hull/Kernel_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/Implicit_function_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_2/Mesh_2_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Detect_sharp_edges_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Point_set_from_vertices_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Create_bbox_mesh_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Pca_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Transform_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Trivial_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Hole_filling_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Orient_soup_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Point_inside_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Polyhedron_slicer_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Self_intersection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Features_detection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Merge_point_sets_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_interference_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Scene_polyhedron_shortest_path_item.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
This is a fix for #1289 .
This PR adds WaitCursors where they were missing and fix possible bugs linked to the WaitCursors (WaitCursor when in a Dialog for example).
> Polyhedron_demo: Add wait cursors everywhere

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Features_detection_plugin.ui
Fix for issue https://github.com/CGAL/cgal/issues/1234
> Fix typo in VCM Feature Estimation plugin

- Polyhedron/demo/Polyhedron/Plugins/Convex_decomposition/Nef_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/GOCAD_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_upsampling_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_item.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
This PR fixes minor bugs detected in several plugins and segfaults that happened when using some specific operations from the context menu of an item.
> Polyhedron_demo: Fix for some plugins

- BGL/test/BGL/CMakeLists.txt
- BGL/test/BGL/graph_concept_Polyhedron_3.cpp
- BGL/test/BGL/graph_concept_Surface_mesh.cpp
During integration of the package the test has been disabled.
> enable concept checking for Surface_mesh

- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
This PR fixes #1282 
It adds lighting to the point set items if they have normals.
> Polyhedron_demo: Light for Point_set_items

- Polyhedron/demo/Polyhedron/Viewer.cpp
This PR fixes the 'Clibboard' typo in the Viewer.
> Polyhedron_demo : Typo fix.

- AABB_tree/doc/AABB_tree/Concepts/AABBTraits.h
- AABB_tree/doc/AABB_tree/dependencies
- Spatial_searching/doc/Spatial_searching/CGAL/Search_traits_2.h
- Spatial_searching/doc/Spatial_searching/CGAL/Search_traits_3.h
- Spatial_searching/doc/Spatial_searching/Concepts/SearchGeomTraits_2.h
- Spatial_searching/doc/Spatial_searching/Concepts/SearchGeomTraits_3.h
- Spatial_searching/doc/Spatial_searching/PackageDescription.txt
fixes #261 
this PR implements what is listed in the issue
@sloriot can you please check whether this PR is complete?
> Spatial_searching doc : Update Search_traits_3 requirements

- Optimal_transportation_reconstruction_2/demo/Optimal_transportation_reconstruction_2/CMakeLists.txt
- Optimal_transportation_reconstruction_2/include/CGAL/OTR_2/Reconstruction_triangulation_2.h
Fixes #965 and #939.
Did not go through the testsuite yet.
> 2 bug fixes for Optimal_transportation_reconstruction_2

- BGL/doc/BGL/graph_traits.txt
> Add doc for boost::graph_traits for OpenMesh

- Polyhedron/demo/Polyhedron/Plugins/Mesh_2/Mesh_2_plugin.cpp
* mark the domain when only calling CDT
* fix wrong coordinate of generated points
> Fix mesh 2 plugin

- Polyline_simplification_2/include/CGAL/Polyline_simplification_2/simplify.h
- Polyline_simplification_2/test/Polyline_simplification_2/simplify_polygon_test.cpp
- STL_Extension/include/CGAL/Modifiable_priority_queue.h
@afabri do you agree with the fix?
> Handle edges with undefined cost

- Installation/cmake/modules/CGAL_SetupBoost.cmake
> -ansi implies c++98 -> update script requirements of boost libraries

- Number_types/include/CGAL/CORE_BigFloat.h
- Number_types/include/CGAL/CORE_BigInt.h
- Number_types/include/CGAL/CORE_BigRat.h
- Number_types/include/CGAL/CORE_Expr.h
- Number_types/include/CGAL/Gmpfi.h
- Number_types/include/CGAL/Gmpfr.h
- Number_types/include/CGAL/Gmpq.h
- Number_types/include/CGAL/Gmpz.h
- Number_types/include/CGAL/Interval_nt.h
- Number_types/include/CGAL/Lazy_exact_nt.h
- Number_types/include/CGAL/MP_Float.h
- Number_types/include/CGAL/Mpzf.h
- Number_types/include/CGAL/Quotient.h
- Number_types/include/CGAL/Sqrt_extension/Eigen_NumTraits.h
> Number_types Eigen::NumTraits::Literal

- Number_types/doc/Number_types/CGAL/Lazy_exact_nt.h
- Number_types/include/CGAL/Lazy_exact_nt.h
> make relative precision thread local

- HalfedgeDS/include/CGAL/HalfedgeDS_iterator_adaptor.h
> HDS: No need for thread local storage as readonly

- Installation/changes.html
- TDS_2/doc/TDS_2/Concepts/TriangulationDataStructure_2.h
- TDS_2/include/CGAL/Triangulation_data_structure_2.h
- TDS_2/test/TDS_2/include/CGAL/_test_cls_tds_2.h
This pull request is for the small feature [Add function insert_in_hole to Triangulation_data_structure_2](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_function_insert_in_hole_to_Triangulation_data_structure_2). 
The last successful test in integration was with internal release CGAL-4.10-Ic-2.
> Triangulation data structure 2 insert in hole i iordanov

- Box_intersection_d/include/CGAL/Box_intersection_d/Box_d.h
- Box_intersection_d/include/CGAL/Box_intersection_d/segment_tree.h
- Installation/include/CGAL/atomic.h
> Box_intersection_d: Make variables thread local

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Meshing_dialog.ui
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
> Polyhedron demo: better display of c3t3 item

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.ui
> Polyhedron demo Shape Detection plugin: Increase max value for spinbox

- Mesh_3/test/Mesh_3/test_meshing_polyhedron.cpp
> Loosen the bounds in parallel mode

- Optimal_transportation_reconstruction_2/doc/Optimal_transportation_reconstruction_2/PackageDescription.txt
> Add link to demo to OTR2

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_rib_exporter_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Rib_dialog.ui
This PR imports the c3t3_rib_export_plugin from the Mesh_3 demo.
It seems to work, but I cannot find a way to visualize a rib file, so I am not sure.
> Polyhedron_demo: Import the c3t3_rib_export_plugin 

- Point_set_processing_3/include/CGAL/internal/Rich_grid.h
> PSP: No need for thread local storage as readonly

- Convex_hull_d/include/CGAL/Regular_complex_d.h
> Convex_hull_d: No need for thread local storage as readonly

- Snap_rounding_2/include/CGAL/Snap_rounding_2.h
> Snap_rounding: Make variables thread local

- Polynomial/include/CGAL/Polynomial/modular_gcd_utcf_pure_wang.h
> Polynomial:  Make variables thread local

- Nef_2/include/CGAL/Filtered_extended_homogeneous.h
- Nef_2/include/CGAL/IO/Nef_polyhedron_2_PS_stream.h
- Nef_2/include/CGAL/Nef_polynomial.h
Address the items that do not concern debugging and visualization in Issue #1381
> Nef_2: declare thread local, or const

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_wlop_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp
Fix for https://github.com/CGAL/cgal/issues/1520.
Tested locally.
> Polyhedron demo: bugfix unoriented normals

- Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
- Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/function_objects.h
- Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/internal/Cone_tree.h
- Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/internal/misc_functions.h
> Remove dependency to Polyhedron_3

- Installation/changes.html
- Scripts/scripts/cgal_create_cmake_script
> Enable C++14 by default in generated CMake scripts

- Kernel_23/doc/Kernel_23/CGAL/Circle_2.h
- Kernel_23/doc/Kernel_23/CGAL/Circle_3.h
- Kernel_23/doc/Kernel_23/CGAL/Direction_2.h
- Kernel_23/doc/Kernel_23/CGAL/Direction_3.h
- Kernel_23/doc/Kernel_23/CGAL/Iso_cuboid_3.h
- Kernel_23/doc/Kernel_23/CGAL/Iso_rectangle_2.h
- Kernel_23/doc/Kernel_23/CGAL/Line_2.h
- Kernel_23/doc/Kernel_23/CGAL/Line_3.h
- Kernel_23/doc/Kernel_23/CGAL/Plane_3.h
- Kernel_23/doc/Kernel_23/CGAL/Point_2.h
- Kernel_23/doc/Kernel_23/CGAL/Point_3.h
- Kernel_23/doc/Kernel_23/CGAL/Ray_2.h
- Kernel_23/doc/Kernel_23/CGAL/Ray_3.h
- Kernel_23/doc/Kernel_23/CGAL/Segment_2.h
- Kernel_23/doc/Kernel_23/CGAL/Segment_3.h
- Kernel_23/doc/Kernel_23/CGAL/Sphere_3.h
- Kernel_23/doc/Kernel_23/CGAL/Tetrahedron_3.h
- Kernel_23/doc/Kernel_23/CGAL/Triangle_2.h
- Kernel_23/doc/Kernel_23/CGAL/Triangle_3.h
- Kernel_23/doc/Kernel_23/CGAL/Vector_2.h
- Kernel_23/doc/Kernel_23/CGAL/Vector_3.h
- Kernel_23/doc/Kernel_23/Concepts/GeomObjects.h
> Replace 'see also' by 'has model' and 'models'

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h
> Fix a bug in isotropic remeshing when the range is empty

- Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
- Mesh_3/include/CGAL/make_mesh_3.h
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
> Mesh_3: fix issue #1501 - about degenerate cases in initialization

- Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
Angles < 45 deg (90 in theory) should be counted as terminal vertices of the sharp features graph.
otherwise protection may fail by refining protecting balls endlessly,
getting closer and closer to the input sharp angle
this bug was introduced by PR #1110
> Mesh_3 - deal with sharp angles inside input sharp features

- Kinetic_data_structures/include/CGAL/Polynomial/internal/GSL_numeric_solver.h
> Protect code that requires gsl

- Linear_cell_complex/doc/Linear_cell_complex/CGAL/import_from_polyhedron_3.h
- Linear_cell_complex/doc/Linear_cell_complex/CGAL/import_from_triangulation_3.h
> Add missing CGAL namespace

- Intersections_3/include/CGAL/Intersections_3/intersection_3_1_impl.h
See details in 875e92eb482481093c72d4422e8b39f5cdbdb688.
> Fix a bug in Intersect_3()(Plane_3, Segment_3)

- Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
This PR hugely speeds up the cut requests of the Cut_plugin.
> Polyhedron_demo: Fix the cut_plugin

- Nef_3/include/CGAL/Nef_3/SNC_indexed_items.h
> Nef_3: Make variables atomic

- Cone_spanners_2/include/CGAL/Cone_spanners_2/Plane_scan_tree.h
> Cone_spanners: No need for thread local storage as readonly

- Segment_Delaunay_graph_Linf_2/include/CGAL/Segment_Delaunay_graph_Linf_2/Segment_Delaunay_graph_Linf_hierarchy_2_impl.h
> SDG_linf_2: No need for thread local storage as readonly

- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Basic_predicates_C2.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Cartesian_converter.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Segment_Delaunay_graph_2_impl.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Segment_Delaunay_graph_hierarchy_2_impl.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Triangulation_face_base_with_edges_2.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/edge_list.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/in_place_edge_list.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_face_base_2.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_hierarchy_2.h
> SDG_2: No need for thread local storage as readonly

- BGL/doc/BGL/Doxyfile.in
- BGL/doc/BGL/PackageDescription.txt
- BGL/doc/BGL/dependencies
- BGL/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
- Installation/changes.html
- Nef_3/doc/Nef_3/CGAL/Nef_polyhedron_3.h
- Nef_3/doc/Nef_3/Nef_3.txt
- Nef_3/doc/Nef_3/dependencies
- Nef_3/doc/Nef_3/examples.txt
- Nef_3/examples/Nef_3/nef_3_to_surface_mesh.cpp
See the [small feature page](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/BGL-nef_to_pm)
TODO:
> Add a function to convert a Nef polyhedron to a polygon mesh

- Installation/changes.html
- Nef_3/doc/Nef_3/CGAL/Nef_polyhedron_3.h
- Nef_3/examples/Nef_3/surface_mesh_to_nef.cpp
- Nef_3/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h
- Nef_3/include/CGAL/Nef_polyhedron_3.h
- Nef_3/include/CGAL/normal_vector_newell_3.h
See the [small feature page](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Build_Nef_from_FaceGraph)
TODO:
> Add a Nef_3 constructor from a FaceGraph

- Circular_kernel_2/include/CGAL/Circular_kernel_2/Circular_arc_2.h
> Circular_kernel_2: Use thread local storage

- Number_types/include/CGAL/Counted_number.h
This solves one line in Issue #1387
> Number_types/Counted_number: Use atomic static variables

- Number_types/include/CGAL/GMP/Gmpzf_type.h
Addresses one item of Issue #1387
> Number_types / Gmpzf: make static variable thread local

- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/doc/Kernel_23/Concepts/Kernel.h
- Kernel_23/doc/Kernel_23/PackageDescription.txt
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/include/CGAL/Kernel/global_functions_3.h
- Kernel_23/include/CGAL/Kernel/global_functions_internal_3.h
- Kernel_23/include/CGAL/Kernel/interface_macros.h
- Mesh_3/include/CGAL/Mesh_3/dihedral_angle_3.h
- Mesh_3/include/CGAL/Mesh_3/vertex_perturbation.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/triangulate_hole_Polyhedron_3_no_delaunay_test.cpp
- Polygon_mesh_processing/test/Polygon_mesh_processing/triangulate_hole_Polyhedron_3_test.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Scale_space_surface_reconstruction_3_impl.h
- Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/Surface_mesh_segmentation.h
- Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrain_sharp_edges.cpp
> Add doc of functor class and concept corresponding to dihedral_angle()

- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Curve_pair_analysis_2.h
- CGAL_ImageIO/include/CGAL/ImageIO/gis_impl.h
- CGAL_ImageIO/include/CGAL/ImageIO/recline_impl.h
- CGAL_ipelets/demo/CGAL_ipelets/multi_delaunay.cpp
- GraphicsView/include/CGAL/Qt/GraphicsViewNavigation_impl.h
- Installation/include/CGAL/config.h
- Intersections_3/include/CGAL/Intersections_3/intersection_3_1_impl.h
- Mesh_3/include/CGAL/Mesh_3/Robust_intersection_traits_3.h
- QP_solver/include/CGAL/QP_models.h
- TDS_3/include/CGAL/Triangulation_data_structure_3.h
- Triangulation_2/include/CGAL/Delaunay_triangulation_2.h
- Triangulation_2/include/CGAL/Regular_triangulation_2.h
> Address the -Wimplicit-fallthrough warnings

- BGL/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
> Add missing include directive

- Arrangement_on_surface_2/include/CGAL/Arr_rat_arc/Rational_arc_d_1.h
Replace && with & as we do want to test a single bit
This should fix ##1593
> Arrangement_2: fix Continuous_rational_arc_d_1

- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Algebraic_real_d_1.h
> Use CGAL_assertion_code

- Periodic_2_triangulation_2/include/CGAL/Periodic_2_Delaunay_triangulation_2.h
> Periodic_2_triangulation_2: Make variables thread local

- Arithmetic_kernel/include/CGAL/GMPXX_arithmetic_kernel.h
- Arithmetic_kernel/test/Arithmetic_kernel/GMPXX_arithmetic_kernel.cpp
- Number_types/include/CGAL/Sqrt_extension/Sqrt_extension_type.h
- Number_types/include/CGAL/gmpxx.h
- Number_types/test/Number_types/root_of_2.cpp
> New GMPXX_arithmetic_kernel.

- AABB_tree/doc/AABB_tree/Concepts/AABBGeomTraits.h
- AABB_tree/doc/AABB_tree/Concepts/AABBTraits.h
- AABB_tree/include/CGAL/AABB_face_graph_triangle_primitive.h
- AABB_tree/include/CGAL/AABB_halfedge_graph_segment_primitive.h
- AABB_tree/include/CGAL/AABB_traits.h
- AABB_tree/include/CGAL/internal/AABB_tree/AABB_traversal_traits.h
- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
Fix documentation bugs, detected during the proper definition of the traits concept for #1578
> Various fix in requirements

- Nef_3/test/Nef_3/test_nef_3_io_EPEC.cpp
- Number_types/include/CGAL/mpq_class.h
- Number_types/test/Number_types/mpq_class.cpp
Hopefully the last piece before #1257.
> I/O for Lazy_exact_nt<mpq_class>

- Nef_3/include/CGAL/Nef_polyhedron_3.h
> Add missing include directives

- Installation/cmake/modules/CGALConfig_install.cmake.in
> Add a hardcoded fall back for the installation prefix

- Apollonius_graph_2/include/CGAL/Apollonius_graph_2/comparator_profiler.h
- Apollonius_graph_2/include/CGAL/Apollonius_graph_2/predicate_profiler.h
- Apollonius_graph_2/include/CGAL/Apollonius_graph_2/uncertain/Uncertain_vertex_conflict_2.h
- Apollonius_graph_2/include/CGAL/Hyperbola_ray_2.h
- Apollonius_graph_2/include/CGAL/Parabola_2.h
- Apollonius_graph_2/include/CGAL/Parabola_segment_2.h
- Apollonius_graph_2/include/CGAL/in_place_edge_list.h
This should fix Issue #1394.
Fix #1394.
> Apollonius_graph: make variables atomic

- Generator/doc/Generator/CGAL/Random.h
- Random_numbers/include/CGAL/Random.h
- Random_numbers/include/CGAL/Random_impl.h
This should fix Issue #1393
Fix #1393.
> Random_numbers: Make static variable thread local

- Installation/changes.html
- Point_set_processing_3/examples/Point_set_processing_3/remove_outliers_example.cpp
- Point_set_processing_3/include/CGAL/remove_outliers.h
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_outliers_removal_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_outliers_removal_plugin.ui
Pre-approved [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Improve_Outlier_Removal_API).
note: the small feature was pre-approved 2nd of November 2016.
> Point set processing: improve outlier removal API

- Arithmetic_kernel/test/Arithmetic_kernel/CMakeLists.txt
- CGAL_Core/examples/Core/CMakeLists.txt
> Fix a CMake warning in Core_Examples

- Segment_Delaunay_graph_Linf_2/include/CGAL/Segment_Delaunay_graph_Linf_2.h
This is a fix for the ipelets for Segment Delaunay graph under the L infinity metric which were not functioning before. The problem was that the L2 metric draw_dual_edge was used and as a result nothing was drawn in ipe.
I have checked the ipelets and now they work. The fix has also been tested in testsuite-Monday and testsuite-Tuesday: 
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.10-I-42.shtml
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.10-Ic-43.shtml
> Fix segment Delaunay graph L infinity ipelets that were drawing nothing

- BGL/doc/BGL/CGAL/Polyhedron_items_with_id_3.h
> Update doc of function that works only for polyhedron

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polygon_mesh.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/fair_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/refine_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_faces.h
> Use readable property map API

- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Algebraic_curve_kernel_2.h
- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Algebraic_real_d_1.h
- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Bitstream_descartes_E08_tree.h
- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Bitstream_descartes_rndl_tree.h
- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Bitstream_descartes_rndl_tree_traits.h
- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Shear_controller.h
- Algebraic_kernel_d/include/CGAL/RS/rs2_calls.h
> Algebraic_kernel_d: Make static variables thread local

- Surface_mesh_parameterization/include/CGAL/Win32_exception.h
> Surface_mesh_parameterization: static -> CGAL_STATIC_THREAD_LOCAL_VARIABLE

- Kernel_23/include/CGAL/Kernel/function_objects.h
`Construct_projected_point_3::operator()(Point_3, Triangle_3)` now
checks if the triangle is degenerated (actually it checks if its
supporting plane is degenerated). If it is, it falls back to
`operator()(Point_3, Segment_3)` with the segment that is equivalent to
the triangle. When using non-exact floating point numbers, it chooses
the edge of the triangle that has the biggest l-infinity length.
> fix Construct_projected_point_3 with degenerate triangles

- Polygon_mesh_processing/test/Polygon_mesh_processing/CMakeLists.txt
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
This should fix  the testcases with an ICE for Visual 2013
> Surface_mesh:  The get/put functions are not templated

- TDS_2/doc/TDS_2/Concepts/TriangulationDSFaceBase_2.h
Prefix with `CGAL::` in order to generate a link.
> TDS_2: Update TriangulationDSFaceBase_2.h

- Three/demo/Three/Example_plugin/Basic_item_plugin.cpp
- Three/demo/Three/Example_plugin/Basic_plugin.cpp
- Three/demo/Three/Example_plugin/Example_plugin.cpp
- Three/doc/Three/Three.txt
- Three/include/CGAL/Three/Scene_group_item.h
This PR updates the documentation of the package Three for the polyhedron_demo.
> Polyhedron_demo : update for the documentation

- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Arrangement_on_surface_2.txt
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/bgl_primal_adapter.cpp
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/conics.cpp
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/dcel_extension.cpp
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/dcel_extension_io.cpp
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/dual_lines.cpp
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/dual_with_data.cpp
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/overlay_unbounded.cpp
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/rational_functions.cpp
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/rational_functions_rational_coefficients.cpp
- Arrangement_on_surface_2/include/CGAL/Arr_default_overlay_traits.h
- Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_bounding_rational_traits.h
- Arrangement_on_surface_2/include/CGAL/Arr_segment_traits_2.h
- Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_global.h
- Arrangement_on_surface_2/include/CGAL/Arrangement_on_surface_2.h
- Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_conic_polycurve.cpp
- BGL/examples/BGL_arrangement_2/primal.cpp
- Boolean_set_operations_2/doc/Boolean_set_operations_2/Boolean_set_operations_2.txt
- Boolean_set_operations_2/examples/Boolean_set_operations_2/set_union.cpp
- Boolean_set_operations_2/include/CGAL/Polygon_set_2.h
This PR fixes some typos in comments and in the doc of the Arrangement_2 package.
> Fixed some typos in Arrangement_2

- Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
> Polyhedron demo, polylines items: fix the radius displayed in the menu

- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/doc/Kernel_23/Kernel_23.txt
> Fix intersection links

- AABB_tree/doc/AABB_tree/aabb_tree.txt
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Nef_3/doc/Nef_3/Nef_3.txt
- Surface_mesh_deformation/doc/Surface_mesh_deformation/Surface_mesh_deformation.txt
> Fix doc issues detected by recent doxygen

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
This PR restores Laurent's fix for  the antialiasing in the Scene_c3t3_item's grid.
> Polyhedron_demo: Fix the grid in c3t3_item

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
This PR fixes #1805:
- The color of the neighbor facet is now the one of the neighbor facet, not of the facet itself
- Use a set of cell_handle to check if a cell is already displayed.
> Polyhedron_demo : Fix the c3t3 intersection's display

- AABB_tree/examples/AABB_tree/AABB_ray_shooting_example.cpp
- AABB_tree/include/CGAL/internal/AABB_tree/AABB_ray_intersection.h
fixes #1822 and #1821 
cc @bo0ts Nice one ;)
> Fix a typo for computing the relative distance

- Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_widget.ui
This PR removes the temporary item in the point_set_selection_plugin and adds a select_box as a third way of selecting.
> Polyhedron_demo : Enhance point set selection plugin

- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
This PR fixes the Segfault that occurs when too many points are selected in a point set.
> Polyhedron_demo: Fix the point_set selection

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
See issue https://github.com/CGAL/cgal/issues/1828.
This is my proposal for the Issue template, PR template and CONTRIBUTING file. This is of course subject to criticism and modifications, feel free to comment below (also @lrineau and @sloriot, feel free to directly edit the files if you can think of any improvement).
For the CONTRIBUTING file (that users see when they click on "Guidelines for contributing" above the issue form), I just put a list of CGAL resources. Maybe we should add some text paragraphs to explain how it works, but we might end up copying-pasting the pages from [CGAL support](http://www.cgal.org/support.html).
> GitHub: prefill issues and pull requests

- Triangulation_2/doc/Triangulation_2/Triangulation_2.txt
- Triangulation_2/doc/Triangulation_2/examples.txt
- Triangulation_2/examples/Triangulation_2/terrain_with_info.cpp
that combines `Projection_traits` and `Vertex_with_info`.  It is a little bit tricky to get all template parameters right.
> Triangulation_2: Add an example 

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h
> PMP: Fix error in the ref manual of connected components functions

- Circular_kernel_2/include/CGAL/Circular_kernel_2/Intersection_traits.h
- Circular_kernel_2/include/CGAL/Circular_kernel_2/function_objects_polynomial_circular.h
- Circular_kernel_2/include/CGAL/Circular_kernel_2/internal_functions_on_line_arc_2.h
- Circular_kernel_2/include/CGAL/Circular_kernel_intersections.h
> Fix CK2::Interect_2

- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
This PR fixes the display of Surface_mesh_items and the computation time of Polyhedron_items.
* Fixes : #1865
> Polyhedron_demo: Fixes for master

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polygon_mesh.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/fair_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/refine_impl.h
Do not include and use `trace.h` from PSP in PMP
> remove dependancy to PSP

- Point_set_3/include/CGAL/Point_set_3.h
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
Fix bug in removed points in `Point_set_3` that resulted in a bug in the point set selection in Polyhedron demo.
* Affected package(s): `Point_set_3`, `Polyhedron` demo
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/1867
> Point set 3: bugfix points marked as removed

- Nef_3/include/CGAL/Nef_3/SNC_io_parser.h
> remove unused variable warnings

- Installation/changes.html
- Triangulation_3/doc/Triangulation_3/CGAL/link_to_face_graph.h
- Triangulation_3/doc/Triangulation_3/dependencies
fix the doc after review by @MoniqueTeillaud .
* Small Feature: [Convex_hull_3_FaceGraph](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Convex_hull_3_FaceGraph)
> Triangulation_3: Fix the doc of link_to_face_graph() 

- Installation/changes.html
- Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/bbox.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/clip.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/measures_test.cpp
- Polygon_mesh_processing/test/Polygon_mesh_processing/point_inside_helpers.h
free functions in CGAL have no dimension suffix
> Rename bbox_3 functions

- Documentation/doc/biblio/cgal_manual.bib
- Number_types/doc/Number_types/CGAL/leda_bigfloat.h
- Number_types/doc/Number_types/CGAL/leda_integer.h
- Number_types/doc/Number_types/CGAL/leda_rational.h
- Number_types/doc/Number_types/CGAL/leda_real.h
> Fix link to the Leda User Manual

- Operations_on_polyhedra/include/CGAL/intersection_of_Polyhedra_3.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
Fix a bug when using the internal API
> fix make_terminal()

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h
Make the function `stitch_borders()` resilient to non-manifold edges.
Such edges are simply ignored instead of making the algorithm crash.
> Make the function stitch_borders() resilient to non-manifold edges

- Documentation/doc/Documentation/Installation.txt
Minor fixes in the documentation about TBB installation
* Issue(s) solved (if any): fix #1326
> Fix TBB installation instructions in Manual

- .travis.yml
- .travis/build_package.sh
- .travis/build_polyhedron_demo.sh
- .travis/generate_travis.sh
- .travis/template.txt
Test all CGAL demos in travis.
* Affected package(s):None
* Issue(s) solved (if any): fix #1900
> Add tests for demos in travis

- Arrangement_on_surface_2/include/CGAL/Basic_sweep_line_2.h
_Fixed typos in the Basic_sweep_line_2 class_
* Affected package(s): Arrangement_on_surface_2
> Fixed typos in Basic_sweep_line_2

- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Trapezoidal_decomposition_2_impl.h
Remove an invalid if statement and precondition
* Affected package(s): Arrangement_2
* Issue(s) solved (if any): fix #1955 
cc @efifogel
> Fix precondition in Trapezoidal_decomposition_2

- TDS_2/doc/TDS_2/Concepts/TriangulationDSFaceBase_2.h
- TDS_2/doc/TDS_2/Concepts/TriangulationDSVertexBase_2.h
Small fixes in the doc.
* Affected package(s):  Triangulation_2
* Issue(s) solved (if any): fix #1987
> Triangulation_2: Add \cgalRefines and polish a little bit

- Polyhedron/demo/Polyhedron/Plugins/IO/Polylines_io_plugin.cpp
Makes the reading of polylines faster in the Polyhedron_demo
* Issue(s) solved (if any): fix #1963
> Fix polylines reading

- CGAL_Core/include/CGAL/CORE/BigFloat_impl.h
- CGAL_Core/include/CGAL/CORE/Expr.h
- CGAL_Core/include/CGAL/CORE/ExprRep.h
- CGAL_Core/include/CGAL/CORE/Expr_impl.h
- CGAL_Core/include/CGAL/CORE/poly/Curves.tcc
- CGAL_Core/include/CGAL/CORE/poly/Poly.tcc
> CGAL_Core: make it less verbose to fix #1915

- Kinetic_data_structures/include/CGAL/Tools/Log.h
> KDS: do not open /dev/null  Fix #1988

- Mesh_3/benchmark/Mesh_3/concurrency.cpp
- Mesh_3/include/CGAL/Mesh_3/Mesher_level.h
- Mesh_3/include/CGAL/Mesh_3/Worksharing_data_structures.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/config_mesh_3.h
- STL_Extension/include/CGAL/Spatial_lock_grid_3.h
- Triangulation_3/include/CGAL/Triangulation_3.h
- Change a few internal function/variable names for more clarity.
- Fix a bug: the work batches of the parallel version were not sorted by default.
- Clean-up some unused or commented code.
> Mesh_3: code improvements + bug fix

- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
As noted by @odevil, the documentation of the concept `CoplanarOrientation_3` had some issues. This PR fixes them.
> Improve documentation of concept CoplanarOrientation_3

- BGL/doc/BGL/graph_traits.txt
- Documentation/doc/biblio/cgal_manual.bib
- Geomview/doc/Geomview/Geomview.txt
Links were either outdated or wrong URLS
* for geomview
* for a BGL concept
More to come.
> Fix links detected with validator.w3.org

- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
- removes implementations in the doc of Surface_mesh
- Removes the code that were specific to the doc but in bounds CGAL_DOCUMENT_INTERNALS
* Issue(s) solved (if any): fix #889
> Clean-up Surface_mesh doc

- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
Add a warning box if the protected edegs are too long for the target length.
* Issue(s) solved (if any): fix #2033
> Polyhedron_demo: Fix Isotropic_remeshing_plugin

- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arrangement_2.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Concepts/ArrangementDcel.h
- Arrangement_on_surface_2/include/CGAL/Arr_dcel_base.h
- Arrangement_on_surface_2/include/CGAL/Arrangement_on_surface_2.h
- Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_spherical_removal.cpp
- Installation/changes.html
Add range support for the arrangement DCEL.
It is not ready, as we have to discuss if we want to add range support for triangulations as well.
* Issue(s) solved (if any): fix #1625 
* Feature/Small Feature (if any): [here](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Range_Support_for_2D_Arrangements)
> Add range support for some CGAL concepts.

- Polygon_mesh_processing/include/CGAL/Side_of_triangle_mesh.h
> Add implementation details

- Polyhedron/demo/Polyhedron/Plugins/PMP/Corefinement_plugin.cpp
> Restore cursor if operation is not possible

- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Cone.h
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Octree.h
* Affected package(s): Point_set_shape_detection
* Issue(s) solved (if any): fix #2110
> Point_set_shape_detection: Remove unused variables

- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h
Add the genus in the statistics of a closedpolyhedorn item.
* Issue(s) solved (if any): fix #1770
> Add genus for closed polyhedra.

- Combinatorial_map/doc/Combinatorial_map/Combinatorial_map.txt
Following Mike Bliudze comment on cgal-edboard.
Mathematical definition of CMap in user manual.
* Affected package(s): CMap
> Update cmap definition

- Mesh_3/include/CGAL/Compact_mesh_cell_base_3.h
- Mesh_3/include/CGAL/Labeled_image_mesh_domain_3.h
- Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h
- Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
- Mesh_3/include/CGAL/Mesh_cell_base_3.h
- Mesh_3/include/CGAL/Mesh_vertex_base_3.h
- Mesh_3/test/Mesh_3/test_meshing_polyhedron.cpp
- Mesh_3/test/Mesh_3/test_meshing_utilities.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orient_polygon_soup.h
- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/Time_stamper.h
- STL_Extension/test/STL_Extension/test_Compact_container.cpp
This PR introduces small improvements that we have recently made to the `Mesh_3` package, ranging from small bug fixes to time and memory footprint improvement.
* Affected package : Mesh_3
> Mesh 3 : small improvements

- Alpha_shapes_3/demo/Alpha_shapes_3/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Alpha_shape_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Alpha_shape_widget.ui
- Polyhedron/demo/Polyhedron/Plugins/Point_set/CMakeLists.txt
- Add a specific alpha_shape item and an alpha_shape_plugin.
- Add a creation of polygon_soup from alpha_shape_item
* Issue(s) solved (if any): partially fix #2038
> Polyhedron_demo: Add an Alpha_shape_plugin

- Polygon/include/CGAL/Polygon_2.h
> Update documentation of Polygon_2.h

- Linear_cell_complex/doc/Linear_cell_complex/CGAL/Polyhedron_3_to_lcc.h
Remove duplicated lines in doc import_from_polyhedron_3
* Affected package(s): Linear_cell_complex
> Bug fix in doc

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.cpp
- Polyhedron/demo/Polyhedron/Polyhedron_demo.cpp
- Polyhedron/demo/Polyhedron/Scene_group_item.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
- Polyhedron/demo/Polyhedron/Viewer.cpp
- Fix point set visualization on mac
- Fix Point_set_shape_detection_plugin
- Enhance the display of the axis system
- Workaround for focus problem on mac
* Issue(s) solved (if any): fix #2128
> Polyhedron demo: Fixes and enhancements

- Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h
- Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h
- Polyhedron/demo/Polyhedron/MainWindow.cpp
Two small patches, for Mesh_3, and for the 3D demo.
* Affected package(s): Mesh_3, Polyhedron_Demo
* Issue(s) solved (if any): fix CGAL/GeometryFactory#6
> Mesh 3: small fixes

- Triangulation_3/demo/Triangulation_3/MainWindow.cpp
- Triangulation_3/demo/Triangulation_3/MainWindow.ui
- Triangulation_3/demo/Triangulation_3/T3_demo.qrc
- Remove deprecated code in MainWindow.cpp
- Fix paths for about.html and about_CGAL.html
* Affected package(s):Triangulation_3_demo
> Fix Triangulation_3_demo

- .travis/build_package.sh
This PR Uses an older version of qglviewer as travis doesn't have a qt version recent enough to work with master.
> Fix qglviewer compilation in travis

- .travis.yml
- .travis/build_package.sh
- .travis/template.txt
Update Travis to use clang-3.6 instead of the default clang-3.5
Replaces #2157.
@maxGimeno Can you try to fix that PR (... once the Qt5/libQGLViewer issue is solved) ?
> Try clang-3.6 with Travis

- Combinatorial_map/include/CGAL/Combinatorial_map.h
- Generalized_map/include/CGAL/Generalized_map.h
Remove return since copy is a procedure (does not return anything).
(why this code compile ? strange...)
* Affected package(s): CMap and GMap
> Bug fix in CMap and GMap copy functions.

- .travis/build_package.sh
- Polyhedron/demo/Polyhedron/Plugins/PMP/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
The isotropic_remeshing_plugin can work with Scene_surface_mesh_items
This PR is based on #1983
* Issue(s) solved (if any): fix #1931
> Isotropic_ remeshing_plugin use SM

- .travis/build_package.sh
- Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_sgm.cpp
Fix the test Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_sgm.cpp, introduced by #2061.
* Affected package(s):Arrangement_on_surface_2
* Issue(s) solved (if any): fix #2171
> Arr_2: fix test_sgm.cpp

- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
Fix ambiguity between two constructors.
* Affected package(s):BGL
> BGL : Fix ambiguity between Face_filtered_graph constructors.

- AABB_tree/include/CGAL/AABB_face_graph_triangle_primitive.h
update a sentence that we forgot to update
> Aabb tree doc update

- Surface_mesh_simplification/doc/Surface_mesh_simplification/Surface_mesh_simplification.txt
> Surface_mesh_simplification:  Fix in User Manual

- Arrangement_on_surface_2/include/CGAL/Arr_spherical_gaussian_map_3/Arr_polyhedral_sgm_initializer_visitor.h
- Arrangement_on_surface_2/include/CGAL/Arr_spherical_gaussian_map_3/Arr_polyhedral_sgm_overlay.h
- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Arc_2.h
- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Point_2.h
- Interpolation/include/CGAL/Voronoi_intersection_2_traits_3.h
See for example [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.11-I-50/Arrangement_on_surface_2/TestReport_lrineau_Fedora-strict-ansi.gz)
> fix unused variable warnings

- .travis/build_package.sh
- BGL/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
- Nef_3/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h
- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Convex_decomposition/Nef_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.h
The Nef_plugin works with surface_mesh_items
This PR is based on #1954 
> convex decomposition work with Surface_mesh_item

- .travis/build_package.sh
- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Algebraic_curve_kernel_2.h
- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/univariate_polynomial_utils.h
- Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_impl.h
- Kinetic_data_structures/include/CGAL/Polynomial/internal/Filtered_kernel/Filtered_sign_at.h
- Operations_on_polyhedra/include/CGAL/internal/corefinement/predicates.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Side_of_triangle_mesh/Ray_3_Triangle_3_traversal_traits.h
- Polynomial/include/CGAL/Polynomial/Polynomial_type.h
- Scale_space_reconstruction_3/include/CGAL/Scale_space_surface_reconstruction_3.h
Quality calls to sign to avoid ambiguity
* Issue(s) solved (if any): fix #2187
> Quality calls to sign

- Arrangement_on_surface_2/test/Arrangement_on_surface_2/cgal_test.cmake
- Arrangement_on_surface_2/test/Arrangement_on_surface_2/cgal_test_base
The fix is not perfect has it only checks for GMP presence but it will fix the testsuite.
> Fix testsuite when GMP is not present

- AABB_tree/demo/AABB_tree/MainWindow.cpp
- AABB_tree/demo/AABB_tree/Scene.h
- AABB_tree/demo/AABB_tree/Viewer.h
- Alpha_shapes_3/demo/Alpha_shapes_3/Viewer.h
- Circular_kernel_3/demo/Circular_kernel_3/Viewer.h
- Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp
- Linear_cell_complex/demo/Linear_cell_complex/Viewer.h
- Linear_cell_complex/examples/Linear_cell_complex/linear_cell_complex_3_viewer_qt.h
- Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Viewer.h
- Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/MainWindow.cpp
- Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/Viewer.h
- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Scene_facegraph_item_k_ring_selection.h
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item_k_ring_selection.h
- Principal_component_analysis/demo/Principal_component_analysis/MainWindow.cpp
- Principal_component_analysis/demo/Principal_component_analysis/Viewer.h
- Surface_mesher/demo/Surface_mesher/viewer.h
- Surface_mesher/demo/Surface_mesher/volume.cpp
- Three/include/CGAL/Three/Viewer_interface.h
- Triangulation_3/demo/Triangulation_3/Scene.h
- Triangulation_3/demo/Triangulation_3/Viewer.cpp
- Triangulation_3/demo/Triangulation_3/Viewer.h
Rework for everything that uses qglviewer so it is not broken by the version 2.7.0.
* Affected package(s): All 3D Demos
> Fix demos for qglviewer 2.7.0

- Arrangement_on_surface_2/include/CGAL/Arr_spherical_gaussian_map_3/Arr_spherical_gaussian_map_3.h
- Arrangement_on_surface_2/test/Arrangement_on_surface_2/cgal_test.cmake
Fix warnings about unused parameters, introduced by the PR #2061.
* Affected package(s): Arrangement
> Arr_2: fix warnings

- Operations_on_polyhedra/include/CGAL/internal/corefinement/Combinatorial_map_output_builder.h
Fixes  https://github.com/Oslandia/SFCGAL/issues/142
> Fix wrong include directive

- AABB_tree/demo/AABB_tree/MainWindow.cpp
- AABB_tree/demo/AABB_tree/Scene.h
- AABB_tree/demo/AABB_tree/Viewer.h
- Alpha_shapes_3/demo/Alpha_shapes_3/Viewer.h
- Circular_kernel_3/demo/Circular_kernel_3/Viewer.h
- Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp
- Linear_cell_complex/demo/Linear_cell_complex/Viewer.h
- Linear_cell_complex/examples/Linear_cell_complex/linear_cell_complex_3_viewer_qt.h
- Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Viewer.h
- Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/MainWindow.cpp
- Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/Viewer.h
- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item_k_ring_selection.h
- Principal_component_analysis/demo/Principal_component_analysis/MainWindow.cpp
- Principal_component_analysis/demo/Principal_component_analysis/Viewer.h
- Surface_mesher/demo/Surface_mesher/viewer.h
- Surface_mesher/demo/Surface_mesher/volume.cpp
- Three/include/CGAL/Three/Viewer_interface.h
- Triangulation_3/demo/Triangulation_3/Scene.h
- Triangulation_3/demo/Triangulation_3/Viewer.cpp
- Triangulation_3/demo/Triangulation_3/Viewer.h
Apply the fixes of #2213  for 4.10
* Affected package(s):3D demos
Fix #2223.
> Fix 3D demos for 4.10

- .travis/build_package.sh
- Documentation/doc/scripts/test_doxygen_versions.sh
- Documentation/doc/scripts/testsuite.py
- Interpolation/include/CGAL/Voronoi_intersection_2_traits_3.h
Fix a path and add post processing in the doc testsuite
> Post processing for doc testsuite

- Installation/changes.html
- Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Alpha_shape_mesher.h
Fixes the two remaining issues from [the original PR](https://github.com/CGAL/cgal/pull/2159):
* cleans up commented pieces of code
* adds a section to `changes.html`
* Affected package(s): Scale Space Reconstruction
> Scale space reconstruction: improve API cleanup

- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Parameterization_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_textured_surface_mesh_item.cpp
- Polyhedron/demo/Polyhedron/Scene_textured_surface_mesh_item.h
Parameterization_plugin also works with sm_items and selection.
> Polyhedron_demo: Add a surface_mesh version of the Parameterization_plugin

- Polyhedron/demo/Polyhedron/Plugins/Subdivision_methods/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Subdivision_methods/Subdivision_methods_plugin.cpp
Subdivisions_methods_plugin works with surface_mesh_items.
> Polyhedron_demo: Make subdivisions_methods_plugin work with surface_mesh_items

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h
`PolygonMesh` -> `TriangleMesh`
> Polygon_mesh_processing: fix doc

- Polyhedron/demo/Polyhedron/Plugins/Convex_decomposition/Nef_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Convex_hull/Kernel_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Edit_box_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.ui
- Polyhedron/demo/Polyhedron/Plugins/PMP/Point_inside_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Self_intersection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.ui
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_segmentation_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_segmentation_widget.ui
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Scene_polyhedron_shortest_path_item.cpp
- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
- Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h
- Polyhedron/demo/Polyhedron/Scene_textured_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/resources/about.html
This PR renames some actions, capitalizes some text and fixes some problems, among which :
-  aabb_tree_items are not created with every new item when there is no cutting plane anymore
- Selection reducing/expanding works with Selection_SM_items 
* fixes #2222
> Polyhedron_demo: Fixes 

- Poisson_surface_reconstruction_3/doc/Poisson_surface_reconstruction_3/Poisson_surface_reconstruction_3.txt
(reported by Ross)
chick -> cheek
> fix language mistake in the user manual

- Mesh_3/include/CGAL/Mesh_3/experimental/Sizing_field_with_aabb_tree.h
> Mesh 3: fix sizing field with aabb tree

- QP_solver/include/CGAL/QP_models.h
Applying mglisse's fix proposal. 
* Affected package(s): QP_Solver
* Issue(s) solved (if any): fix #2283
> Fix QP_Solver tests with no GMP

- Nef_S2/include/CGAL/Nef_S2/Sphere_circle.h
* Affected package: Nef_S2
* Issue solved: fix #2187
> Qualify call to CGAL::sign.

- Surface_mesh_parameterization/doc/Surface_mesh_parameterization/Surface_mesh_parameterization.txt
> Surface mesh parameterization: typo fix

- Documentation/doc/CMakeLists.txt
* Issue(s) solved (if any): fix #2292
> Handle deprecation of DOXYGEN_EXECUTABLE in FindDoxygen

- Polyhedron/demo/Polyhedron/Plugins/PMP/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/PMP/Fairing_plugin.cpp
This PR makes the  Fairing_plugin able to handle Scene_surface_mesh_items.
* Issue(s) solved (if any): fix #2271
> Polyhedron_demo: Fairing_plugin for SM

- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp
Replace the last updateGL() call by update().
* Issue(s) solved (if any): fix #2300
> Polyhedron_demo: Fix remaining ArchLinux compilation error

- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
Fix next/prev for `Face_filtered_graph` as well as the change of selected faces.
> Fix Face_filtered_graph bugs

- Convex_hull_3/examples/Convex_hull_3/CMakeLists.txt
- Convex_hull_3/examples/Convex_hull_3/quickhull_OM_3.cpp
> Convex_hull_3: Fix OpenMesh example

- Triangulation_2/include/CGAL/Triangulation_2.h
> Fix Triangulation_2::circumcenter in the regular case

- .travis.yml
- .travis/build_package.sh
- .travis/generate_travis.sh
- .travis/template.txt
This PR makes our travis config use Qt 5.5.
fixes #2323
> Travis uses qt-5.5

- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
Fix for the selected points that are not displayed if the current item is not the first in the list.
> Polyhedron_demo: Fix selected points display

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
Add color to the status text so it is more visible. The status is the text displayed at the bottom of the mainWindow, which is also written in the console widget.
> Polyhedron_demo: Add visibility to the status messages

- Documentation/doc/biblio/cgal_manual.bib
- Surface_mesh_simplification/examples/Surface_mesh_simplification/CMakeLists.txt
- Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_bounded_normal_change.cpp
The new code was not tested as the example testing it was not compiled (not in the cmake script).
> Test and fix PR 2193

- Polyhedron/demo/Polyhedron/include/CGAL/statistics_helpers.h
This corrects a possible copy-paste error in the demo statistics.
> Polyhedron demo: minor fix in statistics

- Documentation/doc/scripts/html_output_post_processing.py
- INSTALL.md
- README.md
> Use https in canonical links

- Point_set_processing_3/doc/Point_set_processing_3/PackageDescription.txt
- Point_set_processing_3/doc/Point_set_processing_3/Point_set_processing_3.txt
Add Florent and Simon as author of the structuring function
> Point Set Processing: Add authors

- Point_set_shape_detection_3/examples/Point_set_shape_detection_3/plane_regularization.cpp
- Point_set_shape_detection_3/examples/Point_set_shape_detection_3/shape_detection_basic.cpp
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Efficient_RANSAC.h
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Region_growing.h
- Polyhedron/demo/Polyhedron/Plugins/IO/PLY_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.cpp
Two fixes for the demo:
* removing typenames that produce errors on Windows in shape detection plugin
* adding a wait cursor when loading PLY files
> Polyhedron demo: PLY and region growing fixes

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
Fixes the intersction visibility in the c3t3_item.
* Issue(s) solved (if any): fix #2353
> Polyhedron demo: Fix the c3t3 tets visibility.

- Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
Add sorting criteria to the output list of splitted polyhedra.
* Issue(s) solved (if any): fix #2363
> Polyhedron demo: Sort split_polyhedra output by increasing number of faces.

- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt
Remove or rename problematic files in CMakeLists.txt
* Issue(s) solved (if any): fix #2387
> Polyhedron_demo: Fix CmakeLists.txt

- Polyhedron/demo/Polyhedron/Plugins/Subdivision_methods/Subdivision_methods_plugin.cpp
> Fix incorrect labels

- Surface_mesh_deformation/doc/Surface_mesh_deformation/Surface_mesh_deformation.txt
> Use https links

- Polyhedron/demo/Polyhedron/Plugins/Subdivision_methods/Subdivision_methods_plugin.cpp
Add a dialog to choose the number of iterations in subdivisions_plugin
* Issue(s) solved (if any): fix #2403
> Polyhedron demo: Subdivisions_plugin

- Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt
> Polyhedron demo: Fix CmakeLists.txt (cont.)

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
Set the shrinking cursor value after setting its maximum.
* Issue(s) solved (if any): fix #2418
> Polyhedron demo: Fix shrinking in c3t3

- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
Fixes multicolor rendering in Polyhedron_item.
* Issue(s) solved (if any): fix #2421
> Polyhedron demo: Fix for Color Connected Components in polyhedron mode

- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
Add missing parenthesis at offset addition.
* Issue(s) solved (if any): fix #2433
> Polyhedron demo: Fix float conversion at buffer filling in SM item

- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Error was appearing in case Surface_mesh.h was included in *.mm file.
OS: MacOS
> Fix for compilation conflict on macOS.

- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/resources/shader_flat.g
- Polyhedron/demo/Polyhedron/resources/shader_flat.v
Fix orientation of facets in modern flat
* Issue(s) solved (if any): fix #2423
> Polyhedron demo: Fix polyhedron orientation errors

- Polyhedron/demo/Polyhedron/resources/shader_flat.f
- Polyhedron/demo/Polyhedron/resources/shader_flat.g
- Polyhedron/demo/Polyhedron/resources/shader_flat.v
Add clipbox management in flat_shader.
* Issue(s) solved (if any): fix #2440
> Polyhedron demo: Fix the Clipping Box Plugin

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h
- Polyhedron/demo/Polyhedron/Scene.cpp
This fixes the re-applying of the transformation to the control groups and makes the fixe plane transparent.
* Issue(s) solved (if any): fix #2076, #2035
> Polyhedron demo: Fix for transformation plugin 

- Polyhedron/demo/Polyhedron/Plugins/PMP/Degenerated_faces_plugin.cpp
Restore cursor before the pop-up if nothing is found and make degenerated degenerate in UI text.
* Issue(s) solved (if any): fix #2511
> Polyhedron demo: Trivial fix on degenerated_faces_plugin

- Documentation/doc/Documentation/Installation.txt
> Remove ambiguous sentence

- Polyhedron/demo/Polyhedron/Plugins/PMP/Hole_filling_plugin.cpp
Add the missing reference.
* Issue(s) solved (if any): fix #2487
> Polyhedron demo: Fix hole filling plugin

- Surface_mesh_segmentation/include/CGAL/internal/auxiliary/graph.h
The main issue was that macros defined in a third party header distributed with CGAL was not undefined. I renamed those macros and undef them. I also removed one of them.
> Fix compilation issue with boost 1.65

- Documentation/doc/CMakeLists.txt
* Affected package(s): Documetntation
* Issue(s) solved (if any): fix #2460
> Set CGAL version when building doc alone

- Polyhedron/demo/Polyhedron/Plugins/Display/Display_property.ui
- Polyhedron/demo/Polyhedron/Plugins/Display/Display_property_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
- Polyhedron/demo/Polyhedron/include/id_printing.h
Add buttons for zooming to extrema faces in the Display_properties_plugin.
fixes #2507
> Polyhedron_demo: Display_plugin can zoom to extrema

- Polyhedron/demo/Polyhedron/resources/shader_c3t3_spheres.v
- Polyhedron/demo/Polyhedron/resources/shader_instanced.v
Fix the instanced vertex shaders : the ModelView matrix was applied to vertex instead of the modified value of vertex.
* Issue(s) solved (if any): fix #2472
> Polyhedron demo: Fix instanced vertex shaders.

- Mesh_2/include/CGAL/Mesh_2/Refine_edges.h
- Polyhedron/demo/Polyhedron/Plugins/PMP/Corefinement_plugin.cpp
- Polyhedron/demo/Polyhedron/Polyhedron_type.h
- Polyhedron/demo/Polyhedron/include/CGAL/Polyhedron_kernel.h
- Triangulation/include/CGAL/Regular_triangulation.h
Fix some fall through warnings + uninitialized variables warnings.
> Fix some warnings 

- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
Replace the halfedge_is_feature_map by a edge_is_feature_map in the item to fit the real map.
> Polyhedron demo: Fix for detect_sharp_edges_sm_plugin

- Polyhedron/demo/Polyhedron/MainWindow.cpp
Remove unwanted duplicated incrementation.
> Polyhedron demo: Fix statistics exportation

- Polyhedron/demo/Polyhedron/Plugins/IO/STL_io_plugin.cpp
- Polyhedron_IO/include/CGAL/IO/STL_writer.h
Add a STL writer in the IO plugin (binary and ASCII)
> Add STL writer

- Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_plugin.cpp
Move the menu addition to file after the creation of its actions and add a mnemonic. This way, the menu should not appear as empty anymore.
> Polyhedron demo: Fix for Basic_generator _plugin

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h
Add an action to make the point item unicolor if it isn't.
* Issue(s) solved (if any): fix #2481
> Polyhedron demo: Make point_item unicolor.

- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
Apply collect_garbage() algorithm to the constrained_edges_map to keep the values correct.
> Polyhedron demo: Fix Isotropic_remeshing_sm_plugin

- Documentation/doc/scripts/test_doxygen_versions.sh
> Make testsuite build release docs

- Polyhedron/demo/Polyhedron/Plugins/Display/Display_property_plugin.cpp
Initialize variables to silence warnings.
> Polyhedron demo: Silence warnings in Display_property_plugin

- Documentation/doc/scripts/test_doxygen_versions.sh
- Documentation/doc/scripts/testsuite.py
Add some information about the generation script at the end of theOverviewpage of the Doxygen Manual Testsuite page.
* Issue(s) solved (if any): fix #2553
> Add info at the end of the generated overview page

- Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_widget.ui
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
This PR fixes
- the orientation of the hexadron in the basic_generator plugin
- the Ids removal of the scene_surface_mesh_item in the destructor.
> Polyhedron demo: minor fixes

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/refine_impl.h
> Turn some #ifndef that should be #ifdef

- Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
- Mesh_3/include/CGAL/internal/Mesh_3/Graph_manipulations.h
*TODO*
_Describe what your pull request changes to CGAL (this can be skipped if it solves an issue already in the tracker or if it is a Feature or Small Feature submitted to the CGAL Wiki)._
> Mesh 3: improve polylines_to_protect()

- Combinatorial_map/include/CGAL/Combinatorial_map_operations.h
- Combinatorial_map/include/CGAL/Combinatorial_map_save_load.h
- Combinatorial_map/include/CGAL/Combinatorial_map_storages.h
- Generalized_map/include/CGAL/Generalized_map_storages.h
- Linear_cell_complex/demo/Linear_cell_complex/MainWindow.cpp
- Linear_cell_complex/demo/Linear_cell_complex/MainWindow.h
- Linear_cell_complex/demo/Linear_cell_complex/MainWindow.ui
- Linear_cell_complex/examples/Linear_cell_complex/CMakeBasicViewerQt.inc
- Linear_cell_complex/examples/Linear_cell_complex/CMakeLists.txt
- Linear_cell_complex/examples/Linear_cell_complex/basic_viewer.h
- Linear_cell_complex/examples/Linear_cell_complex/linear_cell_complex_3_operations.cpp
- Linear_cell_complex/examples/Linear_cell_complex/linear_cell_complex_3_viewer_qt.h
- Linear_cell_complex/examples/Linear_cell_complex/voronoi_2.cpp
- Linear_cell_complex/examples/Linear_cell_complex/voronoi_3.cpp
- Linear_cell_complex/include/CGAL/CMap_linear_cell_complex_storages.h
- Linear_cell_complex/include/CGAL/GMap_linear_cell_complex_storages.h
Several small bug fixes in CMap/GMap/LCC packages.
* Affected package(s): CMap, GMap, LCC
> CMap bugfixes

- .travis.yml
- .travis/build_package.sh
- .travis/packages.txt
- .travis/template.txt
- Installation/cmake/modules/CGAL_Macros.cmake
Use make install in travis and change CGAL_DIR to /usr/local
> Test make install in travis

- Polygon_mesh_processing/include/CGAL/polygon_mesh_processing.h
> Add missing directive

- Convex_hull_3/include/CGAL/Convex_hull_3/dual/halfspace_intersection_3.h
- Convex_hull_3/include/CGAL/Convex_hull_3/dual/halfspace_intersection_with_constructions_3.h
Code was using `add_vertex(pt,graph)` while it is not required by the concept
> Use documented API

- BGL/doc/BGL/Concepts/HalfedgeGraph.h
Improve the visibility of an important invariant
> Re-add an invariant in the concept doc

- Arrangement_on_surface_2/include/CGAL/Arr_geodesic_arc_on_sphere_traits_2.h
- Boolean_set_operations_2/benchmark/Boolean_set_operations_2/polygon_set_2_join.cpp
- Filtered_kernel/include/CGAL/Epic_converter.h
- Filtered_kernel/include/CGAL/Lazy_kernel.h
- Filtered_kernel/include/CGAL/Static_filtered_predicate.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Compare_squared_radius_3.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Do_intersect_2.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Do_intersect_3.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Orientation_2.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Orientation_3.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Side_of_oriented_circle_2.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Side_of_oriented_sphere_3.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Static_filters.h
- Kernel_23/include/CGAL/Exact_predicates_exact_constructions_kernel.h
- Kernel_23/include/CGAL/Kernel/Type_mapper.h
- Nef_S2/include/CGAL/Nef_S2/Sphere_circle.h
- Nef_S2/include/CGAL/Nef_S2/Sphere_segment.h
- Partition_2/include/CGAL/Partition_2/Indirect_edge_compare.h
- Partition_2/include/CGAL/Partition_2/Indirect_not_less_yx_2.h
- Partition_2/include/CGAL/Partition_2/Partition_opt_cvx_edge.h
- Partition_2/include/CGAL/Partition_2/Partitioned_polygon_2.h
- Partition_2/include/CGAL/Partition_2/Rotation_tree_2.h
- Partition_2/include/CGAL/Partition_2/Triangulation_indirect_traits_2.h
- Partition_2/include/CGAL/Partition_2/Vertex_visibility_graph_2_impl.h
- Partition_2/include/CGAL/Partition_2/partition_approx_convex_2.h
- Partition_2/include/CGAL/Partition_2/partition_optimal_convex_2.h
- Partition_2/include/CGAL/Partition_2/partition_y_monotone_2.h
- Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h
Add a generic static filtering in the `Lazy_kernel`,  
* Affected package(s): Kernel
> Add Static Filters for the Exact Construction Kernel

- Documentation/doc/scripts/html_output_post_processing.py
> Make postprocessing script working with python3 and python2

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
Fixes some stuf in io_image_plugin.
* Issue(s) solved (if any): fix #2668
> Polyhedron demo: small fixes for io_image_plugin

- Polyhedron/demo/Polyhedron/CMakeLists.txt
There was a missing "CGAL_target_use_TBB()" for scene_c3t3_item. Adding it if (TBB_FOUND) fixes the crash.
* Issue(s) solved (if any): fix #2692
> Polyhedron demo: Fix mesh_3 with TBB

- BGL/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
> Add an option to triangulate all the faces

- Documentation/doc/Documentation/Tutorials/Tutorial_hello_world.txt
Fixed typo in tutorial documentation. Listed `operator<<` should have been `operator<`.
* Affected package(s): None
* Issue(s) solved (if any): None
* Feature/Small Feature (if any): None
> Fixed typo in tutorial documentation.

- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
> Triangulation_2: cleanup

- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
Assertions was wrong for border halfedges
> Fix assertions

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
Commit cherry-picked from #2626
> More verbose debug output

- Installation/changes.md
PR https://github.com/CGAL/cgal/pull/2697 should have had a section in `changes.md`. This PR adds it.
> OTR: Fix missing section in changes.md

- Installation/changes.md
> Fix typo in changes.md

- Periodic_3_triangulation_3/include/CGAL/Periodic_3_Delaunay_triangulation_3.h
- Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_3.h
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_p3rt3_as_p3t3.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_p3rt3_insert_remove_point_set.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_p3rt3_versus_rt3.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_regular_triangulation_3.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_regular_triangulation_traits_3.h
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_triangulation_traits_3.h
Add timers in all tests, remove an old expensive assertion, and repla…ce a map with an unordered_map
* Affected package(s): Periodic_3_triangulation_3
> Periodic_3_triangulation_3: Some accelerations

- .travis.yml
- .travis/install_openmesh.sh
- .travis/template.txt
- BGL/include/CGAL/boost/graph/graph_traits_OpenMesh.h
- BGL/include/CGAL/boost/graph/graph_traits_PolyMesh_ArrayKernelT.h
- BGL/include/CGAL/boost/graph/graph_traits_TriMesh_ArrayKernelT.h
This PR adds a script for travis to download, fix, build and install the OpenMesh library.
> Travis: Add OpenMesh

- Documentation/doc/scripts/process_doc.sh
- Documentation/doc/scripts/test_doxygen_versions.sh
- Documentation/doc/scripts/testsuite.py
The result of the script now stores logs of all three versions and display them.
> Documentation testsuite : Add results and overview for all three doxygen versions

- Polygon/include/CGAL/Polygon_2.h
This was because of an incomplete command.
> Some functions did not appear in the doc

- Documentation/doc/CMakeLists.txt
- Documentation/doc/resources/1.8.13/BaseDoxyfile.in
- Documentation/doc/resources/1.8.13/deprecated.html
- Documentation/doc/resources/1.8.4/deprecated.html
- Documentation/doc/resources/1.8.4/header_package.html
- Documentation/doc/scripts/test_doxygen_versions.sh
- Maintenance/public_release/scripts/prepare_release
* Affected package(s): doc
* Issue(s) solved (if any): fix #2633
> Use new URL for MathJax

- .travis.yml
- .travis/generate_travis.sh
- .travis/template.txt
This PR removes GCC from every job but CHECK, which makes it approximately twice faster for a full build to finish.
> Travis: Remove GCC

- .travis.yml
- .travis/install.sh
- .travis/template.txt
Manually call apt-get install on each package and wrap it in a test to make it try again when it fails.
* Issue(s) solved (if any): fix #2740
> Travis: retry on apt-get failure

- Mesh_3/include/CGAL/Mesh_3/experimental/Sizing_field_with_aabb_tree.h
- Mesh_3/include/CGAL/Polyhedral_complex_mesh_domain_3.h
This pull-request fixes undocumented (and untested) pieces of code of Mesh_3. The bug was introduced during the release cycle of CGAL-4.12.
> Mesh_3: fix bugs in undocumented code

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/STL_io_plugin.cpp
The STL IO plugin did not read files with *.STL
> Polyhedron: Add *STL to nameFilters()

- Arrangement_on_surface_2/include/CGAL/Arr_curve_data_traits_2.h
- BGL/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
Address two warnings issued by [clang on apple](https://cgal.geometryfactory.com/CGAL/testsuite/)
* Affected package(s): Arrangement and Nef_3 (and what depends on them).
> Fix two warnings about unused variable/parameter

- Polyhedron/demo/Polyhedron/Scene.cpp
If the color column selected clicked is not in the selection, edit the corresponding item, not the current selection.## Release Management
> Polyhedron demo: fix color selection in the SceneView.

- Intersections_3/include/CGAL/internal/Intersections_3/Triangle_3_Segment_3_intersection.h
* Issue(s) solved (if any): fix #2809
> Intersections_3: Replace last case with a default to avoid warning

- BGL/include/CGAL/boost/graph/selection.h
Deal correctly with border halfedges.
* Affected package(s): Polygon Mesh Processing
* Issue(s) solved (if any): fix #2788
> PMP: bugfix in expand_face_selection_for_removal()

- Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
> Correctly generate cgal_test_with_cmake

- Number_types/include/CGAL/GMP/Gmpfi_type.h
- Number_types/include/CGAL/GMP/Gmpfr_type.h
> Issue2790 mprf4 - deprecated functions

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/CMakeLists.txt
- Testsuite/test/collect_cgal_testresults_from_cmake
- Fix a bug in demo/Polyhedron/Plugins/Mesh_3/CMakeLists.txt
- Remove CMake Warning about /usr/share/cmake/Modules/FindBoost
> fix various minor issues

- BGL/doc/BGL/Concepts/FaceGraph.h
- BGL/doc/BGL/Concepts/HalfedgeGraph.h
- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
- BGL/include/CGAL/boost/graph/Graph_with_descriptor_with_graph.h
- BGL/include/CGAL/boost/graph/copy_face_graph.h
- BGL/include/CGAL/boost/graph/named_params_helper.h
- BGL/include/CGAL/boost/graph/properties.h
- BGL/include/CGAL/boost/graph/properties_OpenMesh.h
- BGL/include/CGAL/boost/graph/properties_Seam_mesh.h
- Linear_cell_complex/include/CGAL/boost/graph/properties_Linear_cell_complex_for_combinatorial_map.h
- Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h
- Polyhedron/include/CGAL/boost/graph/properties_Polyhedron_3.h
- Surface_mesh/examples/Surface_mesh/sm_derivation.cpp
- Surface_mesh/include/CGAL/boost/graph/properties_Surface_mesh.h
Move graph_has_property from namespace boost to namespace CGAL and provide some doc for it.
* Issue(s) solved (if any): fix #1837
* Feature/Small Feature (if any):[ here](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Graph_has_property)
* pre-approved by Sloriot 24 January 2018
> BGL: Document graph_has_property

- Installation/CMakeLists.txt
- Installation/cmake/modules/CGAL_SetupCGAL_Qt5Dependencies.cmake
Try to fix errors or feature requests of #2656.
* Affected package(s): CMake/Installation
* Issue(s) solved (if any): fix #2656
> Fix CGAL_HEADER_ONLY

- .travis/build_package.sh
This PR rectifies the build script of travis so BGL examples are tested despite their unusual architecture.
> Travis: fix build script for BGL examples

- BGL/examples/BGL_polyhedron_3/polyhedron_partition.cpp
- BGL/include/CGAL/boost/graph/METIS/partition_dual_graph.h
- BGL/include/CGAL/boost/graph/METIS/partition_graph.h
Fix two warnings in BGL's partition code.
> BGL: Fix partition warnings

- Arrangement_on_surface_2/include/CGAL/Arr_geodesic_arc_on_sphere_traits_2.h
- Arrangement_on_surface_2/include/CGAL/Arr_rat_arc/Algebraic_point_2.h
- Arrangement_on_surface_2/include/CGAL/Arr_rat_arc/Rational_function.h
- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Curve_renderer_facade.h
- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Curved_kernel_via_analysis_2_impl.h
- Cone_spanners_2/include/CGAL/Construct_theta_graph_2.h
- Number_types/include/CGAL/constant.h
- Polynomial/include/CGAL/Polynomial_traits_d.h
Fixes for bugs revealed by the header only VC++ testsuite.
* Affected package(s): Arrangements_on_surface_2, Cone_spanners_2, Polynomial
* Fix  #2656
> More  CGAL_STATIC_THREAD_LOCAL_VARIABLE

- .travis/build_package.sh
move .travis.yml validity cehck in the first place of the job CHECK.
> Travis: perform the test of .travis.yml validity in first place

- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
Only relevant operations are showed in the operations combo box.
* Issue(s) solved (if any): fix #2840
> Polyhedron demo: Enhance selection tool

- Intersections_3/include/CGAL/internal/Intersections_3/Triangle_3_Line_3_intersection.h
- Intersections_3/include/CGAL/internal/Intersections_3/Triangle_3_Ray_3_intersection.h
- Intersections_3/include/CGAL/internal/Intersections_3/Triangle_3_Segment_3_intersection.h
We had fixed Triangle-Segment intersections before. Now we add Triangle-Ray and Triangle-Line.
* Affected package(s): Intersections_3
> Intersections_3: Deal with fallthrough warnings

- Polyhedron/demo/Polyhedron/Plugins/PMP/Corefinement_plugin.cpp
restore cursor in case of early return
> Restore cursor in case of failure

- Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polylines_item.h
Fix the selection for polylines with corners shown.
* Issue(s) solved (if any): fix #2882
> Polyhedron demo: Fix operations for polyline

- Documentation/doc/scripts/testsuite.py
Add a line to the table to make it easier to read the results.
> Documentation: Enhance the doc testsuite display

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
This PR fixes the plane and the display of the c3t3_item when it has big coordinates.
> Polyhedron demo: fix c3t3 display with big coordinates

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
This is modifying a non-documented function that is used in a plug-in of the demo, marked as experimental.
> Improve removal of self-intersections for the demo plugin

- Polyhedron/demo/Polyhedron/Plugins/PMP/Repair_polyhedron_plugin.cpp
> Add actions to use autorefinement

- Documentation/doc/scripts/testsuite.py
> Documentation: change header

- Scripts/developer_scripts/create_new_release
This should fix the typo introduced in #2885
> Scripts: Fix typo

- Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
Fix the cut_plugin behavior when adding a new item to the scene when a cut_segment_plane is present.
* Issue(s) solved (if any): fix #2902
> Polyhedron demo: Fix cut plugin

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h
`Is_outward_oriented()` results in a segfault if the input mesh has some isolated vertices.
> Handle isolated vertices

- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
Make the code for edge_to_facets selection safer.
> Polyhedron demo: Fix the selection edge to faces

- Polyhedron/demo/Polyhedron/Viewer.cpp
Fixes the segfault with QGLViewer 2.6 and the freeze with 2.7.
> Polyhedron demo: Fix snapshot

- BGL/include/CGAL/boost/graph/properties.h
- BGL/test/BGL/test_Prefix.h
- Linear_cell_complex/include/CGAL/Linear_cell_complex_constructors.h
- Linear_cell_complex/include/CGAL/boost/graph/properties_Linear_cell_complex_for_combinatorial_map.h
- Linear_cell_complex/package_info/Linear_cell_complex/dependencies
- Polyhedron/include/CGAL/boost/graph/properties_Polyhedron_3.h
Remove one #include to Polyhedron_iostream.h which is useless.
* Affected package(s): LCC
* Issue(s) solved (if any): fix #2949 (partial fix, only the second problem)
> Remove one useless dependency in LCC to Polyhedron.

- Classification/include/CGAL/Classification/Feature/Gradient_of_feature.h
- Classification/include/CGAL/Classification/Local_eigen_analysis.h
- Classification/include/CGAL/Classification/Point_set_feature_generator.h
- Point_set_3/include/CGAL/Point_set_3/IO.h
- Polyhedron/demo/Polyhedron/Color_ramp.cpp
- Polyhedron/demo/Polyhedron/Color_ramp.h
- Polyhedron/demo/Polyhedron/Plugins/Classification/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Classification/Classification_advanced_widget.ui
- Polyhedron/demo/Polyhedron/Plugins/Classification/Classification_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Classification/Classification_widget.ui
- Polyhedron/demo/Polyhedron/Plugins/Classification/Cluster_classification.cpp
- Polyhedron/demo/Polyhedron/Plugins/Classification/Cluster_classification.h
- Polyhedron/demo/Polyhedron/Plugins/Classification/Item_classification_base.h
- Polyhedron/demo/Polyhedron/Plugins/Classification/Point_set_item_classification.cpp
- Polyhedron/demo/Polyhedron/Plugins/Classification/Point_set_item_classification.h
This PR adds some features to the classification plug-in:
- much better reworked widget
- possibility to compute classification on clusters (from RANSAC or region growing)
Some undocumented code is added to the package (some might be completed and documented later on with a small feature).
* Affected package(s): Classification, Polyhedron demo
* Tested locally on GNU/Linux using both `clang` and `gcc`
> Classification Plug-In: Better Widget & Cluster Classification

- AABB_tree/include/CGAL/AABB_primitive.h
* Affected package(s): AABB-tree
* Issue(s) solved (if any): fix #2962
> Update pmap requirements

- AABB_tree/include/CGAL/AABB_primitive.h
* Affected package(s): AABB-tree
* Issue(s) solved (if any): fix #2963
> Add a constructor from iterator on id for AABB_primitive

- Combinatorial_map/include/CGAL/Combinatorial_map_basic_operations.h
Replace some wrong Dart_handle by Dart_const_handle.
* Affected package(s): CMap
> Replace some wrong Dart_handle by Dart_const_handle.

- Number_types/include/CGAL/FPU.h
- Number_types/include/CGAL/Interval_nt.h
- Number_types/test/Number_types/Interval_nt.cpp
* Issue(s) solved (if any): fix #2981
> Remove CGAL::internal::infinity

- Surface_mesh/doc/Surface_mesh/Surface_mesh.txt
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
- Surface_mesh_parameterization/doc/Surface_mesh_parameterization/PackageDescription.txt
- Surface_mesh_parameterization/doc/Surface_mesh_parameterization/Surface_mesh_parameterization.txt
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Orbifold_Tutte_parameterizer_3.h
Fix a few missing links and wrong concepts.
* Affected package(s): `SMP`, `Surface_mesh`
> Doc: fix minor issues in Surface_mesh and SMP

- Homogeneous_kernel/include/CGAL/Homogeneous/Aff_transformationH2.h
- Homogeneous_kernel/include/CGAL/Homogeneous/Aff_transformationH3.h
- Visibility_2/include/CGAL/Rotational_sweep_visibility_2.h
* Affected package(s): Visibility_2, Kernel_23
> Yet more fallthrough fixes

- Classification/doc/Classification/PackageDescription.txt
Classification is said to have been introduced in 4.9 but in reality it is 4.12.
> Classification:fix introduced release

- .travis.yml
- .travis/build_package.sh
- .travis/template.txt
- .travis/test_package.sh
Moves the dependencies test into the install: step to gain more time if a package is not concerned.
> Travis: optimization

- .travis.yml
- .travis/generate_travis.sh
- .travis/template.txt
Remove GCC from all the tests.
> Travis: Don't test gcc anymore.

- Polyhedron/demo/Polyhedron/Plugins/PMP/Scene_facegraph_item_k_ring_selection.h
When using the lasso in the Mesh Selection plugin, the background was captured at each frame, which could result in a buggy "blinking" display in some configs (Mesa driver, it seems). This fixes it by only capturing the background when the button is clicked, similarly to what is done in the Point Set Selection plugin.
> Polyhedron demo: Fix selection blinking display

- Point_set_processing_3/include/CGAL/estimate_scale.h
- Point_set_processing_3/include/CGAL/structure_point_set.h
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/property_maps.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/intersection.h
Three fixes in PMP and PSP for issues introduced between 4.11 and 4.12-beta2.
> Pmp psp fixes for release

- BGL/include/CGAL/boost/graph/Euler_operations.h
- BGL/test/BGL/test_Euler_operations.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
Bug fix
* Affected package(s): BGL, Polyhedron Demo
> Fix Euler::add_vertex_and_face_to_border()

- AABB_tree/doc/AABB_tree/Concepts/AABBTraits.h
- AABB_tree/include/CGAL/AABB_traits.h
- AABB_tree/include/CGAL/AABB_tree.h
- Circulator/doc/Circulator/Concepts/Circulator.h
- Interpolation/doc/Interpolation/CGAL/surface_neighbor_coordinates_3.h
- Jet_fitting_3/doc/Jet_fitting_3/Jet_fitting_3.txt
- Polygon/doc/Polygon/Concepts/PolygonTraits_2.h
- Polygon/include/CGAL/General_polygon_with_holes_2.h
- Polygon/include/CGAL/Polygon_2.h
- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
- Surface_mesh_deformation/doc/Surface_mesh_deformation/Concepts/DeformationClosestRotationTraits_3.h
- Surface_mesh_deformation/doc/Surface_mesh_deformation/Concepts/RawPoint_3.h
- Surface_mesh_deformation/include/CGAL/Surface_mesh_deformation.h
- Surface_mesh_shortest_path/doc/Surface_mesh_shortest_path/Concepts/SurfaceMeshShortestPathTraits.h
- Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
- Surface_mesh_skeletonization/doc/Surface_mesh_skeletonization/Concepts/MeanCurvatureSkeletonizationTraits.h
- Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h
- Triangulation/doc/Triangulation/Triangulation.txt
Fix warnings and bugs discovered by doxygen improvements
> Fix doc warnings (and bugs)

- Point_set_processing_3/include/CGAL/mst_orient_normals.h
Fix in ref manual page of `mst_orient_normals`.
> Point Set Processing: Use \cgalCite

- Scripts/developer_scripts/cgal_check_dependencies.sh
The current dependencies are checked with a simple diff between the committed and the re-computed dependecies files, which means that if the dependencies are not found in the same order, it counts like an error. With this PR it is not like that anymore, which should allow to manually add or remove the problematic dependencies without having to run the 20 min process to try and find the problems.
> Travis: Make the dependencies check NOT order dependant.

- Scripts/developer_scripts/cgal_check_dependencies.sh
This is a cherry pick of #3075
> Travis: Apply last changes to 4.12

- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d_1.h
- Arrangement_on_surface_2/include/CGAL/Arr_polycurve_traits_2.h
- Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_overlay_traits_2.h
- CGAL_Core/include/CGAL/CORE/CoreDefs.h
- Installation/include/CGAL/disable_warnings.h
- Minkowski_sum_2/include/CGAL/Minkowski_sum_2/AABB_traits_2.h
- Partition_2/include/CGAL/Partition_2/Rotation_tree_2.h
- Polynomial/include/CGAL/Polynomial_traits_d.h
- SearchStructures/include/CGAL/Segment_tree_d.h
Also inside a class scope we have to add forward declarations.
* Affected package(s):  Arrangement_2 and what uses it
* Issue(s) solved (if any):  VC2017 preview
> Arrangement_2: Add Forward Declaration

- Installation/CHANGES.md
> Kernel_23: Update CHANGES.md

- Documentation/doc/scripts/testsuite.py
Specifies in the result page that Doxygen 1.8.13 is the one used for the CGAL documentation and adds a header to the result table to regroup the columns by version in a cleaner way.
> Documentation overview: enhancement

- Number_types/include/CGAL/Gmpq.h
- Number_types/include/CGAL/mpq_class.h
- Number_types/test/Number_types/Gmpq.cpp
* Issue(s) solved (if any): fix #3099
> Fix conversion from mpq to interval

- Spatial_searching/test/Spatial_searching/Point_with_info.h
> Spatial searching: fix missing includes in test header

- Polyhedron/demo/Polyhedron/MainWindow.cpp
function returns if less than 2 selected items.
* Issue(s) solved (if any): fix #3117
> Polyhedron demo: Fix for Set Different Colors for Selected Items

- Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp
> Replace M_PI with CGAL_PI

- .travis/build_package.sh
- STL_Extension/include/CGAL/assertions_behaviour.h
- Scripts/developer_scripts/cgal_check_dependencies.sh
This should trigger the test of the test_headers.cpp file.
> Travis: Add  check_headers in the CHECK pass of travis

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane_intersection.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane_intersection.h
- Polyhedron/demo/Polyhedron/Scene_image_item.cpp
The intrinsic offset of the 3D images were ignored by the Demo, not anymore.
> Polyhedron demo: Use image's offset in display

- Surface_mesher/demo/Surface_mesher/volume.cpp
- Surface_mesher/demo/Surface_mesher/volume.h
Similar to #3150  only with `Facet` instead of `Point`.
* Affected package(s): Surface_mesher demo
> Surface mesher demo: Another problem with VS2017 -permissive-

- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
> PMP: Fix typos in the User Manual

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/transform.h
@maxGimeno I wonder what you have tested.
> Add missing overload for PMP::transform

- CGAL_Core/include/CGAL/CORE/CoreDefs.h
> Undo unwanted change in  777d305

- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
> Kernel_23: Fix typo in doc

- Classification/include/CGAL/Classification/Planimetric_grid.h
The method `Planimetric_grid::has_points()` was not well implemented, it contained a test that was useless in most cases and should have been deported to specific parts where it was actually needed. In addition, this test was not done in all cases where it should have been, leading to bugs (see https://github.com/CGAL/cgal/issues/3176).
This issue deports the tests in parts where they are actually needed and cleans up the `has_points()` method (some additional assertions are also added to help future debugging). The bug is gone and the other examples/tests work well.
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/3176
> Classification: Fix bug + clean up has_points() method in Planimetric_grid

- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/Plugins/IO/Selection_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Three.cpp
- Three/include/CGAL/Three/Three.h
With this PR, static functions to access the scene and the mainwindow are added.
It is used to automatically decide if the selection_io_plugin or the selection_io_sm_plugin should be used.
> Polyhedron demo: Automatically decide between selection_io_plugin or selection_io_sm_plugin

- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/discrete_authalic.cpp
- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/lscm.cpp
- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/orbifold.cpp
- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/seam_Polyhedron_3.cpp
- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/simple_parameterization.cpp
- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/square_border_parameterizer.cpp
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/MVC_post_processor_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Orbifold_Tutte_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/internal/angles.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/orbifold_shortest_path.h
- Surface_mesh_parameterization/test/Surface_mesh_parameterization/extensive_parameterization_test.cpp
* Issue(s) solved (if any): fix #3193 
> SMP: clean verbosity

- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
A while loop had a typo, making it infinite.
* Issue(s) solved (if any): fix #3202
> Polyhedron_demo: Fix triangulate_convex_facet in Scene_surface_mesh_item

- Surface_mesh/include/CGAL/Surface_mesh/IO.h
Call documented functions in convenience functions.
* Issue(s) solved (if any): fix #3189
> Fix non-documented IO functions

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h
Do not delete twice a vertex in case it was already updated
> Stitch bug fix 

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
This PR
- fixes the behavior of the camera copy/paste function
- Reset the viewer's scene bbox when zooming to an item (from the context menu)
- Makes the transparency propagable to all selected items
> Polyhedron Demo: minor fixes and enhancements

- BGL/include/CGAL/boost/graph/helpers.h
Do not remove element you iterate on
@bo0ts booh! ;)
> Fix CGAL::clear

- Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp
- Polyhedron/demo/Polyhedron/resources/solid_wireframe_shader.f
- Polyhedron/demo/Polyhedron/resources/solid_wireframe_shader.g
- Polyhedron/demo/Polyhedron/resources/solid_wireframe_shader.v
Add the clipping planes equations to the new polylines program.
> Polyhedron Demo: Restore clipping for polylines

- Polyhedron/demo/Polyhedron/Plugins/Display/Display_property.ui
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Partition_graph_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_segmentation_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h
- Polyhedron/demo/Polyhedron/resources/shader_c3t3.f
- Polyhedron/demo/Polyhedron/resources/shader_c3t3_edges.f
- Move a misplaced bracket in the picking code of the Scene.
- Fixes the management of face colors and patch_ids in surface_mesh_item
> Polyhedron demo: Fixes 

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
The only non-collapsable constrained edges are those with
both endpoints being explicitly constrained vertices or corners
> Be more permissive for collapsing constrained edges in Isotropic remeshing

- Triangulation/include/CGAL/Triangulation.h
- Triangulation/include/CGAL/internal/Triangulation/Triangulation_ds_iterators.h
- Triangulation/test/Triangulation/test_triangulation.cpp
* Affected package(s): `Triangulation`
* Issue(s) solved (if any): fix #3274
> Triangulation: Fix finite_facets_begin()/end()

- Alpha_shapes_3/examples/Alpha_shapes_3/visible_alpha_shape_facets_to_OFF.cpp
> Add an example writing into OFF visible facets of an alpha-shape

- BGL/doc/BGL/BGL.txt
- Documentation/doc/Documentation/Installation.txt
Added a few lines about METIS in the list of third party libraries.
> Doc: Add METIS to the list of third party librairies

- BGL/include/CGAL/boost/graph/Euler_operations.h
- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Detail/Edge_collapse_impl.h
> Handle the case of degenerate volumes in the link condition

- BGL/doc/BGL/BGL.txt
- BGL/doc/BGL/CGAL/boost/graph/properties.h
- BGL/doc/BGL/Concepts/EdgeListGraph.h
- BGL/doc/BGL/Concepts/VertexListGraph.h
- BGL/doc/BGL/NamedParameters.txt
- BGL/doc/BGL/PackageDescription.txt
- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
- Combinatorial_map/doc/Combinatorial_map/Concepts/CellAttribute.h
- Cone_spanners_2/doc/Cone_spanners_2/Cone_spanners_2.txt
- Documentation/doc/Documentation/General.txt
- Documentation/doc/Documentation/Preliminaries.txt
- Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h
- Ridges_3/doc/Ridges_3/Ridges_3.txt
- STL_Extension/doc/STL_Extension/CGAL/Iterator_range.h
- STL_Extension/doc/STL_Extension/CGAL/algorithm.h
- Surface_mesh/doc/Surface_mesh/Surface_mesh.txt
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/orbifold_shortest_path.h
- Surface_mesh_skeletonization/doc/Surface_mesh_skeletonization/Surface_mesh_skeletonization.txt
- Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h
> Do not link to sgi.com (offline)

- Documentation/doc/resources/1.8.13/menu_version.js
- Documentation/doc/resources/1.8.14/menu_version.js
- Documentation/doc/resources/1.8.4/menu_version.js
If the version of the doc in the url is not in the list of expected versions, it is still displayed and considered selected.
> Documentation: Fix the version menu.

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
Use a better approximation in the IntConverter.
* Issue(s) solved (if any): fix #3181
> Polyhedron demo: Fix Pixel Value in Image Reading

- .travis.yml
- .travis/template.txt
Add tests, examples and demos to the initial configuration of CGAL in Travis.
> Travis: Add tests, examples and demos to travis's call to cmake for CGAL

- Scripts/developer_scripts/Bundle_polyhedron_demo_with_appimage.sh
Add a script in Scripts/developer_scripts that bundles the Polyhedron demo with AppImage Linux.
We should discuss where to put the said bundle to download and modify the script accordingly.
* Issue(s) solved (if any): fix #2650
> Automatically create a bundle of the Polyhedron demo for Linux.

- Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/PCA/MeshOnGrid_dialog.ui
Add an action to the Affine_transformation_plugin to copy a selected item on a 3D grid.
> Polyhedron demo: Duplicate meshes on a grid

- Triangulation_2/doc/Triangulation_2/Triangulation_2.txt
> Fix locate description

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_normal_estimation_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_group_item.cpp
- Polyhedron/demo/Polyhedron/Scene_item.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- Three/include/CGAL/Three/Scene_item.h
Fixes some trivial bugs in the Polyhedron demo.
* Issue(s) solved (if any): fix #3356, fix #3360
> Polyhedron demo:  Several fixes

- Convex_hull_3/include/CGAL/convex_hull_3.h
Fix typos preventing activation of local static filters
> Fix activation of local static filters

- BGL/include/CGAL/boost/graph/selection.h
- BGL/test/BGL/test_Manifold_face_removal.cpp
An extra test was needed when a vertex is on the boundary
> Fix selection issue with boundary vertices

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/intersection.h
* Issue(s) solved (if any): fix #3403
> PMP: Fix look-up error

- Kernel_23/doc/Kernel_23/CGAL/Aff_transformation_3.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
> Kernel_23: Fix doc typos

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h
The orientation of the clipper was ignored.
> Fix clipping of open meshes

- Installation/cmake/modules/CGAL_TweakFindBoost.cmake
> Installation: Fix wrong policy setting

- BGL/include/CGAL/boost/graph/helpers.h
- Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_plugin.cpp
Adds missing information in the doc of make_grid and adds the 3rd argument of the functor.
* Affected package(s):BGL
* Issue(s) solved (if any): fix #3422
> BGL: Fix make_grid() documentation

- BGL/doc/BGL/Concepts/EdgeListGraph.h
- BGL/doc/BGL/Concepts/VertexListGraph.h
> BGL: fix doc typo
