CGAL/cgal

- Documentation/doc/scripts/compare_testsuites.sh
- Documentation/doc/scripts/process_doc.sh
- Documentation/doc/scripts/test_doxygen_versions.sh
- Documentation/doc/scripts/testsuite.py
- Scripts/developer_scripts/run_doxygen_testsuite
Modify the scripts so it generates and compare documentation  from 3 versions of doxygen.
A demonstration of the result can be found [here.](https://cgal.geometryfactory.com/~mgimeno/Doc_results/index.html)
When this is integrated, the existing index.html of the doc overview page should be manually modified to add the 3rd column to the table header. 
* Affected package(s):Ducumentation
* Issue(s) solved (if any): fix #1800
> Add a 3rd diff column to the documentation overview page.

- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
Workaround for ` Construct_bbox_2::operator()(Triangle_2)`  with ` Simple_cartesian<…Interval_nt<0>>` .
Shows up in the master testsuite for 4.12, e.g. [here](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-I-102.shtml) 
It looks like a compiler error. Versions  VC > 2013   don't have this problem.
> Fix for VC++ 2013

- Polyhedron/demo/Polyhedron/CMakeLists.txt
Export the selection item for `Surface_mesh`.
This is needed for external plugins using the selection plugin with `Surface_mesh_item`
* Affected package(s): CGAL demo
> Polyhedron demo : export surface_mesh_selection_item for external plugins

- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
Change the word 'scenarii' to 'scenarios'
* Affected package(s): PMP documentation
* Feature/Small Feature (if any): none
> Polygon Mesh Processing documenation - Correct spelling mistake

- Mesh_2/doc/Mesh_2/CGAL/lloyd_optimize_mesh_2.h
- Mesh_2/include/CGAL/Mesh_2/Mesh_global_optimizer_2.h
This PR fixes the use of `CGAL::lloyd_optimize_mesh_2()` when used on a `CDT_2` that was not constructed using `Mesh_2`.
Formerly, the convergence test `check_convergence()` was returning `true` all the time because no facet was tagged as "in the domain".
The convergence test should not suffer from that change, mainly because constrained vertices are not considered.
* Affected package : Mesh_2 (smoothing only)
Thanks @gdamiand for the bug report!
> Mesh 2 : fix the use of Lloyd from any CDT_2

- Triangulation_2/include/CGAL/Constrained_Delaunay_triangulation_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
Derecursify `Constrained_triangulation_2::insert_constraint(Vertex_handle,Vertex_handle)` 
Increment parameter `depth` of `Constrained_Delaunay_triangulation_2::propagating_flip(,,depth)` when going into recursion.
* Affected package(s):  Triangulation_2
> Derecursify functions in Constrained Delaunay and Constrained Triangulation

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/measure.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/measures_test.cpp
Fix `<CGAL/Polygon_mesh_processing/measure.h>` that requires `CGAL::exact(FT)` from `<CGAL/Lazy.h>`. `exact(FT)` is not called by ADL (because most of the number types, such as `double`, are not in the CGAL namespace, and that is why the function must be declared before its use.
Fixes #2654.
The addition of `<utility>` is from a merge conflict with `master`.
* Issue(s) solved (if any): fix #2654
> Fix <CGAL/Polygon_mesh_processing/measure.h>

- Point_set_processing_3/include/CGAL/estimate_scale.h
If the point map returns a temporary a temporary was returned.
> Use reference type of the pmap

- Point_set_3/include/CGAL/Point_set_3.h
When a point is removed, it is in reality only swapped with the end element and the `garbage_begin()` iterator is decremented. When adding a point, this garbage is reused to avoid reallocation. The problem is that properties are not reset, which is not intuitive (especially because properties are given default values).
This fixes it.
(I based it on 4.11 because it relies on a method that was introduced in 4.11.)
> Point Set 3: Reinitialize properties when reusing memory

- Subdivision_method_3/doc/Subdivision_method_3/Subdivision_method_3.txt
- Subdivision_method_3/examples/Subdivision_method_3/CatmullClark_subdivision.cpp
- Subdivision_method_3/examples/Subdivision_method_3/Customized_subdivision.cpp
- Subdivision_method_3/examples/Subdivision_method_3/DooSabin_subdivision.cpp
- Subdivision_method_3/examples/Subdivision_method_3/Loop_subdivision.cpp
- Subdivision_method_3/examples/Subdivision_method_3/Sqrt3_subdivision.cpp
- Subdivision_method_3/include/CGAL/Subdivision_method_3/internal/subdivision_hosts_impl_3.h
- Subdivision_method_3/include/CGAL/Subdivision_method_3/subdivision_masks_3.h
- Subdivision_method_3/test/Subdivision_method_3/test_Subdivision_method_3.cpp
At the same time I updated examples that were using an undocumented API
> Use reference type from the pmap and fix warnings

- Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
The level type is hard-coded as `std::size_t` while `num_faces()` returns a type from `graph_traits` that might be signed (which causes the warning I have).
> Workaround conversion warning

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/Preferences.ui
Add a hierarchy to the list of plugins in the Preferences dialog based on their location :
Edit : 
now, it looks like this : 
and items have a tooltip if they are not green, saying why they were not loaded. (Apparently, my screenshot manager does not capture the cursor neither the tooltips, sorry.)
> Polyhedron_demo: Enhance the plugins management in Preferences

- .travis.yml
- .travis/template.txt
- Polyhedron/demo/Polyhedron/resources/shader_flat.f
- Polyhedron/demo/Polyhedron/resources/shader_flat.g
For very small polyhedron items, the flat shading was failing, I think because of dFdx() and dFdy(). 
This PR also add the flag --silent to the make install in travis, to avoid the log to be unreadable because of its size.
> Polyhedron demo: Fix polyhedron flat shading and silent make install in travis

- GraphicsView/demo/Periodic_2_triangulation_2/Periodic_2_Delaunay_triangulation_2.cpp
- Periodic_2_triangulation_2/include/CGAL/Periodic_2_Delaunay_triangulation_traits_2.h
- Periodic_2_triangulation_2/include/CGAL/Periodic_2_triangulation_traits_2.h
- Periodic_2_triangulation_2/include/CGAL/internal/Periodic_2_Delaunay_triangulation_filtered_traits_2.h
- Periodic_2_triangulation_2/include/CGAL/internal/Periodic_2_Delaunay_triangulation_statically_filtered_traits_2.h
- Periodic_2_triangulation_2/include/CGAL/internal/Periodic_2_construct_point_2.h
- Periodic_2_triangulation_2/include/CGAL/internal/Periodic_2_triangulation_filtered_traits_2.h
- Periodic_2_triangulation_2/include/CGAL/internal/Periodic_2_triangulation_statically_filtered_traits_2.h
- Periodic_2_triangulation_2/include/CGAL/internal/Static_filters/Periodic_2_orientation_2.h
- Periodic_2_triangulation_2/include/CGAL/internal/Static_filters/Periodic_2_side_of_oriented_circle_2.h
MSCV has some weird bug when compiling code like:
```
template<K>
struct T : K { T() : K() { }  };
```
if `K` defines a typedef `K` in one its bases.
This was encountered in #2369 ( https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-27/Periodic_2_triangulation_2_Demo/TestReport_jtournois_x64_Cygwin-Windows10_MSVC2015-Debug-64bits.gz ) but a simplification of the typedef ( fecfaac ) made it a non-issue.
A good workaround is to use safer template parameter names. Commit fecfaac is reverted so that the sanity of the template parameter names can be checked.
* Affected package(s): `Periodic_2_triangulation_2`
> P2T2: Precautionary template parameter renaming 

- Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
There is a compilation error with g++ 4.1 on CentOS 5:
```
[100%] Building CXX object CMakeFiles/mesh_3D_image_with_features.dir/mesh_3D_image_with_features.cpp.o
/usr/bin/c++   -DCGAL_MESH_3_NO_DEPRECATED_C3T3_ITERATORS -DCGAL_MESH_3_NO_DEPRECATED_SURFACE_INDEX -DCGAL_TEST_SUITE -DCGAL_TEST_SUITE=1 -DCGAL_USE_GMP -DCGAL_USE_MPFR -DCGAL_USE_ZLIB -DCGAL_USE_ZLIB=1 -Wall -frounding-math -I/home/cgal_tester/build/src/cmake/platforms/CentOS5/test/Mesh_3_Examples/../../include -I/home/cgal_tester/build/src/cmake/platforms/CentOS5/test/Mesh_3_Examples -isystem /home/cgal_tester/build/src/cmake/platforms/CentOS5/include -isystem /mnt/testsuite/include -isystem /usr/local/include    -Wall -frounding-math -o CMakeFiles/mesh_3D_image_with_features.dir/mesh_3D_image_with_features.cpp.o -c …
```
> Fix a compilation error (on CentOS5)

- Convex_hull_3/include/CGAL/convex_hull_3.h
- Convex_hull_3/test/Convex_hull_3/quickhull_test_3.cpp
`CGAL::convex_hull_3` documents that the output is a triangulation
polyhedron. That is true... but for coplanar input points! In case of
coplanar input point, the output before this patch was a polyhedron with a
single polygonal face. The patch triangulates the face using a pivot point
and Euler operations.
* For CGAL-4.10.2
* Affected package(s): Convex_hull-3
> Fix Convex_hull_3 quickhull, with coplanar point

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Parameterization_plugin.cpp
Avoid a conversion warning (`std::size_t` to `int`) for msvc 2013
* Affected package(s): 3D demo
* Issue(s) solved (if any): fix #2683
> Demo parameterization plugin : avoid conversion warning

- Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_impl.h
- Arrangement_on_surface_2/test/Arrangement_on_surface_2/data/test_observer/test01.txt
- Installation/changes.md
When removing an edge from an arrangement and the user has requested to remove the end-vertices in case they become redundant (either isolated or approach infinity), defer the removal of the such end-vertices to occur after the observer is notified that the edge has been removed. This is symmetric (opposite) to the order of notification when an edge is inserted.
This fix does not completely resolve the issue. The notifications occur when inserting an edge and removing and edge are still not completely symmetric, because of notifications related to ccb's (connected component of the boundaries):
**Insert:**
```
before_create_vertex
after_create_vertex
before_create_vertex
after_create_vertex
before_create_edge
after_create_edge
before_add_inner_ccb
after_add_inner_ccb
```
**Remove:**
``` …
```
> Aos_2: non symetrical observer

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Parameterization_plugin.cpp
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
- Surface_mesh_parameterization/test/Surface_mesh_parameterization/CMakeLists.txt
Rework the way different solvers can be selected in the ARAP parameterization method. Default linking to Core is removed in SMP/test/ and in the polyhedron demo.
* Issue(s) solved (if any): Fix #2672 
> SMP: Remove Core dependency

- Installation/cmake/modules/CGAL_SetupCGALDependencies.cmake
Prior to the change, even with the below simplest code will have compilation error
CMakeLists
```cmake
cmake_minimum_required(VERSION 3.9)
project(Example)
set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/main.cpp)
find_package( CGAL REQUIRED )
add_executable(${PROJECT_NAME} ${PROJECT_SRCS})
target_link_libraries(${PROJECT_NAME} CGAL::CGAL)
```
main.cpp
```c++
#include "CGAL/remove_outliers.h"
int main(){
return 0;
}
```
Compilation error
```
In file included from /usr/include/c++/5/cstddef:45:0,
from /usr/include/boost/config/select_stdlib_config.hpp:18,
from /usr/include/boost/config.hpp:44,
from /usr/include/CGAL/config.h:111,
from /usr/include/CGAL/license/Point_set_processing_3.h:27,
from /usr/include/CGAL/remove_outliers.h:24,
from /home/hypevr/test/main.cpp:1: …
```
> fix incorrect INTERFACE_INCLUDE_DIRECTORIES that causes compilation error for downstream project

- BGL/include/CGAL/boost/graph/parameters_interface.h
- Installation/changes.md
- Polygon_mesh_processing/doc/Polygon_mesh_processing/NamedParameters.txt
- Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt
- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/corefinement.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/CMakeLists.txt
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_orient_cc.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Inside_out_plugin.cpp
This PR adds a function in orientation.h that orients positively all the connected components of a triangle mesh. 
* Affected package(s): Polygon Mesh Processing
* Issue(s) solved (if any): fix #2513 
* Feature/Small Feature (if any):[Orient connected components](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Orient_connected_components)
* Pre-approved by @sloriot  13 December 2017
> PMP :  Orient_connected_components function

- .travis/build_package.sh
Adds a test in the CHECK tests of travis that installs cgal in a non standard path and builds a trivial program.
* Issue(s) solved (if any): fix #2704
> Check if a non standard "make install" path for CGAL works

- .travis.yml
- .travis/template.txt
Change the travis configuration to add boost-iostreams.
* Issue(s) solved (if any): fix #2702
> Add boost iostream to travis

- Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
With recent changes, Mesh_3 was no longer compiler with
`CGAL_SEQUENTIAL_MESH_3_ADD_OUTSIDE_POINTS_ON_A_FAR_SPHERE` defined.
This PR fixes the compilation issue.
> Mesh_3: fix CGAL_SEQUENTIAL_MESH_3_ADD_OUTSIDE_POINTS_ON_A_FAR_SPHERE

- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
Set ids in polyhedron_item after creation and in invalidateOpenGLBuffers.
* Issue(s) solved (if any): fix #2703
> Polyhedron demo: Fix Scene_polyhedron_item ids

- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
- Cartesian_kernel/include/CGAL/constructions/kernel_ftC3.h
This fix is similar to https://github.com/CGAL/cgal/pull/2122: when computing `Plane_3::point()` (which is supposed to return one point lying on the plane - any point, there is no more constraint), the current code uses a division by the first non-null coordinate: if a coordinate is close to 0 (but non-null), the point's corresponding coordinate goes far away and becomes badly defined.
This leads, for example, to wrong and clearly unusable values for the `Plane_3::to_2d()` method (which internally uses `Plane_3::point()` as the origin of the 2D base), as was reported in https://github.com/CGAL/cgal/issues/2733.
In this fix, we simply check for the largest coordinate (in norm) and use it, to make sure that we always get the coordinate that is the closest to the origin (this is, again, very …
> Cartesian kernel: improve plane point() computation

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
In Haussdorf distance computation in parallel, while the operations are atomic there could be an update of the value and the real max would be overwritten.
In passing it also fixes this [issue](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-I-141/Polygon_mesh_processing/TestReport_lrineau_CentOS6-CXX11-Boost157.gz).
> Make the update of the max value correct

- Maintenance/infrastructure/cgal.geometryfactory.com/bin/create_release
- Scripts/developer_scripts/create_new_release
- wininst/developer_scripts/script_cgal.nsi
This PR fixes issues in our release creation scripts, when a public release was created:
- if the docker container creating the NSIS installer failed, then the script stopped, without cleaning directories,
- that made the next public release contain temporary tarball files,
- and then it got bigger and bigger. For `CGAL-4.12-I-141-public`, the tarball size was > 900MB!
> Scripts: fix release creation

- TDS_3/doc/TDS_3/Concepts/TriangulationDataStructure_3.h
The documentation of `ConvertVertex` and `ConvertCell` in `tds.copy_tds()` was missing some `const`
* Affected package(s): TDS_3, documentation only
> TDS_3 - add missing `const` in doc of `copy_tds()`

- Generalized_map/test/Generalized_map/Generalized_map_2_test.h
- Generalized_map/test/Generalized_map/Generalized_map_3_test.h
- Generalized_map/test/Generalized_map/Generalized_map_4_test.h
- Linear_cell_complex/test/Linear_cell_complex/Linear_cell_complex_copy_test.cpp
Initialise dart info when non void, in GMap test.
Modify the same code for GMap to use random value and not always 0.
* Affected package(s): GMap, CMap
* Issue(s) solved (if any):  #2751
> Bug fix in GMap test.

- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Efficient_RANSAC.h
There exists a very specific an rare case in RANSAC where no new candidate shapes are generated but no candidates are integrated nor discarded, which leads to a constant stop criterion, which leads to an infinite loop.
This is the least invasive fix that I managed to do: if the search is over but no shape was either integrated or discarded, we increase the stop criterion to unlock the situation. It works experimentally and does not modify other cases (and statistically, RANSAC gives the same distribution of shapes and assigned points with and without the fix).
* Affected package(s): Point Set Shape Detection 3
> Shape Detection: Fix Infinite Loop

- Circular_kernel_2/benchmark/dxf_to_bff/dxf_converter.h
- Circular_kernel_2/include/CGAL/IO/Dxf_reader.h
- Circular_kernel_2/include/CGAL/IO/Dxf_reader_doubles.h
- Circular_kernel_2/include/CGAL/IO/Dxf_variant_reader.h
- Straight_skeleton_2/include/CGAL/IO/Dxf_writer.h
In the `.dxf` [file format doc](https://www.autodesk.com/techpubs/autocad/acad2000/dxf/), it is said that the radius of a circle is a length (non-squared). However, the `Construct_circle_2` constructor requires the squared radius in argument. Thus `r` -> `r * r` a couple of times.
* Affected package(s): `Circular_kernel_2`
> Circular_kernel_2: Fix the circle reading in the `.dxf ` file reader

- Documentation/doc/resources/1.8.13/DoxygenLayout.xml
- Documentation/doc/resources/1.8.13/cgal_stylesheet.css
- Documentation/doc/resources/1.8.14/DoxygenLayout.xml
- Documentation/doc/resources/1.8.14/cgal_stylesheet.css
- Documentation/doc/resources/1.8.4/DoxygenLayout.xml
- Documentation/doc/scripts/html_output_post_processing.py
This PR 
- hides the broken index of the Manual page
- adds some postprocessing for 1.8.13 and 1.8.14 so the colors of the Namespace, Class and Concept nodes are modified the same way it is in 1.8.4
* Issue(s) solved (if any): fix #2750
> Documentation:  Fix postprocessing

- Maintenance/public_release/scripts/prepare_release
- Scripts/developer_scripts/run_doxygen_testsuite
The scripts that take care of the documentation now use results from Doxygen 1.8.13.
* Issue(s) solved (if any): fix #2706
> Use Doxygen 1.8.13 for official CGAL doc.

- Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/Concepts/Periodic_3DelaunayTriangulationTraits_3.h
- Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/Concepts/Periodic_3RegularTriangulationTraits_3.h
- Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/Concepts/Periodic_3TriangulationTraits_3.h
- Periodic_3_triangulation_3/include/CGAL/Periodic_3_regular_triangulation_3.h
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_regular_triangulation_3.cpp
- Triangulation_3/doc/Triangulation_3/Concepts/DelaunayTriangulationTraits_3.h
- Triangulation_3/doc/Triangulation_3/Concepts/RegularTriangulationTraits_3.h
- Triangulation_3/include/CGAL/Regular_triangulation_3.h
- `Is_Gabriel(Vertex_handle)` is wrong for RT3 and P3RT3: it checks whether a point `p` is within its own power cell while it should check whether the smallest circumsphere orthgonal to `p` (that is the sphere `(p, -w_p)`) is empty. This is equivalent to checking whether the nearest power vertex of `p` is outside of this sphere. This PR fixes that.
- `nearest_power_vertex()` was also bugged for P3RT3. This change is actually a cherry-pick from the P3M3 branch (#2658) that already fixed it.
Along the way, the PR cleans the T3/P3T3 concepts by:
- Fixing `(power)side_of_bounded_(power)_sphere` not being required in various concepts.
- Cleaning redundant requirements (that is, requiring something like `construct_point_3(Point_3)` from `Periodic_3TriangulationTraits_3`, which is already …
> T3/P3T3: Fix Is_Gabriel(Vertex_handle) for regular triangulations

- BGL/test/BGL/graph_concept_Triangulation_2.cpp
- Triangulation_2/include/CGAL/Regular_triangulation_2.h
- Triangulation_2/include/CGAL/boost/graph/graph_traits_Regular_triangulation_2.h
For some reason, the typedef `Triangulation` in `Regular_triangulation_2` is not the base triangulation `Triangulation_2`, but a typedef to `Self`. Consequently, the `halfedge_descriptor` in the graph traits of `Regular_triangulation_2` is wrong and cannot compile.
Although it's not documented, I left `typedef Self Triangulation` in case it's used somewhere (but I couldn't find it anywhere in CGAL) as it could create a nasty bug. Base is typedef'd by `Tr_Base` for consistency with the base typedef in (P3)T3 classes.
Added `RT2` to `graph_concept_Triangulation_2`, but the T2 graph traits are missing proper tests...
* Affected package(s): `Triangulation_2`
> Triangulation_2: Fix template parameter in RT_2's graph traits

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp
The GUI offers a spin box in degrees, but the algorithms expects a value in radiants, and the conversion was not done in all cases…
> Polyhedron Demo Surface Reco. Plugin: Fix missing conversion from degrees to radiants

- STL_Extension/include/CGAL/assertions.h
That should fix the following warning.
```
[ 50%] Building CXX object CMakeFiles/dynamic_properties_test.dir/dynamic_properties_test.cpp.o
/usr/local/bin/c++   -DCGAL_TEST_SUITE=1 -DCGAL_USE_GMP -DCGAL_USE_MPFR -I/home/cgal_tester/build/src/cmake/platforms/Ubuntu-latest-GCC6-CXX1z/test/Property_map/../../include -isystem /usr/include/x86_64-linux-gnu -I/home/cgal_tester/build/src/cmake/platforms/Ubuntu-latest-GCC6-CXX1z/test/Property_map -I/home/cgal_tester/build/src/cmake/platforms/Ubuntu-latest-GCC6-CXX1z/include -I/mnt/testsuite/include  -DDONT_USE_BOOST_PROGRAM_OPTIONS -Wall -Wextra -std=c++1z -frounding-math   -Wall -frounding-math -o CMakeFiles/dynamic_properties_test.dir/dynamic_properties_test.cpp.o -c /home/cgal_tester/build/src/cmake/platforms/Ubuntu-latest-GCC6-CXX1z/test/Proper …
```
> Use std::uncaught_exceptions() when available

- Polyhedron/demo/Polyhedron/Plugins/Classification/CMakeLists.txt
Set two variables in CMakeLists.txt
* Issue(s) solved (if any): fix #2690
> win32 fix concerning bzip headers in the classification plugin CMakeLists.txt

- Property_map/include/CGAL/Dynamic_property_map.h
Address warning seen in the [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-168/AABB_tree/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release.gz)
> Property_map: Remove unused parameter (leading to a warning)

- Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h
- Optimal_transportation_reconstruction_2/test/Optimal_transportation_reconstruction_2/test_vertex_edge.cpp
Fix for https://github.com/CGAL/cgal/issues/2787, which was much trickier than I originally thought.
- the `std::bad_alloc` was happening in an orientation test in EPICK
- I found that one of the coordinates of the points in this test was `nan`
- I figured that it actually came from the fact that the point of the `infinite_vertex()` of a DT2 was used at some point. So there was also a bug in other platforms, but for some reason it was only producing a `nan` on this 32b architecture (on my personal computer, I got random values close to 0).
- In the tests, some internal functions of the algorithms are called but **using elements of a copy of the DT2** as parameters. So of course, tests like `if (v != m_dt.infinite_vertex())` can't work if `v` is not part of `m_dt`.
- After fixing this by …
> OT Reconstruction: Fix test_vertex_edge bug by not copying the TDS

- Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/CMakeLists.txt
- Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/CMakeLists.txt
Remove Qt5::Help from CMakeLists because it causes errors and it is not used.
* Affected package(s):Periodic_3_Triangulation_3 demos
> Fix Fedora_32 errors in the testsuite

- Polyhedron/demo/Polyhedron/MainWindow.cpp
If the filters are empty, filters.first().split(";;") will trigger an assertion and probably segfault, so this PR adds a check before that. If it is empty, it will trigger the warning and return.
> Polyhedron_demo: Fix some crashes when saving an item.

- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_widget.ui
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
- Only call the opposite of the selected halfedge if it is not a border halfedge.
- Add a button to select the whole boundary if in edge selection mode.
* Issue(s) solved (if any): fix #2778
> Polyhedron demo: Fix edge selection -> face selection conversion

- Installation/CMakeLists.txt
- Installation/cmake/modules/CGALConfig_binary.cmake.in
- Installation/cmake/modules/CGALConfig_install.cmake.in
- Installation/cmake/modules/CGAL_Common.cmake
- Installation/cmake/modules/CGAL_SetupFlags.cmake
- Installation/cmake/modules/UseCGAL.cmake
*That is a bug-fix of PR #1436 (see the issue #2793).*
Add a new CMake option `CGAL_DEV_MODE` that I have, for the moment, only document in our public wiki, at
https://github.com/CGAL/cgal/wiki/CGAL_DEV_MODE
@sloriot:
- is the documentation sufficient?
- where should it be linked in the wiki?
* Issue(s) solved (if any): fix #2793
> Add CGAL_DEV_MODE

- CGAL_Core/include/CGAL/CORE/BigFloat_impl.h
- CGAL_Core/include/CGAL/CORE/CoreAux_impl.h
- Installation/CMakeLists.txt
- Installation/cmake/modules/CGAL_SetupCGALDependencies.cmake
- Profiling_tools/include/CGAL/Real_timer_impl.h
- Stream_support/include/CGAL/IO/io.h
Replace functions by "safe" functions that check that no buffer overflow can happen.
* Affected package(s):  ImageIO, Core, Stream_support
* Issue(s) solved (if any): fix #2818
> Address the warning concerning SCL_SECURE for VC++

- Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h
- Mesh_3/test/Mesh_3/test_meshing_polyhedron_with_features.cpp
We add the function `CGAL::Polyhedral_mesh_domain_with_features_3::polyhedra()`. 
* Issue(s) solved (if any): fix #2766
> Mesh_3: Add access function to the stored polyhedra 

- Triangulation_2/test/Triangulation_2/include/CGAL/_test_line_face_circulator.h
Address [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-173/Triangulation_2/TestReport_gimeno_Fedora-rawhide.gz)
```
test/Triangulation_2/include/CGAL/_test_line_face_circulator.h:94:13: warning: unnecessary parentheses in declaration of 'lt' [-Wparentheses]
Locate_type(lt);
^
```
> Triangulation_2: fix a warning in  test/.../_test_line_face_circulator.h

- Number_types/include/CGAL/double.h
- Number_types/include/CGAL/float.h
> Number_types: Call std::isfinite() if possible

- Installation/CMakeLists.txt
- Segment_Delaunay_graph_Linf_2/include/CGAL/Segment_Delaunay_graph_Linf_2/Voronoi_vertex_sqrt_field_new_C2.h
Set CGAL_PROFILE to ON  if CGAL_ENEABLE_CHECK_HEADERS is ON.
* Issue(s) solved (if any): fix #1622
> CGAL_ENABLE_CHECK_HEADERS implies CGAL_PROFILE

- Installation/include/CGAL/config.h
- STL_Extension/include/CGAL/assertions.h
...and move the macro before the functions.
* Affected package(s):  STL_extensions (assertions.h)
* Issue(s) solved (if any): fix #2826
> Define CGAL_NORETURN also for VC++ 

- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Algebraic_curve_kernel_2.h
- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Curved_kernel_via_analysis_2_functors.h
- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Make_x_monotone_2.h
- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Sweep_curves_adapter_2.h
- GraphicsView/include/CGAL/Qt/PointsInKdTreeGraphicsItem.h
- STL_Extension/include/CGAL/iterator.h
... as replacement for the deprecated `std::iterator`.  It is only an implementation detail, that is we do not document it. 
* Affected package(s): `STL_extension`, ` Algebraic_kernel_d`, `Arrangement_on_surface_2`, `GraphicsView` 
* Issue(s) solved (if any): fix #2832
> STL_extension: Introduce CGAL::iterator 

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Output_builder_for_autorefinement.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Visitor.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_nodes.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/intersection.h
This brings a few improvements for the non-documented autorefinement functionality in case 3 faces intersect in a point (that is not a common vertex).
More than 3 faces intersecting and coplanar faces are not handled for now.
> Improve internal autorefinement function

- Combinatorial_map/include/CGAL/internal/Combinatorial_map_copy_functors.h
Bug fix when copying attributes of a cmap into another cmap, and both have no info.
Copy also attribute in this special case.
* Affected package(s): CMap
> CMap bug fix in copy

- Solver_interface/include/CGAL/Diagonalize_traits.h
upper case variables are more likely to be defined as macro in other code (especially EPSILON).
> do not use uppercase name for variables

- Installation/cmake/modules/CGAL_Common.cmake
If the environment variable `CGAL_DEV_MODE` is set to a "true" value,
according to CMake, then the `CGAL_DEV_MODE` CMake option is `ON` by
default.
https://cmake.org/Wiki/CMake/Language_Syntax#CMake_supports_boolean_variables.
> CMake considers an empty string, "FALSE", "OFF", "NO", or any string
> ending in "-NOTFOUND" to be false. [..] Other values are true.
That improves the PR #2799.
> Set the default value of CGAL_DEV_MODE from the env variable

- Generator/examples/Generator/random_points_on_triangle_mesh_2.cpp
- Generator/include/CGAL/internal/Generic_random_point_generator.h
- Generator/include/CGAL/point_generators_2.h
- Generator/test/Generator/generic_random_test.cpp
`random_points_in_triangle_mesh_2` is supposed to generate points in the interior faces of a 2D triangulation, but it didn't check if faces were interior or not. Tests were also broken.
* Affected package(s): `Generator`
> Generator: Fix `random_points_in_triangle_mesh_2`

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/PLY_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/Surface_mesh_io_plugin.cpp
- Three/include/CGAL/Three/Polyhedron_demo_io_plugin_interface.h
- Adds a function to IO plugins interface.
It decides if the plugin should be the default plugin for saving a given item.
- Set off_plugin as default saver for polygon soups and polyhedron_items, surface_mesh_io_plugin for surface_mesh_items and PLY_plugin for point_with_normals_items.
This means their first nameFilter(OFF for the 2 first, PLY for the latter) will be the first choice when saving an item.
- When saving a file, if it was loaded, will use its loading-path as default for saving. If it was not loaded, will use the last path used for saving in the current session as default path for saving. If none of the previous cases are applicable, use the same default path as before (which must be the build dir of the demo I think).
* Issue(s) solved (if any): fix #2334
> Polyhedron demo: Save as enhancement

- Random_numbers/include/CGAL/Random.h
Add on overload for `std::size_t`.
An alternative would have been to add 4267  to the disabled warnings in [`Random.h`](https://github.com/CGAL/cgal/blob/master/Random_numbers/include/CGAL/Random.h#L36)
* Affected package(s): Random_numbers
* Issue(s) solved (if any): fix #2555
> Random_numbers: Add overload for uniform_smallint

- Generator/include/CGAL/Random_polygon_2_sweep.h
- Polygon/include/CGAL/Polygon_2/Polygon_2_simplicity.h
- Snap_rounding_2/include/CGAL/Snap_rounding_2.h
Latest version of g++ generates an error if an `operator()` used as compare function is not  `const`.
* Affected package(s):  Polygon, Generator, Snap_rounding
> Declare several operator() used for comparisons const

- Polyhedron_IO/include/CGAL/IO/STL_reader.h
- Polyhedron_IO/test/Polyhedron_IO/stl2off.cpp
A critical instruction was hidden within the patch of #2657
I do have a question for @afabri:
Your patch will not work as soon as the optional name after solid is too long. Indeed, you require that _facet_ is found before reaching the 80th character (as it's the limit of the header in binary format). Shall we consider this as an issue?
> Fix reading of ASCII STL

- Polyhedron/demo/Polyhedron/MainWindow.cpp
After #2759 the statistics action disappeared from the context menu of the sceneview if more than one item was selected. This PR put it back.
> Polyhedron demo: Restore statistics for multiple items

- Cartesian_kernel/include/CGAL/Cartesian/Circle_3.h
While working on a branch we are currently developing, @danston found a bug in the Cartesian kernel that was actually the same as https://github.com/CGAL/cgal/pull/561 but with `Circle_3`. The fix is very similar, we use an internal `struct` that is the same as a `std::pair` and it fixes it.
* Affected package(s): pretty much all of them…
> Bugfix: pair not compatible with Circle_3 (clang)

- Polyhedron/demo/Polyhedron/Plugins/PMP/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/PMP/Orient_soup_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h
Add an action to Orient_polygon_soup_plugin that creates a polyline from non manifold edges of a soup,
and another action for non-manifold vertices to points.
> Polyhedron demo: Make Polyline from non manifold edges

- Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
- Scripts/developer_scripts/create_new_release
This PR fixes a possible mistake in cgal_create_release_with_cmake (in a regex) and add an argument to specify a beta number in create_new_release.sh.
* Issue(s) solved (if any): fix #2881
> Update release scripts

- Mesh_3/include/CGAL/Implicit_to_labeling_function_wrapper.h
- Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
- Nef_3/include/CGAL/Nef_polyhedron_3.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Visitor.h
In `Nef_polyhedron_3`, this PR fixes the use of `typedef`s for Visual Studio versions >= 2017, with and without the `/permissive-` flag.
The use of these typedefs is valid for VS>=2017, and needed when using VS2017 with `/permissive-`
* Affected package : `Nef_3`
* partially solves issue #2414
> Use of /permissive- with Visual Studio 2017

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Output_builder_for_autorefinement.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Visitor.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_nodes.h
Fix for the case when the input surface is pinched along an edge
This happens when you have a ridge and some edges perpendicular to the ridge are duplicated on each side of the ridge. You then have some volume trapped by the intersection polyline.
This PR also ships a fix when using exact constructions with autorefinement.
> Autorefine bugfixes

- Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
The hash used to set $Id$ was HEAD and not the hash of the last modification of each file.
> Use the hash of the last modification per file

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/self_intersection_surface_mesh_test.cpp
Handle degenerate faces in `does_self_intersect()` and `self_intersections()`
> Handle degenerate faces in self-intersection tests

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
Position request (ctrl + click) and region selection (shift + click) on point sets were buggy when an item has very large coordinates (and the `offset` trick was used). This fixes it.
* Affected package(s): Polyhedron Demo
> Polyhedron demo: Fix Region Selection / Position Request

- Algebraic_kernel_d/include/CGAL/RS/rs2_calls.h
- Installation/cmake/modules/FindMPFI.cmake
1. Check that MPFR and MPFI versions are compatible. This is done at CMake level.
2. Forbid the compilation of code using RS if the version of MPFR is between 3.1.3 and 3.1.6 (this modifies the previous code, where version 3.1.6 was not forbidden).
3. Fix a typo in the static assertion of the previous item.
* Affected package(s): Algebraic_kernel_RS, Number_types_Gmpfi
* Issue(s) solved (if any): #2797
> Algebraic kernel d RS-Fix compatibility of MPFR, MPFI and RS.

- Polyhedron/demo/Polyhedron/Viewer.cpp
- Polyhedron/demo/Polyhedron/Viewer.h
This PR overrides another function of QGLViewer to add a misisng makeCurrent().
Fix #2601.
> Polyhedron demo: More fixes for the Viewer

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp
Check if the c3t3 type is really Fake_c3t3 before trying to load an input .mesh. 
As I still have no clue what example file is supposed to be a "Fake_c3t3" I could not test I didn't break anything.
* Issue(s) solved (if any): fix #2858
> Polyhedron_demo : Add a check before trying to load a cdt_3 to avoid crashing

- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/CMakeLists.txt
Fixes the cmake warning on the Ubuntu test platform.
* Affected package(s):Surface_mesh_parameterization
> Surface_mesh_parameterization: Fix CMakeLists.txt for orbifold example

- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
Fix selection_item's tooltip so it shows the number of selected simplices instead of the number of simplices of the original mesh.
> Polyhedron demo: Fix tooltip for selection item

- Mesh_3/benchmark/Mesh_3/CMakeLists.txt
- Mesh_3/examples/Mesh_3/CMakeLists.txt
- Point_set_processing_3/examples/Point_set_processing_3/CMakeLists.txt
- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Triangulation_3/demo/Triangulation_3/CMakeLists.txt
Prefix CMake options `ACTIVATE_CONCURRENT_<something>` with `CGAL_`.
- in `examples/Mesh_3/`,
- in `examples/Point_set_processing_3/`,
- in `demo/Polyhedron/`, and
- in `demo/Triangulation_3/`.
Cc @afabri 
* Targets CGAL-4.12-beta2
* Affected package(s): Mesh_3, Triangulation_3, Polyhedron demo, Point_set_processing_3
> Prefix CMake options with `CGAL_`

- Boolean_set_operations_2/doc/Boolean_set_operations_2/Boolean_set_operations_2.txt
The typos are [here](https://doc.cgal.org/latest/Boolean_set_operations_2/index.html#title14)
> Boolean Set Operations: Fix typos

- .travis.yml
- .travis/build_package.sh
- .travis/generate_travis.sh
- .travis/install.sh
- .travis/packages.txt
- .travis/template.txt
- Scripts/developer_scripts/cgal_check_dependencies.sh
This PR removes the polyhedron_demo from the travis matrix, as it timeouts too often. 
It also optimizes the installation script so it doesn't take 5min+ anymore, reduces the depth of the CGAL clone to 3 instead of default 50, and it only installs openMesh for the jobs that need it. 
A run that doesn't touch any dependency, is done in ~50min.
> Travis: Time enhancement

- Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h
- Polygon/test/Polygon/AlgorithmTest.cpp
- Polygon/test/Polygon/SimplicityTest.cpp
Currently, `is_simple()` and similar segfault if called on an empty polygon / range. This PR checks for emptiness. `True` is chosen for symmetry with `is_convex`, which returns `true` when the polygon/range is empty.
* Affected package(s): `Polygon`
> Polygon: avoid segfaulting when the polygon/range is empty

- Triangulation_3/include/CGAL/Delaunay_triangulation_3.h
- Triangulation_3/include/CGAL/Regular_triangulation_3.h
If the input point set is degenerate, `dimension() < 3` might always be `true` and we will eventually try to read beyond the end of the input point range.
* Affected package(s): `Triangulation_3`
* Issue(s) solved (if any): fix #2922 
> T3: Fix missing bound check in the sequential insertion phase of parallel triangulations

- Box_intersection_d/doc/Box_intersection_d/CGAL/Box_intersection_d/Box_d.h
- Box_intersection_d/doc/Box_intersection_d/CGAL/Box_intersection_d/Box_traits_d.h
- Box_intersection_d/doc/Box_intersection_d/CGAL/Box_intersection_d/Box_with_handle_d.h
- Box_intersection_d/doc/Box_intersection_d/CGAL/box_intersection_d.h
- Box_intersection_d/doc/Box_intersection_d/Concepts/BoxIntersectionTraits_d.h
- Box_intersection_d/include/CGAL/box_intersection_d.h
- Box_intersection_d/test/Box_intersection_d/test_box_grid.cpp
One of the overloads of `box_self_intersection_d` did not propagate the value of  `cutoff`.
Also minor fixes and enhancements to the documentation to make it clearer when address-based IDs shouldn't be used.
* Affected package(s): `Box_intersection_d`
> Box intersection d : minor bug fix and doc enhancement

- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
- Cartesian_kernel/include/CGAL/constructions/kernel_ftC3.h
`possibly` will return true in case the evaluation lead to true or false
as possible values. If the exact value is computed or interval refined,
false could be the true value which has a consequence will give a
different result for point or base vector.
> Fix the determinism of the computation of point and base vectors

- Mesh_3/doc/Mesh_3/Concepts/MeshComplexWithFeatures_3InTriangulation_3.h
- Mesh_3/include/CGAL/Mesh_complex_3_in_triangulation_3.h
This PR fixes 2 doc bugs in the `MeshComplexWithFeatures_3InTriangulation_3` (package `Mesh_3`).
- `number_of_corners(corner_index)` is documented but makes no sense because there cannot be 2 corners with the same index, so I remove it from the doc
- `number_of_corners()` was documented but not implemented. Now it's both.
* Affected package : Mesh_3
> C3T3 doc fix : `number_of_corners()`

- Cartesian_kernel/include/CGAL/Cartesian/Aff_transformation_rep_2.h
- Cartesian_kernel/include/CGAL/Cartesian/Aff_transformation_rep_3.h
- Cartesian_kernel/include/CGAL/Cartesian/Rotation_rep_2.h
- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Edge_sorter.h
- Homogeneous_kernel/include/CGAL/Homogeneous/Aff_transformationH2.h
- Homogeneous_kernel/include/CGAL/Homogeneous/Aff_transformationH3.h
- Intersections_2/include/CGAL/Segment_2_Segment_2_intersection.h
- Visibility_2/include/CGAL/Rotational_sweep_visibility_2.h
- Replace the third `case` with `default` in ternary `switch`. 
- Declare an `operator<()`  const
* Affected package(s): Kernel_23, Intersections_2, Convex_decomposition_3
> More fixes for GNU 8.0.1: fallthrough warnings  and constness

- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Algebraic_curve_kernel_2.h
- Algebraic_kernel_d/test/Algebraic_kernel_d/Curve_pair_analysis_2.cpp
- Algebraic_kernel_d/test/Algebraic_kernel_d/Real_embeddable_traits_extension.cpp
- Algebraic_kernel_d/test/Algebraic_kernel_d/include/CGAL/_test_algebraic_kernel_2.h
`Curve_pair_analysis_2` sorts the pair based on a pointer comparison. Instead of fixing all `assert` in the testsuite, we don't swap in the testsuite. 
* Affected package(s): Algebraic_kernel_d
* Issue(s) solved (if any):  [cgal-develop] Tracking down the bug of Curve_pair_analysis_2
> Fix Algebraic_kernel_d testsuite

- BGL/include/CGAL/boost/graph/METIS/partition_graph.h
I left obsolete includes in one of the partition headers in #2723. This PR fixes that.
@afabri BGL still includes PMP in https://github.com/CGAL/cgal/blob/master/BGL/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h#L27.
* Issue(s) solved (if any): fix #2934 
> BGL: Remove PMP dependency in partition_graph.h

- Installation/CMakeLists.txt
- Installation/cmake/modules/CGALConfig_binary.cmake.in
- Installation/cmake/modules/CGALConfig_install.cmake.in
- Installation/cmake/modules/CGAL_SetupFlags.cmake
- Installation/cmake/modules/CGAL_enable_end_of_configuration_hook.cmake
- Installation/lib/cmake/CGAL/CGALConfig.cmake
- With `CGAL_DEV_MODE`, the default of `CMAKE_BUILD_TYPE` is now "Release" instead of "Debug"
- Add a warning at the end of the configuration, when `CMAKE_BUILD_TYPE` is either empty or "Debug".
* Affected package(s): CMake, all CGAL
@sgiraudot @MaelRL Could you try again, now?
As for the default `CMAKE_BUILD_TYPE`, I found out that we can set a variable `CMAKE_BUILD_TYPE_INIT` to initialize it, but it has to be set before the call to `project(..)`. Do we want that?
> Improve CMake scripts,  continued

- BGL/include/CGAL/boost/graph/parameters_interface.h
- BGL/include/CGAL/boost/graph/selection.h
- BGL/test/BGL/test_cgal_bgl_named_params.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
- No longer use `Euler::add_face()` that can lead to bugs depending on the insertion sequence
- Compactify the domain to be remeshed
- Allow change of genus
- clean up debug message
- better usage of named parameter
- fix an incorrectly named function in PMP
* Affected package(s): PMP, BGL, Demo
> Improvement of self-intersection removal using local remeshing

- BGL/doc/BGL/Doxyfile.in
- BGL/doc/BGL/PackageDescription.txt
- BGL/package_info/BGL/dependencies
- Nef_3/doc/Nef_3/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
- Nef_3/doc/Nef_3/PackageDescription.txt
- Nef_3/doc/Nef_3/dependencies
- Nef_3/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
- Nef_3/package_info/Nef_3/dependencies
Move `<BGL/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h>` from BGL to Nef_3, without changing the directory. Also move the documentation.
* Affected package(s): BGL, Nef_3
* Issue(s) solved (if any): fix #2934
> Move file from BGL to Nef_3

- Subdivision_method_3/examples/Subdivision_method_3/CatmullClark_subdivision.cpp
- Subdivision_method_3/examples/Subdivision_method_3/Customized_subdivision.cpp
- Subdivision_method_3/examples/Subdivision_method_3/DooSabin_subdivision.cpp
- Subdivision_method_3/examples/Subdivision_method_3/Loop_subdivision.cpp
- Subdivision_method_3/examples/Subdivision_method_3/Sqrt3_subdivision.cpp
- Subdivision_method_3/include/CGAL/Subdivision_method_3/subdivision_hosts_3.h
- Subdivision_method_3/include/CGAL/Subdivision_method_3/subdivision_methods_3.h
- Subdivision_method_3/package_info/Subdivision_method_3/dependencies
Use named parameters from the BGL package. That will remove the dependency from Subdivision (LGPL) to PMP (GPL).
* Affected package(s): Subdivision_method_3
> Subdivision: Use named parameters from the BGL package

- Installation/include/CGAL/Surface_mesh/Surface_mesh_fwd.h
- Mesh_3/include/CGAL/Triangle_accessor_3.h
- Mesh_3/package_info/Mesh_3/dependencies
- TDS_2/include/CGAL/Triangulation_utils_2.h
- TDS_2/package_info/TDS_2/dependencies
- TDS_3/include/CGAL/Triangulation_simplex_3.h
- TDS_3/include/CGAL/Triangulation_utils_3.h
- TDS_3/include/CGAL/internal/Dummy_tds_3.h
- TDS_3/include/CGAL/internal/Triangulation_ds_circulators_3.h
- TDS_3/include/CGAL/internal/Triangulation_ds_iterators_3.h
- TDS_3/package_info/TDS_3/dependencies
Before the patch Mesh_3 was dependent on Surface_mesh. And the split between TDS_23 and Triangulation_23 was wrong.
* Affected package(s): T2, T3, Mesh_3
> Mesh_3, T2, T3: fix dependencies by moving files

- .travis/build_package.sh
- .travis/install_openmesh.sh
- Scripts/developer_scripts/cgal_check_dependencies.sh
Remove the verbose option in install_openmesh.sh so the logs are less polluted.
Also fix the name of the cmake variable that computes dependences.
> Travis: Fixes

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
The `Scene_surface_mesh_item` was not setting `is_bbox_computed` to `true` after computing its bbox, 
and the bbox was not invalidated in `invalidateOpenGLBuffers()` neither in it nor in the `Scene_polyhedron_item`.
This PR also adds a call to `item->itemChanged()` after validating a deformation, to trigger the update of the `Info` view.
* Issue(s) solved (if any): fix #2959
> Polyhedron demo: Fix Bbox computation in facegraph_items

- Number_types/include/CGAL/Mpzf.h
Remove two semicolons that are not required at this position and can trigger warnings in code that includes CGAL when compiling with MSVC.
> Remove unnecessary semicolons

- Convex_hull_3/doc/Convex_hull_3/CGAL/Convex_hull_traits_3.h
- Convex_hull_3/doc/Convex_hull_3/CGAL/convex_hull_3.h
- Convex_hull_3/examples/Convex_hull_3/lloyd_algorithm.cpp
- Convex_hull_3/examples/Convex_hull_3/quickhull_3.cpp
- Convex_hull_3/include/CGAL/Convex_hull_3/dual/halfspace_intersection_3.h
- Convex_hull_3/include/CGAL/Convex_hull_traits_3.h
- Convex_hull_3/include/CGAL/convex_hull_3.h
- Convex_hull_3/include/CGAL/convex_hull_3_to_polyhedron_3.h
- Convex_hull_3/package_info/Convex_hull_3/dependencies
- Convex_hull_3/test/Convex_hull_3/convex_hull_traits_3_fp_bug.cpp
- Convex_hull_3/test/Convex_hull_3/quickhull_degenerate_test_3.cpp
- Convex_hull_3/test/Convex_hull_3/quickhull_test_3.cpp
- HalfedgeDS/include/CGAL/HalfedgeDS_default.h
- HalfedgeDS/include/CGAL/HalfedgeDS_items_2.h
- HalfedgeDS/include/CGAL/HalfedgeDS_list.h
- HalfedgeDS/include/CGAL/HalfedgeDS_vector.h
- HalfedgeDS/include/CGAL/boost/graph/graph_traits_HalfedgeDS.h
- HalfedgeDS/include/CGAL/boost/graph/graph_traits_HalfedgeDS_default.h
- HalfedgeDS/package_info/HalfedgeDS/dependencies
- Installation/CHANGES.md
- Installation/include/CGAL/Polyhedron_3_fwd.h
- Point_set_processing_3/include/CGAL/Point_set_processing_3/internal/Voronoi_covariance_3/voronoi_covariance_3.h
- Point_set_processing_3/package_info/Point_set_processing_3/dependencies
- Point_set_processing_3/test/Point_set_processing_3/normal_estimation_test.cpp
- Polyhedron/include/CGAL/Polyhedron_3.h
- The halfspace intersection function now uses `HalfedgeDS_default` instead of  `Polyhedron_3` internally.
- In order to use the convex hull functions with `Polyhedron_3` as default, the user is in charge to include the header file.
> Convex_hull_3: Remove dependency on Polyhedron_3

- Ridges_3/include/CGAL/Ridges.h
- Ridges_3/package_info/Ridges_3/dependencies
Replace the estimation of the size of the domain with a bbox instead of  the smallest enclosing sphere. (ok given by @pougetma)
* Affected package(s): Ridges_3
> Ridges_3: Remove dependency on Bounding_volumes

- Documentation/doc/Documentation/Installation.txt
- Installation/CHANGES.md
- Maintenance/public_release/announcement/mailing-beta.eml
Document pure header-only.
The new documentation is in the ["section 7.3 Header-only Option" of the installation manual][doc].
I have split that section into two:
- 7.3.1 Header-only with CMake Configuration
- 7.3.3 Possible Problem on Windows
and I have added:
- 7.3.2 Header-only without CMake configuration
[doc]: https://cgal.geometryfactory.com/~lrineau/Documentation-CMake_pure_header_only-GF/Manual/installation.html#subsection_headeronly
* Affected package(s): Doc
* Issue(s) solved (if any): fix #2656 
@CGAL/geometryfactory Please do a quick review. I want to merge this PR as soon as possible, before tomorrow evening.
> Documentation pure header-only, for CGAL-4.12

- .travis/install.sh
Sometimes, install.sh runs fine but exits with code 100. I suppose it is caused by a warning about ppas that are not well secured, which does not trigger a failure for the || operator, but does when exiting the script with a non 0 code. 
I added exit 0 at the end of the file, to insure that if the script executed until the end, then we don't consider any error.
> Travis: Fix install.sh

- Algebraic_foundations/include/CGAL/Test/_test_algebraic_structure.h
- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Arc_2.h
- STL_Extension/test/STL_Extension/test_namespaces.cpp
- Skin_surface_3/test/Skin_surface_3/subdivision_test.cpp
* Affected package(s): Arrangement_2, STL_Extensions, Skin_surface, Algebraic_foundations
* Issue(s) solved (if any): fix #2970
> Fix clang 6.0 warnings

- Scripts/developer_scripts/check_licenses
In the script check_licenses, the existance of the file INSTALL is checked to decide if we are in the right directory, but this file is now named INSTALL.md. 
> Scripts: Fix check_licenses

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane.h
The (x/y/z)-scaling was badly applied to the result of getTranslation().
> Polyhedron demo: Fix Image Reader with Offset

- BGL/include/CGAL/boost/graph/helpers.h
Orient icosahedron CW to fit the orientation of other helpers.
* Affected package(s):BGL
* Issue(s) solved (if any): fix #2975
> BGL: fix orientation of make_icosahedron()

- Polyhedron/demo/Polyhedron/Plugins/PMP/Orient_soup_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h
Don't add NM edges extremities to NM vertices item when extracting the Non-Manifold Simplices of a polygon soup.
> Polyhedron demo: Fix NM simplices extraction

- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/PMP/CMakeLists.txt
Update the CMakeLists.txt of the demo so MeanCurvatureFlow skeleton plugin and item are not compiled if Eigen was not found.
* Issue(s) solved (if any): fix #2996
> Polyhedron demo: Fix MCF whithout Eigen

- README.md
Add links as otherwise you only find them when you click on wiki
>  Add links for new developers in the README

- Documentation/doc/resources/1.8.13/cgal_stylesheet.css
- Documentation/doc/resources/1.8.14/cgal_stylesheet.css
This PR fixes:
- a bug in Doxygen 1.13 CSS: the vertical bar separating the navtree from the content is now fully from the top to the bottom,
- an annoying feature: now the floating table of content is no longer limited to a width of 200 pixels.
* Affected package(s): Doxygen documentation
> CSS tweaks, for CGAL-4.12

- Point_set_processing_3/include/CGAL/IO/read_ply_points.h
When reading `elements` in a PLY header, vertices and faces where correctly handled but other elements were not ignored, leading to their properties being assigned to vertices (or faces, depending on the order). This PR makes other elements ignored. It is based on `master` as the code is quite different in `4.11` and this release requires another fix (I'm doing it right now).
* Affected package(s): Point Set Processing, Point Set 3, Polyhedron demo
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/3012
> PSP: Fix PLY reading properties other than those of vertices

- Point_set_processing_3/include/CGAL/IO/read_ply_points.h
(Same as https://github.com/CGAL/cgal/pull/3013 but for `4.11`, when PLY faces were not handled yet.)
* Affected package(s): Point Set Processing, Point Set 3, Polyhedron demo
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/3012
> PSP: Fix PLY reading properties other than those of vertices (4.11)

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/Polyhedron_demo.cpp
With this PR, all the logs for the plugins loading are hidden, unless the demo has been launched with the --verbose option. Logs for the scripts are unaffected.
* Issue(s) solved (if any): fix #2439
> Polyhedron demo: Add a verbose option

- Installation/CHANGES.md
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3.h
- Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Efficient_RANSAC_traits.h
- Point_set_shape_detection_3/test/Point_set_shape_detection_3/CMakeLists.txt
- Point_set_shape_detection_3/test/Point_set_shape_detection_3/deprecated_test_scene.cpp
`Efficient_RANSAC_traits` was renamed `Shape_detection_traits`, but this breaking change was not documented and no backward-compatibility was provided.
This PR:
- updates `CHANGES.md`
- reintroduces back the class with the old name along with a deprecated warning
> Shape detection: fix undocumented breaking change

- Polyhedron/demo/Polyhedron/MainWindow.cpp
The algorithm detecting the presence or the absence of the typed extension in the filter list was incorrect. This fixes it, so cube.off won't be saved as cube.off.off and test.polylines.txt won't be saved as test.polylines.txt *.cgal, for example.
> Polyhedron demo: fix Save as 

- Polygon/doc/Polygon/PackageDescription.txt
- Polygon/doc/Polygon/Polygon.txt
- Polygon/include/CGAL/General_polygon_with_holes_2.h
Add anchors as otherwise the first word of the section title is used as anchor and not displayed.
Add a section for the classes `Polygon_with_holes_2` and `General_polygon_with_holes_2`.
* Affected package(s): Polygon_2
> Polygon_2: Fix Section Headings

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
Put parenthesis around subexpressions.
It looks like a compiler bug though. Independently from this PR I will try to boil it down in order to make a bug report.
* Affected package(s): Polygon_mesh_processing, Mesh_3
* Issue(s) solved (if any): [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-224.shtml)
> Fix compilation error with VC2017 and -permissive-   

- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
If the isolated vertices are removed from the mesh after its creation , its garbage needs to be collected, or the edges will be messy.
> Polyhedron demo: Fix the orientation of polygon soup to surface_mesh

- STL_Extension/include/CGAL/hash_openmesh.h
Looking at the commit dates, both changes made it into the same master batch.
* Affected package(s): `STL_Extensions`
> STL_Extension: Fix a leftover std::unary_function

- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Error_code.h
`inline`  function to avoid an "already defined" error.
* Affected package(s): Surface_mesh_parameterization
* Issue(s) solved (if any): raised on [stackoverflow](https://stackoverflow.com/questions/49732958/multiple-definition-of-cgalsurface-mesh-parameterizationget-error-messagei)
> Surface_mesh_parameterization: inline get_error_message()

- Documentation/doc/scripts/testsuite.py
In the python script construction the new rows, there were an indentation error in a for loop, which made the warning sum for 1.8.13 the same as the one from master.
> Documentation: Fix 1.8.13 column

- Polyhedron/demo/Polyhedron/resources/shader_flat.g
- Polyhedron/demo/Polyhedron/resources/shader_flat.v
Fixes the flat_shader used for unicolor polyhedron_items with OpenGL 4.3.
> Polyhedron demo: Fix Polyhedron Lighting

- CGAL_ipelets/demo/CGAL_ipelets/mst.cpp
Oops, I forgot to remove part of the console output from the example when I copied it to the ipelet...
* Affected package(s): CGAL_ipelets
> Remove debug printing

- Installation/CHANGES.md
- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
This PR makes the CDT_2 less verbose by moving some error streamed information to a compilation warning, and it adds an overload for the `intersect()` function that use a new tag to throw an exception when the constrained edges intersect.
* Affected package(s):Triangulation_2
* Issue(s) solved (if any): fix #2752 
* Feature/Small Feature (if any): [New_Exception_in_Constrained_triangulation_2](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/New_Exception_in_Constrained_triangulation_2)
> Triangulation_2: Make CDT_2 less verbose

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/intersection.h
PMP::do_intersect() for 2 meshes work with 2 different types of VPM **as long as their value_type is the same.**
* Issue(s) solved (if any): fix #3047
> PMP: do_intersect() work with 2 types of VPM

- Classification/include/CGAL/Classification/Point_set_feature_generator.h
- Property_map/include/CGAL/property_map.h
`Default_property_map` should return the value that is chosen in the constructor. 
I also extended it to be a writable property map, with the idea that we don't have (or I can't find) a nice dummy property map that is also writable. It would then replace custom pmaps such as [No_mark](https://github.com/CGAL/cgal/blob/2cec8e6aca6cab7b5e733fc88ac6baed99560d0c/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h#L39).
* Affected package(s): `Property_map`
> Property map: fix get() not returning the default value

- AABB_tree/doc/AABB_tree/Concepts/AABBGeomTraits.h
- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
- Homogeneous_kernel/include/CGAL/Homogeneous/function_objects.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_constructions_3.h
Add an operator for a Ray_3 to ConstructProjectedPoint_3 and Construct_projected_point_3.
* Affected package(s):Kernel_23
* Issue(s) solved (if any): fix #3044
* Feature/Small Feature (if any): [Kernel_23_ConstructProjectedPoint_3_for_Ray_3](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Kernel_23_ConstructProjectedPoint_3_for_Ray_3)
* Pre-approved by @lrineau 25 April 2018
> Kernel: Add an operator for a Ray_3 to ConstructProjectedPoint_3

- Alpha_shapes_2/include/CGAL/internal/Lazy_alpha_nt_2.h
- Alpha_shapes_3/include/CGAL/internal/Lazy_alpha_nt_3.h
`CGAL::internal::Is_traits_point_convertible` is defined twice, namely in `Lazy_alpha_nt_2/3.h` and the two are slighlty different. The fix is to postfix with the dimension.
* Affected package(s): Alpha_shape_2/3
* Issue(s) solved (if any): bugreport by a user
> Alpha_shapes: class template has already been defined.

- GraphicsView/demo/Triangulation_2/TriangulationCircumcircle.h
The `hint` was outdated after `cdt.clear()`, leading to a segfault.
In order to reproduce: generate points, switch on circumcircle, clear, add points.
> Triangulation_2: Fix Constrained Delaunay demo. 

- STL_Extension/include/CGAL/internal/boost/array_binary_tree.hpp
It only served to define some nested types.
> The class std::iterator got deprecated. 

- AABB_tree/include/CGAL/AABB_traits.h
A fix for MSVC 2017 15.7 (Preview 4) with `/permissive-`
MSVC is probably right that it was not a valid C++ code: the previous
version called a static member function of the enclosing class, without
qualification, and that static member function was defined *after*.
@mglisse An interesting exercise of reading the norm. From what I ready [in cppreference][1]:
> c) if this class is nested, the body of the enclosing class until the declaration of this class and the entire body of the base class(es) of the enclosing class.
The part "until the declaration of this class" is the critical argument, in my opinion. As far as I understand, in the first pass of the Two Pass Name Lookup, the code is ill-formed.
[1]: http://en.cppreference.com/w/cpp/language/unqualified_lookup#Class_definition
* …
> A fix for MSVC 2017 15.7 with /permissive-

- Arrangement_on_surface_2/include/CGAL/Arr_circle_segment_traits_2.h
- Arrangement_on_surface_2/include/CGAL/Arr_conic_traits_2.h
As the counter/index is only required to be unique we can make it atomic.
* Affected package(s): Arrangement_2
* Issue(s) solved (if any): fix #1384
> Arrangement_2: Address all remaining points of issue #1384, but the renderer

- .travis.yml
- .travis/build_package.sh
- .travis/install.sh
- .travis/template.txt
- Scripts/developer_scripts/cgal_check_dependencies.sh
The errors due to dependency modification are painful to detect in the over spammed report of travis. 
With this PR, each change reported by the check is listed in the end, so we don't have to grep PKG_DIFF and search for one that is not empty anymore.
> Infrastructure: Enhance dependency managing in Travis

- Documentation/doc/Documentation/Installation.txt
- Fixed links
- Remove a paragraph "Before 4.6 blabla"
- Upgrade minimum VC++
* Affected package(s): Installation Manual
* Issue(s) solved (if any): fix #3078
> Installation: Fix minimum version numbers

- AABB_tree/include/CGAL/AABB_tree.h
- Installation/CMakeLists.txt
- Installation/cmake/modules/run_cmd_redirection_cerr.cmake
- Scripts/developer_scripts/cgal_check_dependencies.sh
- When there is an error in `check_headers`, now the same file is recompiled without `-H`, to display the error without the display of all the included headers.
- In Travis, that check is now triggered with `make -k`, so that the compilation continue with the other headers, in case of an error.
- I have introduced a compilation error on purpose in `<CGAL/AABB_tree.h>` to check the feature.
* Affected package(s): Installation, Travis
> Installation: better check_headers (for Travis)

- Mesh_3/include/CGAL/Mesh_3/experimental/Lipschitz_sizing_experimental.h
- Mesh_3/include/CGAL/Mesh_domain_with_polyline_features_3.h
- Mesh_3/test/Mesh_3/test_domain_with_polyline_features.cpp
This PR introduces functions to add corners in the complex, possibly with curve/patch incidence information.
Notes:
- I have left the functions undocumented since this targets 4.12.
- This version is a bit denser than P3M3 (#2658) and will create conflicts (and this should thus be integrated first).
* Issue(s) solved (if any): Fix #3011 
> Mesh_3: Add `add_corner()` and similar corner-adding functions

- STL_Extension/include/CGAL/internal/boost/array_binary_tree.hpp
Complete the already merged PR #3070
We had a bug in the [VC2013 testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.13-Ic-14/STL_Extension/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz)
> Fix nested types

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Output_builder_for_autorefinement.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h
- Property_map/include/CGAL/property_map.h
- Property_map/test/Property_map/CMakeLists.txt
- Property_map/test/Property_map/test_property_map.cpp
* Affected package(s): Property_map
* Issue(s) solved (if any): fix #2737
> Property_map: Fix make_property_map(std::vector&) for an empty vector

- .travis.yml
- .travis/build_package.sh
- .travis/template.txt
Only interrupt travis before script if all three packages in the job are ignored.
* Issue(s) solved (if any): fix #3112
> Infrastructure: Fix condition for skipping tests in Travis

- .travis.yml
- .travis/template.txt
The checking of Maintenance's dependencies is skipped in build_package.sh but not in the pre-script tests. This fixes it.
> Travis: Skip test of Maintenance's dependencies.

- Documentation/doc/Documentation/Installation.txt
There is no straight skeleton demo + the pattern described to build a demo of a package is not correct (the target named should be used)
> Use a directory that exists

- Documentation/doc/resources/1.8.13/BaseDoxyfile.in
> Fix default mathjax URL for doxygen 1.8.13

- Point_set_processing_3/include/CGAL/structure_point_set.h
- Spatial_searching/doc/Spatial_searching/CGAL/Fuzzy_iso_box.h
- Spatial_searching/doc/Spatial_searching/CGAL/Fuzzy_sphere.h
- Spatial_searching/doc/Spatial_searching/Spatial_searching.txt
- Spatial_searching/examples/Spatial_searching/iso_rectangle_2_query.cpp
- Spatial_searching/include/CGAL/Fuzzy_iso_box.h
- Spatial_searching/include/CGAL/Fuzzy_sphere.h
- Spatial_searching/test/Spatial_searching/Circular_query.cpp
- Spatial_searching/test/Spatial_searching/Iso_rectangle_2_query.cpp
- Spatial_searching/test/Spatial_searching/Point_with_info.h
More serious attempt at fixing inconsistencies in the code and documentation of fuzzy items after some bad commits (c0cbdab and 5ed7255) and the revert (#1808).
- Points in the _interior_ of the inner approximation are always returned
- Points in the _interior_ of the outer approximation and not in the interior of the inner approximation may or may not be returned
- Everything else is never returned
When there is no fuzziness, points on the boundary of the object are not returned. Also:
- Half open boxes so the "interior" is a little weird and buggy
- Inconsistencies between the doc and the code (doc was vague before, I made it wrong with commits mentioned above).
- Points in the inner approximation are always returned (boundary included)
- Points in the outer approximation and not in the …
> Spatial searching: rework fuzzy items

- Kernel_23/doc/Kernel_23/CGAL/Bbox_2.h
- Kernel_23/doc/Kernel_23/CGAL/Bbox_3.h
- Kernel_23/include/CGAL/Bbox_2.h
- Kernel_23/include/CGAL/Bbox_3.h
- Kernel_23/include/CGAL/internal/Projection_traits_3.h
- Triangulation_2/doc/Triangulation_2/Concepts/ConstrainedTriangulationTraits_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
- Triangulation_2/include/CGAL/internal/Triangulation_2_projection_traits_base_3.h
When `Constrained_triangulation_2` computes the intersection of two
segments, with a floating-point number type, and with
`Exact_predicates_tag`, the computed intersection point is snapped to an
extremity of the two segments, if it is closest to 4 ulp (with the l-inf
distance).
That value `4` can be changed by defining the macro
`CGAL_CDT_2_INTERSECTION_SNAPPING_ULP_DISTANCE` to another value.
I have benched on a crazy data set of 56000 segments, intersecting, and with duplicated (or almost duplicated) segments. I did not found more than 0.1s of difference, in a run of 50.0s, and the difference was not always in the same direction.
That is a bug-fix, but I wonder if it should be backported to 4.11.2 and 4.12.1, because that modifies the behavior of the code.
What is more, that choice of …
> Fix CDT_2 errors, using snapping of intersection points

- Triangulation_2/include/CGAL/Regular_triangulation_2.h
- Triangulation_3/include/CGAL/Regular_triangulation_3.h
- Triangulation_3/test/Triangulation_3/test_regular_insert_range_with_info.cpp
A functor in `Regular_triangulation_23` expected the return type of `Construct_point_3(const Weighted_point_3&)` to be a `const Point_3&`. This is not the case with EPECK, which uses a lazy representation and builds points on the fly, resulting in taking references to temporaries.
* Affected package(s): Triangulation_23
> Triangulation_23: fix wrong return type in spatial_sort functor

- Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
- Mesh_3/test/Mesh_3/CMakeLists.txt
- Mesh_3/test/Mesh_3/test_mesh_3_issue_1554.cpp
- Mesh_3/test/Mesh_3/test_meshing_polyhedron_with_features.cpp
- Mesh_3/test/Mesh_3/test_meshing_verbose.cpp
- Mesh_3/test/Mesh_3/test_meshing_with_one_step.cpp
When `CGAL_MESH_3_VERBOSE` is defined, the code path is different and, before this patch, the manifold criterion was without any effect, resulting in a possible non-manifold output surface mesh.
The fix in itself is https://github.com/CGAL/cgal/commit/335034e3cf49ff0764c0f5d5f20a3e20dbc1f813. This PR also adds two tests for two different code paths:
- one for `CGAL_MESH_3_VERBOSE`,
- and one for the use of a loop on `mesher.one_step()`.
> Mesh_3: fix verbose mode (when the manifold criterion is used)

- Triangulation_3/test/Triangulation_3/test_regular_insert_range_with_info.cpp
The merge of #3122 caused some `std::unary_function` to sneak through to the 4.12 branch.
> Triangulation_3: Fix std::unary_function leftover

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h
- Surface_mesher/demo/Surface_mesher/volume.cpp
- Surface_mesher/demo/Surface_mesher/volume.h
- Triangulation_3/include/CGAL/Delaunay_triangulation_3.h
As `Point` seems to be a type that is defined by VC++ we get for VS2017 with `-permissive -std:c++latest` an  [error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.13-Ic-26/Polyhedron_Demo/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz)
include\CGAL/Delaunay_triangulation_3.h(1413): error C2244: 'CGAL::Delaunay_triangulation_3<Gt,Tds_,CGAL::Default,Lock_data_structure_>::side_of_oriented_sphere': unable to match function definition to an existing declaration
Adding `typedef Point Point_;` and using the latter in the method definition solves the problem.
* Affected package(s): Polyhedron demo.
> Polyhedron demo: Remove conflicting 'Point' typedef

- Spatial_searching/include/CGAL/Fuzzy_sphere.h
- Spatial_searching/include/CGAL/Search_traits_adapter.h
- Spatial_searching/test/Spatial_searching/Search_traits_adapter_with_identity_map.cpp
When using a `Search_traits_adapter` with a `key_type` that is the same as the point type of the `Search_traits` base, there was a compilation error:
```sh
(...)/Spatial_searching/include/CGAL/Fuzzy_sphere.h:161:69: error: no type named
'type' in 'boost::disable_if<boost::is_same<CGAL::Point_2<CGAL::Simple_cartesian<double> >,
CGAL::Point_2<CGAL::Simple_cartesian<double> > >, void>'
typename SearchTraits::Point_d> >::type* = 0)
```
The `disable_if` did not work because none of its arguments was template (so it was instantiated anyway). This PR:
- changes the constructor on which `disable_of` is applied: by default, if the adapter and the base have the same type, we enforce passing by the property map (in case this property map does have the same type but is not …
> Spatial Searching: bugfix disable_if

- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- Polyhedron/demo/Polyhedron/triangulate_primitive.h
If the coordinates of the points of a mesh are too big, their triangulation may fail due to exceding the precision of double. To restrain these cases, this PR applies the viewer's offset to the pointsbefore they are inserted in the CDT2.
> Polyhedron demo: Fix triangulation of facets

- Polygon_mesh_processing/doc/Polygon_mesh_processing/NamedParameters.txt
- Polygon_mesh_processing/doc/Polygon_mesh_processing/dependencies
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/bbox.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/border.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/corefinement.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/detect_features.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/fair.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/intersection.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/measure.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/random_perturbation.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/refine.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/transform.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_faces.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h
The word _should_  is too weak for a requirement.
* Affected package(s): Polygon_mesh_processing documentation.
> Polygon_mesh_processing: Change should  to must/shall

- GraphicsView/include/CGAL/Qt/camera_impl.h
- GraphicsView/include/CGAL/Qt/frame_impl.h
- GraphicsView/include/CGAL/Qt/image_interface.h
- GraphicsView/include/CGAL/Qt/qglviewer.h
- GraphicsView/include/CGAL/Qt/qglviewer_impl.h
- Mesh_3/doc/Mesh_3/CGAL/Labeled_mesh_domain_3.h
- Mesh_3/examples/Mesh_3/mesh_3D_gray_image_multiple_values.cpp
- Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
- Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Scene_facegraph_item_k_ring_selection.h
- Polyhedron/demo/Polyhedron/Scene_item.cpp
- Polyhedron/demo/Polyhedron/TextRenderer.cpp
- Polyhedron/demo/Polyhedron/Viewer.cpp
- Polyhedron/demo/Polyhedron/include/id_printing.h
The previous implementation of `get_least_square_surface_plane` and
`project_on_surface`, in `C3T3_helpers`, was using uninitialized
values. Now, it uses `boost::optional`.
> Mesh_3: Fix the warnings about uninitialized variables

- CGAL_Core/include/CGAL/CORE/BigFloat.h
- CGAL_Core/include/CGAL/CORE/BigFloatRep.h
`BigInt` has a constructor from unsigned int but BigFloat hasn't. 
Pb reported on cgal-discuss
> Add missing constructor for unsigned int

- GraphicsView/include/CGAL/Qt/qglviewer_impl.h
- Polyhedron/demo/Polyhedron/Viewer.cpp
- Polyhedron/demo/Polyhedron/Viewer.h
Add a QOpenGLDebugLogger to the viewer to easily track errors and warning from OpenGL. 
Unfortunately this will probably not help us tracking context errors, as this system is dependant of the said context.
> Polyhedron demo: add some OpenGL debugging information 

- Mesh_3/include/CGAL/Labeled_mesh_domain_3.h
- STL_Extension/include/CGAL/exceptions.h
- STL_Extension/include/CGAL/result_of.h
assertions.h includes exceptions.h includes lexical_cast.hpp includes...... a boost/preprocessor heaeder for which VC++ generates a [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.13-Ic-27/Mesh_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz):
C:\CGAL\test\CGAL-4.13-Ic-27\include\CGAL/Labeled_mesh_domain_3.h(401): warning C4003: not enough actual parameters for macro 'BOOST_PP_SEQ_DETAIL_IS_NOT_EMPTY'
> Mesh_3: Suppress warning concerning boost/preprocessor

- Polyhedron/demo/Polyhedron/Polyhedron_demo_plugin_helper.cpp
As it is quite hard to reproduce twice the same bug, I cannot be sure, but this seems to improve the dock widgets management.
> Polyhedron demo : Change the sizing preferency for DockWidgets

- Triangulation_3/doc/Triangulation_3/CGAL/Delaunay_triangulation_3.h
- Triangulation_3/doc/Triangulation_3/CGAL/Regular_triangulation_3.h
- Triangulation_3/doc/Triangulation_3/CGAL/Triangulation_3.h
This PR fixes missing `const&` in function signatures and wrong point types in the function `nearest_power_vertex()` (and similar functions).
* Affected package(s): `Triangulation_3`
* Issue(s) solved (if any): fix #3178 
> Triangulation_3: Minor doc fixes

- Kernel_23/doc/Kernel_23/CGAL/Point_2.h
- Kernel_23/doc/Kernel_23/CGAL/Weighted_point_2.h
- Kernel_23/doc/Kernel_23/CGAL/Weighted_point_3.h
- Kernel_23/include/CGAL/Weighted_point_3.h
The documentation says we can translate weighted points using `operator+(Vector_3)`. In practice, we can't. I'm not too sure about adding overloads for weighted points of predicates/constructions meant to act on (bare) points (see [this comment](https://github.com/CGAL/cgal/issues/3167#issuecomment-396617477)), so the doc is changed instead.
* Issue(s) solved (if any): fix #3167
> Kernel_23: Fix some doc issue with weighted points

- BGL/include/CGAL/boost/graph/io.h
- BGL/include/CGAL/boost/graph/named_params_helper.h
- BGL/package_info/BGL/dependencies
- Linear_cell_complex/benchmark/Linear_cell_complex_2/surface_mesh/IO.h
- Linear_cell_complex/benchmark/Linear_cell_complex_2/surface_mesh/IO_off.cpp
- Point_set_3/package_info/Point_set_3/dependencies
- Polyhedron_IO/include/CGAL/IO/Polyhedron_iostream.h
- Polyhedron_IO/include/CGAL/IO/generic_print_polyhedron.h
- Polyhedron_IO/include/CGAL/IO/print_OFF.h
- Subdivision_method_3/package_info/Subdivision_method_3/dependencies
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Add NamedParameters to the off I/O functions.
* Affected package(s):BGL Polyhedron_3 Surface_mesh LCC 
* Issue(s) solved (if any): fix #3049
> BGL: Use Named Parameters in OFF I/O

- Interpolation/doc/Interpolation/CGAL/sibson_gradient_fitting.h
- Interpolation/examples/Interpolation/interpolation_vertex_with_info_2.cpp
- Interpolation/examples/Interpolation/sibson_interpolation_rn_vertex_with_info_2.cpp
- Interpolation/examples/Interpolation/sibson_interpolation_vertex_with_info_2.cpp
- Interpolation/include/CGAL/interpolation_functions.h
- Interpolation/include/CGAL/sibson_gradient_fitting.h
- Interpolation/test/Interpolation/include/CGAL/_test_interpolation_functions_2.cpp
- Interpolation/test/Interpolation/test_interpolation_functions_2.cpp
Using `::result_type` and `::argument_type` prevents from passing more generic value/gradient functors (such as lambdas).
- `::result_type` can be easily replaced by `result_of`.
- `::argument_type`, which was needed to distinguish between two types (say `T1` & `T2`), is a bit trickier. It is replaced by some SFINAE to check whether one can construct a `std::function<ret(T1/2)>` or not. [Only in C++11]
* Affected package(s): `Interpolation`
> Interpolation: replace usages of Functor::result_type and Functor::argument_type

- Polyhedron/demo/Polyhedron/Viewer.cpp
Set default alpha to 1.0f for PROGRAM_WITH_LIGHT so items using it without transparency don't risk to render buggy.
> Polyhedron Demo: Fix Colors for Polygon soups

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_nodes.h
we abuse the tm2 field to store the second copy of the vertex.
> Make sure identical vertices have identical coordinates in autorefinement

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Offset_meshing_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
Reimplementation of the offset meshing plugin using Mesh_3 instead of Surface_mesher.
At the same time, the plugin can now work from a triangle soup.
This PR is based of the #2739. It will be rebased once #2739 is merged in `master`.
* Affected package(s): Polyehedron demo
> Polyhedron demo: reimplement offset_meshing_plugin with Mesh_3

- Polyhedron/demo/Polyhedron/MainWindow.cpp
Choose etween ':' and ':' as separator in the path to the plugins dir and add it to the global PATH if running on Windows so the potential plugin dependency dlls are found by the linker.
* Issue(s) solved (if any): fix #3204
> Polyhedron Demo: Fix path to external plugins

- wininst/developer_scripts/script_cgal.nsi
Add `CGALConfig.cmake` to the Windows installer. The real `CGALConfig.cmake` is in `lib/cmake/CGAL/`, but that is more convenient if the redirection is also installed by the Windows installer.
* Affected package(s): windows installer
> Add CGALConfig.cmake to the Windows installer

- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
When loading a polygon soup with non-triangular facets, these facets are triangulated. For triangulation, the points are projected in 2D after computing the normal vector of the facet.
In the code, the normal is computed using the cross product of the 3 first points of the facet. But it can happen that these 3 points are aligned, leading to an infinite normal and to an assertion failed in the triangulation construction.
This PR tests other combinations of vertices to find the first non-collinear triple. Tested locally, it fixes the bug I had with a specific dataset with aligned vertices.
> Polyhedron demo: Fix normal facet computation for triangulation

- BGL/include/CGAL/boost/graph/named_params_helper.h
It was ignoring the fact that a vpm could have been given by the user
> Fix GetGeomTraits

- Installation/cmake/modules/CGAL_TweakFindBoost.cmake
ArchLinux has upgraded CMake to a dev version of CMake-3.13, and we have CMake [warnings]:
```
CMake Warning (dev) at /mnt/testsuite/cmake/modules/CGAL_TweakFindBoost.cmake:44 (option):
Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
--help-policy CMP0077" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
For compatibility with older versions of CMake, option is clearing the
normal variable 'CGAL_Boost_USE_STATIC_LIBS'.
Call Stack (most recent call first):
/mnt/testsuite/cmake/modules/CGAL_SetupBoost.cmake:18 (include)
/home/cgal_tester/build/src/cmake/platforms/ArchLinux-CXX14/CGALConfig.cmake:119 (include)
/home/cgal_tester/build/src/cmake/platforms/ArchLinux-CXX14/CGALConfig.cmake:159 (check_cgal_component) …
```
> Set CMP0077 to OLD (new in CMake-3.13)

- Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h
- Polygon/test/Polygon/AlgorithmTest.cpp
When the range of points was of size 3, nothing was returned.
Also, because this is meant to be filtering points in a polygon, added some preconditions:
- there must be at least three points.
- there must be at least three non-collinear points.
* Affected package(s): `Polygon`
> Polygon: Fix `filter_collinear_points()` early return

- Polyhedron/demo/Polyhedron/MainWindow.cpp
Don't ask for  write permission when loading an item.
fix #3196
> Polyhedron demo: Fix Load Item

- Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
If you select item from bottom to up manually, join will make them disappear without joining them
> Fix join plugin

- BGL/include/CGAL/boost/graph/copy_face_graph.h
The algorithm relies on a feature that is not always true if the target mesh has garbage. We make sure the feature is valid.
> Fix copy_face_graph with target mesh having garbage

- BGL/include/CGAL/boost/parameter.h
- Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
- Mesh_3/include/CGAL/Mesh_3/Refine_cells_3.h
- Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
- Mesh_3/include/CGAL/Mesh_3/Refine_facets_manifold_base.h
- Mesh_3/include/CGAL/Mesh_3/Worksharing_data_structures.h
- Mesh_3/include/CGAL/Mesh_error_code.h
- Mesh_3/include/CGAL/refine_mesh_3.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_function.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
A user using the `Sequential_tag` version of Mesh_3 was able to use 
```C++
while(!mesher.algorithm_done())
mesher.one_step()
```
and then add extra logic to control the loop and allow the stop of the algorithm before its end. With `Parallel_tag` that was not possible. This PR adds the possibility via a (yet) undocumented feature.
> Mesh 3 fix: add the possibility to stop the algorithm, when Parallel_tag is used (for CGAL-4.12-branch)

- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
As I don't think it is possible to find which ids are impacted by a modification of the mesh (invalidateOpenGLBuffers() only re-compute everything, it is not possible to track which face(s), edge(s) or vertex(ices) is/are precisely modified), I think the easiest way of not having Ids in the wrong place is to simply hide them all.
> Polyhedron Demo: Hide ids when modifying the mesh

- BGL/include/CGAL/boost/parameter.h
- Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
- Mesh_3/include/CGAL/Mesh_3/Refine_cells_3.h
- Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
- Mesh_3/include/CGAL/Mesh_3/Refine_facets_manifold_base.h
- Mesh_3/include/CGAL/Mesh_3/Worksharing_data_structures.h
- Mesh_3/include/CGAL/Mesh_error_code.h
- Mesh_3/include/CGAL/refine_mesh_3.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_function.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
- STL_Extension/include/CGAL/thread.h
A user using the `Sequential_tag` version of Mesh_3 was able to use 
```C++
while(!mesher.algorithm_done())
mesher.one_step()
```
and then add extra logic to control the loop and allow the stop of the algorithm before its end. With `Parallel_tag` that was not possible. This PR adds the possibility via a (yet) undocumented feature.
> Mesh 3 fix: add the possibility to stop the algorithm, when Parallel_tag is used

- Polyhedron/demo/Polyhedron/Scene.cpp
Fixes snapshots without alpha and fixes the crash that occures when a selection item  and its parent are both in the list of deleted items.
fixes #3246
> Polyhedron Demo: Fix snapshot and erase all

- CGAL_ImageIO/include/CGAL/ImageIO_impl.h
When linking with zlib, always use the gz API, as gzFiles are not compatible with fopen(), fread(),etc. 
* Affected package(s):CGAL_imageIO
> CGAL_imageIO: Fix .inr writing without zlib

- Polyhedron/demo/Polyhedron/Plugins/PMP/Scene_facegraph_item_k_ring_selection.h
Call filter_operations() after a selection using the lasso so the operations on selection are displayed.
> Polyhedron demo: Fix selection plugin

- Mesh_2/include/CGAL/Mesh_2/README
The subdirectory Mesh_2 being used now, this file is useless.
Report on cgal-develop by Joachim.
> Remove outdated file

- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
- Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h
Since CGAL-4.6, the check that avoids inserting a constrain twice was no longer effective. This PR reintroduces the implementation of the check.
* Issue(s) solved (if any): fix #3267
> Implement the check that avoids to insert a constraint twice

- wininst/developer_scripts/script_cgal.nsi
Ship the lib/ sub-directory with the Windows installer, because it contains `lib/cmake/CGAL/CGALConfig.cmake`.
* Affected package(s): Windows installer
* Issue(s) solved (if any): fix #3219
> Ship the lib/ sub-directory with the Windows installer

- Polyhedron/demo/Polyhedron/Plugins/Classification/Cluster_classification.cpp
- Polyhedron/demo/Polyhedron/Plugins/Classification/Point_set_item_classification.cpp
Simple features (based on point set properties, without any computation) were computed in parallel. The problem is that it resulted in temporary references being passed to threads, which lead to segfaults later.
As these features do not require any computation, it's anyway useless to include them in the parallel processing, so I just move them out of the parallel part.
(This bug is not in `4.12`.)
> Classification Plugin Bugfix: do not compute simple properties in parallel

- Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
Fix headers fot statistics in polyhedorn and surface_mesh items so the Null Length is not in the Angles part anymore.
> Polyhedron demo: Fix statistics for facegraph items

- Installation/INSTALL.md
Only * - + are allowed for bullet lists in markdown. Replaced `o` with a star providing a better layout
* Affected package(s): none
> [doc] fix nested bullet list in INSTALL.md

- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
When a non-triangular facet is triangulated in the polygon soup, the first non-aligned three vertices are used to compute the normal: if these 3 vertices form a concavity, the normal is oriented in the wrong direction. To address that, I added a test that computes the 2D projected polygon and checks if its orientation is correct (otherwise, the normal is inverted). That solved the issue on the data where I noticed the problem.
> Polyhedron demo: Fix normal orientation of soup triangulated facet

- Point_set_3/include/CGAL/Point_set_3.h
- Point_set_processing_3/include/CGAL/IO/read_ply_points.h
- Point_set_processing_3/include/CGAL/IO/write_las_points.h
- Point_set_processing_3/include/CGAL/IO/write_ply_points.h
This PR fixes several bugs/badly done things:
- The constness of LAS output functions (issue https://github.com/CGAL/cgal/issues/3320)
- The index of a new point in a point set was not correctly setted when reusing existing memory
- When writing a point set with points using `float`, they were still written as `double` in the PLY output (which is bad because in binary, it doubles the size of the file with no added value)
- One of the three `char` types (`signed char`, `char` and `unsigned char`) was missing for PLY IO
- `char` type appeared as characters in the ASCII PLY output (whereas they should just be numbers)
* Affected package(s): Point Set Processing, Point Set 3
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/3320
> Point set processing IO: Several bugfixes

- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
- Triangulation/doc/Triangulation/Triangulation.txt
The end of the user manual was clipped due to the usage of `\cond`. Using `\if` fixed it.
Introduced by #3057
> Fix PMP user manual

- GraphicsView/include/CGAL/Qt/quaternion.h
- GraphicsView/include/CGAL/Qt/quaternion_impl.h
- GraphicsView/include/CGAL/Qt/vec.h
- GraphicsView/include/CGAL/Qt/vec_impl.h
operators << for vec and quaternion should not be in CGAL::qglviewer namespace (otherwise there is a link error).
* Issue(s) solved (if any): fix #3327
> QGLViewer bugfix 

- Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
- Mesh_3/include/CGAL/Mesh_3/Mesher_level.h
When the stop variable is flipped, cancel unprocessed tasks, instead of just waiting for them to finish.
* Issue(s) solved (if any): fix  #3242
> Mesh_3, parallel: fix the stop feature

- Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
- Scripts/developer_scripts/create_new_release
create_new_release has been updated to get rid of rpm and svn, and use a cmake script instead of the pearl script that creates a release.
PS: the calls to that script will probably have to be updated, as new options have been added.
Also, I could not test the [public] option, so it will have to be tested before integration.
> Maintenance: Use cmake to create a release

- TDS_3/include/CGAL/Triangulation_ds_cell_base_3.h
This patch fixes an undefined behavior: when one want to convert a
handle to a point, we used `&*handle` a lot. But dereferencing the
default-constructed (null) handle, is undefined-behavior.
The patch calls `operator->` of the handle class, instead.
That is similar to c774546e1bc95f79aed9718160d23efc5dc08dc2, from PR #161. This time the undefined-behavior was not detected by the static analyzers of clang, but by [USBAN](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html).
* Affected package(s): TDS_3 (and thus Triangulation_3, Mesh_3, and others)
> `&*handle`, if handle is null, is undefined-behavior

- Circular_kernel_2/doc/Circular_kernel_2/Circular_kernel_2.txt
There was a small bug in the User manual of the 2D Circular Kernel: a citation was missing the \cgalCite macro in Section "4 Design and Implementation History", so it was not linking. Since the bug is so small, I am creating a PR directly against <code>master</code>
* Affected package(s): <code>Circular_kernel_2</code> (documentation)
* Issue(s) solved (if any): none
* Feature/Small Feature (if any): none
* Link to compiled documentation: none
* License and copyright ownership: none
> Small bugfix (User Manual of CK_2)

- Polyhedron/demo/Polyhedron/Plugins/Classification/Cluster_classification.cpp
- Polyhedron/demo/Polyhedron/Plugins/Classification/Point_set_item_classification.cpp
When calling methods to add features in a parallel scope, no temporary object should be used (as documented). This was not the case in the plug-in where the normal map was created on the fly (and destroyed before the launched thread had the chance to use it). This PR fixes it by creating the point map outside of the method.
* Affected package(s): Polyhedron demo only
> Classification plugin bugfix: don't use temp refs in parallel code

- Number_types/include/CGAL/Mpzf.h
With Intel Compiler 2019, in Mesh_3, there was a misscompilation of `Mpzf::clear()`:
https://github.com/CGAL/cgal/blob/bd105ab68d22230eb5419160f48cde76894510aa/Number_types/include/CGAL/Mpzf.h#L304-L311
The line
```c++
while(*--data()==0);
```
was compiled as if:
```c++
while(*(data()-1)==0);
```
that is: the internal pointer `data_` was not decremented, and the loop was never-ending.
I have modified the code slightly to workaround that bug from Intel Compiler. I was not able to find a small test case triggering the bug, unfortunately.
* Affected package(s): Mesh_3, Number_types
Cc: @mglisse
> Mpzf: Workaround a misscompilation bug with Intel Compiler 2019

- Convex_hull_3/include/CGAL/Convex_hull_traits_3.h
- Convex_hull_3/include/CGAL/Extreme_points_traits_adapter_3.h
Replace "hand written" filtering with just calling the functor of the kernel chosen by the user so that static filters are used.
> Convex_hull_3: Fix so that static filters are used

- Point_set_shape_detection_3/include/CGAL/regularize_planes.h
Work around a bug that only happens with `_MSC_VER == 1915`.
See [bug report](https://developercommunity.visualstudio.com/content/problem/340310/unaccepted-typename-that-other-compilers-require.html)
* Affected package(s): Point Set Shape Detection
> Point set shape detection: Fix VC2017 bug

- GraphicsView/include/CGAL/Qt/DemosMainWindow.h
- GraphicsView/include/CGAL/Qt/DemosMainWindow_impl.h
- Polyhedron/demo/Polyhedron/MainWindow.cpp
Always use the same member QSettings in the mainwindow makes it 200ms faster to build an item. This is really significant when loading hundreds of small items.
* Issue(s) solved (if any): fix #3373
> Polyhedron demo: Accelerate the creation of items.

- Cartesian_kernel/include/CGAL/constructions/kernel_ftC2.h
- Kernel_23/test/Kernel_23/issue_3301.cpp
The implementation had a "better", that is more robust version in an ` #else`, but it had a bug. 
We keep the vertical and horizontal special cases, and use fixed ` #else`. Add an ` issue_3301.cpp`   in the testsuite, that at the same time has a performance test. The new code is slightly faster.
* Issue(s) solved (if any): fix #3301
> Improve Projection of 2D point on line

- Polyhedron_IO/include/CGAL/IO/OFF_reader.h
inline a non-template function
* Affected package(s): Polyhedron_IO
* Issue(s) solved (if any):  [cgal-discuss] Multiple Definitions Error with OFF_reader.h
> inline fill_point()

- Periodic_3_triangulation_3/include/CGAL/Periodic_3_Delaunay_triangulation_3.h
- Periodic_3_triangulation_3/include/CGAL/Periodic_3_regular_triangulation_3.h
- Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_3.h
- Call to `random_shuffle` if `is_point_set_large` is `true` is redundant since the next thing done is to call `spatial_sort`, which calls `random_shuffle` itself.
- `make_canonical` was needlessly using addresses to compare `Vertex_handle`s. With that change, P3T3 is deterministic when using time stamped vertex/cell base classes, but for now requires to always be in 1-cover.
* Affected package(s): `Periodic_3_triangulation_3`
* Issue(s) solved (if any): fix #3346 
> P3T3: Minor improvements (random_shuffle + determinism)

- Mesh_3/include/CGAL/Polyhedral_complex_mesh_domain_3.h
Fix `Polyhedral_complex_mesh_domain_3` when `detect_features()` is not called.
* Issue(s) solved (if any): https://stackoverflow.com/q/52726224/1728537
> Fix Polyhedral_complex_mesh_domain_3 when detect_features() is not called

- Triangulation_3/examples/Triangulation_3/CMakeLists.txt
- Triangulation_3/include/CGAL/Delaunay_triangulation_3.h
- Triangulation_3/include/CGAL/Regular_triangulation_3.h
Re-add examples incorrectly disabled by PR #2835 and then fix them. The bug was introduced in CGAL-4.13.
Cc: @afabri
> Re-add examples incorrectly disabled by PR #2835

- Surface_mesh/examples/Surface_mesh/CMakeLists.txt
If CMP0070 exists,
set policy of CMP0053 to new  and CMP0071 to OLD, if they exist.
* Issue(s) solved (if any): fix #3388
> Surface_mesh_Examples:Fix cmake warning

- Mesh_3/include/CGAL/Mesh_3/Mesh_complex_3_in_triangulation_3_base.h
- Mesh_3/test/Mesh_3/test_meshing_determinism.cpp
- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
- STL_Extension/include/CGAL/Time_stamper.h
- STL_Extension/test/STL_Extension/test_Concurrent_compact_container.cpp
- `Time_stamper` uses an atomic counter, to be usable with threads.
- Changes to `Compact_container` and `Concurrent_compact_container`:
- Remove `CCC_iterator`, because a slightly modified `CC_iterator` can be used instead
- `Concurrent_compact_container` now uses also the time stamper.
* Affected package(s): STL_Extension, Triangulation_3, Mesh_3
> Mesh_3 is now deterministic with TBB when only one thread is used

- .travis/build_package.sh
- Mesh_3/include/CGAL/Mesh_3/io_signature.h
- Mesh_3/include/CGAL/Mesh_domain_with_polyline_features_3.h
- Mesh_3/include/CGAL/internal/Mesh_3/indices_management.h
- Mesh_3/test/Mesh_3/test_domain_with_polyline_features.cpp
- Mesh_3/test/Mesh_3/test_meshing_polyhedron_with_features.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/detect_features.h
Mesh_3: Allow `Subdomain_index` to be `short`.
... That forced me to modify the `Index` of domains with features.
* License and copyright ownership: no change (maintenance by GF of an Inria package)
> Mesh_3: Allow `Subdomain_index` to be `short`

- AABB_tree/include/CGAL/AABB_tree.h
- AABB_tree/test/AABB_tree/aabb_test_datum.cpp
To make it easier to access the datum of a primitive, regardless of the presence of shared_data or not, a new function is added to AABB_tree.
* Issue(s) solved (if any): fix #1872
* documentation:
<pre>
//! Returns the datum (geometric object) represented `p`. 
typename AABBTraits::Primitive::Datum_reference datum(Primitive& p)const
</pre>
> AABB_tree: add datum()

- GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h
- Linear_cell_complex/include/CGAL/draw_linear_cell_complex.h
- Polyhedron/include/CGAL/draw_polyhedron.h
- Surface_mesh/include/CGAL/draw_surface_mesh.h
- Triangulation_2/include/CGAL/draw_triangulation_2.h
- Triangulation_3/include/CGAL/draw_triangulation_3.h
Update basic viewers to correct a bug when we want to visualize an object using EPEK.
I tested all the 5 existing viewers with EPEK and EPIK without problem.
* Affected package(s): Surface_mesh, Polyhedron, LCC
* Issue(s) solved (if any): fix #3401
> Basic viewers: bugfix for Epeck

- Solver_interface/include/CGAL/Diagonalize_traits.h
@sgiraudot could you confirm that Eigen is used by default only if `CGAL_USE_EIGEN` is not defined?
> Add an option to disable the deprecation warning

- Polyhedron/demo/Polyhedron/Plugins/Display/Display_property_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Partition_graph_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Alpha_shape_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_to_mesh_distance_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_plane_detection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_segmentation_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Parameterization_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
Everytime a dockwidget is shown, it should also raise(), so that it comes on top of the possible tab stask.
* Issue(s) solved (if any): fix #3385
> Polyhedron demo: raise the tabified widgets when they are set visible.

- Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_plugin.cpp
The vector to compute the position of the points around the center was inverted.
* Issue(s) solved (if any): fix #3396
> Polyhedron demo: Fix orientation of the sphere generator.

- AABB_tree/include/CGAL/AABB_tree.h
This adds a parameter pack to the function build() that calls set_shared_data(t...) if specified.
* Issue(s) solved (if any): fix #1166 
* documentation: 
```c++
/// After one or more calls to `insert()` the internal data
/// structure of the tree must be reconstructed. This procedure
/// has a complexity of \f$O(n log(n))\f$, where \f$n\f$ is the number of
/// primitives of the tree.  This procedure is called implicitly
/// at the first call to a query member function. You can call
/// `build()` explicitly to ensure that the next call to
/// query functions will not trigger the reconstruction of the
/// data structure.
/// The parameter pack `T` is of any types
/// such that `Primitive` has a constructor with the following …
```
> AABB_tree: Add an overload to build() for shared data

- AABB_tree/include/CGAL/AABB_face_graph_triangle_primitive.h
- AABB_tree/include/CGAL/AABB_halfedge_graph_segment_primitive.h
- AABB_tree/test/AABB_tree/aabb_test_multi_mesh.cpp
- BGL/include/CGAL/boost/graph/property_maps.h
- Installation/CHANGES.md
Use a std::pair containing the id and the associated graph if the tag OneGraphPerTree is false, so it is possible to use the primitives returned by the intersections tests.
* Issue(s) solved (if any): fix #3364 
* Feature/Small Feature (if any): [Pairs as ids](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/AABB_tree/Pairs_as_ids)
* Link to compiled documentation (obligatory for small feature) [link](https://cgal.geometryfactory.com/~mgimeno/AABB_tree_primitive_id/AABB_tree/)
Copyright (c) 2012 INRIA Sophia-Antipolis (France).
* **Pre-approved:** 2018/10/09
> Aabb_tree: change the id of AABB_face_graph_triangle_primitive and AABB_halfedge_graph_segment_primitive

- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
Re-computes the normals of the selection_item after the mesh has been changed. 
* Issue(s) solved (if any): fix #3384
> Polyhedron demo: re-computes normals after mesh edition in selection item

- BGL/include/CGAL/boost/graph/parameters_interface.h
- BGL/test/BGL/test_cgal_bgl_named_params.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/corefinement.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_clip.cpp
Fixes a bug when a patch with no input vertex must be classified wrt the clipper
The patch uses existing code with a special switch to disable some part of it.
Fix #3428
> Fix bug in clipping code

- BGL/include/CGAL/boost/graph/iterator.h
The adjacent_vertices uses the wrong iterator type in it's body. This PR changes it to the same as the function's return type.
* Affected package(s): CGAL and the Boost Graph Library
> BGL: Fix type missmatch in adjacent_vertices

- NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Point_d.h
- NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Vector_d.h
- NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Weighted_point_d.h
- NewKernel_d/test/NewKernel_d/Epick_d.cpp
- Triangulation/examples/Triangulation/convex_hull.cpp
- Triangulation/include/CGAL/IO/Triangulation_off_ostream.h
- Triangulation/include/CGAL/Triangulation.h
- Triangulation/include/CGAL/Triangulation_data_structure.h
- Triangulation/include/CGAL/Triangulation_vertex.h
- Triangulation/test/Triangulation/test_triangulation.cpp
> Fix vertex istream operator

- Cartesian_kernel/include/CGAL/Cartesian/Aff_transformation_2.h
- Cartesian_kernel/include/CGAL/Cartesian/Aff_transformation_3.h
- Homogeneous_kernel/include/CGAL/Homogeneous/Aff_transformationH2.h
- Homogeneous_kernel/include/CGAL/Homogeneous/Aff_transformationH3.h
- Kernel_23/doc/Kernel_23/CGAL/Aff_transformation_2.h
- Kernel_23/doc/Kernel_23/CGAL/Aff_transformation_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_aff_transformation_2.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_aff_transformation_3.h
Add an equality test to Aff_transformation_2 and Aff_transformation_3.
* Affected package(s): Kernle_23, Cartesian_kernel, Homogeneous_kernel
* Issue(s) solved (if any): fix #3055 
* Link to compiled documentation (obligatory for small feature) [link](https://mydoc/Manual/Pkg)
> Kernel_23: Add an equality test to Aff_transfo 2 and 3.

- Alpha_shapes_2/doc/Alpha_shapes_2/CGAL/Alpha_shape_2.h
- Alpha_shapes_2/include/CGAL/internal/Lazy_alpha_nt_2.h
- Alpha_shapes_3/doc/Alpha_shapes_3/CGAL/Alpha_shape_3.h
- Alpha_shapes_3/include/CGAL/internal/Lazy_alpha_nt_3.h
- Number_types/include/CGAL/Lazy_exact_nt.h
Only minimally tested.
* Affected package(s): Alpha_shapes_3, Number_types
* Issue(s) solved (if any): fix #3153
> Copy relative_precision_of_to_double from Lazy_exact_nt to Lazy_alpha_nt_3

- AABB_tree/include/CGAL/AABB_tree.h
Fixes [this warning](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.14-Ic-40/logs_master/AABB_tree.log)
> Fix doc warning

- Skin_surface_3/include/CGAL/Skin_surface_base_3.h
- Skin_surface_3/include/CGAL/Triangulated_mixed_complex_observer_3.h
- Skin_surface_3/include/CGAL/triangulate_mixed_complex_3.h
- Skin_surface_3/include/CGAL/triangulate_power_diagram_3.h
Fix for VC2017.  See [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-48/Skin_surface_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz)
See [gist](https://gist.github.com/afabri/8a28b1c30cedbc6e9dfc492a419e399a)
Reported to Microsoft.
* Affected package(s): Skin_surface_3
> Skin_surface_3: Fix for VC2017 which has a problem with the conversion to std::pair

- Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
computeItemColorVectorAutomatically(true) was missing.
* Issue(s) solved (if any): fix #3475
> Polyhedron Demo: fix colorize each Connected Component

- Snap_rounding_2/test/Snap_rounding_2/cgal_test_base
Add missing argument in cgal_test, that makes that Blake doesn't find the dependencies.
* Affected package(s):Snap_rounding_2
* Issue(s) solved (if any): red square in testsuite.
> Snap_rounding_2: Fix test script

- Mesh_2/test/Mesh_2/test_double_map.cpp
- Modular_arithmetic/test/Modular_arithmetic/Residue.cpp
- Number_types/test/Number_types/Interval_nt.cpp
- STL_Extension/test/STL_Extension/test_dispatch_output.cpp
- Segment_Delaunay_graph_2/test/Segment_Delaunay_graph_2/include/test_types.h
- Segment_Delaunay_graph_Linf_2/test/Segment_Delaunay_graph_Linf_2/include/test_types.h
In the testsuite we assign sometimes variables to themselves: `f = f`. 
This triggers a [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-49/Mesh_2/TestReport_lrineau_ArchLinux-clang-CXX14.gz) and it can be avoided by writing `void(f = f)`.
* Affected package(s): Mesh_2  (more to follow if it works)
> Address warning Wself-assign-overloaded

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.h
In the Mesh_3 plugin, generalise the creation of surface-only c3t3 items, also for meshes created from images or implicit functions.
* License and copyright ownership: trivial patch
> Polyhedron demo:  mesh_3_plugin  surface_only

- Triangulation/examples/Triangulation/delaunay_triangulation.cpp
It seems that without the use of the Delaunay_triangulation class, the obtained triangulation is not the actual full Delaunay triangulation of the points.
* Affected package(s): dD Triangulations
* Issue(s) solved (if any): fix #3502
> generate a truly Delaunay triangulation

- Point_set_3/include/CGAL/Point_set_3/IO.h
- Point_set_processing_3/include/CGAL/IO/read_ply_points.h
- Polyhedron_IO/include/CGAL/IO/PLY_reader.h
Currently, our PLY reader only handles elements of type `vertex` and `face`. Though this is in itself acceptable, a problem occurs if another type of element is used in the PLY input: in that case, our reader might read garbage (as the properties of the elements are not processed at all instead of being processed but ignored, which would be the right behaviour).
This PR fixes it. It also makes the handling of PLY element much better: the internal API (not documented) of our PLY reader now allows to have access to _all_ elements and their respective properties, which can be handy if we want to read other types of PLY elements.
* Affected package(s): Point Set Processing, Point Set 3, Polyhedron IO, Polyhedron demo
> Point Set Processing: Fix PLY unknown element reading

- Arrangement_on_surface_2/include/CGAL/Arr_spherical_gaussian_map_3/Arr_polyhedral_sgm.h
Fixed the workaround for the absence of c++11 auto feature---added facets properly.
* Affected package(s): Arrangement_of_surface_2
* Link to compiled documentation (obligatory for small feature) [link](https://mydoc/Manual/Pkg)
> Aos 2 sgm efif

- Mesh_3/include/CGAL/Mesh_3/Mesher_level.h
- TDS_3/include/CGAL/Triangulation_data_structure_3.h
- Triangulation_3/include/CGAL/Regular_triangulation_3.h
- Triangulation_3/test/Triangulation_3/include/CGAL/_test_cls_parallel_triangulation_3.h
- Triangulation_3/test/Triangulation_3/test_regular_3.cpp
- In a parallel insertion of a range of weighted points, the 'hint' is a vertex handle that is unsafe to use because the insertion of a weighted point by another thread might hide (delete) the hint.
_Solution_: check the validity of the hint before and after trying to lock it.
- The removal of a range of weighted points while storing hidden points means that we re-insert hidden points after a successful removal. However, since we have only locked what was needed to remove the vertex and not to re-insert the hidden points, deadlocks can appear.
_Solution_: unlock everything after successful removal and threads can then wrestle normally for control of zones to re-insert hidden points. Same check is needed on the hint.
* Affected package(s): `Triangulation_3`
* Issue(s) solved (if any): fix …
> Triangulation_3: Fix insertion and removal of ranges of weighted points (for 4.12)

- Mesh_3/include/CGAL/IO/File_medit.h
Modified facet output code in function CGAL::output_to_medit() in file File_medit.h. The orientation of neighboring facet triangles in the output medit file was random before. Now, a consistent orientation is ensured by taking both the facet subdomain-index-pair and the facet parity (odd/even index of opposite vertex) into account.
We create a temporary clone of each facet. If the (first, second) subdomain-index of the facet fulfills the condition (first < second), then we mirror the facet. Additionally, if the index of the opposite vertex is an odd number, we swap the vertex orientation of the facet.
NOTE: This could perhaps be written in a different way, like replacing the vertex swap with another call to tr.mirror_facet(). However, I'm staying close to the fix suggested in 2010 by …
> Modified output_to_medit() for consistent facet orientation

- Subdivision_method_3/include/CGAL/Subdivision_method_3/subdivision_masks_3.h
Previous `static_cast` was forgotten when the package was switched to `FaceGraph`.
* Affected package(s): `Subdivision`
* Issue(s) solved (if any): fix #3603
> Subdivision: Fix using unsigned type in CatmullClark computations

- Segment_Delaunay_graph_Linf_2/include/CGAL/Segment_Delaunay_graph_Linf_filtered_traits_2.h
- Segment_Delaunay_graph_Linf_2/include/CGAL/Side_of_bounded_square_2.h
- Segment_Delaunay_graph_Linf_2/test/Segment_Delaunay_graph_Linf_2/test_sdg_linf_2_et.cpp
- Segment_Delaunay_graph_Linf_2/test/Segment_Delaunay_graph_Linf_2/test_sdg_linf_2_ft.cpp
- Segment_Delaunay_graph_Linf_2/test/Segment_Delaunay_graph_Linf_2/test_sdg_linf_hierarchy_2_et.cpp
- Segment_Delaunay_graph_Linf_2/test/Segment_Delaunay_graph_Linf_2/test_sdg_linf_hierarchy_2_ft.cpp
- Segment_Delaunay_graph_Linf_2/test/Segment_Delaunay_graph_Linf_2/test_sdg_linf_new_range_api.cpp
Should fix [this](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.13-I-125/Segment_Delaunay_graph_Linf_2/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.1_Release-LEDA-without-GMP.gz) and [that](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.13-I-125/Segment_Delaunay_graph_Linf_2_Examples/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.1_Release-LEDA-without-GMP.gz).
> Fix when not using Gmp

- Nef_2/include/CGAL/Nef_2/HDS_items.h
- Nef_2/include/CGAL/Nef_2/PM_const_decorator.h
Before the patch, when used with `Bounded_kernel` the halfedge pointer of the unbounded face could be a removed halfedge.
> Reset the halfedge pointer of the faces before setting them

- Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/CMakeLists.txt
- Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/CMakeLists.txt
[Qt 5.12 has changed a lot in QtHelp](http://blog.qt.io/blog/2018/11/02/whats-new-qt-help/), and:
> We have merged the qcollectiongenerator tool into the qhelpgenerator, which now accepts both .qhp and .qhcp files as input and generates .qch and .qhc files, respectively.
Our `CMakeLists.txt` needed extra code to use either `qcollectiongenerator` for Qt<=5.11 and `qhelpgenerator` for Qt>=5.12.
* Affected package(s): Periodic_3 demos
* License and copyright ownership: maintenance by GeometryFactory, Inria keeps the rights
> Support Qt-5.12: qcollectiongenerator merged into qhelpgenerator

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_normal_estimation_plugin.cpp
Copy/paste error, the jet estimation was using the PCA neighbor parameter instead of its own.
* Bug introduced in 4.13
> Polyhedron demo: Fix normal estimation parameter

- Number_types/include/CGAL/internal/Exact_type_selector.h
As discussed in #3614, to avoid the temptation to revert #3406.
> Prefer Quotient<MP_Float> to cpp_rational for now.

- Polyhedron/demo/Polyhedron/MainWindow.cpp
Remove the while() mechanic in the eraseall() function of the mainwindow. This way, if the first item of the scene (index 0) is a lock child of a group, it won't hang because it cannot be erased and the erase function returns false.
* Issue(s) solved (if any): fix #3626
> Polyhedron Demo: Fix Erase_all

- Periodic_3_mesh_3/examples/Periodic_3_mesh_3/CMakeLists.txt
- Periodic_3_mesh_3/test/Periodic_3_mesh_3/CMakeLists.txt
Fix for  the testuite  [4.14-I-108](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-I-108/Periodic_3_mesh_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz)
* Added `ImageIO` to `find_package()`  
* Added `include( ${CGAL_USE_FILE} )` 
* Affected package(s): Periodic_3_mesh_3
Fixes #3559.
> Periodic_3_mesh_3: Link with ImageIO for VC++

- AABB_tree/examples/AABB_tree/AABB_custom_indexed_triangle_set_example.cpp
- AABB_tree/examples/AABB_tree/AABB_custom_triangle_soup_example.cpp
The testsuite _x64_Cygwin-Windows10_MSVC2017-Debug-64bits_  has several warnings concerning iterators, allocators, argument and result types which must be dealt with. 
* Affected package(s): AABB Tree (more to come)
> Address VC++ deprecation warnings concerning the STL

- CGAL_Core/include/CGAL/CORE/CoreDefs.h
A call to `std::setprecision()` does not affect any stream. In order to do so the returned object would have to be inserted into a stream. So we can just remove the line.  Thank you for pointing this out @ysyrov.
* Affected package(s): Core
* Issue(s) solved (if any): fix #3606
> CGAL_Core: Remove call of setprecision()

- Installation/cmake/modules/CGAL_SetupCGAL_CoreDependencies.cmake
- Triangulation/examples/Triangulation/delaunay_triangulation.cpp
- Triangulation/examples/Triangulation/triangulation.cpp
- Triangulation/test/Triangulation/test_delaunay.cpp
- Triangulation/test/Triangulation/test_torture.cpp
- Triangulation/test/Triangulation/test_triangulation.cpp
Clang also defines `__GNUC__`, but it defines `__clang__` too, so I also check if `__clang__` is not defined to only match GCC < 4.4.
* Affected package(s):Triangulation
* Issue(s) solved (if any): fix ##3605
> Triangulation: Fix the tests for GCC<4.4 so it wont match clang.

- CMakeLists.txt
- Installation/CMakeLists.txt
- Installation/cmake/modules/CGAL_add_test.cmake
Fix the troublesome extra targets created by `CTest.cmake` (see [StackOverflow](https://stackoverflow.com/q/54507170/1728537)).
Instead of including `CTest.cmake`:
- Define the option `BUILD_TESTING`
- Call to `enable_testing()` if `BUILD_TESTING` is on.
That is a fix, but for a minor issue. I prefer not to backport the fix to release branches.
* Affected package(s): All CGAL, via CMake scripts
* Issue(s) solved (if any): https://stackoverflow.com/q/54507170/1728537
> Replace include(CTest) by minimal usage

- Classification/examples/Classification/CMakeLists.txt
In the `CMakeLists.txt` of the classification examples, there was a duplicated `find_package()` for OpenCV, one of them searching for the whole library. It's useless and probably lead to [these runtime library errors](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-112/Classification_Examples/TestReport_lrineau_Fedora-Release.gz) (as parts of the full OpenCV will search for Qt5).
* Introduced in 4.13
> Classification: Remove useless full find_package for OpenCV

- Number_types/include/CGAL/boost_mp.h
- Number_types/test/Number_types/utilities.cpp
We rely a lot on intervals of length 0, for performance. I had written a simple to_interval for boost types (essentially to_double enlarged, so it never has length 0), but I have to copy the one from Gmpq/mpq_class to avoid regressions. I am also adding the boost types to the utilities.cpp test, which required fixing Coercion_traits.
Note that cpp_int/cpp_rational (as opposed to mpz_int/mpq_rational) will still use the simple to_interval, which may make them slower for some applications. But then we currently only use them if GMP and LEDA are not available, so it doesn't matter.
> Rewrite to_interval for boost.multiprecision types

- Periodic_2_triangulation_2/examples/Periodic_2_triangulation_2/p2t2_info_insert_with_pair_iterator_2.cpp
- Periodic_2_triangulation_2/examples/Periodic_2_triangulation_2/p2t2_info_insert_with_transform_iterator_2.cpp
- Periodic_2_triangulation_2/examples/Periodic_2_triangulation_2/p2t2_info_insert_with_zip_iterator_2.cpp
Some examples in P2T2 were using insufficient vertex base classes (only T2 vertex classes and not P2T2 vertex classes). 
It was most likely only seen on some Windows platforms (e.g. https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-105/Periodic_2_triangulation_2_Examples/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz), because that compiler was over-zealous and compiling functions not used by the examples (whatever the P2T2 vertex base class brings is rarely used).
* Affected package(s): `Periodic_2_triangulation_2`
> P2T2: Fix not using periodic vertex bases in P2T2 examples

- .travis/build_package.sh
Remove QGLViewer from travis. It removes the call to qmake and should fix the problem in xenial.
> Travis: Remove QGLViewer from Travis

- Convex_hull_d/include/CGAL/Regular_complex_d.h
Fix warning in the testsuite [4.14-Ic-110](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-110/Convex_hull_d/TestReport_lrineau_ArchLinux-CXX17-Release.gz)
I initialize now an `int` with `0`, but didn't check if the before uninitialized member was ever used.
* Affected package(s): Convex_hull_d
> Convex_hull_d: Initialize to avoid warning

- Polygon_mesh_processing/test/Polygon_mesh_processing/test_corefinement_and_constraints.cpp
Initialize a `boost::optional` to see if [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-110/Polygon_mesh_processing/TestReport_lrineau_Fedora-32-Release.gz) goes away.
> Polygon_mesh_processing: Initialize a boost::optional

- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
- Surface_mesh/include/CGAL/boost/graph/properties_Surface_mesh_features.h
For some reason, the results in and out the demo differs. This should unify them.
Also :
- protection can use detected shard edges and not only selected edges
- Split only can be used with only a selection of edges and not a selection of faces
- When trying to remesh with a selection of edges and a protection, if the constrained are too long, a pop up asks if the user wants to split instead of simply aborting. 
* Issue(s) solved (if any): fix #3649
> Polyhedron Demo: Fix isotropic remeshing plugin

- Polyhedron/demo/Polyhedron/Scene_group_item.cpp
A call to renderChildred() was misisng.
> Polyhedron Demo: Fix Rendering of Nested Groups

- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_p3rt3_insert_remove_point_set.cpp
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_regular_triangulation_3.cpp
- Triangulation_3/doc/Triangulation_3/CGAL/Regular_triangulation_cell_base_3.h
- Triangulation_3/include/CGAL/Regular_triangulation_cell_base_3.h
The [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-117/Periodic_3_triangulation_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz) for 3D periodic regular triangulations calls `std::distance(b,e)` where the iterators are from a list. The function that returns a range (something we want later anyways) permits to call `.size()`. 
* Affected package(s): Triangulation_3 and Periodic_3_triangulation_3
> Regular_triangulation_3: Add Regular_triangulation_cell_base_3::hidden_points()

- Point_set_processing_3/examples/Point_set_processing_3/callback_example.cpp
10K instead of 1M points is enough to illustrate the callback mechanism.    And it avoids a timeout in the [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-117/Point_set_processing_3_Examples/TestReport_afabri_x64_Cygwin-Windows10_MSVC2015-Debug-64bits.gz)
* Affected package(s): Point_set_processing
> PSP: Reduce the size of the data set in an example

- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
Avoid [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-117/Triangulation_2/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz).  
@mglisse can you please have a quick look, as you made good comments on initialization in other PRs. 
> Triangulation_2: Initialize to avoid warning

- Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Scene.cpp
A default  constructed point is not necessarily at the origin.   Fix warning in [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-I-114/Periodic_3_triangulation_3_Demo/TestReport_lrineau_ArchLinux-CXX17-Release.gz)
* Affected package(s): Periodic_3_triangulation_3
> Periodic_3_triangulation_3 demo: Initialize Point_3

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Output_builder_for_autorefinement.h
Fix for non documented autorefinement functions
> Use only initialized values

- AABB_tree/include/CGAL/AABB_triangulation_3_cell_primitive.h
- Intersections_3/include/CGAL/Intersections_3/internal/Tetrahedron_3_Bounded_3_do_intersect.h
- Intersections_3/include/CGAL/Intersections_3/internal/Tetrahedron_3_Unbounded_3_do_intersect.h
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
The `Scene_c3t3_item` from our 3D demos now uses an AABB tree of cells, instead of an AABB tree of triangles. That divides the number of primitives by 4, and save times:
Before:
```
C3t3 facets AABB tree built in 22.010006904602051 wall-clock seconds
Scene_c3t3_item_priv::computeIntersections in 0.50893402099609375 wall-clock seconds
```
After:
```
C3t3 cells AABB tree built in 13.072829008102417 wall-clock seconds
Scene_c3t3_item_priv::computeIntersections in 0.41458892822265625 wall-clock seconds
```
The gain seems mostly in the construction of the tree (40% saved), and the gain on the queries seems lower (about 20%).
* Affected package(s): AABB_tree, Polyhedron demo
* License and copyright ownership: maintenance by GeometryFactory, license and copyright remain unchanged
> New undocumented AABB primitive: cells of a 3D triangulation

- Mesh_3/include/CGAL/Mesh_3/Slivers_exuder.h
@maxGimeno please no longer test #3634, but test this PR instead.
> Mesh_3: Disable parallel sliver exudation in VC++ debug in the testsuite

- Optimal_transportation_reconstruction_2/include/CGAL/OTR_2/Reconstruction_triangulation_2.h
- Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h
The OTR algorithm manipulates triangulation objects using low-level functions. In many cases, the validity of the `Triangulation_2` (and even of the TDS sometimes) was broken. Most of the time, things still went well (by luck) but it was likely to create bugs such as https://github.com/CGAL/cgal/issues/3601.
This PR does the following:
- corrects `copy_star()` so that the copy is a valid triangulation (it was _never_ the case before). Note that because the copy is only a copy of a 1-star around a vertex, it may have concavities (therefore, only the TDS is made valid, not the `Triangulation_2`)
- adds a validity-check after flipping and after collapsing (both can produce invalid triangulations) and discard the candidate edge if the produced triangulation is invalid (we only check the …
> OTR: Fix validity of triangulation

- Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/MainWindow.ui
- Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Scene.cpp
In find_conflict, if the request point is a vertex of the request cell, there is no conflict and that triggers an assertion. I added a test before calling it in the demo to avoid this situation, that was systematic when adding the moving point to the triangulation.
> P3t3 demo: Fix crash 

- Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
- Mesh_3/test/Mesh_3/test_meshing_with_one_step.cpp
Fix for Issue #3553 : Refine_facets_3::number_of_bad_elements_impl() is not up-to-date (won't compile).
The number_of_bad_elements_impl() method in Refine_facets_3 was not updated after recent API-breaking changes. This is my attempt at fixing the compile errors in this method. 
I'm not sure how you'd like to handle the printing comparison of is_in_complex() vs optional<Subdomain> around line 1146. I used boost optional_io to print the optional<Subdomain> value.
To test the fix, one must call the Mesher_3::display_number_of_bad_elements(), since the compiler will otherwise not visit this (debugging) function.
* Issue(s) solved (if any): fix #3553
> Fixed non-compiling outdated code (for issue #3553)

- Circular_kernel_2/examples/Circular_kernel_2/functor_has_on_2.cpp
- Circular_kernel_2/examples/Circular_kernel_2/intersecting_arcs.cpp
- Circular_kernel_2/test/Circular_kernel_2/CMakeLists.txt
- Circular_kernel_2/test/Circular_kernel_2/test_Exact_circular_kernel.cpp
- Circular_kernel_2/test/Circular_kernel_2/test_Filtered_bbox_circular_kernel.cpp
- Circular_kernel_2/test/Circular_kernel_2/test_Lazy_circular_kernel.cpp
- Circular_kernel_3/examples/Circular_kernel_3/functor_has_on_3.cpp
- Circular_kernel_3/test/Circular_kernel_3/CMakeLists.txt
- Circular_kernel_3/test/Circular_kernel_3/test_Spherical_kernel.cpp
- Circular_kernel_3/test/Circular_kernel_3/test_Spherical_kernel_with_core.cpp
The tests and examples included unnecessary files.  A test should include the absolute minimum, and examples must be exemplary.
* Affected package(s): Circular_kernel  2D and 3D
> Circular_kernel_{2,3}: Cleanup of examples and tests

- Advancing_front_surface_reconstruction/examples/Advancing_front_surface_reconstruction/CMakeLists.txt
- Classification/examples/Classification/CMakeLists.txt
- Cone_spanners_2/examples/Cone_spanners_2/CMakeLists.txt
- Mesh_3/test/Mesh_3/CMakeLists.txt
- Number_types/test/Number_types/CMakeLists.txt
- Optimal_transportation_reconstruction_2/examples/Optimal_transportation_reconstruction_2/CMakeLists.txt
- Point_set_3/examples/Point_set_3/CMakeLists.txt
- Point_set_processing_3/examples/Point_set_processing_3/CMakeLists.txt
- Point_set_processing_3/test/Point_set_processing_3/CMakeLists.txt
- Solver_interface/examples/Solver_interface/CMakeLists.txt
- Surface_mesh_approximation/test/Surface_mesh_approximation/CMakeLists.txt
- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/CMakeLists.txt
- Surface_mesh_parameterization/test/Surface_mesh_parameterization/CMakeLists.txt
Remove unnecessary `include_directories()`.  
If anybody has more suggestions what should get cleaned up it could go into this PR.
For example removing `SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4244")`  from [this ](https://github.com/CGAL/cgal/blob/master/Spatial_searching/examples/Spatial_searching/CMakeLists.txt#L27) file, first of all as it does not work as @lrineau told me, and secondly because we shouldn't suppress warnings this way.
* Affected package(s): several
> CGAL: clean up CMakeLists.txt files in examples and tests

- Polyhedron/demo/Polyhedron/triangulate_primitive.h
- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
Test if the two constraints vertices are different before inserting to avoid crash.
> Polyhedron demo: Fix crash in triangulation of non convex facets.

- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
The function `halfedges(..)` is the only one not returning a range. This is important for writing `for( : )` loops.
> BGL: Make halfedges(Face_filtered_graph&) return Iterator_range instead of std::pair

- NewKernel_d/include/CGAL/NewKernel_d/Cartesian_LA_base.h
- NewKernel_d/include/CGAL/NewKernel_d/Types/Hyperplane.h
- NewKernel_d/include/CGAL/NewKernel_d/Types/Segment.h
- NewKernel_d/include/CGAL/NewKernel_d/Types/Sphere.h
- NewKernel_d/include/CGAL/NewKernel_d/Types/Weighted_point.h
- NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Point_d.h
- NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Vector_d.h
Suppress the warning
> include\CGAL/NewKernel_d/Wrapper/Point_d.h(82): warning C4309: 'specialization': truncation of constant value
[here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-I-126/NewKernel_d/TestReport_afabri_x64_Cygwin-Windows10_MSVC2015-Debug-64bits.gz) that seems to be a false positive for VC2015.
> NewKernel_d: Suppress VC2015 warning

- Documentation/doc/Documentation/Developer_manual/Chapter_checks.txt
Documentation had double "in the"
> Small documentation correction

- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
That was missing to make `write_off()` working with a `Face_filtered_graph`
> add missing function required by the concept

- Point_set_processing_3/include/CGAL/IO/read_ply_points.h
In order to avoid reading/writing point coordinates that are `float` as `double` when using the PLY reader with `CGAL::Simple_cartesian<float>`, I introduced an automatic detection of the FT type based on the value type of the point map. This detection fails if the kernel is exact, see issue https://github.com/CGAL/cgal/issues/3696.
This fixes it by declaring the type to read/write (from a PLY point of view) as double by default, _except_ when using the float kernel.
(I'll also have to fix https://github.com/CGAL/cgal/pull/3636 similarly.)
* Affected releases: from 4.13 (the automatic FT detection was not in 4.12)
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/3696
> Point Set Processing: Fix PLY FT type detection

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Surface_mesh_approximation_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/VSA_wrapper.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/VSA_wrapper.h
- Surface_mesh_approximation/examples/Surface_mesh_approximation/vsa_isotropic_metric_example.cpp
- Surface_mesh_approximation/include/CGAL/Surface_mesh_approximation/L21_metric_plane_proxy.h
- Surface_mesh_approximation/include/CGAL/Surface_mesh_approximation/L2_metric_plane_proxy.h
- Surface_mesh_approximation/include/CGAL/Variational_shape_approximation.h
- Surface_mesh_approximation/test/Surface_mesh_approximation/vsa_metric_test.cpp
Handle degenerate faces, degenerate 1-d boundaries and floating ball-components with one proxy.
* Affected package(s): Surface Mesh Approximation
> Surface mesh approximation: handle degenerate cases

- Hyperbolic_triangulation_2/doc/Hyperbolic_triangulation_2/Hyperbolic_triangulation_2.txt
- Periodic_4_hyperbolic_triangulation_2/doc/Periodic_4_hyperbolic_triangulation_2/Periodic_4_hyperbolic_triangulation_2.txt
CSS properties and values should be separated by semicolons but here the width property was followed by an equal sign.
Note: there is still a problem with multiple attributes, in some cases doxygen also uses the style attribute. This still has to be merged, will, soon, be a doxygen pull request.
2019/02/28: I've just pushed a proposed patch, pull request https://github.com/doxygen/doxygen/pull/6861
> CSS properties and values separated by semicolons

- Installation/CMakeLists.txt
- Installation/src/CMakeLists.txt
- Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
In CGAL-4.14, I would like to have `libCGAL.so.13` (to keep
compatibility), but `libCGAL_Image.so.14` (to break compatibility).
This PR allows to have different `SOVERSION` and `SONAME` for each libraries. And it also change the SOVERSION and SONAME for `liCGAL_ImageIO`, while keeping the versions same as for CGAL-4.13 for all the other CGAL libraries.
@maxGimeno I need this PR before CGAL-4.14-beta1 is published, so that one can have CGAL-4.14 in recent Linux distributions as soon as possible.
> Allow to have different SOVERSION for each CGAL libraries

- Ridges_3/doc/Ridges_3/Ridges_3.txt
When having italics in italics and (X)HTML warning is given about  Opening and ending tag mismatch.
The `<EM>` as well as `<I>` result in emphasized text and would map in doxygen both to `<i>` but will confuse doxygen. output
The problematic code can be found in `Ridges_3/doc/Ridges_3/Ridges_3.txt`
The original text looks like:
The updated text:
> Documentation italic in italics

- Documentation/doc/Documentation/main.txt
The xhtml lint checker gave:
`parser error : Opening and ending tag mismatch: div line 375 and p`
Solved by making the `\htmlonly` into `\htmlonly[block]` to prevent invalid HTML
> Inconsistent tags for (X)HTML output (Manual)

- Classification/include/CGAL/Classification/classify.h
To subdivide an input set, a set of bounding boxes is used. Because the coordinates are converted to floats, some points may end up not being assigned to any subdivision (with the precision loss, they can end up outside of all bboxes).
This fixes it and also adds an assertion to check that all points have been assigned to a subdivision.
* Issue(s) solved (if any): fix #3720
> Classification: Fix bbox precision

- Documentation/doc/resources/1.8.13/BaseDoxyfile.in
- Documentation/doc/resources/1.8.14/BaseDoxyfile.in
- Documentation/doc/resources/1.8.4/BaseDoxyfile.in
- Inscribed_areas/doc/Inscribed_areas/Concepts/ExtremalPolygonTraits_2.h
- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/Periodic_2_Delaunay_triangulation_2.h
- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/Periodic_2_triangulation_2.h
- Point_set_3/include/CGAL/Point_set_3.h
- Spatial_searching/doc/Spatial_searching/Concepts/Splitter.h
- Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h
- TDS_3/doc/TDS_3/Concepts/TriangulationDataStructure_3.h
- Triangulation/doc/Triangulation/CGAL/Triangulation.h
- Triangulation/doc/Triangulation/CGAL/Triangulation_data_structure.h
- Triangulation/doc/Triangulation/CGAL/Triangulation_ds_full_cell.h
- Triangulation/doc/Triangulation/CGAL/Triangulation_ds_vertex.h
- Triangulation/doc/Triangulation/Concepts/TriangulationDataStructure.h
- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
> Fix brief of advanced

- Mesh_3/include/CGAL/IO/File_medit.h
Orientations of output triangles in medit files should now be consistent and work fine in rendering with backface-culling.
* Mirroring facets is now only done when print_each_facet_twice is true. 
* The condition for mirroring facets is inverted, to match the subdomain label ordering imposed by No_patch_facet_pmap_first/second and makes inner facets consistent with outer facets.
* When printing the second triangle (if printing twice), its orientation is reversed (as expected).
* Affected package(s): Mesh_3 I/O
* Issue(s) solved (if any): fix #3566
> Further fix for triangle orientation in medit output

- CMakeLists.txt
Cmake fix: The project now will be added to the local cmake cache (On UNIX located in $HOME/.cmake)
Fix some warnings for new compilers (gcc 9, -std=c++2a)
> export(PACKAGE CGAL)

- Documentation/doc/Documentation/packages.txt
- Documentation/doc/resources/1.8.13/BaseDoxyfile.in
- Documentation/doc/resources/1.8.14/BaseDoxyfile.in
- Documentation/doc/resources/1.8.4/BaseDoxyfile.in
- Documentation/doc/scripts/html_output_post_processing.py
In packages.html we get:
`Element style is not declared in p list of possible children`
as the `style` tag is only allowed in the `head` part of a file.
The specific changes are only needed for this one file, so it has been implemented using the post processing facility of te CGAL documentation generation.
> Invalid (X)HTML sequence

- BGL/examples/BGL_surface_mesh/surface_mesh_partition.cpp
- Point_set_3/examples/Point_set_3/point_set_read_ply.cpp
- Point_set_3/examples/Point_set_3/point_set_read_xyz.cpp
- Point_set_processing_3/examples/Point_set_processing_3/bilateral_smooth_point_set_example.cpp
- Point_set_processing_3/examples/Point_set_processing_3/edge_aware_upsample_point_set_example.cpp
- Point_set_processing_3/examples/Point_set_processing_3/hierarchy_simplification_example.cpp
- Point_set_processing_3/examples/Point_set_processing_3/normal_estimation.cpp
- Point_set_processing_3/examples/Point_set_processing_3/random_simplification_example.cpp
- Point_set_processing_3/examples/Point_set_processing_3/read_write_xyz_point_set_example.cpp
- Point_set_processing_3/examples/Point_set_processing_3/structuring_example.cpp
- Point_set_processing_3/examples/Point_set_processing_3/wlop_simplify_and_regularize_point_set_example.cpp
- Point_set_processing_3/examples/Point_set_processing_3/write_ply_points_example.cpp
- Point_set_processing_3/include/CGAL/IO/write_off_points.h
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
- Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_all_short_edges.cpp
- Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_bounded_normal_change.cpp
- Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrained_border_polyhedron.cpp
- Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrained_border_surface_mesh.cpp
- Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_enriched_polyhedron.cpp
- Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_polyhedron.cpp
- Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_surface_mesh.cpp
Examples which write a point set or mesh to a stream should set the precision.
Additionally I added a \note in the manual.
* Affected package(s): Point_set_3, Point_set_processing, Surface_mesh_simplification.
> IO: Set precision of the ostream when writing a point set or face graph

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
If there is no degenerate faces to deal with, i.e. if the function has nothing to do, it now returns `true`, and not `0`
This change was introduced by commit e4ad5d96a7afd1f2cca3fbc7cb2661a1c1be7659
we now use the new API in the debug code of `isotropic_remeshing()`
> PMP debug code - use the new API of `PMP::remove_degenerate_faces()`

- Mesh_3/test/Mesh_3/test_meshing_utilities.h
Computing the dihedral angles in `double` is sensitive to the precision of `double`.
Therefore we can release the comparison test by 1e-15.
* Affected package(s): Mesh_3 tests
* Issue(s) solved (if any): assertion failure met in the testsuite
[CGAL-4.13-Ic-31](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.13-Ic-31/Mesh_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz)
> Mesh_3 tests : deal with precision of `double`'s

- Surface_mesher/doc/Surface_mesher/Concepts/SurfaceMeshTriangulation_3.h
The function `incident_cells` has been defined twice, removed second definition.
The issue was found as the (X)HTML checker gave the warning:
```
doc_output/Surface_mesher/classSurfaceMeshTriangulation__3.html:773: element a: validity error : ID a1a72cc14f3646bfe0f4e1969b4c47609 already defined
<a id="a1a72cc14f3646bfe0f4e1969b4c47609"></a>
^
ID a1a72cc14f3646bfe0f4e1969b4c47609 already defined
Document doc_output/Surface_mesher/classSurfaceMeshTriangulation__3.html does not validate
```
* Affected package(s): Surface_mesher
> Multiple definition of incident_cells

- Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_plugin.cpp
Fixes the warning introduced by #3746
> Polyhedron_Demo: Fix warning

- .travis.yml
- .travis/build_package.sh
- .travis/generate_travis.sh
- .travis/template.txt
I would like to know why our Travis testsuite is so slow. I have wrapped a lot of commands with `time`, to see the timing.
**Work in progress:** let's see how Travis deals with it.
> Travis: Add calls to `time` to display timings

- AABB_tree/include/CGAL/internal/AABB_tree/AABB_ray_intersection.h
`AABB_tree::first_intersection()` is relying on constructions thus the result provided is not exact.
The following patches does not fix the non-exactness issue but increase the precision of the computation done.
I have an additional patch that I did not commit.
**Pro**: It remove a division and increase the precision of the result
**Con**: The bounds on the nodes are larger
I don't have time right know to investigate if the extra patch does worth it. If no one else have time to investigate either, let's create an issue with the preliminary patch once this PR is merged.
```
diff --git a/AABB_tree/include/CGAL/AABB_traits.h b/AABB_tree/include/CGAL/AABB_traits.h
index 632f2256d4..51698a8ece 100644
--- a/AABB_tree/include/CGAL/AABB_traits.h
+++ b/AABB_tree/include/CGAL/AABB_traits.h
@@ …
```
> More robust first_intersection

- Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_widget.ui
- Polyhedron/demo/Polyhedron/Scene_plane_item.cpp
Don't forget the offset in the tooltip
* Issue(s) solved (if any): fix #3764
> Polyhedron demo: fix the plane_item's equation

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
Before collapsing a short edge, the remesher performs the test : `collapse_does_not_invert_face(halfedge)`, that checks whether the collapse would make the mesh fold on itself.
Testing orientation of normals per patch (identified by their Id) is not a
good solution, because it can happen that we are trying to collapse an edge
that is sharp but which has both of its incident faces on the same surface
patch (wrt ids).
The new test is a lot simpler : for each non-degenerate face of the link of
the edge to be collapsed, simply check if its own normal has changed
orientation or not. The adjacent faces do not need to be taken into account
Edit on March 8 : the function `collapse_does_not_invert_face(halfedge)` has been renamed to `collapse_would_invert_face(halfedge)`, and the meaning reversed …
> PMP : fix isotropic remeshing surviving tiny constraints

- BGL/include/CGAL/boost/graph/Seam_mesh.h
- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/square_border_parameterizer.cpp
Clarify that we require that the selection comes from a file with the extension `*.selection.txt`. 
* Issue(s) solved (if any): fix #3782
> BGL:  Seam_mesh::add_seams() requires .selection.txt

- Intersections_2/include/CGAL/Intersection_traits_2.h
- Intersections_2/include/CGAL/Intersections_2/Point_2_Point_2.h
- Intersections_2/test/Intersections_2/test_intersections_2.cpp
Fix `intersection(Point_2,Point_2)`. It seems it was never tested, and never worked.
PR #2792 introduced a compilation error in cgal-swig-bindings, by the addition of `do_intersect(Point_2,Circle_2)` and `intersection(Point_2,Circle_2)`:
```
.../CGAL/Kernel/function_objects.h:2954:63: error: call of overloaded ‘do_intersect(const CGAL::Point_2<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >&, const CGAL::Point_2<CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >&, CGAL::Simple_cartesian<CGAL::Interval_nt<false> >)’ is ambiguous
{ return Intersections::internal::do_intersect(t1, t2, K()); }
^
```
https://travis-ci.org/CGAL/cgal-swig-bindings/jobs/509442278#L4727
* Affected package(s): Intersections_2
> Fix intersection(Point_2,Point_2)

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h
If the normal vector is small enough, it might happen that the vector is considered not null, but the approximate_sqrt of its norm is. Then the returned normalized vector is Nan. To avoid that, i added a check that the norm is not null.
> PMP: Fix in normalize()

- Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_widget.ui
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Viewer.cpp
- Polyhedron/demo/Polyhedron/Viewer.h
- Three/include/CGAL/Three/Viewer_interface.h
Don't select clipped points.
Also change the design of the clipping box plugin: 
added a checkable button to enable clipping in 2D, so that it won't conflict with the 2D selection.
@sgiraudot please stress-test this, as I encountered numerous weird bugs while I developped it. I feel like I got rid of everything but I can't be sure.
I strongly suggest to test it in a clean build directory.
* Issue(s) solved (if any): fix #3792
> Polyhedron Demo: Only Select in the clipped zone

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
Check if the alpha slider exists before calling it to avoid a crash on reload.
* Issue(s) solved (if any): fix #3800
> Polyhedron Demo: Fix c3t3 reload

- Mesh_3/doc/Mesh_3/Concepts/MeshComplexWithFeatures_3InTriangulation_3.h
Add two missing 's' in the concept  `MeshComplexWithFeatures_3InTriangulation_3` documentation.
There was no link on these in [the doc](https://doc.cgal.org/latest/Mesh_3/classMeshComplexWithFeatures__3InTriangulation__3.html#a4d1ab6033eb1f6ffd61c2522f2fd23af).
> Doc fix (tiny) in concept `MeshComplexWithFeatures_3InTriangulation_3`

- Number_types/include/CGAL/FPU.h
Define the floating point control word values for arm architectures (for gcc).
* Affected package(s):Number Types
> Number_types: Add support for arm and aarch64

- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
https://github.com/CGAL/cgal/pull/2358 made it so new elements of the `Surface_mesh` use default property map values instead of values from the deleted element, but edge properties were forgotten.
* Affected package(s): `Surface_mesh`
> Surface Mesh: Fix not reseting edge property when a new element re-uses memory

- STL_Extension/include/CGAL/Compact_container.h
This pull-request will fix the [-Wnull-pointer-arithmetic] warning of AppleClang, that we can see [here]:
```
In file included from .../CGAL-5.0-Ic-1/cmake/platforms/x86-64_Darwin-18.2_Apple-clang-default_Release/test/Advancing_front_surface_reconstruction/kernels.cpp:7:
In file included from .../CGAL-5.0-Ic-1/include/CGAL/Advancing_front_surface_reconstruction.h:33:
In file included from .../CGAL-5.0-Ic-1/include/CGAL/Triangulation_data_structure_3.h:51:
.../CGAL-5.0-Ic-1/include/CGAL/Compact_container.h:662:65: warning: arithmetic on a null pointer treated as a cast from integer to pointer is a GNU extension [-Wnull-pointer-arithmetic]
return ((p - (char *) NULL) & ~ (std::ptrdiff_t) START_END) + (char *) NULL;
^ ~~~~~~~~~~~~~
```
[here]: …
> Fix AppleClang -Wnull-pointer-arithmetic warning

- Installation/CMakeLists.txt
- Installation/cmake/modules/CGAL_SetupGMP.cmake
- Installation/cmake/modules/FindGMP.cmake
- Installation/cmake/modules/FindMPFR.cmake
There was a bug in `FindGMP.cmake` and `FindMPFR.cmake`: they were using the undefined macro `cache_set`.
I have removed those variables definitions, and wrote the code differently where they were used.
Cc: @sloriot 
> Remove (GMP|MPFR)_IN_CGAL_AUXILIARY

- STL_Extension/include/CGAL/Iterator_range.h
Add an conversion operator to tuple into Iterator_range to satisfy clang used with c++11 and libc++
* Affected package(s):STL_Extension
> Fix Iterator_range for Apple Clang

- Mesh_3/examples/Mesh_3/mesh_polyhedral_domain_with_features.cpp
- Mesh_3/examples/Mesh_3/mesh_polyhedral_domain_with_features_sm.cpp
- Mesh_3/include/CGAL/IO/output_to_vtu.h
Add a test for `output_to_vtu` and then fix it.
`output_to_vtu` was added by #3297. (CGAL-4.14).
* Issue(s) solved (if any): fix #3297 
* License and copyright ownership: maintenance by GF of Inria package
> Add test for output_to_vtu

- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/CMakeLists.txt
- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/HDT2.cpp
- Hyperbolic_triangulation_2/examples/Hyperbolic_triangulation_2/CMakeLists.txt
- Hyperbolic_triangulation_2/test/Hyperbolic_triangulation_2/CMakeLists.txt
- Maintenance/public_release/scripts/precompiled_demos_zips
- Periodic_4_hyperbolic_triangulation_2/demo/Periodic_4_hyperbolic_triangulation_2/CMakeLists.txt
- Periodic_4_hyperbolic_triangulation_2/examples/Periodic_4_hyperbolic_triangulation_2/CMakeLists.txt
- Periodic_4_hyperbolic_triangulation_2/test/Periodic_4_hyperbolic_triangulation_2/CMakeLists.txt
The executables of the hyperbolic demos did not have the same name as their .cpp in the CMakeLists, which made the testsuite ignore them. 
* Affected package(s):Hyperbolic_triangulation_2, Periodic_4_hyperbolic_triangulation_2
> Fix Precompiled Demos

- Polyhedron/doc/Polyhedron/CGAL/IO/Polyhedron_iostream.h
- Polyhedron_IO/test/Polyhedron_IO/test_polyhedron_io.cpp
- Stream_support/include/CGAL/IO/File_header_OFF_impl.h
When reading an OFF file with 0 vertices the `std::ios::badbit` was set.  This was documented behavior.
I suggest that we change this with CGAL 5.0.
Is this a Breaking Change?   I didn't modify changes.md yet, as it makes merging painful.
* Issue(s) solved (if any): fix #3108
> Polyhedron:  read_OFF() must not set the badbit if there are 0 vertices

- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/MVC_post_processor_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Orbifold_Tutte_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/orbifold_shortest_path.h
> SMP: mute ARAP and Orbifold output by default

- Mesh_3/include/CGAL/Mesh_3/experimental/Get_facet_patch_id.h
- Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h
Use the new possibilities of the AABB_face_graph_triangle_primitive to unify and simplify the primitive type of the AABB_tree in the Polyhedral_mesh_domain_3.
* Affected package(s):Mesh_3
* Issue(s) solved (if any): fix #3716
> Mesh_3: Simplify AABB_primitive of Polyhedral_mesh_domain_3

- Point_set_processing_3/include/CGAL/Point_set_processing_3/internal/Parallel_callback.h
- Point_set_processing_3/include/CGAL/Point_set_processing_3/internal/Search_traits_vertex_handle_3.h
- Point_set_processing_3/include/CGAL/bilateral_smooth_point_set.h
- Point_set_processing_3/include/CGAL/compute_average_spacing.h
- Point_set_processing_3/include/CGAL/jet_estimate_normals.h
- Point_set_processing_3/include/CGAL/jet_smooth_point_set.h
- Point_set_processing_3/include/CGAL/mst_orient_normals.h
- Point_set_processing_3/include/CGAL/pca_estimate_normals.h
- Point_set_processing_3/include/CGAL/radial_orient_normals.h
- Point_set_processing_3/include/CGAL/wlop_simplify_and_regularize_point_set.h
- Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/poisson_reconstruction.cpp
- Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/poisson_reconstruction_example.cpp
- Poisson_surface_reconstruction_3/include/CGAL/Poisson_reconstruction_function.h
- Poisson_surface_reconstruction_3/include/CGAL/poisson_refine_triangulation.h
- Poisson_surface_reconstruction_3/test/Poisson_surface_reconstruction_3/poisson_reconstruction_test.cpp
- Polyhedron_IO/include/CGAL/IO/OBJ_reader.h
- Stream_support/include/CGAL/IO/trace.h
- Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/Alpha_expansion_graph_cut.h
- Surface_mesh_segmentation/package_info/Surface_mesh_segmentation/dependencies
- Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h
- Surface_mesh_skeletonization/package_info/Surface_mesh_skeletonization/dependencies
- Move `<CGAL/trace.h>`  to `Stream_support/include/CGAL/IO/trace.h>
- This file was also called by Poisson, skeletonization, and segmentation.
- Move internal files to `CGAL/Point_set_processing_3/internal/
* Affected package(s): PSP, Poisson, Skeletonization, Segmentation
> Point Set Processing:  cleanup 

- Interpolation/include/CGAL/natural_neighbor_coordinates_2.h
- Interpolation/include/CGAL/regular_neighbor_coordinates_2.h
- Triangulation_2/include/CGAL/Delaunay_triangulation_2.h
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/DT2_strict_and_weak_conflict_zone is a small feature that was integrated a while ago without approval has some legitimate concerns in it (see discussion in the small feature page). This PR reverts its changes, which are entirely code (no doc).
This small feature was integrated to fix some bug in the Interpolation package, possibly due to the presence of potentially null coordinates in the output when called on degenerate configurations. This PR filters irrelevant (`==0`) or illogical (`<0`) coordinates after the computation rather than modifying the triangulation's conflict zone.
No test failed after I reverted the small feature and before I added the filters, so it is difficult to evaluate whether whatever bug …
> Triangulation_2: revert small feature DT2_strict_and_weak_conflict_zone

- Maintenance/infrastructure/magritte.geometryfactory.com/reference_platforms/x86-64_Darwin-13.0_Apple-clang-5.0_Release-cpp11/CMakeCache.txt
- Maintenance/infrastructure/magritte.geometryfactory.com/reference_platforms/x86-64_Darwin-13.0_Apple-clang-5.0_Release-cpp11/setup
- Maintenance/infrastructure/magritte.geometryfactory.com/reference_platforms/x86-64_Darwin-13.0_Apple-clang-5.0_Release/CMakeCache.txt
- Maintenance/infrastructure/magritte.geometryfactory.com/reference_platforms/x86-64_Darwin-13.0_Apple-clang-5.0_Release/setup
- Maintenance/infrastructure/magritte.geometryfactory.com/reference_platforms/x86-64_Darwin-13.0_Apple-clang-5.1_Release-LEDA-without-GMP/CMakeCache.txt
- Maintenance/infrastructure/magritte.geometryfactory.com/reference_platforms/x86-64_Darwin-13.0_Apple-clang-5.1_Release-LEDA-without-GMP/setup
Update of the reference_platforms files of magritte to use boost 1.60
* Affected package(s):Maintenance
> Maintenance: Update boost in Magritte

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orient_polygon_soup.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h
- Polyhedron/demo/Polyhedron/Plugins/PMP/Orient_soup_plugin.cpp
- Polyhedron/demo/Polyhedron/include/CGAL/IO/read_surf_trianglemesh.h
Replace `map< pair<int,int>, flat_set<int> >` by `vector< flat_map<int, flat_set<int> >`  for the edge map.
The speed up is huge because we use a lot the edge map for navigation and the new data set is efficient because in regular cases, there are no isolated vertices.
> Speed-up polygon soup orientation

- BGL/doc/BGL/Concepts/MutableFaceGraph.h
- BGL/include/CGAL/boost/graph/copy_face_graph.h
- HalfedgeDS/include/CGAL/boost/graph/graph_traits_HalfedgeDS_default.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h
Add missing calls to reserve in functions creating meshes.
There might be more I did not think about...
> Add calls to reserve before creating meshes

- Number_types/include/CGAL/Interval_nt.h
Without this, when computing some decompositions for a matrix of intervals, Eigen looks for the largest element in a column (for instance). There may easily be 2 equal, slightly imprecise numbers that could equally well be used as pivots, but Eigen ends up spuriously throwing in the comparison between them. So we provide a different strategy for picking the pivot.
This is a functionality that I added to Eigen years ago, but for some reason I completely forgot to push the CGAL part using it :disappointed: . On a basic test of computing alpha-complexes in Gudhi, this divides the computation time by 8.
* Affected package(s): Number_types (as far as I know only NewKernel_d uses Eigen with intervals)
> Give Eigen a scoring strategy for pivot selection with intervals

- Installation/CHANGES.md
- Nef_3/doc/Nef_3/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
- Nef_3/doc/Nef_3/PackageDescription.txt
- Nef_3/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
- Nef_3/test/Nef_3/test_nef_to_soup.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h
- Make it possible to use `polygon_soup_to_polygon_mesh()` with something else than a std::vector
- Document `convert_nef_polyhedron_to_polygon_soup()` and make it use template types as point range and polygon range.
* Issue(s) solved (if any): fix #1657
* Feature/Small Feature (if any): after first reviews
* Link to compiled documentation (obligatory for small feature) [link](https://cgal.geometryfactory.com/~mgimeno/Nef_to_soup/1/Nef_3/group__PkgNef3IOFunctions.html#ga2e47f1a21e5b35af36c7ef665c66e848)
> Nef_3 : Document convert_nef_polyhedron_to_polygon_soup-GF

- Circular_kernel_3/include/CGAL/Circular_kernel_3/function_objects_polynomial_sphere.h
- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/doc/Kernel_23/Concepts/Kernel.h
- Kernel_23/doc/Kernel_23/PackageDescription.txt
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/include/CGAL/Kernel/global_functions_3.h
- Kernel_23/include/CGAL/Kernel/global_functions_internal_3.h
- Kernel_23/include/CGAL/Kernel/interface_macros.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_angle.h
Computing an angle between 3 points is code that is currently in Surface_mesh_parameterization.
I've put it in a global function and a functor of the Kernel as we also need it for measuring mesh quality.
[small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/approximate_angle) 
* License and copyright ownership:  LGPL. It was added by Mael to Surface_mesh_parameterization, so we can move it.
TODO: Changelog
> [Small Feature] Add angle(Vector_3, Vector_3) to the kernel

- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
- Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h
- Triangulation_2/test/Triangulation_2/issue_3447.cpp
We need two versions of the insert_constraint() function of the class `Polyline_constraint_hierarchy_2`, namely
- one for the old API where constraints were just 2d segments (it is deprecated), and where one cannot insert the same constraint twice
- and one for polylines where it is possible to insert the same polyline twice.
* Issue(s) solved (if any): fix #3447
> Triangulation_2:  Fix Polyline_constraint_hierarchy_2

- Boolean_set_operations_2/archive/demo/Boolean_set_operations_2_GraphicsView/CMakeLists.txt
- GraphicsView/demo/Alpha_shapes_2/CMakeLists.txt
- GraphicsView/demo/Apollonius_graph_2/CMakeLists.txt
- GraphicsView/demo/Bounding_volumes/CMakeLists.txt
- GraphicsView/demo/Circular_kernel_2/CMakeLists.txt
- GraphicsView/demo/Generator/CMakeLists.txt
- GraphicsView/demo/L1_Voronoi_diagram_2/CMakeLists.txt
- GraphicsView/demo/Largest_empty_rect_2/CMakeLists.txt
- GraphicsView/demo/Periodic_2_triangulation_2/CMakeLists.txt
- GraphicsView/demo/Periodic_2_triangulation_2/Periodic_2_Delaunay_triangulation_2.cpp
- GraphicsView/demo/Polygon/CMakeLists.txt
- GraphicsView/demo/Segment_Delaunay_graph_2/CMakeLists.txt
- GraphicsView/demo/Segment_Delaunay_graph_Linf_2/CMakeLists.txt
- GraphicsView/demo/Snap_rounding_2/CMakeLists.txt
- GraphicsView/demo/Spatial_searching_2/CMakeLists.txt
- GraphicsView/demo/Stream_lines_2/CMakeLists.txt
- GraphicsView/demo/Stream_lines_2/Stream_lines_2.cpp
- Mesh_2/demo/Mesh_2/CMakeLists.txt
- Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/CMakeLists.txt
- Periodic_4_hyperbolic_triangulation_2/demo/Periodic_4_hyperbolic_triangulation_2/CMakeLists.txt
- Polyline_simplification_2/demo/Polyline_simplification_2/CMakeLists.txt
- Principal_component_analysis/demo/Principal_component_analysis/CMakeLists.txt
- Surface_mesher/demo/Surface_mesher/CMakeLists.txt
just a cleanup
>   Make sure the compiler can find generated .moc files
include_directories(BEFORE ${CMAKE_CURRENT_BINARY_DIR})
include_directories( ${QT_INCLUDE_DIR} )
in a few files. Either this is really needed and then we have to add it in other demos, or we can remove it.
* Affected package(s): demos
> CMakeLists.txt: Remove unnecessary include directories

- Scripts/developer_scripts/cgal_create_package_dir.py
The file names `copyright` has no extension `.txt`.
> Scripts:  Fix cgal_create_package_dir

- Number_types/include/CGAL/FPU.h
- Number_types/include/CGAL/Interval_nt.h
Reimplement interval arithmetic using SSE, for x86.
If I compile benchmark/Triangulation_3/simple_2.cpp with `-DCGAL_NO_STATIC_FILTERS -DCGAL_NO_STRUCTURAL_FILTERING` and run it for 100000 points, this patch roughly divides the running time by 2.
This is x86-only, mostly because I don't know of any good multi-platform simd library that would allow to write (mostly) common code for neon and powerpc (there may be something in a future standard, but that's far away). I could instead write the code in a way that works on x86/powerpc/arm/etc, but then it would not work for MSVC, which I assume would make some people unhappy.
The performance is likely to differ for different CPUs. The most crucial operation, `operator*`, has several implementations that you can compare.
There are probably more …
> SSE version of Interval_nt

- Number_types/include/CGAL/int.h
- Number_types/include/CGAL/long_double.h
- Number_types/include/CGAL/test_FPU_rounding_mode_impl.h
- Stream_support/include/CGAL/IO/io_impl.h
@afabri reported that the header `<CGAL/Interval_nt.h>` did not compile. That is due to cyclic dependencies, that all lead to `<CGAL/basic.h>` or `<CGAL/number_type_basic.h>`. This pull-request tries to reduce the graph of dependencies between headers of `Number_types/`. At least now `<CGAL/Interval_nt>` does compile.
I have verified that the whole testsuites of `Number_types`, `Kernel_23`, and `Stream_support` still pass, with CTest.
* Affected package(s): Number_types, all the core of CGAL
> Reduce inclusions of <CGAL/basic.h> and <CGAL/number_type_basic.h>

- Point_set_processing_3/doc/Point_set_processing_3/NamedParameters.txt
- Point_set_processing_3/doc/Point_set_processing_3/Point_set_processing_3.txt
- Point_set_processing_3/examples/Point_set_processing_3/normals_example.cpp
- Point_set_processing_3/include/CGAL/Point_set_processing_3/internal/neighbor_query.h
- Point_set_processing_3/include/CGAL/bilateral_smooth_point_set.h
- Point_set_processing_3/include/CGAL/jet_estimate_normals.h
- Point_set_processing_3/include/CGAL/jet_smooth_point_set.h
- Point_set_processing_3/include/CGAL/mst_orient_normals.h
- Point_set_processing_3/include/CGAL/pca_estimate_normals.h
- Point_set_processing_3/include/CGAL/remove_outliers.h
- Point_set_processing_3/include/CGAL/wlop_simplify_and_regularize_point_set.h
Many _Point Set Processing_ algorithms use a KD-tree to make neighborhood queries. These algorithms currently use a fixed K number of nearest neighbors, but in some cases it can be interesting to use a fixed spherical neighborhood radius instead.
This small feature adds the possibility for 6 algorithms to use the (existing) named parameter `neighbor_radius` to switch to this behavior. The default behavior remains the same (using K).
The following functions are impacted:
- `bilateral_smooth_point_set()`
- `jet_estimate_normals()`
- `jet_smooth_point_set()`
- `mst_orient_normals()`
- `pca_estimate_normals()`
- `remove_outliers()`
The named parameter `neighbor_radius` can be used. If this parameter is provided, then the parameter `k` is used as a maximum number of points (to avoid overly …
> [Small Feature] PSP: Spherical Neighborhood Queries

- Mesh_3/include/CGAL/Polyhedral_complex_mesh_domain_3.h
This PR improves the documentation of the constructor of `Polyhedral_complex_mesh_domain_3`.
Pairs of subdomain indices cannot be reversed or the domain would not be consistent.
* Issue(s) solved (if any): fix #3870 .
> Mesh_3 : improve doc of constructor for `Polyhedral_complex_mesh_domain_3`

- Generator/include/CGAL/Random_polygon_2_sweep.h
- Polygon/include/CGAL/Polygon_2/Polygon_2_simplicity.h
From @mhsaar 
Some STL implementations may call comparator(x, x)
to verify irreflexivity.  Don't violate less_than_in_tree's
in such an environment.
> Fix for less

- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/arrange_offset_polygons_2.h
- Straight_skeleton_2/include/CGAL/arrange_offset_polygons_2.h
Return `false` instead of raising an exception.
> Change return type to avoid raising a precondition

- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_2.h
- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
- Triangulation_2/include/CGAL/Constrained_Delaunay_triangulation_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
- Triangulation_2/include/CGAL/Regular_triangulation_2.h
- Triangulation_2/include/CGAL/Triangulation_2.h
- Triangulation_2/include/CGAL/Triangulation_2/internal/Polyline_constraint_hierarchy_2.h
- Triangulation_2/include/CGAL/Triangulation_hierarchy_2.h
- Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_const_triang_plus_2.h
So far we only write/read the underlying constrained triangulation. The fact that constraints consist of subconstraints was lost.   
I based this PR  on #3890 
> Triangulation_2:  Fix I/O for Constrained_triangulation_plus_2 

- Intersections_3/include/CGAL/Intersections_3/intersection_3_1_impl.h
When computing the intersection of 2 almost collinear segments, the intersection of the two supporting lines is first computed by diving 0 by the length of the cross product of the support vector (which is also 0):
```c++
const Point_3 &p1 = l1.point();
const Point_3 &p3 = l2.point();
const Vector_3 &v1 = l1.to_vector();
const Vector_3 &v2 = l2.to_vector();
const Point_3 p2 = p1 + v1;
const Point_3 p4 = p2 + v2;
if(!K().coplanar_3_object()(p1,p2,p3,p4)) return intersection_return<typename K::Intersect_3, typename K::Line_3, typename K::Line_3>();
const Vector_3 v3 = p3 - p1;
const Vector_3 v3v2 = cross_product(v3,v2);
const Vector_3 v1v2 = cross_product(v1,v2);
const FT t = ((v3v2.x()*v1v2.x()) + (v3v2.y()*v1v2.y()) + (v3v2.z()*v1v2.z())) /
(v1v2.squared_length());
```
In that case, the …
> Intersections_3: Fix almost collinear segment bug

- Documentation/doc/Documentation/Installation.txt
- Installation/INSTALL.md
The code of CGAL_Qt5 and CGAL Qt5 demos requires Qt-5.9, but we kept documenting that the minimal version was 5.3. Now, document version 5.9 or later.
* License and copyright ownership: maintenance
> Document that Qt 5.9 or later is required

- BGL/include/CGAL/boost/graph/helpers.h
If the mesh being tested is actually invalid, infinite loops are possible when walking around vertices (for example). Loops must thus break after a while. Added a few more tiny tests too (number of edges vs number of halfedges).
Also reduced verbosity (don't care about things that go well), and improved indentation to make it readable.
> BGL: Fix is_valid_polygon_mesh not breaking away from potential infinite loops

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_slicer.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/polygon_mesh_slicer_test.cpp
Insure that the polylines produced by the slicer are ccw when seen from the positive side of the slicing plane.
* Issue(s) solved (if any): fix #3883
> PMP::Orient polylines of Polgon Mesh Slicer ccw.

- Classification/include/CGAL/Classification/ETHZ/internal/random-forest/forest.hpp
Missing `#include <algorithm>`.
The incriminated file moved and changed quite a bit in `CGAL 4.14`, that's why I don't do the fix for `4.13` (to avoid wasting time with conflicts for a minor bug).
> [Classification] Add missing "algorithm" include

- .travis.yml
- .travis/build_package.sh
- .travis/template.txt
`TRAVIS_PULL_REQUEST` is actually never empty:
> `TRAVIS_PULL_REQUEST`: The pull request number if the current job is a pull request, “false” if it’s not a pull request.
(from the [documentation](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables))
Use `TRAVIS_PULL_REQUEST_BRANCH` instead:
> `TRAVIS_PULL_REQUEST_BRANCH`:
>    - if the current job is a pull request, the name of the branch from which the PR originated.
>    - if the current job is a push build, this variable is empty ("").
* Affected package(s): Travis
> Use $TRAVIS_PULL_REQUEST_BRANCH instead

- Mesh_3/examples/Mesh_3/CMakeLists.txt
- Mesh_3/examples/Mesh_3/mesh_3D_image_with_custom_initialization.cpp
- Mesh_3/include/CGAL/Mesh_criteria_3.h
- Mesh_3/test/Mesh_3/test_meshing_polyhedral_complex.cpp
This pull-request adapts Mesh_3 so that it compiles with newest Boost version 1.71 (current `master` branch of Boost). It stays compatible with previous Boost versions as well.
* Affected package(s): Mesh_3, Installation
* This is a bug-fix, based on CGAL-4.13.1.
* No conflict with current `integration` branch.
Cc: @afabri @janetournois
> Adapt Mesh_criteria_3 to Boost 1.71 (current 'master')

- Installation/CHANGES.md
The deprecated API was removed by https://github.com/CGAL/cgal/pull/3739 (it's been deprecated for 3 releases). This adds a note about this removal in the `CHANGES.md`.
> Add changes about old PSP API removed

- Installation/cmake/modules/CGAL_add_test.cmake
When the current binary dir is a sub-directory of the current sources
dir, then the recursive copy of the sources dir to `__exec_test_dir/`
cannot be done. In that case, do not setup the fixture
directory. Tests can still be run in the source directory (and pollute
it).
@afabri: That is an old bug that prevented you from using CTest. You reported it more than one year ago. It will be soon fixed in release branches and `master`.
* Affected package(s): CMake
* Issue(s) solved (if any): fix #2865
> Fix CTest CGAL tests when binary dir is a sub-directory

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
Should fix the compilation error described in [this comment](https://github.com/CGAL/cgal/pull/3857#issuecomment-493866442).
> Add missing 'using' for boost's choose_param() / get_param()

- Convex_hull_3/include/CGAL/Convex_hull_traits_3.h
The documentation of `convex_hull_3` says that, if the kernel is "like `Epick`", then the default traits class of `convex_hull_3` is `Convex_hull_traits_3`.
But that is wrong, because `Convex_hull_traits_3` is documented with only two template parameters, and if the kernel is "like `Epick`", the third argument is `CGAL::Tag_true`, whereas the default of that parameter is `CGAL::Tag_false`. If users want to write explicitly the traits in the call to `convex_hull_3`, they cannot know that there is a third parameters, and that it must be `Tag_true`.
This PR fixes the default of that third argument.
Cc: @afabri
> Fix the default of 3rd template parameter of Convex_hull_traits_3

- Installation/CHANGES.md
- Triangulation_2/doc/Triangulation_2/CGAL/Delaunay_triangulation_2.h
- Triangulation_2/doc/Triangulation_2/CGAL/Triangulation_2.h
- Triangulation_2/include/CGAL/Delaunay_triangulation_2.h
- Triangulation_2/include/CGAL/Triangulation_2.h
- Triangulation_2/test/Triangulation_2/test_triangulation_with_zip_iterator_2.cpp
- Triangulation_3/doc/Triangulation_3/CGAL/Delaunay_triangulation_3.h
- Triangulation_3/doc/Triangulation_3/CGAL/Triangulation_3.h
- Triangulation_3/include/CGAL/Delaunay_triangulation_3.h
- Triangulation_3/include/CGAL/Regular_triangulation_3.h
- Triangulation_3/include/CGAL/Triangulation_3.h
- Triangulation_3/test/Triangulation_3/test_Triangulation_with_transform_iterator.cpp
- Triangulation_3/test/Triangulation_3/test_Triangulation_with_zip_iterator.cpp
Add a constructor and insert function that takes a range of points with info (pair/tuple/transform iterator/zip iterator) to `CGAL::Triangulation_2` and `CGAL::Triangulation_3`.
No longer call `spatial_sort()` when inserting a range of points into a  triangulation, as the form of the triangles depends on the insertion order. 
* Affected package(s): Triangulation_2, Triangulation_3
* Issue(s) solved (if any):  See cgal-discuss: Add information in Triangulation while inserting a range of points
> 2D and 3D Triangulations:  Unify insertion of range of points with info

- Mesh_3/include/CGAL/Mesh_3/Is_mesh_domain_field_3.h
- Mesh_3/include/CGAL/Mesh_cell_criteria_3.h
- Mesh_3/include/CGAL/Mesh_edge_criteria_3.h
- Mesh_3/include/CGAL/Mesh_facet_criteria_3.h
- Mesh_3/test/Mesh_3/test_mesh_capsule_var_distance_bound.cpp
Allow lambdas (or other callables) as [`MeshDomainField_3`].
[`MeshDomainField_3`]: https://doc.cgal.org/4.14/Mesh_3/classMeshDomainField__3.html
That patch uses C++11 `<type_traits>`, and `boost::callable_traits::is_invocable` that is available only since 1.66. If Boost<1.66, then the previous behavior (testing `Sizing_field::FT`) is kept.
Fix issue #3005.
* Issue(s) solved (if any): fix #3005 
This PR uses C++11, and can only target CGAL-5.0 or later.
> Mesh_3: Allow lambdas (or other callables) as MeshDomainField_3

- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
To read into a point with `is >> p`  is a mistake for a homogeneous point.
Instead read three doubles.
> Surface_mesh: Fix read_off(istream,Surface_mesh)

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
Since PR #3412, the 'Load plugin' had two issues, fixed by this PR:
- a segfault because a dangling reference to a destroyed object,
- the inability to load manually a plugin with the wrong meta-data.
> Polyhedron demo:  fix the menu entry 'Load plugin'

- Scripts/developer_scripts/tag_pr_per_release.sh
Example of results:
* [PR merged in 4.13.1 since 4.13](https://github.com/CGAL/cgal/issues?q=label%3AMerged_in_4.13.1+is%3Aclosed)
* [PR merged in 4.14 since 4.13](https://github.com/CGAL/cgal/issues?q=label%3AMerged_in_4.14+is%3Aclosed)
The script use `ghi` and requires a github token has been created and registered using for exemple:
`git config --global ghi.token TOKEN`
> Add script to label PR merge in a release since the previous major one

- Polygon_mesh_processing/doc/Polygon_mesh_processing/NamedParameters.txt
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h
By default, hole filling functions in PMP use the 3D Delaunay triangulation as a basis to chose the best triangulation to fill the given hole. When it does not succeed to find a solution in the Delaunay triangulations space (extended by some more cases, not exhaustive), the hole filling function fails to fill the hole.
This PR adds a fallback to the non-Delaunay framework and allows to check the whole set of triangulations to find a solution.
* Issue(s) solved (if any): fix #3928
> PMP : add fallback to non-Delaunay triangulations for hole filling functions

- Polyhedron_IO/include/CGAL/IO/PLY_writer.h
- Stream_support/include/CGAL/IO/WKT.h
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Some BOOST_FOREACH sneaked in through recent merges.
* Affected package(s): Surface_mesh, Stream_support, Polyhedron_IO
> Replace BOOST_FOREACH with C++11 for

- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
... because we add the property in the constructor and never remove it.
> Surface_mesh: No need to call add_property_map()

- Shape_detection/include/CGAL/Shape_detection/Region_growing/Region_growing_on_polygon_mesh/Least_squares_plane_fit_region.h
Shape detection
I fixed the `CGAL::max` error for Windows test suite by changing it to `(CGAL::max)`.
* Affected package(s): Point_set_shape_detection_3
> Shape detection

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h
For unused points and duplicate polygons to be discarded, `repair_polygon_soup()` swaps bad element IDs to be the end of a container before resizing the container to discard the bad elements. The algorithms were similarly wrong in both cases.
> PMP: Fix repair polygon soup bad swaps

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
The bug was hard to spot because in most cases the intersection point was recomputed instead of using the existing value.
> Fix invalid index

- Mesh_3/include/CGAL/internal/Mesh_3/check_weights.h
If some vertices have a non-zero weights and do not belong to input
features, then global optimizers should not be used.
Before this PR, the case without feature protection was not treated.
It is already documented in [`exude_mesh_3()`](https://doc.cgal.org/latest/Mesh_3/group__PkgMesh3Functions.html#gabf09a95838226da018a742a631824af9) that "it [...] must be the last optimizer to be called"
> Mesh_3 : fix global optimizers protection

- Mesh_3/test/Mesh_3/test_meshing_3D_gray_image.cpp
See https://github.com/CGAL/cgal/issues/2870#issuecomment-494355193.
* Affected package(s): Mesh_3 (testsuite only)
* Issue(s) solved (if any): fix #2870
The buggy test was introduced in CGAL-4.12. Will be fixed in CGAL-4.13.2.
> Mesh_3: fix issue #2870 (do not deactivate all topological criteria)

- AABB_tree/include/CGAL/AABB_traits.h
- AABB_tree/test/AABB_tree/aabb_test_all_intersected_primitives_tree.cpp
Add do_intersect() overloads for AABB_trees.  The functions
- `do_intersect()`
- `any_intersected_primitive()`
- `all_intersected_primitives()`
of the AABB_traits now work with another `AABB_tree` as query.
> AABB_tree: add do_intersect() for trees

- Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_filtered_traits_2.h
- Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/Segment_Delaunay_graph_2.txt
* Affected package(s):  Segment_Delaunay_graph_2  **only documentation**
> Segment_Delaunay_graph_2: Improve documentation

- Classification/include/CGAL/Classification/Cluster.h
- Polyhedron/demo/Polyhedron/Plugins/Classification/Cluster_classification.cpp
Because they use vectors internally (that can grow big), clusters are heavy to copy. I fixed this by using shared pointers (instantiated only when explicitly constructed).
There was also a bug in the computation of the bbox: it was the full bounding box of all items no matter what the actual cluster was. This is also fixed.
> [Classification] Make cluster lightweight to copy + fix bbox computation

- Classification/include/CGAL/Classification/ETHZ/internal/random-forest/forest.hpp
`random_shuffle` is deprecated since C++11 and removed in C++17, to avoid errors, we use the CGAL  alternative `CGAL::cpp98::random_shuffle`.
> Classification: use cpp98::random_shuffle to avoid errors in C++17

- BGL/include/CGAL/boost/graph/parameters_interface.h
- BGL/test/BGL/test_cgal_bgl_named_params.cpp
- Installation/CHANGES.md
- Periodic_3_triangulation_3/include/CGAL/Periodic_3_regular_triangulation_traits_3.h
- Polygon_mesh_processing/doc/Polygon_mesh_processing/NamedParameters.txt
- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
- Polygon_mesh_processing/doc/Polygon_mesh_processing/dependencies
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/connected_component_polyhedron.cpp
- Polygon_mesh_processing/test/Polygon_mesh_processing/connected_component_surface_mesh.cpp
- Polyhedron/doc/Polyhedron/CGAL/Polyhedron_3.h
- Polyhedron/doc/Polyhedron/dependencies
The functions [PMP::keep_large_CCs](https://doc.cgal.org/latest/Polygon_mesh_processing/group__keep__connected__components__grp.html#ga6de4710f16947ea7817a0365c2fb72f1) and [PMP::keep_largest_CCs](https://doc.cgal.org/latest/Polygon_mesh_processing/group__keep__connected__components__grp.html#ga68c6c29dfc6a26a6a2f8befe6944f19d) both determine what is the larger (largest) connected components by counting the number of faces in each connected component. This is quite limited and can also be a little counter intuitive as "large" more naturally evocates the size (i.e. the area) of the connected component rather than the number of its elements. …
> PMP: Generalize `keep_large(st)_CCs`

- Intersections_3/include/CGAL/Intersections_3/internal/intersection_3_1_impl.h
This call to `do_intersect()` is ambiguous, resulting in a compile time error when compiling with clang on my mac.
> do_intersect() Ambiguity

- Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h
- Triangulation_2/test/Triangulation_2/issue_4010.cpp
Fix the bookkeeping of constraints. Forgot to remove it from a `std::map`.
**This must NOT go into master**, as we have removed the function `remove_constraint()` which takes two vertex handles as key.
* Issue(s) solved (if any): fix #4010
> Triangulation_2: Fix CDT_plus_2::remove_constraint()

- Triangulation_2/test/Triangulation_2/issue_4010.cpp
Accidentally used C++11 in test file that was merged in 4.14.1
* Issue(s) solved (if any): fix #4033
> Triangulation_2: Do not use C++11

- Intersections_2/test/Intersections_2/test_intersections_2.cpp
* Affected package(s): `Intersections_2`
* Issue(s) solved (if any): partial fix of #4033
> Intersections_2: remove superfluous 'typename's

- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Basic_predicates_C2.h
If the base kernel has an exact number type that does not provide a square root, constructions use square roots extensions to do all the intermediary comparisons. However, at the end you still need to compute actual roots, which will be done using a `sqrt` over a double extracted from the exact number type.
To avoid negative numbers popping up under square roots, this patch sanitizes the input of the square root function in the function that evaluates the nested square root extension.
* Affected package(s): `Segment_Delaunay_Graph_2`
* Issue(s) solved (if any): fix #4030
> SDG: Sanitize input of square root in evaluation of nested extensions

- CGAL_ImageIO/include/CGAL/Image_3.h
- Mesh_3/include/CGAL/Labeled_image_mesh_domain_3.h
- Mesh_3/include/CGAL/Labeled_mesh_domain_3.h
Fix https://github.com/CGAL/cgal/pull/3539#issuecomment-503078370.
* Issue(s) solved (if any): fix #3539.
> Fix the use of VTK offset in Labeled_mesh_domain_3

- Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h
- Triangulation_2/test/Triangulation_2/issue_4025.cpp
Fix an undocumented, so far unused, and also untested (public) function in order to fix an issue.
* Issue(s) solved (if any): fix #4025
> Triangulation_2: Fix remove_vertex_from_constraint

- Kernel_23/test/Kernel_23/Filtered_cartesian.cpp
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_tetrahedron_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_triangle_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_new_3.h
Fix remaining warnings after #3939.
Fix one error from #4033.
> Kernel_23: fix warnings

- Installation/cmake/modules/CGAL_add_test.cmake
Add a new ctest fixture, that checks the build system. That will avoid that `cmake` is run in parallel several times, when `ctest -j` is used.
@maxGimeno That may explain why you found CTest unreliable, so far. Now, CTest will always start by checking if `cmake` must be run before starting the tests.
* Affected package(s): CMake
* License and copyright ownership: GeometryFactory
I think this pull-request cannot really be tested, unless perhaps in the test platform using CTest instead of `autotest_cgal`.
> CTest: Add a new ctest fixture, that checks the build system

- Polynomial/include/CGAL/Test/_test_polynomial_traits_d.h
#3463  Summary of Changes
Fix issue #4044 about warnings in Polynomial testsuite with LEDA.
* Affected package(s): Polynomial
* Issue(s) solved (if any): fix #4044
* License and copyright ownership: trivial maintenance
> warning, fix issue #4044

- Classification/include/CGAL/Classification/Cluster.h
I introduced a lambda + auto with PR https://github.com/CGAL/cgal/pull/3961 (I thought it would go in 5.0, but finally based it on 4.13...). This replaces it by a simple functor. 
* Affected package(s): Classification + demo
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/4033
> Classification: Remove lambda/auto from cxx03 code

- Mesh_3/include/CGAL/IO/output_to_vtu.h
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14.1-I-173.shtml#Mesh_3_Examples
* Issue(s) solved (if any): related to #4033 
> Mesh_3: older versions of gcc does not like that pair of const

- Mesh_3/include/CGAL/internal/Mesh_3/Handle_IO_for_pair_of_int.h
`std::cout << std::make_pair(0, 1)` does not compile... I have tried in the past to add an `operator<<` for `std::pair`, but that does not work. Let's remove that old attempt, now.
> Mesh_3: remove the attempt for `os << std::pair`

- CGAL_Core/include/CGAL/CORE/Gmp_impl.h
- CGAL_Core/include/CGAL/CORE/poly/Poly.h
- CGAL_Core/include/CGAL/CORE/poly/Poly.tcc
Summary of Changes
There was `using namespace std;` in the global scope of `CGAL_Core/include/CGAL/CORE/Gmp_impl.h`. That meant that, in header-only, all CGAL programs using CORE were importing that namespace std in the global scope. And thus conflicts between `byte` and `std::byte` (from C++20).
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14.1-I-173/Hyperbolic_triangulation_2_Demo/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz
* Affected package(s): CGAL_Core
> CGAL_Core: remove 'using namespace std' from namespaces

- .travis/test_package.sh
Currently, if the file dependencies is misisng in the package_info of a package, Travis simply returns an error, complaining it is missing. With that PR, it will also run the cmake step that computes the dependencies and display them.
> Travis: compute dependencies when file is missing

- Polyhedron/demo/Polyhedron/Classification.cpp
- Polyhedron/demo/Polyhedron/Mesh_3.cpp
- Polyhedron/demo/Polyhedron/Polyhedron_3.cpp
- Polyhedron/demo/Polyhedron/Polyhedron_demo.cpp
Factorize more code into Polyhedron_demo.cpp
At the same time, fix that warning from Qt5:
> Attribute Qt::AA_UseDesktopOpenGL must be set before QCoreApplication is created.
* License and copyright ownership: maintenance of the demo
> Factorize more code into Polyhedron_demo.cpp

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
Fix PR #3987 with "mesh surface only". That was a bug in #3987 merged in 4.14.1-dev. If one tries "mesh surface" then there is an assertion `!tree.empty()`:
```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
what():  CGAL ERROR: assertion violation!
Expr: !tree_.empty()
File: [...]/Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h
Line: 649
```
> Fix PR #3987 with "mesh surface only"

- BGL/include/CGAL/boost/graph/helpers.h
Some error messages were not printed despite failure. Some error messages were printed wrongly since as soon as 'valid' was wrong, everything below was printed, even if the test was not actually failing.
> BGL: Fix output of "is_valid_polygon_mesh" function family

- Stream_support/include/CGAL/IO/PLY.h
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
* Fix uninitialized warning (see [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-I-72/Polyhedron_Demo/TestReport_lrineau_ArchLinux-CXX17-Release.gz)). Code introduced in 5.0.
* Fix error https://github.com/CGAL/cgal/issues/4067 that happens when a property is found on edges and halfedges, but then its type is not handled, which leads to the header being filled _but_ the properties not written (which leads to an error when reading the produced PLY). Now, the header for edges and halfedges are only written if the properties were actually found with an handled type.
> [Surface Mesh / PLY] Fix uninitialized warning and error on unhandled properties

- Polyhedron_IO/include/CGAL/IO/OBJ_reader.h
If an index is negative in a face of an OBJ file, reads it relatively to the current state of the points vector instead of brutally crashing.
* Affected package(s):Polyhedron_IO
* Issue(s) solved (if any): fix #4066
> Polyhedron_IO: OBJ_reader reads relative indices

- BGL/test/BGL/test_Face_filtered_graph.cpp
Fix a memory leak in `test/BGL/`, so that one can run CTest with ASAN enabled without false-positives.
For `master` only, because I have used C++14 (`std::make_unique`) to fix the issue.
> BGL: fix memory leak in test

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/MainWindow.ui
* Issue(s) solved (if any): fix #4070
> Polyhedron Demo: Fix View Menu

- Scripts/developer_scripts/autotest_cgal_with_ctest
Move logging functions in the script to avoid having to ask for CGAL-I before it is set.
> Scripts: Fix autotest_with_ctest

- Installation/CHANGES.md
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
Add a new function to collect all non manifold vertices at once. Useful because `is_non_manifold_vertex` runs in linear time.
* Feature/Small Feature (if any): [here](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_non_manifold_vertices_collector) -- pre-approved date: 2019-07-02 (accepted 2019-07-16)
> PMP: Add function 'non_manifold_vertices'

- AABB_tree/demo/AABB_tree/MainWindow.cpp
- GraphicsView/demo/Circular_kernel_2/ArcsGraphicsItem.h
- GraphicsView/demo/Periodic_2_triangulation_2/include/CGAL/Qt/PeriodicTriangulationGraphicsItem.h
- GraphicsView/include/CGAL/Qt/AlphaShapeGraphicsItem.h
- GraphicsView/include/CGAL/Qt/DelaunayMeshTriangulationGraphicsItem.h
- GraphicsView/include/CGAL/Qt/DemosMainWindow_impl.h
- GraphicsView/include/CGAL/Qt/PointsGraphicsItem.h
- GraphicsView/include/CGAL/Qt/PointsInKdTreeGraphicsItem.h
- GraphicsView/include/CGAL/Qt/PolygonGraphicsItem.h
- GraphicsView/include/CGAL/Qt/PolygonWithHolesGraphicsItem.h
- GraphicsView/include/CGAL/Qt/RegularGridGraphicsItem.h
- GraphicsView/include/CGAL/Qt/RegularGridVectorFieldGraphicsItem.h
- GraphicsView/include/CGAL/Qt/RegularTriangulationGraphicsItem.h
- GraphicsView/include/CGAL/Qt/SegmentDelaunayGraphGraphicsItem.h
- GraphicsView/include/CGAL/Qt/SegmentDelaunayGraphLinfGraphicsItem.h
- GraphicsView/include/CGAL/Qt/TriangulationGraphicsItem.h
- GraphicsView/include/CGAL/Qt/qglviewer_impl.h
- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Viewer.cpp
- Polyline_simplification_2/demo/Polyline_simplification_2/include/CGAL/Qt/Polyline_simplification_2_graphics_item.h
- Polyline_simplification_2/demo/Polyline_simplification_2/include/CGAL/Qt/TriangulationArrangementGraphicsItem.h
- Principal_component_analysis/demo/Principal_component_analysis/MainWindow.cpp
- Three/include/CGAL/Three/TextRenderer.h
- Triangulation_3/demo/Triangulation_3/Viewer.cpp
Replace the `matrix` calls with `worldTransform`
* Issue(s) solved (if any): fix #4061
> Fix Qt deprecation warnings

- GraphicsView/include/CGAL/Buffer_for_vao.h
The fix is small; tested locally.
Bug fix in is_empty method in Buffer_for_vao
* Affected package(s): all viewers
> Bug fix in is_empty method in Buffer_for_vao

- Principal_component_analysis/include/CGAL/PCA_util_Eigen.h
- Principal_component_analysis_LGPL/include/CGAL/centroid.h
The variant of PCA on tetrahedra is broken, the returned plane/line has no meaning and is obviously wrong. It's been this way for a very long time, I tracked the bug back to CGAL 4.7 (I did not have the faith to go farther...). The problem is we only test compilation+execution on this package, not the validity of the result from a geometric point of view. We know for sure that the variants of PCA on points and triangles work because we (I for starters) use them regularly, but the other variants might be broken too as far as we know.
At some point, we want to add validity tests, but I discussed it with @palliez in March and we did not have time to work on those tests since then. In the mean time, Pierre found back his old prototype code which works well, so we thought we should at least …
> [PCA] Fix PCA on tetrahedra

- NewKernel_d/include/CGAL/NewKernel_d/Types/Weighted_point.h
- NewKernel_d/include/CGAL/NewKernel_d/function_objects_cartesian.h
Looks like a typo kind of mistake: the value was computed and stored repeatedly in the inner loop instead of once in the outer loop... At least it was correct, if wasteful.
> Move store outside the loop.

- Documentation/doc/Documentation/Installation.txt
- Installation/CMakeLists.txt
Fix #3767:
> The release after CGAL-4.14 will be named CGAL-5.0.
> 
> We should make CGAL_HEADER_ONLY the default in that version.
* Issue(s) solved (if any): fix #3767
> Make CGAL_HEADER_ONLY the default in CGAL-5.0

- Convex_hull_3/test/Convex_hull_3/test_extreme_points.cpp
- Convex_hull_3/test/Convex_hull_3/test_halfspace_intersections.cpp
- Kernel_23/include/CGAL/Exact_predicates_inexact_constructions_kernel.h
- Kernel_23/test/Kernel_23/Filtered_cartesian.cpp
`EPICK_without_intervals` actually inherits intervals, defeating its purpose. It might be useful and can be fixed e.g. by changing the way the static filter wrapper works (see https://github.com/CGAL/cgal/pull/3939); however, the release is nigh, and so this PR removes it.
> Kernel 23: remove epick without intervals

- Point_set_processing_3/include/CGAL/IO/read_las_points.h
- Point_set_processing_3/include/CGAL/IO/write_las_points.h
- Point_set_processing_3/include/CGAL/IO/write_ply_points.h
Some functions in PLY/LAS IO are non-template, which creates multiple definition errors if they are included several times. This fixes it.
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/4090
> Add missing inlines to PSP IO non-template functions

- Installation/cmake/modules/CGAL_add_test.cmake
- Polyhedron/demo/Polyhedron/implicit_functions/CMakeLists.txt
Put `Mesh_3_implicit_finctions` in `Polyhedron_demo` and `check_build_system` in `Installation` to get rid of the additional lines in the ctest testsuite.
* Affected package(s):Installation, Polyhedron_Demo
> Installation: Add missing cmake labels

- Mesh_3/include/CGAL/Mesh_3/Mesh_global_optimizer.h
- Mesh_3/include/CGAL/Mesh_3/Worksharing_data_structures.h
add missing parenthesis around `std::min` and `std::max`, and `std::numeric_limits<FT>::max` to fix compilation on Windows.
> Mesh_3 : add missing parenthesis around min and max for windows

- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_clip.cpp
Use a correct way to reset the stringstream in test_pmp_clip, the `=` operator being private.
> PMP: Fix test_pmp_clip

- Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
PR #2739 introduced a bug in CGAL-4.13. This PR fixes it.
* Issue(s) solved (if any): fix #2739
> Mesh_3: fix protection of 1D features on borders of 3D images

- Triangulation/doc/Triangulation/Concepts/TriangulationDataStructure.h
- Triangulation_2/doc/Triangulation_2/CGAL/Triangulation_2.h
Removing last "warning: unbalanced grouping commands" messages.
Note: maybe useful to add in `Triangulation_2/doc/Triangulation_2/CGAL/Triangulation_2.h` some `\name` parts for handles / iterators / ...
> warning: unbalanced grouping commands

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
The collapse step of `PMP::isotropic_remeshing()` has a post processing step that removes degenerate faces.
We had forgotten to deal with degenerate faces that are on a boundary, and this lead to a segfault.
It's fixed now.
* Issue(s) solved (if any): fix #4112
> Fix segfault in `PMP::isotropic_remeshing()`

- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
Fix the documentation for the value  type of  `Constrained_triangulation_plus_2::Subconstraint_iterator`.
* Issue(s) solved (if any): fix #4005
> Triangulation_2:  Fix documentation of a typedef

- Polygonal_surface_reconstruction/doc/Polygonal_surface_reconstruction/Polygonal_surface_reconstruction.txt
- Polygonal_surface_reconstruction/doc/Polygonal_surface_reconstruction/dependencies
- Polygonal_surface_reconstruction/doc/Polygonal_surface_reconstruction/examples.txt
- Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/CMakeLists.txt
- Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_with_region_growing.cpp
This PR proposes to add an extra example to the package [Polygonal_surface_reconstruction](https://github.com/CGAL/cgal/tree/master/Polygonal_surface_reconstruction) (PSR) that shows how to use the PSR with the new version of region growing from the package [Shape_detection](https://github.com/CGAL/cgal/tree/master/Shape_detection). The docs are updated accordingly.
* Added and locally tested (MacOS/AppleClang).
* Affected package(s): Polygonal_surface_reconstruction
* Issue(s) solved (if any): no issues
* Feature/Small Feature (if any): not a feature
> Polygonal surface reconstruction with a region growing example

- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/CMakeLists.txt
- Periodic_4_hyperbolic_triangulation_2/demo/Periodic_4_hyperbolic_triangulation_2/CMakeLists.txt
- Scripts/developer_scripts/run_testsuite_with_ctest
Add a test to replace an empty number of processors by 1 and move --timeout sooner in the options to prevent an eventual other parsing error.
> Fix ctest testsuite script 

- Cartesian_kernel/TODO
- Cartesian_kernel/include/CGAL/Cartesian/Line_3.h
- Cartesian_kernel/include/CGAL/Cartesian/Ray_3.h
- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
- Cartesian_kernel/include/CGAL/Cartesian/point_constructions_2.h
- Cartesian_kernel/include/CGAL/constructions/kernel_ftC2.h
- Homogeneous_kernel/include/CGAL/Homogeneous/RayH3.h
- Homogeneous_kernel/include/CGAL/Homogeneous/function_objects.h
- Kernel_23/doc/Kernel_23/CGAL/Line_2.h
- Kernel_23/doc/Kernel_23/CGAL/Line_3.h
- Kernel_23/doc/Kernel_23/CGAL/Ray_2.h
- Kernel_23/doc/Kernel_23/CGAL/Ray_3.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/include/CGAL/Line_2.h
- Kernel_23/include/CGAL/Line_3.h
- Kernel_23/include/CGAL/Ray_2.h
- Kernel_23/include/CGAL/Ray_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_line_2.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_line_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_ray_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_ray_new_2.h
There is no real requirement on `i` being an 'int', except for some symmetry with the segment. On the other hand, it restricts heavily what you can do with the function for no reason.
Ideally, segment_23 would also return a point on the segment with `0<=i<=1`, but it would be a strong breaking change (right now it expects an int and applies a %2 before calling source() or target()). There are not enough reasons to break such low level code.
Put as a bug/cleaning fix, but could (should be a small feature ?)
* Issue(s) solved (if any): fix #4113
> Change ray_23 and line_23's point(int) function to point(FT)

- Nef_S2/examples/Nef_S2/nef_s2_construction.cpp
- Nef_S2/include/CGAL/Nef_S2/SM_overlayer.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap.h
Fix a memory corruption due to const refs on temporary objects.
* Affected package(s):Nef_S2
> Nef_S2: Fix memory corruption

- Installation/lib/cmake/CGAL/CGALConfig.cmake
Since PR https://github.com/CGAL/cgal/pull/3900 CGAL is header-only by default. As a side effect, that made all test platforms use `-isystem` instead of `-I` , when supported, to specify the include path for CGAL. And thus all CGAL warnings were disabled.
* Affected package(s): Installation, but all packages might show new warnings
* Issue(s) solved (if any): fix #3900
* License and copyright ownership: GeometryFactory
@maxGimeno: you might see new warnings popping up in all CGAL, once this PR is merged in `integration`. There were just hidden, before.
> Header-only: remove -isystem in the testsuite or dev-mode

- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Detail/Edge_collapse_impl.h
Simple fix making it obvious that the placement must be valid.
My guess is that it was the job of the cost to return `boost::none` is the placement was invalid (but nothing was documented).
> Do not collapse an edge is the placement cannot be computed

- Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_polygonal_impl.cpp
If no solver is available, some parameters are not used, which can generate warnings (introduced by https://github.com/CGAL/cgal/pull/4108).
* Affected package(s): Demo
> Demo: Fix warnings if no solver available

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
The function `approximate_Hausdorff_distance_impl()` has a `PointRange` as parameter but then calls a functor with `std::vector<Point_3>` as parameter, which makes the function unable to handle anything else than a vector of Point_3 (which makes the template useless).
This PR makes the functor us a `PointRange` too.
The range used by `max_distance_to_triangle_mesh()` is now documented as having random access iterators.
> PMP: Fix distance range type

- Point_set_processing_3/include/CGAL/IO/read_ply_points.h
- Point_set_processing_3/include/CGAL/IO/write_ply_points.h
* The documentation of `read_ply_with_properties()` was not compiled because `/*` was used instead of `/**`
* The documentation of `write_ply_with_properties()` was incorrect, referring to a non-existing `point_map` parameter
* Affected package(s): PSP (doc)
> PSP: fix documentation of PLY IO

- Alpha_shapes_3/doc/Alpha_shapes_3/CGAL/Alpha_shape_3.h
- Alpha_shapes_3/doc/Alpha_shapes_3/CGAL/Alpha_shape_cell_base_3.h
- Alpha_shapes_3/doc/Alpha_shapes_3/CGAL/Fixed_alpha_shape_3.h
Rephrase the documentation of a  constructor.
* Affected package(s): Alpha_shapes_3
* Issue(s) solved (if any):  See [stackoverflow](https://stackoverflow.com/questions/57572583/does-fixed-alpha-shape-3-destroy-or-modify-original-triangulation)
> Fixed_alpha_shape_3: Replace destroyed with swapped in documentation

- Polygonal_surface_reconstruction/doc/Polygonal_surface_reconstruction/Polygonal_surface_reconstruction.txt
Some formulas are shown as code due to the fact that the indentation of the start of the formula is 4 or more compared to the paragraph it is part of (handling of code sections has been improved from e.g. 1.8.13 to master).
the formula construct `\f$ .. \f$` should not be used when using e.g. the `equation` environment. With MathJax this works but in standard LaTeX an error is thrown (not yet the focus of CGAL, but might be of interest in the future / newer implementations of MathJax when more compatible).
See: Polygonal_surface_reconstruction/index.html#title2
> Formulas shown as code

- Advancing_front_surface_reconstruction/doc/Advancing_front_surface_reconstruction/Advancing_front_surface_reconstruction.txt
In case we have a single quote in a code span it is better to have the start and end backtics of the code span as double backticks.
Sometimes the constructs lead to warnings or to garbled code. This happens in the newer versions of doxygen where some new heuristics are used to recognize texts line "it's".
See also "Warning in case of usage of a single quote in a code span." (https://github.com/doxygen/doxygen/pull/7209).
The wrong result (see 2nd section the text: However....), as obtained from https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.0-Ic-119/master/Advancing_front_surface_reconstruction/index.html#Chapter_Advancing_Front_Surface_Reconstruction
the correct / updated result:
> Problem with single quote in code span.

- Documentation/doc/biblio/cgal_manual.bib
- adding missing closing curly bracket (twice)
- correcting typo '|' -> '}'
> Incorrect lines in bib file

- Spatial_searching/doc/Spatial_searching/CGAL/Search_traits_adapter.h
- Spatial_searching/include/CGAL/Search_traits_adapter.h
`Search_traits_adapter` requires an lvalue point map because, internally, the `cartesian_const_iterator` is used to iterate on the coordinates of points. In practice, this is a very annoying limitation, as it means one cannot construct a kd tree with points generated on-the-fly (for example).
This PR adds an alternative to the `cartesian_const_iterator` defined by the search traits adapter in the case where the point map is not lvalue (by storing the point in a shared pointer to avoid iterating on a temporary object). If the point map is lvalue, the original behavior is kept.
Now the point map can be only readable and still work with `Search_traits_adapter`.
* Affected package(s): Spatial Searching
> Spatial Searching: Search Traits Adapter without lvalue point map

- CMakeLists.txt
- Installation/CMakeLists.txt
- Mesh_3/examples/Mesh_3/CMakeLists.txt
- Mesh_3/include/CGAL/Mesh_3/Mesh_complex_3_in_triangulation_3_base.h
- Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
- Mesh_3/include/CGAL/make_mesh_3.h
- Periodic_3_mesh_3/package_info/Periodic_3_mesh_3/dependencies
- Periodic_4_hyperbolic_triangulation_2/demo/Periodic_4_hyperbolic_triangulation_2/CMakeLists.txt
In Mesh_3, the initial triangulation after the initialization was assumed with `dimension() == 3`. But, if the input domain is completely coplanar then the initial triangulation can only have `dimension() == 2`. This PR:
- enables the first stage of Mesh_3 to deal with a 2D triangulation,
- and adds 3D far points unconditionally, to ensure that the triangulation is 3D for the next stages.
> Allow Mesh_3 to cope with a 2D initial triangulation

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
There was an issue with keeping a valid incident halfedge (i.e. non-null) after non-manifold vertex duplication. Now, we ensure that the halfedge incident to the initial vertex that we do not duplicate is properly set.
Not done for CGAL 4.13 because the version in 4.13 was really different and it's not worth it.
* Issue(s) solved (if any): #4133
* version for 5.0: #4139
> PMP: Fix improper halfedge incidence state in post non-manifold vertex duplication mesh (4.14)

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h
>  PMP: Fix boundary cycle when non manifold vertices exist in the cycle (4.14)

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_stitching.cpp
Boundary cycle stitching was done by "zipping" the cycle up from all potential starting points (a pair of consecutive & geometrically equal border halfedges). When there are non manifold vertices, this doesn't work because zipping from one side can zip part of another starting pair.
The function is completely rewritten to zip compatible ranges one-by-one instead (theoretically worse complexity, but unnoticeable in practice).
> PMP: Fix boundary cycle when non manifold vertices exist in the cycle (5.0)

- Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp
The affine transform plugin's behavior when creating a new point set item from the transformation was quite bad: all properties were lost in the process (normals, colors, etc.), and by looking at the code, I realized that the point set was copied twice for no reason (the first copy being also never properly deleted, leading to a memory leak).
This PR removes the useless copies + memory leak and does a full copy of the point set to avoid loosing properties.
* Affected package(s): demo
> Demo: Improve affine transform on point sets

- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
Documentation of the functor seems to indicate the projection of the lifted point along `Oz` would be the 2D point, but this is not what this functor is about. Rather, it maps the `xOy` plane and the user-provided plane via an affine transformation (in the CGAL implementation, it maps `Ox` and `Oy` to the vectors given by `plane.base1()` and `plane.base2()`.
> Kernel_23: Fix documentation of functor `ConstructLiftedPoint_3`

- Documentation/doc/Documentation/Installation.txt
Using links to local disks is not a good idea
- giving the impression that a link exists / something can be seem
- will give messages about address not understood / empty pages in the browser
- give problems with other output formats (not an issue yet with CGAL though)
> Using links to local disks

- Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
There was a conflict between maps in the split_polyhedra operations, causing a crash when re-computing the original item. 
This removes the patch_id property_map of the item after creating it to avoid tricking the item into thinking it has an associated color_map when it really has not.
> Polyhedron Demo: Fix Split Polyhedra

- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/CMakeLists.txt
A `include_directories()` instruction disappeared from the CMakeLists.txt of HDT_2 demo. It fixes it.
> Hyperbolic_triangulation_2: Fix demo

- Polyhedron/demo/Polyhedron/Plugins/Classification/Point_set_item_classification.h
Some ranges were sent empty to an algorithm that expects allocated ranges.
* Affected package(s): Demo
* Introduced in CGAL 4.14
> Demo/classif: Fix unresized ranges

- .travis/install.sh
- Classification/include/CGAL/Classification/OpenCV_random_forest_classifier.h
OpenCV includes were done wrong, leading to errors with the latest OpenCV 4.1 version.
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/4214
> Classification: Fix OpenCV includes

- Installation/cmake/modules/FindTBB.cmake
`FindTBB.cmake`: read both `TBBROOT` and `TBB_ROOT`
Fix #4240
* Issue(s) solved (if any): fix #4240
> FindTBB.cmake: read both TBBROOT and TBB_ROOT

- Spatial_searching/include/CGAL/Search_traits_adapter.h
The behavior I introduced in https://github.com/CGAL/cgal/pull/4187 to handle non-lvalue property maps in `Search_traits_adapter` was buggy:
- the operator that is supposed to return the `end()` iterator actually returned `begin()` (I don't understand how I managed to make anything work at that time considering this bug…)
- I forgot to remove one static assertion that made sure the property map was lvalue 
* Affected package(s): Spatial Searching
> Spatial Searching: Fix no lvalue Search_traits_adapter

- Number_types/include/CGAL/Mpzf.h
fixes #4268, tested locally on Windows 10, Visual Studio 2017
> fix Mpfz default constructor causes unreachable code warning in Visual Studio

- CGAL_ImageIO/include/CGAL/read_vtk_image_data.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane.h
When an image has a dimension that is really different than the others (like in 512x512x28) the sphere handles are not aligned with the plane, that makes strange effect. 
This PR fixes that.
> CGAL 3D Demo: Fix DICOM display

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/bbox.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/extrude.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/smooth_mesh.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/smooth_shape.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h
master version of #4269  that adds the missing macro definition to more recent files.
> PMP: Fix doc macro-master

- Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Polyhedron_stitching_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
For now, loading an OFF as a Surface_mesh does not check for the validity of the Polygon Mesh. It means that it is possible to load a data set that is not a 2-manifold in a surface_mesh, which can cause problems when iterating the structure. 
This PR fixes it by adding a check in the load function. If it is not valid, then the set is loaded as a soup, which forces the user to orient it, which will duplicate the non-manifold vertices. 
EDIT: This PR now only adds stats for nm vertices to the scene_surface_mesh_item and modify the stitching plugin to not use a filter graph in the "Detect Boundaries" operation, so that it doesn't use the `is_border(vertex)` function that doesn't work on nm vertices.
> Polyhedron Demo: Fix  stitching plugin 

- Installation/include/CGAL/config.h
Fix macro in Installation/include/CGAL/config.h
* Issue(s) solved (if any): fix #4220
> Remove extra S in macro

- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/MVC_post_processor_3.h
The main change is the choice of default solvers: ARAP now uses Suitesparse (or SparseLU as back-up) instead of BiCGSTAB. This choice is motivated by tests on a bit more data. Cleaned some minor things along the way.
The documentation changed because I updated the default models, but it is not a real change.
* Issue(s) solved (if any): Fixes #4290
> SMP: Various improvements to the ARAP parameterizer

- Nef_3/include/CGAL/normal_vector_newell_3.h
Hello all,
Thank you for you swift reply the previous time @gdamiand  and @lrineau .  This is related to issue #4291 and its solution proposed #4293.  The minimal example provided in #4291 does indeed compile now succefully. However  if I create a Nef polyhedron and convert it to a Polygon  polyhedron there is another namespacing issue. I made this small fix that successfully compiled for all my usecases. This  a minimal example that illustrates the other namespacing issue. 
```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/IO/Polyhedron_iostream.h>
#include <CGAL/Polyhedron_3.h>
#include <CGAL/Nef_polyhedron_3.h>
#include <CGAL/draw_polyhedron.h>
#include <fstream>
typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef …
```
> Namespaced newell function

- Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_insertion_ss_visitor.h
- Surface_sweep_2/include/CGAL/Surface_sweep_2.h
- Surface_sweep_2/include/CGAL/Surface_sweep_2/Default_event_base.h
- Surface_sweep_2/include/CGAL/Surface_sweep_2/No_overlap_subcurve.h
- Surface_sweep_2/include/CGAL/Surface_sweep_2/Surface_sweep_2_impl.h
Arrangement testsuite is not yet happy with it.
Test failing are `test_construction_segments` and `test_construction_polylines` with some input in 
`Arrangement_on_surface_2/test/Arrangement_on_surface_2/data`
```
for i in ./data/test_construction/segments/*; do
echo $i; ./test_construction_segments $i;
done
```
I compile the tests with a CGAL build using:
`cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_examples=ON -DWITH_tests=ON -DWITH_demos=ON -DBUILD_TESTING=ON  ../..` and calling `make test_construction_segments` in the generated directory `test/Arrangement_on_surface_2`
> Derecursification of overlap detectiong on the right of event

- Number_types/include/CGAL/Mpzf.h
1000-999=0001, there are multiple leading 0s to remove.
The issue was reported by @lrineau .
> Properly canonicalize the result of a subtraction in Mpzf

- Apollonius_graph_2/include/CGAL/Parabola_segment_2.h
The current API is not so useful because it is is not adapted to other scales.
This is all undocumented code.
> Apollonius Graph 2: make sampling distance a parameter of the parabola sampling function

- Documentation/doc/CMakeLists.txt
- Documentation/doc/Documentation/Usage.txt
- Documentation/doc/Documentation/windows.txt
- Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
Try to fix that issue: the version number of CGAL in the documentation of CGAL-5.0-beta2 is `5.0`, instead of `5.0-beta2`.
Also fix the download URLs.
> Take the version number from `public_release_name`

- Point_set_3/examples/Point_set_3/point_set_read_ply.cpp
@afabri noticed that `CGAL::Point_set_3` IO methods were not clear (especially the binary behavior), so this PR details a bit more the exampe.
* Affected package(s): Point_set_3 (example only)
> Better IO example in Point_set_3

- Number_types/include/CGAL/Interval_nt.h
- Number_types/test/Number_types/Interval_nt_new.cpp
Handle cases where interval multiplication produces NaN. For SSE, I use `min(x,infinity)` as an equivalent of `isnan(x)?infinity:x`. For non-SSE, I explicitly check for the problematic case.
This seems safer, close to the release, than the other branch where I was checking the exception flag.
* Issue(s) solved (if any): fix #4312
> Wrong interval multiplication with NaN

- Surface_sweep_2/include/CGAL/Surface_sweep_2/Surface_sweep_2_impl.h
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14.2-I-193.shtml  shows a call to nullptr. This PR is only to replace it by NULL.
* Affected package(s):Surface_sweep_2
> Surface_sweep_2 Fix c++11 call

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Preferences.ui
- Polyhedron/demo/Polyhedron/Viewer.cpp
- Polyhedron/demo/Polyhedron/Viewer.h
- Polyhedron/demo/Polyhedron/resources/compatibility_shaders/shader_with_light.frag
- Polyhedron/demo/Polyhedron/resources/shader_with_light.frag
- Three/include/CGAL/Three/Viewer_interface.h
Add a Viewer option to use a specific shader to make more obvious the orientation of the fragments in a shaded program.
To use it, enable/disable it from the `View` menu :
You can edit the colors from the Edit->Preferences menu:
* Issue(s) solved (if any): fix #4320
> Cgal 3D Demo: Two-sided shading

- AABB_tree/include/CGAL/AABB_face_graph_triangle_primitive.h
- AABB_tree/include/CGAL/AABB_halfedge_graph_segment_primitive.h
- Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h
- Polygon_mesh_processing/include/CGAL/Side_of_triangle_mesh.h
Use the mesh's bbox until a request falls inside, only then use the AABB_tree.
* Issue(s) solved (if any): fix #4247
> PMP: Make Side_of_triangle_mesh faster for disjoint meshes

- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Add `= delete`'d generic comparison templates so that we only compare indices of exactly the same type.  Without this the compiler used the conversion to the underlying integer type and compared them.
> Surface_mesh: Disable comparison of mixed index types

- AABB_tree/demo/AABB_tree/Scene.cpp
- AABB_tree/demo/AABB_tree/benchmarks.cpp
- AABB_tree/examples/AABB_tree/AABB_face_graph_triangle_example.cpp
- AABB_tree/examples/AABB_tree/AABB_halfedge_graph_edge_example.cpp
- AABB_tree/examples/AABB_tree/AABB_insertion_example.cpp
- AABB_tree/examples/AABB_tree/AABB_polyhedron_edge_example.cpp
- AABB_tree/examples/AABB_tree/AABB_polyhedron_facet_distance_example.cpp
- AABB_tree/examples/AABB_tree/AABB_segment_3_example.cpp
- AABB_tree/include/CGAL/AABB_tree.h
- AABB_tree/test/AABB_tree/aabb_test_empty_tree.cpp
- AABB_tree/test/AABB_tree/aabb_test_singleton_tree.cpp
- Installation/CHANGES.md
- Mesh_3/include/CGAL/Mesh_3/experimental/Lipschitz_sizing_experimental.h
- Mesh_3/include/CGAL/Mesh_3/experimental/Lipschitz_sizing_polyhedron.h
- Mesh_3/include/CGAL/Mesh_3/polyhedral_to_labeled_function_wrapper.h
- Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/poisson_reconstruction.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/random_perturbation.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/smooth_mesh.h
- Polyhedron/demo/Polyhedron/Plugins/PMP/Distance_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_to_mesh_distance_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_poisson_impl.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Offset_meshing_plugin.cpp
- Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/SDF_calculation.h
Make the `accelerate_distance_queries()` lazy and add a function to disable it.
* Issue(s) solved (if any): fix #4008
> AABB_tree: make accelerate distance queries default

- Triangulation_2/include/CGAL/Triangulation_2/internal/Polyline_constraint_hierarchy_2.h
Small cleanup PR : remove the useless `point_` data member from `Polyline_constraint_hierarchy_2.h`. A *const* reference to the point can be retrieved as `vertex_->point()`.
The `id` public data seems also useless, but it is actually used in `Polyline_simplification_2/include/CGAL/Polyline_simplification_2/simplify.h`.
* Affected package(s): Triangulation_2, Polyline_simplification_2
> Polyline_constraint_hierarchy_2.h: remove the useless point_ data member

- Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h
In some cases K can become really large but doesn't get to infinity and instead gets into a situation where K + epsilon == K and the the while loop never exits. 
Check for the case where K stops changing and exit the loop.  This happens when K + step == K for large values of K.
* Affected package(s):  Advancing front surface reconstruction
* Feature/Small Feature (if any): Small bug fix
* Link to compiled documentation (obligatory for small feature) [link](https://doc.cgal.org/latest/Advancing_front_surface_reconstruction/index.html)
* License and copyright ownership: CGAL
> Prevent infinite loop in Advancing front surface reconstruction. 

- Kernel_23/include/CGAL/internal/Projection_traits_3.h
- Triangulation_2/doc/Triangulation_2/Concepts/ConstrainedTriangulationTraits_2.h
- Triangulation_2/test/Triangulation_2/issue_4405.cpp
The functor must create a 2D bounding box so that snapping can happen correctly.
@lrineau note that this also means a small change in the concept [`ConstrainedTriangulationTraits_2`](https://doc.cgal.org/latest/Triangulation_2/classConstrainedTriangulationTraits__2.html#a8e5e507b08b0cd8b2351303428219ec3).
* Affected package(s):  Triangulation_2 and Kernel_23
* Issue(s) solved (if any): fix #4405
* License and copyright ownership: maintenance for Inria
> Triangulation_2:  Projection_traits::Construct_bbox_2 must return Bbox_2

- Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
- Scripts/scripts/cgal_create_CMakeLists
- Triangulation_3/benchmark/Triangulation_3/CMakeLists.txt
- Triangulation_3/benchmark/Triangulation_3/DT3_benchmark_with_TBB.cpp
Fix #4388.
This fixes the performance loss.
With the macro `CGAL_CONCURRENT_COMPACT_CONTAINER_APPROXIMATE_SIZE` defined to `1`, then the `Concurrent_compact_container` implements a function `approximate_size()`, but at a cost of 3% of performance loss, even if the function is not used (to maintain the atomic values).
* Affected package(s): STL_Extension, Triangulation_[23]
* Issue(s) solved (if any): fix #4388 
**PR #4392 is the same patch, but for the branch of 4.14.x.**
> Fix  DT3 parallel performance loss (issue #4388)

- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_ray_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_segment_3.h
These warnings: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-33/Kernel_23/TestReport_Friedrich_Debian-stable-arm-linux-gnu-32bits.gz
> Kernel_23: Fix "used but uninitialized" warnings

- Generator/doc/Generator/CGAL/point_generators_2.h
- Generator/doc/Generator/CGAL/point_generators_3.h
- Generator/doc/Generator/CGAL/point_generators_d.h
- STL_Extension/doc/STL_Extension/PackageDescription.txt
This PR removes some links that have become obsolete after conversion from `CGAL::cpp11` into `std`, as well as a bunch of useless \sa links. 
* Affected package(s): `Generator`, `STL_Extension`
> Doc: Remove some obsolete links

- Surface_mesh/include/CGAL/Surface_mesh/Properties.h
The swap function swapped the content, but not the variable storing the size of the content.
The fix is not worth backporting, as the function  is not documented publicly and only used in a future PR.
> Surface_mesh: Fix Property_container::swap()

- Intersections_3/include/CGAL/Intersections_3/internal/Triangle_3_Line_3_intersection.h
Fix issue #4357
Compilation error if `<CGAL/Intersections_3/Triangle_3_Triangle_3.h>` is included first.
* Affected package(s): Intersections_3
* Issue(s) solved (if any): fix #4357 
> Fix issue #4357

- CGAL_ImageIO/include/CGAL/ImageIO_impl.h
- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
The ImageIO saving functions cannot save images as `.inr` when Zlib version is lower than 1.2.9,
even if `CGAL_USE_ZLIB` is true.
This PR introduces an error message to help the user understand what's going wrong.
It also fixes a seg fault in the demo, that happened when saving an image as `.inr` had failed.
This PR follows PR #3256
* Affected package(s): ImageIO, Polyhedron demo
> ImageIO and Polyhedron demo - Add error message when `io_image_plugin` can't save

- STL_Extension/include/CGAL/assertions_impl.h
Move error handler/behaviour accessor inlines out of anonymous namespace when compiling in header-only mode.  This allows statics in the handler/behaviour accessor inlines to be globally unique in header-only mode.
* Affected package(s): STL_Extension
* Issue(s) solved (if any): fix #4400
> Fix set_error_handler() header-only-mode issue (#4400)

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
- Polyhedron/demo/Polyhedron/Scene_spheres_item.cpp
- Polyhedron/demo/Polyhedron/Scene_spheres_item.h
- Polyhedron/demo/Polyhedron/resources/compatibility_shaders/shader_c3t3.frag
- Polyhedron/demo/Polyhedron/resources/compatibility_shaders/shader_with_light.frag
- Polyhedron/demo/Polyhedron/resources/shader_c3t3.frag
- Polyhedron/demo/Polyhedron/resources/shader_with_light.frag
Add a mechanism to perform picking on the spheres. Add a parameter to the constructor to disable it.
* Affected package(s):Polyhedron Demo
TODO:
> Polyhedron_demo : Add picking on spheres

- Documentation/doc/resources/1.8.13/cgal_stylesheet.css
- Documentation/doc/resources/1.8.14/cgal_stylesheet.css
- Documentation/doc/resources/1.8.4/cgal_stylesheet.css
Give the class name more space by modifying the CSS.
Before:
After:
> Doxygen: More space for class names

- AABB_tree/doc/AABB_tree/Concepts/AABBTraits.h
- Combinatorial_map/include/CGAL/Combinatorial_map.h
- Combinatorial_map/include/CGAL/Combinatorial_map_insertions.h
- Generalized_map/include/CGAL/Generalized_map.h
- Mesh_2/include/CGAL/Mesh_2/Clusters.h
- Mesh_2/include/CGAL/Mesh_2/Refine_edges.h
- Surface_sweep_2/include/CGAL/No_intersection_surface_sweep_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
The word _splitted_ is ["non-standard or archaic"](https://www.yourdictionary.com/splitted)
> Typos: splitted -> split

- TDS_2/doc/TDS_2/CGAL/Triangulation_data_structure_2.h
- TDS_2/doc/TDS_2/PackageDescription.txt
- TDS_3/doc/TDS_3/CGAL/Triangulation_data_structure_3.h
- TDS_3/doc/TDS_3/PackageDescription.txt
- TDS_3/doc/TDS_3/TriangulationDS_3.txt
- Use `\tparam ` and CamelCase for template parameters.
- Replace  the template parameter `TriangulationDSVertexBase_3`  with `VertexBase` as it makes no sense to write: `TriangulationDSVertexBase_3` must be a model of `TriangulationDSVertexBase_3`.
- Remove non-existing `Vertex_container_strategy,Cell_container_strategy` in the main page of the  Reference manual where we falsely write:  `CGAL::Triangulation_data_structure_3<TriangulationDSVertexBase_3,TriangulationDSCellBase_3,Vertex_container_strategy,Cell_container_strategy,Concurrency_tag>`.
- For the 2D TDS replace template parameters `Vb` and `Fb` with `VertexBase` and `FaceBase`, in order to unify.
- @MaelRL  plans to unify in the periodic versions later.
- Removing `_3` unifies with Alpha shapes_2/3, Mesh_2/3. I didn't check …
> TDS_2/3: Cleanup in the documentation

- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Barycentric_mapping_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Discrete_authalic_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Discrete_conformal_map_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Fixed_border_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/MVC_post_processor_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Mean_value_coordinates_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Orbifold_Tutte_parameterizer_3.h
I added a pragma message in 9eebcfb so that the error is not just something like `CGAL::Default has no type Vector`. However, it was badly done since the pragma message will show up as soon as Eigen is not linked, even if the user has correctly provided a traits class.
Reported in https://github.com/CGAL/cgal/issues/4442#issuecomment-570511774.
> SMP: Fix bad usage of pragma message

- Point_set_3/include/CGAL/Point_set_3.h
The copy constructor was missing, leading to the default being used, which resulted in uninitialized references to the internal properties and made the copied point set unusable (seg fault).
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/4365
> Point_set_3: add missing copy constructor

- BGL/include/CGAL/boost/graph/selection.h
I cannot produce a test for that case because it depends on the iteration order in the model (detected on a model I cannot share)
> Handle "border" case

- Installation/include/CGAL/version.h
- Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
Replace #4358.
* Affected package(s): Installation, Scripts
* Issue(s) solved (if any): fix #4355 
TODO after merge: backport manually to 4.14 and 5.0.
> Workaround for SWIG parser

- Circular_kernel_3/include/CGAL/Circular_kernel_3/internal_functions_on_circle_3.h
- Circular_kernel_3/include/CGAL/Circular_kernel_3/internal_functions_on_circular_arc_3.h
- Nef_3/include/CGAL/Nef_3/SNC_const_decorator.h
- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
- Nef_3/include/CGAL/Nef_3/SNC_simplify.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/Weights.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Visitor.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polygon_mesh.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/experimental/experimental_code.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/fair_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_does_bound_a_volume.cpp
- Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/SDF_calculation.h
- Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/Surface_mesh_segmentation.h
Fixes #4456 + places where `CGAL_warning_msg` was meant to be used (fixes conversion warnings)
> Update warning macro usages

- Mesh_3/include/CGAL/IO/File_binary_mesh_3.h
On Windows, `\n` is turned into `\r\n` when writing to a file. This PR allows the binary I/O of Mesh_3 to deal with a first line that ends with `\r\n` instead of `\n`.
Cc: @janetournois 
* Affected package(s): Mesh_3, Polyhedron demo
> Mesh_3 binary I/O: allow to read a binary file with a CRLF EOL at the end of first line

- Advancing_front_surface_reconstruction/examples/Advancing_front_surface_reconstruction/reconstruction_structured.cpp
- Point_set_processing_3/examples/Point_set_processing_3/structuring_example.cpp
- Point_set_shape_detection_3/examples/Point_set_shape_detection_3/efficient_RANSAC_custom_shape.cpp
- Point_set_shape_detection_3/examples/Point_set_shape_detection_3/efficient_RANSAC_parameters.cpp
- Point_set_shape_detection_3/examples/Point_set_shape_detection_3/efficient_RANSAC_point_access.cpp
- Point_set_shape_detection_3/examples/Point_set_shape_detection_3/plane_regularization.cpp
- Point_set_shape_detection_3/examples/Point_set_shape_detection_3/shape_detection_basic.cpp
- Point_set_shape_detection_3/examples/Point_set_shape_detection_3/shape_detection_with_callback.cpp
- Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/poisson_reconstruction.cpp
- Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/poisson_reconstruction_example.cpp
There is a structure `CGAL::Point_with_normal_3` that is internally used by the bilateral smoothing algorithm (and some tests). Though undocumented, the header was included in several examples (probably as a result of a large copy-paste, as the structure in itself was not used), and the structure was used in 2 examples of Poisson reconstruction.
I cleaned these examples of it as we should not use undocumented classes in public examples.
* Affected package(s): AFSR, PSP, Shape Detection, Poisson
> Remove undocumented CGAL::Point_with_normal_3 from examples

- Surface_mesh/include/CGAL/Surface_mesh/Properties.h
The properties used in Surface Mesh and Point Set 3 are internally a vector of vectors with dynamic type. Most operations on vectors are available (`resize(), `reserve()`, etc.), but I noticed that the capacity was not handled well.
This is what can typically happen:
1. Add some properties
2. Call `resize(s)` and `reserve(c)`
3. -> all properties have size `s` and capacity `c`
4. Add a new property
5. -> this new property is given size `s` and capacity `s` (not `c`), because only `resize()` is called when adding a new property, not `reserve()`
It seems to me that once the user does `reserve()`, then a property added afterwards should also be given the wanted capacity, similarly to how size is handled. This PR mimics the behavior of `resize()/size` with `reserve()/capacity`.
* Affected …
> [Surface Mesh / Point Set] Fix capacity handling in properties

- Apollonius_graph_2/include/CGAL/Parabola_segment_2.h
Might have t(p0) > tp(1) in parabola segmentation.
> AP2: Remove bad precondition

- Convex_hull_2/doc/Convex_hull_2/CGAL/ch_jarvis.h
detected by the bindings
no need to backport IMO
> Fix iterator type required

- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
- Polygon_mesh_processing/doc/Polygon_mesh_processing/examples.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/hole_filling_example_SM.cpp
I found the hole-filling functionality of CGAL to be very powerful, but problematic in practice, since there is no control over the hole size. Many real-world meshes are not closed, or otherwise have huge holes, and the algorithm either hangs on those or can give junk results.
Here I am making a small addition to the hole-filling example by allowing the user to control the diameter and number of edges in a hole to fill.
I added this to the surface mesh example (there are 4 hole-filing examples in the repo), because the Surface_mesh datastructure seems to be more natural when dealing with meshes than the Polyhedron_3 datastructure, and I mention in the doc that examples exist for the other ones as well (but those I did …
> Add control over hole size in the hole-filling example

- Advancing_front_surface_reconstruction/examples/Advancing_front_surface_reconstruction/reconstruction_fct.cpp
The user manual at 
https://doc.cgal.org/latest/Advancing_front_surface_reconstruction/index.html 
goes to great lengths to describe the parameter radius_ratio_bound. Yet, the example right below that is meant to illustrate the code is missing it. One of course visit the reference documentation and dig up what it is and where it should go, but it can make the example more useful to actually use the parameter that is discussed. I am setting it to the value 5 that is used as the default value per the user and reference manuals.
> Add to the user manual example a parameter described in the text

- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/include/CGAL/_test_cls_periodic_3_tds_cell.h
- TDS_2/doc/TDS_2/CGAL/Triangulation_data_structure_2.h
- TDS_2/doc/TDS_2/CGAL/Triangulation_ds_face_base_2.h
- TDS_2/doc/TDS_2/CGAL/Triangulation_ds_vertex_base_2.h
- TDS_2/doc/TDS_2/Concepts/TriangulationDSFaceBase_2.h
- TDS_2/doc/TDS_2/Concepts/TriangulationDSVertexBase_2.h
- TDS_2/doc/TDS_2/Concepts/TriangulationDataStructure_2.h
- TDS_2/doc/TDS_2/PackageDescription.txt
- TDS_2/include/CGAL/Triangulation_ds_face_base_2.h
- TDS_3/doc/TDS_3/CGAL/Triangulation_data_structure_3.h
- TDS_3/doc/TDS_3/CGAL/Triangulation_ds_cell_base_3.h
- TDS_3/doc/TDS_3/CGAL/Triangulation_ds_vertex_base_3.h
- TDS_3/doc/TDS_3/Concepts/TriangulationDSCellBase_3.h
- TDS_3/doc/TDS_3/Concepts/TriangulationDSVertexBase_3.h
- TDS_3/doc/TDS_3/Concepts/TriangulationDataStructure_3.h
- TDS_3/doc/TDS_3/PackageDescription.txt
- TDS_3/test/TDS_3/include/CGAL/_test_cls_tds_cell.h
Some cleaning in TDS_23, only doc, no breaking changes:
* Properly document the refinement of concepts (e.g. `TriangulationDSCell_3` refines `TDS3::Cell`)
* Don't duplicate requirements between concepts that refine each other, instead inherit the concept 
* Fix `Cell_data`'s doc that was all broken. `Cell_data` can't be defined at the level of `TriangulationDSCell_3`, but it must be in the concept TDS3::cell. Its API was also not documented.
* Rebind mechanisms are required by `Triangulation_data_structure_23`, not by the vertex and face/cell concepts of `TDS_23`: it's needed to a fix a circular dependency because there is a TDS class templated by a vertex and a cell, and those are template parametered by the vertex and the cell. But on paper you could define a class `My_TDS_3` that …
> TDS_23: Doc cleaning

- INSTALL.md
The compilation instructions have been very confusing. Its first section suggests that no libraries are needed and no CMakeLists is needed. Also the same block of code is repeated three times.
I removed the redundant and incorrect first section, made it clear early on how to create a CMakeLists.txt, and that linking to external libraries is necessary. 
I did not remove any information.
This is discussed in more detail at https://github.com/CGAL/cgal/issues/4413
> Improve the instructions

- BGL/examples/BGL_LCC/copy_lcc.cpp
- BGL/examples/BGL_polyhedron_3/copy_polyhedron.cpp
- BGL/examples/BGL_surface_mesh/write_inp.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_LCC.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_SM.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_consecutive_bool_op.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_difference_remeshed.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_and_intersection.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_with_attributes.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_polyhedron_union.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_of_patch_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/mesh_smoothing_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/orient_polygon_soup_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/random_perturbation_SM_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/refine_fair_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/shape_smoothing_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/stitch_borders_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/surface_mesh_intersection.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/triangulate_faces_example.cpp
- Polyhedron/examples/Polyhedron/polyhedron_prog_cut_cube.cpp
- Polyhedron/examples/Polyhedron/polyhedron_prog_subdiv.cpp
- Polyhedron/examples/Polyhedron/polyhedron_prog_subdiv_with_boundary.cpp
- Surface_mesh/examples/Surface_mesh/sm_join.cpp
- Surface_mesh/test/Surface_mesh/sm_ply_io.cpp
I know that this is a trivial thing, yet, CGAL is a very high precision numerical software, and surely the default way of saving a mesh should use full precision, especially that some algorithms, eg., mesh smoothing, can have very subtle effects, which won't be recorded if a mesh is saved simply with 8 digits of precision. 
* Affected package(s): Mesh processing
* Issue(s) solved (if any): Fix for mesh not being saved with sufficient precision. 
* License and copyright ownership: Assigned to CGAL under any desired license
> Set the precision when saving a mesh

- Box_intersection_d/doc/Box_intersection_d/CGAL/box_intersection_d.h
- Box_intersection_d/include/CGAL/Box_intersection_d/Box_with_info_d.h
- Box_intersection_d/include/CGAL/Box_intersection_d/segment_tree.h
- Box_intersection_d/include/CGAL/box_intersection_d.h
- Box_intersection_d/test/Box_intersection_d/CMakeLists.txt
- Box_intersection_d/test/Box_intersection_d/test_box_grid.cpp
- Filtered_kernel/include/CGAL/internal/Static_filters/Coplanar_3.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Static_filters.h
- Installation/CHANGES.md
- Kernel_23/include/CGAL/Kernel/interface_macros.h
- Polygon_mesh_processing/examples/Polygon_mesh_processing/CMakeLists.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/self_intersections_example.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/AABB_traversal_traits_with_transformation.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_callbacks.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/repair_extra.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/intersection.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/CMakeLists.txt
- Polygon_mesh_processing/test/Polygon_mesh_processing/self_intersection_surface_mesh_test.cpp
- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- STL_Extension/doc/STL_Extension/CGAL/tags.h
- STL_Extension/doc/STL_Extension/PackageDescription.txt
- STL_Extension/include/CGAL/exceptions.h
- STL_Extension/include/CGAL/tags.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/internal/validity.h
Add parallel versions of `CGAL::PMP::self_intersections()` and `CGAL::PMP::does_self_intersect()`.
TODO:
**Integrate #4364 first.**
* Affected package(s): Polygon_mesh_processing, Box_intersection_d
* Link to small feature: [Parallel_self_intersections](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Parallel_PMP::Self_intersections)  -- **Pre-approval date:** 2020/01/14
> PMP::self_intersections: Add Concurrency

- Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_no_id.cpp
- Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_1.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_2.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_3.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_4.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_5.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/TestMesh.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/include/CGAL/test_util.h
Fix some const correctness issue and make it clear that vertex/halfedge/face ID maps should be initialized priori to constructing the SMSP class.
* Affected package(s): `Surface_mesh_shortest_path`
> SMSP: Fix some const correctness

- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
The Surface Mesh PLY writer used the vertices indices directly, which could lead to ill-formed files in the presence of garbage for example. This PR introduces a reindexing of vertices, similarly to what was already done in the OFF writer of the same class.
PR targets the 5.0 branch as the PLY writer was introduced in 5.0.
* Affected package(s): Surface Mesh
> [Surface Mesh] Fix PLY writing by reindexing vertices

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h
A vertex can become interior after the stitch of the patches kept
while being the endpoint of a polyline to be removed
Completes #3893
Fixes #4522
> Handle the case of interior vertex

- BGL/doc/BGL/CGAL/boost/graph/properties.h
- BGL/include/CGAL/boost/graph/properties.h
- Surface_mesh_simplification/doc/Surface_mesh_simplification/CGAL/Surface_mesh_simplification/edge_collapse.h
The package BGL has documentation split between `doc/CGAL` and `include/CGAL`. The doc for `graph_has_property` was erroneously put into `include/CGAL` and thus it didn't show up in the doc.
External indices property tags are also undocumented despite being used in most `Polyhedron_3` examples, but I don't know if we really want to document them (@sloriot ?); sounds to me like it would be better to phase out `Polyhedron_3` from example.
> BGL: fix doc of graph_has_property

- Documentation/doc/Documentation/Usage.txt
- Documentation/doc/Documentation/windows.txt
This PR fixes the doc about how to install and use CGAL from Homebrew. 
It also indicates some usage of the package [cgal-qt5](https://github.com/Homebrew/homebrew-core), which is not yet accepted on brew.
> Documentation: Update installation instructions

- Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp
- Polyhedron_IO/include/CGAL/IO/OFF_reader.h
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
OFF reader is not robust enough. If the header says CNOFF but there is no color/no normals, it crashes. This PR fixes that
* Issue(s) solved (if any): fix #4499
> Fix OFF reader

- Surface_mesh_segmentation/include/CGAL/mesh_segmentation.h
Fix a citation error, caught by recent builds of Doxygen (since doxygen/doxygen@fa520f975a0893c0d123c1cafec63206bf737794).
* Affected package(s): Surface_mesh_segmentation
* License and copyright ownership: n/a
> Surface_mesh_segmentation: Fix citation (wrong case)

- Cartesian_kernel/include/CGAL/Cartesian/Point_2.h
- Cartesian_kernel/include/CGAL/Cartesian/Point_3.h
- Cartesian_kernel/include/CGAL/Cartesian/Vector_2.h
- Cartesian_kernel/include/CGAL/Cartesian/Vector_3.h
- Filtered_kernel/include/CGAL/Lazy.h
- Kernel_23/include/CGAL/Point_2.h
- Kernel_23/include/CGAL/Point_3.h
- Kernel_23/include/CGAL/Vector_2.h
- Kernel_23/include/CGAL/Vector_3.h
- NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Point_d.h
- Number_types/include/CGAL/GMP/Gmpq_type.h
- Number_types/include/CGAL/Lazy_exact_nt.h
- STL_Extension/include/CGAL/Handle.h
- STL_Extension/include/CGAL/Handle_for.h
The most important part is noexcept on the copy constructors. I assumed that the destructors of the types we put in there don't throw, it would be possible to make it conditionally noexcept, but that doesn't seem worth the trouble.
There is an issue with the precondition in the copy constructor of Handle: noexcept means that it cannot throw an exception it will terminate instead. I think the gains of noexcept far outweigh the possibility to catch such an exception.
* Affected package(s): Number_types, STL_Extension
> Some noexcept, swap, etc to help Handle* types

- Kernel_23/include/CGAL/Kernel/interface_macros.h
`Compare_distance_3` is a generic functor that is comparing
the returned value of Squared_distance_3. If called to
compare the distance of a point to a plane/segment/triangle
a division is used leading to runtime error.
Links in the code to the division:
https://github.com/CGAL/cgal/blob/master/Distance_3/include/CGAL/squared_distance_3_1.h#L140
https://github.com/CGAL/cgal/blob/master/Distance_3/include/CGAL/squared_distance_3_0.h#L202
> Use FT instead of RT

- Linear_cell_complex/include/CGAL/Cell_attribute_with_point.h
- Triangulation_3/include/CGAL/Triangulation_3_to_lcc.h
Bug fix in the function import_from_triangulation_3 that transforms a T3 into a LCC.
When the T3 use weighted points, the function does not compile.
* Affected package(s): T3 ? (or LCC)
> Fix LCC import_from_triangulation_3

- Principal_component_analysis/include/CGAL/PCA_util.h
- Principal_component_analysis/include/CGAL/PCA_util_Eigen.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_segments_2.h
- Principal_component_analysis_LGPL/include/CGAL/centroid.h
This one partially fixes #4527 - first commit is all that is necessary to fix compiling Yade. Second commit is because the changes were extremely similar to the first commit, so I felt they were appropriate.
The `std::abs` though looks very strange there, it's called on an always positive value of `squared_length`, unless you expect complex numbers to be in play?
* Affected package(s): PCA
* License and copyright ownership: license already used by CGAL
> Fix Yade high precision Real compilation

- Mesh_2/include/CGAL/Delaunay_mesh_size_criteria_2.h
- Mesh_2/test/Mesh_2/test_mesh_projection_traits.cpp
Fix the issue "Instantiate new geometry traits" (#4458).
Now, Mesh_2 can be used with `<CGAL/Triangulation_2_projection_traits_3.h>`.
* Affected package(s): Mesh_2
* Issue(s) solved (if any): fix #4458
> Fix issue #4458 (Mesh_2 and Triangulation_2_projection_traits_3)

- Mesh_3/include/CGAL/Labeled_mesh_domain_3.h
Fixes a bug introduced in CGAL-4.13 (PR #2739).
cc: @sloriot 
* Issue(s) solved (if any): fix #2739
> Labeled_mesh_domain_3: Fix the `value_outside` parameter

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
This PR fixes `PMP::isotropic_remeshing()` when it is used with a `face_patch_map` and no constrained edges.
It should consider interface polylines as constrained edges, so that they can be (or not, depending on the protection parameter) resampled but never "broken".
Moreover, it is what is documented.
Until now, the polyline interfaces were simply not taken into account.
> PMP::isotropic_remeshing() - fix remeshing with patch ids

- BGL/include/CGAL/boost/graph/Euler_operations.h
- BGL/test/BGL/test_Euler_operations.cpp
The bug was here because of an assumption that was wrong (border vertex has a border halfedge pointer)
> Fix issue with border vertices in Euler::add_face

- Spatial_searching/examples/Spatial_searching/searching_polyhedron_vertices_with_fuzzy_sphere.cpp
The traits also must be passed to the fuzzy sphere, otherwise it relies on the default VPM being correct and being the VPM passed to the tree.
> Spatial_searching: Pass custom traits to the Fuzzy_sphere object constructor

- .travis/test_package.sh
The point is to avoid getting dependencies differencies in a package if some 3rd party lib is not install for that specific job.
> Travis: Don't compute dependencies if a package is missing.

- Installation/cmake/modules/CGAL_SetupCGALDependencies.cmake
Protect MSVC specific compilation flags with `$<COMPILE_LANGUAGE:CXX>`, to fix issue #4571.
* Issue(s) solved (if any): fix #4571
> Protect MSVC specific compilation flags with $<COMPILE_LANGUAGE:CXX>

- Triangulation_2/include/CGAL/Constrained_Delaunay_triangulation_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
When using face addresses, we do get the same combinatorics and geometry in the result, but it is possible to create different TDS' from one run to another, with a given face not having the same order of points in memory.
* Affected package(s): `Triangulation_2`
> CDT2: Base CDT2's edge sets on geometry to ensure determinism

- Triangulation_2/examples/Triangulation_2/draw_triangulation_2.cpp
- Voronoi_diagram_2/examples/Voronoi_diagram_2/draw_voronoi_diagram_2.cpp
CGAL needs to create a simple viewer for each data structure. The simple viewer example for all available viewers allows to passing arguments in the main function except these two: draw_triangulation_2.cpp and draw_voroni_diagram_2.cpp.
The edit here will allow users to pass arguments in the example.
> update input arguments for draw_triangulation_2.cpp and draw_voroni_diagram_2.cpp

- Apollonius_graph_2/include/CGAL/Apollonius_graph_filtered_traits_2.h
- Apollonius_graph_2/include/CGAL/Apollonius_graph_traits_2.h
- Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_3.h
- Periodic_3_triangulation_3/include/CGAL/internal/Periodic_3_Delaunay_triangulation_remove_traits_3.h
- Periodic_3_triangulation_3/include/CGAL/internal/Periodic_3_regular_triangulation_remove_traits_3.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Filtered_traits_base_2.h
- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Traits_base_2.h
- Triangulation_2/include/CGAL/Triangulation_2.h
- Triangulation_3/include/CGAL/Triangulation_3.h
`Point_3 construct_point(const P&)` (function introduced when dealing with weighted points in https://github.com/CGAL/cgal/pull/2102) should not return a copy when `P := Point_3`.
Gains ~5-10% of runtime.
* Affected package(s): `Triangulation_23`
> Triangulation_23: Grab return of construct_point() by reference when possible

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Use_ssh.cpp
When pushing a file with scp, it seems the permissions were not right. This PR replaces 0707 with 0777
* Affected package(s):Polyhedron Demo
> Polyhedron Demo: Fix ssh scene 

- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
A caption had kept the old named parameter name; it is changed to the new one.
* Issue(s) solved (if any): fix #4585
> Use actual named parameter name in clip figure's caption

- Installation/include/CGAL/Surface_mesh/Surface_mesh_fwd.h
- Surface_mesh/include/CGAL/Surface_mesh.h
Fix forward-declarations of `CGAL::Surface_mesh`.
In the forward-declaration, the template parameters do not matter, but they do if the code is parsed by an IDE (with IntelliSense for example): in that case, the contextual information, while typing, is wrong.
> Fix forward-declarations of CGAL::Surface_mesh

- Polyhedron/demo/Polyhedron/Triangle_container.cpp
Fixes a segfault when trying to read a polygon soup with colored vertices from an OFF file
* Affected package(s):Polyhedron Demo
> Polyhedron Demo: Fix colored soups reading

- Polyline_simplification_2/package_info/Polyline_simplification_2/dependencies
- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
- Triangulation_2/doc/Triangulation_2/Triangulation_2.txt
- Triangulation_2/doc/Triangulation_2/dependencies
- Triangulation_2/doc/Triangulation_2/examples.txt
- Triangulation_2/examples/Triangulation_2/segment_soup_to_polylines.cpp
- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
- Triangulation_2/include/CGAL/Triangulation_2/internal/CTP2_subconstraint_graph.h
The _Constrained Delaunay Triangulation Plus 2_ is a very useful structure to embed a set of polyline and process it (for example, for _Polyline Simplification_ in CGAL). The main difficulty to use it is that the full polylines must be passed (and thus known) to the CDT+ structure: in some cases, users may only have a segment soup as input and thus may not know how this soup decomposes into a set of polylines.
CGAL provides a function [`CGAL::split_graph_into_polylines()`](https://doc.cgal.org/latest/BGL/group__PkgBGLRef.html#ga99ea6bf193f1194db5e523e713c82fb9) that performs such an operation (dividing a set of segment soup into a set of polylines, using vertices of degree `!= 2` as endpoints). One solution to the problem described above is to first preprocess the segment soup into a …
> [Small Feature] CDT+ Split Subconstraint Graph Into Constraints

- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
Fix a typo in [the documentation of `CGAL::Constrained_triangulation_plus_2<Tr>::insert_constraint(..)`][1].
[1]: https://doc.cgal.org/4.14.3/Triangulation_2/classCGAL_1_1Constrained__triangulation__plus__2.html#aaaa7c59fac3307b1e55f9fbd4353d043
> CT_plus_2: fix a pair of typos in the documentation

- Filtered_kernel/include/CGAL/Lazy.h
In Epeck_d, `*approx(iterator)` was copying the approx part of the element instead of returning a reference. With a dynamic dimension, this caused a ton of allocations. The patch saves 12% of running time on the testcase I was looking at.
* Affected package(s): Filtered_kernel, but really NewKernel_d
> Deduce reference return type in approx()

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap.h
* License and copyright ownership: No change
> PMP: Fix copy-paste error leading to wrong dynamic pmap sizes

- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
- Distance_2/include/CGAL/squared_distance_2_1.h
- Distance_2/test/Distance_2/issue_4189.cpp
- Homogeneous_kernel/include/CGAL/Homogeneous/function_objects.h
- Installation/CHANGES.md
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/doc/Kernel_23/Concepts/Kernel.h
- Kernel_23/doc/Kernel_23/PackageDescription.txt
- Kernel_23/include/CGAL/Kernel/global_functions_internal_2.h
- Kernel_23/include/CGAL/Kernel/interface_macros.h
Avoiding subtractions fixes the issues when using `Simple_cartesian<double>`, and to use `orientation()` should make it robuster with `Epick`. 
The same should be done for Ray_2/Segment_2.   
We could introduce a predicate for 4 points that computes all orientation tests and determines at the same time which is the closer endpoint. This would make it yet robuster and it would avoid redundant computations.
I accidentally committed also a slightly faster implementation of  compare_signed_distance_to_line()`.
TODO:
* Affected package(s): Distance_2
* Issue(s) solved (if any): fix #4189
* Small Feature: [CompareSignedDistanceToLine_2](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Kernel::CompareSignedDistanceToLine_2) I pre-approuve. -- Laurent Rineau 10:34, 12 …
> Make 2d segment segment distance more robust for kernel with inexact constructions

- Spatial_searching/include/CGAL/Euclidean_distance.h
`Orthogonal_k_neighbor_search` is broken when dimension is 6 or higher (segfault). The reason is there's an optimization for `dim>=6` that misuses an iterator. 
* Affected package(s): Spatial Searching
* Introduced on master
> Bugfix : Spatial Searching Interruptible Distance

- Property_map/doc/Property_map/Doxyfile.in
- Property_map/doc/Property_map/Property_map.txt
- Property_map/doc/Property_map/examples.txt
- Property_map/examples/Property_map/CMakeLists.txt
- Property_map/examples/Property_map/custom_property_map.cpp
CGAL uses quite extensively property maps. I noticed that we often advise users to write their own property maps to apply CGAL algorithms to their data, but we don't give any indication on how to do it. Of course, because property maps are originated from Boost, indications are technically available on the Boost Manual. But it can't hurt to add more information to our own manual, just to have somewhere where we can orient users when we suggest they should write their own property map.
This (very) small feature simply adds a section with example to the _Property Map_ package.
No API change, just a new example and section in the manual.
(no change)
No need
* [__User manual__](https://cgal.geometryfactory.com/~sgiraudot/Pmap_example/Property_map/index.html#title5)
- Developed and locally …
> [Small Feature] Custom Property Map Example

- Point_set_processing_3/include/CGAL/jet_smooth_point_set.h
I introduced a bug with https://github.com/CGAL/cgal/pull/4552: because points are not longer copied in the KD Tree, altering the point cloud means altering the KD Tree. In the case of the jet smoothing, that means that the projection was computed on a subset of points that could contain already altered points (whereas it should be computed on the original points). In parallel mode, it's even worse because some points could be read and written at the same time, I did not spot this possibility when I wrote it…
Anyway, this PR separates computation of new points from their update and fixes it.
> [Bugfix] PSP Jet Smoothing do not alter points when reading them

- BGL/examples/BGL_polyhedron_3/copy_polyhedron.cpp
- BGL/include/CGAL/boost/graph/Dual.h
- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
- BGL/include/CGAL/boost/graph/copy_face_graph.h
- BGL/test/BGL/graph_concept_Dual.cpp
- BGL/test/BGL/test_Euler_operations.cpp
- HalfedgeDS/include/CGAL/boost/graph/graph_traits_HalfedgeDS_default.h
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Linear_cell_complex/include/CGAL/boost/graph/properties_Linear_cell_complex_for_combinatorial_map.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/extrude.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/triangulate_faces_test.cpp
- Triangulation_2/include/CGAL/boost/graph/internal/properties_2D_triangulation.h
- Triangulation_2/include/CGAL/boost/graph/properties_Triangulation_data_structure_2.h
There should not be an overhead if there are no non-manifold umbrellas (only a extra loop over halfedges).
I also:
- removed the internal mecanism for the hash-map selection and replaced it with a dynamic map.
- fix compilation issues of the dynamic map with `Face_filter_graph`
- fix compilation issues of the dynamic map with LCC. @gdamiand : there is probably a better solution if you want to update the code (instead of using the default I mean, not the trick to avoid the ambiguity)
Possible TODO: update in the corefinement code in face_graph_utils.h the method importing a patch.
Fixes #3206
No backport to 4.14 on purpose.
> Handle non-manifold vertices in copy_face_graph

- Documentation/doc/scripts/html_output_post_processing.py
Doc post-processing: fix Python script that inserted a `<a name="details">` incorrectly.
Fix #3754, see https://github.com/CGAL/cgal/issues/3754#issuecomment-612929760.
* Issue(s) solved (if any): fix #3754
> Doc post-processing: fix Python script that inserted a `<a name="details">` incorrectly

- Classification/include/CGAL/Classification/ETHZ/Random_forest_classifier.h
- Classification/include/CGAL/Classification/ETHZ/internal/random-forest/common-libraries.hpp
- Classification/include/CGAL/Classification/ETHZ/internal/random-forest/forest.hpp
- Classification/include/CGAL/Classification/ETHZ/internal/random-forest/node-gini.hpp
- Classification/include/CGAL/Classification/ETHZ/internal/random-forest/node.hpp
- Classification/include/CGAL/Classification/ETHZ/internal/random-forest/tree.hpp
- Installation/cmake/modules/CGAL_target_use_Boost_IOStreams.cmake
- Installation/cmake/modules/CGAL_target_use_Boost_Serialization.cmake
First step of an on-going work to get rid of dependencies to _Boost IO Streams_ and _Boost Serialization_. Currently, compiling any program using CGAL Classification without these creates a compilation error (or at least a link error). While this is consistent with the documentation that states that these 2 Boost packages are hard dependencies of Classification, in practice only `CGAL::Classification::ETHZ::Random_forest::save_configuration()` and `CGAL::Classification::ETHZ::Random_forest::load_configuration()` depend on them.
This PR adds some CMake definitions and preprocessor conditions to make Classification usable without _Boost IO Streams_ and _Serialization_ (provided, of course, that the IO functions of the Random Forest are not used). This does not change anything from a user …
> Allow Classification package to be used without Boost IO Stream and Serialization

- Documentation/doc/Documentation/Developer_manual/cmakelist_script.txt
- Documentation/doc/Documentation/Developer_manual/create_and_use_a_cmakelist.txt
- Documentation/doc/Documentation/Doxyfile.in
- Documentation/doc/Documentation/Getting_started.txt
- Surface_mesh/examples/Surface_mesh/CMakeLists.txt
Adds page in the developer manual that explains how to create a CMakeLists to use with CGAL.
* Affected package(s):Manual
* Issue(s) solved (if any): fix #3105
* Link to compiled documentation (obligatory for small feature) 
[Getting Started ](https://cgal.geometryfactory.com/~mgimeno/doc/CMakeTuto/Manual/general_intro.html)
[the new page](https://cgal.geometryfactory.com/~mgimeno/doc/CMakeTuto/Manual/devman_create_and_use_a_cmakelist.html)
> Documentation: Add a page that explains how to use cmake

- Documentation/doc/Documentation/Third_party.txt
#4397 introduced the small_vector of boost, but it only appeared in the version 1.58 of boost. 
> Documentation : Update Boost Minimal Version

- Point_set_3/include/CGAL/Point_set_3.h
Using a float kernel is raising warnings on some platforms because points and vectors are initialized from doubles. This fix uses `CGAL::ORIGIN` and `CGAL::NULL_VECTOR` instead.
(I also changed some outdated `boost::tie` lines.)
* Affected package(s): Point Set 3
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/4367
> Point Set: Fix warnings with float kernel

- Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_x_monotone_2.h
In `point_position` in the case when `p` is rational, the following equation is solved:
```
curve.x_polynomial() / norm_x = numerator(p.x) / denominator(p.x) 
<=>
curve.x_polynomial() *  denominator(p.x) = numerator(p.x) * norm_x 
```
to find the point where `X(t) = p.x`, and then compute `Y(t)` and compare it to `p.y` to determine whether `p` lies above or below the curve. The bug was that `norm_x` was not multiplied to `numerator(p.x)`
* Affected package(s):  2D Arrangements
* Issue(s) solved (if any): fix #94
* License and copyright ownership: The license used by CGAL
> Fix bug in point_position in the bezier traits

- STL_Extension/include/CGAL/Compact_container.h
Hash compact_container iterators directly from their underlying
pointers, rather than taking the address of their dereferenced objects.
This avoids situations where a reference may be constructed from a null pointer.
* fixes #4617
* License and copyright ownership: As CGAL sees fit.
----
> Fix reference-to-null-pointer UB

- Triangulation/include/CGAL/Triangulation.h
In small dimension, small_vector won't allocate, and in large dimension, orientations are more costly than a single allocation.
I was tempted to go for the simpler and cheaper
```c++
CGAL_assertion(cur_dim <= 31);
signed char orientations_[32];
```
(or even 15 and 16, I don't think Triangulation is very usable in such large dimensions)
I used `signed char` to store Oriented_side because it seemed wasteful to use 32 bits (on some ABIs) just for { -1, 0, 1 }. I considered changing the definition as `enum Sign : signed char { ... };` in enum.h, but it doesn't look like we store those enums in many places, so leaving it to the implementation to decide on the size seems good.
* Issue(s) solved (if any): fix #4537
> Make orientations_ a local variable, for thread-safety

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
PR https://github.com/CGAL/cgal/pull/4074 introduced a compilation error with MSVC 2015, that was not correctly detected by the testsuite.
MSVC 2015 is wrong: the code is correct because, even if the struct `Image_mesh_items` has two members, the second one has a default member initializer.
Fix only in `master`, because the PR #4074 was merged in `master`, for CGAL-5.1.
* Issue(s) solved (if any): fix #4074
> Demo mesh_3_plugin: fix a compilation error with MSVC 2015

- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_X_trapezoid.h
- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_active_edge.h
- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_active_fictitious_vertex.h
- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_active_trapezoid.h
- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_active_vertex.h
- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_dag.h
- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_dag_node.h
- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_inactive_edge.h
- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_inactive_fictitious_vertex.h
- Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_inactive_vertex.h
- Convex_hull_2/include/CGAL/IO/Tee_for_output_iterator.h
- Filtered_kernel/include/CGAL/Lazy.h
- STL_Extension/include/CGAL/Handle.h
This PR allows to use kernel objects from `CGAL::Epeck` (or `CGAL::Lazy_kernel<...>`) in `CGAL::Compact_container`.
See also discussion on cgal-dev started by @gdamiand, 2020-02-11 15:07 CET.
* Affected package(s): Kernel_23, Filtered_kernel, STL_Extension
> Enable the use of Lazy objects in Compact_container

- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Algebraic_curve_kernel_2.h
Documentation in Curve_analysis_2 suggests that this was intended behavior, but not added.
> Make f square-free in Construct_curve_2 (fix #2224)

- Point_set_processing_3/include/CGAL/Point_set_processing_3/internal/Rich_grid.h
- Point_set_processing_3/include/CGAL/edge_aware_upsample_point_set.h
`CGAL::edge_aware_upsample_point_set()` produced a segfault in some cases. This came from 2 problems combined:
1. The size of a `std::vector` was computed using `int` variables: in the bug case, an overly large vector was created, but the `int` silently overflowed with an incorrect size instead of triggering a `std::bad_alloc`
2. At some point, the `CGAL::Bbox_3` of the point cloud was initialized with all values to 0, which is obviously wrong as it means that the origin is always included, which is not necessarily the case.
What happens is that for point clouds far away from the origin, the size of a `std::vector` computed from the bbox size becomes overly large. Because of the `int` overflow, this is not detected, the vector is constructed with the wrong size, and at some point an …
> Fix initialization of Bbox_3 in edge_aware_upsample_point_set()

- Heat_method_3/include/CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h
- Heat_method_3/include/CGAL/Heat_method_3/internal/Intrinsic_Delaunay_triangulation_3.h
That function was initially called distance(), but when the base distance was removed, its upper level wasn't removed (https://github.com/CGAL/cgal/commit/27bfd0521dd36150e77119588260b1fbb5058a8c).
Initially reported on cgal-discuss by @seb-tourneux (2020-04-24 16:56 CEST)
* Affected package(s): `Heat_method_3`
> Heat Method: remove wrapper around deleted function

- Solver_interface/doc/Solver_interface/Concepts/DiagonalizeTraits.h
- Solver_interface/doc/Solver_interface/Concepts/MixedIntegerProgramTraits.h
- Solver_interface/doc/Solver_interface/Concepts/NormalEquationSparseLinearAlgebraTraits_d.h
- Solver_interface/doc/Solver_interface/Concepts/SparseLinearAlgebraTraits_d.h
- Solver_interface/doc/Solver_interface/Concepts/SparseLinearAlgebraWithFactorTraits_d.h
- Solver_interface/doc/Solver_interface/Concepts/SvdTraits.h
- Solver_interface/doc/Solver_interface/Solver_interface.txt
- Solver_interface/include/CGAL/GLPK_mixed_integer_program_traits.h
- Solver_interface/include/CGAL/Mixed_integer_program_traits.h
- Solver_interface/include/CGAL/SCIP_mixed_integer_program_traits.h
This PR fixes internal doc links in the `Solver_interface` package. It does not affect any code!
In particular, the `MixedIntegerProgramTraits` concept and its associated concepts were not included in the reference manual. The corresponding models had wrong internal references as well. In order to find them, the user had to search for them in the `Class and Concept List` section, which is super inconvenient. This PR also fixes a few small typos. The latter concept has been added for the first time in CGAL 5.0, if I am not mistaken.
* Affected package(s): Solver_interface
* Issue(s) solved (if any): no issues
* Feature/Small Feature (if any): not a feature
* Link to compiled documentation (obligatory for small feature): [docs](https://cgal.geometryfactory.com/~danston/Solver_interface/index …
> Solver_interface: docs bug fix

- STL_Extension/include/CGAL/In_place_list.h
This is a manually-generated change. Ensure that behavior and style are
preserved by carefully inspecting the diff.
> Prevent dynamically bind references to null pointer.

- TDS_2/include/CGAL/Triangulation_ds_face_base_2.h
This is a manually-generated change. Ensure that behavior and style are
preserved by carefully inspecting the diff.
> Prevent dynamic binding of references to null pointers

- Documentation/doc/CMakeLists.txt
- Documentation/doc/resources/1.8.14/BaseDoxyfile.in
When (re)generating the documentation from the sources and not using the, internally patched CGAL, doxygen version one gets messages about:
```
warning: ignoring unsupported tag 'EXTRACT_ALL_NO_DETAILED_IF_EMPTY'
```
By introducing the option `CGAL_EXTRACT_ALL_NO_DETAILED_IF_EMPTY` this doxygen setting can be steered
- option not supplied to cmake, will use as if specified  `-DCGAL_EXTRACT_ALL_NO_DETAILED_IF_EMPTY=ON`
- option supplied to cmake as `-DCGAL_EXTRACT_ALL_NO_DETAILED_IF_EMPTY=ON` will write the line `EXTRACT_ALL_NO_DETAILED_IF_EMPTY = YES` in the doxygen configuration
- option supplied to cmake as `-DCGAL_EXTRACT_ALL_NO_DETAILED_IF_EMPTY=OFF` will write the line `#EXTRACT_ALL_NO_DETAILED_IF_EMPTY = NO` in the doxygen configuration, so just using the default setting of `NO` …
> Introducing CMake option CGAL_EXTRACT_ALL_NO_DETAILED_IF_EMPTY

- Arrangement_on_surface_2/include/CGAL/Arr_geodesic_arc_on_sphere_traits_2.h
- Arrangement_on_surface_2/include/CGAL/Arr_polycurve_basic_traits_2.h
1. Fixed discrepancy between traits and subcurve-traits in the polycurve basic traits.
2. Down casted a variable of type Point_2 (extended direction) to the Kernel::Direction_2 type, so that it can be passed to kernel functors.
* Affected package(s): Arrangement_on_surface_2
> Aos 2 small fixes efif

- AABB_tree/benchmark/AABB_tree/CMakeLists.txt
- AABB_tree/benchmark/AABB_tree/tree_construction.cpp
- AABB_tree/doc/AABB_tree/Concepts/AABBGeomTraits.h
- AABB_tree/doc/AABB_tree/Concepts/AABBPrimitive.h
- AABB_tree/doc/AABB_tree/Concepts/AABBPrimitiveWithSharedData.h
- AABB_tree/doc/AABB_tree/Concepts/AABBRayIntersectionTraits.h
- AABB_tree/doc/AABB_tree/Concepts/AABBTraits.h
- AABB_tree/doc/AABB_tree/aabb_tree.txt
- AABB_tree/include/CGAL/AABB_face_graph_triangle_primitive.h
- AABB_tree/include/CGAL/AABB_halfedge_graph_segment_primitive.h
- AABB_tree/include/CGAL/AABB_primitive.h
- AABB_tree/include/CGAL/AABB_segment_primitive.h
- AABB_tree/include/CGAL/AABB_tree.h
- AABB_tree/include/CGAL/AABB_triangle_primitive.h
- AABB_tree/include/CGAL/internal/AABB_tree/AABB_node.h
- Installation/CHANGES.md
- Polygon_mesh_processing/include/CGAL/Side_of_triangle_mesh.h
- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/Bounded_distance_placement.h
- Surface_mesh_simplification/test/Surface_mesh_simplification/test_edge_collapse_bounded_distance.cpp
Follow up of #4244 + document explicitely what is done.
The PR is on purpose for 5.1 only.
> Make the kd-tree build really lazy and fix thread safety of builds

- Classification/include/CGAL/Classification/Point_set_feature_generator.h
- Classification/include/CGAL/Classification/Point_set_neighborhood.h
- Installation/CHANGES.md
- Spatial_searching/doc/Spatial_searching/CGAL/Kd_tree.h
- Spatial_searching/doc/Spatial_searching/Spatial_searching.txt
- Spatial_searching/doc/Spatial_searching/examples.txt
- Spatial_searching/examples/Spatial_searching/CMakeLists.txt
- Spatial_searching/examples/Spatial_searching/parallel_kdtree.cpp
- Spatial_searching/include/CGAL/Kd_tree.h
- Spatial_searching/include/CGAL/Kd_tree_node.h
Many algorithms (notably in the _Point Set Processing_ package) rely on the _Spatial Searching_ package for fast neighbor queries. Although many PSP algorithms take advantage of trivial parallelisation to speed-up computation by querying the `kd` tree in parallel for each point, a substantial time can be spend _building_ the `kd` tree, especially for very large point clouds. Up to a third of the computation time of algorithms like `CGAL::jet_estimate_normals()` can be spent building the `kd` tree when queries are done in parallel.
This feature adds a parallel variant of the `KD_tree::build()` member function. On a quad-core processor, this parallel algorithm is experimentally 2 to 3 times faster than the sequential one, depending on the point cloud.
A template parameter `ConcurrencyTag` …
> [Small Feature] Parallelize KD Tree build

- Mesh_3/include/CGAL/Compact_mesh_cell_base_3.h
- TDS_3/include/CGAL/Triangulation_ds_cell_base_3.h
Fix UBSAN error: do not bind reference to null pointer, equivalent to #4683.
* Affected package(s): Triangulation_3, Mesh_3
> Fix UBSAN error: do not bind reference to null pointer

- Surface_mesh_topology/examples/Surface_mesh_topology/edgewidth_lcc.cpp
- Surface_mesh_topology/examples/Surface_mesh_topology/shortest_noncontractible_cycle.cpp
- Surface_mesh_topology/examples/Surface_mesh_topology/unsew_edgewidth_repeatedly.cpp
- Surface_mesh_topology/include/CGAL/Face_graph_wrapper.h
- Surface_mesh_topology/include/CGAL/Path_on_surface.h
- Surface_mesh_topology/include/CGAL/Polygonal_schema.h
- Surface_mesh_topology/include/CGAL/Surface_mesh_topology/internal/Shortest_noncontractible_cycle.h
1. computation of cycle lengths, when some halfedges are flip;
2. when we use of face graph wrapper with surface mesh we can not use nullptr.
* Affected package(s): Surface_mesh_topology
> Two bug fixes in Surface mesh topology package

- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/Object.h
- TDS_2/include/CGAL/Triangulation_ds_circulators_2.h
When compiling draw_linear_cell_complex.cpp example with -Wall -Wextra, I have 23 warnings:
parameter ‘n’ set but not used [-Wunused-but-set-parameter]
This probably comes from the fact that the methods use std::nullptr_t and thus the assertion (n == nullptr) is removed since it is always true.
There are probably other places where this problem occurs.
* Affected package(s): STL_Extension and TDS_2
> Remove "unused-but-set-parameter" warnings

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/Weights.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/fair.h
This PR proposes a fix for the issue #4706.
The issue was the imprecise computation of the cotangent weights used to set up an optimization problem. I changed them to the other version that has already been a part of the package.
I based this PR on the `4.14-branch`.
* Issue(s) solved (if any): fix #4706
* Feature/Small Feature (if any): not a feature
> PMP fairing cotangent weights issue fix

- Cartesian_kernel/include/CGAL/Cartesian/Aff_transformation_3.h
- Cartesian_kernel/include/CGAL/Cartesian/Aff_transformation_rep_3.h
- Homogeneous_kernel/include/CGAL/Homogeneous/Aff_transformationH2.h
Fixes an issue with a missing `print` method in `Aff_transformationC3`. Said method was being called in the overloaded output `operator<<(std::ostream&)` function.
It also includes a tiny tweak to the way the transformation is represented, adding a missing space just before subsequent matrix rows beyond the first one.
* Issue(s) solved (if any): fix #4698
> Add missing `Aff_transformationC3::print` and `Aff_transformationH2::operator<<`

- Installation/lib/cmake/CGAL/CGALConfig.cmake
update issue #4736
Issue Description:
I found there is only "CGAL_target_use_TBB.cmake" available when performing vcpkg installation on Windows OS, where I run
PATH_TO_VCPKG> ./vcpkg.exe install cgal[qt]:x64-windows
As provided in CGAL/cgal/Installation/cmake/modules, there should be CGAL_target_use_[Boost_IOStreams/Boost_Serialization/Eigen/GLPK/LASLIB/OpenCV/OpenGR/SCIP/TBB/TensorFlow/pointmatcher] available in vcpkg installation under share/cgal.
So If a compilation using Eigen, CMake will pop up a CMake Error indicating: Unknown CMake command "CGAL_target_use_Eigen".
> add include of other modules

- Installation/CHANGES.md
- Point_set_processing_3/doc/Point_set_processing_3/Point_set_processing_3.txt
- Point_set_processing_3/examples/Point_set_processing_3/remove_outliers_example.cpp
- Point_set_processing_3/include/CGAL/remove_outliers.h
- Point_set_processing_3/test/Point_set_processing_3/remove_outliers_test.cpp
- Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/tutorial_example.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_outliers_removal_plugin.cpp
Many algorithms in _Point Set Processing_ are parallelized, but `CGAL::remove_outliers()` is not: the main reason is that it originally filled a `std::multimap` structure which is hard to parallelize.
This small feature adds a `ConcurrencyTag` template parameter to `CGAL::remove_outliers()` similarly to what already exists in other PSP functions. The algorithm has also changed slightly in the sense that it does not sort points anymore: apart from that, the output partition (which point is outlier, which point is inlier) is unchanged.
A parallel variant of the algorithm is added, and the sequential version is also made faster (around 1.7x faster in my experiments).
In practice:
- replacing the `std::multimap` by a `std::vector` filled first and sorted afterwards makes the algorithm 1.3x …
> [Small Feature] Parallel Outlier Removal

- Mesh_2/include/CGAL/Delaunay_mesh_face_base_2.h
- Mesh_2/test/Mesh_2/reproductibility.cpp
- TDS_2/include/CGAL/Triangulation_data_structure_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
Use a time stamper for the mesh face base class. This makes the construction deterministic.
The Edge_iterator is also deterministic as it compares face handles which means comparing time stamps.
We decided not to document the time stamp mechanism, and not to document that the mesh generator is deterministic.
I tried it with two more test cases: the contour of norway, as well as many segments all intersecting in a single point in order to have more complicated clusters.
I replaced the call of `create_face()` which makes a copy of a face and messes up the time stamper, with a call of `create_face()` which only copies the connectivity. 
This breaks the 2D constrained triangulation testsuite because the bool that  marks a constrained edge gets lost.  In PR #4690 I tried to fix this by …
> Mesh_2: Make it deterministic  V2

- STL_Extension/include/CGAL/Compact_container.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
- Triangulation_2/test/Triangulation_2/issue_4405.cpp
- Triangulation_2/test/Triangulation_2/test_cdt_degenerate_case.cpp
Fix a bug in `<CGAL/Constrained_triangulation_2.h>`
The function parameter was locally shadowed by a local `int i` variable!
Then the edge `(f, i)` in the call `remove_constrained_edge(f, i)` was the wrong one!
The bug was introduced by ecfd82e287378977a325ae34e21087a2075a05cd, ten years ago.
The bug was only triggered on degenerated cases, when two constraints intersect, but the code failed to compute the intersection. Then, if the intersection vertex `vi` was either `vaa` or `vbb` (and not `vcc` or `vdd`), then the edge `(f, i)` was the wrong one._Please use the following template to help us managing pull requests.
> Fix a bug in <CGAL/Constrained_triangulation_2.h>

- Installation/CHANGES.md
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
The function clear() of the Surface_mesh celars the property_maps but does not remove them. 
This PR remove all the maps in clear(), then creates the default maps again.
* Affected package(s):Surface_mesh
> Surface_mesh: fix clear()

- Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/Polygon_2_curve_iterator.h
- Boolean_set_operations_2/include/CGAL/Gps_circle_segment_traits_2.h
- Inscribed_areas/include/CGAL/Largest_empty_iso_rectangle_2.h
- Interpolation/include/CGAL/interpolation_functions.h
- Number_types/include/CGAL/GMP/Gmpq_type.h
- Number_types/include/CGAL/Lazy_exact_nt.h
- Number_types/include/CGAL/MP_Float.h
- Number_types/include/CGAL/Quotient.h
- Polynomial/include/CGAL/Polynomial/Polynomial_type.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
- Union_find/include/CGAL/Union_find.h
The important part is the changes to Quotient and Lazy_exact_nt so the code actually works with -std=c++20 and recent compilers.
The change to Gmpq is an experiment (on a very simple type), I first thought I would handle the others that way, but `operator<=>` is harder to work with than I expected. One idiotic detail is that std::strong_ordering is essentially an int that can be -1, 0, or 1, but they do not provide any direct way to convert to/from such an int. Also, using a non-standard return type for <=> seems less acceptable than for the traditional operators.
I think more work will be needed on this topic, but let's first unbreak things.
* Issue(s) solved (if any): partial #4615
> C++20 fixes

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
- Polyhedron/demo/Polyhedron/Plugins/PMP/Distance_plugin.cpp
Use `parallel_reduce` instead of `parallel_for` in hausdorff computation.
* Issue(s) solved (if any): fix #4750
> PMP: Fix parallel hausdorff

- Documentation/doc/Documentation/Usage.txt
We published doc about a brew formula named `cgal-qt5`, but [it never existed](https://github.com/Homebrew/homebrew-core/pull/50022).
> Documentation : Fix brew doc

- Documentation/doc/resources/1.8.13/menu_version.js
- Documentation/doc/resources/1.8.14/menu_version.js
- Documentation/doc/resources/1.8.4/menu_version.js
This PR adds a warning on top of the documentation of `master`, so that users are not confused.
> Documentation: add warning about doc of master gf

- Nef_3/include/CGAL/Nef_nary_intersection_3.h
- Nef_3/include/CGAL/Nef_nary_union_3.h
Don't segfault on `Nef_nary_union_3::get_union()` and intersection with empty queue due to the call to front() on empty std::list() (= UB). There is already a member `empty`, so I think this check was intended but just forgotten.
* License and copyright ownership: None significant change. Hereby transfer ownership to respective owners.
Also I noticed the similarity between Nef_nary_union_3 and Nef_nary_intersection_3. Probably they can be parametrized using std::plus and std::multiplies from <functional>. Although get_union/get_intersection would ideally be renamed to get_result() for this to make the most sense.
Also Nef_nary_intersection_3 appears to be undocumented.
> Don't segfault on empty Nef_nary_x

- Tetrahedral_remeshing/doc/Tetrahedral_remeshing/PackageDescription.txt
- Tetrahedral_remeshing/doc/Tetrahedral_remeshing/Tetrahedral_remeshing.txt
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/Remeshing_cell_base_3.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/Remeshing_triangulation_3.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/Remeshing_vertex_base_3.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/Sizing_field.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/Uniform_sizing_field.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/FMLS.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/collapse_short_edges.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/compute_c3t3_statistics.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/flip_edges.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/smooth_vertices.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/split_long_edges.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/tetrahedral_remeshing_io.h
- Tetrahedral_remeshing/include/CGAL/tetrahedral_remeshing.h
This PR fixes the list of authors for the whole "Tetrahedral remeshing" package, fixes the package bibtex key, and adds a longer "short description" to the package.
> Tetrahedral Remeshing - fix the list of authors

- BGL/include/CGAL/boost/graph/copy_face_graph.h
If we append one triangle, the check on for non-manifold vertices was done on the whole mesh.
Not relevant for 5.0-branch
> Fix complexity in case of append

- HalfedgeDS/include/CGAL/HalfedgeDS_iterator.h
- Kernel_d/include/CGAL/Kernel_d/Direction_d.h
- Kernel_d/include/CGAL/Kernel_d/Hyperplane_d.h
- Kernel_d/include/CGAL/Kernel_d/Vector_d.h
- Nef_2/include/CGAL/Nef_2/iterator_tools.h
- Nef_2/include/CGAL/Nef_polynomial.h
Fix compilation errors
```
/home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-CXX20-Release/test/Kernel_d/afftrafo-test.cpp:136:31: error: use of overloaded operator '==' is ambiguous (with operand types 'VectorHd<CGAL::VectorHd<__gmp_expr<mpz_t, mpz_t>, CGAL::Linear_algebraHd<__gmp_expr<mpz_t, mpz_t>, std::allocator<__gmp_expr<mpz_t, mpz_t> > > >::RT, CGAL::VectorHd<__gmp_expr<mpz_t, mpz_t>, CGAL::Linear_algebraHd<__gmp_expr<mpz_t, mpz_t>, std::allocator<__gmp_expr<mpz_t, mpz_t> > > >::LA>' (aka 'VectorHd<__gmp_expr<mpz_t, mpz_t>, CGAL::Linear_algebraHd<__gmp_expr<mpz_t, mpz_t>, std::allocator<__gmp_expr<mpz_t, mpz_t> > > >') and 'Vector_d<CGAL::Homogeneous_d<__gmp_expr<mpz_t, mpz_t>, CGAL::Linear_algebraHd<__gmp_expr<mpz_t, mpz_t>, std::allocator<__gmp_expr<mpz_t, mpz_t> > > > …
```
> HalfedgeDS/Kernel_d: Fix ambiguous comparison errors with C++20

- STL_Extension/include/CGAL/Concurrent_compact_container.h
The Concurrent_compact_container uses some undefined behavior to  maintain time_stamps and some other things, including a counter that is not initialized during construction. 
In Vicual Studio 2019, the behavior of the std::atomic constructor changed, breaking this counter, leading to bugs at least in Mesh_3. This PR fixes it.
* Affected package(s):STL_Extension
* Issue(s) solved (if any): fix #4796
> Fix unknown behavior that changed in Visual 2019

- Mesh_3/include/CGAL/Compact_mesh_cell_base_3.h
Continue workaround for MSVC2015. That is a followup to commit 5fbaaa9e4282b3f81551c4fa89e126f5c281055c from PR #4468.
I also chose a better name `is_null` instead of `compare_weighted_circumcenter`.
* Issue(s) solved (if any): fix #4468
> Continue workaround for MSVC2015

- Testsuite/test/run_testsuite_with_cmake
Use `timeout` if available, instead of a system of sleep/kill
The GNU coreutils software [timeout](https://man7.org/linux/man-pages/man1/timeout.1.html) is a perfect replacement for our buggy function `wait_for_process`.
This patch uses it when available. On Linux, brew, Cygwin, it is available in the `coreutils` package.
* Affected package(s): Testsuite, and thus all
> Testsuite rework the timeout of run_testsuite

- STL_Extension/include/CGAL/Object.h
- STL_Extension/include/CGAL/Uncertain.h
- STL_Extension/include/CGAL/exceptions.h
- Triangulation_3/doc/Triangulation_3/CGAL/Regular_triangulation_cell_base_with_weighted_circumcenter_3.h
- Triangulation_3/include/CGAL/Regular_triangulation_cell_base_with_weighted_circumcenter_3.h
**Small change:** replaced all `throw()` with `noexcept`
_throw() is equivalent to noexcept(true) but was deprecated with C++11 and will be removed with C++20._ [source](https://www.modernescpp.com/index.php/c-core-guidelines-the-noexcept-specifier-and-operator)
> replaced throw() with noexcept

- Installation/include/CGAL/config.h
- Spatial_searching/include/CGAL/Orthogonal_incremental_neighbor_search.h
Remove cpp11. And use `#ifdef CGAL_NO_DEPRECATED_CODE` around the backward
compatibility code in `<CGAL/config.h>`.
Version of #4774 for CGAL-5.0.x, restricted to `<CGAL/config.h>` and `Spatial_searching`.
> Remove cpp11::(tuple|get)

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/collapse_short_edges.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
In a C3t3, an edge cannot be added to the complex if it is already there.
* Issue(s) solved (if any): fix #4808
> Tetrahedral remeshing : fix a bug in collapse

- Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
- TDS_3/include/CGAL/Triangulation_data_structure_3.h
- Triangulation_3/include/CGAL/Regular_triangulation_3.h
- Triangulation_3/include/CGAL/Triangulation_3.h
In Mesh_3, the parallel versions of global optimizers, and of sliver perturber, were missing several locks.
This PR
- adds the missing locks,
- introduces `adjacent_vertices_threadsafe()` in TDS_3,
- fixes `incident_edges_threadsafe()` in TDS_3.
* Affected package(s): Mesh_3, TDS_3, Triangulation_3
> Mesh_3 - fix parallel optimisers

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_self_intersections.h
Fix two cases where the algorithm attempted to use a bad patch, which led to rightful assertions/segfault.
* License and copyright ownership: No changes.
> PMP: remove_self_intersections() fixes

- Polyhedron/include/CGAL/boost/graph/graph_traits_Polyhedron_3.h
Extra `const` noticed by @sloriot on one overload of `set_halfedge()`, which creates ambiguities when `HalfedgeDS_vector` is used (and somehow everything is fine otherwise...).
> Remove 'const' markers in Polyhedron-modifying functions

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h
Adds the missing reserve() in the split_cc_impl algorithm.
> PMP: Split_cc missing reserve

- Mesh_3/include/CGAL/Mesh_3/Mesh_complex_3_in_triangulation_3_base.h
- Mesh_3/include/CGAL/Mesh_complex_3_in_triangulation_3.h
- Mesh_3/test/Mesh_3/test_c3t3.cpp
Add move-semantic for c3t3. Required for #4803.
> Add move-semantic for c3t3, and a test

- Point_set_processing_3/include/CGAL/Point_set_processing_3/internal/Neighbor_query.h
- Point_set_processing_3/include/CGAL/cluster_point_set.h
- Point_set_processing_3/include/CGAL/jet_estimate_normals.h
- Point_set_processing_3/include/CGAL/jet_smooth_point_set.h
When performing a neighbor query using a range with fixed radius, problems may occur if no point was found in the radius, which lead me to add a fallback mode using k=3 if no point was found (which seemed like the minimum number of points to fit a plane for example, provided they are not collinear).
While debugging the bindings of CGAL, @maxGimeno encountered a bug which made me realize that these (internal) parameter should vary depending on the algorithm: in that case, the algorithms that use the _Jet Fitting_ package have a precondition on the minimum number of neighbors, so I fixed the bug by using this value as the fallback value.
The neighbor query class did not exist in CGAL 5.0 so this is a fix for master only.
> [PSP] Fix neighbor query fallback

- Installation/CMakeLists.txt
- Scripts/developer_scripts/autotest_cgal
Remove `CGAL_REFERENCE_CACHE_DIR` from our CMake script. That no longer works with header-only, anyway. Now we use the option `-C` of CMake, with a small file loaded from the environment variable
`INIT_FILE`.
For `master`. Not a blocker for 5.1, but it can be integrated if the tests are well.
* Affected package(s): Installation, Scripts
> Remove CGAL_REFERENCE_CACHE_DIR from our CMake scripts

- Mesh_3/examples/Mesh_3/CMakeLists.txt
Fix use of TBB in `examples/Mesh_3/CMakeLists.txt`. I have introduced that bug in 4.14.1 with #4157.
This PR conflicts with `master` because of #4636. PR #4842 the equivalent PR for `master`.
> Mesh_3: fix use of TBB in examples/Mesh_3/CMakeLists.txt (conflicts with master)

- Mesh_3/examples/Mesh_3/CMakeLists.txt
Fix use of TBB in `examples/Mesh_3/CMakeLists.txt`. I have introduced that bug in 4.14.1 with #4157.
This PR is the resolution of conflicts of #4841 with `master`.
> Mesh_3: fix use of TBB in examples/Mesh_3/CMakeLists.txt (for master)

- Scripts/developer_scripts/test_merge_of_branch
`test_merge_of_branch` returns the following issue without the patch
```
Arrangement_on_surface_2/archive/demo/Arr_algebraic_segment_traits_2/xalci/data/various_degree_arrangement: CSV text
Maintenance/package_info/Maintenance/copyright: CSV text
Periodic_4_hyperbolic_triangulation_2/benchmark/Periodic_4_hyperbolic_triangulation_2/bench_results_hyperbolic_vs_euclidean.txt: CSV text
Segment_Delaunay_graph_Linf_2/test/Segment_Delaunay_graph_Linf_2/include/inp_hier.h: CSV text
Segment_Delaunay_graph_Linf_2/test/Segment_Delaunay_graph_Linf_2/include/inp_sdg.h: CSV text
```
> Handle updated version of file

- Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
```
.../CGAL/Mesh_3/C3T3_helpers.h:1249:14: warning: ‘*((void*)& surface +4)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
1249 |       return surface;
|              ^~~~~~~
```
The patch of https://github.com/CGAL/cgal/commit/25eeff801bd102fcbc5050d3556bad4b661e2582 is a trick that avoids to copy an optional that the compiler flagged as "may be empty". 
> Mesh_3: fix a warning

- Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_model_complexty_control.cpp
- Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_user_provided_planes.cpp
- Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_with_region_growing.cpp
- Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_without_input_planes.cpp
After using the code `CGAL::write_off()`, we should flush the buffer immediately so that the result data can be written into a certain file.  If not, we may get an empty file when reading this file next line.
* Affected package(s):  Polygonal_surface_reconstruction
> flush the buffer

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
- Tetrahedral_remeshing/include/CGAL/tetrahedral_remeshing.h
Some flat tetrahedra incident to the boundary, with small dihedral angles can be "peeled" off the internal C3t3. This should include slivers, caps, blades...
This PR introduces a new criterion on areas of internal facets vs surface facets, to select these cells.
> Tet remeshing - fix peeling of slivers

- Advancing_front_surface_reconstruction/examples/Advancing_front_surface_reconstruction/reconstruction_structured.cpp
- Advancing_front_surface_reconstruction/examples/Advancing_front_surface_reconstruction/reconstruction_surface_mesh.cpp
Replace CGAL::cpp11::array with std::array in an Advancing_front example.
* Affected package(s):Advancing_front
> Advancing front: Fix deprecated array

- .travis.yml
- .travis/install.sh
- .travis/template.txt
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
In `compare_subdomains(v1, v2)` compared `std::vector` were not made unique!
It was always returning `DIFFERENT` in presence of different numbers of incident cells for `v0` and `v1`.
Here is a small example of what tetrahedral remeshing can now do. First screenshot is the output of Mesh_3, and then remeshed with a super coarse target edge length.
> Tetrahedral remeshing - fix compare_subdomains()

- Point_set_processing_3/include/CGAL/edge_aware_upsample_point_set.h
In `edge_aware_upsample_point_set()`, there is a precondition `neighbor_radius > 0` while the default value of `neighbor_radius` is `-1`. It is documented that the neighbor radius is set automatically if lower than a factor of the average spacing, so the default value is correct and the precondition is wrong. I removed it.
> Point Set Processing: Remove outdated precondition

- Documentation/doc/Documentation/Developer_manual/Chapter_portability.txt
Seen the discussion with the doxygen pull request https://github.com/doxygen/doxygen/pull/7782 and the subsequent regression, I think it is better to signal the words like `__GNUC__` really as code by using back-ticks in the code.
Representation of `<TT>__GNUC__</TT>` and friends as code and not in a typewriter font.
* Affected package(s): Documentation / Manual
- Before changes (in CGAL):
- After changes in CGAL and before doxygen https://github.com/doxygen/doxygen/pull/7782
> Representation of `__` in typewrite font versus code

- Polygon_mesh_processing/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h
This was broken in https://github.com/CGAL/cgal/pull/4418, but untested so unseen.
An example is modified so the code is tested now.
> PMP: Restore array-based soup to mesh conversion

- Intersections_3/include/CGAL/Intersections_3/internal/Tetrahedron_3_Bounded_3_do_intersect.h
Moving do_intersect(Tetrahedron_3, Bbox_3) below do_intersect(Bbox_3, Tetrahedron_3)
Before do_intersect(Tetrahedron_3, Bbox_3)  called do_intersect(Iso_cuboid_3, Tetrahedron_3), which compiled due to implicit conversion. 
AFAIKT it even worked, up to instances with degenerated Bbox_3/Iso_cuboid_3 executed in debug mode.
> Fix dispatch do_intersect(Tetrahedron_3, Bbox_3)

- Intersections_3/include/CGAL/Intersections_3/internal/Tetrahedron_3_Bounded_3_do_intersect.h
In Line 65 in function do_intersect_tetrahedron_bounded (tr,tet,p,k) we eval  k.has_on_bounded_side_3_object()(tet, p), where tr=lh_tet and tet=rh_tet.
Thus p must be generated from lh_tet or L65 is always true. 
* Affected package(s): Kernel23
> Fix do_intersect for Tetrahedron_3 Tetrahedron_3

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
Before this PR, tetrahedral remeshing was always ending with at least 2 layer of tetrahedra on each patch of surface.
This PR fixes the collapse of edges on surface that have only one endvertex on a polyline feature (one vertex on a surface, one on a polyline feature or a corner).
> Tetrahedral Remeshing - fix the two-layer issue

- Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_cache.h
- Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_point_2.h
- Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_x_monotone_2.h
- CGAL_Core/include/CGAL/CORE/poly/Poly.tcc
For #4817 it was 2 bugs at play:
1. A bug in "pseudoRemainder" in CORE::Polynomial. Can be reproduced using this example
```C++
// This will segfault
#include <CGAL/CORE_BigInt.h>
#include <CGAL/CORE_BigRat.h>
#include <CGAL/CORE_Expr.h>
#include <CGAL/CORE/poly/Poly.h>
int main()
{
using Polynomial = CORE::Polynomial<CORE::BigInt>;
Polynomial poly(
"6292610697842286811635955139693732935009542961033344667036418048-"
"103819018355033897838248246203466232014668376703031553190065602560*x+"
"389958343406394061055782957406169075627518035964428754926430060544*x^2-"
"944918087329222432316982976498054054571260048471617675425124188160*x^3+"
"1211824183851140903767601657701759440881940385941369372497424678912*x^4-"
"699316777172893143445259888350571697548316324857460168144464117760*x^5+" …
```
> Fix bug with self intersecting bezier curves + with CORE::Polynomial

- .travis/build_package.sh
Use -DCMAKE_DISABLE_FIND_PACKAGE_XXX to keep travis to test the classification IO system, as we don't have a working version of boost for that.
* Issue(s) solved (if any): fix #4929
> Disable boost_serialization and iostreams

- Documentation/doc/resources/1.8.13/stylesheet.css
- Documentation/doc/resources/1.8.14/stylesheet.css
- Documentation/doc/resources/1.8.4/stylesheet.css
When having a bit a long citation description, the description runs, in the HTML output on the bibliography page, into 3 or more lines where the 3rd and following lines continue underneath the citation number like:
```
[1]  Eric Berberich, Arno Eigenwillig, Michael Hemmer, Susan Hert, Lutz Kettner, Kurt Mehlhorn, Joachim Reichel, Susanne Schmitt, Elmar Schömer, and Nicola Wolpert. Exacus: Efficient and exact
algorithms for curves and surfaces. In Gerth S. Brodal and Stefano Leonardi, editors, 13th Annual European Symposium on Algorithms (ESA 2005), volume 3669 of Lecture Notes in Computer Science,
pages 155–166, Palma de Mallorca, Spain, October 2005. European Association for Theoretical Computer Science (EATCS), Springer.
```
The example was found  in e.g. …
> Layout on the bibliography page

- .travis/build_package.sh
- .travis/install.sh
As we found out, the boost versions on the mhier PPA is not fitted for CGAL, as they are not built with zlib and bzip2, which is needed for Classification. 
As a reminder, the problem is that the components iostreams and serialization are found, but they are missing all the parts we use, which leads to linking errors. I don't think there is an easy way to detect if those components are built correctly, so I decided to use another ppa for boost, one that does build the two components correcly. 
In #4933, I tried to use CMAKE_DISABLE_FIND_PACKAGE to block iostreams and serialization, but for some reason it doesn't work on linux. (I say on linux because I use it in the cgal-swig-bindings in the windows CI and it is not ignored like it is on travis) .
> Travis: Use another PPA for boost

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Optimization_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Optimization_plugin_cgal_code.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
When performing optimizations on a c3t3, the original domain is lost, and a new one is re-created according to the type of the original meshed item (surface_mesh, segmented image or implicit function), with default values.
In the case of a surface_mesh, the default behavior when claling mesh_3 is to detect features, with a sharp_edges_angle_bound parameter set to 60. This is not the default behaviour in optimizers, so the results clearly differ, as there are no patch ids in the second case. 
To "fix" this behaviour, I added two members (and accessors) to the c3t3_item, to store at the meshing time if we detect the features or not. Using these, those two parameters are retrieved in the optimizer pass, allowing to rebuild the right patch ids in the domain. 
There was also a wrong color set …
> Polyhedron Demo: Fix c3t3 colors after optimization

- Stream_support/include/CGAL/IO/Color.h
The function `CGAL::Color::set_hsv` ignores (most of) the value of `hue`, because for some reason `(hue/60.)` is converted to an integer. I changed two lines in the color conversion code and it now has the expected behaviour.
I also removed one line of documentation because it was inconsistent with the code.
* Affected package(s): IO Streams
> Fix error in HSV/RGB color conversion

- Arrangement_on_surface_2/include/CGAL/Arr_dcel_base.h
- Arrangement_on_surface_2/include/CGAL/Arr_segment_traits_2.h
- Arrangement_on_surface_2/include/CGAL/Arrangement_on_surface_2.h
This PR contains the following enhancements:
- in `Arr_segment_traits_2`, when computing the intersection between 2 segments, an overlap test on the bboxes is done to exit the function early when the segments are obviously distinct
- the bbox computation is now done on the points directly to avoid constructing a segment
- a more efficient specialization of `do_intersect()` is added to take into account the fact the the orientations of the segments are known in this structure
- `boost::fast_pool_allocator` is now used by default instead of `std::allocator` for both `Arrangement_on_surface_2` and `Arr_dcel_base`, as it is a more efficient allocator for list-like structures
Experimentally, all these enhancement lead to a speed-up between 10% and 50% depending on the dataset.
* Affected …
> Arrangement 2: Small Enhancements

- NewKernel_d/include/CGAL/NewKernel_d/Cartesian_LA_functors.h
- NewKernel_d/include/CGAL/NewKernel_d/Types/Weighted_point.h
- NewKernel_d/include/CGAL/NewKernel_d/function_objects_cartesian.h
- NewKernel_d/test/NewKernel_d/Epick_d.cpp
- Number_types/include/CGAL/Interval_nt.h
The linear system used to compute the circumcenter of sets of fewer than d+1 points is not so good, so I am replacing it with one that works better: faster, and numerically more stable (fewer filter failures). I am also adding a special case when the number of points is small.
The formula is not exactly the same as used in Kernel_23, because I wanted it to work independently of the ambient dimension.
And I did the same for the weighted case.
* Affected package(s): NewKernel_d, Number_types
> Rewrite circumcenter computations in NewKernel_d

- Documentation/doc/Documentation/Third_party.txt
- Documentation/doc/resources/1.8.13/menu_version.js
- Documentation/doc/resources/1.8.14/menu_version.js
- Documentation/doc/resources/1.8.4/menu_version.js
- Installation/CHANGES.md
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/corefinement.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Generic_clip_output_builder.h
- Polygon_mesh_processing/include/CGAL/Side_of_triangle_mesh.h
If `tm1` is self-intersecting and you do not need to refine `tm2` (that is self-intersection free) you can now call `corefine(tm1, tm2, params::all_default(), params::do_not_modify(true))` or `corefine(tm2,tm1, params::do_not_modify(true))`.*
Affected package(s): `Polygon_mesh_processing`
Issue(s) solved (if any): -
Feature/Small Feature (if any): [Here](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Corefine_only_one_mesh)  -- **Pre-approved** on 2020/08/04
Link to compiled documentation (obligatory for small feature):
> Add an option to corefine to refine only one mesh

- Polyhedron/demo/Polyhedron/include/id_printing.h
Near border edges, Print_id may cause a crash because we test is_border_edge() instead of is_border() on the selected halfedge. 
This PR fixes that.
* Issue(s) solved (if any): fix #5002
> Demo: Fix id_printing

- Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Alpha_shape_mesher.h
This small PR addresses the bug reported in #4988. 
* Affected package(s): Scale_space_reconstruction_3
* Issue(s) solved (if any): fix #4988 
* Link to compiled documentation (obligatory for small feature): no changes
> Fix leaking memory in Alpha_shape_mesher

- Surface_mesher/examples/Surface_mesher/mesh_an_implicit_function.cpp
- Surface_mesher/include/CGAL/IO/Complex_2_in_triangulation_3_to_medit.h
- Surface_mesher/include/CGAL/IO/Complex_2_in_triangulation_3_to_vtk.h
- Surface_mesher/include/CGAL/IO/facets_in_complex_2_to_triangle_mesh.h
Do not create isolated vertices when creating a `Surface_mesh` from a `C2T3`.
There is nothing to do for the 3D equivalent `facets_in_complex_3_to_triangle_mesh()`.
* Affected package(s): Surface_mesher  
* Issue(s) solved (if any): fix #4970
> Do not create isolated vertices

- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
When doing the following sequence of operations :
- open/create a triangulated surface mesh,
- detect sharp features with the corresponding menu,
- call "Isotropic Remeshing",
detected sharp features were geometrically preserved, but not properly colored in red, nor properly stored for later use, in the demo.
This PR fixes that issue. Now sharp features are still the valid ones after remeshing.
> Polyhedron demo - get the sharp edges back after remeshing

- Shape_detection/include/CGAL/Shape_detection/deprecated/Region_growing.h
Check that the pointer is non null after dynamic cast.
> [Shape Detection] Fix nonnull warning in deprecated Region Growing

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
`CGAL::isotropic remeshing()` is a local process, so it does not need the mesh to be globally valid (e.g. it is allowed to have isolated vertices).
This PR removes the global test when it's not needed, i.e. when the input mesh already was not valid.
When the input mesh is valid, we keep the test in debug mode anyhow.
> PMP isotropic remeshing - test validity during remeshing only if input mesh was valid

- Triangulation/include/CGAL/Triangulation_full_cell.h
- Triangulation/include/CGAL/Triangulation_vertex.h
In 3d there are separate classes for the case with_info. In dD, it is a single class. Since by default there is no data, avoid wasting space using the relevant attribute. I didn't check if this really saves anything, but it shouldn't hurt.
> Use [[no_unique_address]] for info in vertex/cell

- Intersections_3/test/Intersections_3/tetrahedron.cpp
Add tests for do_intersect(tet_3, tet_3) for the following intersections:
- vertex/vertex
- vertex/edge
- vertex/face
- edge/edge
- edge/face
- face/face
- tet_3/tet_3 (full intersection)
and one test for 2 tets not intersecting
* Affected package(s): Intersection_3
* Issue(s) solved (if any): fix #4913
> Intersection_3: Add tests for do_intersect(Tet_3, Tet_3)

- AABB_tree/include/CGAL/AABB_tree.h
- Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
The Scene_aabb_item is not very readable, as it shows every box of the tree of a surface mesh.  
In this PR, I added options in the menu of the item to display only the Nth level of the tree and or only the intersected cells (by the cut plane) : 
- The basic tree of an elephant:
- the new menu: 
- the new tooltip:
- Only one level of the same tree:
-  The same level intersected by the plane:
* Issue(s) solved (if any): fix #4909
> Polyhedron demo: filter the AABB_tree representation

- Envelope_2/doc/Envelope_2/CGAL/envelope_2.h
- Envelope_2/include/CGAL/Envelope_2/Env_divide_and_conquer_2.h
- Envelope_2/include/CGAL/envelope_2.h
Add a couple of free functions (`upper_envelope_x_monotone_2` and `lower_envelope_x_monotone_2`) that accept the arrangement traits object. The already existing functions resulted in the envelope creating its own traits object, and thus losing the cache, making future operations slower. 
So in #4818 instead of
```C++
Diagram_1 diagram;
CGAL::lower_envelope_x_monotone_2(
monotone_curves.begin(), monotone_curves.end(), diagram);
```
We would
```C++
Diagram_1 diagram;
CGAL::lower_envelope_x_monotone_2(
monotone_curves.begin(), monotone_curves.end(), arr.traits(), diagram);
```
where `arr` is the arrangement.
* Affected package(s): Envelope_2
* Issue(s) solved (if any): fix #4818
* License and copyright ownership: The license used by CGAL
> Add envelope free functions that accept traits object

- Installation/CHANGES.md
- Kernel_d/doc/Kernel_d/CGAL/Epeck_d.h
- Kernel_d/doc/Kernel_d/CGAL/Epick_d.h
- NewKernel_d/include/CGAL/NewKernel_d/Kernel_d_interface.h
- NewKernel_d/test/NewKernel_d/Epick_d.cpp
Document 2 existing functors of `Ep[ie]ck_d`. To try and make reviewers happy, I renamed `Power_distance_d` to `Compute_power_product_d` so it matches the names in `Kernel_23`. `Power_center_d` does not seem to have an equivalent in 2D/3D, where you can get the point, but you have to compute the radius/weight separately afterwards (computing both together can save a few operations).
* Affected package(s): `NewKernel_d`
* Feature/Small Feature (if any): https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/More_Weighted_point_d_functors
* Link to compiled documentation (obligatory for small feature) [here](https://geometrica.saclay.inria.fr/team/Marc.Glisse/tmp/cgal-power/Kernel_d/structCGAL_1_1Epick__d.html)
> Document Power_center_d, Power_distance_d (renamed)

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Offset_meshing_plugin.cpp
Swith offset mesh item to wireframe and don't hide source item.
* Issue(s) solved (if any): fix #5017
> Polyhedron Demo: Offset mesher detail

- Number_types/include/CGAL/FPU.h
Windows, FPU.h: replace `_control_fp` by SSE2 intrisics. Fix #2135
* Issue(s) solved (if any): fix #2135 
Cc: @afabri please check if that accelerates on Windows
> Windows, FPU.h: replace `_control_fp` by SSE2 intrisics

- Nef_2/include/CGAL/Nef_2/debug.h
https://github.com/CGAL/cgal/blob/ac3f1101a31fe8553e78ec8ad6b637d70ed95b55/Nef_2/include/CGAL/Nef_2/debug.h#L61-L63
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-I-14/Convex_decomposition_3/TestReport_lrineau_Ubuntu-latest-GCC6.gz
```
/mnt/testsuite/include/CGAL/Nef_2/debug.h:61:28: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
61 | #define CGAL_NEF_TRACEN(t) if((debugthread%CGAL_NEF_DEBUG)==0) \
|                            ^~
/mnt/testsuite/include/CGAL/Nef_2/debug.h:61:28: note: in definition of macro 'CGAL_NEF_TRACEN'
61 | #define CGAL_NEF_TRACEN(t) if((debugthread%CGAL_NEF_DEBUG)==0) \
|                            ^~
/mnt/testsuite/include/CGAL/Nef_2/debug.h:63:2: note: ...this statement, but the latter is misleadingly indented as if it were …
```
> Nef_2: Fix a warning in an debug code

- BGL/doc/BGL/NamedParameters.txt
The example about the NamedParameters mentioned a dot operator but didn't use it. Now it does.
* Affected package(s):BGL
> BGL-Minor_doc_fix

- GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h
- GraphicsView/include/CGAL/Qt/qglviewer_impl.h
- Use O instead of < as it doesn't work on some keyboards (mine, for example)
- Remove the Camera state from the settings saved, as it is supposed to be overridden by the recenter, and sometimes, if the said state is broken enough, the user is unable to visualize anything even after re-launching the app.
> Basic_viewer: Minor fixes

- Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_hierarchy_3.h
- Ridges_3/test/Ridges_3/PolyhedralSurf.h
This PR fixes warnings and errors about things that are deprecated/removed from c++20 and fail in the CGAL testsuite.
* Affected package(s): Periodic_3_Triangulation_3, Ridges_3
> Fix errors and warnings for C++20

- CGAL_Core/include/CGAL/CORE/Gmp_impl.h
CORE::BigRat parses rational numbers in the form `<digit>* <whitespace>* '/' <whitespace>* <digit>*`. This causes eating extra whitespace (including new line characters) when parsing a rational that doesn't have a denominator. Arrangement IO uses the new line character to denote a new piece of information, which causes problems.
The change is to parse rationals in the form `<digit>* '/' <whitespace>* <digit>*` which is in line with what Gmpq IO does.
* Affected package(s): Core
* Issue(s) solved (if any): fix #5003
* License and copyright ownership: The license used by CGAL.
> Fix eating extra whitespace in CORE::BigRat

- Mesh_3/include/CGAL/Mesh_3/Mesh_global_optimizer.h
- Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
- Mesh_3/include/CGAL/Mesh_3/Mesher_level.h
- Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
- Mesh_3/include/CGAL/Mesh_3/Sliver_perturber.h
- Mesh_3/include/CGAL/Mesh_3/Slivers_exuder.h
- Mesh_3/include/CGAL/Mesh_3/Worksharing_data_structures.h
- Mesh_3/include/CGAL/Meshes/Filtered_multimap_container.h
Mesh_3, now uses `tbb:task_group` instead of `tbb::task` (deprecated). Fixes #4872.
* Issue(s) solved (if any): fix #4872
> Mesh_3: now uses tbb:task_group instead of tbb::task (deprecated)

- Polyhedron/demo/Polyhedron/Plugins/Camera_position/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Display/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Display/Display_property.ui
- Polyhedron/demo/Polyhedron/Plugins/Display/Display_property_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/IO/PLY_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/PMP/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
This PR modifies the Display_property_plugin to make it automatically detect any property map of the target Surface-mesh_item that has an arithmetic type as value_type, and display it with a color map or ramp.
Properties of the faces are visible in Flat mode, and properties of the vertices on Gouraud mode.
It works better with PLY IO, as it allows to save/load properties witha surface_mesh.
> 3D Demo: Display Surface_mesh properties

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/shape_predicates.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_repair_degeneracies.cpp
To avoid calling `is_edge_degenerate` twice per edge, the code was removing both faces incident to a degenerate edge immediately. However, one of these faces might have been prevent in the range of faces to fix and thus we would iterate over invalidated iterators.
The code is rewritten to be simpler: just loop faces, check edges, delete when degenerate and move on. This means two calls of `is_edge_degenerate` per edge, but the cost of `is_edge_degenerate` is negligible compared to the rest of the machinery.
Bug reported @oboes in by https://github.com/CGAL/cgal/pull/5001.
Also make degeneracy removal / shape predicates work with EPECK.
* Issue(s) solved (if any): fix #4952
* PR for 5.0.x: #5011
> PMP: Degeneracy removal fixes

- Stream_support/include/CGAL/IO/File_writer_OFF.h
use std::int32_t instead of boost's and add misisng include 
* Affected package(s):Stream_support
> Fix File_write_OFF.h error

- GraphicsView/include/CGAL/Qt/camera_impl.h
- GraphicsView/include/CGAL/Qt/manipulatedCameraFrame_impl.h
- GraphicsView/include/CGAL/Qt/manipulatedFrame_impl.h
- GraphicsView/include/CGAL/Qt/qglviewer_impl.h
- GraphicsView/include/CGAL/Qt/viewer_actions.h
Add a "real zoom" as new feature for the basic viewer and demo. It changes te field of view in order to emulate an optical zoom (instead of simply translating the camera closer as we currently do). It allows to bypass the clipping problem (when the camera is too close of an item and it goes through it).
It is triggered by maintaining the Z key and using the wheel.
> Viewer zoom to rectangle

- Principal_component_analysis/include/CGAL/PCA_util_Eigen.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_rectangles_2.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_segments_2.h
- Principal_component_analysis/test/Principal_component_analysis/test_validity.cpp
When converting the deprecated API to the Eigen version a few years ago, I must have missed a division which lead to an incorrect moment matrix initialization in the case of an input with `Segment_3`, which lead to the bug https://github.com/CGAL/cgal/issues/4993.
This PR fixes it. Now the Eigen version (which is the officially documented one) works well.
This PR also adds a validity test to check that the output of each PCA variant is correct. This revealed other errors which I fixed:
- the moment matrix of `Iso_cuboid_3` was wrong too
- the overload of the variant using `Segment_2` with `CGAL::Dimension_tag<0>` was broken due to 2 inverted arguments
- the overloads of the variants using `Iso_rectangle_2` with `CGAL::Dimension_tag<1>` and `<0` were broken due to a missing argument
All is …
> PCA: Add validity test and fix several bugs

- .github/workflows/build_doc.yml
Only capture between : and the first whitespace if there is one. Also requires `/build:` instead of `build:`
> CI: Better capture for auto doc build

- Filtered_kernel/include/CGAL/internal/Static_filters/Do_intersect_3.h
- Intersections_3/include/CGAL/Intersections_3/internal/intersection_3_1_impl.h
- Intersections_3/test/Intersections_3/test_intersections_3.cpp
- Kernel_23/doc/Kernel_23/CGAL/intersections.h
Fix compilation of `CGAL::do_intersect(Plane_3, Plane_3, Plane_3)`, test it, and document it.
* Affected package(s): Kernel_23, Intersections_3
* Issue(s) solved (if any):  fix #5013 
> Intersections_3 - fix do_intersect(Plane_3, Plane_3, Plane_3)

- Intersections_3/include/CGAL/Intersections_3/internal/intersection_3_1_impl.h
- Intersections_3/test/Intersections_3/test_intersections_3.cpp
- Kernel_23/doc/Kernel_23/CGAL/intersections.h
This PR is a duplicate of PR #5022 (target is CGAL-5.0.4), that fixes the conflicts with `master` (target is CGAL-5.2).
Fix compilation of `CGAL::do_intersect(Plane_3, Plane_3, Plane_3)`, test it, and document it.
* Affected package(s): Kernel_23, Intersections_3
* Issue(s) solved (if any):  fix #5013 
> Intersections_3 - fix do_intersect(Plane_3, Plane_3, Plane_3) in master

- Box_intersection_d/include/CGAL/box_intersection_d.h
- Installation/include/CGAL/config.h
- Polyhedron/demo/Polyhedron/MainWindow.cpp
Defined `CGAL_CXX20` for fixing deprecations in C++ 20
Similar to `CGAL_CXX17`
checked on clang 10.0.1-1
Replaced `[=]` with `[=,this]` in 2 places for C++ 20 in Polyhedron Demo 
checked on g++ 14
* Affected package(s): [Installation](https://github.com/CGAL/cgal/tree/master/Installation), [Polyhedron Demo](https://github.com/CGAL/cgal/blob/master/Polyhedron/demo/Polyhedron/MainWindow.cpp)
* Issue(s) solved (if any): partially fixes #5020
* Feature/Small Feature (if any): Defined CGAL_CXX20, replaced [=] for C++ 20
> Defined CGAL_CXX20 and replaced [=] with [this] for C++ 20

- Kernel_23/include/CGAL/Weighted_point_2.h
- Kernel_23/include/CGAL/Weighted_point_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_aff_transformation_2.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_aff_transformation_3.h
Same fix as in PR https://github.com/CGAL/cgal/pull/5038 by @thomasp85, but rebased onto 4.14 and adding missing tests.
> Kernel_23: Fix affine transformations of weighted points

- .travis/build_package.sh
- Installation/test/Installation/CMakeLists.txt
Use ctest in travis to avoid skipping tests when the architecture of the package differs from the usual (i.e BGL examples).
> Use ctest in travis

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_callbacks.h
fix compile error when using Collect_face_bbox_per_edge_bbox as callback when DO_NOT_HANDLE_COPLANAR_FACES is defined
> fix edge_to_faces key in Collect_face_bbox_per_edge_bbox

- CGAL_ImageIO/include/CGAL/ImageIO/gif_impl.h
Renamed the preprocessor define `DEBUG` to `CGAL_GIF_IMPL_DEBUG`.
Having such a general term defined in a header can cause issues in downstream projects (e.g. if DEBUG is used as member of an enum).
It should not have any impact relevant on other parts of CGAL.
This change impacts following parts (If the changed header was includes before the listed headers).:
https://github.com/CGAL/cgal/blob/f8029d68ba54e4f767e0c0063a06ac640dea3059/Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h#L476
https://github.com/CGAL/cgal/blob/f8029d68ba54e4f767e0c0063a06ac640dea3059/Polytope_distance_d/include/CGAL/width_assertions.h#L22
Probably both impacts are unintended and can be considered as bugs.
* CGAL_ImageIO
* …
> Rename the define DEBUG to CGAL_GIF_IMPL_DEBUG

- CGAL_ImageIO/include/CGAL/ImageIO/analyze_impl.h
Use prefix CGAL_analyze_impl_ to avoid clashing and breaking dirent.h. This header is included by some boost headers.
Also fixes a potential bug when including
"CGAL/Classification/TensorFlow/Neural_network_classifier.h"
after this header
https://github.com/CGAL/cgal/blob/56ab14ec6cd68b63e2e3465042840356b6ad10ab/Classification/include/CGAL/Classification/TensorFlow/Neural_network_classifier.h#L710
* Affected package(s): ImageIO
> Fix define clashes with dirent.h which is included by some boost headers

- Arrangement_on_surface_2/include/CGAL/Arr_dcel_base.h
- Arrangement_on_surface_2/include/CGAL/Arr_overlay_2.h
- Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_overlay_traits_2.h
- Surface_sweep_2/include/CGAL/No_intersection_surface_sweep_2.h
- Surface_sweep_2/include/CGAL/Surface_sweep_2/No_intersection_surface_sweep_2_impl.h
When performing a sweep on a set of connected segments, the connectivity is actually lost (disconnected segments are passed to the sweep) and found again through the event comparator (if two segments have the same endpoint, then this endpoint will only trigger one event), which is an unnecessarily costly operation.
This PR adds a new function `indexed_sweep()` to surface sweep which takes a range of edges with an accessor to get indices and some other information, so that each vertex only trigger one event without the need to use the comparison operator in the multiset of events. A set of indexed events is maintained accordingly during the initialization. The rest of the sweep is the same as without indices.
This indexed sweep if used in `Arr_overlay_2.h` (except when geodesic traits are …
> Surface Sweep + Arr Overlay: Init with indexed edges

- .github/workflows/build_doc.yml
- .github/workflows/delete_doc.yml
Attempts to drastically reduce the size of our github pages repo to avoid build errors.
- Filter doc to push to only keep impacted packages
- Remove directory from repo after PR closure
- Always amend and force push to keep the history size at a strict minimum
> CI auto doc : filter 

- Installation/cmake/modules/CGAL_CreateSingleSourceCGALProgram.cmake
- Installation/cmake/modules/CGAL_add_test.cmake
Fix CTest issues with CGAL_Qt5
Add a target `compilation_of__CGAL_Qt5_moc_and_resources`, and a corresponding CTest test, so that `CGAL_Qt5_moc_and_resources` is always compiled first, when needed. That will fix CTest race-conditions, where `CGAL_Qt5_moc_and_resources` was being compiled by several CTest test at the same time.
This PR is expected to fix the Travis issues that are currently in all branches, since we merged #5078.
> Fix CTest issues with CGAL_Qt5

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_stitching.cpp
Fixes #5113 
Bug introduced by https://github.com/CGAL/cgal/pull/4729, in `master`, for CGAL-5.2-beta.
> Fix return type

- Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_function.h
Mesh_3: Fix `Polyhedral_mesh_domain_with_features_3::add_features`
This PR allows to mesh a polyhedron in a 3D demo, while specifying a polylines item for the sharp features.
> Mesh 3: fix add_features

- Arrangement_on_surface_2/demo/Arrangement_on_surface_2/ArrangementDemoWindow.cpp
- Arrangement_on_surface_2/demo/Arrangement_on_surface_2/ArrangementDemoWindow.h
- Arrangement_on_surface_2/demo/Arrangement_on_surface_2/RationalTypes.h
Includes were wrongly guarded by a CORE macro definition. Tested it locally with GMP without CORE.
* Affected package(s): Arrangement_on_surface_2 Demo
* License and copyright ownership: License used by CGAL
> Fix arrangement demo compiling without CORE

- Poisson_surface_reconstruction_3/include/CGAL/Poisson_reconstruction_function.h
- Poisson_surface_reconstruction_3/test/Poisson_surface_reconstruction_3/CMakeLists.txt
- Poisson_surface_reconstruction_3/test/Poisson_surface_reconstruction_3/poisson_and_parallel_mesh_3.cpp
Poisson reconstruction had a couple of problems when used with parallel `Mesh_3` as some structures were not thread-safe:
- a lazy cache mechanism to store barycentric coordinates of cells
- a global cell hint for fast locate
This PR fixes these 2 problems using atomic variables. It also adds a test for this specific case. This test triggers and assertion fail on master and succeeds on this branch.
* Affected package(s): Poisson Surface Reconstruction
* Issue(s) solved (if any): [cgal-discuss:  make_mesh_3 assertion violation in Triangulation_ds_cell_base_3](http://cgal-discuss.949826.n4.nabble.com/make-mesh-3-assertion-violation-in-Triangulation-ds-cell-base-3-td4665230.html)
> Poisson Reconstruction: Fix thread safety

- Mesh_2/include/CGAL/Mesh_2/Refine_edges_with_clusters.h
Allow instantiation of Refine_edges_with_clusters with Epec
.
Use CGAL::to_double before calling sqrt, this should be a null op with Epic, while avoiding cascaded constructions for Epec. 
> Allow Epec in Refine_edges_with_clusters

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
Edge collapse is allowed for a dart, and is forbidden for an isolated constrained edge.
This PR fixes an inconsistency in the collapsibility check functions (which could cause a crash).
> PMP isotropic remeshing - fix collapsibilty check

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/locate.h
Fix `locate_with_AABB_tree(Point, ..._)` with default point pmap (`CGAL::Default`). The compilation error was:
```
.../Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/locate.h:1697:55: error: no type
named 'value_type' in 'boost::property_traits<CGAL::Default>'
typedef typename boost::property_traits<Point3VPM>::value_type                           Point_3;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
``` 
@MaelRL Probably I should have updated the testsuite, to test that possibility. But the testsuite uses complicated vertex point pmaps. I do not know how to test with `CGAL::Default` as the pmap. Maybe in the example?
* Issue(s) solved (if any): fix #4277 (merged in CGAL-5.0)
> Fix locate_with_AABB_tree(Point, ..._) with default point pmap

- Testsuite/test/parse-ctest-dashboard-xml.py
CTests adds a line per label in the results of the testsuite. 
In this PR, I filter the labels to only keep those with _Tests, _Examples or _Demo. It will prevent `CGAL_cmake_testsuite` and `CGAL_build_system` from being added, when they are really only subtests of the label Installation.
* Affected package(s):Testsuite
> Testsuite: Filter labels in results collection

- Surface_mesh_parameterization/doc/Surface_mesh_parameterization/Doxyfile.in
The image on https://cgal.geometryfactory.com/CGAL/doc/master/Surface_mesh_parameterization/index.html#title11 is not appearing, because the figure was missing from the list of external html files.
> SMP: Fix image not appearing in doc

- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
In the demo, the `isotropic_remeshing_plugin` was invalidating the set of selected edges (resp. vertices, facets) given as input via the selection plugin, because of the modifications made to the mesh associated with the call to `surface_mesh->collect_garbage()`.
This PR uses the visitor in `surface_mesh->collect_garbage(visitor)` to keep selection valid after remeshing and garbage collection.
This PR follows PR #4978 in the case we have a selection_item with selected edges
> Demo isotropic_remeshing_plugin - keep selection valid

- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/Multiset.h
- STL_Extension/test/STL_Extension/CMakeLists.txt
- Surface_sweep_2/include/CGAL/No_intersection_surface_sweep_2.h
- Surface_sweep_2/include/CGAL/Surface_sweep_2/No_intersection_surface_sweep_2_impl.h
- Surface_sweep_2/include/CGAL/Surface_sweep_2/No_overlap_event_base.h
- Surface_sweep_2/package_info/Surface_sweep_2/dependencies
This PR enhances memory allocation in surface sweep by:
- using a `Compact_container` to allocate elements in `Multiset` (by adding an optional non-documented template argument to `Multiset` defaulting to the default non-CC-based `Multiset` version)
- simplifying the allocation and tracking of allocated events, by merging a multiset (used to allocate events) and a vector (used to keep track of the events allocated) in a single `Compact_container` structure that takes care of both while providing a much better memory allocation (taking advantage of memory freed by previous events)
These enhancements lead to a speed-up of 8% to 25% in best cases.
* Affected package(s): STL Extension + Surface Sweep + packages that rely on it (Arrangement, Boolean Operation, etc.)
> Surface Sweep: Enhance memory allocation with Compact Container

- Arrangement_on_surface_2/include/CGAL/Arr_segment_traits_2.h
- Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/Polygon_2_curve_iterator.h
- Boolean_set_operations_2/include/CGAL/Gps_segment_traits_2.h
- Polygon/include/CGAL/Polygon_2.h
- Polygon/include/CGAL/Polygon_2/Polygon_2_edge_iterator.h
This PR is another small enhancement for arrangement:
- we define an alternative undocumented edge iterator for `Polygon_2` which does not construct any `Segment_2` object but just returns pairs of Points (pairs of reference wrappers to be precise). This allows, when constructing a GPS from a Polygon, to avoid the cost of constructing very short-living `Segment_2`
- when constructing an `Arr_segment_2`, we don't construct the `Line_2` support immediately but delay this construction until it's needed. This is especially useful in conjunction with https://github.com/CGAL/cgal/pull/4861 when intersections of segments are discarded early (some segments' line support may not need to be computed at all). To do so, I replace the boolean `is_vert` by an enum (to have a `UNKNOWN` value when the …
> Arrangement: Avoid constructing Segment_2/Line_2 objects when possible

- Convex_hull_3/examples/Convex_hull_3/CMakeLists.txt
- Convex_hull_3/include/CGAL/convexity_check_3.h
Add `const`  in the signature of several functions.  The problem did not show up in the examples and testsuite as the polyhedron passed to these functions is not const.      It shows up in the example put on [gist.gitub.com](https://gist.github.com/afabri/ec9cb00c0c321d91389649b858576782)
This PR should replace PR #5146
> Convex_hull_3: Fix constness

- Heat_method_3/include/CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h
Degenerate faces in the input triangle mesh cause an infinite loop in `loop_over_edges()`.
This PR adds a precondition to avoid degenerate faces in input.
* Affected package(s): Heat_method_3
* Issue(s) solved (if any): fix #5010 
> Heat_method_3 - avoid degenerate faces

- Installation/CHANGES.md
Preview: https://github.com/MaelRL/cgal/blob/CGAL-Prepare_changes.md-5.2-GF/Installation/CHANGES.md
@efifogel CHANGES.md say that `CGAL::Object` is replaced by `boost::variant`, but in [`decompose()`](https://cgal.geometryfactory.com/CGAL/doc/master/Arrangement_on_surface_2/group__PkgArrangementOnSurface2Funcs.html#gae20b2917f6de15db9bf025f83abf8e89), the template parameter still uses `CGAL::Object`; is that normal?
* License and copyright ownership: -
> Prepare CHANGES.md for 5.2

- GraphicsView/src/CGAL_Qt5/CMakeLists.txt
- Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
Check if /demo exists before copying its content.
It might look like I'm only treating a symptom instead of the disease, but this error only seems to occur in the "library" tarball, from which it is impossible to build the demos because they are not included anyway. 
* Affected package(s):Installation, CGAL_Qt5
> Installation: Fix in Qt5 module

- .github/workflows/build_doc.yml
The last pyquery version to be compatible with python 2, which we still use in outr scripts, is 1.4.1. 
* Affected package(s):CI
> Force pyquery 1.4.1

- Shape_detection/include/CGAL/Shape_detection/Region_growing/Region_growing.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/Region_growing_on_polygon_mesh/Least_squares_plane_fit_region.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/Region_growing_on_polygon_mesh/One_ring_neighbor_query.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/internal/utils.h
At several places, there are tests for positiveness of  `std::size_t`s. I removed them in this PR to silence related warnings.
* Affected package(s):Shape_detection
> Shape_detection: Fix warnings.

- Nef_S2/include/CGAL/Nef_S2/SM_overlayer.h
Fix CWE-457: Use of Uninitialized Variable in SM_overlayer.h
In the function `complete_face_support`, after a number of itterations of ` for (SVertex_iterator v = v_start; v != v_end; ++v) `, `v == v_start` can be false, `e_below != SHalfedge_handle()` can be false, and `!is_isolated(v)` can be false meaning `m_buffer` is uninitalised.
`m_buffer` is then dereferenced in the line:
https://github.com/CGAL/cgal/blob/98fafe4ef186037a8c63c04d041da18f34bbe0b3/Nef_S2/include/CGAL/Nef_S2/SM_overlayer.h#L2151 
leading to undefined behaviour.
* Affected package(s): pkg::Nef_S2
* Issue(s) solved (if any): security/bugfix
> Fix use of uninitialized variable in SM_overlayer.h

- Nef_3/include/CGAL/Nef_3/Vertex.h
In the following code `sncp_` is checked for a null pointer, implying that it can be null, however later on the code calls `sncp()` which dereferences `sncp_` without checking for null.
https://github.com/CGAL/cgal/blob/077937383555a61e5b23460fc21cf75f3f005018/Nef_3/include/CGAL/Nef_3/Vertex.h#L337-L346
Simply adding a check for `valid` to the if ensures no fault in this scenario.
* Feature/Small Feature (if any): bugfix
> Fix dereference after null check in Nef_3/Vertex.h

- Barycentric_coordinates_2/include/CGAL/Barycentric_coordinates_2/Segment_coordinates_2.h
It is better to define the anchor in the detailed section of a method as when it is in the brief description it will be shown in the overview of the functions (top of the page) and in the detailed description.
This is due to the `REPEAT_BRIE=YES` setting.
See pages: Barycentric_coordinates_2/classCGAL_1_1Barycentric__coordinates_1_1Segment__coordinates__2.html and Barycentric_coordinates_2/index.html
> Double defined ID seg_coord_global

- Shape_detection/doc/Shape_detection/Concepts/EfficientRANSACTraits.h
I get a double defined ID (when running xmllint on the output) regarding the Vector_3 typedef.
In my opinion the second definition should be Vector_2 and not Vector_3.
> Typo in list of documentation typedefs

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h
A missing `\cgalParamEnd` results in incorrect HTML code (i.e. `</div>` is missing, but which is still shown correctly)
> Missing \cgalParamEnd

- Documentation/doc/resources/1.8.20/BaseDoxyfile.in
Due to some subtle interactions between used doxygen commands and the defined `\cgalAdvancedEnd` incorrect HTML code is generated.
This was shown by `xmllint` (and some options) as
```
parser error : Opening and ending tag mismatch: div line</td></tr>
```
With the `\noop` "trick" this can here be overcome.
The presented output though looked OK.
Problems were found for the packages:
- Periodic_2_triangulation_2
- Point_set_3
- TDS_3
- Triangulation
- Triangulation_2
> Incorrect HTML code in relation with \cgalAdvancedEnd

- Spatial_searching/doc/Spatial_searching/Concepts/FuzzyQueryItem.h
The type `D` was not a real requirement as none of the models provided by CGAL actually provided this typedef, but it's in the concept to explicit the dimension requirements between the KD-tree and the object.
Renamed to `Dimension` to match the actual code.
* Issue(s) solved (if any): fix #5178
> Rename 'D' to 'Dimension'

- Number_types/include/CGAL/Mpzf.h
In the following code the `if mini <= cache_size` statement, where cache_size is defined as 8 the only way it can reach the code after the If body, is when mini is > 8, this means that the later check `if(mini < 2)` is always false.
https://github.com/CGAL/cgal/blob/97123fc3c725d2d9d489d7c70d88f3b1af5c572d/Number_types/include/CGAL/Mpzf.h#L272-L285
This commit just adds an  `#ifndef CGAL_MPZF_USE_CACHE` around the second if, since its only relevant when not using the cache. This wards off the error in static code analysis.
* Feature/Small Feature (if any): small/bugfix
> Fix dead code warning in Mpzf.h

- Scripts/developer_scripts/test_merge_of_branch
Workaround issues with some version of awk 
(not sure where the issue comes from)
`xargs` was complaining of a line being too long (filenames were not separated)
> Update merge test script to workaround

- Documentation/doc/resources/1.8.13/footer.html
- Documentation/doc/resources/1.8.14/footer.html
- Documentation/doc/resources/1.8.20/footer.html
- Documentation/doc/resources/1.8.4/footer.html
To prevent extra redirects and a secure connection it is better to use `https` instead of `http` here.
> Documentation of doxygen is at https server

- Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
- Mesh_3/include/CGAL/Mesh_3/Lloyd_move.h
- Mesh_3/include/CGAL/Mesh_triangulation_3.h
- Periodic_3_mesh_3/include/CGAL/Periodic_3_mesh_triangulation_3.h
When global optimizers (ODT or Lloyd) of Mesh_3 compute moves for surface vertices (`v` has dimension 2), the move is computed as follows :
- compute the 3D move of `v`, taking its incident inside cells into account,
- project the resulting point to the surface to which `v` belongs. 
The projection uses the normal to a plane estimated by PCA, using as input the **surface Delaunay balls centers** of the surface facets incident to `v`.
If the projection is not precise enough, it can happen that the projected point is moved _inside_ a protecting ball, though it should not.
It turns out that using a plane estimated by PCA, using as input the **facets** incident to `v` themselves (triangles) is more accurate, provide a better projection vector, and avoid projection inside a protecting ball. …
> Mesh_3 global optimizers - improve projection to surface

- Mesh_3/include/CGAL/Mesh_3/Mesh_surface_cell_base_3.h
- Mesh_3/test/Mesh_3/CMakeLists.txt
- Mesh_3/test/Mesh_3/test_mesh_cell_base_3.cpp
- Tetrahedral_remeshing/examples/Tetrahedral_remeshing/CMakeLists.txt
- Tetrahedral_remeshing/examples/Tetrahedral_remeshing/mesh_and_remesh_polyhedral_domain_with_features.cpp
Fix `std::atomic::compare_and_swap()` that doesn't wxist into `compare_exchange_weak()`
* Affected package(s):Tetrahedral_remeshing, Mesh_3
* Issue(s) solved (if any): fix #5216
> Mesh_3: Fix std::atomic wrong function 

- AABB_tree/include/CGAL/AABB_face_graph_triangle_primitive.h
- AABB_tree/include/CGAL/AABB_halfedge_graph_segment_primitive.h
This is a residual of the usage of `CGAL::Default` in the class templates.
Fix it by also documenting constructors in a `#ifdef DOXYGEN_RUNNING` block, like the types.
* Affected package(s): `AABB_tree`
* Issue(s) solved (if any): fix #4907
> AABB: Fix extra underscore in the documentation of the VPM template parameter

- Optimal_bounding_box/doc/Optimal_bounding_box/PackageDescription.txt
- Shape_detection/doc/Shape_detection/PackageDescription.txt
The texts in the ALIASES are taken literally and therefore should be (in this case) no space after the comma as this results in a space ion the resulting link and thus a file not found.
> Superfluous space in link

- Shape_detection/include/CGAL/Shape_detection/Efficient_RANSAC/Efficient_RANSAC.h
When using `min_points` greater than the total number of points, RANSAC was silently recomputing `min_points=0.01*nb_points`, because it wrongly assumed the automatic detection was required. This PR fixes that.
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/5250
> [RANSAC] Fix detection of automatic parameter selection

- Surface_mesh/test/Surface_mesh/sm_remove.cpp
Assertions sometimes appear in the test `sm_remove` . We concluded that sometimes, memory is reused and assertions  that test adresses are different fail. So I removed those assertions.
* Affected package(s):Surface_mesh
> Surface_mesh: Fix sm_remove test

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/split_long_edges.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
During the splitting edges step, some vertices could get a wrong value for their `dimension` (the smallest dimension of the geometric components they belong to), because an edge can have its 2 end vertices on some surface patches/feature polylines, and still be in the interior of the domain.
* Issue(s) solved (if any): fix #5235 
> Tetrahedral remeshing - fix edge split step

- Jet_fitting_3/examples/Jet_fitting_3/PolyhedralSurf.h
- Ridges_3/examples/Ridges_3/PolyhedralSurf.h
- STL_Extension/test/STL_Extension/test_Concurrent_compact_container.cpp
Fix warnings `[-Wnon-c-typedef-for-linkage]`, emitted by clang. Example of such a warning:
```
.../test/Jet_fitting_3_Examples/PolyhedralSurf.h:148:19: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct {
^
FGeomTraits
.../test/Jet_fitting_3_Examples/PolyhedralSurf.h:149:5: note: type is not C-compatible due to this member declaration
public:
^~~~~~~
.../test/Jet_fitting_3_Examples/PolyhedralSurf.h:151:7: note: type is given name FGeomTraits for linkage purposes by this typedef declaration
} FGeomTraits;
^
```
from https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1.1-I-252/Jet_fitting_3_Examples/TestReport_lrineau_ArchLinux-clang-CXX17-Release.gz …
> Fix warnings [-Wnon-c-typedef-for-linkage] In Ridges and Jet_fitting

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_repair_degeneracies.cpp
`remove_degenerate_edges()` iteratively calls `degenerate_edges(edge_range)`, but degenerate edges within `edge_range` will (should) disappear, resulting in a call over an invalid range.
* Issue(s) solved (if any): fix #5043 
> Fix multiples calls to degenerate_edges() with an invalid input range

- Shape_detection/include/CGAL/Shape_detection/Efficient_RANSAC/Shape_base.h
The validity test I recently added revealed another bug on 32 bits platforms (see [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-I-61/Shape_detection/TestReport_lrineau_Fedora-32-Release.gz) for example) where, in some cases, no shapes are detected at all.
It was tricky but I finally figured out the reason: at some point, there is a multiplication of `std::ptrdiff_t` numbers that might lead to very large number and thus overflow in 32 bits (leading to computing the square root of a negative number, leading to NaN, etc.). In practise, they are multiplied to create double, so I fixed the bug by converting them _before_ multiplying them.
> [RANSAC] Fix ptrdiff overflow

- Random_numbers/include/CGAL/Random.h
`Random_print_seed()` was fixed in 4.9 but `get_random_seed()` was not updated.
* Affected package(s):Random_numbers
> Random_numbers : re-activate the seed printing in cgal_only

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
`is_corner(v)` should count both incoming and outgoing halfedges around `v`, because the `Halfedge_status` is not symmetric.
This PR fixes (at least) the case where `v` is part of the border of a facet selection, and an end-vertex of a constrained edge. One incident edge was being collapsed in the wrong direction because the corner-status of `v` was wrong.
@xiaoXiaoCam @lrineau this patch should fix the issue you met
> PMP::isotropic_remeshing - fix is_corner(v)

- Circulator/doc/Circulator/CGAL/circulator.h
Fix typo `functiona` -> `function`
* Affected package(s): Handles and circulators
* Issue(s) solved (if any): documentation bugfix 
> Fix typo in doc circulator.h

- Triangulation/include/CGAL/Delaunay_triangulation.h
Use a small_vector in Delaunay_triangulation. It is only used locally in a function, and its size is at most the dimension + 2.
Making the vector thread_local would work as well, but we already had a small_vector in Triangulation.h.
This saves about 7% on Delaunay for some specific point sets.
> Use a small_vector in Delaunay_triangulation

- Combinatorial_map/include/CGAL/Cell_attribute.h
- Combinatorial_map/include/CGAL/Combinatorial_map_fwd.h
- Combinatorial_map/include/CGAL/Combinatorial_map_storages.h
- Combinatorial_map/include/CGAL/Dart.h
- Combinatorial_map/include/CGAL/internal/Combinatorial_map_utility.h
- Generalized_map/include/CGAL/Generalized_map_fwd.h
- Generalized_map/include/CGAL/Generalized_map_storages.h
- Linear_cell_complex/include/CGAL/CMap_linear_cell_complex_storages.h
- Linear_cell_complex/include/CGAL/GMap_linear_cell_complex_storages.h
- Linear_cell_complex/include/CGAL/Linear_cell_complex_fwd.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
Add a tag to the storage classes of CMap, GMap and LCC, allowing to choose to use either Compact_container (default) or Concurrent_compact_container as underlying container.
These classes are undocumented, and by default Compact_container is used; thus there is no change in documented API, nor in user code.
Also add index method in Concurrent_compact_container: this method exists only in Compact_container.
* Affected package(s): CMap, GMap, LCC
> Allow to use compact container or concurrent compact container for CMap, GMap and LCC

- Number_types/include/CGAL/boost_mp.h
In #3406, the plan was
> * disable boost.multiprecision for MSVC for CGAL-4.14,
> * and reenable it for 4.15, after 1.70 has been released.
But apart from a reminder in #4495 it was forgotten.
This branch is completely untested, the whole point is for the testsuite to run on it (I checked and there is at least one platform with msvc and a recent enough boost).
> Enable Boost.Multiprecision with MSVC and recent boost

- Number_types/include/CGAL/GMP/Gmpz_type.h
Fix warning about uninitialized member (mpZ) in Gmpz_type.h
> Fix uninitialized member in Gmpz_type.h

- Periodic_3_mesh_3/examples/Periodic_3_mesh_3/mesh_implicit_shape.cpp
With the previous facet size criterion, the restricted Delauany has an
unfortunate choice of restricted facets, making it look like an unwanted hole.
See also this comment: https://github.com/CGAL/cgal/issues/5046#issuecomment-739922611
* Affected package(s): `P3M3`
* Issue(s) solved (if any): fix #5046
> Modify facet size criterion to avoid unfortunate dent in an example

- Number_types/include/CGAL/Interval_nt.h
Add a SSE2 version of CGAL::square for Interval_nt. This gains a factor larger than 3 compared to the scalar code, and reduces the time to build a Delaunay_triangulation of points on a grid by more than 10%. Just replacing square(x) with x*x was enough to get most of the gain, but this version seems a bit faster.
> SSE2 version of square for intervals

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/collapse_short_edges.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/smooth_vertices.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/split_long_edges.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
The use of `cell_selector` in `CGAL::tetrahedral_isotropic_remeshing()`, that allows to remesh only a (sub)set of selected cells of the input mesh, was broken in several places of the code.
This PR fixes it.
@xiaoXiaoCam thank you for the bug report. This PR should fix your issue
> Tetrahedral_remeshing - fix the cell selection

- Documentation/doc/resources/1.8.20/BaseDoxyfile.in
In the doxygen version 1.9.0 the setting `COLS_IN_ALPHA_INDEX` has been made obsolete and generates a warning during building.
As the default value is used it can also be removed (doxygen will automatically take the default value in the older versions).
> Obsolete doxygen setting COLS_IN_ALPHA_INDEX

- Circulator/doc/Circulator/Circulator.txt
Not familiar with the word "akeen", its not in the English dictionary. Probably should be "akin"
* Affected package(s): circulators
> Fix spelling akeen -> akin

- Filtered_kernel/include/CGAL/internal/Static_filters/Collinear_3.h
Make the changes as suggested by @mglisse to fix the issue.  I didn't address the further suggested improvements.
* Issue(s) solved (if any): fix #5207
> Kernel: Collinear_3: Static Analysis

- Nef_3/include/CGAL/Nef_3/SNC_simplify.h
In SNC_simplify.h the function  simplify_redundant_box_vertex unconditionally returns false.
https://github.com/CGAL/cgal/blob/a848e52552a9205124b7ae13c7bcd2b860eb4530/Nef_3/include/CGAL/Nef_3/SNC_simplify.h#L194-L202
This function should probably be removed as it is effectively not in use.
* Issue(s) solved (if any): bugfix
> Fix structurally dead code in SNC_simplify.h

- Nef_3/include/CGAL/Nef_3/SNC_io_parser.h
In SNC_io_parser the parameter i in the function output_sorted_indexes is of type `CGAL::Object_index<CGAL::internal::In_place_list_iterator<CGAL::SNC_in_place_list_sface<CGAL::SNC_indexed_items::SFace<CGAL::SNC_structure<CGAL::Epeck, CGAL::SNC_indexed_items, bool> > >, std::allocator<CGAL::SNC_in_place_list_sface<CGAL::SNC_indexed_items::SFace<CGAL::SNC_structure<CGAL::Epeck, CGAL::SNC_indexed_items, bool> > > > > >` and has a size of 152 bytes. For this reason its usual to pass the parameter  by reference instead of by value.
Furthermore the parameter D in the constructor of sort_sface_cycle_entries is of type `CGAL::SNC_io_parser<CGAL::SNC_structure<CGAL::Epeck, CGAL::SNC_indexed_items, bool> >::SNC_structure (size 480 bytes) by value.` which is 480 bytes in size. The parameters for …
> Fix passing big parameters by value in SNC_io_parser.h

- Triangulation_3/include/CGAL/Triangulation_hierarchy_3.h
Construct a `double` from the `enum`  to avoid the warning seen in
the [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-29/Triangulation_3/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz) with a VC++ preview release:
`C:\cgal_test\CGAL-5.3-Ic-29\include\CGAL/Triangulation_hierarchy_3.h(866): warning C5055: operator '/': deprecated between enumerations and floating-point types` 
The "better" fix is in #5310 but it needs a more modern C++ so let's apply that later.
* Affected package(s): Triangulatyion_3
* partially fixes #5342
> Triangulation_3: Construct double to avoid VC++ warning C5055

- Point_set_processing_3/include/CGAL/edge_aware_upsample_point_set.h
Just a minor patch: I think this output was for debug purpose.
> PSP_3: Remove debug output

- STL_Extension/include/CGAL/Handle_for_virtual.h
Fixes null pointer dereference in the destructor of `Handle_for_virtual` which can be caused as demonstrated in #5338 
* Affected package(s): STL Extension
* Issue(s) solved (if any): fix #5338, partially fix #5342
* Feature/Small Feature (if any): bugfix
> Fix segmentation fault in destructor of Handle_for_virtual.h

- Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Alpha_shape_mesher.h
When testing that the index is in the right range, it's useless to test `>= 0` considering the index is unsigned. This raises some warnings on recent compilers.
* Affected package(s): Scale Space
> [Scale Space] Fix warning, comparing size_t with 0 is always true

- Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_polycurve_intersection.cpp
- BGL/include/CGAL/boost/graph/copy_face_graph.h
- CGAL_ipelets/include/CGAL/grabbers.h
- Classification/examples/Classification/example_cluster_classification.cpp
- Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
- Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h
- Mesh_3/include/CGAL/Mesh_3/Slivers_exuder.h
- NewKernel_d/include/CGAL/NewKernel_d/Lazy_cartesian.h
- Periodic_3_mesh_3/include/CGAL/Periodic_3_mesh_3/Protect_edges_sizing_field.h
- Point_set_processing_3/include/CGAL/Point_set_processing_3/internal/Neighbor_query.h
- Polygon_mesh_processing/examples/Polygon_mesh_processing/connected_components_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_of_patch_example.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/intersection.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h
- Polyhedron/demo/Polyhedron/Plugins/PMP/Hole_filling_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Hole_filling_polyline_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Weighted_PCA_smoother.h
- Shape_detection/examples/Shape_detection/region_growing_on_point_set_3.cpp
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Fixed_border_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/IO/File_off.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/LSCM_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Two_vertices_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/internal/validity.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/parameterize.h
The header was already deprecated in boost 1.66
> Include non-deprecated header (5.1)

- Point_set_processing_3/examples/Point_set_processing_3/registration_with_OpenGR.cpp
- Point_set_processing_3/examples/Point_set_processing_3/registration_with_opengr_pointmatcher_pipeline.cpp
- Point_set_processing_3/examples/Point_set_processing_3/registration_with_pointmatcher.cpp
Windows requires `std::ios::binary` tag to properly read binary input. It was missing from the registration examples.
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/5315
> Point Set Processing - Fix missing std::ios::binary tag in some examples

- Polyhedron_IO/demo/Polyhedron_IO/geomview_demo.cpp
Deactivate completely the Geomview demo.
* Affected package(s):Polyhedron_IO
> Deactivate geomview_demo

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_nodes.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_of_coplanar_triangles_3.h
Use Node_vector to deduce the exact kernel instead of hardcoding it.
Fixes #5322
> remove hardcoded kernel

- Classification/include/CGAL/Classification/ETHZ/Random_forest_classifier.h
- Polyhedron/demo/Polyhedron/Plugins/Classification/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Classification/Classification_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Classification/Item_classification_base.h
The dependency to Boost IO Stream and Serialization has been removed since https://github.com/CGAL/cgal/pull/4626.
This PR fixes 2 problems:
- the `save_configuration()` / `load_configuration()` were still enclosed in `#ifdef` about Boost, whereas they don't depend on it anymore
- the dependency is now optional for compiling the plugin, considering it's just used to load deprecated configuration files (everything else works without it)
* Affected package(s): Classification + Demo
> [Classification] Fix Boost optional dependencies
