CGAL/cgal

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h

Use correct vpm

---

Three/include/CGAL/Three/Scene_item_rendering_helper.h
Three/include/CGAL/Three/Triangle_container.h

Fix warning doc.
* Issue(s) solved (if any): fix #3459, fix #3461

Three: Fix warnings in Three documentation.

---

Documentation/doc/resources/1.8.13/header.html
Documentation/doc/resources/1.8.13/header_package.html
Documentation/doc/resources/1.8.14/header.html
Documentation/doc/resources/1.8.14/header_package.html
Documentation/doc/resources/1.8.4/header.html
Documentation/doc/resources/1.8.4/header_package.html

close link

---

Documentation/doc/biblio/cgal_manual.bib

Fix urls in bib

---

BGL/include/CGAL/boost/graph/named_params_helper.h

Do no ignore user provided traits

Fix in PSP named parameters

---

BGL/include/CGAL/boost/graph/Face_filtered_graph.h

BGL: Fix doc of Face_filtered_graph

---

Nef_S2/include/CGAL/Nef_polyhedron_S2.h

Fix typo. Thank you @cedricpradalier
* Affected package(s): Nef_S2
* Issue(s) solved (if any): fix #3474

Nef_S2: has_sloop() -> has_shalfloop()

---

Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp

Polyhedron demo: fix Advancing front 

---

CGAL_ImageIO/include/CGAL/read_vtk_image_data.h

take offset from vtkImage and add it to cgal image.
* Affected package(s):ImageIO

ImageIO: Add offset from vtk

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h

Add a missing swap
Somehow fixes #3565

Add missing swap

---

BGL/include/CGAL/boost/graph/METIS/partition_dual_graph.h
BGL/include/CGAL/boost/graph/METIS/partition_graph.h

* Issue(s) solved (if any): fix #3528

BGL: Fix memory leaks in partition code

---

Nef_3/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h

This allows an undocumented use of nef -> polygon soup

More modular implementation of nef to face graph

---

Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/Straight_skeleton_converter_2.h

Add missing :

---

QP_solver/doc/QP_solver/CGAL/QP_functions.h
QP_solver/doc/QP_solver/CGAL/QP_models.h
QP_solver/doc/QP_solver/CGAL/QP_options.h
QP_solver/doc/QP_solver/CGAL/QP_solution.h

doc clean-up

---

Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h

Fix how the freelists get joined.

Fix Surface_mesh::join()

---

Mesh_3/include/CGAL/Mesh_3/Mesher_level.h
TDS_3/include/CGAL/Triangulation_data_structure_3.h
Triangulation_3/include/CGAL/Regular_triangulation_3.h
Triangulation_3/test/Triangulation_3/include/CGAL/_test_cls_parallel_triangulation_3.h
Triangulation_3/test/Triangulation_3/test_regular_3.cpp

Same as #3367 but with conflicts with 4.13 fixed.

 Triangulation_3: Fix insertion and removal of ranges of weighted points (4.13+)

---

Polyhedron/demo/Polyhedron/Plugins/Display/Display_property_plugin.cpp

This fixes the call to the FacetTriangulator inside the Scene_heat_item.

Polyhedron demo: Fix Display_property_plugin

---

Scripts/developer_scripts/cgal_create_release_with_cmake.cmake

Remove applications directory

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/border.h

Fixes a broken link
@MaelRL shouldn't we move the function (file) to BGL before the release?

fix wrong ref

---

Polyhedron/demo/Polyhedron/MainWindow.cpp

Fix the runtime warning about sendMessage in the mainwindow.

Polyhedron demo: Small Fix for Qt missing Connection

---

Polyhedron/demo/Polyhedron/MainWindow.cpp
Polyhedron/demo/Polyhedron/MainWindow.h
Polyhedron/demo/Polyhedron/MainWindow.ui
Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp

Fixes color each cc, remove isolated vertices and detect borders.
* Affected package(s):Polyhedron_Demo

Polyhedron Demo: fixes

---

.travis/install.sh

Add qt5-sqlite in the deps for the demo P3T3

Travis add missing dep to qt5 sql

---

Classification/test/Classification/test_classification_point_set.cpp
Installation/CHANGES.md
Point_set_3/include/CGAL/Point_set_3.h
Point_set_3/include/CGAL/Point_set_3/IO.h
Point_set_3/test/Point_set_3/point_set_test_join.cpp
Polyhedron/demo/Polyhedron/Plugins/PMP/Point_inside_polyhedron_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_to_mesh_distance_plugin.cpp
Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
Polyhedron/demo/Polyhedron/include/Point_set_3.h
Surface_mesh/include/CGAL/Surface_mesh/Properties.h

Small feature wiki page: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Point_Set_3_v2
The Point Set 3 package is still young and can be improved: this small feature introduces several small improvements.
-   Add a method `copy_properties()` that allows to copy the properties from a point set to another one (without copying the content);
-   add a method `insert(const Point_set&, const Index&)` to copy a point *along with all its associated properties* from another point set;
-   `remove()` methods now only invalidate the `end()` iterator instead of invalidating all iterators;
-   add a method `is_removed()` that takes an index as argument;
-   document `garbage_size()`;
-   add a method `cancel_removal()` to restore removed points (if no point was inserted …

[Small Feature] Point Set 3 v2

---

Documentation/doc/resources/1.8.13/hacks.js
Documentation/doc/resources/1.8.14/hacks.js

fix navtree hack

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_faces.h
Polygon_mesh_processing/test/Polygon_mesh_processing/triangulate_faces_test.cpp

* Issue(s) solved (if any): -- 

PMP: Fix incorrect named parameters 

---

Polyhedron/demo/Polyhedron/MainWindow.cpp
Polyhedron/demo/Polyhedron/Plugins/Display/Display_property_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PMP/Orient_soup_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PMP/Scene_facegraph_item_k_ring_selection.h
Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Offset_meshing_plugin.cpp
Polyhedron/demo/Polyhedron/Scene_item_rendering_helper.cpp
Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
Polyhedron/demo/Polyhedron/Viewer.cpp
Polyhedron_IO/include/CGAL/IO/OFF_reader.h

More bug fixes in the demo.
* Issue(s) solved (if any): fix #3629

Polyhedron Demo: new batch of bug fixes

---

Solver_interface/doc/Solver_interface/PackageDescription.txt

add missing concept to the packagedescription of solver_interface.
* Affected package(s):Solver_interface

Solver_interface: minor doc fix

---

Circular_kernel_3/include/CGAL/Circular_kernel_3/Circular_arc_3.h

Fix [this test](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-127/Circular_kernel_3/TestReport_lrineau_Fedora-Release.gz).  We forgot to do it in ##3580
* Affected package(s): Circular_kernel_3

Circular_kernel_3: Initialize data member

---

Documentation/doc/scripts/generate_how_to_cite.py

Made generated file (X)HTML compliant.

File not (X)HTML compliant

---

TDS_2/include/CGAL/Triangulation_data_structure_2.h

Fix the conversion member function.
* Affected package(s): TDS_2
* Issue(s) solved (if any): fix #3709

TDS_2: Fix Default_vertex_converter

---

Polyhedron/demo/Polyhedron/MainWindow.cpp
Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
Polyhedron/demo/Polyhedron/include/CGAL/statistics_helpers.h

Adds statistics to the selection item:
* Issue(s) solved (if any): fix #3728

Polyhedron_demo: Add stats to the selection_item

---

Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp

The way to select points was producing very poor performances in case of a large point set (worst case complexity _O(n²)_). The bug was introduced by https://github.com/CGAL/cgal/pull/3343 (first included in 4.14-beta).
It is fixed by simply partitioning the indices (which is quick) and setting the index of the first selected.

Polyhedron demo: Fix point set selection speed

---

Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_widget.ui
Polyhedron/demo/Polyhedron/Scene.h

Fixes the two bugs reportes in #3745 
* Issue(s) solved (if any): fix #3745

Polyhedron Demo:  fix visualization bugs

---

Mesh_2/doc/Mesh_2/Concepts/DelaunayMeshFaceBase_2.h
Triangulation_2/doc/Triangulation_2/Concepts/ConstrainedTriangulationFaceBase_2.h
Triangulation_2/doc/Triangulation_2/Concepts/TriangulationVertexBaseWithInfo_2.h
Triangulation_3/doc/Triangulation_3/Concepts/RegularTriangulationCellBase_3.h

tiny fixes.
* Affected package(s): Triangulation_2, Triangulation_3, Mesh_2

T2,T3,Mesh_2: backticks, lowercase, capitalize

---

SearchStructures/doc/SearchStructures/CGAL/Range_segment_tree_traits.h
SearchStructures/doc/SearchStructures/Concepts/RangeSegmentTreeTraits_k.h
SearchStructures/doc/SearchStructures/PackageDescription.txt
Triangulation_3/doc/Triangulation_3/Concepts/DelaunayTriangulationCellBase_3.h
Triangulation_3/doc/Triangulation_3/Concepts/DelaunayTriangulationTraits_3.h
Triangulation_3/doc/Triangulation_3/Concepts/RegularTriangulationCellBaseWithWeightedCircumcenter_3.h
Triangulation_3/doc/Triangulation_3/Concepts/RegularTriangulationCellBase_3.h
Triangulation_3/doc/Triangulation_3/Concepts/RegularTriangulationVertexBase_3.h
Triangulation_3/doc/Triangulation_3/Concepts/TriangulationCellBaseWithInfo_3.h
Triangulation_3/doc/Triangulation_3/Concepts/TriangulationCellBase_3.h
Triangulation_3/doc/Triangulation_3/Concepts/TriangulationVertexBaseWithInfo_3.h
Triangulation_3/doc/Triangulation_3/Concepts/TriangulationVertexBase_3.h

Thank you @lvalque  for pointing this out. 
* Affected package(s): SearchStructures
* Issue(s) solved (if any): fix #3742

Range and Segment Trees: Sync code and doc

---

Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_polycurve_traits_2.h
Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/Periodic_2_triangulation_2.h

Various doc fixes

---

Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/Gps_on_surface_base_2.h

Fixes #3747
@efifogel would you mind add the failing test in the testsuite ?

Fix error in outer CCB setting

---

Surface_mesh_simplification/doc/Surface_mesh_simplification/Surface_mesh_simplification.txt
Surface_mesh_simplification/doc/Surface_mesh_simplification/examples.txt
Surface_mesh_simplification/examples/Surface_mesh_simplification/CMakeLists.txt
Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_bounded_normal_change.cpp
Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrained_border_surface_mesh.cpp
Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_enriched_polyhedron.cpp
Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_polyhedron.cpp
Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_surface_mesh.cpp
Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_visitor_surface_mesh.cmd
Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_visitor_surface_mesh.cpp

Use  `Surface_mesh` in more examples.    Also fix the "empty" [section](https://doc.cgal.org/latest/Surface_mesh_simplification/index.html#title10).

SMS: Examples with Surface_mesh

---

Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PCA/Transformation_widget.ui

Fix for the widget which display waas broken on Windows.
* Issue(s) solved (if any): fix #3787

Polyhedron Demo: Fix Affine_transformation_plugin

---

Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/CMakeLists.txt
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h

Fixes for some warnings on Friedrich.
* Affected package(s):Hyperbolic_triangulation_2, PMP

Fixes for warnings

---

.travis/test_package.sh

Don't compare with master but with the branch of the PR using `...`

Travis: Fix the test of dependencies

---

Polyhedron_IO/include/CGAL/IO/STL_writer.h

STL writer under LGPL

---

Documentation/doc/Documentation/Developer_manual/Chapter_checks.txt
Documentation/doc/Documentation/Installation.txt
Documentation/doc/biblio/cgal_manual.bib

Fix some of the missing links.
* Issue(s) solved (if any): fix #3819

CGAL:Fix missing links after Albert's review

---

Polyhedron/demo/Polyhedron/include/id_printing.h

Check that the manipulated halfegdes in zoom_to_id are not border to avoid invalid faces.
* Issue(s) solved (if any): fix #3811

Polyhedron_demo: Fix zoom to Id

---

Maintenance/public_release/scripts/precompiled_demos_zips

Add hyperbolic triangulation demos.
* Affected package(s):Maintenance
* Issue(s) solved (if any): fix #3817

Maintenance: Update the script for the zipped demos

---

Scripts/developer_scripts/cgal_create_package_dir.py

Cleanup, as it currently creates a little bit too much files and directories.
* Affected package(s): developer_scripts

Scripts: Update create_package_dir

---

Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h
Three/include/CGAL/Three/Scene_item.h

Add statistics to the polygon soups: 
Number of Points
Number of Polygons
Pure Triangle
Pure Quad
Number of Degenerate Polygons
Number of Edges
Minimum Edge Length
Maximum Edge Length
Median Edge Length
Mean Edge Length
Number of Degenerate Edges
Minimum Angle
Maximum Angle
Average Angle
* Issue(s) solved (if any): fix #3839

Polyhedron Demo: Add stats to polygon_soup

---

Mesh_2/include/CGAL/Delaunay_mesher_2.h
Nef_2/include/CGAL/Nef_2/PM_const_decorator.h

Fix warnings

---

BGL/include/CGAL/boost/graph/Face_filtered_graph.h
BGL/test/BGL/test_Face_filtered_graph.cpp

See #3862.
Compared to the other PR, commit e17f10f (deletes a useless data file) is not present there, because it will not create any conflict anyway.

BGL: Fix `Face_filtered_graph`'s `is_selection_valid()` (5.0)

---

Boolean_set_operations_2/doc/Boolean_set_operations_2/PackageDescription.txt
Envelope_3/doc/Envelope_3/PackageDescription.txt
Nef_2/doc/Nef_2/PackageDescription.txt
Partition_2/doc/Partition_2/PackageDescription.txt
Straight_skeleton_2/doc/Straight_skeleton_2/PackageDescription.txt

Remove link to old demos

---

STL_Extension/include/CGAL/Concurrent_compact_container.h

The PR #3824 was incomplete. I still had to implement the same patch for `<CGAL/Concurrent_compact_container.h>`.
* Affected package(s): STL_Extension (Compact_container)

Fix AppleClang -Wnull-pointer-arithmetic warning with TBB as well

---

Installation/CHANGES.md

I forgot to update the `CHANGES.md` file in https://github.com/CGAL/cgal/pull/3636.

Surface Mesh PLY IO: Update CHANGES.md

---

Stream_support/examples/Stream_support/CMakeLists.txt

Set find_package for boost to QUIET and remove duplicate.
* Affected package(s):Stream_support

Stream_support Examples: Fix CMakeLists

---

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_rib_exporter_plugin.cpp

Remove debug message from the  init() function of the rib plugin.
* Issue(s) solved (if any): fix #3913

Polyhedron demo: Remove useless message at startup

---

BGL/include/CGAL/boost/graph/helpers.h

BGL: Fix is valid polygon mesh (5.0)

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_slicer.h
Polygon_mesh_processing/test/Polygon_mesh_processing/polygon_mesh_slicer_test.cpp

This is the master verison of #3910

Polygon_mesh_slicer:  Fix orientation for master

---

Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2.h
Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h

Fix initialization of the vector of indices fill directly instead of resizing it and inserting back...

T2: Fix insertion of range of constraints

---

Nef_3/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h

Fix index order of triangles

---

Barycentric_coordinates_2/include/CGAL/Barycentric_coordinates_2/Mean_value_2.h
Circular_kernel_3/include/CGAL/Circular_kernel_3/internal_functions_on_sphere_3.h
Interpolation/include/CGAL/constructions/constructions_for_voronoi_intersection_cartesian_2_3.h
Interpolation/include/CGAL/natural_neighbor_coordinates_2.h
Interpolation/include/CGAL/predicates/predicates_for_voronoi_intersection_cartesian_2_3.h
Interpolation/package_info/Interpolation/dependencies
Number_types/include/CGAL/Root_of_traits.h
Number_types/include/CGAL/Sqrt_extension/Sqrt_extension_type.h
Optimal_transportation_reconstruction_2/include/CGAL/OTR_2/Reconstruction_triangulation_2.h
Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h
Periodic_3_triangulation_3/include/CGAL/internal/Periodic_3_triangulation_dummy_36.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap.h
STL_Extension/include/CGAL/iterator.h

There hasn't been much testing of `Simple_cartesian<mpq_class>` as an exact kernel...
Since this touches a number of places, you are welcome to take a look and shout if you notice anything suspicious.
* Affected package(s): many

Misc fixes for expression templates

---

Polyhedron/demo/Polyhedron/Scene_lcc_item.cpp
Polyhedron/demo/Polyhedron/Scene_lcc_item.h

Add colors per face or volume in the context menu of the lcc item.
@gdamiand sorry for the long delay, but this finalizes your feature request. Don't hesitate to ask for more stuffs, now that the big modifications on the demo are integrated it will be much faster.
* Issue(s) solved (if any): fix #2411

3D Demo: Lcc IO plugin

---

Interpolation/examples/Interpolation/sibson_interpolation_2.cpp
Interpolation/examples/Interpolation/sibson_interpolation_rn_2.cpp
Interpolation/examples/Interpolation/surface_neighbor_coordinates_3.cpp
Surface_mesh_deformation/examples/Surface_mesh_deformation/custom_weight_for_edges_example.cpp
Surface_mesh_deformation/examples/Surface_mesh_deformation/deform_polyhedron_with_custom_pmap_example.cpp
Surface_mesh_deformation/examples/Surface_mesh_deformation/k_ring_roi_translate_rotate_Surface_mesh.cpp
Surface_mesh_deformation/examples/Surface_mesh_deformation/k_ring_roi_translate_rotate_example.cpp
Surface_mesh_segmentation/examples/Surface_mesh_segmentation/sdf_values_example.cpp
Surface_mesh_segmentation/examples/Surface_mesh_segmentation/segmentation_from_sdf_values_OpenMesh_example.cpp
Surface_mesh_segmentation/examples/Surface_mesh_segmentation/segmentation_from_sdf_values_SM_example.cpp
Surface_mesh_segmentation/examples/Surface_mesh_segmentation/segmentation_from_sdf_values_example.cpp
Surface_mesh_segmentation/examples/Surface_mesh_segmentation/segmentation_via_sdf_values_example.cpp
Surface_mesh_segmentation/examples/Surface_mesh_segmentation/segmentation_with_facet_ids_example.cpp

WIP
* Affected package(s): Surface_mesh_segmentation, Surface_mesh_deformation

Use C++11 for loop in examples

---

Testsuite/test/post_process_ctest_results.py
Three/doc/Three/Three.txt

Add a warning about the Polyhedron_demo_DIR in the doc to explain it needs to be from the same CGAL version as the CGAL_DIR

Polyhedron Demo: Enhance doc

---

Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Finite_edge_interior_conflict_C2.h
Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_filtered_traits_2.h
Segment_Delaunay_graph_2/test/Segment_Delaunay_graph_2/sdg_br_case1.cpp

Fix the in-conflict of Voronoi edge

---

Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/Gps_on_surface_base_2.h
Boolean_set_operations_2/test/Boolean_set_operations_2/bug_3989.cpp

Fix outer ccb supply chain

---

Scripts/developer_scripts/cgal_create_release_with_cmake.cmake

Add an option to create tarballs while creating a release

---

Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.h

Make possible to mesh a bounded volume with extra surfaces inside, like the example `examples/Mesh_3/mesh_polyhedral_domain_with_surface_inside.cpp`.
* Affected package(s): Mesh_3, Polyhedron Demo
* License and copyright ownership: maintenance

Polyhedron demo:  mesh several surfaces at a time

---

Intersections_2/include/CGAL/Ray_2_Triangle_2_intersection.h
Intersections_2/include/CGAL/Triangle_2_Iso_rectangle_2_intersection.h
Intersections_2/test/Intersections_2/test_intersections_2.cpp

* Affected package(s): `Intersections_2`

Intersections_2: Fix some issues and populate tests

---

Apollonius_graph_2/include/CGAL/Apollonius_graph_2.h
Apollonius_graph_2/include/CGAL/Apollonius_graph_2/Apollonius_graph_2_impl.h
Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2.h
Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Segment_Delaunay_graph_2_impl.h
Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Segment_Delaunay_graph_hierarchy_2_impl.h
Segment_Delaunay_graph_Linf_2/include/CGAL/Segment_Delaunay_graph_Linf_2/Segment_Delaunay_graph_Linf_hierarchy_2_impl.h

Recursive functions are fancy but they can cause stack issues.
* Affected package(s): `Segment_Delaunay_graph_2`

SDG: Derecursify functions

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h

Needed if you have garbage or use a (hash) map

update marks on removed edges

---

Installation/CHANGES.md

I forgot to update it for PR https://github.com/CGAL/cgal/pull/3869.

Update CHANGES.md for PSP: Spherical Neighborhood Queries

---

BGL/include/CGAL/boost/graph/helpers.h

Same as #4053, with conflicts with 5.0 fixed.

 BGL: Fix output of "is_valid_polygon_mesh" function family (5.0)

---

Polynomial/include/CGAL/Test/_test_polynomial_traits_d.h

Fix issue #4044.
* Affected package(s): Polynomial (with LEDA only)
* Issue(s) solved (if any): fix #4044
* License and copyright ownership: trivial change

Polynomial: fix a remaining warning (with LEDA), fix issue #4044

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h
Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_clip.cpp

- better handling of border non-manifold edges during clipping.

Fixes for clipping

---

Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
Polyhedron/demo/Polyhedron/Scene_item_rendering_helper.cpp

Fix the c3t3 item, its sizing balls and its intersection with several viewers.
* Issue(s) solved (if any): fix #4079 

3D Demo: Fix c3t3_item

---

AABB_tree/demo/AABB_tree/MainWindow.cpp
GraphicsView/demo/Circular_kernel_2/ArcsGraphicsItem.h
GraphicsView/demo/Periodic_2_triangulation_2/include/CGAL/Qt/PeriodicTriangulationGraphicsItem.h
GraphicsView/include/CGAL/Qt/AlphaShapeGraphicsItem.h
GraphicsView/include/CGAL/Qt/DelaunayMeshTriangulationGraphicsItem.h
GraphicsView/include/CGAL/Qt/DemosMainWindow_impl.h
GraphicsView/include/CGAL/Qt/PointsGraphicsItem.h
GraphicsView/include/CGAL/Qt/PointsInKdTreeGraphicsItem.h
GraphicsView/include/CGAL/Qt/PolygonGraphicsItem.h
GraphicsView/include/CGAL/Qt/PolygonWithHolesGraphicsItem.h
GraphicsView/include/CGAL/Qt/RegularGridGraphicsItem.h
GraphicsView/include/CGAL/Qt/RegularGridVectorFieldGraphicsItem.h
GraphicsView/include/CGAL/Qt/RegularTriangulationGraphicsItem.h
GraphicsView/include/CGAL/Qt/SegmentDelaunayGraphGraphicsItem.h
GraphicsView/include/CGAL/Qt/SegmentDelaunayGraphLinfGraphicsItem.h
GraphicsView/include/CGAL/Qt/TriangulationGraphicsItem.h
GraphicsView/include/CGAL/Qt/qglviewer_impl.h
Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/include/internal/Qt/TriangulationGraphicsItem.h
Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/include/internal/Qt/TriangulationGraphicsItemWithColorInfo.h
Periodic_4_hyperbolic_triangulation_2/demo/Periodic_4_hyperbolic_triangulation_2/include/internal/Qt/TriangulationGraphicsItem.h
Polyhedron/demo/Polyhedron/MainWindow.cpp
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
Polyhedron/demo/Polyhedron/Scene.cpp
Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
Polyhedron/demo/Polyhedron/Viewer.cpp
Polyline_simplification_2/demo/Polyline_simplification_2/include/CGAL/Qt/Polyline_simplification_2_graphics_item.h
Polyline_simplification_2/demo/Polyline_simplification_2/include/CGAL/Qt/TriangulationArrangementGraphicsItem.h
Principal_component_analysis/demo/Principal_component_analysis/MainWindow.cpp
Three/include/CGAL/Three/TextRenderer.h
Triangulation_3/demo/Triangulation_3/Viewer.cpp

Fix Qt deprecation warnings for 4.14

---

CGAL_ipelets/include/CGAL/CGAL_Ipelet_base_v7.h
Intersections_2/test/Intersections_2/test_intersections_2.cpp
Kernel_23/include/CGAL/determinant.h
Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_site_2.h
Segment_Delaunay_graph_2/test/Segment_Delaunay_graph_2/include/test_types.h
Snap_rounding_2/include/CGAL/Snap_rounding_kd_2.h

warnings and errors fixes.
* Issue(s) solved (if any): fix #4086

Fixes for 4.13

---

Shape_detection/include/CGAL/Shape_detection/Efficient_RANSAC/Efficient_RANSAC.h

Add const spedifier to access the function `number_of_unassigned_points`.

minor fix: add const specifier

---

Stream_support/include/CGAL/IO/File_writer_wavefront.h
Surface_mesh/include/CGAL/Surface_mesh/IO.h

Add vertex nomals in write_OBJ for Surface_mesh
* Affected package(s):Surface_mesh
* Issue(s) solved (if any): fix #4071

Surface_mesh: normals in OBJ Writer

---

Polyhedron/demo/Polyhedron/MainWindow.cpp
Polyhedron/demo/Polyhedron/MainWindow.h
Polyhedron/demo/Polyhedron/Plugins/Display/Display_property.ui
Polyhedron/demo/Polyhedron/Plugins/Display/Display_property_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/IO/3mf_io_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Scene_polyhedron_shortest_path_item.cpp
Polyhedron/demo/Polyhedron/Scene.cpp
Polyhedron/demo/Polyhedron/Scene.h
Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
Three/include/CGAL/Three/Scene_interface.h

Fixes #4110, fixes #4127 
- Fix the reloading of an oriented soup. 
- Restore highlighting of self-intersections.

3D Demo: Fixes

---

Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Arrangement_on_surface_2.txt

User manual fixes

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h

Internal code of `PMP::isotropic_remeshing()` uses `CGAL::Euler::flip_edge()` to fix degenerate faces that can be created during the short edges collapse step.
This PR fixes this use of `flip_edge()` by adding a topological condition that prevents from creating non-manifold configurations (and a segfault in the following steps).
The condition was there but only as an assertion, and has been turned into a strong condition.
* Issue(s) solved (if any): fix #4148

`PMP::isotropic_remeshing()` - prevent creating non-manifold configurations

---

CGAL_ImageIO/examples/CGALimageIO/CMakeLists.txt
CGAL_ImageIO/examples/CGALimageIO/extract_a_sub_image.cpp
CGAL_ImageIO/include/CGAL/ImageIO.h
CGAL_ImageIO/include/CGAL/ImageIO_impl.h
CGAL_ImageIO/include/CGAL/Image_3.h
CGAL_ImageIO/include/CGAL/read_vtk_image_data.h
CGAL_ImageIO/test/CGAL_ImageIO/test_trilinear_interpolation.cpp
Random_numbers/include/CGAL/Random.h
Surface_mesher/demo/Surface_mesher/values_list.cpp
Surface_mesher/demo/Surface_mesher/volume.cpp
Surface_mesher/demo/Surface_mesher/volume.h

Add a new tool extract_a_sub_image.cpp to extract a sub-image.
* Affected package(s): CGAL_ImageIO
* License and copyright ownership: maintenance by GeometryFactory 
This PR can go to any beta of CGAL-5.0 or CGAL-5.1. I do not really care.

CGAL_ImageIO: Add a new tool extract_a_sub_image.cpp to extract a sub-image

---

BGL/include/CGAL/boost/graph/Named_function_parameters.h
Scripts/developer_scripts/update_to_CGAL_np.sh

Add code to prevent silent bad usage of boost::get_param

---

BGL/include/CGAL/boost/graph/Named_function_parameters.h

Fix for #4208 
The change shall make it in 4.14 branch but not master.

available only if c++11 is available

---

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
Polyhedron/demo/Polyhedron/Viewer.cpp

- fixes the segmented image items, that did not display anything
- fixes the c3t3 .mesh loading/saving, as a .mesh has an invalid triangulation, and it must not be saved in that case.
* Affected package(s):CGAL 3D Demo

CGAL 3D Demo: Some more fixes

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h
Triangulation_2/test/Triangulation_2/issue_4010.cpp

- Remove some c++11 code from a test in Triangulation_2
* Affected package(s):Triangulation_2

Fixes for 4.14

---

Nef_S2/examples/Nef_S2/nef_s2_construction.cpp
Nef_S2/include/CGAL/Nef_S2/SM_overlayer.h

This is a backport of #4152 for 4.14
* Affected package(s):Nef_S2

Nef_S2: Fix memory corruption

---

Installation/CHANGES.md
Maintenance/public_release/announcement/mailing-beta.eml

Prepare CGAL 5.0-beta1: CHANGES, and announcement email

Prepare CGAL 5.0-beta1: CHANGES, and announcement email

---

GraphicsView/include/CGAL/Buffer_for_vao.h
GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h
Linear_cell_complex/include/CGAL/draw_linear_cell_complex.h
Polyhedron/include/CGAL/draw_polyhedron.h
Surface_mesh/include/CGAL/draw_surface_mesh.h

Update cgal basic viewer to solve a linker error when used with nef.
* Affected package(s): Cgal basic viewer
* Issue(s) solved (if any): fix #4291

Basic viewer bugfix

---

Installation/include/CGAL/config.h

Replaces/addresses https://github.com/mhsaar/cgal/pull/15

Add a way to define a default endianness

---

Installation/CHANGES.md
Polygon_mesh_processing/doc/Polygon_mesh_processing/Doxyfile.in
Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt
Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt

Fix a bunch of tiny errors (see individual commits).
* Affected package(s): `PMP`, Manual

PMP (and changelog): Fix misc errors in 5.0-beta1

---

Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/SDF_calculation.h

Be more robust to degenerate and almost degenerate faces

---

Documentation/doc/resources/1.8.13/stylesheet.css
Documentation/doc/resources/1.8.14/stylesheet.css
Documentation/doc/resources/1.8.4/stylesheet.css

Fixes #2095
@albert-github running with a recent doxygen (9a23681bc4322a1912fc98f683bcf3e49a85f47b) with option -w to generate the stylesheet I see the issue is still here. Would you have time to fix it or do you prefer I open a PR?

Fix doc style issue

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/bbox.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/extrude.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h

Add missing definitions of
`CGAL_PMP_NP_TEMPLATE_PARAMETERS` and ` CGAL_PMP_NP_CLASS`

PMP: Fix doc macro

---

Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
Scripts/developer_scripts/create_new_release

wip
* Issue(s) solved (if any): fix #3330, fix https://github.com/CGAL/GeometryFactory/issues/24

Developers scripts: create_release_with_cmake  create new tarballs

---

Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.cpp

CGAL 3D Demo: Fix nef_polyhedron normals

---

Distance_3/include/CGAL/squared_distance_3_2.h
Distance_3/test/Distance_3/test_distance_3.cpp

The squared_distance(Plane_3, Plane_3) implementation was missing
* Affected package(s):Distance_3

Distance_3: Add Pl_3-Pl_3

---

CGAL_ImageIO/include/CGAL/ImageIO/iris_impl.h

Fix warnings
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-176.shtml#CGAL_ImageIO
* Affected package(s): ImageIO

ImageIO: fix warnings

---

GraphicsView/demo/icons/license.txt
Installation/LICENSE
Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/icons/license.txt

Fix issues reported by @joachim-reichel

Fix license issues

---

Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
STL_Extension/include/CGAL/Concurrent_compact_container.h
Scripts/scripts/cgal_create_CMakeLists
Triangulation_3/benchmark/Triangulation_3/CMakeLists.txt
Triangulation_3/benchmark/Triangulation_3/DT3_benchmark_with_TBB.cpp

Same as #4389 (that targets 5.0.x), but for `releases/CGAL-4.14-branch`.
* Affected package(s): STL_Extension, Triangulation_[23]
* Issue(s) solved (if any): fix #4388 

Fix DT3 parallel performance loss (issue #4388) for CGAL-4.14.x

---

Solver_interface/include/CGAL/GLPK_mixed_integer_program_traits.h
Solver_interface/include/CGAL/SCIP_mixed_integer_program_traits.h

Two supposedly documented solvers are not showing up in the documentation: https://doc.cgal.org/5.0/Solver_interface/group__PkgSolverInterfaceRef.html. They also don't have associated pages. This PR fixes that.
The large diff is because I had a warning in Doxygen about the virtual function and it was resolved by recombining the declarations and bodies.
* Affected package(s): `Solver_interface`

Solver Interface: Fix two solvers not showing up in documentation

---

NewKernel_d/include/CGAL/NewKernel_d/function_objects_cartesian.h

Remove some unnecessary dereferencing.

---

Kernel_23/include/CGAL/Aff_transformation_3.h
Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Detail/Edge_collapse.h

Add misisng headers in Aff_transformation_3.h
* Affected package(s):Kernel_23
* Issue(s) solved (if any): fix #4382

Fix Aff_transformation_3 missing includes

---

Maintenance/test_handling/testsuite_comparison/diff_testsuites.html
Maintenance/test_handling/testsuite_comparison/diff_testsuites.js
Maintenance/test_handling/testsuite_comparison/difflib.js
Maintenance/test_handling/testsuite_comparison/fill_empty_lines.js
Maintenance/test_handling/testsuite_comparison/print_diff.js
Maintenance/test_handling/testsuite_comparison/test.html
Maintenance/test_handling/testsuite_comparison/worker.js

Just saving my scripts for the diff between testsuites.

Maintenance: Add scripts for testsuite diff

---

Surface_mesh_simplification/doc/Surface_mesh_simplification/Surface_mesh_simplification.txt
Surface_mesh_simplification/doc/Surface_mesh_simplification/dependencies

* Affected package(s): `Surface_mesh_simplification`

SMS: Fix some missing links in doc

---

Polyhedron/demo/Polyhedron/MainWindow.cpp
Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
Polyhedron/demo/Polyhedron/Scene.cpp
Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp

Some more fixes for the demo.
Fixes #4378

Fixes for the Demo

---

Mesh_3/include/CGAL/Mesh_3/Mesher_3.h

Fix https://github.com/CGAL/cgal/pull/4392. See https://github.com/CGAL/cgal/pull/4392#issuecomment-572602138.
* Issue(s) solved (if any): fix #4392 

Bug in the demo (mesh_3_plugin)

---

Installation/cmake/modules/FindGLPK.cmake
Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt

Add a PATHS parameter to the find_path for 3mf in the demo.
* Affected package(s):Polyhedron Demo
* Issue(s) solved (if any): fix #4369, fix #4368

Add PATHS to find_path 3mf

---

Apollonius_graph_2/include/CGAL/Hyperbola_segment_2.h
Apollonius_graph_2/include/CGAL/Parabola_segment_2.h

This PR fixes a bunch of tiny errors in the discretization of parabola and hyperbola segments. Tested visually with Segment Delaunay Graphs for parabolas.

Fix discretization of parabola and hyperbola segments

---

Classification/include/CGAL/Classification/ETHZ/internal/random-forest/forest.hpp
Classification/include/CGAL/Classification/Feature_set.h
Classification/include/CGAL/Classification/Local_eigen_analysis.h
Classification/include/CGAL/Classification/Mesh_feature_generator.h
Classification/include/CGAL/Classification/Sum_of_weighted_features_classifier.h
Classification/include/CGAL/Classification/classify.h
Mesh_3/include/CGAL/Compact_mesh_cell_base_3.h
Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
Mesh_3/include/CGAL/Mesh_3/Mesh_complex_3_in_triangulation_3_base.h
Mesh_3/include/CGAL/Mesh_3/Mesh_global_optimizer.h
Mesh_3/include/CGAL/Mesh_3/Mesh_surface_cell_base_3.h
Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
Mesh_3/include/CGAL/Mesh_3/Worksharing_data_structures.h
Mesh_3/include/CGAL/Mesh_3/vertex_perturbation.h
Mesh_3/include/CGAL/Mesh_cell_base_3.h
Mesh_3/test/Mesh_3/CMakeLists.txt
Mesh_3/test/Mesh_3/test_meshing_3D_gray_image.cpp
Mesh_3/test/Mesh_3/test_meshing_determinism.cpp
Point_set_processing_3/include/CGAL/bilateral_smooth_point_set.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_to_mesh_distance_plugin.cpp
STL_Extension/include/CGAL/Spatial_lock_grid_3.h
STL_Extension/include/CGAL/thread.h
STL_Extension/test/STL_Extension/test_Concurrent_compact_container.cpp
Triangulation_3/examples/Triangulation_3/sequential_parallel.cpp
Triangulation_3/include/CGAL/Delaunay_triangulation_3.h
Triangulation_3/include/CGAL/Regular_triangulation_3.h

This PR replaces the tbb deprecated code with std equivalents.
* Affected package(s):Mesh_3, PMP, PSP, Classification,STL_Extension, Triangulation_3

TBB deprecated code replacement

---

Polyhedron/demo/Polyhedron/Plugins/PMP/Point_inside_polyhedron_plugin.cpp

I could reproduce https://github.com/CGAL/cgal/issues/4487 but I don't quite understand why it becomes longer the second time...
Anyway, I've replaced the selection section by a more efficient mechanism using `std::partition` similarly to what I did in the point set selection plugin, it seems to work well from what I tested.
* Affected package(s): demo
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/4487

[Demo] Fix point selection in Point_inside_polyhedron_plugin

---

Polyhedron/demo/Polyhedron/Plugins/PMP/Repair_polyhedron_plugin.cpp

Trivial demo fix 

---

Barycentric_coordinates_2/benchmark/Barycentric_coordinates_2/Discrete_harmonic_coordinates/DH_speed_test_100_vertices.cpp
Barycentric_coordinates_2/benchmark/Barycentric_coordinates_2/Mean_value_coordinates/MV_speed_test_100_vertices.cpp
Barycentric_coordinates_2/benchmark/Barycentric_coordinates_2/Wachspress_coordinates/WP_speed_test_100_vertices.cpp
Generator/include/CGAL/point_generators_d.h
Optimal_transportation_reconstruction_2/demo/Optimal_transportation_reconstruction_2/scene.h
Point_set_processing_3/include/CGAL/bilateral_smooth_point_set.h
Ridges_3/include/CGAL/Umbilics.h
Snap_rounding_2/include/CGAL/Snap_rounding_kd_2.h
Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_builder_2_impl.h

Use `CGAL_PI` instead of hardcoding pi (usually with a lower precision).
* Affected package(s): Multiple
* Issue(s) solved (if any): #4445

Use `CGAL_PI` where relevant

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h
Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_clip.cpp

Add clipping overload to a iso-cuboid

---

Installation/CMakeLists.txt
Installation/cmake/modules/CGAL_SetupGMP.cmake
Intersections_3/test/Intersections_3/call_test.cpp

With this PR, the default of the WITH_GMPXX option will be set to ON if GMPXX is found.
* Issue(s) solved (if any): fix #4266

Set GMPXX ON if detected

---

NewKernel_d/include/CGAL/NewKernel_d/Lazy_cartesian.h
Triangulation/test/Triangulation/test_delaunay.cpp
Triangulation/test/Triangulation/test_regular.cpp

More testing for Epeck_d would be good. We are getting compilation issues on windows in gudhi, we'll see if they already appear in CGAL this way.

Also test Triangulation with Epeck_d

---

Shape_detection/examples/Shape_detection/efficient_RANSAC_with_parameters.cpp

Shape_detection: Correcting comment in efficient_RANSAC_with_parameters example

---

INSTALL.md

Fix missing path in cmake invocation in example docs

INSTALL.md: Fix missing path in cmake invocation

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/merge_border_vertices.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h

* Issue(s) solved (if any): fix #4548

PMP: Fix doxygen warnings

---

Polyhedron/demo/Polyhedron/CGAL_double_edit.cpp
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Meshing_dialog.ui

Fixes the Mesh_dialog in the Mesh_3 plugin
* Issue(s) solved (if any): fix #4478

3D Demo:  Fix Meshing_dialog.ui

---

Documentation/doc/Documentation/advanced/Configuration_variables.txt

Add some information to the Summary page of the Getting Started documentation.

Documentation: Add missing configuration variables for METIS

---

Filtered_kernel/include/CGAL/Kernel_profiler.h
Kernel_23/doc/Kernel_23/CGAL/Filtered_predicate.h
Kernel_23/include/CGAL/Kernel_checker.h
Kernel_d/include/CGAL/Kernel_d/function_objects.h
Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_builder_traits_2_aux.h
Straight_skeleton_2/include/CGAL/Unfiltered_predicate_adaptor.h

@mglisse: Not sure why you have two versions in `Kernel_d/include/CGAL/Kernel_d/function_objects.h`, one with different template parameters and one with identical one.

use Variadic templates

---

Installation/CHANGES.md

Forgotten update of `CHANGES.md` for https://github.com/CGAL/cgal/pull/4530.

[CDT / Split Constraints] Update CHANGES.md

---

BGL/test/BGL/test_Prefix.h
Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_constrained_triangulation_2.h
Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_delaunay_triangulation_2.h
Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_triangulation_2.h

I only checked BGL (because I vaguely remembered seeing that before) and T2 (to fix #4609)
* Affected package(s): `BGL`, `Triangulation_2`
* Issue(s) solved (if any): fix #4609

Fix some tests intializing or changing data in assertions

---

Polyhedron/demo/Polyhedron/Scene.cpp

Fix selection by picking in the presence of a wireframe item.

CGAL 3D Demo: Fix picking with wireframe and points

---

Documentation/doc/resources/1.8.14/BaseDoxyfile.in

Remove deprecated doxygen config options

---

Polyhedron/demo/Polyhedron/MainWindow.cpp

A typo added a useless line width action that did nothing.
* Affected package(s):Demo

Demo - Fix line width in menus

---

Documentation/doc/Documentation/License.txt

Fixes #4634
Only for 5.0 branch as the file has been moved and it isn't worth the trouble to backport onto 4.14

Use regular font

---

Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_filtered_traits_2.h
Segment_Delaunay_graph_Linf_2/include/CGAL/Segment_Delaunay_graph_Linf_filtered_traits_2.h

Use Exact_field_selector

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h

Fixes  #3847
I'm not doing the backport to release branches as the doc changed and it is not worth handling the conflict.

Fix is_outward_oriented doc

---

Boolean_set_operations_2/doc/Boolean_set_operations_2/CGAL/Boolean_set_operations_2.h

Fix doc links

---

Polyhedron/demo/Polyhedron/include/CGAL/IO/read_surf_trianglemesh.h

Enhancement for our surf_reader

Surf_reader : Enhancement

---

Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_observer.h

Clarify doc

---

Polygon_mesh_processing/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp
Polyhedron/demo/Polyhedron/Plugins/Classification/Cluster_classification.cpp
Polyhedron/demo/Polyhedron/Plugins/Classification/Surface_mesh_item_classification.cpp
Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp

Fix a remaining std::max in a plugin of the demo
* Affected package(s):Polyhedron demo

Fix remaining std::max

---

Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_consecutive_bool_op.cpp
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h

Simplify example

---

Polyhedron/demo/Polyhedron/Plugins/IO/Surf_io_plugin.cpp
Polyhedron/demo/Polyhedron/include/CGAL/IO/read_surf_trianglemesh.h

Add support for binary surf reading.
* Affected package(s):Polyhedron_demo, Stream_support

IO: Add binary support for surf reading.

---

Optimal_bounding_box/include/CGAL/Optimal_bounding_box/internal/evolution.h
Optimal_bounding_box/include/CGAL/Optimal_bounding_box/internal/optimize_2.h
Optimal_bounding_box/include/CGAL/Optimal_bounding_box/oriented_bounding_box.h

Self-explanatory commits.
* Affected package(s): `Optimal_bounding_box`

OBB: Accuracy improvements

---

.travis/build_package.sh
.travis/windows.h

Add a fake windows.h for travis to detect the most common mistakes.

Travis: <windows.h>

---

Spatial_searching/examples/Spatial_searching/distance_browsing.cpp
Spatial_searching/include/CGAL/Incremental_neighbor_search.h
Spatial_searching/include/CGAL/Orthogonal_incremental_neighbor_search.h

Add missing const

---

.travis/build_package.sh

Travis - Fix

---

Polyhedron/demo/Polyhedron/CMakeLists.txt
Polyhedron/demo/Polyhedron/MainWindow.cpp
Polyhedron/demo/Polyhedron/MainWindow.h
Polyhedron/demo/Polyhedron/MainWindow.ui
Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Point_set/CMakeLists.txt
Polyhedron/demo/Polyhedron/Server_ws.cpp
Polyhedron/demo/Polyhedron/Server_ws.h
Polyhedron/demo/Polyhedron/Use_ssh.cpp
Polyhedron/demo/Polyhedron/Viewer.cpp
Polyhedron/demo/Polyhedron/include/CGAL/Use_ssh.h

CGAL 3D Demo: Enhancements and fixes

---

Shape_detection/doc/Shape_detection/PackageDescription.txt

No need to say that this is CGAL.   And if we really want to keep it we have to use the macro or put a % before to avoid the link being generated.

Shape Detection: Update PackageDescription.txt

---

Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
Surface_sweep_2/include/CGAL/Surface_sweep_2/Curve_pair.h

Fix C++20 errors/warnings. Followup to PR #4640.
Cc @mglisse 
* Affected package(s): all

Fix C++20 errors

---

Triangulation_2/doc/Triangulation_2/Triangulation_2.txt
Triangulation_2/doc/Triangulation_2/examples.txt
Triangulation_2/doc/Triangulation_2/fig/low_dimensional.svg
Triangulation_2/examples/Triangulation_2/low_dimensional.cpp

Add a figure that illustrates how a low dimensional triangulation is represented.
* Affected package(s): Triiangulation_2   only documentation.
* License and copyright ownership:  maintenancy by GeometryFactory

Triangulation_2: Add a figure and an example for dimension < 2

---

Polyhedron/demo/Polyhedron/Plugins/IO/Implicit_function_io_plugin.cpp

Fix the Generate_objet typo in the file menu.

Polyhedorn Demo: Fix typo

---

AABB_tree/demo/AABB_tree/Scene.cpp
AABB_tree/demo/AABB_tree/Scene.h

Fix the CPU consumption of the AABB demo
* Issue(s) solved (if any): fix #4766

AABB_demo: Fix

---

Distance_3/include/CGAL/squared_distance_3_1.h

Fix error in Distance_3 with LEDA
* Affected package(s):Distance_3

Distance_3: Fix error with LEDA

---

Straight_skeleton_2/include/CGAL/Straight_skeleton_halfedge_base_2.h
Straight_skeleton_2/test/Straight_skeleton_2/test_straight_skeleton_copy.cpp

Make straight_skeleton copy_constructible

---

Point_set_processing_3/include/CGAL/hierarchy_simplify_point_set.h

Condition "or" should be "and".
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/4765

PSP: Fix documentation of hierarchy simplify point set

---

Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_cache.h

Compute all roots of one of the resultants to do successful matching.
Two methods are used for computing the intersections:
1. de Casteljau subdivision.
2. Analytic solution by solving their equations.
In case de Casteljau fails, the analytic method is used. It's easy to reproduce the bug by disabling de Casteljau subdivision (changing line 2355 in `Bezier_x_monotone_2.h` for example to `if (false)`)
and  trying these curves:
https://www.desmos.com/calculator/f9efwzbb3k
In which, there are two roots, both out of range, but it'll match them as if they're one root resulting in an incorrect root which is in range.
* Affected package(s): 2D Arrangements
* Issue(s) solved (if any): fix #3381
* License and copyright ownership: license already used by CGAL

Fix Bezier intersection bug around the boundaries (issue #3381)

---

Polyhedron/demo/Polyhedron/Plugins/PMP/RemoveNeedlesDialog.ui

Improve ui of needles/caps removal

---

AABB_tree/doc/AABB_tree/aabb_tree.txt

AABB_tree: Fix typo

---

AABB_tree/include/CGAL/AABB_traits.h

Hide undocumented inheritance

---

Polyhedron/demo/Polyhedron/MainWindow.cpp

I have simplified the code, using `std::lower_bound` and standard comparisons from Qt5 `QString`.
* Affected package(s): 3d demo

3D demo MainWindow.cpp: Reimplement addActionToMenu with standard algorithms

---

GraphicsView/include/CGAL/Qt/camera_impl.h
Number_types/include/CGAL/Exact_algebraic.h
Number_types/test/Number_types/Lazy_exact_nt_new.cpp

A few fixes to our LEDA testsuite.

A few fixes to our LEDA testsuite

---

BGL/include/CGAL/boost/graph/Dual.h
BGL/include/CGAL/boost/graph/METIS/partition_dual_graph.h
BGL/include/CGAL/boost/graph/METIS/partition_graph.h
BGL/include/CGAL/boost/graph/Seam_mesh.h
BGL/include/CGAL/boost/graph/selection.h
BGL/include/CGAL/boost/graph/split_graph_into_polylines.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/locate.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/manifoldness.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_mesh_to_polygon_soup.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/smooth_mesh.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h

* Affected package(s): `BGL/PMP`
* License and copyright ownership: No changes

Use lower case for function documentation starting with a verb (BGL/PMP)

---

Nef_3/include/CGAL/Nef_3/Bounding_box_3.h
Nef_3/include/CGAL/Nef_3/SNC_constructor.h
Nef_3/include/CGAL/Nef_3/SNC_io_parser.h
Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
Nef_3/test/Nef_3/CMakeLists.txt
Nef_3/test/Nef_3/test_nef_3_io_EPIC.cpp

Re-enable compilation with double based kernel

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h
Polygon_mesh_processing/test/Polygon_mesh_processing/test_repair_polygon_soup.cpp

Fix and simplification proposed by @SamSavitz.
* Issue(s) solved (if any): partial fix of #4882

Fix and simplify polygon soup repairing subfunction "simplify_polygon"

---

Kernel_23/test/Kernel_23/test_approximate_dihedral_angle_3.cpp

Add `test/Kernel_23/test_approximate_dihedral_angle_3.cpp`.
* License and copyright ownership: GF

Add test/Kernel_23/test_approximate_dihedral_angle_3.cpp

---

Stream_support/include/CGAL/IO/write_vtk.h

The package and the headers are LGPL.

remove incorrect license include statement

---

Filtered_kernel/include/CGAL/Lazy.h

* Affected package(s): `Filtered_kernel`
* Issue(s) solved (if any): fix #4974

Filtered_kernel: Add missing header includes

---

Installation/include/CGAL/Mesh_3/Mesh_complex_3_in_triangulation_3_fwd.h
Mesh_3/include/CGAL/Mesh_3/tet_soup_to_c3t3.h
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp

When reading a .mesh in the demo, if a subdomain is 0, make it 1.

Polyhedron Demo: .mesh reading enhancement

---

.github/workflows/build_doc.yml
.github/workflows/delete_doc.yml

Add a workflow using the github actions to build and upload the doc for each new pull_request
* Issue(s) solved (if any): fix #4900

Documentation: add build and upload with CI

---

.github/workflows/build_doc.yml

Only run the automated doc creation if the PR is labeled "small feature"

CI : Limit the automated doc to "small feature" labels

---

GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h

Add an option to toggle between 2D and 3D mode for the basic viewer; feature asked by an user.
* Fix: #4966

Add an option to toggle between 2D and 3D mode for the basic viewer.

---

Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp

add a 1.001 factor in the default spacing,
* Issue(s) solved (if any): fix #4956

Polyhedron demo: change for grid plugin

---

Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_widget.ui

Add a checkbox to triangulate a polyline/polygon in the basic generator.

Polyhedron Demo: Add an option to the polyline generator

---

Polyhedron/demo/Polyhedron/Plugins/PMP/Engrave_text_plugin.cpp

Add some warnings and connections to reset pointers to null.

Polyhedron Demo: Robustify the engrave_text_plugin

---

Polyhedron/demo/Polyhedron/Plugins/PMP/Repair_polyhedron_plugin.cpp

Update displayed number of isolated vertices after removal.

Polyhedron Demo: Fix Remove_isolated_vertices

---

.github/workflows/delete_doc.yml

Test if index.html changed before trying to push it

CI: fix error

---

Intersections_2/include/CGAL/Intersections_2/Line_2_Line_2.h
Intersections_2/include/CGAL/Intersections_2/Line_2_Ray_2.h
Intersections_2/include/CGAL/Intersections_2/Segment_2_Segment_2.h
Intersections_2/include/CGAL/Intersections_2/internal/Straight_2.h
Kernel_23/examples/Kernel_23/MyPointC2.h
Triangulation_2/include/CGAL/Triangulation_2.h

Fix some uninitialized warning

Fix some warnings

---

Point_set_processing_3/include/CGAL/remove_outliers.h
Point_set_processing_3/test/Point_set_processing_3/remove_outliers_test.cpp

Use property map in std::nth_element call

---

Mesh_3/include/CGAL/Compact_mesh_cell_base_3.h
Mesh_3/include/CGAL/Mesh_3/io_signature.h
Mesh_3/include/CGAL/Mesh_triangulation_3.h
Mesh_3/include/CGAL/Mesh_vertex_base_3.h
Mesh_3/include/CGAL/internal/Mesh_3/indices_management.h
Mesh_3/test/Mesh_3/CMakeLists.txt
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_rib_exporter_plugin.cpp

Reduce size of symbols (and debug infos):
- one nested struct `Tds` in `Mesh_triangulation_3`,
- rework of `Mesh_vertex_base_3` and `Compact_mesh_cell_base_3`.
That reduction of debug infos and size of symbols will help the IDEs and debuggers.
```
Debug info size (with gcc-9, and `-g`)
ORIG	AFTER	RATIO  		FILE IN examples/Mesh_3/
56532	55572	1.01727		mesh_3D_image_with_custom_initialization.debug
64696	63420	1.02012		mesh_cubes_intersection_with_features.debug
56700	55536	1.02096		mesh_3D_image.debug
56488	55324	1.02104		mesh_implicit_sphere.debug
56496	55332	1.02104		mesh_implicit_sphere_variable_size.debug
56776	55604	1.02108		mesh_3D_image_variable_size.debug
56520	55296	1.02214		mesh_cubes_intersection.debug
56684	55428	1.02266		mesh_3D_gray_image.debug
56796	55536	1.02269 …
```

Reduce size of symbols (and debug infos)

---

GraphicsView/demo/Triangulation_2/Regular_triangulation_2.cpp
GraphicsView/demo/Triangulation_2/TriangulationPointInputAndConflictZone.h
GraphicsView/include/CGAL/Qt/GraphicsViewCircleInput.h

Fix some width and add a double click for 0 weihted points.

GraphicsView: Regular_triangulation_2 enhancements

---

BGL/include/CGAL/boost/graph/Face_filtered_graph.h
Surface_mesh_segmentation/examples/Surface_mesh_segmentation/extract_segmentation_into_mesh_example.cpp

improves the readability of user code

Add a constuctor with an empty selection

---

BGL/examples/BGL_LCC/normals_lcc.cpp
BGL/examples/BGL_polyhedron_3/normals.cpp
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/manifoldness.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/random_perturbation.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/smooth_mesh.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/smooth_shape.h
Polygon_mesh_processing/test/Polygon_mesh_processing/connected_component_polyhedron.cpp
Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PMP/Scene_facegraph_item_k_ring_selection.h
Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
Polyhedron/include/CGAL/boost/graph/properties_Polyhedron_3_features.h
Property_map/include/CGAL/property_map.h
Surface_mesh/include/CGAL/boost/graph/properties_Surface_mesh_features.h

* init vectors
* remove duplicated map
* add static boolean map
* add named parameter to avoid removing some vertices (make them isolated)

Clean in connected components

---

.github/workflows/build_doc.yml

Trigger the build of the doc when a collaborator comments "build:xxx". xxx should be round1, round2 etc.

Documentation : Trigger on build:xxx

---

Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/flip_edges.h
Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/smooth_vertices.h

Fixes for warnings in 5.1

---

Bounding_volumes/doc/Bounding_volumes/CGAL/Min_sphere_d.h

Fix doc warning : wrong example path

Warning Fixes in master

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h

Warnings fixes for 5.0

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
Polygon_mesh_processing/test/Polygon_mesh_processing/remove_degeneracies_test.cpp

Release branch version of PR: #5012

Degeneracy removal: fix removing upcoming elements while iterating

---

Polyhedron/demo/Polyhedron/Plugins/PCA/Edit_box_plugin.cpp

Fix the export_to_facegraph that doesn't show.

Polyhedron_demo : Fix Edit_box->export_to_facegraph()

---

Polyhedron/demo/Polyhedron/Viewer.cpp

reset the frustum after scaling the scene.

Polyhedron demo: Fix the scene scaling

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h

PMP: Remove overload of non-existent function

---

Triangulation_2/include/CGAL/Constrained_triangulation_2.h
Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
Triangulation_2/include/CGAL/Triangulation_2/internal/Polyline_constraint_hierarchy_2.h
Triangulation_2/test/Triangulation_2/issue_5080.cpp

_Describe what your pull request changes to CGAL (this can be skipped if it solves an issue already in the tracker or if it is a Feature or Small Feature submitted to the CGAL Wiki)._

Triangulation_2: improve CDT_plus_2

---

Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h

Accomodate duplicated points in the input mesh

---

.travis/build_package.sh

Add a misisng exit 0 that makes every CHECK step fail

Fix Travis

---

.github/workflows/build_doc.yml

Specify that the doc takes some time before being available.

CI : Message for the doc

---

GraphicsView/include/CGAL/Qt/qglviewer_impl.h
Polyhedron/demo/Polyhedron/Viewer.cpp

Updates the descriptions of the mouse and key bindings of the demo and some of the basic viewer.

Polyhedron demo: Update Mouse and Key Bindings

---

Polyhedron/demo/Polyhedron/Scene.cpp
Polyhedron/demo/Polyhedron/Scene.h
Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h
Polyhedron/demo/Polyhedron/Viewer.cpp
Polyhedron/demo/Polyhedron/Viewer.h
Three/include/CGAL/Three/Scene_draw_interface.h
Three/include/CGAL/Three/Scene_print_item_interface.h
Three/include/CGAL/Three/TextRenderer.h
Three/include/CGAL/Three/Viewer_interface.h

Document the `scaler` parameter.

Three_documentation: Fix warning

---

Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h

Add const qualifier for getters in class Mean_curvature_flow_skeletonization
* Affected package(s): Triangulated Surface Mesh Skeletonization

Add const qualifier for getters in MCF skeletonization

---

.github/workflows/build_doc.yml
.github/workflows/delete_doc.yml

Prevents egrep from failing the whole job

CI: auto doc fix

---

.github/workflows/build_doc.yml

CI fix git diff

---

.github/workflows/build_doc.yml

Really fix git diff and stop job if list_of_PKGS is empty.

CI fix doc 

---

.github/workflows/build_doc.yml
.github/workflows/delete_doc.yml

- Don't try to copy doc_output/Installation as it doesn't exist
- Don't try to git rm a PR_NUMBER if it doesn't exist.

Ci another fix for the doc

---

.github/install.sh
.github/test.sh
.github/workflows/cmake-all.yml
.github/workflows/demo.yml

Add a github worflow in 4 jobs to test the polyhedron demo compilation.

Ci test demo 

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/locate.h

PMP: Remove obsolete forward declaration with no body

---

GraphicsView/include/CGAL/Buffer_for_vao.h

Fix cases where the face contains aligned edges .
* Issue(s) solved (if any): fix #4002

GraphicsView: Fix is_facet_convex()

---

Polyhedron/demo/Polyhedron/Plugins/Convex_hull/Convex_hull_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_simplification_plugin.cpp
Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
Polyhedron/demo/Polyhedron/Scene_spheres_item.cpp
Polyhedron/demo/Polyhedron/Scene_spheres_item.h

Some enhancements and behavior fixes for the demo

Polyhedron Demo: Enhancements 

---

Scripts/developer_scripts/cgal_create_release_with_cmake.cmake

Add the missing /demo in the release creation script

Fix CGAL_Qt5 installation

---

.github/workflows/build_doc.yml

Add apt-get update before the dependencies installation

Add apt-get update

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_mesh_to_polygon_soup.h

* Issue(s) solved (if any): fix #5224

PMP: Add missing header include (PM to PS)

---

Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Concepts/ArrangementXMonotoneTraits_2.h

Small reformulation (seen as closing bracket was missing).

Small correction (text / missing bracket)

---

Documentation/doc/resources/1.8.20/footer.html
Documentation/doc/resources/1.8.20/header_package.html

For a better quality also the close image was converted to an svg image, so the png does not exists anymore. This has to be reflected in this file as well.

Referencing non existing file

---

Triangulation/benchmark/Triangulation/Td_vs_T2_and_T3.cpp

Fix benchmark compilation

---

Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h

Ignore isolated vertices

---

GraphicsView/include/CGAL/Qt/qglviewer.h
GraphicsView/include/CGAL/Qt/qglviewer_impl.h
Polyhedron/include/CGAL/draw_polyhedron.h

When performing the first tick of an optical zoom (z+wheel), recenter the camera to the cursor if it is over an item.

GraphicsView: Zoom enhancement

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h

TIny improvement of surface isotropic remeshing

---

Polygon_mesh_processing/examples/Polygon_mesh_processing/surface_mesh_intersection.cpp
Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths.cpp
Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_OpenMesh.cpp
Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_multiple_sources.cpp
Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_no_id.cpp
Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_with_id.cpp
Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrain_sharp_edges.cpp
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_LCC_example.cpp
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_example.cpp
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_sm_example.cpp
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/simple_mcfskel_LCC_example.cpp
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/simple_mcfskel_example.cpp
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/simple_mcfskel_sm_example.cpp

Change extension to the one recognized by the demo

---

BGL/include/CGAL/boost/graph/generators.h

Allow FT that isn't floating point.

---

.github/workflows/demo.yml

Add `push` to the triggers of the demo.yml, so it is also tested when branches are merged in master.

CI: Trigger the demo checks on push too

---

BGL/include/CGAL/boost/graph/copy_face_graph.h
CGAL_ipelets/include/CGAL/grabbers.h
Classification/examples/Classification/example_cluster_classification.cpp
Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h
Mesh_3/include/CGAL/Mesh_3/Slivers_exuder.h
Minkowski_sum_2/examples/Minkowski_sum_2/approx_inset.cpp
Minkowski_sum_2/examples/Minkowski_sum_2/approx_offset.cpp
Minkowski_sum_2/examples/Minkowski_sum_2/exact_inset.cpp
Minkowski_sum_2/examples/Minkowski_sum_2/exact_offset.cpp
Minkowski_sum_2/test/Minkowski_sum_2/test_minkowski_sum_with_holes.cpp
NewKernel_d/include/CGAL/NewKernel_d/Lazy_cartesian.h
Periodic_3_mesh_3/include/CGAL/Periodic_3_mesh_3/Protect_edges_sizing_field.h
Point_set_processing_3/include/CGAL/Point_set_processing_3/internal/Neighbor_query.h
Polygon_mesh_processing/examples/Polygon_mesh_processing/connected_components_example.cpp
Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_example.cpp
Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_of_patch_example.cpp
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/intersection.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h
Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Weighted_PCA_smoother.h
Shape_detection/examples/Shape_detection/region_growing_on_point_set_3.cpp
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Fixed_border_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/IO/File_off.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Iterative_authalic_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/LSCM_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Two_vertices_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/internal/validity.h

Get rid of some warnings pointed out by @joachim-reichel (thank you)
* Issue(s) solved (if any): fix some of #5303

Fixes for  boost::function_output_iterator and boost::timer

---

Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_polycurve_intersection.cpp
BGL/include/CGAL/boost/graph/copy_face_graph.h
CGAL_ipelets/include/CGAL/grabbers.h
Classification/examples/Classification/example_cluster_classification.cpp
Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h
Mesh_3/include/CGAL/Mesh_3/Slivers_exuder.h
NewKernel_d/include/CGAL/NewKernel_d/Lazy_cartesian.h
Periodic_3_mesh_3/include/CGAL/Periodic_3_mesh_3/Protect_edges_sizing_field.h
Point_set_processing_3/include/CGAL/Point_set_processing_3/internal/Neighbor_query.h
Polygon_mesh_processing/examples/Polygon_mesh_processing/connected_components_example.cpp
Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_example.cpp
Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_of_patch_example.cpp
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/intersection.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h
Polyhedron/demo/Polyhedron/Plugins/PMP/Hole_filling_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h
Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Weighted_PCA_smoother.h
Shape_detection/examples/Shape_detection/region_growing_on_point_set_3.cpp
Shape_detection/test/Shape_detection/test_validity_sampled_data.cpp
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Fixed_border_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/IO/File_off.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Iterative_authalic_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/LSCM_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Two_vertices_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/internal/validity.h

Include non-deprecated header (5.2)

---

.github/workflows/build_doc.yml

The index.html was not committed after the doc building.

Fix the Documentation jobs in the CI 

---

Documentation/doc/Documentation/Developer_manual/create_and_use_a_cmakelist.txt
Surface_mesh/examples/Surface_mesh/CMakeLists.txt

Restore the CMakelist.txt in the Minimal Example Using Qt5 of the developer manual

Documentation: Re-add missing CMakeLists

---

Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp
Linear_cell_complex/include/CGAL/draw_linear_cell_complex.h

Bug fix in LCC demo.
Before this patch, the demo crashes and cannot be run.
(thanks @maxGimeno for the bug report)
* Affected package(s): LCC

Bug fix in LCC demo

---

Convex_decomposition_3/test/Convex_decomposition_3/check_decomposition.cpp
Nef_2/include/CGAL/Nef_2/PM_io_parser.h
Nef_2/include/CGAL/Nef_polyhedron_2.h
Nef_3/include/CGAL/Nef_3/SNC_io_parser.h
Nef_S2/include/CGAL/Nef_S2/SM_io_parser.h

Add bound checks in IO functions of Ned_2/S2/3, and don't crash the program if there is an error but simply return witth a cerr.
* Affected package(s):Nef_2, Nef_S2, Nef_3

Fix OOB issues in Nef_*

---

BGL/include/CGAL/boost/graph/copy_face_graph.h
BGL/test/BGL/test_Euler_operations.cpp

Handle isolated vertices in the target mesh

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h

Hole filling is allowed to failed, not display a CGAL warning

Do not emit warning as hole filling can fail

---

Kernel_23/doc/Kernel_23/CGAL/Projection_traits_xy_3.h
Kernel_23/include/CGAL/internal/Projection_traits_3.h
Nef_3/include/CGAL/Nef_3/Exact_triangulation_euclidean_traits_xy_3.h
Nef_3/include/CGAL/Nef_3/Exact_triangulation_euclidean_traits_xz_3.h
Nef_3/include/CGAL/Nef_3/Exact_triangulation_euclidean_traits_yz_3.h
Triangulation_2/doc/Triangulation_2/Concepts/ConstrainedTriangulationTraits_2.h
Triangulation_2/include/CGAL/Constrained_triangulation_2.h
Triangulation_2/include/CGAL/Triangulation_2/internal/Triangulation_2_projection_traits_base_3.h

See Issue #5174.
Todo:  Document in changes that it is a breaking change for people writing their own traits class.
* Issue(s) solved (if any): fix #5174
* License and copyright ownership: remains with Inria

Nef_3, Triangulation_2:  Change the result type of the Intersect_2 functor

---

Voronoi_diagram_2/doc/Voronoi_diagram_2/Concepts/AdaptationTraits_2.h

Add namespace `CGAL::`  as we are in a concept page.

Voronoi_diagram_2: Update AdaptationTraits_2.h

---

Scripts/developer_scripts/autotest_cgal_with_ctest

The script autotest_with_ctest was broken

Testsuite: Fix script for ctest

---

Filtered_kernel/include/CGAL/internal/Static_filters/Compare_distance_3.h
Filtered_kernel/include/CGAL/internal/Static_filters/Static_filters.h

Adding the static filter accelerated offset meshing which compares distances all the time.
* Affected package(s):  Kernel_23

Filtered Kernel: Add static filter for Compare_distance_3

---

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Offset_meshing_plugin.cpp

Add an action to inflate a mesh to the Offset_meshing_plugin. That means simply translate each vertex along its normal.

Polyhedron_demo: Add inflate_mesh

---

Polyhedron/demo/Polyhedron/resources/shader_with_texture.vert

Fix a mistake in a demo shader
Only in master because it was broken in #5285, which was integrated in 5.3

Polyhedron_demo: Fix a shader

---

.github/test.sh
.github/workflows/demo.yml

backport the CI tests for the demo to 5.1

CI: Add tests for the demo

---

GraphicsView/include/CGAL/Qt/camera_impl.h
GraphicsView/include/CGAL/Qt/qglviewer_impl.h

Fix Qt warnings

---

Mesh_3/include/CGAL/Mesh_3/experimental/Facet_patch_id_map.h
Mesh_3/include/CGAL/Mesh_3/experimental/Get_facet_patch_id.h
Mesh_3/include/CGAL/Mesh_3/experimental/Lipschitz_sizing_experimental.h
Mesh_3/include/CGAL/Mesh_3/experimental/Sizing_field_with_aabb_tree.h
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_function.h

The current code was breaking some user code

Clean and fix default facet patch id map

---

BGL/test/BGL/test_bgl_read_write.cpp
Polygon_mesh_processing/test/Polygon_mesh_processing/pmp_compute_normals_test.cpp
Polygon_mesh_processing/test/Polygon_mesh_processing/test_is_polygon_soup_a_polygon_mesh.cpp

Fix a warning in Apple clang
* Affected package(s):BGL, PMP

BGL, PMP: Fix a warning

---

Filtered_kernel/include/CGAL/Filtered_predicate.h
NewKernel_d/include/CGAL/NewKernel_d/Cartesian_LA_base.h
NewKernel_d/include/CGAL/NewKernel_d/Cartesian_LA_functors.h
NewKernel_d/include/CGAL/NewKernel_d/Cartesian_filter_K.h
NewKernel_d/include/CGAL/NewKernel_d/Cartesian_static_filters.h
NewKernel_d/include/CGAL/NewKernel_d/Filtered_predicate2.h
NewKernel_d/include/CGAL/NewKernel_d/Kernel_2_interface.h
NewKernel_d/include/CGAL/NewKernel_d/Kernel_3_interface.h
NewKernel_d/include/CGAL/NewKernel_d/LA_eigen/constructors.h
NewKernel_d/include/CGAL/NewKernel_d/Lazy_cartesian.h
NewKernel_d/include/CGAL/NewKernel_d/Types/Hyperplane.h
NewKernel_d/include/CGAL/NewKernel_d/Types/Sphere.h
NewKernel_d/include/CGAL/NewKernel_d/function_objects_cartesian.h
NewKernel_d/include/CGAL/NewKernel_d/functor_properties.h
NewKernel_d/test/NewKernel_d/CMakeLists.txt
NewKernel_d/test/NewKernel_d/Epick_d_eigen.cpp
NewKernel_d/test/NewKernel_d/tri2.cpp
Number_types/include/CGAL/Interval_nt.h

I put the benchmark in test/ so it gets compiled.
This is at the same time a private demo without type wrappers so that Point_2 is Eigen::Vector2d.
This has several other PRs merged in.

benchmark Delaunay 2d with NewKernel_d

---

GraphicsView/include/CGAL/Qt/constraint_impl.h
GraphicsView/include/CGAL/Qt/qglviewer_impl.h
Polyhedron/demo/Polyhedron/MainWindow.cpp
Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Diff_between_meshes_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp
Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
Polyhedron/demo/Polyhedron/create_sphere.h
Polyhedron/demo/Polyhedron/resources/compatibility_shaders/shader_spheres.vert
Polyhedron/demo/Polyhedron/resources/shader_spheres.vert

- Fix Sphere Lighting
- Fix the constraint of a very small edit-box 
- Invalidate the aabb_tree of an item after moving one of its vertices
- Fix scene saving 
- Fix name of result items in diff_between_meshes_plugin

Polyhedron demo: Fixes for 5.1

---

Polygon_mesh_processing/include/CGAL/Rigid_triangle_mesh_collision_detection.h

PMP Move assign for Rigid_triangle_mesh_collision_detection

---

Distance_3/include/CGAL/squared_distance_3.h
Distance_3/include/CGAL/squared_distance_3_2.h
Distance_3/include/CGAL/squared_distance_3_3.h
Distance_3/test/Distance_3/test_distance_3.cpp
Kernel_23/doc/Kernel_23/CGAL/squared_distance_2.h

Add squared distance computation for point and tetrahedron
This replaces the PR #5304.  The proposed code here makes fewer tests.
* Affected package(s): Distance_3

Distance_3: Add Point_3/Tetrahedron_3

---

Filtered_kernel/include/CGAL/Lazy.h
Filtered_kernel/include/CGAL/Lazy_kernel.h
Intersections_3/include/CGAL/Intersections_3/Line_3_Plane_3.h
Intersections_3/include/CGAL/Intersections_3/Plane_3_Plane_3.h
Kernel_23/include/CGAL/Kernel/function_objects.h
Kernel_23/include/CGAL/Kernel/interface_macros.h
Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h

Change the name of undocumented functor and function so that it is clear that it is an implementation detail.
* Affected package(s): Kernel, PMP
* Issue(s) solved (if any): fix #5471

Kernel_23:  Rename internal function and functor

---

BGL/include/CGAL/boost/graph/selection.h

Move non-documented experimental function in experimental namespace

---

Convex_hull_2/include/CGAL/Convex_hull_2/convexity_check_2_impl.h
Kernel_23/examples/Kernel_23/intersections.cpp
Mesh_3/include/CGAL/Mesh_3/Slivers_exuder.h
Partition_2/include/CGAL/Partition_2/Rotation_tree_2.h
Periodic_4_hyperbolic_triangulation_2/include/CGAL/Periodic_4_hyperbolic_Delaunay_triangulation_2.h
Triangulation_2/include/CGAL/Regular_triangulation_2.h
Triangulation_3/include/CGAL/Regular_triangulation_3.h

Remove last bind

---

.github/workflows/delete_doc.yml

Fix CI doc deletion

---

Polyhedron/demo/Polyhedron/MainWindow.cpp
Polyhedron/demo/Polyhedron/Scene.h

- Adds the bbox axis length in the items info
- Adds support for groups in scene IO

Polyhedron Demo: New features

---

Documentation/doc/CMakeLists.txt
Documentation/doc/scripts/generate_how_to_cite.py
Documentation/doc/scripts/html_output_post_processing.py
Documentation/doc/scripts/pkglist_filter.py
Documentation/doc/scripts/testsuite.py

Remove mentions to python2

---

Kernel_23/test/Kernel_23/include/CGAL/_test_new_3.h

Fix issue reported [here](https://github.com/CGAL/cgal/pull/5363/files/18f7f91c3cf3f113484d2e72f44e4110f84766b5#diff-beaa2812e22c3802f4da7e058d1347d7eeadf85af9653fc97735e5445490fe9e)

Use initialized vector

---

Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h

Do not test combinations of planes where we know that there is no intersection point.
* Affected package(s): Polygon Mesh Processing, Surface Mesh Simplification

PMP - Polyhedral Envelope :  Make it faster by making combinatorial tests 

---

Nef_3/include/CGAL/Nef_3/Nef_box.h
Nef_3/include/CGAL/Nef_3/SNC_FM_decorator.h
Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
Nef_3/include/CGAL/Nef_3/SNC_simplify.h
Nef_3/test/Nef_3/test_nef_3_io_EPIC.cpp

Avoid a geometric test that will lead to a filter failure
* License and copyright ownership: maintenance

Nef_3: Avoid a filter failure

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_callbacks.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h

Some faces were not collected and should have been taken into account while checking for self-intersections

Collect faces incident to edges too

---

Mesh_3/include/CGAL/Mesh_3/experimental/Sizing_field_with_aabb_tree.h

This PR fixes protection of features from - this is experimental code.
cc @lrineau 

Mesh_3 - fix feature protection for images

---

Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp

Fix text in the polyline corner item description.
The error appeared in 5.2

Polyhedron demo: Fix corner-item description

---

Documentation/doc/scripts/html_output_post_processing.py

Proper error handling instead of a crash

Workaround doxygen bug

---

Orthtree/doc/Orthtree/Orthtree.txt

Small correction in history of this new package, as @palliez informed me that he was actually the original developer of the prototype code.
* Affected package(s): Orthtree

Orthtree: Fix history

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_self_intersections.h

Used only in a non-documented function

Simplify conditional code

---

Skin_surface_3/include/CGAL/make_skin_surface_mesh_3.h

Case = 1 is using a special path

Add missing return statement

---

Number_types/include/CGAL/Mpzf.h

Fixup #5532, asked by @lrineau .

Disable /= with CGAL_NO_MPZF_DIVISION_OPERATOR

---

Polyhedron/demo/Polyhedron/Scene_group_item.cpp

Fixes warning: suggest explicit braces to avoid ambiguous ‘else’

Polyhedron Demo : Fix a warning

---

Triangulation_3/demo/Triangulation_3/Scene.h

fix an inverted if()
* Affected package(s):Trinagulation_3

Triangulation-3 Demo: Fix a warning

---

Nef_3/include/CGAL/Nef_3/bounded_side_3.h

This replaces #5708. Firstly this removes a check in the function side_of_plane_3 that tests `if(plane == Plane_3(0,0,0,0))`. 
>The check is needed so that when a parameter isn't given, an empty default parameter indicates that it should be populated from the points in the Iterator. However the function is never called without the plane parameter so the code is probably redundant, and the comment says it's not tested!
> The operator== for an empty plane isn't trivial. For cartesian kernels, it invokes equal_planeC3 which then in tern invokes equal_directionC3 which calculates the signs of 3 determinants...
>  Removing the redundant code doesn't give much of a performance boost (about 2% in my tests) but I think it's worthwhile nonetheless.
Secondly, the PR makes use of projection traits …

Remove redundant code in side_of_plane_3

---

Kernel_23/include/CGAL/Kernel/function_objects.h
Kernel_23/test/Kernel_23/include/CGAL/_test_fct_vector_3.h

Fix copy paste bug spotted by @GilesBathgate (thank you Giles)
* Affected package(s): Kernel_23, Nef_3
* Issue(s) solved (if any): See PR #5522

Kernel_23: Fix Non_zero_dimension

---

Installation/CHANGES.md

Reorganized, rewrote, added links, etc.
I have checked the links manually.

Prepare CHANGES.md for CGAL 5.3

---

Hash_map/include/CGAL/Handle_hash_function.h
STL_Extension/include/CGAL/In_place_list.h

Hash value of handles use directly the address of the node

---

Classification/doc/Classification/Classification.txt
Documentation/doc/Documentation/Developer_manual/Chapter_code_format.txt
Documentation/doc/Documentation/Third_party.txt
Documentation/doc/Documentation/Tutorials/Tutorial_hello_world.txt
Documentation/doc/Documentation/windows.txt
Documentation/doc/biblio/cgal_manual.bib
Installation/doc_html/index.html
Installation/include/CGAL/config.h
Mesh_3/doc/Mesh_3/Mesh_3.txt
Nef_3/include/CGAL/Nef_3/SNC_indexed_items.h
Point_set_processing_3/doc/Point_set_processing_3/Point_set_processing_3.txt
Point_set_processing_3/include/CGAL/bilateral_smooth_point_set.h
Point_set_processing_3/include/CGAL/wlop_simplify_and_regularize_point_set.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
Polygonal_surface_reconstruction/doc/Polygonal_surface_reconstruction/Polygonal_surface_reconstruction.txt
STL_Extension/doc/STL_Extension/CGAL/algorithm.h
STL_Extension/doc/STL_Extension/STL_Extension.txt
Solver_interface/doc/Solver_interface/Solver_interface.txt
Solver_interface/include/CGAL/Mixed_integer_program_traits.h
Spatial_searching/doc/Spatial_searching/Spatial_searching.txt
Stream_support/doc/Stream_support/File_formats/Supported_file_formats.txt
Surface_mesh/doc/Surface_mesh/Surface_mesh.txt
Triangulation_3/doc/Triangulation_3/Triangulation_3.txt

The link checker gave a number of redirects and incorrect links.
- the redirects have been solved as far as possible
- the incorrect links have been checked and corrected where possible, others  have been reported through issues;
Fixes #5755

Correction of hyperlinks

---

Surface_mesh/doc/Surface_mesh/Surface_mesh.txt

Remove a broken link.
Fix #5755

Remove a broken link

---

Interpolation/doc/Interpolation/Interpolation.txt

* Affected package(s): `Interpolation`
* Issue(s) solved (if any): fix #5749

Fix broken section link

---

Nef_S2/include/CGAL/Nef_S2/Sphere_segment.h

This PR just removes some of the code duplication in Sphere_segment. ( It's what I was looking at when I came across #5684 )
* Affected package(s): Nef_3/Nef_S2

Nef 3 cleanup sphere segment

---

Apollonius_graph_2/include/CGAL/Parabola_2.h

Self-explanatory. The class is undocumented.
+ don't copy needlessly

Add a getter for the origin of the parabola

---

Alpha_shapes_2/doc/Alpha_shapes_2/Concepts/AlphaShapeTraits_2.h
Alpha_shapes_2/doc/Alpha_shapes_2/Concepts/WeightedAlphaShapeTraits_2.h
Alpha_shapes_3/doc/Alpha_shapes_3/Concepts/AlphaShapeTraits_3.h
Alpha_shapes_3/doc/Alpha_shapes_3/Concepts/FixedAlphaShapeTraits_3.h
Alpha_shapes_3/doc/Alpha_shapes_3/Concepts/FixedWeightedAlphaShapeTraits_3.h
Alpha_shapes_3/doc/Alpha_shapes_3/Concepts/WeightedAlphaShapeTraits_3.h

As reported by @efifogel on cgal-dev.
* Affected package(s): `Alpha_shape_23`

Fix inheritance for periodic triangulations in Alpha Shapes concepts

---

Documentation/doc/Documentation/Getting_started.txt
Documentation/doc/Documentation/Third_party.txt
Documentation/doc/Documentation/advanced/Configuration_variables.txt
Documentation/doc/Documentation/advanced/Installation.txt
Installation/CHANGES.md

Add an entry in CHANGES and update the doc about configuration and installation.
* Affected package(s):Installation, Documentation
* Issue(s) solved (if any): fix #5798

Announce CGAL drop of not-header-only support

---

Triangulation_on_sphere_2/doc/Triangulation_on_sphere_2/Triangulation_on_sphere_2.txt

Funding acknowledgement for the package

---

Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp

Add a pop-up to ask if the user wants to export the internal properties in the off plugin.

Polyhedron Demo: Popup for OFF

---

Nef_3/include/CGAL/Nef_3/K3_tree.h
Nef_3/include/CGAL/Nef_3/SNC_point_locator.h

This PR removes the `update` functions in the SNC_point_locator class, these are virtual functions for which the base class already has code commented out.
In addition, the `bytes` and `leafs` functions are removed from K3_tree as these are not used.
Finally, the class `Objects_around_box` and code which references it, that is commented out is removed.

Remove dead code in SNC_point_locator and K3_tree

---

Triangulation_2/include/CGAL/Triangulation_2/internal/Triangulation_2_projection_traits_base_3.h
Triangulation_2/test/Triangulation_2/test_cdt_2_projection_traits_special_case.cpp

Clean the `Intersect_2` functor and add the case of overlap between segments

Clean Intersect_2 in Triangulation_2_projection_traits_3

---

.github/workflows/build_doc.yml

Add missing error text in cases the build job returns 1.

Documentation tool: Add missing error messages

---

.github/workflows/build_doc.yml

Fix error in doc tool

---

.github/workflows/build_doc.yml

Doc tool fix

---

Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h

PMP: Minor comment fixes

---

Stream_support/doc/Stream_support/IOstream.txt

Fix doc: constants -> functions

---

BGL/test/BGL/test_split.cpp

Fix may-be-used-uninitialized warning

---

Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h
Surface_mesh/test/Surface_mesh/colored_tetra.ply

Aligned Edge property to PLY standard

---

BGL/test/BGL/data/colored_tetra.ply
BGL/test/BGL/data/invalid_cut.ply
BGL/test/BGL/data/invalid_nv.ply
Stream_support/test/Stream_support/data/colored_tetra.ply
Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h

Update PLY files to valid format

---

Polyhedron/demo/Polyhedron/Scene_plane_item.cpp

Polyhedron Demo: Scene_plane_item

---

Documentation/doc/Documentation/packages.txt
Optimal_bounding_box/include/CGAL/Optimal_bounding_box/internal/optimize_2.h
Optimal_bounding_box/include/CGAL/Optimal_bounding_box/oriented_bounding_box.h
Optimal_bounding_box/package_info/Optimal_bounding_box/dependencies

Move the package to "Geometric Optimization".
* Affected package(s): `Optimal_bounding_box`
* Issue(s) solved (if any): fix #5910

OBB: Change package category

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Visitor.h

Pick bug fixes from #5049 
When merged into master, changes from master should be kept.

Bug fixes cherry picked from #5049

---

.github/workflows/filter_testsuite.yml

Change owner to sloriot and lrineau
replaces #5942

Filter testsuite update

---

Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PCA/MeshOnGrid_dialog.ui

Add a check-box to create all the grid in a single item

Polyhedron Demo: SM's grid in a single item

---

BGL/include/CGAL/boost/graph/Named_function_parameters.h
BGL/test/BGL/test_cgal_bgl_named_params.cpp

Allow non-copyable object to be passed as parameters

Improvement for named parameters

---

Polygonal_surface_reconstruction/include/CGAL/internal/compute_confidences.h

fixed the minor bug mentioned in issue #5924
Release Management
Affected package(s):
Issue(s) solved (if any): fix Bug in compute_confidences.h #5924
Feature/Small Feature (if any): Polygonal_surface_reconstruction

bug fix for issue #5924

---

Convex_hull_3/include/CGAL/convex_hull_3.h
Filtered_kernel/include/CGAL/Filtered_construction.h
Filtered_kernel/include/CGAL/Filtered_predicate.h
Filtered_kernel/include/CGAL/Filtered_predicate_with_state.h
Filtered_kernel/include/CGAL/Lazy.h
Nef_2/include/CGAL/Filtered_extended_homogeneous.h
NewKernel_d/include/CGAL/NewKernel_d/Cartesian_filter_NT.h
NewKernel_d/include/CGAL/NewKernel_d/Filtered_predicate2.h
NewKernel_d/include/CGAL/NewKernel_d/Lazy_cartesian.h
Skin_surface_3/include/CGAL/Skin_surface_base_3.h
Skin_surface_3/include/CGAL/triangulate_mixed_complex_3.h
Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_builder_traits_2_aux.h

Thoses changes should have been done when the code was modified for
CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG

Make sure the rounding mode is restored when doing exact computations (5.2)

---

.github/workflows/build_doc.yml
.github/workflows/filter_testsuite.yml

* Affected package(s): - 
* Issue(s) solved (if any): - 
* License and copyright ownership: -

Minor automated message improvements

---

CGAL_Core/include/CGAL/CORE/BigFloat_impl.h

In case there is a read error we have to relase the memory.
* Affected package(s): CGAL_CORE

CORE:  Fix memory leak

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h
Polygon_mesh_processing/test/Polygon_mesh_processing/test_remove_caps_needles.cpp

Addition to non-documented function
Depends on #5945

Add a filter in function to remove caps/needle

---

Kernel_d/include/CGAL/Kernel_d/Segment_d.h
Number_types/include/CGAL/CORE_BigFloat.h
Number_types/include/CGAL/CORE_BigInt.h
Number_types/include/CGAL/CORE_BigRat.h
Number_types/include/CGAL/CORE_Expr.h
Number_types/include/CGAL/Gmpq.h
Number_types/include/CGAL/Gmpz.h
Number_types/include/CGAL/Gmpzf.h
Skin_surface_3/include/CGAL/make_union_of_balls_3.h

Remove self-include directives

---

Intersections_2/include/CGAL/Intersections_2/Iso_rectangle_2_Line_2.h
Intersections_2/include/CGAL/Intersections_2/Iso_rectangle_2_Ray_2.h
Intersections_2/include/CGAL/Intersections_2/Iso_rectangle_2_Segment_2.h
Intersections_2/include/CGAL/Intersections_2/Line_2_Line_2.h
Intersections_2/include/CGAL/Intersections_2/Line_2_Ray_2.h
Intersections_2/include/CGAL/Intersections_2/Line_2_Segment_2.h
Intersections_2/include/CGAL/Intersections_2/Line_2_Triangle_2.h
Intersections_2/include/CGAL/Intersections_2/Point_2_Triangle_2.h
Intersections_2/include/CGAL/Intersections_2/Ray_2_Ray_2.h
Intersections_2/include/CGAL/Intersections_2/Ray_2_Segment_2.h
Intersections_2/include/CGAL/Intersections_2/Ray_2_Triangle_2.h
Intersections_2/include/CGAL/Intersections_2/Segment_2_Segment_2.h
Intersections_2/include/CGAL/Intersections_2/Segment_2_Triangle_2.h
Intersections_2/include/CGAL/Intersections_2/internal/Triangle_2_Triangle_2_intersection_impl.h

Avoid extra bool by relying on enum

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/detect_features.h
Polygon_mesh_processing/test/Polygon_mesh_processing/test_detect_features.cpp

Avoid computing square roots (cuts the runtime by more than half), const-correctness, properly use the VPM & GT, indentation, etc.

Enhancements & fixes for PMP::detect_features

---

BGL/include/CGAL/boost/graph/IO/PLY.h
BGL/include/CGAL/boost/graph/IO/STL.h
Point_set_3/include/CGAL/Point_set_3/IO.h
Point_set_3/include/CGAL/Point_set_3/IO/LAS.h
Point_set_3/include/CGAL/Point_set_3/IO/PLY.h
Point_set_processing_3/include/CGAL/IO/read_las_points.h
Point_set_processing_3/include/CGAL/IO/read_ply_points.h
Point_set_processing_3/include/CGAL/IO/write_las_points.h
Point_set_processing_3/include/CGAL/IO/write_ply_points.h
Stream_support/doc/Stream_support/IOstream.txt
Stream_support/doc/Stream_support/PackageDescription.txt
Stream_support/include/CGAL/IO/PLY.h
Stream_support/include/CGAL/IO/STL.h
Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h

* Affected package(s): `BGL`, `PSP3`, `Stream_support`

CGAL IO: Clarify binary warning

---

Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Conic_x_monotone_arc_2.h
GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h
GraphicsView/include/CGAL/Qt/qglviewer.h
GraphicsView/include/CGAL/Qt/qglviewer_impl.h
Homogeneous_kernel/include/CGAL/Homogeneous/SphereH3.h
Homogeneous_kernel/include/CGAL/Homogeneous/function_objects.h
Polyhedron/demo/Polyhedron/MainWindow.cpp
Polyhedron/demo/Polyhedron/Viewer.cpp
Surface_mesh_topology/include/CGAL/draw_face_graph_with_paths.h
Triangulation_3/demo/Triangulation_3/PreferenceDlg.cpp
Triangulation_3/demo/Triangulation_3/Viewer.cpp

-Wdeprecated-enum-enum-conversion

Fix warnings about arithmetic operations on enum

---

BGL/include/CGAL/boost/graph/Named_function_parameters.h
Scripts/developer_scripts/test_merge_of_branch

Note the check should fail otherwise the script does not work

Add a new test for documented named parameters

---

Installation/CHANGES.md

Add changes that were missing in PR #5597 

Mesh_3 weighted images - add changes

---

Installation/CHANGES.md

We might want to put it at the top as it's a big announcement.

Mention mt safety

---

Arrangement_on_surface_2/include/CGAL/Arr_dcel_base.h
STL_Extension/include/CGAL/Compact_container.h
STL_Extension/include/CGAL/Concurrent_compact_container.h

Fix issues with new containers for arrangement cells

---

Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Conic_x_monotone_arc_2.h
CGAL_Core/include/CGAL/CORE/BigFloatRep.h
Installation/include/CGAL/Installation/internal/enable_third_party_libraries.h
NewKernel_d/include/CGAL/NewKernel_d/LA_eigen/constructors.h
Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Scene_utils.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/AABB_traversal_traits_with_Hausdorff_distance.h
Polyhedron/demo/Polyhedron/include/CGAL/Polyhedron_kernel.h
Stream_support/include/CGAL/IO/OFF/generic_copy_OFF.h
Three/include/CGAL/Three/exceptions.h

Put parenthesis around calls to `Bbbox_3::min()` and `max() `.
* Issue(s) solved (if any): fix #6108

PMP: Fix Warnings in Master

---

Boolean_set_operations_2/include/CGAL/draw_polygon_set_2.h
Linear_cell_complex/include/CGAL/draw_linear_cell_complex.h
Nef_3/include/CGAL/draw_nef_3.h
Periodic_2_triangulation_2/include/CGAL/draw_periodic_2_triangulation_2.h
Point_set_3/include/CGAL/draw_point_set_3.h
Polygon/include/CGAL/draw_polygon_2.h
Polygon/include/CGAL/draw_polygon_with_holes_2.h
Polyhedron/include/CGAL/draw_polyhedron.h
Straight_skeleton_2/include/CGAL/draw_straight_skeleton_2.h
Surface_mesh/examples/Surface_mesh/draw_surface_mesh_small_faces.h
Surface_mesh/include/CGAL/draw_surface_mesh.h
Surface_mesh_topology/include/CGAL/draw_face_graph_with_paths.h
Triangulation_2/include/CGAL/draw_triangulation_2.h
Triangulation_3/include/CGAL/draw_triangulation_3.h
Voronoi_diagram_2/include/CGAL/draw_voronoi_diagram_2.h

Remove -old parameter for Polyhedron_3 draw.
* Issue(s) solved (if any): fix #6099

Remove -old option for Polyhedron_3 draw

---

Barycentric_coordinates_2/doc/Barycentric_coordinates_2/Concepts/DiscretizedDomain_2.h
Heat_method_3/doc/Heat_method_3/PackageDescription.txt
Installation/CHANGES.md
Weights/doc/Weights/PackageDescription.txt
Weights/doc/Weights/Weights.txt

Preview: https://github.com/MaelRL/cgal/blob/CGAL-Prepare_changes.md-5.4-GF/Installation/CHANGES.md

Prepare CHANGES.md for 5.4

---

Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/internal/validity.h

Fix ambiguity in function signature

---

BGL/include/CGAL/boost/graph/METIS/partition_dual_graph.h
BGL/include/CGAL/boost/graph/METIS/partition_graph.h

* Issue(s) solved (if any): fix #5410

Fix conversion error in METIS wrappers

---

BGL/include/CGAL/boost/graph/Euler_operations.h
BGL/test/BGL/CMakeLists.txt
BGL/test/BGL/test_Collapse_edge_with_constraints.cpp

also added a test for the function testing all possible branches.

Fix collapse_edge bug when both edges to remove are constrained edges

---

Nef_3/include/CGAL/Nef_polyhedron_3.h
Nef_3/test/Nef_3/test_nef_3_operator.cpp

Fix a reported issue.
* Issue(s) solved (if any): fix #6151

Nef_3: Fix broken greater-than

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h

This will workaround issue with boundary non-manifold vertices

Apply the operations per patches

---

Mesh_3/include/CGAL/Mesh_triangulation_3.h

* Affected package(s): `Mesh_3`
* Issue(s) solved (if any): fix #6194

Fix: remove extra ';'

---

Mesh_3/doc/Mesh_3/Mesh_3.txt

Mesh_3 doc warnings

---

Surface_mesh_approximation/include/CGAL/Variational_shape_approximation.h

Fix infinite loop in case no proxy could be added  error threshold is not yet reached

Fix infinite loop

---

Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h

Fix of typos, wording, order of parameters.
* Affected package(s): Advancing_front_surface_reconstruction

Advancing Front Surface Reconstruction: Fixes in the doc.

---

BGL/include/CGAL/boost/graph/parameters_interface.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_distance.cpp

Add random generator np for sampling

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/helper.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap.h

modification on an internal function

Add visitor function call for tracking faces split

---

Convex_hull_3/test/Convex_hull_3/quickhull_degenerate_test_3.cpp

Fixes 
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-12/Convex_hull_3/TestReport_lrineau_Ubuntu-Latest.gz
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-136/Convex_hull_3/TestReport_lrineau_ArchLinux-CXX14.gz

Convex hull can also be a triangle

---

STL_Extension/test/STL_Extension/test_Uncertain.cpp

Remove conditional code as the flag has disappeared

---

Combinatorial_map/include/CGAL/Combinatorial_map_functors.h

Remove warning
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-141/BGL/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz
* Affected package(s): Combinatorial Map

CMap remove a warning

---

Advancing_front_surface_reconstruction/examples/Advancing_front_surface_reconstruction/reconstruction_surface_mesh.cpp

Advancing Front Reconstruction: Remove unused variable in example

---

Convex_hull_3/include/CGAL/Convex_hull_face_base_2.h
Convex_hull_3/include/CGAL/Convex_hull_vertex_base_2.h
Convex_hull_3/include/CGAL/convex_hull_3.h

Fix info type and set default value

---

Principal_component_analysis/include/CGAL/linear_least_squares_fitting_circles_2.h
Principal_component_analysis/include/CGAL/linear_least_squares_fitting_points_2.h
Principal_component_analysis/include/CGAL/linear_least_squares_fitting_rectangles_2.h
Principal_component_analysis/include/CGAL/linear_least_squares_fitting_segments_2.h
Principal_component_analysis/include/CGAL/linear_least_squares_fitting_triangles_2.h

Simplified a few expressions
* Affected package(s): Principal_component_analysis

Simplified expressions

---

Spatial_searching/include/CGAL/Manhattan_distance_iso_box_point.h

Fix a warning in this [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-I-9/Spatial_searching_Examples/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz)

Spatial_searching: Add a variable as we had a warning about a potentially dangling pointer

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_self_intersections.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/smooth_mesh.h

Some fixes and improvements for PMP::remove_self_intersections

PMP::remove_self_intersections improvements

---

Algebraic_foundations/test/Algebraic_foundations/Chinese_remainder_traits.cpp
BGL/include/CGAL/boost/graph/Seam_mesh.h
BGL/include/CGAL/boost/graph/selection.h
Combinatorial_map/include/CGAL/Combinatorial_map.h
Generalized_map/include/CGAL/Generalized_map.h
GraphicsView/include/CGAL/Buffer_for_vao.h
GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h
Hyperbolic_triangulation_2/include/CGAL/Hyperbolic_triangulation_2/internal/Hyperbolic_Delaunay_triangulation_traits_2_functions.h
Linear_cell_complex/include/CGAL/Linear_cell_complex_base.h
Linear_cell_complex/include/CGAL/Linear_cell_complex_constructors.h
Linear_cell_complex/include/CGAL/Linear_cell_complex_incremental_builder.h
Linear_cell_complex/include/CGAL/Linear_cell_complex_operations.h
Linear_cell_complex/include/CGAL/boost/graph/graph_traits_Linear_cell_complex_for_combinatorial_map.h
Modifier/test/Modifier/test_modifier.cpp
Nef_3/include/CGAL/draw_nef_3.h
Point_set_3/include/CGAL/Point_set_3.h
Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h
Polyhedron/test/Polyhedron/test_polyhedron.cpp
Polynomial/test/Polynomial/include/CGAL/gen_sparse_polynomial.h
STL_Extension/include/CGAL/Compact_container.h
STL_Extension/include/CGAL/Concurrent_compact_container.h
STL_Extension/include/CGAL/STL_Extension/internal/boost/relaxed_heap.hpp
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Square_border_parameterizer_3.h
Surface_mesh_topology/include/CGAL/Face_graph_wrapper.h
Surface_mesh_topology/include/CGAL/Surface_mesh_topology/internal/Path_generators.h
Surface_mesh_topology/include/CGAL/draw_face_graph_with_paths.h

CGAL: In testcode do not use CGAL_assertion but assert 

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h

Tiny doc fixes for PMP Hausdorff distance functions

---

Mesh_3/include/CGAL/Mesh_3/experimental/Get_facet_patch_id.h
Mesh_3/include/CGAL/Mesh_3/experimental/Lipschitz_sizing_experimental.h

This PR fixes two minor bugs in Mesh_3 experimental headers

Mesh 3 experimental - minor fixes

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_self_intersections.h

fix compilation with Polyhedron_3

PMP - BGLize repair code

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/repair_extra.h

* Issue(s) solved (if any): fix #6337

Make collect_close_stitchable_boundary_edges() compatible with EPECK

---

Intersections_3/include/CGAL/Intersections_3/internal/Iso_cuboid_3_Plane_3_intersection.h
Intersections_3/include/CGAL/Intersections_3/internal/Tetrahedron_3_Plane_3_intersection.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h

Add missing static keyword

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Output_builder_for_autorefinement.h
Polygon_mesh_processing/test/Polygon_mesh_processing/test_autorefinement.cmd

Relates to issue reveled by  #6209

Never try to fix when a polyline does not split a patch

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/AABB_traversal_traits_with_Hausdorff_distance.h
Polygon_mesh_processing/test/Polygon_mesh_processing/test_hausdorff_bounded_error_distance.cpp

Diff without the first commit that fixes indentation: https://github.com/MaelRL/cgal/compare/e12f9febe88e42ecc20859770f14310432434dca..4c1df5eea75d8a7825e3f9fbc941e5faa560f59f?w=1

Fixes for bounded Hausdorff computations

---

Convex_hull_3/doc/Convex_hull_3/CGAL/convex_hull_3.h
Surface_mesh_simplification/doc/Surface_mesh_simplification/CGAL/Surface_mesh_simplification/edge_collapse.h

Non-inlined doc NP update

---

Kernel_23/doc/Kernel_23/Kernel_23.txt

We already say 5 a few lines below.

Consistent count in the doc

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h

See meaning of the word ["Indexation"](https://en.wikipedia.org/wiki/Indexation)

PMP:  Doc Indexation -> Indexing

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Visitor.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_nodes.h

This makes sure all vertices that must be identical have the same point

Handle the update of points  for autorefinement

---

Documentation/doc/Documentation/Developer_manual/Chapter_code_format.txt

remove deprecated recommendation

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h

* Issue(s) solved (if any): fix #6369

Fix not using / forwarding traits

---

Generator/include/CGAL/random_convex_hull_in_disc_2.h

Address [this ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-41/Generator/TestReport_gimeno_ArchLinux-clang.gz) warning, 

Generator: Remove unused variable

---

Alpha_shapes_2/doc/Alpha_shapes_2/Alpha_shapes_2.txt
Alpha_shapes_3/doc/Alpha_shapes_3/Alpha_shapes_3.txt

The address `http://gudhi.gforge.inria.fr` does not exist and should be `https://gudhi.inria.fr`

Incorrect link to Gudhi project

---

Spatial_sorting/examples/Spatial_sorting/sp_sort_using_property_map_2.cpp
Spatial_sorting/examples/Spatial_sorting/sp_sort_using_property_map_3.cpp
Spatial_sorting/examples/Spatial_sorting/sp_sort_using_property_map_d.cpp
Spatial_sorting/include/CGAL/Hilbert_sort_median_2.h
Spatial_sorting/include/CGAL/Hilbert_sort_median_3.h
Spatial_sorting/include/CGAL/Hilbert_sort_median_d.h
Spatial_sorting/include/CGAL/Hilbert_sort_middle_2.h
Spatial_sorting/include/CGAL/Hilbert_sort_middle_3.h
Spatial_sorting/include/CGAL/Hilbert_sort_middle_d.h
Spatial_sorting/include/CGAL/Spatial_sort_traits_adapter_2.h
Spatial_sorting/include/CGAL/Spatial_sort_traits_adapter_3.h
Spatial_sorting/include/CGAL/Spatial_sort_traits_adapter_d.h

Fix traits adapters

---

Triangulation_2/doc/Triangulation_2/examples.txt

Add an example that already exists to this [list of examples](https://cgal.geometryfactory.com/CGAL/doc/master/Triangulation_2/examples.html)

Triangulation_2: Add example file to list of examples

---

Spatial_sorting/include/CGAL/Hilbert_sort_middle_2.h

do not use default constructed kernel

---

Hash_map/include/CGAL/Hash_map/internal/chained_map.h
Hash_map/include/CGAL/Tools/chained_map.h
Hash_map/include/CGAL/Unique_hash_map.h

I guess it should replace #6474 
@afabri, with and without the tss should be benched.
Each commit contains a unique change.

Simplify code and make it read-only thread safe

---

Triangulation_2/TODO

Typo fix.
* Affected package(s): `Triangulation_2`

Typo fix in Triangulation_2/TODO

---

Filtered_kernel/include/CGAL/Lazy.h
Number_types/include/CGAL/Interval_nt.h

Default constructed Interval_nt is the invalid interval (1,0). When we construct an interval with 2 explicit bounds, we check its validity. Lazy_rep (the version with 2 atomic_double) deconstructs and reconstructs intervals all the time, so even copying an interval triggers the assertion --> disable it.
As far as I can tell, this is only an issue with an assertion in debug mode, release mode was fine.
* Affected package(s): Number_types, Filtered_kernel
* Issue(s) solved (if any): fix #6491 (partially)

Don't check interval validity in Lazy_rep

---

BGL/include/CGAL/boost/graph/internal/Has_member_clear.h
BGL/include/CGAL/boost/graph/internal/Has_member_id.h
BGL/test/BGL/test_Has_member_clear.cpp

Followup to https://github.com/CGAL/cgal/pull/6461/commits/6260d5a4e47f891deb6cd8eed47d4b73a88ae884. See also https://github.com/CGAL/cgal/pull/6461#discussion_r839550495 and following comments.
* Affected package(s): STL_Extension

New implementation for Has_member_*

---

Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h
Surface_mesh/include/CGAL/Surface_mesh/Properties.h
Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Surface_mesh/test/Surface_mesh/SM_common.h
Surface_mesh/test/Surface_mesh/surface_mesh_test.cpp

Surface_mesh: Add move semantics

---

Stream_support/include/CGAL/IO/OFF/File_scanner_OFF.h

Fix https://github.com/CGAL/cgal/issues/6491#issuecomment-1111095399.
Fix #6491.
* Affected package(s): Stream_support

Stream_support File_Scanner_OFF: Add #include vector

---

Mesh_3/doc/Mesh_3/Mesh_3.txt

issue #6539 Mesh3: unreachable page of ircad

---

Surface_mesh_skeletonization/doc/Surface_mesh_skeletonization/examples.txt
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/CMakeLists.txt
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_om_example.cpp

Add an example that uses OpenMesh as input.
* Affected package(s): Surface_mesh_skeleton

Surface_mesh_skeleton: Add example

---

BGL/doc/BGL/PackageDescription.txt

Fix broken BGL ref manual link

---

Documentation/doc/scripts/html_output_post_processing.py

Fix issue like [here](https://doc.cgal.org/latest/Polygon/classCGAL_1_1Polygon__2.html#aacf55ebc4ccb144496b1aae6b867ef5e)

Workaround issue with pyquery

---

Solver_interface/include/CGAL/Eigen_svd.h
Surface_mesh_deformation/benchmark/Surface_mesh_deformation/optimal_rotation/optimal_rotation_polar_eigen.cpp
Surface_mesh_deformation/benchmark/Surface_mesh_deformation/optimal_rotation/optimal_rotation_svd_eigen.cpp
Surface_mesh_deformation/include/CGAL/Deformation_Eigen_closest_rotation_traits_3.h

Moved parameters from compute method to class template.
* Affected package(s): Surface_mesh_deformation

Fixed Eigen3 3.4.90 deprecation warnings

---

Documentation/doc/Documentation/Developer_manual/Chapter_namespaces.txt

- correcting permanent redirect
- improve readability

Redirect and readability

---

AABB_tree/include/CGAL/AABB_tree.h
Orthtree/include/CGAL/Orthtree.h
Poisson_surface_reconstruction_3/include/CGAL/Poisson_reconstruction_function.h
Poisson_surface_reconstruction_3/include/CGAL/Reconstruction_triangulation_3.h
Poisson_surface_reconstruction_3/include/CGAL/poisson_refine_triangulation.h
Polyhedron/include/CGAL/Polyhedron_3.h
Surface_mesh_approximation/include/CGAL/Variational_shape_approximation.h
Surface_mesher/include/CGAL/IO/output_surface_facets_to_polyhedron.h

Address Issue #6583, #6584,  and #6585 
* Affected package(s): Poisson Surface Reconstruction,  Polyhedron_3
* Issue(s) solved (if any): fix #6583, #6584, #6585

Fix doxygen warnings

---

Triangulation_2/test/Triangulation_2/issue_5055.cpp

Add the testcase of issue #5055, so that we can actually test it fully on all the test platforms.
* Issue(s) solved (if any): fix #5055 (if the test is fine)

Triangulation_2: Add testcase of issue #5055

---

Surface_mesh_simplification/examples/Surface_mesh_simplification/CMakeLists.txt
Surface_mesh_simplification/examples/Surface_mesh_simplification/collapse_small_edges_in_parallel.cpp

instead of having it somewhere locally, it is better shipped with CGAL...

add an example to simplify a mesh in parallel

---

Arrangement_on_surface_2/include/CGAL/Arr_dcel_base.h
Arrangement_on_surface_2/include/CGAL/Arrangement_on_surface_2.h

Some regressions are observed in multithreaded env
Should fix #6293

Disable boost pool allocator

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h

Add face_patch_map to split_long_edges

---

Arrangement_on_surface_2/include/CGAL/Arr_segment_traits_2.h

Arrangement: Fix comment in Arr_segment_traits

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h

improve doc + add an early quit to avoid building the AABB-tree when we reached the last level of the hierarchy

Better doc + early quit

---

Nef_3/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h
Nef_3/include/CGAL/Nef_polyhedron_3.h
Nef_3/test/Nef_3/test_nef_3_io_EPEC.cpp
Nef_3/test/Nef_3/test_nef_3_operator.cpp

Nef_3, conversion from Polyhedron_3 to Nef_3: fix constness and index maps

---

Bounding_volumes/doc/Bounding_volumes/CGAL/Approximate_min_ellipsoid_d.h
Bounding_volumes/include/CGAL/Approximate_min_ellipsoid_d.h
Bounding_volumes/include/CGAL/Approximate_min_ellipsoid_d/Khachiyan_approximation_impl.h
Bounding_volumes/test/Bounding_volumes/issue6626.cpp

Fix Issue #6626
typo: axes -> axis  
* Affected package(s): Bounding_volumes

Bounding_volumes: Fix zero volume ellipsoid bug (and a typo)

---

Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangle.h
Polygon_mesh_processing/test/Polygon_mesh_processing/CMakeLists.txt
Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_triangle.cpp

Add a convenience function to obtain a triangle for a face.

PMP::Add function triangle(face_descriptor, tmesh)

---

Bounding_volumes/test/Bounding_volumes/min_sphere_test.cpp
Number_types/include/CGAL/NT_converter.h

Fix forward declaration living in the wrong namespace

---

Scripts/developer_scripts/autotest_cgal
Scripts/developer_scripts/detect_wrong_encoding
Scripts/developer_scripts/run_testsuite_from_branch_name.sh
Scripts/developer_scripts/test_merge_of_branch
Scripts/scripts/cgal_create_CMakeLists
Scripts/scripts/cgal_create_cmake_script
Testsuite/test/run_testsuite_with_cmake

Change `egrep` to `grep -E`. Fix #6710.
* Affected package(s): Scripts, Testsuite
* Issue(s) solved (if any): fix #6710

sed -i -e 's/egrep/grep -E/g'

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h

Checked with https://gist.github.com/MaelRL/1c45432e88451313063e8189af24a3f3.
* Issue(s) solved (if any): fix #6715

Add proper traits usage to PMP::stitch_borders

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h

Add proper traits usage to PMP::stitch_borders - 5.5 version

---

GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h

Update the basic viewer to set camera mode in 2D earlier
TODO: please @efifogel could you test and tell me if this solves your bug?
* Issue(s) solved (if any): maybe fix #6722

Update basic viewer to set camera mode earlier (following Efi issue)

---

Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_np_function.cpp
STL_Extension/include/CGAL/Named_function_parameters.h

Add an example for default vector normal map

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h

Minor improvement to PMP split documentation.
* Issue(s) solved (if any): fix #6765

Improve PMP::split documentation

---

GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h

Fix copy/paste error

---

Documentation/doc/resources/1.9.3/BaseDoxyfile.in

Replacing the doxygen obsolete settings with the new settings

Replacing OBSOLETE doxygen settings

---

Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Iterative_authalic_parameterizer_3.h

Change to `CGAL_DEBUG_IA` as requested by @lrineau  in a previous PR that got already merged.

Parameterization:  Scope name of a #define

---

Alpha_wrap_3/doc/Alpha_wrap_3/alpha_wrap_3.txt
Alpha_wrap_3/doc/Alpha_wrap_3/examples.txt
Alpha_wrap_3/examples/Alpha_wrap_3/CMakeLists.txt
Alpha_wrap_3/examples/Alpha_wrap_3/triangle_soup_wrap.cpp

Add an example for triangle soup wrapping.
* Affected package(s): `3D Alpha Wrap`

Add triangle soup wrap example for alpha wrap

---

STL_Extension/include/CGAL/STL_Extension/internal/boost/relaxed_heap.hpp
Surface_mesh_simplification/test/Surface_mesh_simplification/edge_collapse_topology.cpp

SMS test relaxed order

---

Polyhedron/demo/Polyhedron/Plugins/PMP/Corefinement_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Offset_meshing_plugin.cpp
Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp

Don't create a new item if the Boolean operation was not successful. 
Make input polyhedra invisible after Boolean operation.
* Issue(s) solved (if any): partially #6690

Polyhedron Demo: Make input invisible after Boolean operation

---

Intersections_3/include/CGAL/Intersections_3/internal/Tetrahedron_3_Triangle_3_intersection.h
Intersections_3/test/Intersections_3/test_intersections_Tetrahedron_3.cpp

Easier version to maintain that is also fixing #6777
As the implementation is a new one I'm not sure we can backport it to release branches. @lrineau what do you think?

Simpler implementation of Tet vs. Tri intersection

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h

Fixes #6757 
@SLopezBRGM Please let me know if this does fix your use case. I used `before/after_vertex_copy()` for vertex duplication

add missing visitor calls in PMP::split()

---

Triangulation_2/include/CGAL/Triangulation_2.h
Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_triangulation_2.h
Triangulation_3/include/CGAL/Triangulation_3.h
Triangulation_3/test/Triangulation_3/include/CGAL/_test_cls_triangulation_3.h

* Affected package(s): `Triangulation_23`

Improvements for Triangulation_23 comparison operators

---

GraphicsView/include/CGAL/Qt/qglviewer_impl.h
Polyhedron/demo/Polyhedron/Polyhedron_3.qrc
Polyhedron/demo/Polyhedron/Viewer.cpp
Polyhedron/demo/Polyhedron/resources/compatibility_shaders/shader_c3t3_spheres.frag
Polyhedron/demo/Polyhedron/resources/shader_c3t3_spheres.frag

This is a possible replacement (to be tested) of PR #6784.
@janetournois Can you please check if that solves the issue on your machine?
* Issue(s) solved (if any): replaces #6784

Polyhedron demo - Fix the display of protecting balls (second version)

---

Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Algebraic_curve_kernel_2.h
Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Xy_coordinate_2.h
Arrangement_on_surface_2/include/CGAL/Arr_point_location/Arr_walk_along_line_pl_impl.h
Arrangement_on_surface_2/include/CGAL/Arr_walk_along_line_point_location.h
Boolean_set_operations_2/include/CGAL/connect_holes.h
Bounding_volumes/include/CGAL/Approximate_min_ellipsoid_d/Khachiyan_approximation.h
Bounding_volumes/include/CGAL/Approximate_min_ellipsoid_d/Khachiyan_approximation_impl.h
CGAL_Core/include/CGAL/CORE/BigFloat_impl.h
CGAL_Core/include/CGAL/CORE/ExprRep.h
CGAL_Core/include/CGAL/CORE/Real_impl.h

Some obvious missing quotes and typos

Some obvious missing quotes and typos

---

Installation/LICENSE
Jet_fitting_3/examples/Jet_fitting_3/README
Nef_3/include/CGAL/Nef_3/Edge_edge_overlay.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orient_polygon_soup.h
Stream_support/include/CGAL/IO/PLY.h

Some obvious missing quotes  (last set)

Some obvious missing quotes

---

Generator/doc/Generator/CGAL/Random.h
Generator/doc/Generator/CGAL/point_generators_2.h
Generator/doc/Generator/Concepts/CombinationElement.h
STL_Extension/doc/STL_Extension/CGAL/algorithm.h

Fix typos.
* Issue(s) solved (if any): fix #6885

Generator: Fix links

---

Kernel_d/doc/Kernel_d/Concepts/LinearAlgebraTraits_d.h
Kernel_d/doc/Kernel_d/Concepts/Matrix.h
Kernel_d/doc/Kernel_d/Concepts/Vector.h

Kernel_d: Incorrect documentation

---

Linear_cell_complex/examples/Linear_cell_complex/plane_graph_to_lcc_2.cpp
Surface_mesh_simplification/doc/Surface_mesh_simplification/Surface_mesh_simplification.txt

Obvious spelling error: betwen -> between

Obvious spelling error

---

Polytope_distance_d/doc/Polytope_distance_d/Concepts/WidthTraits_3.h
Polytope_distance_d/doc/Polytope_distance_d/dependencies

* Affected package(s): `Polytope_distance_d`
* Issue(s) solved (if any): fix #6904, fix #6905

Optimal Distances: tiny doc fixes

---

Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_progress.cpp
Polyhedron/include/CGAL/Polyhedron_3.h
Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h

PMP corefinement: add convenience functions and fix visitor

---

BGL/include/CGAL/boost/graph/selection.h
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/fair.h

@lrineau you might just look at the diff and merge without testing.
* Affected package(s):  BGL, Polygon_mesh_processing

Fixed typo:  shrinked -> shrunk

---

Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
Polygon_mesh_processing/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp

fix wording. too trivial for a testsuite.

Polygon_mesh_processing: reparation -> repairing

---

Polyhedron/demo/Polyhedron/Plugins/IO/VTK_io_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp

This PR adds a reader for *.nrrd files, using `vtkNrrdReader`

Polyhedron demo - add *.nrrd reader for images

---

.github/workflows/build_doc.yml

Fix javascript syntax on build_doc.yml
* Issue(s) solved (if any): #7049

Fix javascript syntax

---

Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_example.cpp
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h

`CGAL_assertion_code` -> `CGAL_warning_code`
* Affected package(s): Polygon Mesh Processing
* Issue(s) solved (if any): fix #7055

Polygon Mesh Processing:  Fix CGAL_assertion_msg

---

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Shortest_path_plugin.cpp

"unamed" ->  "unnamed"
* Issue(s) solved (if any): fix #7051

Polyhedron Demo: unamed

---

Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h
Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction_vertex_base_3.h

* Issue(s) solved (if any): fix #7042

Translate some French error messages / comments

---

CGAL_ImageIO/include/CGAL/IO/read_vtk_image_data.h
CGAL_ImageIO/include/CGAL/Image_3.h
Mesh_3/doc/Mesh_3/CGAL/Image_3.h
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Image_res_dialog.ui
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp

Add the possibility to read a directory with bmp files which are together a voxel image

3d Demo: Try to read bmp files

---

.github/workflows/Remove_labels.yml
.github/workflows/build_doc.yml
.github/workflows/checks.yml
.github/workflows/cmake-all.yml
.github/workflows/delete_doc.yml
.github/workflows/demo.yml
.github/workflows/filter_testsuite.yml

Add workflow_dispatch to trigger actions manually

Add workflow_dispatch to run actions manually

---

.github/workflows/cmake-all.yml

Correcting a typo in `cmake-all.yml`

fix typo in cmake-all workflow

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_self_intersections.h
STL_Extension/include/CGAL/STL_Extension/internal/parameters_interface.h

While providing very good results in some case, it lead to issues in some reported cases. Get back to the behavior in 5.4.

Make smooth an option that is OFF by default

---

GraphicsView/demo/Triangulation_2/Constrained_Delaunay_triangulation_2.cpp
Stream_support/include/CGAL/IO/WKT.h

Instead of only reading one multipolygon the demo can now read files with points, polylines, and mltipolygons.
This PR is WIP as looking at the code there is room for  improvement.

Triangulation_2 Demo: Read files with many WKT entities

---

Installation/CHANGES.md
Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_by_reduced_convolution_2.h

Fixed a bug in Minkowski_sum_2.
In particular, fixed the function get_point_in_face()
* Affected package(s): Minkowski_sim_2
* Issue(s) solved (if any): fix #5830
* Link to compiled documentation (obligatory for small feature): NA
* License and copyright ownership: Tel Aviv Univ.

Minkowski_sim_2: fix missed hole

---

.github/workflows/build_doc.yml
Documentation/doc/scripts/html_output_post_processing.py

Force html output (needed with lxml greater than 4.6.5)

---

Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_X_trapezoid.h
Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_active_edge.h
Arrangement_on_surface_2/include/CGAL/Arr_point_location/Td_active_trapezoid.h
Arrangement_on_surface_2/include/CGAL/Arr_point_location/Trapezoidal_decomposition_2_impl.h
Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/gfx/Curve_renderer_2.h
Jet_fitting_3/examples/Jet_fitting_3/PolyhedralSurf_rings.h
Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h
Ridges_3/examples/Ridges_3/PolyhedralSurf_rings.h
Ridges_3/test/Ridges_3/PolyhedralSurf_rings.h
Spatial_searching/benchmark/Spatial_searching/include/nanoflann.hpp
Spatial_searching/include/CGAL/Incremental_neighbor_search.h
Spatial_searching/include/CGAL/Orthogonal_incremental_neighbor_search.h
Spatial_searching/include/CGAL/Spatial_searching/internal/K_neighbor_search.h
Surface_sweep_2/include/CGAL/Surface_sweep_2/No_overlap_event_base.h
Surface_sweep_2/include/CGAL/Surface_sweep_2/Surface_sweep_2_impl.h

As indicated in #7041 (Spelling corrections) there were still some open corrections in respect to variables / functions, these have been addressed here.

Spelling correction in respect to function / variable names

---

Documentation/doc/biblio/cgal_manual.bib
Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h

Thanks to @hoskillua.
* Issue(s) solved (if any): fix #6486

Improve documentation of PMP::compute_vertex_normal()

---

Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
Mesh_3/test/Mesh_3/CMakeLists.txt
Mesh_3/test/Mesh_3/test_meshing_determinism.cpp
Mesh_3/test/Mesh_3/test_meshing_without_features_determinism.cpp

Add a testcase as suggested in the issue. 
* Issue(s) solved (if any): fix #6958

Mesh_3: Add test for determinism when not checking for features

---

Documentation/doc/Documentation/windows.txt

Corrected slashes in the windows part

issue #7211 Manual bug

---

Intersections_3/include/CGAL/Intersections_3/internal/Triangle_3_Triangle_3_intersection.h

* Affected package(s):  `Intersections_3`

Fix set-but-not-used warning

---

Kernel_23/doc/Kernel_23/CGAL/Aff_transformation_2.h
Kernel_23/doc/Kernel_23/CGAL/Bbox_2.h
Kernel_23/doc/Kernel_23/CGAL/Bbox_3.h
Kernel_23/doc/Kernel_23/CGAL/Circle_2.h
Kernel_23/doc/Kernel_23/CGAL/Circle_3.h
Kernel_23/doc/Kernel_23/CGAL/Direction_2.h
Kernel_23/doc/Kernel_23/CGAL/Direction_3.h
Kernel_23/doc/Kernel_23/CGAL/Iso_cuboid_3.h
Kernel_23/doc/Kernel_23/CGAL/Iso_rectangle_2.h
Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
Kernel_23/doc/Kernel_23/CGAL/Point_2.h
Kernel_23/doc/Kernel_23/CGAL/Point_3.h
Kernel_23/doc/Kernel_23/CGAL/Ray_2.h
Kernel_23/doc/Kernel_23/CGAL/Ray_3.h
Kernel_23/doc/Kernel_23/CGAL/Sphere_3.h
Kernel_23/doc/Kernel_23/CGAL/Vector_2.h
Kernel_23/doc/Kernel_23/CGAL/Vector_3.h
Kernel_23/doc/Kernel_23/CGAL/Weighted_point_2.h
Kernel_23/doc/Kernel_23/CGAL/Weighted_point_3.h
Kernel_23/doc/Kernel_23/CGAL/rational_rotation.h
Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h

Made preconditions in the C++ form.

Kernel_23: inconsistent documentation

---

Arrangement_on_surface_2/include/CGAL/Arr_topology_traits/Arr_spherical_topology_traits_2_impl.h

Spelling corrections

---

GraphicsView/demo/Largest_empty_rect_2/Largest_empty_rectangle_2.cpp
GraphicsView/demo/Largest_empty_rect_2/Largest_empty_rectangle_2.ui

Add the possibility to read a file of 2D points, so that we can visualize the bug report in #7183 and eventually fix.
* Affected package(s): Inscribed_volumes

Largest_empty_iso_rectangle: Improve Demo

---

Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_model_complexity_control.cpp
Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_user_provided_planes.cpp
Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_with_region_growing.cpp
Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_without_input_planes.cpp

This allows developers to test polyfit surface reconstruction algorithm on custom data wihle also being able run as previously intended if no input is given

Modified polyfit examples to take in user input

---

Installation/CHANGES.md

PMP remeshing with Mesh_3 - improve changes.md

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h

Early exit if the mesh is empty

---

Filtered_kernel/include/CGAL/Lazy.h

This fixes the issue previously opened https://github.com/CGAL/cgal/issues/6382 
the main motivation is it's easier for step-through debugging.
* Affected package(s): Lazy_kernel
* Issue(s) solved (if any): #6382
* License and copyright ownership: CGAL Authors

Lazy_kernel: Replace BOOST_PP repeat macros with variadic templates

---

Boolean_set_operations_2/doc/Boolean_set_operations_2/CGAL/Boolean_set_operations_2.h

* Affected package(s): `Boolean_set_operations_2`
* Issue(s) solved (if any): partial fix of #7242 

#7242 issue: interior spelling correction

---

BGL/include/CGAL/boost/graph/IO/polygon_mesh_io.h

Document the named parameter of the function `CGAL::IO::write_polygon_mesh()`
* Affected package(s):  BGL
* Link to compiled documentation:  [link](https://cgal.github.io/7308/v0/BGL/group__PkgBGLIOFct.html#gafa143949a33371dc6df8307be1ab8a66)

BGL: Document use_binary_mode

---

Bounding_volumes/package_info/Bounding_volumes/copyright
Classification/package_info/Classification/copyright
Combinatorial_map/package_info/Combinatorial_map/copyright
Generalized_map/package_info/Generalized_map/copyright
Linear_cell_complex/package_info/Linear_cell_complex/copyright
NewKernel_d/package_info/NewKernel_d/copyright
copyright

* Affected package(s):  various
* Issue(s) solved (if any): n/a
* License and copyright ownership: see diff

Fix a number of copyright-related issues

---

Generator/test/Generator/test_generators.cpp

Depending on a seed it is well possible that the average result is far off from the expected value.
* Issue(s) solved (if any): fix #7081

Generator: Fix assert

---

.github/workflows/Remove_labels.yml
.github/workflows/build_doc.yml
.github/workflows/checks.yml
.github/workflows/cmake-all.yml
.github/workflows/delete_doc.yml
.github/workflows/demo.yml
.github/workflows/filter_testsuite.yml
.github/workflows/list_workflow_last_run.css
.github/workflows/list_workflow_last_run.yml
.github/workflows/send_email.yml
.github/workflows/wiki_notification.yml

That will avoids warnings in actions triggered from pull-requests based on release branches.

Update Github workflows from CGAL `master` version

---

Maintenance/test_handling/create_testresult_page
Maintenance/test_handling/testresult.css
Testsuite/test/parse-ctest-dashboard-xml.py

Adding a timeout column to the test suite that Distinguish between error and time-out.
Testsuite improvements #2205

Adding a timeout column to the testsuite

---

Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_widget.ui

Make it possible to have a multi line entry for tetrahedra (like points or polylines) instead of tedious point-by-point
* Issue(s) solved (if any): partial fix of #6690

Polyhedron: object generator tetrahedron -added line entry UI and logic

---

Intersections_3/test/Intersections_3/bbox_other_do_intersect_test.cpp
Stream_support/include/CGAL/IO/helpers.h

Fix a warning.
* Affected package(s):  Surface_mesh
* Issue(s) solved (if any): fix #6127

CGAL/IO/helpers.h: fix VC++ /W4 warning

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/tangential_relaxation.h

handle degenerate triangles (usually created with the reprojection)

---

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp

3D demo, Mesh_3 plugin: fix the protect_borders/features

---

Barycentric_coordinates_2/doc/Barycentric_coordinates_2/Barycentric_coordinates_2.txt

Corrected link to the indicated place at the university

Fix unreachable link

---

CGAL_ImageIO/include/CGAL/Image_3.h
Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
Polyhedron/demo/Polyhedron/Scene_image_item.cpp

Add the possibility to read NIFTI files for the Tet mesh generator in case VTK is installed.
I do not understand why I have to choose the plugin when selecting a *nii file in the demo.

Polyhedron Demo: Add reading NIFTI files (*.nii)

---

Mesher_level/include/CGAL/Meshes/Triangulation_mesher_level_traits_3.h
Polyhedron/demo/Polyhedron/Scene_textured_surface_mesh_item.cpp

fix 2 warnings I got with gcc-13

fix warnings 

---

Documentation/doc/CMakeLists.txt
Documentation/doc/resources/1.9.6/BaseDoxyfile.in
Documentation/doc/resources/1.9.6/CGAL_mathjax.js
Documentation/doc/resources/1.9.6/DoxygenLayout.xml
Documentation/doc/resources/1.9.6/DoxygenLayoutPackage.xml
Documentation/doc/resources/1.9.6/cgal_stylesheet.css
Documentation/doc/resources/1.9.6/footer.html
Documentation/doc/resources/1.9.6/hacks.js
Documentation/doc/resources/1.9.6/header.html
Documentation/doc/resources/1.9.6/header_package.html
Documentation/doc/resources/1.9.6/menu_version.js
Documentation/doc/resources/1.9.6/stylesheet.css
Documentation/doc/scripts/html_output_post_processing.py
Documentation/doc/scripts/process_doc.sh
Documentation/doc/scripts/test_doxygen_versions.sh
Documentation/doc/scripts/testsuite.py
Scripts/developer_scripts/run_doxygen_testsuite

Update doc testsuite to use 1.9.6

---

GraphicsView/include/CGAL/Qt/vec.h

* Affected package(s): `GraphicsView`

Add missing include for `qreal`

---

Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_with_region_growing.cpp

adapted polygonal surface reconstruction to updated api of region growing
* Affected package(s): Polygonal Surface Reconstruction

Polygonal Surface Reconstruction: adapted polygonal surface reconstruction to updated api of region growing

---

Optimal_bounding_box/include/CGAL/Optimal_bounding_box/oriented_bounding_box.h
Polyhedron/demo/Polyhedron/Plugins/PCA/CMakeLists.txt
Polyhedron/demo/Polyhedron/Plugins/PCA/Create_bbox_mesh_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PCA/Create_obb_mesh_plugin.cpp

Overall clean-up, more items supported, fixes for degenerate cases for OBB, etc.
* Issue(s) solved (if any): partial fix of #6690

AABB / OBB plugins improvements

---

Installation/test/Installation/test_configuration.cmake.in
Installation/test/Installation/test_configuration_qt5.cmake.in

Trivial PR that could me merged without testing.

Minimum version should be first

---

Installation/cmake/modules/CGAL_Eigen3_support.cmake
Installation/lib/cmake/CGAL/CGALConfig.cmake

Small change to be compatible with Conan 2.0. see PR https://github.com/conan-io/conan-center-index/pull/17858.

fix for Conan 2.0

---

Polyhedron/demo/Polyhedron/Point_container.cpp
Three/include/CGAL/Three/Point_container.h
Three/include/CGAL/Three/Primitive_container.h

fix memory leaks
This applies to 5.4.x, 5.5.x, and `master`.
* Affected package(s): Polyhedron/demo

fix various memory leaks in CGAL Lab

---

Installation/cmake/modules/CGAL_SetupCGALDependencies.cmake

That new CMake function will ease the work with the Conan CGAL package.

create a new CMake function CGAL_setup_CGAL_flags

---

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp

Fix remeshing of a surface
* Issue(s) solved (if any): fix #7547

Polyhedron demo: Fix remeshing of a surface

---

Scripts/developer_scripts/run_testsuite_with_ctest

Follow up of #7519 that was not done on the right file

Disable MSVC 2015 starting with CGAL 6.0

---

Scripts/developer_scripts/run_testsuite_with_ctest

#7538 followup
one more time 🎵 🎵 🎵 🎵

(Really) Disable MSVC 2015 starting with CGAL 6.0 

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h

Rephrase documentation of one-sided Haussdorff distance function

---

Polyhedron/demo/Polyhedron/Plugins/Display/Heat_method_plugin.cpp

The proper fixes would be to prevent the "reset colors" and the creation of a selection item from emitting "item changed": in neither case the item changed. Future work...

Fix connect infinite loop in heat method plugin

---

Stream_support/include/CGAL/IO/io.h

Fix istream for optional

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh_planar_patches.h
Shape_detection/include/CGAL/Polygon_mesh_processing/region_growing.h

In particular allows the use of region growing in remeshing with common interface

Fixes for undocumented remeshing with common interface

---

Spatial_sorting/doc/Spatial_sorting/Spatial_sorting.txt

Remove gray background and get some indentation

issue #7702 Appearance of " Hilbert Sorting" in documentation.

---

Polygon_mesh_processing/doc/Polygon_mesh_processing/Concepts/PMPCorefinementVisitor.h

edge and face edges were exchanged.

Fix concept doc

---

GraphicsView/include/CGAL/Buffer_for_vao.h

Update the triangulation method of Buffer_for_vao.
* Issue(s) solved (if any): fix a bug from Efi

Bug fix in drawing of interior faces when the outer boundary is pinched

---

Documentation/doc/biblio/cgal_manual.bib
Stream_support/doc/Stream_support/File_formats/Supported_file_formats.txt

Correcting permanent redirect

---

Triangulation/doc/Triangulation/Triangulation.txt

issue #7774 Link to support funding of GUDHI project not found

---

Documentation/doc/Documentation/Third_party.txt

issue #7770 Non existing link to the LASLib / LAStools

---

Polyhedron/demo/Polyhedron/Plugins/Isosurfacing_3/Isosurface_3_plugin.cpp
Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp

Fix warnings [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-I-85/Polyhedron_Demo/TestReport_lrineau_Fedora-with-LEDA.gz)

fix demo warnings

---

Algebraic_foundations/doc/Algebraic_foundations/Concepts/ExplicitInteroperable.h
Algebraic_foundations/doc/Algebraic_foundations/Concepts/Fraction.h
Algebraic_foundations/doc/Algebraic_foundations/Concepts/FromDoubleConstructible.h
Algebraic_foundations/doc/Algebraic_foundations/Concepts/FromIntConstructible.h
Algebraic_foundations/doc/Algebraic_foundations/Concepts/ImplicitInteroperable.h
Kernel_23/doc/Kernel_23/CGAL/Aff_transformation_2.h
Kernel_23/doc/Kernel_23/CGAL/Aff_transformation_3.h
Kernel_23/doc/Kernel_23/CGAL/aff_transformation_tags.h
Kernel_23/doc/Kernel_23/CGAL/intersections.h
Minkowski_sum_2/doc/Minkowski_sum_2/CGAL/Polygon_convex_decomposition_2.h
Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction.h
Solver_interface/include/CGAL/Eigen_sparse_matrix.h
Surface_mesh_parameterization/include/CGAL/surface_mesh_parameterization.h

Fix serveral labels reported by @albert-github 
Fixes issues #7793, #7791, #7790, #7788

Fix wrong \ingroup statements

---

Convex_hull_3/doc/Convex_hull_3/CGAL/convex_hull_3.h

fix a typo reported by email by Stefan Schirra
* License and copyright ownership: trivial change

Convex_hull_3: fix a typo

---

Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Periodic_3_triangulation_3.qhcp
Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/Periodic_Lloyd_3.qhcp

Should fix writes to read-only locations in the testsuite.
Locally tested

Fix qhelpgenerator call

---

Scripts/developer_scripts/list_cgal_workflows_last_run.sh

Enhances GitHub Action report by adding clickable links. Also, remove the file column

Enhancing GitHub Actions Report with Clickable Links

---

Filtered_kernel/include/CGAL/Filtered_kernel/internal/Static_filters/Power_side_of_oriented_power_circle_2.h
Filtered_kernel/include/CGAL/Filtered_kernel/internal/Static_filters/Static_filters.h

Fix issue
* Affected package(s): Filtered_kernel
* Issue(s) solved (if any): fix #7719

Filtered_kernel: Add Power_side_of_oriented_power_circle_2.h

---

BGL/test/BGL/test_Face_filtered_graph.cpp
BGL/test/BGL/test_graph_traits.cpp

Fixes [those 2 errors](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-113/BGL/TestReport_gimeno_Debian-testing-clang-main.gz)

workaround error with clang++-18

---

Intersections_3/include/CGAL/Intersections_3/internal/Plane_3_Plane_3_Plane_3_intersection.h

Increase precision of the intersection of 3 planes

---

Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp

Affine transformation transforms points, but didn't transform their normals. This PR takes care of normal transformation of point sets.
* Affected package(s): Polyhedron Demo

CGAL Lab: Transformation of point normals

---

Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arr_traits_adaptor_2.h

Fix typo in comment in Arr_traits_adaptor_2.h

fix typo in comment

---

Polyhedron/demo/Polyhedron/Plugins/PMP/Inside_out_plugin.cpp

Rename the action "Inside Out" of CGAL Lab, to something more explicit.
* Affected package(s): CGAL Lab

Rename the action "Inside Out" to something more explicit

---

.github/workflows/reuse.yml

Github workflow `reuse.yml`: call `apt-get update`, to fix errors

`reuse.yml`: call `apt-get update`

---

Triangulation/doc/Triangulation/Triangulation.txt

replace the, for doxygen and thus for the output, strange constructs with better constructs.

issue #8075 Documentation in Triangulation package

---

Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/Complex_cells_selector.h
Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/peel_slivers.h
Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
Tetrahedral_remeshing/include/CGAL/tetrahedral_remeshing.h

Tetrahedral_remeshing - `peel_slivers()`

---

Polyline_simplification_2/include/CGAL/Polyline_simplification_2/Stop_above_cost_threshold.h

_smaller_ -> _greater_ in documentation
* Affected package(s): Polyline_simplification
* Issue(s) solved (if any): fix #8114

Polyline_simplification: fix documentation

---

Surface_sweep_2/include/CGAL/Surface_sweep_2/Surface_sweep_2_impl.h

Added missing include statements of std headers
* Affected package(s): Surface_sweep_2
* Issue(s) solved (if any): NA
* Link to compiled documentation: NA

Added missing headers

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh_planar_patches.h

<s>The map is actually also an input parameter</s>
It can actually be with a small modification

Update parameter description

---

Lab/demo/Lab/Plugins/Display/Display_property_plugin.cpp
Lab/demo/Lab/Scene_surface_mesh_item.cpp

Fix bad optional access errors.

Fix property map calls in the demo

---

Installation/CHANGES.md

[Preview](https://github.com/MaelRL/cgal/blob/CGAL-Prepare_changes.md-6.0-GF/Installation/CHANGES.md)

 Prepare CHANGES.md for 6.0

---

Boolean_set_operations_2/doc/Boolean_set_operations_2/CGAL/draw_polygon_set_2.h
Linear_cell_complex/doc/Linear_cell_complex/CGAL/draw_linear_cell_complex.h
Nef_3/doc/Nef_3/CGAL/draw_nef_3.h
Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/draw_periodic_2_triangulation_2.h
Point_set_3/include/CGAL/draw_point_set_3.h
Polygon/include/CGAL/draw_polygon_2.h
Polygon/include/CGAL/draw_polygon_with_holes_2.h
Polyhedron/doc/Polyhedron/CGAL/draw_polyhedron.h
Surface_mesh/include/CGAL/draw_surface_mesh.h
Triangulation_2/doc/Triangulation_2/CGAL/draw_constrained_triangulation_2.h
Triangulation_2/doc/Triangulation_2/CGAL/draw_triangulation_2.h
Triangulation_3/doc/Triangulation_3/CGAL/draw_triangulation_3.h
Voronoi_diagram_2/doc/Voronoi_diagram_2/CGAL/draw_voronoi_diagram_2.h

instanciation -> instantiation

Spelling correction

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h

Forward the visitor for split

---

Nef_3/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h

Be resilient to isolated vertices

---

Ridges_3/doc/Ridges_3/Ridges_3.txt

Added missing citation command.

Missing citation command

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap.h

Fix initialization for partial hedge range

---

Kinetic_space_partition/doc/Kinetic_space_partition/Doxyfile.in
Kinetic_surface_reconstruction/doc/Kinetic_surface_reconstruction/Doxyfile.in

Thanks @albert-github for the report

Remove extra macro definitions

---

Kinetic_space_partition/doc/Kinetic_space_partition/PackageDescription.txt
Kinetic_surface_reconstruction/doc/Kinetic_surface_reconstruction/PackageDescription.txt

Made the bibliography references unique

issue #8318 Double bibliography reference

---

Mesh_3/test/Mesh_3/test_meshing_3D_gray_image_deprecated.cpp

Use default surface topology criteria

---

Arrangement_on_surface_2/demo/Arrangement_on_surface_2/ArrangementDemoTab.h
Arrangement_on_surface_2/include/CGAL/Arr_geodesic_arc_on_sphere_traits_2.h
BGL/test/BGL/test_Euler_operations.cpp
Boolean_set_operations_2/doc/Boolean_set_operations_2/CGAL/Boolean_set_operations_2.h
Circulator/test/Circulator/test_circ1.cpp
Circulator/test/Circulator/test_circ2.cpp
Combinatorial_map/include/CGAL/Combinatorial_map.h
Distance_3/test/Distance_3/test_distance_3.cpp
Generator/doc/Generator/CGAL/point_generators_2.h
Heat_method_3/include/CGAL/Heat_method_3/internal/Intrinsic_Delaunay_triangulation_3.h
Kernel_23/test/Kernel_23/Dimension.cpp
Lab/demo/Lab/Plugins/PMP/Interpolated_corrected_principal_curvatures_plugin.cpp
Lab/demo/Lab/Scene_textured_surface_mesh_item.cpp
Mesh_2/test/Mesh_2/test_meshing.cpp
Number_types/test/Number_types/Interval_nt_new.cpp
Orthtree/include/CGAL/Orthtree/Traversals.h
Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/MainWindow.cpp
Periodic_3_triangulation_3/include/CGAL/Periodic_3_regular_triangulation_3.h
Point_set_processing_3/include/CGAL/IO/write_off_points.h
Polygon_mesh_processing/doc/Polygon_mesh_processing/examples.txt
Polyhedron/doc/Polyhedron/Polyhedron.txt
Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_multiple_sources.cpp
Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/internal/Common.h
Triangulation_2/doc/Triangulation_2/Concepts/DelaunayTriangulationTraits_2.h
Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h

Deal with Issue #8348 
* Affected package(s):  Triangulation_2 and Periodic_triangulation_2
* Issue(s) solved (if any): fix #8348 

Deal with duplicate lines

---

Nef_3/include/CGAL/Nef_3/SNC_const_decorator.h
Nef_3/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
Nef_3/test/Nef_3/issue_6423.cpp

Fix the case of surfaces with borders. Then they may be incident to only the unbounded volume which so far was ignored. 
* Affected package(s): Nef_polyhedron_3
* Issue(s) solved (if any): fix #6423

Nef_3: Fix conversion to a FaceGraph

---

Installation/REUSE.toml
REUSE.toml

Simple reformating of those files.
No need to test in testsuite: test only the CI Action "REUSE" .

reformat the REUSE.toml file (readability), add natvis files

---

Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_model_complexty_control.cpp
Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_user_provided_planes.cpp
Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_with_region_growing.cpp
Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/polyfit_example_without_input_planes.cpp

Results of examples were using a file path with a folder.
* Affected package(s): Polygonal Surface Reconstruction

[PSR] Fixed example saving paths

---

GraphicsView/demo/Polygon/Polygon_2.cpp
GraphicsView/demo/Triangulation_2/Constrained_Delaunay_triangulation_2.cpp
GraphicsView/demo/Triangulation_2/Delaunay_triangulation_2.cpp
GraphicsView/include/CGAL/Qt/DemosMainWindow.h
Polyline_simplification_2/demo/Polyline_simplification_2/Polyline_simplification_2.cpp

Fix when QT SVG is not present

Fix conditional compilation

---

Arrangement_on_surface_2/include/CGAL/Arr_conic_traits_2.h
Combinatorial_map/include/CGAL/Combinatorial_map_storages_with_index.h
Combinatorial_map/include/CGAL/Compact_container_with_index.h
Combinatorial_map/include/CGAL/Dart.h
Kinetic_space_partition/examples/Kinetic_space_partition/include/Terminal_parser.h
Kinetic_space_partition/include/CGAL/KSP/debug.h
Kinetic_space_partition/include/CGAL/KSP_3/Initializer.h
Kinetic_space_partition/include/CGAL/KSP_3/Support_plane.h
Kinetic_space_partition/include/CGAL/Kinetic_space_partition_3.h
Kinetic_space_partition/test/Kinetic_space_partition/kinetic_3d_test_all.cpp
Kinetic_surface_reconstruction/examples/Kinetic_surface_reconstruction/include/Terminal_parser.h
Kinetic_surface_reconstruction/include/CGAL/KSR_3/Graphcut.h
Kinetic_surface_reconstruction/include/CGAL/Kinetic_surface_reconstruction_3.h
Linear_cell_complex/include/CGAL/CMap_linear_cell_complex_storages_with_index.h
Number_types/include/CGAL/CORE_BigFloat.h
Number_types/include/CGAL/cpp_float.h
Orthtree/include/CGAL/Orthtree_traits_polygons.h

In CGAL headers we must not use `assert()`
* Affected package(s): several

assert() ->  CGAL::assertion()

---

Arrangement_on_surface_2/benchmark/data/benchArrSegments.xml
Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Arc_2.h
Boolean_set_operations_2/test/Boolean_set_operations_2/test_compilation.cpp
Circular_kernel_3/doc/Circular_kernel_3/CGAL/global_functions_spherical_kernel_3.h
Installation/cmake/modules/CGAL_Macros.cmake
Intersections_2/test/Intersections_2/test_intersections_2.cpp
Kernel_23/test/Kernel_23/include/CGAL/_test_new_2.h

Deal with was not yet done in #8396
WIP
* Affected package(s): Circular_kernel_3, Arrangements, 2D Booelan, Installation

Duplicate Lines

---

Scripts/developer_scripts/tag_pr_per_release.sh

tag_pr_per_release.sh: allow to relaunch the script if it failed and code review with GH Copilot

tag_pr_per_release.sh: allow to relaunch the script if it failed

---

Maintenance/test_handling/Summary_Script.js
Maintenance/test_handling/create_testresult_page

Separate toggle button classes to prevent unwanted interactions between Open/Close All functionality and Third Party Libraries display

Testsuite Summary: Fix toggle buttons behavior

---

Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
Kernel_23/doc/Kernel_23/Concepts/GeomObjects.h

Add missing kernel functor overloads + cleaning

---

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h

remove duplicate header file inclusion

refactor: remove duplicate header file inclusion

---

Kinetic_space_partition/include/CGAL/KSP/debug.h
Kinetic_space_partition/include/CGAL/KSP_3/Data_structure.h
Kinetic_space_partition/include/CGAL/KSP_3/Initializer.h
Kinetic_space_partition/include/CGAL/KSP_3/Support_plane.h
Kinetic_space_partition/include/CGAL/Kinetic_space_partition_3.h
Kinetic_surface_reconstruction/include/CGAL/Kinetic_surface_reconstruction_3.h

Re-enabling EPECK support in KSP 
* Affected package(s): KSP, KSR

KSP: Repairing EPECK support in KSP

---

Lab/demo/Lab/Plugins/PCA/Basic_generator_plugin.cpp
Lab/demo/Lab/Plugins/PCA/Basic_generator_widget.ui
Lab/demo/Lab/Plugins/PMP/Selection_plugin.cpp
Lab/demo/Lab/Plugins/PMP/Selection_widget.ui
Lab/demo/Lab/Scene_polyhedron_selection_item.cpp
Lab/demo/Lab/Scene_polyhedron_selection_item.h
Lab/demo/Lab/Viewer.cpp
Triangulation_on_sphere_2/demo/Triangulation_on_sphere_2/main.cpp

Modifying coordinates in the files and reloading is painful, so this PR adds a way to specify new coordinates from the selection item:
https://github.com/user-attachments/assets/965f6c65-0936-4778-a9ac-8e8acb237774
* Affected package(s): `Lab`

Make it possible to enter target coordinates to move a point

---

Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_global.h
Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_do_intersect.cpp
Installation/CHANGES.md

The title says it all.
* Affected package(s): Aos_2
* Issue(s) solved (if any): fix #8782
* Link to compiled documentation (obligatory for small feature): 

Fixed do_intersect() of curves (provided by Edkirito).

---

STL_Extension/include/CGAL/Compact_container.h
STL_Extension/include/CGAL/Concurrent_compact_container.h

Fixes [these errors](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.1-Ic-122/Alpha_wrap_3/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz)
cc @mglisse

Workaround bug in gcc

---

Shape_detection/include/CGAL/Shape_detection/Efficient_RANSAC/Efficient_RANSAC.h
Shape_detection/include/CGAL/Shape_detection/Region_growing/Point_set/Least_squares_cylinder_fit_sorting.h
Shape_detection/include/CGAL/Shape_detection/Region_growing/Point_set/Least_squares_plane_fit_sorting.h

Checking for normals when Point_set_3 is used as input range
* Issue(s) solved (if any): fix #6806

Shape_detection: Checking for normals

---

Generator/doc/Generator/CGAL/point_generators_2.h
Generator/doc/Generator/CGAL/point_generators_3.h
Generator/doc/Generator/CGAL/point_generators_d.h
Generator/include/CGAL/point_generators_3.h

Added default value in documentation.
* Issue(s) solved (if any): fix #8866

Generator: Document default for parameter radius

---

Lab/demo/Lab/Plugins/PCA/Basic_generator_plugin.cpp
Lab/demo/Lab/Plugins/PCA/Basic_generator_widget.ui

Fix [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.1-I-152/Lab_Demo/TestReport_gimeno_Debian-testing-clang-main.gz)

Do not use deprecated function

---

Documentation/doc/Documentation/License.txt

Fixes https://github.com/CGAL/cgal/issues/7346 (lazily)

Add note about CGAL and pragma license messages

---

Algebraic_foundations/doc/Algebraic_foundations/Algebraic_foundations.txt

Turn subsection to subsubsection
* Affected package(s): Algebraic Foundations
* Issue(s) solved (if any): fix #8912

Algebraic Foundations: Turn subsection to subsubsection

---

Distance_3/include/CGAL/Distance_3/Line_3_Line_3.h
Distance_3/include/CGAL/Distance_3/Line_3_Plane_3.h
Distance_3/include/CGAL/Distance_3/Plane_3_Plane_3.h
Distance_3/include/CGAL/Distance_3/Point_3_Line_3.h
Distance_3/include/CGAL/Distance_3/Point_3_Plane_3.h
Distance_3/include/CGAL/Distance_3/Point_3_Point_3.h
Distance_3/include/CGAL/Distance_3/Point_3_Ray_3.h
Distance_3/include/CGAL/Distance_3/Point_3_Segment_3.h
Distance_3/include/CGAL/Distance_3/Point_3_Tetrahedron_3.h
Distance_3/include/CGAL/Distance_3/Point_3_Triangle_3.h
Distance_3/include/CGAL/Distance_3/Ray_3_Line_3.h
Distance_3/include/CGAL/Distance_3/Ray_3_Plane_3.h
Distance_3/include/CGAL/Distance_3/Ray_3_Ray_3.h
Distance_3/include/CGAL/Distance_3/Segment_3_Line_3.h
Distance_3/include/CGAL/Distance_3/Segment_3_Plane_3.h
Distance_3/include/CGAL/Distance_3/Segment_3_Ray_3.h
Distance_3/include/CGAL/Distance_3/Segment_3_Segment_3.h
Distance_3/include/CGAL/Distance_3/Triangle_3_Triangle_3.h

Add namespace ::CGAL:: when calling compare to compile with leda.
fix: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.1-Ic-167/Kernel_23/TestReport_cgaltest_Fedora-with-LEDA.gz
* Affected package(s): Distance_3
* License and copyright ownership: GF

Resolve the issue with leda in Distance_3

---

Constrained_triangulation_3/doc/Constrained_triangulation_3/Constrained_triangulation_3.txt
Constrained_triangulation_3/include/CGAL/Conforming_Delaunay_triangulation_3.h
Constrained_triangulation_3/include/CGAL/IO/write_MEDIT.h

Fixes in the user manual
* Affected package(s): CDT_3

CDT_3: small adjustements (documentation)

---

Constrained_triangulation_3/examples/Constrained_triangulation_3/remesh_constrained_Delaunay_triangulation_3.cpp

* Affected package(s): `Constrained_triangulation_3`
* Issue(s) solved (if any): fix -

Minor CDT3+tet remesh example improvements

---

Number_types/doc/Number_types/CGAL/Gmpzf.h
Number_types/doc/Number_types/CGAL/MP_Float.h

* Issue(s) solved (if any): fix #8991

Reference Mpzf/Gmpzf/MP_Float from each other's doc

---

CGAL_ImageIO/include/CGAL/SEP_to_ImageIO.h
Installation/cmake/modules/CGAL_pointmatcher_support.cmake
Lab/demo/Lab/Plugins/Mesh_3/CMakeLists.txt
Lab/demo/Lab/Plugins/Mesh_3/Io_image_plugin.cpp

Lab:  Use std::filesystem instead of boost::filesystem

---

Installation/cmake/modules/CGALHelpers.cmake
Installation/demo/CMakeLists.txt
Installation/examples/CMakeLists.txt
Installation/test/CMakeLists.txt

Fix issues while building examples/tests/demos for a release (internal or public)
Fixes #8981

fix build of tests/examples/demos for a release
