CGAL/cgal

- Mesh_3/examples/Mesh_3/CMakeLists.txt
- Mesh_3/include/CGAL/Mesh_3/Refine_cells_3.h
- Mesh_3/include/CGAL/Mesh_3/mesh_standard_cell_criteria.h
- Mesher_level/include/CGAL/Meshes/Double_map_container.h
The error was actually due to an mismatch between `CGAL_LINKED_WITH_TBB` and `CGAL_CONCURRENT_MESH_3`. See #5375.
For CGAL-5.3 we should clean that up!
The error was actually due to an mismatch between `CGAL_LINKED_WITH_TBB`
and `CGAL_CONCURRENT_MESH_3`.
For CGAL-5.3 we should clean that up!The error was actually due to an mismatch between `CGAL_LINKED_WITH_TBB`
and `CGAL_CONCURRENT_MESH_3`.
For CGAL-5.3 we should clean that up!
> Fix examples/Mesh_3/mesh_implicit_domains.cpp

- Nef_2/include/CGAL/Nef_2/debug.h
Remove the `std::flush` which is not needed for `std::cerr` and put parenthesis.
* Affected package(s): Nef_2
* Issue(s) solved (if any): fix #5312
> Nef_2: fix misleading indentation

- CGAL_ipelets/demo/CGAL_ipelets/CMakeLists.txt
- CGAL_ipelets/demo/CGAL_ipelets/generator.cpp
- CGAL_ipelets/demo/CGAL_ipelets/hull.cpp
- CGAL_ipelets/include/CGAL/CGAL_Ipelet_base.h
- Installation/CMakeLists.txt
- Installation/cmake/modules/FindIPE.cmake
Restore missing lines in CMakelists that propagated the Ipe version to use to simple_triangulation
* Affected package(s):CGAL_ipelets
> CGAL_Ipelets: Fix after merge in master.

- Documentation/doc/Documentation/Third_party.txt
- Installation/cmake/modules/CGAL_pointmatcher_support.cmake
- Point_set_processing_3/examples/Point_set_processing_3/CMakeLists.txt
- Point_set_processing_3/examples/Point_set_processing_3/registration_with_OpenGR.cpp
- Point_set_processing_3/examples/Point_set_processing_3/registration_with_opengr_pointmatcher_pipeline.cpp
- Point_set_processing_3/examples/Point_set_processing_3/registration_with_pointmatcher.cpp
Fixes to OpenGR and pointmatcher examples.
* Affected package(s):Point_set_processing_3_Examples
> PSP_3: Fix pointmatcher support

- Point_set_3/include/CGAL/Point_set_3.h
- Point_set_3/test/Point_set_3/point_set_test.cpp
The function `Point_set_3::properties_and_types()` returned a pair of `std::string` and `std::type_info`, which lead to a compilation error as `std::type_info` is not copyable. This is fixed by using the C++11 [`std::type_index`](https://en.cppreference.com/w/cpp/types/type_index) class (which is specifically done for cases like this one).
* Affected package(s): Point Set 3
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/5368
> [Point Set 3] Fix broken properties and types

- GraphicsView/demo/Segment_Delaunay_graph_2/include/CGAL/Constraints_loader.h
- GraphicsView/demo/Segment_Delaunay_graph_Linf_2/include/CGAL/Constraints_loader.h
Fix the SDG demos by using `CGAL::cpp98::random_shuffle()`   as `std::random_shuffle()`  is going to disappear for `std::shuffle`. 
* Affected package(s): SDG
* Issue(s) solved (if any): fixes two items of #5374
> Segment Delaunay Graph demos: Use CGAL::cpp98::random_shuffle()

- STL_Extension/include/CGAL/array.h
- Testsuite/include/CGAL/Testsuite/Triangulation_23/test_move_semantic.h
- Triangulation_2/include/CGAL/Triangulation_hierarchy_2.h
- Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_triangulation_short_2.h
- Triangulation_3/include/CGAL/Triangulation_hierarchy_3.h
- Triangulation_3/test/Triangulation_3/include/CGAL/_test_cls_delaunay_3.h
- Triangulation_3/test/Triangulation_3/include/CGAL/_test_cls_regular_3.h
- Triangulation_3/test/Triangulation_3/include/CGAL/_test_cls_triangulation_3.h
This PR started as a fix for the issue https://github.com/CGAL/cgal/issues/5396.
Then I have discovered that, in the PR https://github.com/CGAL/cgal/pull/4496, I had not implemented a test-suite for the move-semantic.
I have also discovered that a moved-from triangulation, since #4496, is not a valid CGAL triangulation: it has an empty TDS, and thus no infinite vertex, and as such has:
- `dimension()==2`,
- `number_of_vertices() == -1` (or `number_of_vertices() + 1 == 0`, to avoid a warning).
- Add a testsuite for the move-semantic:
- check that a move-constructed triangulation is equivalent to its source,
- check the strange state of move-from triangulation (`dimension()==2`),
- check that a moved-from triangulation:
- can be destroyed,
- can be assigned,
- and can be restored to the …
> Fix the move-semantic of Triangulation_hierarchy_3

- Algebraic_foundations/include/CGAL/number_utils.h
- Cartesian_kernel/include/CGAL/constructions/kernel_ftC2.h
- Cartesian_kernel/include/CGAL/constructions/kernel_ftC3.h
- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_line_2.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_plane_3.h
> Allow an inexact version of bisector when no sqrt is available.

- Surface_mesh_topology/include/CGAL/Surface_mesh_topology/internal/Path_on_surface_with_rle.h
Add copy constructor in `Path_on_surface_with_rle` to remove a warning (`implicitly-declared is deprecated [-Wdeprecated-copy]`).
* Affected package(s): Surface_mesh_topology
* Issue(s) solved (if any): partial fix #5373
> Warning in surface mesh topology

- NewKernel_d/include/CGAL/NewKernel_d/Cartesian_LA_base.h
- NewKernel_d/include/CGAL/NewKernel_d/LA_eigen/constructors.h
- NewKernel_d/test/NewKernel_d/Epick_d_eigen.cpp
- Number_types/include/CGAL/Interval_nt.h
Since it isn't tested, there was some bitrot in the code to use Eigen vectors in NewKernel_d (instead of std::vector/std::array). Tested locally with
```diff
--- a/NewKernel_d/include/CGAL/NewKernel_d/Cartesian_LA_base.h
+++ b/NewKernel_d/include/CGAL/NewKernel_d/Cartesian_LA_base.h
@@ -34,7 +34,7 @@
namespace CGAL {
template < typename FT_, typename Dim_,
-#if 1
+#if 0
typename Vec_=Mix_vector<Array_vector<FT_, Dim_>,
Vector_vector<FT_, Dim_>,
FT_, Dim_>,
```
* Affected package(s): Number_types, NewKernel_d
> Fix NewKernel_d/Eigen compatibility

- Arrangement_on_surface_2/demo/Arrangement_on_surface_2/CMakeLists.txt
- Minkowski_sum_2/test/Minkowski_sum_2/CMakeLists.txt
- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Set_movable_separability_2/examples/Set_movable_separability_2/CMakeLists.txt
- Set_movable_separability_2/test/Set_movable_separability_2/CMakeLists.txt
- Shape_detection/benchmark/Shape_detection/CMakeLists.txt
- Shape_detection/examples/Shape_detection/CMakeLists.txt
- Shape_detection/test/Shape_detection/CMakeLists.txt
CGAL now requires c++14, so the CMAKE_CXX_STANDARD instructions in our CMake scripts have become useless. 
This PR removes them.
* Issue(s) solved (if any): fix #5311
> Remove CMAKE_CXX_STANDARD commands in cmake scripts

- Spatial_sorting/include/CGAL/Hilbert_sort_median_3.h
Linking of the CGAL tests and examples, which depend on the Hilbert sort, with the clang compiler is very slow due to the recursion sort. The templated member function is called recursively 8 times. We have no problems with calling this function 4 times, but when calling it 5 and more times, which is required for Hilbert sort on 3D points, the linking time increases very quickly. This affects several packages.
The problem is experienced only with -03 optimizations turned on. There is no such problem with -01. By looking at the difference between -01 and -03, we figured out that the problem comes when the `-fvisibility-inlines-hidden` optimization is omitted, which is the case for -03. This optimization gives inline C++ member functions hidden visibility by default. So, one way to fix the …
> Hilbert sort 3D, slow clang linking

- Nef_2/include/CGAL/Nef_2/debug.h
- Nef_3/include/CGAL/Nef_3/K3_tree.h
- Nef_3/include/CGAL/Nef_3/SNC_external_structure.h
This ensures that the trace macros `CGAL_NEF_TRACE.*` are disabled unless the user specifically enables them by defining `CGAL_USE_TRACE`. `NDEBUG` also ensures `CGAL_USE_TRACE` is undefined.
* Affected package(s): Nef_2, Nef_3
* Issue(s) solved (if any): fix #5240
> Default disable NEF trace macros

- Polygon_mesh_processing/include/CGAL/Side_of_triangle_mesh.h
Add move ctor and move assign to Side_of_triangle_mesh.
These are only added, if `BOOST_NO_CXX11_RVALUE_REFERENCES` is defined
> Add move ctor and move assign to Side_of_triangle_mesh

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
If there is only one patch in a c3t3, de-synchronize the tets and item colors.
> Polyhedron Demo: C3t3 colors enhancement

- Nef_3/include/CGAL/normal_vector_newell_3.h
Implemented the performance improvements as discussed in #5379
* Optimise for Cartesian and Homogeneous kernels
* Use locals instead of multiple functions calls and recalculations
* Use `orthogonal_vector` for triangles
* Issue(s) solved (if any): fix #5379
* Feature/Small Feature (if any): performance enhancement.
> Calculate normals for facets more efficiently

- NewKernel_d/include/CGAL/NewKernel_d/Cartesian_static_filters.h
Not sure where this static filter stuff is going (wrapping the Kernel_23 functions is ugly, but duplicating code wouldn't be better), it was just there to prove that it is possible, but it might as well be a bit useful by wrapping a predicate that is important for triangulations. It would be more useful if it was also used with Dynamic_dimension_tag, but that's for some other time.
> static filter for 2d Side_of_oriented_sphere

- Filtered_kernel/include/CGAL/Filtered_predicate.h
- NewKernel_d/include/CGAL/NewKernel_d/Cartesian_LA_functors.h
- NewKernel_d/include/CGAL/NewKernel_d/Cartesian_filter_K.h
- NewKernel_d/include/CGAL/NewKernel_d/Filtered_predicate2.h
- NewKernel_d/include/CGAL/NewKernel_d/Lazy_cartesian.h
- NewKernel_d/include/CGAL/NewKernel_d/Types/Hyperplane.h
- NewKernel_d/include/CGAL/NewKernel_d/Types/Sphere.h
- NewKernel_d/include/CGAL/NewKernel_d/function_objects_cartesian.h
- NewKernel_d/include/CGAL/NewKernel_d/functor_properties.h
Some predicates do not perform any arithmetic operation and only do comparisons. For Epick_d, we can do them directly with `double`, no need for intervals. For Epeck_d, we do use intervals, but we do not need to set the rounding mode.
This last optimization might be a little bit risky. First, interval comparisons might at some point in the future require protection. Second, other operations might happen outside of the predicate, in particular the conversion to approximate (C2A), and some operations like constructing an interval from `int64_t` do require protection. I think that the restriction to Epeck_d (where we already have intervals) and to a small list of predicates makes this ok... :crossed_fingers:
> Optimize trivial predicates

- NewKernel_d/include/CGAL/NewKernel_d/Cartesian_LA_functors.h
- NewKernel_d/include/CGAL/NewKernel_d/Kernel_2_interface.h
- NewKernel_d/include/CGAL/NewKernel_d/Kernel_3_interface.h
Just some bitrot in the code to give NewKernel_d an interface compatible with Kernel_23.
If all my pending PRs get merged, then I can build a 2D Delaunay triangulation with Eigen vectors as Point_2 as fast as the usual Epick.
```c++
#define CGAL_NEWKERNEL_D_USE_EIGEN_VECTOR 1
#include <CGAL/Epick_d.h>
#include <CGAL/NewKernel_d/Kernel_2_interface.h>
#include <CGAL/Triangulation_structural_filtering_traits.h>
namespace CGAL {
struct Epick_2_help1
: Cartesian_filter_K<
Cartesian_base_d<double, CGAL::Dimension_tag<2>>,
Cartesian_base_d<Interval_nt_advanced, CGAL::Dimension_tag<2>>,
Cartesian_base_d<internal::Exact_field_selector<double>::Type, CGAL::Dimension_tag<2>>
>
{
};
struct Epick_2_help2
: Cartesian_filter_K<
Epick_2_help1,
Cartesian_base_d<Interval_nt_advanced, …
```
> bitrot in Kernel_[23]_interface

- Segment_Delaunay_graph_Linf_2/include/CGAL/Segment_Delaunay_graph_Linf_2/Voronoi_vertex_sqrt_field_new_C2.h
Fix for
`warning C5055: operator '*': deprecated between enumerations and floating-point types`
in [Segment_Delaunay_graph_Linf_2_Examples](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-53/Segment_Delaunay_graph_Linf_2_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz)
* Affected package(s): SDG_Linf_2
> SDG_Linf_2: Cast enum to fix warning

- Kernel_d/include/CGAL/Kernel_d/Iso_box_d.h
Fix for the [`Kernel_d`](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-52/Kernel_d/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz)  testsuite with `/c++-latest` for VC++.
Add the trivial functions in the namespace `CGAL::Kernel_d`.
* Affected package(s): Kernel_d
> Kernel_d:   Deal with deprecated result_type

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h
This avoids the loop over all faces per patch. Init of shared and interior edges is still lazy
> Corefine: always init faces of patches

- Intersections_3/include/CGAL/Intersections_3/internal/Iso_cuboid_3_Plane_3_intersection.h
- Intersections_3/include/CGAL/Intersections_3/internal/Tetrahedron_3_Plane_3_intersection.h
- Intersections_3/test/Intersections_3/issue_5428.cpp
- Intersections_3/test/Intersections_3/test_intersections_3.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h
In the first commits we added checks that the `boost::optional` is not `boost::none`.
As the code does not always does the right thing for inexact constructions we rewrote two intersection functions. They are now only based on segment plane intersections.   We may also have a look at Triangle_3/Tetrahedron_3 and Line_3/Tetrahedron_3.
* Affected package(s): Intersect_3
* Issue(s) solved (if any): fix #5428
> Intersect_3: Fix Iso_cuboid_3/Plane_3 and Tetrahedon_/Plane_3 intersection using PMP::clip internal function

- Box_intersection_d/include/CGAL/Box_intersection_d/Box_d.h
I would like to see if[ this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-62/Box_intersection_d/TestReport_lrineau_Fedora-rawhide-Release.gz) goes away.
@maxGimeno can you please give this a try on a local machine where we get this warning.
* Affected package(s): Box_intersection_d
> Box_intersection_d:  Replace built-in array with std::array

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/shape_predicates.h
Fix a number of issues with `PMP::remove_almost_degenerate_faces()`:
- `Edge::collapse_edge` ignored the `ecm`
- A needle ignored due to having a too long collapsable edge was not considered as a cap
- Fix not purging the edge being currently considered from future sets (might have been inserted from an adjacency)
- Fix over-purging sets when using `remove_face()` in the case of a cap on the border
- Don't purge sets if `get_best_oriented()` is going to reject the collapse anyway (everything should still be in the future sets)
- Don't swap if we're going to return anyway
> PMP: Remove needles&caps fixes

- Spatial_searching/include/CGAL/Kd_tree.h
This PR fixes issue #5482 by changing the constructor of `Kd_tree`. The internal vector with points is now created at the initialization step using the vector constructor instead of the `insert` method. This is more efficient and clean as well. This should also fix the macOS-related test suite errors.
* Issue(s) solved (if any): fix #5482
> Kd_tree using vector constructor instead of insert

- Algebraic_kernel_for_spheres/include/CGAL/Algebraic_kernel_for_spheres/internal_functions_comparison_root_for_spheres_2_3.h
- Distance_2/include/CGAL/squared_distance_2_1.h
Specify CGAL::compare to prevent conflict with LEDA::compare()
* Affected package(s):Distance_2, Algebraic_kernel_for_spheres
> Fix compare() with LEDA

- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_new_3.h
Add an extra operator to construct the plane inside the predicate so that the plane is exact.
> Add an extra operator to have an exact plane

- Nef_3/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h
Bypass coplanarity assertion for triangular facets in `polygon_mesh_to_nef_3`
When walking the edges of a triangular facet, it is known that the 3 points of the facet will always be on a plane defined by the facet normal, so the assertions are not necessary.
The PR also removes duplicate hash table lookups of the point variable `pv`.
* Issue(s) solved (if any): fix #5379 
* Feature/Small Feature (if any): performance/speed
> Bypass coplanarity assertion for triangular facets.

- Nef_3/include/CGAL/Nef_polyhedron_3.h
Applying the single responsibility principle marking bounded volumes should neither `compute_external` nor `simplify`. Then `simplify()` can be called explicitly where needed (and only once)
More details in https://github.com/CGAL/cgal/issues/5379#issuecomment-780733581
* Issue(s) solved (if any): fix #5379 
* Feature/Small Feature (if any): performance/speed
> Explicitly call simplify after marking bounded volumes

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h
In the macOS test suite, the `self_intersections_example` is using TBB. When the TBB support is on, this example is aborted due to an exception thrown by TBB, however, this exception is not caught. As far as I see, the problem is that the TBB version provided by brew (which is what I think most often used on macOS) is compiled without C++11 support, which is required to handle this exception according to the posts [here](https://software.intel.com/content/www/us/en/develop/blogs/exact-exception-propagation-in-the-intel-threading-building-blocks-library-and-c11.html) and [here](https://www.threadingbuildingblocks.org/docs/help/reference/environment/feature_macros.html). In fact, only one CGAL file seems to use this type of exception and this is the `self_intersections` from PMP.
This PR …
> Use TBB captured exception in PMP

- STL_Extension/include/CGAL/hash_openmesh.h
- STL_Extension/test/STL_Extension/CMakeLists.txt
- STL_Extension/test/STL_Extension/test_hash_OpenMesh.cpp
As the `boost::graph_traits<OpenMesh>::edge_descriptor` is a CGAL type and not the edge handle of OpenMesh, we have to provide the specialiasation of `hash` even if we have a version  of OpenMesh that has implemented the `hash` for its handle types.
* Affected package(s):  STL Extensions
* Issue(s) solved (if any): fix #5493
> Provide specialization of hash for the edge_descriptor we provide for OpenMesh

- Point_set_processing_3/include/CGAL/edge_aware_upsample_point_set.h
- Shape_detection/include/CGAL/Shape_detection/Efficient_RANSAC/Efficient_RANSAC.h
Fix 3 conversion warnings when using float kernel:
- [1 in RANSAC](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-55/Shape_detection/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz)
- [2 in PSP](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-55/Point_set_processing_3/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz)
* Affected package(s): Shape Detection / PSP
* Based on 5.2 as the RANSAC warning was probably introduced by https://github.com/CGAL/cgal/pull/5234
> [PSP/RANSAC] Fix warnings

- Shape_detection/test/Shape_detection/test_validity_sampled_data.cpp
Shape detection runs tests that can take a while in debug mode, so it's better to disable them completely unless users want to try them.
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/5479
* (Based on 5.2 as guilty test was introduced by https://github.com/CGAL/cgal/pull/5234 integrated in 5.2)
> Shape Detection: Disable expensive tests by default

- AABB_tree/include/CGAL/AABB_traits.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h
Use an exact AABB-tree using exact node values.
Not backported to 5.1 on purpose.
> Robustify internal side-of-triangle-mesh calls

- Arrangement_on_surface_2/include/CGAL/Arr_dcel_base.h
- Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_impl.h
- Arrangement_on_surface_2/include/CGAL/Arrangement_on_surface_2.h
- Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_construction_ss_visitor.h
- Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_overlay_ss_visitor.h
_Release note: (Because 5.0 branch was deleted, [the previous PR](https://github.com/CGAL/cgal/pull/4875) was closed and we can't seem to open it again. Please refer to this PR for previous reviews.)_
This PR replaces https://github.com/CGAL/cgal/pull/4851.
As said in the previous PR, _when merging 2 inner CCBs, all halfedges of one of the CCB are traversed again and updated, which can lead to an explosion of complexity, for example when computing the arrangement of a very large holes with many concavities_.
This new PR uses a similar approach than the previous one (using temporary redirections of inner CCBs towards a valid one and cleaning everything afterwards). The differences are:
- instead of union set, we simply keep, for each inner CCB, a pointer to another CCB: these pointers form …
> Arrangement 2: Enhanced CCB Merging for Surface Sweep

- Number_types/include/CGAL/NT_converter.h
- Point_set_processing_3/include/CGAL/compute_average_spacing.h
- Poisson_surface_reconstruction_3/include/CGAL/Poisson_mesh_cell_criteria_3.h
- Poisson_surface_reconstruction_3/include/CGAL/Poisson_reconstruction_function.h
- Poisson_surface_reconstruction_3/include/CGAL/poisson_surface_reconstruction.h
Poisson currently only compiles with Epick (see https://github.com/CGAL/cgal/issues/5431). This PR makes it compile with simple cartesian (both using double and float). However, the code rarely works at runtime (because it is based on Delaunay triangulation which are not robust without exact predicates), so I couldn't add a test for this.
I have tried to make it compile with Epeck, but it required many changes (including changes in Surface Mesher) and ended up breaking the Epick version, so I figured it was not worth the trouble.
* Affected package(s): Poisson
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/5431
> [Poisson Reconstruction] Compatibility with Simple Cartesian

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/FMLS.h
This PR prevents a "bad_alloc" error that could happen when the size of the input object (in terms of size of the bbox) was very small and edge lengths even smaller, e.g. `cellSize = 1e-9`.
Thresholding the bbox size with `1e-3` was not consistent with the size of the object, leading to using `resize(n)` on a `std::vector` with `n` larger than `vector.max_size()`.
> Tetrahedral_remeshing - fix bad_alloc for very small input mesh

- Polygon_mesh_processing/doc/Polygon_mesh_processing/examples.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/CMakeLists.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_OM_union.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_consecutive_bool_op.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h
- STL_Extension/include/CGAL/hash_openmesh.h
Change the comparison operator for descriptors in the corefinement code so that it works with OpenMesh.
> PMP:: Use operator<  instead of operator> as OM only implements the former

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/VSA_wrapper.h
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- Polyhedron/demo/Polyhedron/Server_ws.cpp
- Polyhedron/demo/Polyhedron/Viewer.h
The macOS test suite reveals various little warnings when compiling the Polyhedron demo. This PR fixes these warnings.
* Issue(s) solved (if any): warnings
> Fixed Polyhedron demo warnings in the macOS test suite

- Documentation/doc/Documentation/Tutorials/Tutorial_GIS.txt
fandom rorest -> random forest
fix tutorial typo
* Link to compiled documentation
https://doc.cgal.org/latest/Manual/tuto_gis.html#title12
none
> Tutorial_GIS.txt: fandom rorest -> random forest

- Polyhedron/demo/Polyhedron/Plugins/PCA/Affine_transform_plugin.cpp
Don't copy extra properties of the sourc esurface_mesh when validating a transformation.
> Polyhedron_demo: Fix Affine_transform_plugin crash

- Point_set_processing_3/include/CGAL/IO/read_ply_points.h
There was a mistake in the group name of that function.
* Affected package(s):PSP
* Issue(s) solved (if any): fix #5531
> Documentation: Fix `read_ply_points_with_properties` 

- Classification/include/CGAL/Classification/Label_set.h
add missing <unordered_map> include
* Affected package(s):Classification
*Not based on 5.1 because the `unordered_map` call only appeared in 5.2
> Classification: Add missing include

- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Arc_2.h
- Bounding_volumes/include/CGAL/Approximate_min_ellipsoid_d/Approximate_min_ellipsoid_d_configure.h
- Convex_hull_2/include/CGAL/Convex_hull_2/ch_akl_toussaint_impl.h
- Convex_hull_2/include/CGAL/Convex_hull_2/ch_assertions.h
- Convex_hull_2/include/CGAL/Convex_hull_2/ch_bykat_impl.h
- Convex_hull_2/include/CGAL/Convex_hull_2/ch_graham_andrew_impl.h
- Convex_hull_2/include/CGAL/Convex_hull_2/ch_jarvis_impl.h
- Kernel_23/include/CGAL/kernel_assertions.h
- Partition_2/include/CGAL/Partition_2/partition_approx_convex_2.h
- Partition_2/include/CGAL/Partition_2/partition_assertions.h
- Partition_2/include/CGAL/Partition_2/partition_greene_approx_convex_2.h
- Partition_2/include/CGAL/Partition_2/partition_optimal_convex_2.h
- Partition_2/include/CGAL/Partition_2/partition_y_monotone_2.h
- Point_set_processing_3/include/CGAL/point_set_processing_assertions.h
- Poisson_surface_reconstruction_3/include/CGAL/surface_reconstruction_points_assertions.h
- Polygon/include/CGAL/Polygon_2/polygon_assertions.h
- Polytope_distance_d/include/CGAL/Width_3.h
- Polytope_distance_d/include/CGAL/Width_polyhedron_3.h
- STL_Extension/include/CGAL/multiset_assertions.h
- STL_Extension/include/CGAL/triangulation_assertions.h
- Scripts/scripts/cgal_create_assertions.sh
- SearchStructures/include/CGAL/Tree_assertions.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_2/assertions.h
- Stream_lines_2/include/CGAL/streamlines_assertions.h
Remove NDEBUG from various nnn_assertions.h files as it is already visible through `CGAL_NO_ASSERTIONS`, `CGAL_NO_PRECONDITIONS`, `CGAL_NO_POSTCONDITIONS`, `CGAL_NO_WARNINGS`
Include missing header files for files which reference the above defines.
* Affected package(s): Arrangement_on_surface_2, Convex_hull_2,Kernel_23,Partition_2,Point_set_processing_3,Poisson_surface_reconstruction_3,Polygon,Polytope_distance_d, STL_Extension, Scripts, SearchStructures, Straight_skeleton_2, Stream_lines_2
* Issue(s) solved (if any): fix #5240 
* Feature/Small Feature (if any): small feature
> Allow -DNDEBUG and CGAL_nnn_assertions at the same time

- Nef_3/include/CGAL/Nef_3/Halfedge.h
- Nef_3/include/CGAL/Nef_3/SHalfedge.h
- Nef_3/include/CGAL/Nef_3/SHalfloop.h
- Nef_3/include/CGAL/Nef_polyhedron_3.h
- STL_Extension/include/CGAL/Handle.h
The static analysis recommends, as a low priority, adding move assignment operators for various classes. I have implemented them using the swap idiom which is exception-safe. 
For Gmpq_type an assignment operator isn't needed because the class has no members, adding a defaulted move assignment operator suppresses the analysis warnings. However adding a move assignment operator when a copy assignment operator isn't explicitly declared deletes the copy assignment operator, which then causes compile errors. Likewise for the copy constructor, these therefore also have to be declared defaulted. I don't think declaring these defaulted member functions introduces any extra code generation.
* Affected package(s): Nef_3, STL_extension, Number_types
* Issue(s) solved (if any): bugfix
* License and …
> Move assignment operators

- TDS_3/include/CGAL/Triangulation_data_structure_3.h
I am trying to fix the PR https://github.com/CGAL/cgal/pull/4364 (the one of the small feature [Patch_to_concurrency_in_CGAL](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Patch_to_concurrency_in_CGAL).
If `Parallel_tag` is used with Triangulation_3/Mesh_3, but `CGAL_LINKED_WITH_TBB` is not defined, there there is a compilation error:
```
.../TDS_3/include/CGAL/Triangulation_data_structure_3.h:134:6: error: static assertion failed: In CGAL triangulations, `Parallel_tag` can only be used with the Intel TBB library. Make TBB available in the build system and then define the macro `CGAL_LINKED_WITH_TBB`.
134 |     (!(std::is_convertible<Concurrency_tag, Parallel_tag>::value),
|      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I am wondering …
> Triangulation_3: Add a static assert so that Parallel_tag can only be used with TBB

- Nef_S2/include/CGAL/Nef_S2/SM_const_decorator.h
Calculate Object_index hash tables as needed i.e when the assertion fails, or when trace message is built.
* Affected package(s): Nef_3, Nef_S2
* Issue(s) solved (if any): fix #5379
* Feature/Small Feature (if any): performance/speed
> Calculate indices only when required.

- CMakeLists.txt
- Installation/CMakeLists.txt
Allow to use CGAL as a submodule of a bigger CMake project.
The trick is to use
- `CGAL_SOURCE_DIR` instead of `CMAKE_SOURCE_DIR`, and
- `CGAL_BINARY_DIR` instead of `CMAKE_BINARY_DIR`.
See
- https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_SOURCE_DIR.html
- https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_BINARY_DIR.html
> This can be useful when add_subdirectory() is used to connect several projects.
> Allow to use CGAL as a submodule of a bigger CMake project

- Mesh_3/doc/Mesh_3/Mesh_3.txt
- Mesh_3/doc/Mesh_3/examples.txt
- Mesh_3/examples/Mesh_3/CMakeLists.txt
- Mesh_3/examples/Mesh_3/mesh_3D_gray_image_with_custom_initialization.cpp
- Mesh_3/include/CGAL/Mesh_3/initialize_triangulation_from_gray_image.h
- Mesh_3/include/CGAL/Mesh_3/initialize_triangulation_from_labeled_image.h
This PR introduces a new example about how to initialize the tet meshing process with points that lie on all connected components of the object to be meshed, described in a 3D gray-level image.
The example is added to the user manual, and undocumented header added.
This PR follows #1115 that was using the same internal code for detection and initialization of connected components, from segmented images.
* Issue(s) solved (if any): offers a partial solution to #923
> Mesh 3 - connected components initialization for 3D gray images

- Installation/CHANGES.md
- Polygon_mesh_processing/doc/Polygon_mesh_processing/Concepts/PMPCorefinementVisitor.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h
Visitor calls for creation of new edges have only been added for the corefinement part and not the Bool Op part.
This PR fixes that.
Link to the modified doc: [here](https://cgal.github.io/5492/v0/Polygon_mesh_processing/classPMPCorefinementVisitor.html).
Link to SF: [here](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Coref_more_visitor_functions_for_edges)
> Add missing visitor calls for the output_builder part

- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Ray_hit_generator.h
- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Ray_hit_generator2.h
- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/SM_walls.h
- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Single_wall_creator.h
- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Single_wall_creator2.h
- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Single_wall_creator3.h
- Nef_3/include/CGAL/Nef_3/ID_support_handler.h
- Nef_3/include/CGAL/Nef_3/SNC_constructor.h
- Nef_3/include/CGAL/Nef_3/SNC_indexed_items.h
- Nef_3/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h
- Nef_3/include/CGAL/Nef_3/vertex_cycle_to_nef_3.h
- Nef_3/include/CGAL/Nef_polyhedron_3.h
This is mostly just cleaning the code in `Face_graph_index_adder` which is part of the code in polygon_mesh_to_nef_3.h
* Remove multiple vector lookups using index.
* Remove an additional property hash lookup.
* Add methods for explicitly creating a new index, and return it instead of set_index()/get_index()
* Rename variable member variable to `shalfedges` instead of `hash`. 
* Feature/Small Feature (if any): cleaning
> Cleanup index adder in polygon_mesh_to_nef_3

- GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h
- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/IO/LAS_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
- Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h
- There is a BOOL declaration in both lib3mf and LASTools, that conflict in 3mf_plugin. To prevent it, I moved the LAS code from the item to the LAS_plugin.
- Some Qt::MidButton were added in Basic_viewer_qt in 5.3, change them in middlebutton to fix a warning
This is based on master because the CGAL_IO and the CMake modernization makes it really hard to have a single coherent fix base don an old release, and I don't think anyone uses lib3mf except me, but if asked I can do 2 other PRs for 5.1 and 5.2
> Polyhedron_demo: Move LAS code from item to plugin

- GraphicsView/demo/Triangulation_2/include/CGAL/Lipschitz_sizing_field_criteria_2.h
This little PR fixes the C++11 warning on the macOS produced by the missing `= default` tag in the Lipschitz sizing field class in the Triangulation 2 demo. The warning is revealed in the recent test suite.
* Affected package(s): `GraphicsView`
* Issue(s) solved (if any): warnings
> Lipschitz sizing field macOS warning fixed

- Linear_cell_complex/include/CGAL/Linear_cell_complex_constructors.h
This change separates the `import_from_plane_graph` logic into 2 separate functions so the user can build the graph directly from a list of points and edges instead of a `std::istream`.
* Affected package(s): Linear_cell_complex
* Issue(s) solved (if any): N/A
> Linear cell complex: Add points and edges constructor

- AABB_tree/include/CGAL/AABB_traits.h
- BGL/include/CGAL/boost/graph/Euler_operations.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Do_intersect_3.h
- Filtered_kernel/include/CGAL/internal/Static_filters/Equal_3.h
- Intersections_3/include/CGAL/Intersections_3/internal/Bbox_3_Sphere_3_do_intersect.h
- Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_example.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h
vtuning in order to find small improvements to make.
> PMP:  Accelerate isotropic remeshing

- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/include/CGAL/Kernel/interface_macros.h
- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
- Nef_3/include/CGAL/Nef_3/bounded_side_3.h
- Nef_S2/include/CGAL/Nef_S2/SM_point_locator.h
- Nef_S2/include/CGAL/Nef_S2/Sphere_segment.h
Given two segments of great circles we construct an intersection of the two great circles. In the test if the intersection point lies on the segments we first check if the point is on the great circle.  First we know that, and second this triggers an exact test.
* Affected package(s): Nef_S2, Nef_3
* License and copyright ownership: unchanged.
> Nef_3: Do not test has_on for a point where we know that it will be true

- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_dialog.ui
- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
This PR improves the behavior of the `isotropic_remeshing_plugin` dialog box, by :
- disabling the spinbox for the number of smoothing iterations when "edges only" is selected
- changing the go-through-by-pushing-tab order to make it go from top to bottom of the UI
> Polyhedron demo - improve PMP::isotropic_remeshing dialog box

- Linear_cell_complex/include/CGAL/Linear_cell_complex_incremental_builder.h
Adds a missing include. This file uses `Generalized_map_tag` on line 50, which is defined in `Linear_cell_complex_base.h`.
* Affected package(s): Linear cell complex
* License and copyright ownership: Signed CLA
> Linear_cell_complex_incremental_builder include

- Surface_mesh/examples/Surface_mesh/sm_do_intersect.cpp
Removes unused boost includes and some duplicate STL includes.
The includes became unnecessary after a735e84.
> [cleanup][surface_mesh] Remove unused and duplicate includes

- HalfedgeDS/include/CGAL/HalfedgeDS_list.h
- Nef_3/include/CGAL/Nef_3/K3_tree.h
- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
- Nef_S2/include/CGAL/Nef_S2/Sphere_map.h
- Nef_S2/include/CGAL/Nef_polyhedron_S2.h
- STL_Extension/include/CGAL/Handle_for.h
- STL_Extension/include/CGAL/In_place_list.h
- STL_Extension/include/CGAL/assertions.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_aux.h
- Stream_support/include/CGAL/IO/VRML/VRML_2_ostream.h
In a previous issue ( #451 ) a `CGAL_destructor_assertion` macro was added to handle assertions made within destructors. When an exception is thrown from a destructor while the stack is being unwound, the existence of any uncaught exceptions cause the program to terminate immediately, without correct error handling. Sometimes it's safe to throw an exception even while std::uncaught_exception() == true. For example, if stack unwinding causes an object to be destructed, the destructor for that object could run code that throws an exception as long as the exception is caught by some catch block before escaping the destructor. That said coverity static analysis has found several places in the codebase where this is not the case, i.e the destructor calls some code which makes a …
> Fix uncaught exceptions

- Principal_component_analysis/examples/Principal_component_analysis/CMakeLists.txt
- Principal_component_analysis/test/Principal_component_analysis/CMakeLists.txt
PCA depends on Eigen, but the CMakeLists still try to compile the examples and tests without it (leading to [warnings](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-88/Principal_component_analysis_Examples/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz) as without Eigen, the package fallbacks on an internal implementation that is deprecated). This PR fixes that.
* Affected package(s): PCA
* Based on 5.2 to avoid conflicts as the CMakeLists changed since 5.1
> PCA: do not compile examples/tests without Eigen

- Classification/examples/Classification/example_cluster_classification.cpp
- Classification/include/CGAL/Classification/Feature_set.h
The cluster example triggered [an error on _one_ platform](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-94/Classification_Examples/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz).
After running the address sanitizer (which did detect problems), I figured it came from the fact that I used a temporary variable when generating features. I made this variable defined at the right scope (as is already documented) and it fixed the problem. I'm surprised no more platforms actually crashed on this…
The address sanitizer also revealed a leak that I fixed (I used `std::unique_ptr<>::release()` instead of `std::unique_ptr<>::reset()`: _release_ does not free the memory but only gives the user the ownership of the pointer).
* Base …
> Classification: Sanitize addresses

- Kernel_23/include/CGAL/Kernel/function_objects.h
Somewhat follow-up of https://github.com/CGAL/cgal/pull/1741.
If the triangle/plane is degenerate, the case is already handled separately.
But if we know the plane is not degenerate, the normal should not be recomputed in a different manner, as it might lead to a null normal and some issues down the line.
> Fix inconsistency in normal computation in robust projection code

- Cartesian_kernel/include/CGAL/Cartesian/Circle_3.h
Replace the Rep type by a boost::tuple to silence a warning.
* Affected package(s):Kernel_23
* Issue(s) solved (if any): fix #5506
> Kernel_23: Fix warnings in Circle_3

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h
Use `std::remove_if` to have `O(n)` complexity instead of `O(k*n)` (`k` being the number of removed polygons), which gets nasty when there are a lot of invalid polygons in the soup.
Based on the oldest release rather than master because it is dramatic enough.
> Speed up invalid polygon removal in repair_PS

- Principal_component_analysis/include/CGAL/PCA_util_Eigen.h
- Principal_component_analysis/include/CGAL/Subiterator.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_circles_2.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_cuboids_3.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_rectangles_2.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_segments_2.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_segments_3.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_tetrahedra_3.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_triangles_2.h
- Principal_component_analysis/include/CGAL/linear_least_squares_fitting_triangles_3.h
- Principal_component_analysis/test/Principal_component_analysis/test_kernels.cpp
- Principal_component_analysis/test/Principal_component_analysis/test_validity.cpp
- Principal_component_analysis_LGPL/include/CGAL/centroid.h
- Solver_interface/include/CGAL/Eigen_diagonalize_traits.h
PR following the discussions with @palliez and @cportaneri.
It improves the _Principal Component Analysis_ package in the following ways:
- fix the computation of the centroid for sets of `Iso_cuboid_3` that were completely wrong, and also fixed the computation of PCA of `Iso_cuboid_3` in volumic variant which was wrong too. The PCA of `Iso_cuboid_3` in surface variant is broken too, but I couldn't fix it yet. I'm still working on it.
- for some reason, the matrices in `Eigen_diagonalize_traits` were filled using `static_cast<float>` operator on each value, which does not seem justified. Removing this cast drastically reduces errors between an estimated line (or plane) and points aligned on a line (or plane), from `1e-8` to `1e-15` in my experiments. This fix may also benefit to other …
> [Principal Component Analysis] Kernel compatibility, diagonalization precision and overload efficiency

- Mesh_3/include/CGAL/Mesh_polyhedron_3.h
- Mesh_3/test/Mesh_3/test_meshing_determinism.cpp
This PR enriches the testing of determinism in Mesh_3 by comparing
the output of `CGAL::facets_in_complex_3_to_triangle_mesh(c3t3, polyhedron);`
and its dump.
> Mesh_3 - more testing of determinism

- Polyhedron/demo/Polyhedron/Scene.cpp
- Polyhedron/demo/Polyhedron/TextRenderer.cpp
- STL_Extension/include/CGAL/Object.h
- Stream_support/include/CGAL/IO/OFF/File_header_OFF_impl.h
- Stream_support/include/CGAL/IO/OFF/File_writer_OFF.h
Fix a trivial warning about braces in the scene
I did not find the issue in previous release so I only applied it in master.
> Polyhedron Demo:  Trivial Warning

- CGAL_ImageIO/archive/demo/CGALimageIO/CMakeLists.txt
- CGAL_ImageIO/examples/CGALimageIO/CMakeLists.txt
- CGAL_ImageIO/examples/CGALimageIO/extract_a_sub_image.cpp
- CGAL_ImageIO/examples/CGALimageIO/slice_image.cpp
- CGAL_ImageIO/include/CGAL/Image_3_vtk_interface.h
This PR is a maintenance PR:
- it adds a new example for CGAL_ImageIO: slicing an image in the z direction. Well, I am not sure "slicing" it the right word.
- it fixes `CGAL_ImageIO/archive/demo/CGALimageIO/CMakeLists.txt` to that one can compile `image_to_vtk_viewer.cpp`.
* Affected package(s): CGAL_ImageIO
> CGAL ImageIO: Add an example and restore VTK support

- Installation/cmake/modules/CGAL_add_test.cmake
- Scripts/developer_scripts/run_testsuite_with_ctest
Adapts a little the ctest scripts for being able to run them on a windows platform.
Also fix a bug in the add_text maccro.
* Affected package(s):Scripts, Installation
> Testsuite: Fixes for windows runs

- Nef_2/include/CGAL/Nef_2/Segment_overlay_traits.h
A small performance optimisation in Segment_overlay_traits that saves calling the same code twice when assertions are enabled.
* Feature/Small Feature (if any): performance
> Nef 3 performance segment overlay traits

- Interpolation/examples/Interpolation/interpolation_vertex_with_info_2.cpp
- Interpolation/examples/Interpolation/sibson_interpolation_rn_vertex_with_info_2.cpp
Inheriting from `std::iterator` is deprecated, which leads to [warnings in the `Interpolation` examples](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-94/Interpolation_Examples/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz) that do that.
Examples are easily fixed by using lambdas (as suggested in the original comments), which also make the code much easier to read.
* Affected package(s): Interpolation
> Interpolation: Fix deprecated inheritance with std::iterator

- Point_set_processing_3/examples/Point_set_processing_3/registration_with_pointmatcher.cpp
Pointmatcher might randomly not converge, which leads to [errors](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-97/Point_set_processing_3_Examples/TestReport_lrineau_Ubuntu-Latest.gz) in the testsuite. In my experiments, it happens only 6% of the time. I added a loop to run it again until convergence and it fixes the problem.
> PSP: Fix pointmatcher example

- Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
Mesh_3 automatically detects and considers input image edges (the 12 edges of the bbox) as polyline features.
Each surface voxel is checked to construct one polyline for each edge. However, not all "points" (constructed at voxels "corners") on the edges of the cube are domain corners.
This PR differentiates between corner vertices and edge vertices.
It is important because corner vertices are forced to be "terminal" in the call to  `split_graph_into_polylines()` hence leading to
as many polylines as segments on image bbox edges, and a protecting ball on each of these fake-corners, and over-refined cube edges.
> Mesh_3 - fix features detection on image bounding box

- Arrangement_on_surface_2/test/Arrangement_on_surface_2/IO_base_test.h
In the recent test suit on the mac mini arm architecture, we have several run-time errors in the `Arrangement_on_surface_2` package. It turns out that they are caused by the unassigned variable that is then used to call the constructor that further leads to errors in the code.
This little PR fixes this problem. The change is tested locally on `x86_64` and `arm` platforms.
* Affected package(s): `Arrangement_on_surface_2`
* Issue(s) solved (if any): run-time errors
> Fixed unassigned variable in the tests of Arrangement_on_surface_2

- Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp
A missing call to viewer->makeCUrrent() was responsible for the bbox being teleported after each picking.
> Polyhedron Demo: Fix edit bbox

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
This PR fixes a "double definition" link error.
We `inline` the `indices(int, int)` function, which is was not template, nor inline and causing the error when compiling two cpp targets together.
> Tetrahedral Remeshing - fix link error

- .github/workflows/build_doc.yml
Add the package itself to the list, and not only the content of package_info/dependencies.
This way, when differencies only appear in Documentation, for exemple, the script will not exit with an empty list of modified packages.
* Affected package(s):CI
* Issue(s) solved (if any): bug in #5596
> CI Doc building: Accept modifications to the Documentation package only

- Kernel_23/include/CGAL/rational_rotation.h
Use directly the parameters which are non const references.   
At the same time drop in some `CGAL::abs()`  and `CGAL::square()`.
* Issue(s) solved (if any): fix #0000, fix #5466 
* License and copyright ownership: maintenance GF
> Kernel_23: Remove local reference in rational_rotation.h

- BGL/include/CGAL/boost/graph/parameters_interface.h
- BGL/test/BGL/test_cgal_bgl_named_params.cpp
- Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_polyhedral_envelope.cpp
> Polyhedral_envelope: face epsilon map

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/FMLS.h
This PR completes #5478 to deal with very small size meshes, and fixes a crash in this case
> Tetrahedral remeshing - fix indices for very small inputs

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
This PR introduces a new type of "halfedge status" of edges that are part of the input constrained edges property map, and are incident to a face to be remeshed only by a vertex.
These edges contribute to creating corner vertices (incident to >= 3 constrained edges), but should still not be considered as patch borders.
Without dealing with these "isolated constraints", the corner vertices that were incident to 2 patch borders and 1 of these edges were not considered as corners but as simple patch border vertices, hence they could be moved/deleted by a collapse or relaxation steps.
> PMP::isotropic_remeshing - keep corners incident to isolated constrained edges

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Offset_meshing_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Remeshing_dialog.ui
If one has some feature to protect, the offset mesher can respect them.
> Add support for protecting features in offset meshing

- Polyhedron/demo/Polyhedron/Scene_group_item.cpp
- Three/include/CGAL/Three/Scene_group_item.h
- Three/include/CGAL/Three/Scene_item_with_properties.h
Replace a member of type QList<> with a pointer to silent a warning about QList<> not being a dll-interface and add a missing macro to an interface class.
* Affected package(s):Polyhedron_Demo, Three
> Polyhedron_demo : Fix a warning

- Scripts/developer_scripts/autotest_cgal
- Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
- Testsuite/test/run_testsuite_with_cmake
This is #5491 without the "skipped" squares in the results.
* Affected package(s):Testsuite, Scripts
> Testsuite: Fix release creation scripts for windows

- Nef_3/include/CGAL/Nef_3/K3_tree.h
In vtune we can see that the kd tree has potential for improvement.  The first step is to replace the allocation on the heap with a `Compact_container`.   
The next step will be the sidedness test for split-planes  which are all axis aligned which currently seems not  to get exploited.   
> Nef_3: Improve K3_tree

- Linear_cell_complex/include/CGAL/Linear_cell_complex_constructors.h
- Surface_mesh_topology/include/CGAL/Path_on_surface.h
Implement what @gdamiand suggested in Issue #5576, that is to check if the stream is still valid, in order to avoid a justified warning.
* Affected package(s): Linear cell complex
* Issue(s) solved (if any): fix #5576
> Linear Cell Complex: Check if stream is valid

- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/isolated_vertices.cpp
- Arrangement_on_surface_2/include/CGAL/Arr_dcel_base.h
- Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_2_iterators.h
- HalfedgeDS/include/CGAL/HalfedgeDS_iterator.h
- Linear_cell_complex/demo/Linear_cell_complex/import_moka.h
- STL_Extension/include/CGAL/Compact_container.h
The DCEL data structure currently uses `In_place_list`. Although using the `fast_pool_allocator` already speeds this structure up, I experimented with the Compact Container and noticed it was more efficient.
- using CC instead of in place lists improves timings up to 15% (5% in average)
- most structures benefit from pointer squatting except for the face and inner CCB classes which are given an additional pointer (small memory overhead)
- using `fast_pool_allocator` remains more efficient than `std::allocator`
By running the testsuite locally, I got errors from iterators constructed from `0`. I replaced that by `nullptr` and it fixed the problems.
* Affected package(s): Arrangement and dependent packages (Surface Sweep, Boolean Operations, etc.)
> Arrangement:  Use Compact Container for DCEL

- Maintenance/public_release/scripts/precompiled_demos_zips
- Scripts/developer_scripts/autotest_cgal
- Scripts/developer_scripts/cgal_demo_copy_all_dlls_cygwin.sh
This PR introduces a new bash script for cygwin that collects all needed `.exe` and `.dll` to run the Polyhedron demo and its plugins.
It should be run from inside the demo build directory.
Maybe we should make it more general so that it can be used directly in the release creation process @lrineau @maxGimeno ?
> Scripts - collect dlls for Polyhedron demo with cygwin

- Point_set_processing_3/include/CGAL/cluster_point_set.h
Fix for the following warning: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-107/Point_set_processing_3_Examples/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz
(The map is documented as having a value type `std::size_t`, but in practice it's more practical if it accepts any integer type without complaining.)
* Issue(s) solved (if any): fix #0000, fix #000
> PSP: Fix conversion warnings in clustering

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h
Detected [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-111/Polygon_mesh_processing/TestReport_lrineau_ArchLinux-CXX17-Release.gz)
> Fix use of empty range

- Documentation/doc/scripts/process_doc.sh
- Documentation/doc/scripts/test_doxygen_versions.sh
- Documentation/doc/scripts/testsuite.py
If the build of doxygen master fails, or if make fails to build the doc with it, the script will fail to upload the whole documentation testsuite. This PR modifies the scripts so that they can upload the testsuite and the log instead of nothing in such a situation.
> Documentation: Fix doxygen comparison scripts

- Combinatorial_map/include/CGAL/Combinatorial_map_iterators_base.h
- Documentation/doc/Documentation/Developer_manual/Chapter_checks.txt
- Installation/include/CGAL/config.h
- Nef_3/include/CGAL/Nef_3/K3_tree.h
- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
- Nef_S2/include/CGAL/Nef_S2/Sphere_map.h
- Nef_S2/include/CGAL/Nef_polyhedron_S2.h
- Polyhedron/include/CGAL/Polyhedron_incremental_builder_3.h
- Polynomial/include/CGAL/Exponent_vector.h
- STL_Extension/include/CGAL/Handle.h
- STL_Extension/include/CGAL/Handle_for.h
- STL_Extension/include/CGAL/Multiset.h
- STL_Extension/include/CGAL/assertions.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_aux.h
- Stream_support/include/CGAL/IO/VRML/VRML_2_ostream.h
- Surface_mesher/archive/include/CGAL/builder.h
This continues the previous changes done under #5233 and addresses further uncaught exceptions found in by static analysis since upgrading from CGAL version 5.0.3
* Make the changes less ugly
* Use the language features correctly (now that C++11 is minimum)
* Fix uncaught exceptions warnings in Handle.h Handle_for.h and Multiset.h
* Affected package(s): STL_extention
* Issue(s) solved (if any): static analysis/bugfix/cleaning
> Fix uncaught exceptions cleanup

- Triangulation_on_sphere_2/include/CGAL/Delaunay_triangulation_on_sphere_2.h
- Triangulation_on_sphere_2/include/CGAL/Delaunay_triangulation_on_sphere_traits_2.h
- Triangulation_on_sphere_2/include/CGAL/Triangulation_on_sphere_2.h
- Triangulation_on_sphere_2/include/CGAL/Triangulation_on_sphere_2/internal/arc_on_sphere_2_subsampling.h
- Voronoi_diagram_2/include/CGAL/Delaunay_triangulation_on_sphere_adaptation_traits_2.h
- Voronoi_diagram_2/include/CGAL/Voronoi_diagram_2/Construct_dual_points.h
- Voronoi_diagram_2/include/CGAL/Voronoi_diagram_2/Identity_rejectors.h
- Voronoi_diagram_2/include/CGAL/Voronoi_diagram_2/Site_accessors.h
Add the additional types / functions / adapters required for `CGAL::Delaunay_triangulation_on_sphere_2` to be compatible with `CGAL::Voronoi_diagram_2`.
Example of usage: https://gist.github.com/MaelRL/f5671a48dccb9ec874c41c47ba13bab4.
TODO:
Into CGAL `5.3.1` due to the minor swap bug.
* Affected package(s): `Triangulation_on_sphere_2`
> Make `ToS2` compatible with `Voronoi_diagram_2`

- Polyhedron/include/CGAL/Polyhedron_incremental_builder_3.h
- STL_Extension/include/CGAL/In_place_list.h
- STL_Extension/include/CGAL/vector.h
- TDS_3/include/CGAL/Triangulation_data_structure_3.h
This uses the nullptr comparison operators of Compact_container to check for an empty handle instead of using an instance of an empty handle.  I think this is clearer semantically, and possibly slightly more performant.
The same operators are then added to In_place_list, and vector_iterator. Comparisons to nullptr utilised in the same way.
The change also suppresses some static analysis warnings about usage after explicit null.
* Affected package(s): Polyhedron_3 and TDS_3
> Polyhedron_3 and TDS_3 compare handle nullptr

- Documentation/doc/resources/1.8.20/header_package.html
Below the bottom blue block we see for the packages some extra white space. For the Manual page this white space is not present.
The reason is the placing of the "hack.js" code.
Note the problem was only observed with Firefox.
The old situation:
The corrected situation:
> Extra white space at bottom of page

- Algebraic_foundations/include/CGAL/number_utils.h
- Number_types/include/CGAL/mpq_class.h
- Number_types/test/Number_types/Gmpzf_new.cpp
- Number_types/test/Number_types/include/CGAL/_test_utilities.h
- Number_types/test/Number_types/utilities.cpp
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_distance.cpp
The default `CGAL::approximate_sqrt()` is implemented as:
```
template <typename NT>
NT approximate_sqrt(const NT& nt)
{
return NT(sqrt(CGAL::to_double(nt)));
}
```
Since `__gmp_expr` uses template to keep a stack of operations, this will fail to compile if `NT` is not trivial as there will not be a constructor from `double` available.
<s>This PR adds an overload for `__gmp_expr` and uses `Coercion_traits` to find the base type.</s>
This PR changes the return types of `CGAL::approximate_sqrt()` to use `Coercion_traits` and `result_type` to use the correct return types.
**Remarks:**
- I am not sure if that would work for everything or just stuff for which we have overloaded `Coercion_traits`.
- With regard to `mpz_class`: I'm a bit confused why this class has a `Sqrt` in `mpz_class.h`:
* …
> Fix approximate_sqrt return types

- Mesh_2/include/CGAL/IO/write_vtu.h
`write_vtu`, from PR #3297 (CGAL-4.14) was buggy with `ASCII_MODE`, because of spurious `"` in the output file.
*I found out while trying to debug the experimental NURBS mesher.*
* Affected package(s): Mesh_2
> Mesh_2: Fix write_vtu in ASCII

- Installation/test/Installation/test_gmp_mpfr_dll.cpp
With the new versions of those dlls we use on some machines, this test fails because the names are not the same. 
This PR allows it to also pass with the new names. Unfortunately, those dlls have no VersionInfo, so the test will not fail if VersionInfo is missing anymore.
> Testsuite: Fix gmp_and_mpfr_dll test

- Installation/cmake/modules/FindTBB.cmake
Add a first call to `find_package(TBB QUIET NO_MODULE)` in our `FindTBB.cmake`, to bypass it in case it is sufficient. This fixes the bug that occurs with oneAPI.
* Issue(s) solved (if any): fix #5676
> First search for TBB in config mode

- Nef_3/include/CGAL/Nef_3/SNC_constructor.h
- Nef_S2/include/CGAL/Nef_S2/Sphere_segment.h
I stumbled across some code and found that the following change seems to work, and gives a performance boost of about 20% when using the Nef_3_benchmark project. I am not sure if this is correct, but similar usage of the function is present in SM_overlayer.h
* Issue(s) solved (if any): #5379 
* Feature/Small Feature (if any): speed
> Nef_3 performance - has_on_after_intersection in SNC_constructor

- .github/workflows/build_doc.yml
If a warning or an error is reported during the building of` doc_with_postprocessing`, stops the process and post a comment with the issue.
In the example below, the image `anchor.png` has been removed from the doc of `AABB_tree`. Here is the result of the `/build` command:
* Affected package(s):CI
> Documentation in github: Report issues in doxygen

- Apollonius_graph_2/include/CGAL/Apollonius_graph_2/comparator_profiler.h
- Apollonius_graph_2/include/CGAL/Apollonius_graph_2/predicate_profiler.h
- Arrangement_on_surface_2/include/CGAL/Arr_circle_segment_traits_2.h
- Arrangement_on_surface_2/include/CGAL/Arr_conic_traits_2.h
- Arrangement_on_surface_2/include/CGAL/Arr_counting_traits_2.h
- Box_intersection_d/include/CGAL/Box_intersection_d/Box_d.h
- CGAL_Core/include/CGAL/CORE/CoreDefs.h
- CGAL_Core/include/CGAL/CORE/CoreDefs_impl.h
- Installation/include/CGAL/atomic.h
- Installation/include/CGAL/config.h
- Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
- Mesh_3/include/CGAL/Mesh_3/Mesher_level.h
- Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h
- Mesh_3/include/CGAL/Mesh_3/Refine_cells_3.h
- Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
- Mesh_3/include/CGAL/Mesh_3/Refine_facets_manifold_base.h
- Mesh_3/include/CGAL/Mesh_vertex_base_3.h
- Mesh_3/include/CGAL/make_mesh_3.h
- Mesh_3/include/CGAL/refine_mesh_3.h
- Nef_3/include/CGAL/Nef_3/SNC_indexed_items.h
- Number_types/include/CGAL/Counted_number.h
- Point_set_processing_3/include/CGAL/Point_set_processing_3/internal/Callback_wrapper.h
- Polyhedron/demo/Polyhedron/Use_ssh.cpp
- Polyhedron/demo/Polyhedron/include/run_with_qprogressdialog.h
- Profiling_tools/include/CGAL/Profile_counter.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
- STL_Extension/include/CGAL/Time_stamper.h
- STL_Extension/include/CGAL/thread.h
Deprecate `cpp11::atomic` and `cpp11::threads` and use std versions instead
> CGAL:: Use std atomic and threads

- Distance_3/include/CGAL/squared_distance_3_0.h
- Distance_3/include/CGAL/squared_distance_3_1.h
- Distance_3/include/CGAL/squared_distance_3_2.h
- Distance_3/package_info/Distance_3/dependencies
- Distance_3/test/Distance_3/test_distance_3.cpp
- Intersections_3/include/CGAL/Intersections_3/internal/Triangle_3_Sphere_3_do_intersect.h
- Intersections_3/test/Intersections_3/test_intersections_3.cpp
The do_intersect function for triangle/sphere was never tested for a number type without division, and had bugs.
The test ` test_intersections_3.cpp`  passes.   I also added the fixes and the test for sphere/segment ,sphere/ray and sphere line which do pass.
NYA flag because there is some temporary code behind a macro, need to bench on Windows to take a final decision on "RT functions" being used in "FT functions".
* Affected package(s): Intersections_3
> Intersections_3: Fix do_intersect(sphere/triangle) if FT has no division

- Documentation/doc/resources/1.8.13/CGAL_mathjax.js
- Documentation/doc/resources/1.8.14/CGAL_mathjax.js
- Documentation/doc/resources/1.8.20/CGAL_mathjax.js
- Documentation/doc/resources/1.8.4/CGAL_mathjax.js
- Snap_rounding_2/doc/Snap_rounding_2/CGAL/Snap_rounding_2.h
- Snap_rounding_2/doc/Snap_rounding_2/Snap_rounding_2.txt
In pull request  #4644 a central MATHJAX_CODEFILE was introduced, but the snap rounding package was omitted, so this is corrected here.
For the MathJax V3 ( see #5707) this change is even mandatory (the current construct doesn't work).
> Adding items to central MATHJAX_CODEFILE

- STL_Extension/include/CGAL/result_of.h
- STL_Extension/test/STL_Extension/test_stl_extension.cpp
Replace `result_of.h`'s content by a simple include to config.h, and test it in `test_stl_extension.cpp`
* Affected package(s):STL_Extension
* Issue(s) solved (if any): fix #5729
> Test deprecated result_of.h

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
Statistics on selection items were merged with stats on surface_mesh_items because of a wrong value in , 
* Affected package(s): Polyhedron Demo
> Polyhedron Demo: Fix classname property for selection_item

- Polyhedron/demo/Polyhedron/Viewer.cpp
- Polyhedron/demo/Polyhedron/Viewer.h
- Three/include/CGAL/Three/Viewer_interface.h
If the user asks for a scene recentering while the scnee is scaled, the camera gets lost. This is a fix for that problem.
Base don 5.2 because the Scene Scaling appeared in 5.2
> Polyhedron Demo: Fix Scene Recentering while Scaled

- Installation/cmake/modules/CGAL_add_test.cmake
- Installation/demo/CMakeLists.txt
- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Camera_position/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Classification/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Convex_hull/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/PCA/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/PMP/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/CMakeLists.txt
- Polyhedron/demo/Polyhedron/polyhedron_demo_macros.cmake
- Scripts/developer_scripts/autotest_cgal_with_ctest
- Scripts/developer_scripts/run_testsuite_with_ctest
- Snap_rounding_2/test/Snap_rounding_2/CMakeLists.txt
- Testsuite/test/parse-ctest-dashboard-xml.py
Change the ctest scripts to work on windows and  directly use MSBuild and its internal parallelism feature for compilation tests. 
* Affected package(s):Testsuite
> Testsuite: Adapt ctest scripts for use with cygwin

- Three/include/CGAL/Three/Scene_interface.h
Though not yet released ...
The documentation after the enum values signal, according to the text, documentation after the enum value but the used documentation starter `//!` is incorrect, should be `//!<`.
(see results on page doc_output/Three/group__PkgThreeRef.html)
Old:
and
New:
and
> Incorrect documentation for enum in Three package

- Triangulation_on_sphere_2/doc/Triangulation_on_sphere_2/Triangulation_on_sphere_2.txt
For the Triangulation_on_sphere_2 packages we get the incorrect links:
```
Checking ./doc_output/Triangulation_on_sphere_2/index.html
==============================================
Processing      file:///.../doc_output/Triangulation_on_sphere_2/index.html
List of broken links and other issues:
file:///...doc_output/Triangulation_on_sphere_2/index.html
Lines: 179, 191
Code: 200 (no message)
To do: Some of the links to this resource point to broken URI fragments
(such as index.html#fragment).
The following fragments need to be fixed:
Section_2D_Triangulations_Regular       Line: 191
Section_2D_Triangulations_Definitions   Line: 179
```
This has been corrected.
> Incorrect links in Triangulation_on_sphere_2

- Documentation/doc/biblio/cgal_manual.bib
Removing rather than updating because there is no exact match on nice (i.e. hal) platforms but it is easy enough to find anyway.
* Affected package(s): `Documentation`
* Issue(s) solved (if any): fix #5751
> Remove dead ftp link

- Nef_3/include/CGAL/Nef_3/Binary_operation.h
- Nef_3/include/CGAL/Nef_3/K3_tree.h
- Nef_3/include/CGAL/Nef_3/Nef_box.h
- Nef_3/include/CGAL/Nef_3/SNC_intersection.h
- Nef_3/include/CGAL/Nef_3/SNC_k3_tree_traits.h
- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
- Nef_3/include/CGAL/Nef_3/SNC_structure.h
- Nef_3/include/CGAL/Nef_polyhedron_3.h
Compiling CGAL with the define CGAL_NEF3_FACET_WITH_BOX set doesn't work. There are a number of compile errors and the implementation is missing here:
https://github.com/CGAL/cgal/blob/a8e87526348d2d1faa2ea893747314853ee6868d/Nef_3/include/CGAL/Nef_3/SNC_k3_tree_traits.h#L550-L560
As such I would assume that the code isn't tested or used publically, so I propose therefore that the code should be removed, and removing it correctly can be achieved using a tool called unifdef using the following: 
`grep CGAL_NEF3_FACET_WITH_BOX * -Rl | xargs unifdef -UCGAL_NEF3_FACET_WITH_BOX -m`
> Remove CGAL_NEF3_FACET_WITH_BOX

- Documentation/doc/Documentation/Third_party.txt
- Documentation/doc/Documentation/windows.txt
- Scripts/developer_scripts/create_new_release
Follow up of #5451
Thanks @albert-github for the report.
Modifications of `windows.txt` were already removed [here](https://github.com/CGAL/cgal/pull/5451/files#diff-f7a36d44b5e3f85dbf2f65258c85ce9327e0424bba4e7e488b5f197d47ba3b33) so I don't understand how they can still be here. I checked the status of the file after the merge of the PR and it was still here.
> remove remaining mentions to setup.exe

- Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
This PR fixes the warning (missing parameter in initializer list) introduced by PR #5587 :
```
missing initializer for member 'CGAL::Mesh_3::internal::Enriched_pixel` 
```
> Mesh_3 - fix missing initializer warning

- Installation/cmake/modules/FindOpenMesh.cmake
I have ran into the following compiling issue:
```
CMake Error at /lib/cmake/CGAL/FindOpenMesh.cmake:58 (target_link_libraries):
IMPORTED library can only be used with the INTERFACE keyword of
target_link_libraries
```
Not a CMake expert, but the proposed patch solved the issue for me.
* Affected package(s): CMake
> Set CMake imported OpenMesh library as INTERFACE

- .github/workflows/build_doc.yml
There is a wrong path in the script that builds the doc, in case there is an error during the building process.
* Affected package(s):CI
> Fix path to tmp.log

- CGAL_ImageIO/include/CGAL/Image_3_vtk_interface.h
Fix possible duplicate symbol:
`duplicate symbol 'CGAL::vtk_image_sharing_same_data_pointer(CGAL::Image_3&)'`
Proposed solution add `inline` to `vtk_image_sharing_same_data_pointer ` in `Image_3_vtk_interface.h` following approach with `read_vtk_image_data` in `read_vtk_image_data.h` 
* Affected package(s): CGAL_ImageIO
* License and copyright ownership: Unchanged
> Add inline vtk_image_sharing_same_data_pointer

- STL_Extension/include/CGAL/Object.h
In the assign operation of Object.h there is a check to see if obj is null: `if(obj) ... `.  however the function any_cast of boost any.hpp already makes the check as follows:
```c++
template<typename ValueType>
ValueType * any_cast(any * operand)
{
return operand && operand->type() == typeid(ValueType)
? &static_cast<any::holder<ValueType> *>(operand->content)->held
: 0;
}
```
Usually, a null check is not worth optimising away but given that this really calls `operator bool` of shared_ptr it does have an impact that shows up in the profiler. Either way, this PR makes the code simpler and cleaner. The CGAL_USE_ANY_BAD_CAST code is never used and would be a bad solution anyway.
* Affected package(s): STL_ext
* Issue(s) solved (if any): cleaning/performance
* License and copyright …
> Simplify assign in Object.h

- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Reflex_vertex_searcher.h
This simplifies the code in Reflex_vertex_searcher.h by utilising the right variables as an array (Object_handle instead of markedsf) so that a loop can be used instead of repeating the same code twice. There is a slightly different trace output format but I don't think that matters.
I don't think the existing code was a deliberate manual loop unrolling, and it should be up to the compiler to unroll loops for performance.
This also fixes a static analysis false positive where the analysis gets confused about the check against markedsf and thinks there is a dereference after null.
* Affected package(s): Convex_decomposition_3
* Issue(s) solved (if any): bugfix / cleaning
> Remove code duplication in Reflex_vertex_searcher.h

- Nef_2/include/CGAL/Nef_2/Segment_overlay_traits.h
- Nef_3/include/CGAL/Nef_3/Binary_operation.h
- Nef_3/include/CGAL/Nef_3/SNC_const_decorator.h
Following on from #5246 I've since discovered three places in the code where `#ifdef CGAL_NEF_DEBUG` is used to disable the compilation of various bits of code. This never worked because CGAL_NEF_DEBUG is defined at the top of the file.
Simply replacing these for the newly introduced `CGAL_USE_TRACE` define (introduced in #5246) solves the problem and ensures this extra code isn't included unless explicitly wanted.
* Affected package(s): Nef_2 / Nef_3
* Issue(s) solved (if any): bugfix
> Replace CGAL_NEF_DEBUG with CGAL_USE_TRACE

- Nef_3/include/CGAL/Nef_3/SNC_k3_tree_traits.h
In SNC_k3_tree_traits a map is used to store the results of point comparisons. Two techniques are used, one of which is supposed to exploit reference counting (whatever that means) and is enabled by the define `CGAL_NEF_EXPLOIT_REFERENCE_COUNTING`, however regardless of whether the macro is defined the class member `OnSideMapRC` is present. (since its default constructed this has an overhead as discussed before with 512 elements)
This PR simply places OnSideMapRC into an `#ifdef` block.
I also noticed that p1 is not passed by reference, which is probably unintentional but the fix too small for its own PR.
> Remove the OnSideMapRC when not needed

- Nef_3/include/CGAL/Nef_3/K3_tree.h
- Nef_3/include/CGAL/Nef_3/SNC_k3_tree_traits.h
- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
Compiling CGAL with the define `CGAL_NEF3_TRIANGULATE_FACETS` set (which also requires CGAL_NEF_EXPLOIT_REFERENCE_COUNTING otherwise there is a compile error) doesn't work. There is a compile error here: https://github.com/CGAL/cgal/blob/68c44a162df2c5577a7f5f51bf45ac1d349ed143/Packages/Nef_3/include/CGAL/Nef_3/SNC_point_locator.h#L250
Where `CT::Edge` should be preceded by a typename keyword. As such I would assume that the code isn't tested or used publically. I tested the code against the performance benchmark (spheregrid/shiftedspheregrid) and didn't find any performance benefit. I propose therefore that the code should be removed, and removing it correctly can be achieved using a tool called `unifdef` using the following: `grep CGAL_NEF3_TRIANGULATE_FACETS * -Rl | xargs unifdef …
> Remove CGAL_NEF3_TRIANGULATE_FACETS

- Nef_3/include/CGAL/Nef_3/SNC_const_decorator.h
- Nef_3/include/CGAL/Nef_3/SNC_decorator.h
- Nef_S2/include/CGAL/Nef_S2/Generic_handle_map.h
This removes code duplication between `SNC_const_decorator` and `SNC_decorator`. The additional template parameter `Traits`, uses `SNC_decorator_traits` to provide both const and non-const handles such that the SNC_decorator version of the code can be replaced by a template instantiation. 
Other functions can potentially be de-duplicated in the same way.
> Remove duplicate code in SNC_const_decorator/SNC_decorator

- Filtered_kernel/include/CGAL/Lazy_kernel.h
The Issue #5724 explains it all and the code was just copy pasted from the issue to the code. Thank you Marc.
I also reproduced the performance gain for the 3d periodic triangulation with a regular triangulation with constant weight.
I did not try to get rid of `LRint`.
* Issue(s) solved (if any): fix #5724
> fast dynamic_cast in Lazy_kernel::Construct_point_3

- Polyline_simplification_2/test/Polyline_simplification_2/CMakeLists.txt
- Polyline_simplification_2/test/Polyline_simplification_2/issue-5774.cpp
- Triangulation_2/include/CGAL/Triangulation_2/internal/Polyline_constraint_hierarchy_2.h
When simplifying a polyline constraint in a triangulation the Points_in_constraint_iterator permits to traverse the input sequence of points. This is broken.  This draft only adds debug code and not a fix.
This PR undoes the PR #4213. The vertex handle in the Node class survives a simplification as it it is in a `Compact_container` but if after the simplification the user adds a new constraint that will recycle the vertex object and put another point in there.
The real bug though was spotted by Mael in the function that removes the points in the skip list for which the vertex was removed.
* Affected package(s): Polyline Simplification
* Issue(s) solved (if any):  [stackoverflow](https://stackoverflow.com/questions/67855845/cgal-polyline-simplification-results-in-self-intersection)
* …
> Polyline_simplification: Bugfix in Points_in_constraint_iterator

- Documentation/doc/Documentation/Usage.txt
It was reported by the user that the current guide to compile CGAL examples with Qt5 on MacOS with brew is outdated:
-DQt5_DIR=/usr/local/opt/**qt**/lib/cmake/Qt5
and he could not succeed by following it.
I have checked that and indeed, after the Qt6 was introduced, the brew default Qt installation is Qt6, which is always linked to the `qt` folder whereas Qt5 is now linked to the `qt5` folder. I have updated the description to better explain how to link against Qt5.
* Affected package(s): `Documentation`
* Issue(s) solved (if any): reported in the mailing list 
* Feature/Small Feature (if any): doc bug fix
* Link to compiled documentation (obligatory for small feature): [docs](https://cgal.geometryfactory.com/~danston/Manual-qt5/usage.html#usage_configuring)
* License and copyright …
> MacOS Qt5 Guide Update

- Scripts/developer_scripts/run_testsuite_with_ctest
- Testsuite/test/parse-ctest-dashboard-xml.py
This PR should speed up by several hundreds of times the python script parsing the ctest results of a testsuite.
* Affected package(s):Testsuite
> Ctest Testsuite: Speed up python parsing script

- Filtered_kernel/include/CGAL/Lazy.h
In case `update_exact()` is called the rep stores a non null pointer in `et` which must be deleted before a re-assignment.
> PMP::Polyhedral_envelope:  Fix memory leak

- Kernel_23/include/CGAL/Bbox_2.h
- Kernel_23/include/CGAL/Bbox_3.h
- Kernel_23/test/Kernel_23/test_bbox.cpp
Adds some helpers to calculate the size of a Bbox in each dimension.
* Issue(s) solved (if any): N/A
* License and copyright ownership: CLA signed
> Bbox size helpers

- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
- Homogeneous_kernel/include/CGAL/Homogeneous/function_objects.h
- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/include/CGAL/Kernel/global_functions_2.h
- Kernel_23/include/CGAL/Kernel/global_functions_3.h
- Kernel_23/include/CGAL/Kernel/global_functions_internal_2.h
- Kernel_23/include/CGAL/Kernel/global_functions_internal_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_constructions_2.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_constructions_3.h
Adds a CGAL::midpoint() implementation for segments.
In the documentation:   [function ](https://cgal.github.io/5545/v0/Kernel_23/group__midpoint__grp.html) and [concept](https://cgal.github.io/5545/v0/Kernel_23/classKernel_1_1ConstructMidpoint__3.html)
* License and copyright ownership: CLA signed
> Segment_2/Segment_3 midpoint()

- Number_types/include/CGAL/GMP/Gmpq_type.h
- Number_types/include/CGAL/Gmpq.h
Is this  faster than a comparison with zero?    And in case we change code where we currently compare with zero, we have to find out if it becomes slower when we apply `is_zero()` to a double.  And what  about `> 0`  ?
> Number_types: Add Is_zero functor for Gmpq

- GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h
Do not clear the pos buffer of clipping plane, when clearing the basic viewer.
Otherwise, the clipping plane is no more drawn after a clear.
Recompute the clipping plane in initialize_buffers, since the bounding box is maybe not the same and so the size of the plane.
Now this pr is ready for testing.
> Basic viewer bugfix

- Three/doc/Three/PackageDescription.txt
Remove bibref in Three package as it is not in the package overview.
* Issue(s) solved (if any): fix #5786
> Three Documentation Fix

- Triangulation_on_sphere_2/doc/Triangulation_on_sphere_2/Triangulation_on_sphere_2.txt
Remove "of CGAL" from the intro since 
1) People reading the document probably already know its related to CGAL
2) It reads as: "the sphere of CGAL" instead of belonging to CGAL, you could use "This chapter describes CGAL's two-dimensional triangulations on the sphere." but I think it's superfluous.
* Affected package(s): Triangulations_on_sphere_2
* Issue(s) solved (if any): documentation grammar.
* Feature/Small Feature (if any): small
> Fix grammar in Triangulation_on_sphere_2

- Algebraic_foundations/doc/Algebraic_foundations/Concepts/FieldNumberType.h
- Algebraic_foundations/doc/Algebraic_foundations/Concepts/RingNumberType.h
The display of `CGAL::Interval_nt_advanced` is different from the other fields in the list
When looking at: https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.3-Ic-163/master/Algebraic_foundations/hasModels.html we see:
instead of:
Note: the difference for: CGAL::Interval_nt_advanced
Note: similar occurs also a bit further down the page.
> Inconsistent display of CGAL::Interval_nt_advanced in documentation

- Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
- Mesh_3/include/CGAL/Mesh_3/Mesh_complex_3_in_triangulation_3_base.h
- Mesh_3/include/CGAL/Mesh_3/Mesh_global_optimizer.h
- Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
- Mesh_3/test/Mesh_3/CMakeLists.txt
The work was already mostly done in PR #4892, but there was still two issues:
- `tbb::parallel_do` has been removed, and `tbb::parall_for_each` was to be used instead,
- the support for `tbb_hasher` has been removed.
This time, I have tested in a container were intel-oneapi-tbb-common-devel-2021.3.0-2021.3.0-511.noarch was installed, but not tbb version 2020.
* Issue(s) solved (if any): fix #5845
> Port Mesh_3 to oneAPI-TBB

- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Animate_mesh_plugin.cpp
Change behavior when reading the previous frame, so that it restores the previous state, and does not simply read the previous frame, which might not do anything if the impacted points are not the same in both frames.
* Affected package(s):Polyhedron demo
> Polyhedron_demo: Animate plugin

- .github/workflows/delete_doc.yml
Apparently git diff actually returns 0 if there is a diff.
> Online Doc: Fix condition for push

- Installation/cmake/modules/CGAL_add_test.cmake
Set CMP0064 to fix #5857. The software iso2mesh uses declarations like `cmake_minimum_required(VERSION 2.6.2)`. That unset `CMP0064`, that we require. Use a local `cmake_policy` command.
* Issue(s) solved (if any): fix #5857
> Set CMP0064 to fix #5857

- .github/install.sh
Add ITK as a dependency to our Github actions tests. For https://github.com/CGAL/cgal/pull/5597.
* Affected package(s): Github workflow
> Install ITK in Github action tests

- Number_types/include/CGAL/FPU.h
it breaks code using the intel compiler on windows
> Remove no longer needed __builtin_sqrt workaround

- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
- BGL/test/BGL/test_Face_filtered_graph.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
`Face_filtered_graph` defined its `property_map<CGAL::Face_filtered_graph<Graph, FIMap, VIMap, HIMap>, CGAL::XXX_index_t>::type` as its const type (a property binder to the underlying graph), which led to type conflicts in the `get()`. Also missing a `get(tag, graph)` for non-const filtered graphs.
This PR puts the index property map of a non-const FFG as a dynamic property map of the underlying graph (not some kind of unordered set despite a FFG being usually small because it feels better to spend memory than runtime).
> Fix index maps for non-const Face_filtered_graph

- Number_types/include/CGAL/FPU.h
Use unsigned long to get a 64bits type and avoid a warning about the wrong size for the type FPU_CW_t
* Affected package(s):Number_types
* Issue(s) solved (if any): fix #5864
> Number_types: Fix a typedef for aarch64

- Scripts/developer_scripts/run_testsuite_from_branch_name.sh
Remove the platform directory before running the filter testsuite if exists, and filter diff of files to ignore /doc files and every non .h or .cpp file.
> Scripts: Fix and enhance Filter testsuite

- Shape_detection/examples/Shape_detection/efficient_RANSAC_with_callback.cpp
- Shape_detection/include/CGAL/Shape_detection/Efficient_RANSAC/Efficient_RANSAC.h
This PR fixes multiple memory leaks in the Efficient RANSAC algorithm.
When running:
```
leaks -atExit -- ./efficient_RANSAC_with_callback
```
on `macOS`, the following output is revealed:
```
Process:         efficient_RANSAC_with_callback [36107]
Path:            /Users/USER/Documents/*/efficient_RANSAC_with_callback
Load Address:    0x101c1a000
Identifier:      efficient_RANSAC_with_callback
Version:         ???
Code Type:       X86-64
Platform:        macOS
Parent Process:  leaks [36106]
Date/Time:       2021-07-08 17:23:15.712 +0200
Launch Time:     2021-07-08 17:23:14.672 +0200
OS Version:      macOS 11.2.3 (20D91)
Report Version:  7
Analysis Tool:   /usr/bin/leaks
Physical footprint:         10.4M
Physical footprint (peak):  13.9M
----
leaks Report Version: 4.0
Process 36107: 830 …
```
> Fixed Memory Leaks in RANSAC

- BGL/include/CGAL/boost/graph/named_params_helper.h
- BGL/include/CGAL/boost/graph/parameters_interface.h
- Installation/CHANGES.md
- Point_set_processing_3/examples/Point_set_processing_3/registration_with_pointmatcher.cpp
- Point_set_processing_3/include/CGAL/pointmatcher/compute_registration_transformation.h
This PR solves the issue #5648 and provides support for the `libpointmatcher::GenericDescriptorOutlierFilter` to the CGAL `libpointmatcher` interface. Now it is possible to provide a scalar map that maps a point from input range to a scalar value so-called weight assigned to this point. These weights are then stored as a matrix and submitted to the `libpointmatcher`. The default weights are all set to one and the corresponding `libpointmatcher` descriptor is added.
* Issue(s) solved (if any): fix #5648
* Feature/Small Feature (if any): [Small Feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Extended_Support_For_Pointmatcher)
* Link to compiled documentation (obligatory for small feature): …
> [Small Feature] Support for libpointmatcher::GenericDescriptorOutlierFilter

- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
- Homogeneous_kernel/include/CGAL/Homogeneous/function_objects.h
- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/include/CGAL/Kernel/global_functions_2.h
- Kernel_23/include/CGAL/Kernel/global_functions_internal_2.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_new_2.h
Add the operator for four points describing two segments.
* Issue(s) solved (if any): fix #5653
* Link to the documentation:  [concept](https://cgal.github.io/5667/v2/Kernel_23/classKernel_1_1CompareSlope__2.html)  and [global function](https://cgal.github.io/5667/v2/Kernel_23/group__compare__slopes__grp.html#ga8d425470625e96c831173da960ec6552)
> Kernel: Add compare_slope with 4 points

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_clip.cpp
Skip shared edges which are already border edges in split_along_edges in Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h.
* Issue(s) solved: fix #5867
> Skip shared edges which are border edges

- TDS_2/include/CGAL/Triangulation_data_structure_2.h
- TDS_2/include/CGAL/Triangulation_ds_face_base_2.h
- TDS_3/include/CGAL/Triangulation_data_structure_3.h
- Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_triangulation_2.h
- Triangulation_3/test/Triangulation_3/include/CGAL/_test_cls_triangulation_3.h
Fix a number of small abuses resulting in UB / sanitizer errors.
Minor optimization in `TDS_3::copy_tds()`.
* Affected package(s): `TDS_23`, `Triangulation_23`
* Issue(s) solved (if any): fix #5855
* License and copyright ownership: No change
In dim -1, there is only one vertex and one face, no neighbor
in position '0' to set.
> Fix some UB / sanitizer errors

- Documentation/doc/scripts/compare_testsuites.sh
- Documentation/doc/scripts/documentation_parser.py
Before this patch `documentation_parser.py`, was a Python2 script. Move to python3 (using `2to3`). The long term solution would be to port all of our Python2 scripts. See #4448.
> Port documentation_parser.py to python3

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h
As we have no idea what to `reserve()`  for a `vector` in which we collect duplicates, we better switch to a `deque`. This probably only plays a role in case of many duplicates.
> PMP: Use deque instead of vector

- Documentation/doc/resources/1.8.20/BaseDoxyfile.in
```
warning: Tag 'LATEX_SOURCE_CODE' at line 1971 of file '.../doc_dxy/BaseDoxyfile' has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'RTF_SOURCE_CODE' at line 2061 of file '.../doc_dxy/BaseDoxyfile' has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'DOCBOOK_PROGRAMLISTING' at line 2166 of file '.../BaseDoxyfile' has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
```
these tags have been declared obsolete (in the current master version), so they should be removed..
CGAL doesn't use the involved formats so this has no influence on …
> Removing obsolete doxygen settings

- Mesh_3/doc/Mesh_3/Mesh_3.txt
Currently we get a number of warnings when building the documentation for Mesh_3:
```
/home/cgal-testsuite/cgal_doc_build/CGAL-5.3.1-I-169/doc/Mesh_3/Mesh_3.txt:743: warning: unable to resolve reference to 'CGAL/Mesh_3/initialize_triangulation_from_labeled_image.h\' for \ref command
/home/cgal-testsuite/cgal_doc_build/CGAL-5.3.1-I-169/doc/Mesh_3/Mesh_3.txt:801: warning: unable to resolve reference to 'Mesh_3/random_labeled_image.h\' for \ref command
/home/cgal-testsuite/cgal_doc_build/CGAL-5.3.1-I-169/doc/Mesh_3/Mesh_3.txt:817: warning: unable to resolve reference to 'CGAL/Mesh_3/initialize_triangulation_from_gray_image.h\' for \ref command
```
Note the backslash at the end of the file name.
Most likely an attempt was made to escape the dot to not have it as part of the filename, though …
> Warnings Mesh_3 regarding non existing file (documentation)

- Subdivision_method_3/include/CGAL/Subdivision_method_3/subdivision_masks_3.h
This adds an assertion to subdivision_masks_3.h which prevents a static analysis wanting about dividing by zero.
* Affected package(s): Subdivision methods
* Issue(s) solved (if any): bugfix / static analysis
> Fix division by zero in subdivision_masks_3.h

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
Running vtune for corefinement of meshes with coplanar faces showed that we can improve by replacing by a hash map.
Astonishingly it degraded performance when also doing it for another container [here](https://github.com/CGAL/cgal/blob/master/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h#L187)
> PMP Corefinement: Replace containers to make it faster

- Filtered_kernel/include/CGAL/Filtered_kernel/Cartesian_coordinate_iterator_2.h
- Filtered_kernel/include/CGAL/Filtered_kernel/Cartesian_coordinate_iterator_3.h
- Filtered_kernel/test/Filtered_kernel/test_cartesian_const_iterator.cpp
This little PR proposes a fix for the issue #5878 by changing some return types in the `Construct_cartesian_iterator_2` and `Construct_cartesian_iterator_3` classes of the `Filtered_kernel`.
Tasks:
* Affected package(s): `Filtered_kernel`
* Issue(s) solved (if any): fix #5878
* Feature/Small Feature (if any): bug
> Filtered Kernel Construct Cartesian Iterator Return Type Fix

- GraphicsView/include/CGAL/Basic_shaders.h
In 5.3, the code for the compatibility shaders has been broken. It uses GLSL 150 syntax, which is the same syntax as the non-compatibility shader code. 
* Issue(s) solved (if any): fix #5933
> Basic_viewer: Restore compatibility shader code

- Documentation/doc/Documentation/advanced/Configuration_variables.txt
Add instructions for OneTBB usage in the `Summary of CGAL's Configuration Variables` section.
* Issue(s) solved (if any): fix #5948
> Update the doc for TBB cmake usage

- Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/measure.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/measures_test.cpp
Add functions for the case that we only want to compare squared distances (for example for a priority queue).
* Small Feature:  [link ](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/PMP::squared_edge_length)
* Link to compiled documentation (obligatory for small feature) 
- [`squared_edge_length()`](https://cgal.github.io/5941/v2/Polygon_mesh_processing/group__measure__grp.html#ga30fa03722cd7aa599f6dcb115f54fec5)
- [`squared_face_area()`](https://cgal.github.io/5941/v2/Polygon_mesh_processing/group__measure__grp.html#ga6eda3738815fd678df225f79ccfc3e03)
> Polygon Mesh Processing:  Add measure functions not using sqrt

- Voronoi_diagram_2/include/CGAL/Voronoi_diagram_2/Handle_adaptor.h
Make `CGAL::VoronoiDiagram_2::Internal::Handle_adaptor<T>` a model of `Handle`. Fix issue #5961.
* Affected package(s): Voronoi_diagram_2
* Issue(s) solved (if any): fix #5961
> VD_2: Make Handle_adaptor a model of Handle

- Filtered_kernel/include/CGAL/internal/Static_filters/Collinear_3.h
* Affected package(s): `Filtered_kernel`
> Add missing profiler macros in the static filter of Collinear_3 (5.2)

- Filtered_kernel/include/CGAL/internal/Static_filters/Collinear_3.h
* Affected package(s): `Filtered_kernel`
>  Add missing profiler macros in the static filter of Collinear_3 (5.3)

- GraphicsView/include/CGAL/Buffer_for_vao.h
PR #5096 fixes a bug in the is_facet_convex.
It works for one case I tested. But the solution is still not correct. We cannot return true after one local test, even in the case of aligned points.
Right, result in master, left result for this branch.
* Issue(s) solved (if any): fix #4002
> GraphicsView: Bug Fix in Buffer_for_vao::is_facet_convex()

- Arrangement_on_surface_2/include/CGAL/Arr_counting_traits_2.h
- Arrangement_on_surface_2/include/CGAL/IO/Fig_stream.h
- CGAL_Core/include/CGAL/CORE/BigFloat_impl.h
- CGAL_Core/include/CGAL/CORE/CoreAux_impl.h
- CGAL_Core/include/CGAL/CORE/Real_impl.h
- Cone_spanners_2/include/CGAL/Cone_spanners_2/Plane_scan_tree_impl.h
- Nef_3/include/CGAL/Nef_3/OGL_helper.h
- Number_types/include/CGAL/FPU.h
- Point_set_processing_3/include/CGAL/jet_estimate_normals.h
- Point_set_processing_3/include/CGAL/mst_orient_normals.h
- Point_set_processing_3/include/CGAL/pca_estimate_normals.h
- Poisson_surface_reconstruction_3/include/CGAL/Poisson_reconstruction_function.h
- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
- Stream_support/include/CGAL/IO/trace.h
- Surface_mesh_segmentation/include/CGAL/Surface_mesh_segmentation/internal/auxiliary/graph.h
- Testsuite/include/CGAL/Testsuite/vc_debug_hook.h
As pointed out by @lrineau most of the usages ARE safe, in the sense that the sizes of source and target memory are constants known at compile time.
* Issue(s) solved (if any): fix #5991
> Deal with memset, memcpy, fscanf...    and their safe equivalents

- BGL/include/CGAL/boost/graph/iterator.h
Fix uninitialized member (winding) in iterator.h
* Issue(s) solved (if any): fix #5181 
* Feature/Small Feature (if any): bugfix
* License and copyright ownership: returned to cgal authors
> Fix uninitialized member in iterator.h

- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Single_wall_creator.h
Fix uninitialized members (sncp, pl) in Single_wall_creator.h
* Affected package(s): Convex_decomposition
> Fix uninitialized member in Single_wall_creator.h

- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Edge_sorter.h
Fix uninitialized members (sncp, pl) in Edge_sorter.h
* Affected package(s): Convex_decomposition
> Fix uninitialized member in Edge_sorter.h

- Nef_3/include/CGAL/Nef_3/K3_tree.h
Fix uninitialized members (root_node, first_segment) in K3_tree.h
> Fix uninitialized member in K3_tree.h

- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Ray_hit_generator2.h
Fix uninitialized members (sncp, pl, edge_splitted, vertex_added) in Ray_hit_generator2.h
* Affected package(s): Convex_decomposition_3
> Fix uninitialized members in Ray_hit_generator2.h

- TDS_3/include/CGAL/internal/Triangulation_ds_iterators_3.h
Fix uninitialized member (_tds) in Triangulation_ds_iterators_3.h
* Affected package(s): TDS_3
> Fix uninitialized member in Triangulation_ds_iterators_3.h

- Triangulation_3/include/CGAL/Triangulation_3.h
Fix uninitialized member (t) in Triangulation_3.h
> Fix uninitialized member in Triangulation_3.h

- Nef_3/include/CGAL/Nef_3/SNC_io_parser.h
Fix uninitialized members (reduce, sorted, addInfiBox, i, vn, en, fn, cn, sen, sln, sfn) in SNC_io_parser.h
> Fix uninitialized member in SNC_io_parser.h

- AABB_tree/doc/AABB_tree/Concepts/AABBGeomTraits.h
- AABB_tree/doc/AABB_tree/Concepts/AABBRayIntersectionGeomTraits.h
- AABB_tree/doc/AABB_tree/Concepts/AABBRayIntersectionTraits.h
- AABB_tree/doc/AABB_tree/PackageDescription.txt
- AABB_tree/include/CGAL/AABB_traits.h
- AABB_tree/test/AABB_tree/aabb_test_is_ray_intersection_geomtraits.cpp
- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
- Homogeneous_kernel/include/CGAL/Homogeneous/function_objects.h
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_constructions_3.h
- Spatial_searching/doc/Spatial_searching/Concepts/SearchGeomTraits_3.h
The description of the requirements within `AABBGeomTraits` (esp. `Do_intersect_3` & `Intersect_3`) did not match the code. Some more requirements also seem poorly documented and even useless (`Construct_min/max_vertex_3`, `Construct_iso_cuboid_3`), but I have left them there in case the traits class is used somewhere else.
Also add `Construct_projected_point_3(Point_3, Point_3)` for kernel models. Intentionally not a new requirement of the concept `Kernel` since this only arises if you use a point as datum in the `AABB_tree`.
CC: @palliez 
* Affected package(s): `AABB_tree`, kernels
* Issue(s) solved (if any): fix #6013
> AABB tree concept fixes + Construct_projected_point_3(P3, P3)

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/helper.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap_vertices.h
- KD tree based snapping (faster, easier to track progress)
- Don't collapse fixed vertices in the preprocessing
- Added a visitor to track the algorithm
- Better "quick exits"
- Minor improvements across the board
> Improvements for PMP's snapping code

- Point_set_processing_3/include/CGAL/IO/read_off_points.h
- Point_set_processing_3/include/CGAL/IO/read_xyz_points.h
- Point_set_processing_3/test/Point_set_processing_3/test_deprecated_io_point_set.cpp
After reading a line too much with a  `while(getline())` we must reset the failbit.
I spotted this while trying to track down a runtime error in the [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-7/Point_set_processing_3/TestReport_Sosno_MSVC-2019-Community-Release.gz)
> Unset fail bit and add assertions about the state of a stream

- Subdivision_method_3/include/CGAL/Subdivision_method_3/subdivision_masks_3.h
This PR introduces a simple fix for Doo-Sabin subdivision, with regard to the issue described in #6073.  The problem is circumvented by simply switching a couple of `size_t` integers in the mask calculations for corner nodes to plain old (signed) `int`s.
I have tested the code with a `CGAL::Cartesian<CGAL::Gmpq>` kernel and it seems to be working fine.
> Fix Doo Sabin subdivision for Gmpq-based kernels

- Stream_support/examples/Stream_support/CMakeLists.txt
<details><summary>Fix a bad merge from PR "Re-organize I/O #4255". Click to see the details...</summary>
Before my fix, the CMakeLists.txt could be sum-up that way:
```cmake
find_package(CGAL REQUIRED)
find_package(Boost QUIET)
if(NOT Boost_FOUND)
message(
STATUS "This project requires the Boost library, and will not be compiled.")
create_single_source_cgal_program( "Point_WKT.cpp" )
else ()
message(STATUS "This project requires the CGAL library, and will not be compiled.")
return()
endif()
```
So, on *all platform*, as Boost is mandatory and always found, the
behavior was to display "This project requires the CGAL library, and
will not be compiled." and return, without configuring any target.
I have simplified the `CMakeLists.txt` to the simplest:
```cmake
cmake_minimum_required(VERSION …
```
> Fix a bad merge from PR "Re-organize I/O #4255"

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
The Hausdorff distance code makes a copy of the provided sample points and sorts them spatially such that the hints provided to the AABB tree will be good. There is an apparent mistake in the code though and instead of the spatially sorted sample points, the original (unsorted) ones are given to the AABB tree. The sorted ones are in fact never used.
This PR changes the code such that the sorted points are used.
> Mesh distance: use spatially sorted sample points

- BGL/include/CGAL/boost/graph/IO/PLY.h
- BGL/include/CGAL/boost/graph/named_params_helper.h
- Classification/include/CGAL/Classification/Point_set_neighborhood.h
- Point_set_processing_3/include/CGAL/estimate_scale.h
- Property_map/include/CGAL/property_map.h
- Stream_support/include/CGAL/IO/Generic_writer.h
- Stream_support/include/CGAL/IO/PLY/PLY_writer.h
- Stream_support/include/CGAL/IO/STL.h
Fix and complement https://github.com/CGAL/cgal/pull/6038
`Identity_map` is mutable
> restore mutable property of the pmap

- Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Conic_x_monotone_arc_2.h
- Installation/CHANGES.md
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/doc/Kernel_23/Concepts/Kernel.h
- Kernel_23/doc/Kernel_23/PackageDescription.txt
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/include/CGAL/Kernel/interface_macros.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_vector_3.h
- Nef_3/include/CGAL/Nef_3/bounded_side_3.h
Add a function object to the concept `Kernel` that enables to find any dimension of a 3D vector that is different from zero. 
* Feature/Small Feature (if any): [link](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/NonZeroDimension_3)
* Link to compiled documentation:  [link](https://cgal.github.io/6102/v3/Kernel_23/classKernel_1_1NonZeroDimension__3.html)
* License and copyright ownership: not changed
> Kernel_23: Add NonZeroDimension_3

- CGAL_Core/include/CGAL/CORE/Expr_impl.h
Fix bug https://gitlab.com/Oslandia/SFCGAL/-/issues/245. Remove the explicit template instanciation from CGAL_Core.
For CGAL-5.3.x
* Affected package(s): CGAL_Core
> CGAL Core: Remove explicit instanciations: CGAL is header-only!

- Point_set_processing_3/include/CGAL/remove_outliers.h
Bug in current code: when no outliers are found, `f2r` is `sorted_points.end()`. So, `if (sit == f2r)` is never true, and `out` keeps its initial value, which is `points.begin()`.
Note: if we don't care about sorting the elements (I'm not sure), a probably better fix would be to test `f2r` and skip the whole loop if it is equal to `sorted_points.end()`. I let you decide what is best.
Side remark: at line 250, why is `threshold_distance` captured by reference?
> Bug fix: `remove_outliers` was removing ALL points when no outliers were found

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/MainWindow.h
- Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_normal_estimation_plugin.cpp
Create normal map only if normal are estimated.
@lrineau `MainWindow::filterOperations(bool)` should be called once the normals are estimated as normal orientation should then become applicable. But it is not accessible from the plugin. If I manually unselect and select the item,  `MainWindow::filterOperations(bool)` is called but a call to `Scene::setSelectedItem(int)` does not help. Any idea or do I need to modify an interface?
> Create normal map only if normal estimation is done

- Cone_spanners_2/include/CGAL/Compute_cone_boundaries_2.h
- Documentation/doc/Documentation/Developer_manual/Chapter_portability.txt
- Polyhedron/doc/Polyhedron/CGAL/Polyhedron_3.h
Some parts were due to to the markdown handling of 4 spaces meaning code converted to code and this was not the intention.
> Remove some unintended artifacts from the documentation

- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
`CGAL::IO::read_polygon_mesh()` does not clear the mesh before writing, and does not clear the mesh if it fails to read.
In the demo, we try to read via `CGAL::IO::read_polygon_mesh()` first, and if that fails through the `read_polygon_soup -> repair -> orient -> soup_to_mesh` pipeline. However, the mesh needs to be cleared before calling that pipeline.
> Fix not clearing mesh after failing to read

- Point_set_processing_3/include/CGAL/IO/read_off_points.h
- Point_set_processing_3/include/CGAL/IO/read_xyz_points.h
- Point_set_processing_3/include/CGAL/IO/write_off_points.h
- Point_set_processing_3/test/Point_set_processing_3/test_deprecated_io_point_set.cpp
- Point_set_processing_3/test/Point_set_processing_3/test_read_write_point_set.cpp
Some cleaning while investigating whether readers should return an error if a normal map is passed (see https://github.com/CGAL/cgal/issues/6125#issuecomment-970724654).
* Affected package(s): `Point_set_processing_3`
> Minor improvements for OFF/XYZ point set IO

- Barycentric_coordinates_2/doc/Barycentric_coordinates_2/Concepts/BarycentricTraits_2.h
- Kernel_23/doc/Kernel_23/CGAL/Projection_traits_3.h
- Kernel_23/doc/Kernel_23/CGAL/Projection_traits_xy_3.h
- Kernel_23/doc/Kernel_23/dependencies
- Triangulation_2/doc/Triangulation_2/Concepts/ConstrainedTriangulationTraits_2.h
- Triangulation_2/doc/Triangulation_2/Concepts/DelaunayTriangulationTraits_2.h
- Triangulation_2/doc/Triangulation_2/Concepts/TriangulationTraits_2.h
Add link [here](https://cgal.geometryfactory.com/CGAL/doc/master/Triangulation_2/classConstrainedTriangulationTraits__2.html)
Add namespace `Barycentric_coordinates` [here](https://cgal.geometryfactory.com/CGAL/doc/master/Kernel_23/classCGAL_1_1Projection__traits__xy__3.html).
> Fix links concerning Projection_traits_3

- Nef_2/include/CGAL/Nef_2/Polynomial_impl.h
Protect code that gets only used when tracing is switched on.
* Affected package(s): Convex_decomposition_3
* Issue(s) solved (if any): fix #0000, fix #6165
> Convex_decomposition_3: Address warning issued by clang

- Convex_hull_3/include/CGAL/Convex_hull_face_base_2.h
- Convex_hull_3/include/CGAL/Convex_hull_traits_3.h
- Convex_hull_3/include/CGAL/Convex_hull_vertex_base_2.h
- Convex_hull_3/include/CGAL/convex_hull_3.h
- Convex_hull_3/package_info/Convex_hull_3/dependencies
- Convex_hull_3/test/Convex_hull_3/quickhull_degenerate_test_3.cpp
- Optimal_bounding_box/package_info/Optimal_bounding_box/dependencies
- Polytope_distance_d/package_info/Polytope_distance_d/dependencies
- TDS_2/include/CGAL/boost/graph/graph_traits_Triangulation_data_structure_2.h
- TDS_2/include/CGAL/boost/graph/internal/graph_traits_2D_TDS_helper.h
- TDS_2/include/CGAL/boost/graph/properties_Triangulation_data_structure_2.h
- Triangulation_2/include/CGAL/boost/graph/internal/graph_traits_2D_triangulation_helper.h
- Triangulation_2/include/CGAL/boost/graph/internal/properties_2D_triangulation.h
`Convex_hull_3` (and packages including `Convex_hull_3`) had a slim dependency to `Triangulation_2` due to using `Triangulation_vertex_base_with_info_2` and `Triangulation_face_base_2`, and accidentally pulling `Triangulation_2` graph traits while using `TDS_2`'s graph traits.
This PR puts the TDS2 graph traits where they ought to be and add `Convex_hull_vertex_base_2` (pretty much a clone of  `Triangulation_vertex_base_with_info_2`) to get rid of the `Triangulation_2` dependency.
* Affected package(s):  `Convex_hull_3`, `Triangulation_2`, `TDS_2`
> Avoid some superfluous Triangulation_2 dependencies

- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/MVC_post_processor_3.h
Hide a `std::cerr` message behind debug macros.
* Issue(s) solved (if any): cgal-discuss
> Silence warning message in ARAP

- Polyhedron/demo/Polyhedron/MainWindow.cpp
Fix bug introduced in #6019 (cherry-picked in 5.3.x)
Seems that I did not understand correctly the doc here:
https://doc.qt.io/qt-5/qkeysequence.html#QKeySequence-2
> Fix shortcut composition

- Testsuite/test/parse-ctest-dashboard-xml.py
CTest Testsuite: resilience to non-UTF8 characters, use the method `backslashreplace` to deal with non-UTF8 characters.
See https://docs.python.org/3/library/codecs.html#error-handlers
* Affected package(s): Testsuite
> CTest Testsuite: resilience to non-UTF8 characters

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
needed only if Q_OBJECT or other macros are in the file
> Remove useless moc include

- Arrangement_on_surface_2/demo/Arrangement_on_surface_2/AlgebraicCurveParser.cpp
- CGAL_ImageIO/include/CGAL/SEP_header.h
fixes 
```
/srv/CGAL/www/Members/testsuite/CGAL-5.4-Ic-121/Polyhedron_Demo/TestReport_lrineau_ArchLinux-clang-CXX20-Release.gz:/usr/local/boost/include/boost/spirit/include/phoenix_core.hpp:12:1: warning: This header is deprecated. Use <boost/phoenix/core.hpp> instead. [-W#pragma-messages]
/srv/CGAL/www/Members/testsuite/CGAL-5.4-Ic-121/Polyhedron_Demo/TestReport_lrineau_ArchLinux-clang-CXX20-Release.gz:/usr/local/boost/include/boost/spirit/include/phoenix_operator.hpp:12:1: warning: This header is deprecated. Use <boost/phoenix/operator.hpp> instead. [-W#pragma-messages]
/srv/CGAL/www/Members/testsuite/CGAL-5.4-Ic-121/Polyhedron_Demo/TestReport_lrineau_ArchLinux-clang-CXX20-Release.gz:/usr/local/boost/include/boost/spirit/include/phoenix_object.hpp:12:1: warning: This header is …
```
> include non-deprecated headers

- Mesh_3/include/CGAL/Polyhedral_complex_mesh_domain_3.h
- Polyhedron/demo/Polyhedron/C3t3_type.h
- Polyhedron/demo/Polyhedron/Plugins/IO/Surf_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.h
After reading a polyhedral complex from file format `.surf`, the demo is now able to run Mesh_3 on the corresponding polyhedral complex.
This PR also fixes the class `Polyhedral_complex_mesh_domain_3` to make it work with `Surface_mesh` as underlying polyhedron type - some `typedef`'s had to be made public.
* Affected package(s): Mesh_3, Polyhedron demo
> Mesh a polyhedral complex in Polyhedron demo

- Box_intersection_d/include/CGAL/Box_intersection_d/segment_tree.h
The motivation for this PR was initially to suppress a static analysis warning. The error reported was that in the constructor initializer list that `this` is not initialized when reading `dist` since it depends on the member variable  `size` which in turn depends on `end` and `begin` However the initialization order is correct so it's not a problem. I did feel however that the approach here wasn't very conventional, what might be called a code smell, rather than an issue. 
Instead, this PR really is just a tidy up of the `Iterative_radon` class, by moving the dependencies of the generator out of the class it potentially allows different generators to be plugged in if dependency injection is desired, for example in unit tests and so on. It just happens to also suppress a false positive …
> Dependency inversion in Iterative_radon of segment_tree.h

- Nef_3/include/CGAL/Nef_3/K3_tree.h
- Nef_3/include/CGAL/Nef_3/SNC_k3_tree_traits.h
- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
Looking carefully at the code in K3_tree and running it through a profiler it can be seen that the code firstly creates an `Object_list` of vertices, edges, and facets. It then spends substantial amount of time unpicking the object list, and casting each object back into vertices/edges/facets to build the K3_tree. While the casts themselves are not very expensive, applying the `make_object` and `CGAL::assign` lavishly so many items does add up to significant overhead. By simply passing separate lists of Vertices, Edges, and Facets much of this casting is avoided and the performance can be boosted. Using the Nef_3_benchmark with spheregrid/shiftedspheregrid a performance gain of 10% can be observed. The Object lists are created at the point a K3_tree `Node` is created, so as to be …
> 18% performance boost in Nef_3 K3_tree.

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_mesh_to_polygon_soup.h
`polygon_soup_to_polygon_mesh()` allows points to be of type `std::array<FT, 3>`, this PR allows the reverse.
> Allow polygon soups to use an `std::array` point type in PM_to_PS

- BGL/include/CGAL/boost/graph/parameters_interface.h
- Mesh_3/include/CGAL/Mesh_3/Sliver_perturber.h
- Polyline_simplification_2/include/CGAL/Polyline_simplification_2/simplify.h
- STL_Extension/include/CGAL/Modifiable_priority_queue.h
- STL_Extension/include/CGAL/STL_Extension/internal/boost/mutable_queue.hpp
- STL_Extension/include/CGAL/STL_Extension/internal/boost/relaxed_heap.hpp
- STL_Extension/test/STL_Extension/test_Modifiable_priority_queue.cpp
- Surface_mesh_simplification/doc/Surface_mesh_simplification/CGAL/Surface_mesh_simplification/edge_collapse.h
- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/edge_collapse.h
- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/internal/Edge_collapse.h
Add an template parameter to `Modifiable_priority_queue` that enables us to pick the relaxed heap instead of the mutable heap.
This enables us to offer in the API of SMS a parameter to use a relaxed ordering to get faster mesh simplification if cost ordering can be relaxed.
On Iphigenia with default cost/placement I have with the non-relaxed heap:
```
1002507 edges removed.
52761 final edges.
Time elapsed: 12418ms
```
and with the relaxed heap:
```
1002507 edges removed.
52761 final edges.
Time elapsed: 10428ms
```
Note that I also imported the boost header because in recent boost version it triggers a deprecation warning.
> Add option to use a relaxed order

- Poisson_surface_reconstruction_3/include/CGAL/poisson_surface_reconstruction.h
- Scale_space_reconstruction_3/doc/Scale_space_reconstruction_3/PackageDescription.txt
Fixed a typo in the intro of [Scale-Space Surface Recontruction](https://doc.cgal.org/latest/Manual/packages.html#PkgScaleSpaceReconstruction3) and fixed #6220
> typo in the intro of 'Scale-Space Surface Reconstruction' and #6220

- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/internal/Edge_collapse.h
Introduced in 5.5
Fix this warning [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-137/Surface_mesh_simplification_Examples/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz).
> fix warning 

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/compute_c3t3_statistics.h
Warning seen in the testsuite
```
/mnt/testsuite/include/CGAL/Tetrahedral_remeshing/internal/compute_c3t3_statistics.h:50:10: warning: variable 'total_angle' set but not used [-Wunused-but-set-variable]
```
computing the average angle does not make much sense so let's just remove it
> Tet remeshing - fix warning

- Installation/include/CGAL/Installation/internal/enable_third_party_libraries.h
- Installation/include/CGAL/config.h
The warning must be put in quotes.
The check for gmp.h does not work for VC2015 so we have to disable it.
This PR fixes [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-141/AABB_tree_Demo/TestReport_Christo_MSVC2015-Release-64bits.gz)
* Affected package(s): Installation   and the warning shows up in AABB Tree
> Installation:  Fix issues for CGAL_WARNING

- Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h
Compiling `Advancing_front_surface_reconstruction` with `CGAL::Simple_cartesian<float>` currently fails:
```
/CGAL-5.3.1/include/CGAL/Advancing_front_surface_reconstruction.h: In instantiation of ‘void CGAL::Advancing_front_surface_reconstruction<B, C>::extend() [with Dt = CGAL::Delaunay_triangulation_3<Kernel, CGAL::Triangulation_data_structure_3<CGAL::Advancing_front_surface_reconstruction_vertex_base_3<Kernel>, CGAL::Advancin
g_front_surface_reconstruction_cell_base_3<Kernel> >, CGAL::Location_policy<CGAL::Fast> >; P = Priority]’:
/CGAL-5.3.1/include/CGAL/Advancing_front_surface_reconstruction.h:804:21:   required from ‘void CGAL::Advancing_front_surface_reconstruction<B, C>::run(double, double) [with Dt = CGAL::Delaunay_triangulation_3<Kernel, …
```
> Advancing Front Surface Reconstruction: allow float

- Hash_map/test/Hash_map/Hash.cpp
Initialize the point to avoid a warning in a [test program](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-141/Hash_map/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz)
* Affected package(s): Hash_map
> Hash_map:  Fix warning in test case

- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
- BGL/test/BGL/test_Face_filtered_graph.cpp
- Optimal_bounding_box/include/CGAL/Optimal_bounding_box/oriented_bounding_box.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polygon_mesh.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/refine.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_self_intersections.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
- Simplify zone expansion (removed code treating non-manifold zones --> ensure manifoldness through expansion).
- Add repair when the zone is not a topological disk but preserve_genus is false
- Use OBB to avoid overly large compactifications
- Fix "local" variable: actually use all strategy (constrained/smoothing/etc.)
- Add adapt() to sample and adapt local hole filling patches
- Better patch compatibility checks
- Misc cleaning
TODO
> Improve self-intersection repair code

- Stream_support/include/CGAL/IO/OFF/File_scanner_OFF.h
Try to fix this warning [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-I-134/Nef_3_Examples/TestReport_lrineau_ArchLinux-CXX17-Release.gz)
```
/mnt/testsuite/include/CGAL/IO/OFF/Scanner_OFF.h:169:39: warning: ‘no’ may be used uninitialized in this function [-Wmaybe-uninitialized]
169 |             for (std::size_t i = 0; i < no; ++i) {
|                                     ~~^~~~
/mnt/testsuite/include/CGAL/IO/OFF/Scanner_OFF.h:163:25: note: ‘no’ was declared here
163 |             std::size_t no;
```
> Fix warnings

- Voronoi_diagram_2/test/Voronoi_diagram_2/CMakeLists.txt
Do not run the tests simultaneously, as the tests write and then read in a file with an identical name.
* Affected package(s): Voronoi
> Voronoi Diagram: Do not run tests simultaneously

- Mesh_3/include/CGAL/Mesh_3/Mesh_global_optimizer.h
With the option `/permissive-` some of the tests of `Mesh_3` do not compile. 
I could boil it down to this [gist](https://gist.github.com/afabri/0416bebec1c32fb4efd6632446698972).
The fix is to move the counter in the base class and add a function to increment it.
> Mesh_3: Fixes for VC++ with option /permissive-

- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/Periodic_2_triangulation_2.txt
When building the Periodic_2_triangulation_2 documentation we get the warning:
```
/home/cgal-testsuite/cgal_doc_build/CGAL-5.5-Ic-3/doc/Periodic_2_triangulation_2/Periodic_2_triangulation_2.txt:202: warning: End of list marker found without any preceding list items
```
This has been corrected.
> Warning when building Periodic_2_triangulation_2 documentation

- Polynomial/test/Polynomial/test_polynomial.h
Fix  for an assertion in the [Polynomial testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-I-4/Polynomial/TestReport_Sosno_MSVC-2019-Community-Release.gz) which is there since ever.
For testing I/O we write to an `ostringstream` and read back from it, but we forgot to call `precision(17)`.   
No idea why we only have this problem with VC++.
* Affected package(s): Polynomial
> Set precision of the ostringstream

- HalfedgeDS/examples/HalfedgeDS/hds_prog_compact2.cpp
Try to workaround this [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-10/HalfedgeDS_Examples/TestReport_lrineau_Fedora-with-LEDA.gz)
```
/home/cgal_tester/build/src/cmake/platforms/Fedora-with-LEDA/test/HalfedgeDS_Examples/hds_prog_compact2.cpp:42:36: warning: array subscript -1 is outside array bounds of ‘std::pair<CGAL::HalfedgeDS_in_place_list_halfedge<My_halfedge<CGAL::HalfedgeDS_list_types<Traits, My_items, std::allocator<int> > > >, CGAL::HalfedgeDS_in_place_list_halfedge<My_halfedge<CGAL::HalfedgeDS_list_types<Traits, My_items, std::allocator<int> > > > > [1]’ [-Warray-bounds]
42 |         return HDS::halfedge_handle( &* h - 1);
|                ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
```
> Workaround warnings

- Polynomial/test/Polynomial/test_polynomial.h
Locally in the IO test function set the  rounding mode to nearest to avoid a known VC++ bug.
So we can keep the intended check that when rounding up the Modular Arithmetic for Polynomials works correctly.
* Affected package(s): Polynomial
* Issue(s) solved (if any): fix #6272
> Polynomial: Workaround for VC bug when cout << double  while rounding up

- Intersections_3/include/CGAL/Intersections_3/internal/Bbox_3_Segment_3_do_intersect.h
- Number_types/test/Number_types/CMakeLists.txt
- Number_types/test/Number_types/Exact_rational.cpp
This PR fixes a problem with the GMP backend in `boost::multiprecision`. 
The failure of the [Intersections_3 testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-2/Intersections_3/TestReport_Sosno_MSVC-2022-Preview-Release.gz) for VC++ comes from the error in  `operator-()`.    The type `CGAL::Exact_rational` is `boost::multiprecision::number<struct boost::multiprecision::backends::gmp_rational,1>`  on this platform and the boost version is 1_78.       When I use `CGAL::Gmpq` directly or if I use `boost::multiprecision::cpp_rational` there is no problem.  
The `operator-()`  is used [here](https://github.com/CGAL/cgal/blob/master/Intersections_3/include/CGAL/Intersections_3/internal/Bbox_3_Segment_3_do_intersect.h#L197).    
In the intersection code we  now  construct a …
> Intersections_3 :   Use Coercion_traits

- BGL/test/BGL/test_Collapse_edge_with_constraints.cpp
- BGL/test/BGL/test_Euler_operations.cpp
Fixes [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-10/BGL/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz)
```
/home/cgal_tester/build/src/cmake/platforms/Ubuntu-latest-GCC6-Release/test/BGL/test_Collapse_edge_with_constraints.cpp:31:47: warning: '<anonymous>' may be used uninitialized [-Wmaybe-uninitialized]
31 |   Mesh::Halfedge_index h = CGAL::make_triangle(Point_3(),Point_3(),Point_3(),m);
|                            ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
And also this [one](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-10/BGL/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz)
```
/home/cgal_tester/build/src/cmake/platforms/Ubuntu-GCC_master_CXX20-Release/test/BGL/test_Euler_operations.cpp:19:25: warning: 'p' may be …
```
> fix ununitialized variable warnings

- Distance_3/test/Distance_3/test_distance_3.cpp
When constructing a homogeneous point from 2 `int` and a double we call the constructor for 3 `Gmpz`  which warns about doubles that are not integral.  When we use `FT`  we construct quotients. 
* Affected package(s): Distance_3
* Issue(s) solved (if any): See this [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-6/Distance_3/TestReport_Christo_MSVC2017-Debug-64bits.gz) with a warning
> Distance_3: Construct a FT from non integral double

- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
We only default initialize a point as we are sure that it will be set by the intersection function before it is used, but the compiler does not know and warns for several test platforms.  So let's just initialize it.
> Triangulation_2: Quiet a warning

- Stream_support/include/CGAL/IO/OFF/File_scanner_OFF.h
In  case of a failure the reference parameter ` size`  did not get set to zero. This leads to a warning in [this testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-11/Stream_support_Examples/TestReport_lrineau_ArchLinux-CXX17-Release.gz). 
* Affected package(s): Stream_support
> Stream_support: Fix File_scanner_OFF::scan_facet()

- Intersections_3/include/CGAL/Intersections_3/internal/Bbox_3_Line_3_do_intersect.h
- Intersections_3/include/CGAL/Intersections_3/internal/Bbox_3_Segment_3_do_intersect.h
- Intersections_3/include/CGAL/Intersections_3/internal/Iso_cuboid_3_Sphere_3_do_intersect.h
Use the correct types when mixing double and coordinate types which may be not double.  This was discussed in PR #6261
* Affected package(s): Intersections_3
> Intersection_3: Use Coercion_traits

- Polygon/include/CGAL/Polygon_2.h
No need to construct an empty container and to call `std::copy()`.  
Additionally I hope that the warning in this [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-11/Polygon_Examples/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz) goes away.
* Affected package(s): Polygon
> Polygon:  Remove a workaround for an old Sun compiler

- Intersections_2/include/CGAL/Intersections_2/Segment_2_Segment_2.h
- Intersections_2/test/Intersections_2/test_intersections_2.cpp
Always use the same ordered segments
> [Intersections_2] Make the crossing point computation deterministic

- Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Decomposition_strategy_adapter.h
- Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_conv_2.h
- Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Minkowski_sum_decomp_2.h
- Minkowski_sum_2/include/CGAL/Polygon_vertical_decomposition_2.h
- Minkowski_sum_2/include/CGAL/Small_side_angle_bisector_decomposition_2.h
Added missing copy constructors and copy assignments to several classes that store pointers to objects that are either passed in via user-defined constructors or allocated. The default implementations caused segmentation faults.
The pointers and the corresponding flags that indicate ownerships should be eventually replaced with a smart pointers. Meanwhile, the copy constructors and copy assignments prevent double deletion. Notice that once a copy constructor (assignment) is present, the move constructor (assignment) is implicitly not generated anyway.
* Affected package(s): Minkowski_sum_2
* Link to compiled documentation (obligatory for small feature)
> Added missing copy constructor && assignment

- Stream_support/examples/Stream_support/Linestring_WKT.cpp
- Stream_support/examples/Stream_support/Point_WKT.cpp
- Stream_support/examples/Stream_support/Polygon_WKT.cpp
- Stream_support/examples/Stream_support/read_WKT.cpp
- Stream_support/test/Stream_support/test_WKT.cpp
Remove some `#include" and `typedef` in some WKT example files.
* Affected package(s):  Stream_support
> Stream_support: clean up the examples for WKT

- Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_path_with_locate.cpp
- Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_multiple_sources.cpp
- Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_1.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_2.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_3.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_4.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_5.cpp
- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_traits_test.cpp
As reported in #Issue #6333 we may have a dangling reference.  Thank you for pointing out @seb-tourneux.
* Affected package(s): Surface_mesh_shortest_path
* Issue(s) solved (if any): fix #6333
> Surface_mesh_shortest_path: Make data member a copy

- Point_set_processing_3/test/Point_set_processing_3/test_deprecated_io_point_set.cpp
Just as in PR #6265 we have two test executable which may dp I/O with the same file, which leads to assertions as in this [teststuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-22/Point_set_processing_3/TestReport_Sosno_MSVC-2019-Community-Release.gz). 
> PSP: ofstream -> sstream

- Mesh_3/include/CGAL/Mesh_3/Mesh_global_optimizer.h
- Mesh_3/test/Mesh_3/test_meshing_polyhedron_with_features.cpp
- Voronoi_diagram_2/test/Voronoi_diagram_2/vda_tos2.cpp
Make two programs less verbose on cerr/cout. Fix #6353.
* Affected package(s): Mesh_3, Voronoi_diagram_2
* Issue(s) solved (if any): fix #6353
> Make two test programs less verbose

- Stream_support/include/CGAL/IO/Color.h
This PR add 2 features to the `CGAL::Color` class.  
I'm personnaly using `Color` as a key of a `std::map`. The map therefore needs a [comparator](https://en.cppreference.com/w/cpp/named_req/Compare). 
Instead of implementing a comparator separately in my code, I think it might be useful to add the `operator<` in the class.   
To do so, I compared the two `m_data` arrays that call internally the [`std::lexicographical_compare`](https://en.cppreference.com/w/cpp/algorithm/lexicographical_compare).
It could be useful to return the color when calling `set_hsv()` and `set_rgb()`, and not `void`.
For example in my code I'm doing this:
```c++
CGAL::Color newColor;
newColor.set_hsv(angle, 100, 100);
put(colorPm, vertex, newColor);
```
But with a return value I could be written on one line. …
> Add CGAL::Color operator< and return values

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h
should also fix [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-27/Polygon_mesh_processing_Examples/TestReport_lrineau_ArchLinux-CXX17-Release.gz)
> ignore CDT2 if normal is null

- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Offset_meshing_plugin.cpp
Fix the use of the manifold criterion in the offset_meshing plugin. Fix #6357.
* Issue(s) solved (if any): fix #6357
> 3D demo offset_meshing_plugin: Fix the use of the manifold criterion

- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
- Polygon_mesh_processing/doc/Polygon_mesh_processing/examples.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/CMakeLists.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/extrude.cpp
Add an example for the function that enables to extrude a mesh.
Text  [subsection ](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.5-Ic-30/output2/Polygon_mesh_processing/index.html#title10 )and example [subsection ](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.5-Ic-30/output2/Polygon_mesh_processing/index.html#title15) in the User Manual.
> PMP: Add example for extrude_mesh()

- Distance_3/include/CGAL/Distance_3/Point_3_Triangle_3.h
- Distance_3/test/Distance_3/test_distance_3.cpp
- Triangulation_on_sphere_2/test/Triangulation_on_sphere_2/test_dtos_traits.cpp
I blundered in commit https://github.com/CGAL/cgal/pull/5527/commits/b95c60fc9fe671eb42a6811e137ab48167657db2: one orientation is of course not sufficient to determine which segment realizes the min.
I'm a little perplexed that nothing exploded, but I think it's because e.g. during an AABB Tree computation, if the computation is wrong for an edge, it still gave the correct result for the same edge seen from the neighboring face.
Reverting to the previous implementation.
* Affected package(s): `Distance_3`
> Fix squared_distance(Point_3, Triangle_3)

- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
Fix the return type of  `Constrained_triangulation_plus_2::constraints()`.  
Also add the `typdef`  for [`Vertices_in_constraint`](https://cgal.github.io/6372/v1/Triangulation_2/classCGAL_1_1Constrained__triangulation__plus__2.html#ac9e4a6b9d892bd683c36dc64ae0613e4)
> Triangulation_2: Fix doc bug

- BGL/include/CGAL/boost/graph/generators.h
I chose to correct the coordinate computations and leave the doc untouched because it is more intuitive for a user to give the center and radius of the circumscribing sphere than to give the edge length (or half of the edge length, or etc.).
* Issue(s) solved (if any): fix #6064
> Fix make_icosahedron() having wrong radius

- Installation/CHANGES.md
- Polygon/doc/Polygon/Polygon.txt
- Polygon/doc/Polygon/examples.txt
- Polygon/examples/Polygon/ranges.cpp
- Polygon/include/CGAL/Polygon_2.h
Add functions for returning a range of vertices, edges, and holes to the existing `begin(()/end()` pairs.
* Affected package(s): Polygon
> Polygon_2: Add functions for ranges

- Triangulation_2/doc/Triangulation_2/CGAL/Delaunay_triangulation_2.h
- Triangulation_2/doc/Triangulation_2/examples.txt
- Triangulation_2/examples/Triangulation_2/CMakeLists.txt
- Triangulation_2/examples/Triangulation_2/star_conflict_zone.cpp
Add an example that computes a conflict zone and then stars it.
Fix at the same time the documentation of  a function, as one parameter has a default.
> Triangulation_2:  Add Example for Starring a Conflict Zone

- Boolean_set_operations_2/doc/Boolean_set_operations_2/CGAL/Boolean_set_operations_2.h
- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
When searching "intersection" in the search bar one has a hard time to find the function in the 2D Linear Kernel as we have functions and documentation groups in Boolean Set Operations as well as in Polygon Mesh Processing.
This PR tries to improve the situation.
> better reference Kernel intersection functions

- AABB_tree/test/AABB_tree/aabb_any_all_benchmark.cpp
- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/internal/Edge_collapse.h
Replaced boost::tuple with std::tuple where there is no difference in use of the two.
* Affected package(s): Surface_mesh_simplification, AABB_tree
> Replaced boost::tuple with std::tuple

- Surface_mesh_deformation/doc/Surface_mesh_deformation/Surface_mesh_deformation.txt
In the file  Surface_mesh_deformation/index.html the deprecated section is not properly shown due to the fact that the list is not properly closed.
**Original**
**New**
> Surface_mesh_deformation: Incorrect deprecated sections

- Point_set_processing_3/include/CGAL/structure_point_set.h
A `\cgalParamEnd` was missing, resulting in an incorrect sequence of HTML tags (in the output just a small extra white space was shown)
**Original**
**New**
> Point_set_processing_3: Missing end command for cgalParam

- Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h
A `\cgalParamEnd` was missing, resulting in an incorrect sequence of HTML tags.
(file: Polygon_mesh_processing/structCGAL_1_1Polyhedral__envelope.html)
> Polygon_mesh_processing: Missing end command for cgalParam

- Combinatorial_map/include/CGAL/Combinatorial_map.h
- Linear_cell_complex/include/CGAL/boost/graph/properties_Linear_cell_complex_for_combinatorial_map.h
- Periodic_2_triangulation_2/include/CGAL/Periodic_2_triangulation_2.h
- Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_3.h
- Skin_surface_3/include/CGAL/triangulate_mixed_complex_3.h
- Skin_surface_3/include/CGAL/triangulate_power_diagram_3.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_builder_2_impl.h
- TDS_2/include/CGAL/Triangulation_data_structure_2.h
- TDS_3/include/CGAL/Triangulation_data_structure_3.h
- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
In functions like `copy_tds()`, and hence in the copy constructor of triangulation classes, as well as when writing to a stream we use `Unique_hash_map`.    When we know that all vertices will be inserted in a loop we better construct the map with a table as big as the number of vertices.
I stumbled in this while checking whether there is a drawback to start with table size 512 or 32 as suggested  by @GilesBathgate  in PR #6306.       I opted for an independent PR. 
We have to check more packages for the same improvement to make.
* Affected package(s):  TDS_2/3, Periodic_2/3
> TDS: Initialize the size of Unique_hash_map

- Mesh_3/doc/Mesh_3/CGAL/Image_3.h
- Mesh_3/doc/Mesh_3/Mesh_3.txt
Replacing the address http://inrimage.gforge.inria.fr/ by https://www-pequan.lip6.fr/~bereziat/inrimage/ as Forge is definitively shutdown.
> Mesh_3: correcting gforge address

- Documentation/doc/Documentation/Third_party.txt
Replacing the address https://mpfi.gforge.inria.fr/ by https://gitlab.inria.fr/mpfi/mpfi as Forge is definitively shutdown.
> Manual: correcting gforge address

- Nef_3/include/CGAL/Nef_3/SNC_decorator_traits.h
- Nef_3/include/CGAL/Nef_3/SNC_structure.h
The code doesn't seem to be used or referenced anywhere except as typedefs.
> Nef_3: Cleanup Halffacet_triangle_handle/Halffacet_triangle_const_handle

- Hash_map/include/CGAL/Tools/chained_map.h
- Hash_map/include/CGAL/Unique_hash_map.h
- Miscellany/doc/Miscellany/CGAL/Unique_hash_map.h
- Nef_3/include/CGAL/Nef_3/Binary_operation.h
- Nef_3/include/CGAL/Nef_3/K3_tree.h
- Nef_3/include/CGAL/Nef_3/SNC_FM_decorator.h
- Nef_3/include/CGAL/Nef_3/SNC_decorator.h
- Nef_3/include/CGAL/Nef_3/SNC_external_structure.h
- Nef_3/include/CGAL/Nef_3/SNC_k3_tree_traits.h
- Nef_3/include/CGAL/Nef_3/SNC_simplify.h
- Nef_3/include/CGAL/Nef_3/SNC_structure.h
- Nef_3/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h
- Nef_3/include/CGAL/Nef_polyhedron_3.h
- Nef_S2/include/CGAL/Nef_S2/Generic_handle_map.h
- Nef_S2/include/CGAL/Nef_S2/Sphere_map.h
This replaces #5673 and implements just the minimal changes required to add a reserve method and initialise the hash map on first access instead of during construction.
* The table is now initialized on first use instead of at construction
* Keep the `default_size` of 512
* Add a `min_size` of 32
* Passing a table_size value less than 512 in the constructor works.
* Calling `reserve` can set the table_size before (and only before) table first use.
---
Changes among Nef_3 classes.
* Utilise the `reserve` method in places where the hash table is created ahead of knowing how many items it would contain
* Utilise the table_size  parameter in the constructor where the hash table is created and the number of items is known.
* Affected package(s): Nef_3 / Hash_map …
> Reserve method for Chained Map / Unique Hash Map 

- Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
`polylines_to_protect(features, existing_features_begin, existing_features_end)` was able to detect acute angles in input polylines. It can now be tuned to angles smaller than a given bound.
When the parameter is left to its default value, the code is unchanged and checks for acute angles as before.
This function is undocumented for now.
> Mesh_3 - add tunable angle to `Angle_tester` for `polylines_to_protect()`

- BGL/include/CGAL/boost/graph/IO/STL.h
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Stream_support/include/CGAL/IO/STL.h
`unit_normal()` is called in STL writing of soup and mesh. Unfortunately, it requires a square root, and will thus not compile with EPECK. This gets especially unpleasant when calling non-STL writing that still requires STL writing compilation e.g., `IO::write_polygon_mesh("out.off", mesh)`.
This PR proposes to use an approximate square root call instead.
* Affected package(s): `Stream_support`, `BGL`
> Make write_STL (and write_polygon_mesh) compile with sqrt-less kernels

- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
Avoids constructing exact numbers. We might write the static filter so that it uses Epick if all intervals have `inf==sup`
> Nef_3: Use has_smaller_distance_to_point()

- Cartesian_kernel/include/CGAL/Cartesian/Plane_3.h
- Cartesian_kernel/include/CGAL/Cartesian/plane_constructions_3.h
- Homogeneous_kernel/include/CGAL/Homogeneous/PlaneH3.h
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/include/CGAL/Plane_3.h
- Nef_3/include/CGAL/Nef_3/SNC_intersection.h
- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
- Nef_3/test/Nef_3/include/CGAL/test_Nef_3.h
- Nef_S2/include/CGAL/Nef_S2/Sphere_segment.h
Deactivate the test of vertices and edges.  Note that there was a line that did exactly that but it is commented.
I argue that we can skip [these tests](https://github.com/CGAL/cgal/blob/master/Nef_S2/include/CGAL/Nef_S2/SM_point_locator.h#L193) as they do not return the [expected type](https://github.com/CGAL/cgal/blob/master/Nef_3/include/CGAL/Nef_3/SNC_point_locator.h#L490) in the `Object`.
@GilesBathgate can you please check that this makes sense.
> Nef_3: Avoid needless tests

- Cartesian_kernel/include/CGAL/Cartesian/Plane_3.h
- Cartesian_kernel/include/CGAL/Cartesian/plane_constructions_3.h
- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Ray_hit_generator.h
- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Ray_hit_generator2.h
- Homogeneous_kernel/include/CGAL/Homogeneous/PlaneH3.h
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/include/CGAL/Plane_3.h
- Nef_3/include/CGAL/Nef_3/SNC_constructor.h
- Nef_3/include/CGAL/Nef_3/SNC_intersection.h
- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
- Nef_3/include/CGAL/Nef_3/binop_intersection_tests.h
- Nef_3/test/Nef_3/include/CGAL/test_Nef_3.h
- Nef_S2/include/CGAL/Nef_S2/Sphere_segment.h
After looking at #6422 I noticed that all of SNC_intersection.h is static methods. So it doesn't need to inherit from SNC_decorator, nor need a constructor. In fact it could just be a namespace. However the rest of the code passes instances of it around so the methods can just be made static for now. Warnings about calling a static method on a variable had to be resolved, and removed some methods are not used (which I confirmed by grepping in case the calls are hidden in an #ifdef )
A performance tweak is under consideration to simplify the overcomplicated code, used for segment-segment, and segment-ray intersections
> Nef_3: Cleanup and performance improvements SNC_intersection

- Cartesian_kernel/include/CGAL/Cartesian/Direction_3.h
- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
- Homogeneous_kernel/include/CGAL/Homogeneous/DirectionH3.h
- Homogeneous_kernel/include/CGAL/Homogeneous/function_objects.h
- Kernel_23/include/CGAL/Segment_3.h
Member functions like `CGAL::Segment_3<K>::has_on(CGAL::Point_3<K>)` must call the corresponding functor.
This should accelerate the Nef_polyhedron_3 a little bit as there we write  `seg.has_on(p)`  instread of `K().has_on_3_object()(seg,p)`.  To change that in Nef is an orthogonal task.  
* Affected package(s): Kernel_23, Nef_3
> Kernel_23: Call function objects from CGAL::Segment_3

- STL_Extension/include/CGAL/Modifiable_priority_queue.h
Some fixes and enhancements for the `CGAL_BOOST_PAIRING_HEAP` specialization of `Modifiable_priority_queue`.
- Fix `pop()` not resetting the handle to null
- Disable copy and assignment since the handles become invalid when the queue is copied
- `top()` can and should return a const ref
- Make `push()` return a `handle_type` rather than `void`
- Add preconditions and assertions
- Add missing `clear()` and `size()`
- Explicitly initialize the handles in the constructor
* Affected package(s): `STL_Extension`
> Various fixes for Modifiable_priority_queue

- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Ray_hit_generator.h
- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/Ray_hit_generator2.h
When looking at #6431 I noticed `Ray_hit_generator2.h` is mostly identical to `Ray_hit_generator.h` these two files can be consolidated using simple inheritance.
* Affected package(s): Convex_decomposition
* Issue(s) solved (if any): cleaning / tech debt
> Consolidate the differences and use inheritance to remove duplication

- Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
- Filtered_kernel/include/CGAL/Epic_converter.h
- Filtered_kernel/include/CGAL/Lazy.h
- Filtered_kernel/include/CGAL/Static_filtered_predicate.h
- Kernel_23/include/CGAL/Origin.h
- Kernel_23/test/Kernel_23/origin_3.cpp
Adding the operator in `CGAL/Cartesian/function_objects.h` required some additions in converters, and in Origin itself. 
I did not add an overload for the homogeneous kernel and I did not add it for the global function. 
The added test case can also be used for benchmarking. For example with ` data/points/sphere_20k.xyz`. 
The main interest is for the exact constructions kernel.
This PR is triggered by a discussion in #6378, and @GilesBathgate might be interested to merge it. 
> Kernel_23: Add Orientation_3::operator()(Origin,Point_3,Point_3,Point_3)

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
> PMP repair: Avoid large DAG when using Lazy

- Tetrahedral_remeshing/include/CGAL/tetrahedral_remeshing.h
Protect the dump of statistics and bad cells with the _DEBUG macro instead of the _VERBOSE macro (which is used in the demo)
> Tetrahedral remeshing - avoid useless dumps

- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/GarlandHeckbert_plane_policies.h
- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/GarlandHeckbert_probabilistic_plane_policies.h
- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/GarlandHeckbert_probabilistic_triangle_policies.h
- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/GarlandHeckbert_triangle_policies.h
- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/internal/GarlandHeckbert_policy_base.h
- Surface_mesh_simplification/test/Surface_mesh_simplification/edge_collapse_garland_heckbert_variations.cpp
Four variations of Garland-Heckbert were introduced with https://github.com/CGAL/cgal/pull/6190. In GH methods, the cost and the placement oracles share quadrics. In the PR, this was implemented using diamond inheritance and a virtual base for the quadric storage class.
This is all fine, until cost and placement adapter come into play: some of these adapters inherit the placement oracle, and thus the initialization becomes messed up because the adapter does not initialize the virtual base and so default construction is performed (see https://godbolt.org/z/91qesjrsM for an illustration), yielding broken quadrics storage.
The test with the `Bounded_normal_change_placement` adapter was not affected by this problem because it does not inherit the base placement (like `Constrained_placement` …
> Dediamondize Garland-Heckbert policy stack

- Nef_S2/include/CGAL/Nef_S2/Sphere_circle.h
Whilst implementing #6378 I noticed another minor optimisation. The Plane_Plane intersection of two sphere circles can be simplified to the cross product of the two planes orthogonal vectors. 
* Affected package(s): Nef_3, Nef_S2
* Issue(s) solved (if any): performance
> Nef_3: Use cross product instead of Plane_Plane intersection

- Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/GarlandHeckbert_policies.h
* Affected package(s): `Surface_mesh_simplification`
> Add missing include for the macro CGAL_DEPRECATED

- Cartesian_kernel/include/CGAL/Cartesian/Point_2.h
- Cartesian_kernel/include/CGAL/Cartesian/Point_3.h
- Cartesian_kernel/include/CGAL/Cartesian/Vector_2.h
- Cartesian_kernel/include/CGAL/Cartesian/Vector_3.h
- Kernel_23/include/CGAL/Point_2.h
- Kernel_23/include/CGAL/Point_3.h
- Kernel_23/include/CGAL/Vector_2.h
- Kernel_23/include/CGAL/Vector_3.h
- NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Point_d.h
Full error message:
```
/home/sloriot/CGAL/git/integration/Cartesian_kernel/include/CGAL/Cartesian/Line_3.h(38): error: incomplete type is not allowed
Point_3 first;
^
detected during:
instantiation of class "CGAL::LineC3<R_>::Rep [with R_=CGAL::Simple_cartesian<double>]" at line 46
instantiation of class "CGAL::LineC3<R_> [with R_=CGAL::Simple_cartesian<double>]" at line 30 of "/home/sloriot/CGAL/git/integration/Kernel_23/include/CGAL/Line_3.h"
instantiation of class "CGAL::Line_3<R_> [with R_=CGAL::Simple_cartesian<double>]" at line 901 of "/usr/include/c++/10/type_traits"
instantiation of class "std::__is_constructible_impl<_Tp, _Args...> [with _Tp=CGAL::VectorC3<CGAL::Simple_cartesian<double>>, _Args=<CGAL::VectorC3<CGAL::Simple_cartesian<double>> &&>]" at line 952 of …
```
> Workaround issue with intel compiler

- Mesh_3/include/CGAL/facets_in_complex_3_to_triangle_mesh.h
The function `facets_in_complex_3_to_triangle_mesh()` uses a vertex handle-based unordered map to convert triangulation vertices to triangle mesh vertices. In the case of periodic meshes, triangulation vertices might correspond to different geometric positions depending on the periodic instance.
This PR changes the unordered map to be handle-based to point-based (in periodic triangulations, `Triangulation::point(Cell_handle, int)` returns a sensible position.
Some minor improvements while there (avoid the `to_double()`).
* Affected package(s): `Mesh_3`
> Fix C3T3_facets_to_TM conversion for periodic meshes

- Scripts/developer_scripts/run_testsuite_with_ctest
Since I have upgrade Cygwin on `christo`, the testsuite cannot process the results of CTest, with that error message:
```
python3: can't open file '/cygdrive/c/CGAL_ROOT/CGAL-5.5-Ic-68/C:/CGAL_ROOT/CGAL-5.5-Ic-68/test/parse-ctest-dashboard-xml.py': [Errno 2] No such file or directory
```
The version of `/usr/bin/python3` in Cygwin is now:
```
Python 3.9.10 (main, Jan 20 2022, 21:37:52)  
[GCC 11.2.0] 
````
It seems the `os.path` module of that version of Python, under Cygwin, can no longer understand Windows paths, and treat them as relative paths. But the `open` function of Python can still open Windows paths. This PR uses a trick: with `open` and `exec` we have an equivalent of the C++ `#include`.
> Fix run_testsuite_with_ctest on Cygwin

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/angle_and_area_smoothing.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_self_intersections.h
(5.5 only as the refactor is introduced in 5.5)
> prevent remove_self_intersections from emitting a warning 

- Shape_regularization/doc/Shape_regularization/PackageDescription.txt
- Weights/doc/Weights/PackageDescription.txt
Due to the fact that an `ALIASES` is used the space will also be part of the file name and thus the link will, incorrectly be `https://www.cgal.org/demo/5.5/%20polyhedron_3.zip` instead of `https://www.cgal.org/demo/5.5/polyhedron_3.zip`
> Incorrect reference to demo zip file

- Mesh_3/include/CGAL/Labeled_mesh_domain_3.h
Address this [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-I-69/Mesh_3/TestReport_cgaltester_x86-64_Darwin-18.5_Apple-clang-default_Release.gz).  Just comparing the code with other header files in Mesh_3 I think we just forgot one place where the warning must be suppressed.  
> Mesh_3: Suppress a clang warning

- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/Periodic_2_triangulation_2.h
Corrected documentation in respect to the miss-use of `\cgalModels`
> issue #6440 Periodic_2_triangulation_2: Strange documentation.

- Solver_interface/include/CGAL/OSQP_quadratic_program_traits.h
> issue #6515 Solver_interface: Non reachable link to https://osqp.org/docs/interfaces/cc++

- BGL/include/CGAL/boost/graph/IO/Generic_facegraph_builder.h
- BGL/include/CGAL/boost/graph/IO/Generic_facegraph_printer.h
- BGL/include/CGAL/boost/graph/IO/PLY.h
- BGL/include/CGAL/boost/graph/named_params_helper.h
- Optimal_bounding_box/include/CGAL/Optimal_bounding_box/oriented_bounding_box.h
- Point_set_processing_3/include/CGAL/IO/write_off_points.h
- Point_set_processing_3/include/CGAL/mst_orient_normals.h
- Point_set_processing_3/include/CGAL/structure_point_set.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/corefinement.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h
- Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_np_function.cpp
- Polyhedron/include/CGAL/IO/Polyhedron_OFF_iostream.h
- STL_Extension/include/CGAL/Named_function_parameters.h
- Scripts/developer_scripts/test_merge_of_branch
- Shape_regularization/include/CGAL/Shape_regularization/regularize_planes.h
- Surface_mesh/include/CGAL/Surface_mesh/IO/OFF.h
- Surface_mesh_approximation/include/CGAL/Surface_mesh_approximation/approximate_triangle_mesh.h
In `named_param_helpers.h` there was `Is_default<NP, P>` (defining `value` + `type`), and in `Named_function_parameters.h` there was `is_default_parameter` but with usage `if(is_default_parameter<NP, P>())`, which isn't really the style of e.g. `std::is_same<T1, T2>`.
This PR merges both into `is_default_parameter<NP, NP`, with usage `if(is_default_parameter<NP, P>::value)`.
Re-indent `named_param_helpers.h` while there (diff without whitespace: https://github.com/CGAL/cgal/pull/6499/files?w=1).
5.5 would be best since `is_default_parameter` was introduced in 5.5.
* Affected package(s): BGL, STL_Extension + usages
> Merge parameters::Is_default and parameters::is_default_parameter 

- Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
`min(90, angle_bound)` should be `max(90, angle_bound)`.
90 is a conservative lower bound. This means that each vertex corresponding to an angle smaller than 90 should be set as terminal by `CGAL::Mesh_3::polylines_to_protect()`, even if `angle_bound < 90`.
If `angle_bound > 90`, we keep `angle_bound` and collect/set more terminal vertices.
This PR fixes PR #6402
> CGAL::Mesh_3::polylines_to_protect with angle bound - bug fix

- Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt
- Triangulation_3/include/CGAL/Triangulation_3.h
While loading a mesh binary file with the `triangulation_io_plugin`, I got a crash. This PR turns the crash into a proper error handling.
> Fix crash during binary I/O of Triangulation_3

- Barycentric_coordinates_2/include/CGAL/Barycentric_coordinates_2/Discrete_harmonic_2.h
- Barycentric_coordinates_2/include/CGAL/Barycentric_coordinates_2/Generalized_barycentric_coordinates_2.h
- Barycentric_coordinates_2/include/CGAL/Barycentric_coordinates_2/Mean_value_2.h
- Barycentric_coordinates_2/include/CGAL/Barycentric_coordinates_2/Wachspress_2.h
- Barycentric_coordinates_2/include/CGAL/Barycentric_coordinates_2/segment_coordinates_2.h
- Barycentric_coordinates_2/include/CGAL/Barycentric_coordinates_2/triangle_coordinates_2.h
After the assignment to an output iterator it  must be incremented. 
* Affected package(s): Barycentric_coordinates
> Barycentric coordinates: bug fix: Increment output iterator 

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap_vertices.h
If `Visitor` is not a reference, the previous code might have been taking a (non-const) ref to a temporary.
> Fix snap visitor get_parameter_reference usage

- Polygonal_surface_reconstruction/doc/Polygonal_surface_reconstruction/Polygonal_surface_reconstruction.txt
- Solver_interface/include/CGAL/Mixed_integer_program_traits.h
It looks like that the https://projects.coin-or.org/Cbc is a permanent redirect to https://github.com/coin-or/Cbc (all https://projects.coin-or.org redirect to github).
> Correcting permanent redirect to Cbc

- Hash_map/include/CGAL/Hash_map/internal/chained_map.h
Fix [this error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-75/Hash_map/TestReport_lrineau_Ubuntu-Latest-NO_DEPRECATED_CODE.gz)
> Add missing include directive

- Principal_component_analysis/include/CGAL/PCA_util.h
Added a check for degenerated input data in fitting_plane_3 used by linear_least_squares_fitting_3 to avoid NaN as a return value.
* Affected package(s): Principal Component Analysis
* Issue(s) solved (if any): fix #6146
> Fixed degenerated case of plane fitting to a linear set of points.

- QP_solver/include/CGAL/QP_solver/functors.h
Check that [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-I-95/QP_solver/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz) does not reappear.
Try to fix:
```
Convex_hull_3_Examples/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz:/usr/local/boost/include/boost/iterator/transform_iterator.hpp:79:9: warning: implicitly-declared 'constexpr CGAL::Map_with_default<std::map<long unsigned int, bool> >::Map_with_default(const CGAL::Map_with_default<std::map<long unsigned int, bool> >&)' is deprecated [-Wdeprecated-copy]
Convex_hull_3_Examples/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz:/usr/local/boost/include/boost/iterator/transform_iterator.hpp:79:9: warning: implicitly-declared 'constexpr CGAL::Map_with_default<std::map<long unsigned …
```
> Try to fix a warning

- Nef_3/include/CGAL/Nef_3/Binary_operation.h
- Nef_3/include/CGAL/Nef_3/ID_support_handler.h
- Nef_3/include/CGAL/Nef_3/SNC_external_structure.h
- Nef_S2/include/CGAL/Nef_S2/ID_support_handler.h
There are a couple of places in Nef_3 where `std::map<int, int>` is used even though the order isn't important and the number of elements that will be placed in the map is known ahead of use. `std::unordered_map<int, int>` is a better choice when this is the case.
* Issue(s) solved (if any): performance
> Nef_3: Performance std::map -> std::unordered_map

- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Arrangement_on_surface_2.txt
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Concepts/ArrangementOpenBoundaryTraits_2.h
- Boolean_set_operations_2/doc/Boolean_set_operations_2/Boolean_set_operations_2.txt
- Documentation/doc/Customizations.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_code_format.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_iterators_and_circulators.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_kernels.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_multithreading.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_namespaces.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_objects.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_portability.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_testing.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_traits_classes.txt
- Documentation/doc/Documentation/Third_party.txt
- Documentation/doc/Documentation/advanced/Configuration_variables.txt
- Documentation/doc/resources/1.8.13/BaseDoxyfile.in
- Documentation/doc/resources/1.8.14/BaseDoxyfile.in
- Documentation/doc/resources/1.8.20/BaseDoxyfile.in
- Documentation/doc/resources/1.8.4/BaseDoxyfile.in
- Documentation/doc/resources/1.9.3/BaseDoxyfile.in
- Documentation/doc/resources/1.9.3/stylesheet.css
- Kernel_23/doc/Kernel_23/Kernel_23.txt
- Kernel_d/doc/Kernel_d/Kernel_d.txt
- Nef_2/doc/Nef_2/CGAL/Nef_polyhedron_2.h
- Number_types/doc/Number_types/CGAL/Sqrt_extension.h
- Number_types/doc/Number_types/NumberTypeSupport.txt
- Polynomial/doc/Polynomial/Polynomial.txt
- Polytope_distance_d/doc/Polytope_distance_d/CGAL/all_furthest_neighbors_2.h
Update of documentation in respect of code fragments
- making code fragments work in footnotes
- placing some words in in code tags
- completing some words to code tags
- removing some `#` as they are not necessary
- don't show obfuscation code in email
> Documentation update in respect to code fragments

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_distance.cpp
Also, make the fact that non-empty ranges are expected clear in the doc and add missing preconditions.
* Issue(s) solved (if any): fix #6536 
> Fix GT/VPM usage in approximate Hausdorff distance computations

- Arrangement_on_surface_2/include/CGAL/graph_traits_Arrangement_2.h
- BGL/doc/BGL/graph_traits.txt
- BGL/include/CGAL/boost/graph/graph_traits_OpenMesh.h
- BGL/test/BGL/graph_concept_Linear_cell_complex.cpp
- BGL/test/BGL/graph_concept_OpenMesh.cpp
- BGL/test/BGL/graph_concept_Polyhedron_3.cpp
- BGL/test/BGL/graph_concept_Surface_mesh.cpp
- HalfedgeDS/include/CGAL/boost/graph/graph_traits_HalfedgeDS.h
- HalfedgeDS/include/CGAL/boost/graph/graph_traits_HalfedgeDS_default.h
- Linear_cell_complex/include/CGAL/boost/graph/graph_traits_Linear_cell_complex_for_combinatorial_map.h
- Surface_mesh/include/CGAL/boost/graph/graph_traits_Surface_mesh.h
Add `adjacency_iterator` to several classes with `typedef`s as defined in the [documentation](https://doc.cgal.org/latest/BGL/group__PkgBGLTraits.html).
Do we want to provide it for `Dual` etc ?
* Affected package(s): Surface_mesh, Polyhedron, LCC
* Issue(s) solved (if any): fix #6531
> BGL: Add adjacency_iterator for several classes

- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/bgl_dual_adapter.cpp
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/bgl_primal_adapter.cpp
- BGL/examples/BGL_LCC/distance_lcc.cpp
- BGL/examples/BGL_LCC/kruskal_lcc.cpp
- BGL/examples/BGL_arrangement_2/arrangement_dual.cpp
- BGL/examples/BGL_polyhedron_3/distance.cpp
- BGL/examples/BGL_polyhedron_3/kruskal.cpp
- BGL/examples/BGL_polyhedron_3/kruskal_with_stored_id.cpp
- BGL/examples/BGL_surface_mesh/prim.cpp
- BGL/examples/BGL_triangulation_2/emst.cpp
- BGL/examples/BGL_triangulation_2/emst_cdt_plus_hierarchy.cpp
- BGL/examples/BGL_triangulation_2/emst_regular.cpp
- BGL/include/CGAL/boost/graph/alpha_expansion_graphcut.h
- BGL/include/CGAL/boost/graph/breadth_first_search.h
- BGL/include/CGAL/boost/graph/dijkstra_shortest_paths.h
- BGL/include/CGAL/boost/graph/kruskal_min_spanning_tree.h
- BGL/include/CGAL/boost/graph/prim_minimum_spanning_tree.h
- Point_set_processing_3/include/CGAL/mst_orient_normals.h
- Surface_mesh_approximation/include/CGAL/Variational_shape_approximation.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/orbifold_shortest_path.h
Address a warning in many VC++ testsuites concerning a boost file. For example in the [BGL ](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.5-I-74.shtml#BGL) package.
> BGL: Suppress warning in boost

- Shape_regularization/include/CGAL/Shape_regularization/internal/Contour_base_2.h
Fix [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-77/Shape_regularization/TestReport_Sosno_MSVC-2022-Preview-Release.gz)
> Fix deprecation warning

- Convex_hull_3/include/CGAL/Convex_hull_3/dual/predicates.h
- Kernel_23/include/CGAL/Kernel/function_objects.h
As the predicates are used with a kernel that may return an `Uncertain`  we must use `K::Boolean` instead of `bool`.
This fixes the 'N' we can see in the VC2015 [Convex_hull_3 ](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.5-I-79.shtml#Convex_hull_3) testsuite. 
> Convex_hull_3: Use K::Boolean and not bool

- Box_intersection_d/doc/Box_intersection_d/examples.txt
- Box_intersection_d/examples/Box_intersection_d/progress.cpp
- Box_intersection_d/include/CGAL/Box_intersection_d/segment_tree.h
- Box_intersection_d/test/Box_intersection_d/CMakeLists.txt
- Box_intersection_d/test/Box_intersection_d/test_Has_member_report.cpp
- Installation/include/CGAL/config.h
- Number_types/include/CGAL/double.h
- Polygon_mesh_processing/doc/Polygon_mesh_processing/Concepts/PMPCorefinementVisitor.h
- Polygon_mesh_processing/doc/Polygon_mesh_processing/examples.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/CMakeLists.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_mesh_union_progress.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Visitor.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_callbacks.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
Introduce an API for tracking progress.  We report the progress in the traversal of the primary tree, that is we report 50% once we come back from the left subtree of the root of the segment tree.
The API is not yet documented, that is for the moment you have to look at the callback class in the example `progress.cpp`.
This PR also adds progress tracking to the Boolean operations based on corefinement.
* Affected package(s): Box_intersection_d, Polygon_mesh_processing
* Feature/Small Feature (if any):  tbd.
> Fast Box Intersection:  Add progress tracking

- Kernel_23/include/CGAL/Kernel/function_objects.h
I could add a `#ifdef __INTEL_COMPILER` but it does not hurt as is.
> Please intel 2019 compiler

- Polyline_simplification_2/examples/Polyline_simplification_2/points_and_vertices.cpp
- Polyline_simplification_2/examples/Polyline_simplification_2/simplify.cpp
- Polyline_simplification_2/examples/Polyline_simplification_2/simplify_polygon.cpp
- Polyline_simplification_2/examples/Polyline_simplification_2/simplify_polyline.cpp
Remove  `#include`s that are not needed.
* Affected package(s):  Polyline_simplification
> Polyline_simplification: Clean up examples

- HalfedgeDS/test/HalfedgeDS/test_hds_range_based_loops.cpp
Fix [this error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5-Ic-88/HalfedgeDS/TestReport_lrineau_Fedora-32-Release.gz)  happening from time to time.   It is not a bug in the CGAL code, but in the testsuite code. 
CGAL-5.5-I-29, CGAL-5.5-I-39, CGAL-5.5-I-44, ...
> Remove geometric test on default constructed objects

- Polyhedron/demo/Polyhedron/Plugins/IO/Polylines_io_plugin.cpp
A scene cannot be saved as `.js` file when it contains a polyline item.
* Affected package(s):  Polyhedron demo
> Polyhedron_3: Fix saving a polyline as part of a scene

- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Arrangement_on_surface_2.txt
The `<OL>` tag has no attribute `compact`.
- only the HTML tag `<menu>` has the `compact` attribute according to https://www.w3schools.com/tags/att_menu_compact.asp but it is not supported in any major browser.
- according to https://www.geeksforgeeks.org/html-ol-compact-attribute/ the `<OL>` tag can have a `compact` attribute but it is not supported by any any major browser.
> Arrangement_on_surface_2: unknown attribute compact specified

- Polyline_simplification_2/demo/Polyline_simplification_2/Polyline_simplification_2.cpp
cleaning code
* Affected package(s): Polyline_simplification
> Polyline simplification: Use const&  in demo instead of copying a polygon

- Poisson_surface_reconstruction_3/include/CGAL/IO/output_surface_facets_to_triangle_soup.h
Found the warning:
```
output_surface_facets_to_triangle_soup.h:29: warning: Found unknown command '@commentheading'
```
Command is superfluous as the `tparam` command will provide the relevant header.
(Tested CGAL documentation with `GENERATE_XML = YES`)
> Poisson_surface_reconstruction_3: unknown command `@commentheading`

- Nef_3/include/CGAL/Nef_3/Binary_operation.h
- Nef_3/include/CGAL/Nef_3/K3_tree.h
- Nef_3/include/CGAL/Nef_3/SNC_point_locator.h
- Nef_3/include/CGAL/Nef_3/binop_intersection_tests.h
It is believed that the object casts in K3_tree/SNC_point_locator creates an overhead. This pull request aims to reduce this overhead by keeping lists of vertices, edges and facets separately in the Node.
* Issue(s) solved (if any): performance
> Nef_3: Use separate lists K3_tree node to avoid object casts

- Installation/cmake/modules/CGAL_SetupCGALDependencies.cmake
In case CGAL or QGLViewer are already installed somewhere in the system, let's have the include paths of this installation of CGAL first.
> Add CGAL include paths first

- AABB_tree/include/CGAL/AABB_tree.h
Document the parameter `node` as well as two parameters as functor (without saying more) and remove the parameter `traits` as it is not used.
* Affected package(s): AABB_tree
* Issues:  #6582
> AABB_tree: Document parameters

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/shape_predicates.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_remove_caps_needles.cpp
- STL_Extension/include/CGAL/STL_Extension/internal/parameters_interface.h
Add an option to a non-documented function prevent flipping triangles with a height larger than a given input threshold.
> Add an option to a remove_almost_degenerate_faces

- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Alpha_wrap_3.h
- GraphicsView/include/CGAL/Qt/qglviewer.h
- GraphicsView/include/CGAL/Qt/qglviewer_impl.h
- Polyhedron/demo/Polyhedron/Plugins/Alpha_wrap_3/Alpha_wrap_3_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Alpha_wrap_3/alpha_wrap_3_dialog.ui
Add a way to visualize and save refinement/carving iterations.
* Affected package(s): `Alpha_wrap_3`, `Polyhedron`
> AW3: Visualize and save wrapping iterations

- Documentation/doc/Documentation/Developer_manual/Chapter_code_format.txt
- Documentation/doc/Documentation/Preliminaries.txt
- STL_Extension/doc/STL_Extension/Concepts/Hashable.h
Change links to some boost ref manual pages as boost.org is not willing to add redirects.
TODO:
* Affected package(s): STL_Extension
* Issue(s) solved (if any): fix #6511
> STL_extension: Fix URL to boost libs

- Polygon/include/CGAL/General_polygon_with_holes_2.h
- Polygon/include/CGAL/Polygon_2.h
- Polygon/include/CGAL/Polygon_with_holes_2.h
- Polygon/test/Polygon/PolygonTest.cpp
- Polygon/test/Polygon/Polygon_with_holes_test.cpp
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Use move semantics for `Polygon_2`  and `Polygon_with_holes_2`.   
The latter gets passed a polygon as outer boundary and an iterator range of polygons for the holes.  
* Affected package(s):  Polygon_2
> Polygon: Add move semantics

- Triangulation_3/include/CGAL/Delaunay_triangulation_3.h
- Triangulation_3/include/CGAL/Triangulation_3.h
- Triangulation_3/include/CGAL/Triangulation_hierarchy_3.h
Initialize a few stack variables.  Using clang memory sanitizer, they were detected as uninitialized in some cases.
These changes should result in no functional change (NFC).
> initialize some stack variables

- .github/workflows/checks.yml
- .github/workflows/cmake-all.yml
- .github/workflows/delete_doc.yml
- .github/workflows/demo.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- Documentation/doc/Documentation/Developer_manual/Chapter_multithreading.txt
- Installation/include/CGAL/atomic.h
Fix #6680. Remove mention of Boost threading features.
* Issue(s) solved (if any): fix #6680
> Remove mention to boost::thread_specific_ptr

- Polyhedron/demo/Polyhedron/Plugins/PMP/Engrave_text_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Parameterization_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
Fix segfaults at exit. The segfaults at the destruction of plugins were because of uninitialized pointers.
> Polyhedron demo: Fix segfaults at exit

- STL_Extension/include/CGAL/Skiplist.h
While `push_back()` creates elements on the heap and `clear()` deletes them, `pop_back()` does not, which led to a memory leak.
The class `Skiplist` is used by packages such as 2D Triangulations.
* Affected package(s): STL_Extension
> STL_extension: Fix memory leak in Skiplist

- Nef_S2/include/CGAL/Nef_S2/SM_overlayer.h
In the expression `M[--L.end()] = M[start];`, the hash map `M` can be rehashed during the evaluation of the expression. That can lead to a use-after-free if the reference to `M[start]` is first loaded, and then the evaluation of `M[--L.end()]` triggers a rehash and invalidates the reference to `M[start]`.
Fix #6671.
* Affected package(s): Nef_S2
* Issue(s) solved (if any): fix #6671
> Nef_S2: Fix a use-after-free

- Polygon_mesh_processing/test/Polygon_mesh_processing/test_does_bound_a_volume.cpp
A test file must include the documented header of a function.
> PMP:  Include the correct header file in a test

- Orthtree/include/CGAL/Orthtree/Node.h
- Orthtree/test/Orthtree/test_octree_refine.cpp
The helper class generates nodes that allocate memory without freeing it. 
* Affected package(s):  Orthtree
> Orthtree: Fix memory leak in test code

- Algebraic_foundations/doc/Algebraic_foundations/Concepts/RealEmbeddableTraits.h
- Linear_cell_complex/doc/Linear_cell_complex/Concepts/LinearCellComplexTraits.h
- Mesh_2/doc/Mesh_2/Concepts/ConformingDelaunayTriangulationTraits_2.h
- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
- Three/doc/Three/Three.txt
The doxygen  symbol resolver for the doxygen master version (1.9.5 (https://github.com/doxygen/doxygen/commit/35711f2d14acc81cff83f81f04c566ad8c8c6fe8)) has been improved (made stricter) but this means also means that some links have to be corrected.
The patch has been tested against the mentioned doxygen master and against doxygen 1.8.13 and the results look in both cases correct (without the patch the master version has some warnings and some incorrect links)..
The patch has been created by @doxygen and upon request created into a pull request by me.
> Corrections for more strict doxygen symbol resolver

- SMDS_3/include/CGAL/tetrahedron_soup_to_triangulation_3.h
We get the warning:
```
SMDS_3/include/CGAL/tetrahedron_soup_to_triangulation_3.h:210: warning: unable to resolve link to 'polygon_soup_to_polygon_mesh()' for \link command
```
see also:
- https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.6-Ic-16/logs_master/SMDS_3.log
- https://github.com/CGAL/cgal/pull/6645
> SMDS_3 Incorrect link

- Orthtree/include/CGAL/Orthtree/Node.h
Fix the upper bound in a ` for`  loop.
* Affected package(s): Orthtree
> Orthtree: Fix in test code

- Surface_mesh_segmentation/include/CGAL/Surface_mesh_segmentation/internal/auxiliary/graph.h
- Surface_mesh_segmentation/include/CGAL/boost/graph/Alpha_expansion_MaxFlow_tag.h
As pointed out by @lrineau the assignment of an empty graph, does not clear le lhs of the assignment.   Instead of writing an assignment operator for `graph` this PR adds a method    `graph::clear()".   
* Affected package(s): Surface_mesh_segmentation
> Surface_mesh_segmentation: fix the memory leak

- Installation/CHANGES.md
- Straight_skeleton_2/doc/Straight_skeleton_2/CGAL/create_offset_polygons_from_polygon_with_holes_2.h
- Straight_skeleton_2/doc/Straight_skeleton_2/Straight_skeleton_2.txt
- Straight_skeleton_2/examples/Straight_skeleton_2/CMakeLists.txt
- Straight_skeleton_2/examples/Straight_skeleton_2/exterior_offset_of_multiple_polygons_with_holes.cpp
- Straight_skeleton_2/include/CGAL/create_offset_polygons_2.h
- Straight_skeleton_2/include/CGAL/create_offset_polygons_from_polygon_with_holes_2.h
- Straight_skeleton_2/test/Straight_skeleton_2/test_sls_offset.cpp
This PR is both a fix and a breaking change of a behavior that was IMO buggy in the first place (thus not backported to 5.4).
Fix the function creating exterior offsets to also consider holes + update functions dumping exterior offsets as polygons with holes to ignore the offset of the outer frame.
> Fix exterior offset creation for a polygon with holes

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_repair_polygon_soup.cpp
This overload does not call functions that are meaningless for arrays (changing the size and splitting facets).
* Affected package(s):  `PMP`
* Issue(s) solved (if any): fix #6693 
> Add an overload of `repair_polygon_soup()` for ranges of arrays

- Spatial_searching/include/CGAL/Kd_tree.h
Quick web-based driveby contribution (not tested) to fix what looks like a likely integer overflow for large point clouds.
> Spatial_searching: unsigned int -> size_t for vector copy

- STL_Extension/doc/STL_Extension/Concepts/Hashable.h
For the file STL_Extension/classHashable.html we got some permanent redirects:
```
List of redirects
http://www.cplusplus.com/reference/unordered_set/unordered_set/
-> https://cplusplus.com/reference/unordered_set/unordered_set/
Line: 177
Code: 301 -> 200 OK
To do: This is a permanent redirect. The link should be updated.
http://www.cplusplus.com/reference/unordered_set/unordered_map/
-> https://cplusplus.com/reference/unordered_set/unordered_map/
Line: 179
Code: 301 -> 200 OK
To do: This is a permanent redirect. The link should be updated.
```
> STL_Extension Documentation permanent redirects

- Arrangement_on_surface_2/demo/Arrangement_on_surface_2/ArrangementPainterOstream.cpp
- Kernel_23/include/CGAL/Kernel_23/internal/Projection_traits_3.h
- Mesh_3/include/CGAL/Mesh_3/search_for_connected_components_in_labeled_image.h
- Number_types/include/CGAL/GMP/Gmpzf_type.h
- Number_types/include/CGAL/MP_Float.h
- STL_Extension/include/CGAL/Uncertain.h
- Straight_skeleton_2/include/CGAL/constructions/Straight_skeleton_cons_ftC2.h
Should remove [those warnings](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-I-19/AABB_tree/TestReport_lrineau_ArchLinux-clang-CXX20-Release.gz)
> Workaround warning with gcc master

- CMakeLists.txt
- Installation/cmake/modules/CGAL_add_test.cmake
- Installation/cmake/modules/CGAL_enable_end_of_configuration_hook.cmake
- Installation/lib/cmake/CGAL/CGALConfig.cmake
- Polyhedron/demo/Polyhedron/polyhedron_demo_macros.cmake
1. Starting with CMake 3.18, use `cmake_language(DEFER CALL..)` instead of `variable_watch`. That was a really bad hack!
2. Create fixture `demo_framework_SetupFixture`.
That avoids that all targets of CGAL depend on `demo_framework`. Now only the plugins depend on it.
3.  Fix the dependencies of CTest tests on `compilation_of__CGAL_Qt5_moc_and_resources`.
* Affected package(s): Installation, Polyhedron demo
> Cleanup CMake scripts

- Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h
Changed ply.h to consider a color property map from named parameters before searching for internal property map.
Tested by using CGAL::IO::write_PLY
> Surface_mesh: fixed saving of face colors using property maps from named parameters

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
Use `construct_midpoint_3_object()` instead of `CGAL::midpoint()` and avoid including `CGAL/Kernel/global_functions_3.h`.
The old code had a compilation error with CGAL 5.4.1 and gcc 10.3, because the compiler could not differentiate between `CGAL::midpoint()` for `Point_2` and `CGAL::midpoint()` for `Point_3`.
Thanks @Simon-Lopez for the report.
> PMP::isotropic_remeshing() - avoid using global function midpoint()

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/tangential_relaxation.h
Use `construct_barycenter_3_object()` instead of `CGAL::barycenter()` and avoid including `CGAL/Kernel/global_functions_3.h`.
The old code (that was in `isotropic_remeshing`) had a compilation error with CGAL 5.4.1 and gcc 10.3, because the compiler could not differentiate between `CGAL::midpoint()` for `Point_2` and `CGAL::midpoint()` for `Point_3`.
This PR is related to #6774 and implements the "same" fix for the code modified for 5.5.
> PMP::tangential_relaxation() - avoid using global function barycenter()

- Solver_interface/doc/Solver_interface/Concepts/SparseLinearAlgebraTraits_d.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Iterative_authalic_parameterizer_3.h
I hard coded the copy of a sparse matrix.   We have to add this properly to a Solver API.
I removed debug output that writes the mesh after each iteration.
* Affected package(s): Surface_mesh_parameterization
* Issue(s) solved (if any): fix #6694
> Parameterization: Make Iterative_authalic_parameterization faster (WIP)

- Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction.h
- Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/compute_confidences.h
- Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/hypothesis.h
- Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/parameters.h
- Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/point_set_with_planes.h
- Polygonal_surface_reconstruction/package_info/Polygonal_surface_reconstruction/license.txt
The package is documented as GPL and even include the license checker but SPDX and package info was invalid.
https://github.com/CGAL/cgal/pull/3984 indicates that the package was intended to be GPL.
> Fix package license

- Documentation/doc/resources/1.9.3/BaseDoxyfile.in
In the current master the settings `DOT_TRANSPARENT` and `FORMULA_TRANSPARENT` are obsolete.
> Obsolete doxygen settings

- Documentation/doc/resources/1.9.3/BaseDoxyfile.in
In doxygen the setting `HTML_COLORSTYLE` has been introduced with as default `AUTO_LIGHT` but due to the current strategy of CGAL in respect to HTML stylesheets the divider between the treeview and the text is not properly  visible anymore. Due to the same strategy the setting to `AUTO_LIGHT` does not make sense for CGAL.
When setting `HTML_COLORSTYLE=LIGHT` the divider is properly visible again.
> Divider between treeview and text

- Filtered_kernel/include/CGAL/Filtered_kernel/internal/Static_filters/Do_intersect_3.h
- Intersections_3/include/CGAL/Intersections_3/internal/Bbox_3_Triangle_3_do_intersect.h
- Intersections_3/test/Intersections_3/bbox_other_do_intersect_test.cpp
Fix static filter of `Do_intersect_3(Bbox_3,Triangle_3)`.
See the publication at https://www.semanticscholar.org/paper/High-performance-triangle-versus-box-intersection-Christensen-Karlsson/bad661b58359ec01be2deb2f47ec8fd8eb293747.
The test of intersection of `bbox` and `triangle.bbox` was missing. It implements 3 of the test out of the 13 that are needed.
* Affected package(s): Filtered_kernel
* Issue(s) solved (if any): fix #6808
> Fix static filter of Do_intersect_3(Bbox_3,Triangle_3)

- Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h
This patch allows manually fixing a range of vertices, preventing them from moving during contraction when using `Mean_curvature_flow_skeletonization`.  Naturally, this will prevent convergence towards the skeleton, but its intended use is in cases where one is interested in the meso-skeleton and needs to keep part of it fixed, similar to the `vertex_is_constrained_map` named parameter of many functions.  (My current use for it, is in combination with `smooth_shape`, which is essentially complementary to it and already has the aforementioned `vertex_is_constrained_map` feature, to achieve relatively uniform contraction of a mesh, keeping a part of it fixed.) 
The implementation is trivial, since it uses an existing part of the algorithm and it seems to work as expected in the cases I've …
> Allow manually fixing a range of vertices, when using  `Mean_curvature_flow_skeletonization`

- Alpha_shapes_3/include/CGAL/Alpha_shape_3.h
- NewKernel_d/include/CGAL/NewKernel_d/utils.h
- Surface_mesh_parameterization/doc/Surface_mesh_parameterization/Concepts/Parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Barycentric_mapping_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Circular_border_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Discrete_authalic_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Discrete_conformal_map_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Fixed_border_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Iterative_authalic_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/LSCM_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/MVC_post_processor_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Mean_value_coordinates_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Orbifold_Tutte_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Square_border_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Two_vertices_parameterizer_3.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/orbifold_enums.h
- Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/parameterize.h
- Triangulation_2/include/CGAL/Triangulation_hierarchy_2.h
Fix typo  in several packages but mainly _Surface Mesh Parameterization_, for example [here](https://doc.cgal.org/latest/Surface_mesh_parameterization/group__PkgSurfaceMeshParameterizationMainFunction.html).
> Parameterization: instanciation ->  instantiation

- Alpha_wrap_3/examples/Alpha_wrap_3/triangle_mesh_wrap.cpp
- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Oracle_base.h
- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Plugins/Alpha_wrap_3/Alpha_wrap_3_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Alpha_wrap_3/alpha_wrap_3_dialog.ui
- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
- Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h
The main change is the change from one box (value) + one check box (relative or not) to always showing absolute and relative values.
Here is the (proposed) new window:
Some other improvements along the way.
* Affected package(s): `Alpha_wrap_3`, `Polyhedron`
* Issue(s) solved (if any): fix #6805
> AW3 Plugin: Show both absolute and relative values for alpha & offset

- Installation/cmake/modules/CGAL_SetupBoost.cmake
The [documentation of Boost as third party](https://doc.cgal.org/latest/Manual/thirdparty.html#thirdpartyBoost) mentions that Boost 1.66 or more recent should be used, and `CGAL_SetupBoost.cmake` has Boost >=1.48 as requirement, and all the CMake calls then say
```
-- Found Boost: C:/dev/boost/boost_1_68_0 (found suitable version "1.68.0", minimum required is "1.48")
```
This PR fixes this number to 1.66
> Installation - update minimal valid Boost version

- Polygon_mesh_processing/include/CGAL/Rigid_triangle_mesh_collision_detection.h
They were automatically removed when we added the move operator
> Add default copy constructor and operator=

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/connected_component_polyhedron.cpp
- Polygon_mesh_processing/test/Polygon_mesh_processing/connected_component_surface_mesh.cpp
* Issue(s) solved (if any): fix #6870
> Fix dry-run of keep_largest_CCs dumping the wrong faces

- Subdivision_method_3/include/CGAL/Subdivision_method_3/subdivision_masks_3.h
Compilation fails when building Sqrt(3) subdivision code using a Epeck kernel on Windows 64-bit, where `size_t` is `long long unsigned int`.  I'm cross-compiling to WIN64 using MinGW, but, as far as I can see,  the problem should exist for MSVC builds as well.  You can use the following trivial test program to verify this:
```C++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/subdivision_method_3.h>
#include <CGAL/Polyhedron_3.h>
typedef CGAL::Exact_predicates_exact_constructions_kernel Kernel;
typedef CGAL::Polyhedron_3<Kernel> PolygonMesh;
using namespace CGAL;
namespace params = CGAL::parameters;
int main(int argc, char **argv) {
PolygonMesh pmesh;
Subdivision_method_3::Sqrt3_subdivision(pmesh, params::number_of_iterations(1)); …
```
> Fix Sqrt(3) subdivision mask calculation for Epeck kernels and Windows 64-bit

- GraphicsView/include/CGAL/Qt/qglviewer.h
- GraphicsView/include/CGAL/Qt/qglviewer_impl.h
While fixing the grid axes scaling, I have also changed the shader to simply use the basic one rather than the specific one that used lighting because:
- It's less code
- It's lighter shader
- It looks objectively better on some parts (for example, the base of the cone is not drawn, and that's visible with the light-based shader)
- It looks better overall (subjective).
Here is a comparison:
* Issue(s) solved (if any): fix #6815
> Demo: Fix grid axes scaling + use basic shader

- Polygon_mesh_processing/examples/Polygon_mesh_processing/repair_polygon_soup_example.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_polygon_soup.h
Follow-up of #6704: in the original pipeline, the "split pinched" + "remove consecutive" will make it so invalid faces have size `< 3`. For array-based soups, we cannot apply these functions since they modify the size, but we still need to remove those invalid faces.
> Complete array-based polygon soup repair

- Number_types/test/Number_types/to_interval_test_boost.cpp
Fix 'N' in this [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-74/Number_types/TestReport_Christo_MSVC-2019-Community-Release.gz)
Note that the bug is in the testsuite code, and not in CGAL itself.
> Number_types: Fix in testsuite code concerning min() and VC++

- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Arrangement_on_surface_2.txt
The construct:
```
...\ref lst_paz "code
example" ...
```
leads to the fact that the link is shown as:
```
codeexample"
```
Note the joined words and the `"` as doxygen doesn't like the return in the string here.
File: doc_output/Arrangement_on_surface_2/index.html
**Old result**
**New result**
> Documentation error in Arrangement_on_surface_2

- Three/include/CGAL/Three/Edge_container.h
- Three/include/CGAL/Three/Point_container.h
The construct:
```
...of each item ?
//!`.
//! \param viewer the active `Viewer_interface`.
```
leads to the fact that the `todo` and the `param` are joined and shown as:
```
... of each item ? . \param viewer the activeViewer_interface`.
```
Files:
- doc_output/Three/structCGAL_1_1Three_1_1Edge__container.html
- doc_output/Three/structCGAL_1_1Three_1_1Point__container.html
(also corrected a typo)
**Old result**
**New Result**
> Documentation error in Three

- Documentation/doc/Documentation/Tutorials/Tutorial_hello_world.txt
The construct:
```
In the previous section, we wrote that "Any model of the CGAL concept
Kernel provides what is required by the concept `ConvexHullTraits_2`.
```
leads to the fact that the entire paragraph is badly formatted as the double quote is not properly closed. Closing the double quote would lead to the fact that the `` `ConvexHullTraits_2` `` is not resolved properly
File:
- doc_output/Manual/tutorial_hello_world.html#intro_concept
**Old result**
**New result**
> Documentation error in Manual

- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_segment_traits_2.h
Replacing the word `Class` by `class`
See issue #6882
> Arrangement_on_surface_2: strange documentation

- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Concepts/ArrTraits--CompareYOnBoundary_2.h
Fix as indicated by @efifogel:
> ArrangementOpenBoundaryTraits_2::Compare_y_on_boundary is not a model of CompareYOnBoundary_2, so this line should be removed.
> Arrangement_on_surface_2 missing link

- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/Periodic_2_triangulation_2.h
Replaced the  `@`  by `Locate_type` like it is also in e.g. Periodic_3_triangulation_3
> Periodic_2_triangulation_2: Strange documentation

- Point_set_processing_3/include/CGAL/vcm_estimate_edges.h
The see also link provided in the function `vcm_is_on_feature_edge` was missing a starting backtick (documentation output file: Point_set_processing_3/group__PkgPointSetProcessing3Algorithms.html)
> Point_set_processing_3: Missing backtick

- Polynomial/doc/Polynomial/CGAL/Polynomial.h
In the file Polynomial/doc/Polynomial/CGAL/Polynomial.h we see some spurious backslashes resulting in the file Polynomial/classCGAL_1_1Polynomial.html in:
```
The template argument Coeff must be at least a model of IntegralDomainWithoutDivision. For all operations naturally involving division, an IntegralDomain is required. Polynomial offers a full set of algebraic operators, i.e.\ binary +, -, *, / as well as +=, -=, *=, /=; not only for polynomials but also for a polynomial and a number of the coefficient type. (The / operator must only be used for integral divisions, i.e.\ those with remainder zero.) The operations are implemented naively: + and - need a number of Coeff operations which is linear in the degree while * is quadratic. Unary + and - and (in)equality ==, != are provided as …
```
> Polynomial: Spurious backslashes

- QP_solver/doc/QP_solver/CGAL/QP_models.h
- QP_solver/doc/QP_solver/QP_solver.txt
In the documentation of QP_solver there are no links to the example file  `QP_solver/solve_convex_hull_containment_lp.h` whilst this would be  beneficial (in my opinion).
See:
- QP_solver/classCGAL_1_1Nonnegative__linear__program__from__iterators.html
- QP_solver/classCGAL_1_1Nonnegative__quadratic__program__from__iterators.html
- QP_solver/index.html#title13
> QP_solver: Missing links to include file

- Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_2.h
- Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_hierarchy_2.h
- Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_storage_traits_with_info_2.h
Correcting some incorrect backticks:
Inside code part there should not be extra backticks
- Segment_Delaunay_graph_2/classCGAL_1_1Segment__Delaunay__graph__2.html
- Segment_Delaunay_graph_2/classCGAL_1_1Segment__Delaunay__graph__hierarchy__2.html
In the see also section there was an incorrect backtick inside the
- Segment_Delaunay_graph_2/classCGAL_1_1Segment__Delaunay__graph__storage__traits__with__info__2.html
> Segment_Delaunay_graph_2: Incorrect backticks

- Triangulation/include/CGAL/Triangulation_data_structure.h
- Triangulation/test/Triangulation/CMakeLists.txt
- Triangulation/test/Triangulation/simple_io_test.cpp
- Triangulation/test/Triangulation/test_tds.cpp
Fixing the triangulation_data_structure.h I/O to make the loaded triangulation valid.
- Issue :  Giving  "vertex's adjacent full cell does not contain that vertex"  error when calling is_valid()  after dumping and reading the triangulation with the stream operator on the loaded triangulation.  (fail at Triangulation_ds_vertex.h:96)    
- Fix :
- Testing validity of the loaded triangulation
-  linking back the full cell of a vertex each time a vertex is linked to a cell.
TODO:
* Affected package(s): `Triangulation`
> Triangulation_d: fix invalid triangulation after I/O 

- Optimal_bounding_box/include/CGAL/Optimal_bounding_box/oriented_bounding_box.h
This change is caused by the improvements of named parameters which added support for reference named parameters: https://github.com/CGAL/cgal/commit/aaa3947e4001487e5b2c0c0a14e8459a9c20d7bb.
Despite not being used in OBB, compilers will try to compile the `::reference` type in `Lookup_named_param_def` if Eigen is not present, and then proceed to complain about the type being `Default& == void&`.
This PR changes the default to be `CGAL::Default`, which solves that, and also aligns with what is done in other packages such as `Surface_mesh_parameterization`.
Bug reported by @fdrmrc (thank you).
* Affected package(s): `Optimal_bounding_box`
> Do not use `void` as default for the geometric traits if Eigen is not present

- Mesh_3/include/CGAL/Mesh_3/Worksharing_data_structures.h
Fix a memory leak in the parallel code of Mesh_3.
> Mesh_3: Fix a memory leak in the parallel code

- Documentation/doc/Documentation/advanced/Configuration_variables.txt
- Documentation/doc/Documentation/advanced/Installation.txt
Fix typo in `Documentation/doc/Documentation/advanced/Configuration_variables.txt`
> fix typo and update documentation

- STL_Extension/doc/STL_Extension/CGAL/In_place_list.h
- STL_Extension/include/CGAL/In_place_list.h
In  STL_Extension/classCGAL_1_1In__place__list.html we see the line:
```
Both lists are increasingly sorted. A suitable operator< for the type T
```
the word `increasingly` means `more and more`, though most likely `in increasing order` is meant here
> STL_Extension: wrong formulation of precondition

- Triangulation_3/doc/Triangulation_3/CGAL/Regular_triangulation_3.h
Obvious error in \tparam parameter, removed `(`
> Triangulation_3: obvious error in \tparam parameter

- STL_Extension/doc/STL_Extension/CGAL/iterator.h
- STL_Extension/doc/STL_Extension/examples.txt
On the page `STL_Extension/classCGAL_1_1Dispatch__or__drop__output__iterator.html` it is obvious that the `\` is missing. To get the reference right (due to the `\ref` in the `cgalExample`) the file must also be added to the list of examples
> STL_Extension: example not shown properly

- Number_types/doc/Number_types/CGAL/CORE_BigInt.h
- Number_types/doc/Number_types/CGAL/CORE_BigRat.h
- Number_types/doc/Number_types/CGAL/Root_of_traits.h
- Number_types/doc/Number_types/CGAL/Sqrt_extension.h
- Number_types/doc/Number_types/CGAL/leda_integer.h
- Number_types/doc/Number_types/Concepts/RootOf_2.h
Use `\mathbb`
* Affected package(s):  Number_types
> Number types:   Use mathbb for mathematical Z, Q, and R

- Periodic_4_hyperbolic_triangulation_2/doc/Periodic_4_hyperbolic_triangulation_2/CGAL/Periodic_4_hyperbolic_triangulation_2.h
* Affected package(s): `Periodic_4_hyperbolic_triangulation_2`
* Issue(s) solved (if any): fix #6899 
> Undocument non-existent P4HT2 operators

- Number_types/doc/Number_types/CGAL/Quotient.h
- Number_types/doc/Number_types/NumberTypeSupport.txt
Move the implementation history of  `Quotient`  to the subsection in the User Manual 
* Affected package(s):  Number_types
> Number_types:  Cleanup concerning Quotient

- Mesh_3/examples/Mesh_3/mesh_3D_weighted_image.cpp
- Mesh_3/include/CGAL/Mesh_3/generate_label_weights.h
Computation of weights for labeled image input was broken. Using `itkDiscreteGaussianImageFilter` with voxel-number standard deviation (instead of `itkRecursiveGaussianImageFilter` with absolute standard deviation) fixes it.
Todo
> Mesh 3 - fix construction of weights image for labeled image input

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h
In the function `PMP::remove_almost_degenerate_faces`, we need to maintain a set of to-collapse edges that correspond to badly shaped faces. These edges describe faces and thus shouldn't be border halfedges.
When an edge is collapsed, the sets need to be purged from deleted edges, but also need to be purged from non-deleted edges that will become boundary edges as these become meaningless since they do not describe a face anymore.
Here is an illustration of the configuration, `prev(h, g)` is constrained, so `rm_h` is `next(h, g)`, and `edge(next(h, g), g)` is a boundary edge.
> Purge to-be-border halfedges from edges-to-collapse sets

- Number_types/test/Number_types/to_interval_test_boost.cpp
Small PR to fix error when `windows.h` is included, on Windows. The modified file `test/Number_types/to_interval_test_boost.cpp` was added in CGAL-5.5.
See errors at https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.5.1-I-121/Number_types/TestReport_Christo_MSVC-2019-Community-Release.gz, for example.
Tested locally.
> test/Number_types/to_interval_test_boost.cpp: parenthesis to fix testsuite on Window (min/max)

- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/HDT2.cpp
- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/include/internal/Qt/HyperbolicPainterOstream.h
- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/include/internal/Qt/HyperbolicPainterOstreamCK.h
- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/include/internal/Qt/HyperbolicVoronoiGraphicsItem.h
- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/include/internal/Qt/TriangulationConflictZone.h
- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/include/internal/Qt/TriangulationGraphicsItem.h
- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/include/internal/Qt/TriangulationMovingPoint.h
- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/include/internal/Qt/TriangulationPointInputAndConflictZone.h
- Hyperbolic_triangulation_2/demo/Hyperbolic_triangulation_2/include/internal/Qt/TriangulationRemoveVertex.h
- Hyperbolic_triangulation_2/doc/Hyperbolic_triangulation_2/CGAL/Hyperbolic_Delaunay_triangulation_2.h
- Hyperbolic_triangulation_2/doc/Hyperbolic_triangulation_2/Concepts/HyperbolicTriangulationFaceBase_2.h
- Hyperbolic_triangulation_2/doc/Hyperbolic_triangulation_2/PackageDescription.txt
- Hyperbolic_triangulation_2/include/CGAL/Hyperbolic_Delaunay_triangulation_2.h
- Hyperbolic_triangulation_2/include/CGAL/Hyperbolic_triangulation_2/internal/Hyperbolic_Delaunay_triangulation_traits_2_functions.h
- Hyperbolic_triangulation_2/include/CGAL/Hyperbolic_triangulation_face_base_2.h
- Hyperbolic_triangulation_2/test/Hyperbolic_triangulation_2/ht2_test_locate.cpp
- Installation/CHANGES.md
Various fixes for the `HT2` package and its demo; commits are atomic and self-explanatory.
There are some doc changes, but I would say these are fixes:
- The previous code tries to handle finite/infinite and hyperbolic/non-hyperbolic with a single flag, which caused errors to get stuff like finite but non-hyperbolic edges (see e.g. #6869). In addition, it used `tds_data()`, which is something that now also exists in `CGAL::triangulation_ds_face_base_2` and could create some conflicts. Hence, I completely re-implemented the way it was done, and added a new `tds_data`-like class in the face base called `Hyperbolic_face_data`, which adds new requirements in the face data class.
- I have removed `HDT2::insert(Point, Locate_type, int)`: The 'lt' is documented to be `HDT2::Locate_type`, which …
> Various fixes for Hyperbolic_Delaunay_triangulation_2

- Surface_mesh_parameterization/doc/Surface_mesh_parameterization/examples.txt
- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/ARAP_parameterization.cpp
- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/CMakeLists.txt
- Weights/include/CGAL/Weights/tangent_weights.h
With the introduction of the Weights package, weights were factorized away from the parameterization package, but a sign error was introduced.
* Affected package(s): `Surface_mesh_parameterization`, `Weights`
> Fix weights in ARAP parameterization's post processing

- Generator/doc/Generator/Generator.txt
- STL_Extension/doc/STL_Extension/CGAL/algorithm.h
- STL_Extension/doc/STL_Extension/CGAL/iterator.h
- STL_Extension/doc/STL_Extension/PackageDescription.txt
Replace #6889.      I do not put `()` behind functions from the STL, but stick to the convention for CGAL functions.  I removed the documentation of deprecated functions.
* Affected package(s): STL_extensions
> STL_extension: Doc Improvements

- Alpha_wrap_3/examples/Alpha_wrap_3/wrap_from_cavity.cpp
- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Alpha_wrap_3.h
- Alpha_wrap_3/include/CGAL/alpha_wrap_3.h
- Alpha_wrap_3/test/Alpha_wrap_3/test_AW3_manifoldness.cpp
- Alpha_wrap_3/test/Alpha_wrap_3/test_alpha_wrap_3_mesh.cpp
Moving some internal named parameters to the input NP rather than the output NP.
> AW3: Move some input named parameters to in_np

- Point_set_3/include/CGAL/Point_set_3.h
The title says it all
* Affected package(s):  Point_set_3
> Point_set_3:  Fix typos in the reference manual page

- .github/workflows/Remove_labels.yml
Added a workflow that removes the `Tested` labels during a new commit in a pull request
* Affected package(s): -
> Add Workflow to remove the 'Tested' label

- .github/workflows/build_doc.yml
Added a workflow that adds a reaction during the build command.  `/build:`
Fix also set-output which has become deprecated.
* Issue(s) solved (if any):  #6964
> Update build_doc Workflow to add reaction

- BGL/include/CGAL/boost/graph/Euler_operations.h
- BGL/include/CGAL/boost/graph/IO/Generic_facegraph_builder.h
- BGL/include/CGAL/boost/graph/generators.h
- BGL/include/CGAL/boost/graph/helpers.h
- BGL/include/CGAL/boost/graph/internal/helpers.h
- BGL/include/CGAL/boost/graph/iterator.h
- BGL/test/BGL/test_test_face.cpp
- Heat_method_3/doc/Heat_method_3/PackageDescription.txt
- Heat_method_3/include/CGAL/Heat_method_3/Surface_mesh_geodesic_distances_3.h
- Heat_method_3/include/CGAL/Heat_method_3/internal/Intrinsic_Delaunay_triangulation_3.h
- Heat_method_3/package_info/Heat_method_3/dependencies
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/bbox.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/detect_features.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/refine_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/locate.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/measure.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/merge_border_vertices.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/shape_predicates.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangle.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_faces.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h
- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
- Surface_mesh/include/CGAL/boost/graph/graph_traits_Surface_mesh.h
- Surface_mesh_topology/doc/Surface_mesh_topology/PackageDescription.txt
Motivated by losing a bit of time because I was calling Euler operations on removed descriptors.
This PR:
- moves code from `is_valid_xxx_graph` into `is_valid_xxx_descriptor` (which were completely unused)
- actually calls these in preconditions in `BGL` and `PMP`
- fixes a couple of doc issues in `is_valid_xxx_graph` functions
- add overloads of `is_valid_xxx_descriptor` for `Surface_mesh` (to call `Surface_mesh::is_valid(descriptor)`
- some misc minor cleaning and improvements.
Runtime in debug in PMP tests was unchanged.
* Affected package(s): `BGL`, `Polygon_mesh_processing`, `Surface_mesh`
> BGL graph validity improvements

- Kernel_d/include/CGAL/Kernel_d/Sphere_d.h
Address warning in [this ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-99/Kernel_d/TestReport_lrineau_Fedora-with-LEDA.gz) testsuite.
Instead of creating a `Rep` and right afterwards setting a data member, add a parameter to the Rep constructor for initialization. 
* Affected package(s): Kernel_d
> Kernel_d: Address -Wmaybe-uninitialized warning

- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Alpha_wrap_3.h
- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Alpha_wrap_AABB_geom_traits.h
- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Point_set_oracle.h
- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Segment_soup_oracle.h
- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Triangle_mesh_oracle.h
- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Triangle_soup_oracle.h
- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/oracles.h
- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/splitting_helper.h
`Alpha_wrap_AABB_traits` is a model of [AABBGeomTraits](https://doc.cgal.org/latest/AABB_tree/classAABBGeomTraits.html) and not [AABBTraits](https://doc.cgal.org/latest/AABB_tree/classAABBTraits.html).
Rename it to `Alpha_wrap_AABB_geom_traits`.
> Rename traits class to avoid confusion

- Mesh_3/include/CGAL/Mesh_3/initialize_triangulation_from_labeled_image.h
- Mesh_3/include/CGAL/Mesh_3/search_for_connected_components_in_labeled_image.h
When meshing from labeled images
* without detection of connected components
* with detection of connected components and random shooting from a seed that is too close to the surface (master)
* with detection of connected components and random shooting from a better chosen seed (commit de9fbdb in this PR) 
* with detection of connected components that have not been already detected/initialized by feature protection
> Mesh 3 for labeled images - avoid vertex clusters on surfaces

- Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_widget.ui
When generating a grid in the demo it is better that it is in the xy plane.
> Polyhedron Demo: Fix upper right corner

- Orthtree/include/CGAL/Orthtree.h
- Orthtree/include/CGAL/Orthtree/Node.h
Fix a memory leak by freeing all nodes, right as the destructor would do, but keeping the root node.
* Affected package(s): Orthtree
* Issue(s) solved (if any): fix #6951
> Orthtree:  Fix memory leak

- Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h
We had hard coded that vertex or face color are `unsigned char`, but encountered files where it is declared `float`.
> Surface_mesh: Deal with PLY files with vertex and face color of type float

- Snap_rounding_2/doc/Snap_rounding_2/Concepts/SnapRoundingTraits_2.h
- Snap_rounding_2/doc/Snap_rounding_2/Snap_rounding_2.txt
- Snap_rounding_2/include/CGAL/Snap_rounding_kd_2.h
deduplicate `#include` and fix typos in the documentation
* Affected package(s):  Snap_rounding
> Snap_rounding:  cleanup

- BGL/include/CGAL/boost/graph/selection.h
`is_selected` is documented to be a `face_descriptor` -> `bool` property map.
> Fix implicit conversion from `std::size_t` to `bool` creating ambiguous calls

- Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/TestMesh.cpp
TestMesh.cpp uses boost program options, and currently has no default for a mesh.
* Affected package(s): Surface_mesh_shortest_path
> Shortest Path: Add a default parameter so that the test does something

- Tetrahedral_remeshing/examples/Tetrahedral_remeshing/tetrahedral_remeshing_of_one_subdomain.cpp
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/collapse_short_edges.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/compute_c3t3_statistics.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/flip_edges.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/smooth_vertices.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/split_long_edges.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
- Tetrahedral_remeshing/include/CGAL/tetrahedral_remeshing.h
- Tetrahedral_remeshing/test/Tetrahedral_remeshing/test_tetrahedral_remeshing_of_one_subdomain.cpp
The doc and name say that `cell_is_selected_map` is a property map, and it was not!
Todo
> Breaking change in Tetrahedral remeshing : the named parameter `cell_is_selected_map` is now consistently a property map in documentation and code.
> Tet remeshing - `cell_is_selected_map` should be a property map

- Barycentric_coordinates_2/examples/Barycentric_coordinates_2/CMakeLists.txt
- Barycentric_coordinates_2/test/Barycentric_coordinates_2/CMakeLists.txt
- Polygonal_surface_reconstruction/examples/Polygonal_surface_reconstruction/CMakeLists.txt
- Polygonal_surface_reconstruction/test/Polygonal_surface_reconstruction/CMakeLists.txt
- Scripts/developer_scripts/test_merge_of_branch
- Shape_regularization/examples/Shape_regularization/CMakeLists.txt
- Shape_regularization/test/Shape_regularization/CMakeLists.txt
- Weights/examples/Weights/CMakeLists.txt
- Weights/test/Weights/CMakeLists.txt
Address the warning that a `CMakeLists.txt` file's first command must be `cmake_minimum_required()`
In the testsuite of `Installation` is also a warning, but that concerns probably the setup of testsuites
```
CMake Warning:
Manually-specified variables were not used by the project:
CMAKE_POLICY_DEFAULT_CMP0053
LEDA_INCLUDE_DIR
WITH_CGAL_Qt3
```
* Affected package(s): several
> CGAL: Fixes for cmake 3.25

- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
During Weighted_point_23 -> Point_23 implicit conversion removal (https://github.com/CGAL/cgal/pull/2102), and more precisely in the commit https://github.com/CGAL/cgal/commit/42506237b212593bc105fdc95c58118633f5afc0 I have added `Construct_point_23`, I have added the overload `Point_23 Construct_point_23(Point_23)` to the requirements of the `TriangulationTraits_23` concepts.
However, I forgot to also add it to the `Kernel` concept, which needs to also contain these requirements since we claim that any model of `Kernel` is a model of `TriangulationTraits_23`.
> Fix the Kernel concept being weaker than TriangulationTraits_23 requirements

- Intersections_3/test/Intersections_3/test_intersections_Line_3.cpp
The construction of the line points is only valid if the tetrahedron is well oriented.
* Affected package(s): `Intersections_3`
> Fix Line_3-Tet_3 intersection test

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
Disable the `sharpFeaturesGroup` for gray level images. Feature protection is not available yet for gray-level images.
Keeping the "protect features" checkbox "on" was crashing the demo.
> Polyhedron demo for Mesh_3 - disable features detection for gray level images

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h
I consider this as a bug fix since without this option it can be hard to exploit the bit of reversibility of a component.
> CGAL::PMP::compatible_orientations: add missing option

- Combinatorial_map/include/CGAL/Compact_container_with_index.h
- Documentation/doc/Documentation/Developer_manual/Chapter_iterators_and_circulators.txt
- STL_Extension/doc/STL_Extension/CGAL/Compact_container.h
- STL_Extension/doc/STL_Extension/CGAL/Concurrent_compact_container.h
- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
- STL_Extension/test/STL_Extension/test_Compact_container.cpp
- STL_Extension/test/STL_Extension/test_Concurrent_compact_container.cpp
- TDS_3/include/CGAL/Triangulation_data_structure_3.h
dereferencable -> dereferenceable     
I deprecated the function but kept it. I do not test the deprecated version, and I do not put it into the changelog. 
* Affected package(s): STL_extension
* Issue(s) solved (if any): fix #6834
> STL Extensions: Correct spelling

- Spatial_searching/doc/Spatial_searching/CGAL/Weighted_Minkowski_distance.h
Only in the documentation:    `power >= 0`   ->  `power=0`.
* Issue(s) solved (if any): fix #7029
> Spatial_searching: Fix doc

- BGL/include/CGAL/boost/graph/named_params_helper.h
- Point_set_3/include/CGAL/Point_set_3.h
- Point_set_processing_3/include/CGAL/IO/read_off_points.h
- Point_set_processing_3/include/CGAL/IO/read_ply_points.h
- Point_set_processing_3/include/CGAL/IO/read_xyz_points.h
- Point_set_processing_3/include/CGAL/IO/write_off_points.h
- Point_set_processing_3/include/CGAL/IO/write_ply_points.h
- Point_set_processing_3/include/CGAL/IO/write_xyz_points.h
- Point_set_processing_3/include/CGAL/bilateral_smooth_point_set.h
- Point_set_processing_3/include/CGAL/edge_aware_upsample_point_set.h
- Point_set_processing_3/include/CGAL/jet_estimate_normals.h
- Point_set_processing_3/include/CGAL/mst_orient_normals.h
- Point_set_processing_3/include/CGAL/pca_estimate_normals.h
- Point_set_processing_3/include/CGAL/scanline_orient_normals.h
- Point_set_processing_3/include/CGAL/structure_point_set.h
- Point_set_processing_3/include/CGAL/vcm_estimate_normals.h
Instead of returning `true`, look for a normal pmap in the point set, and in the named parameters.
* Affected package(s): Point_set_3, PSP_3
> Point_set_3 - `NP_helper::has_normal_map()` should not always return true

- CGAL_Core/include/CGAL/CORE/CoreIO_impl.h
Do not compare a `char` with `EOF`
* Issue(s) solved (if any): fix #6790
> CORE: Use istream.eof()

- Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h
Initialize a variable. This is not really needed, because we know that the inner body of the nested for loop will be executed, but the compiler doesn't because it has never read the paper. See this [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-129/Polygon_mesh_processing/TestReport_lrineau_Debian-stable-Release.gz)
* Affected package(s): PMP:  Polyhedral_envelope
> PMP: Fix for a -Wmaybe-uninitialized

- GraphicsView/include/CGAL/Qt/camera.h
- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/IO/triangulation_3_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Smoothing_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_triangulation_3_item.cpp
- Triangulation_2/include/CGAL/Triangulation_2.h
When compiling the Polyhedron demo with  `add_definitions ( -DCGAL_NO_DEPRECATED_CODE )`    there is an error message for `std::array` being not defined.
I would also consider it as a good idea to add the above mention `#define`  in the CMakeLists.txt flle of the demo. What do you think @sloriot ?
> Three, and Polyhedron Demo: Add an #include and remove deprecated code

- Scripts/developer_scripts/run_testsuite_with_ctest
So far, the config type was only used if Cygwin was detected, because implicitly it was for the Visual Studio CMake generator. But the config type maybe used on other platforms. On MacOS, with the XCode generator, the config type is required.
So, the change is that `CONFIG_TYPE` is used if and only if it is defined. Simple.
I have based the change on 5.4 because we need the change for the testsuite on `monet`, a MacOS test machine, and we still test 5.4.x and 5.5.x.
@sloriot This PR should be in the current batch of PRs to be tested.
* Affected package(s): Scripts, testsuite
> Scripts, run_testsuite_with_ctest: CONFIG_TYPE maybe used on other platforms

- Kernel_23/include/CGAL/Projection_traits_xy_3.h
- Triangulation_2/include/CGAL/Constrained_Delaunay_triangulation_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
We can enable `Triangulation_2::inexact_locate()` out of the box for the projection in the xy-plane. 
We should have a look if it is also trivial for the projections in the xz and yz plane. 
* Affected package(s): Kernel_23, Triangulation_2
> Projection_traits_xy_3: Enable structural filtering

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h
Be consistent with `inconsistent_classification()`
> Conditional assertions

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
This reverts commit a90488fce5e5d7defb387d57560afda09819db38, introduced by PR #6992
Feature preservation (resampling allowed) was broken by this commit
> Tet remeshing - fix vertices `dimension`

- Optimal_transportation_reconstruction_2/demo/Optimal_transportation_reconstruction_2/render.cpp
- Optimal_transportation_reconstruction_2/demo/Optimal_transportation_reconstruction_2/scene.h
- Optimal_transportation_reconstruction_2/examples/Optimal_transportation_reconstruction_2/otr2_simplest_example.cpp
- Optimal_transportation_reconstruction_2/include/CGAL/OTR_2/Cost.h
- Optimal_transportation_reconstruction_2/include/CGAL/OTR_2/Reconstruction_face_base_2.h
- Optimal_transportation_reconstruction_2/include/CGAL/OTR_2/Reconstruction_triangulation_2.h
- Optimal_transportation_reconstruction_2/include/CGAL/OTR_2/Reconstruction_vertex_base_2.h
- Optimal_transportation_reconstruction_2/include/CGAL/OTR_2/Sample.h
- Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h
- Optimal_transportation_reconstruction_2/test/Optimal_transportation_reconstruction_2/test_reconstruction_until.cpp
Keep the samples in a `std::vector<Sample>`  to avoid a memory leak. I guess that one can still have an inconsistent data structure after a failed `run()` that led to the leak.
* Affected package(s): Optimal_transport_reconstruction
* Issue(s) solved (if any): fix #0000, fix #7132
> Optimal Transport Reconstruction: Fix memory leak

- Spatial_searching/include/CGAL/Search_traits_adapter.h
It is 10 time faster than way when building the kd-tree. Only apply to property maps return points as lvalue.
> Replace shared_ptr with a plain copy

- Orthtree/test/Orthtree/test_octree_grade.cpp
Remove an assertion.  It just may happen that the random input already has a graded tree.
* Affected package(s): Orth_tree
* Issue(s) solved (if any): fix #7080
> Orthree: Fix testsuite code

- Convex_hull_2/test/Convex_hull_2/ch_test_CH.cpp
- Convex_hull_2/test/Convex_hull_2/ch_test_SC.cpp
- Convex_hull_2/test/Convex_hull_2/ch_test_SH.cpp
- Convex_hull_2/test/Convex_hull_2/ch_test_SS.cpp
Remove the tests without exact predicates. We just know that they may fail.
* Affected package(s): Convex_hull_2
* Issue(s) solved (if any): fix #7107
> Convex_hull_2: Do not assert without exact predicates

- Boolean_set_operations_2/examples/Boolean_set_operations_2/bezier_traits_adapter2.cpp
- Polyline_simplification_2/demo/Polyline_simplification_2/Polyline_simplification_2.cpp
- Straight_skeleton_2/include/CGAL/Polygon_offset_builder_2.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Polygon_offset_builder_2_impl.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_aux.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_builder_2_impl.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_builder_traits_2_aux.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_2/debug.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_builder_2.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_converter_2.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_halfedge_base_2.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_vertex_base_2.h
- Straight_skeleton_2/include/CGAL/Trisegment_2.h
- Straight_skeleton_2/include/CGAL/constructions/Straight_skeleton_cons_ftC2.h
- Straight_skeleton_2/include/CGAL/predicates/Straight_skeleton_pred_ftC2.h
- Straight_skeleton_2/test/Straight_skeleton_2/CMakeLists.txt
- Straight_skeleton_2/test/Straight_skeleton_2/issue7149.cpp
When inputs have some collinear segments and an e0-e2 collinearity configuration appears, seed computation was wrongly assumed to simply always be the middle point between the two (collinear) segments.
A first fix was done https://github.com/CGAL/cgal/pull/5213.
Once the seed is known and the node has been created, the trisegment history takes care of reproducing the correct geometrical position during construction of the skeleton. However, when constructing an offset, we previously lost trisegment trees and only kept triedge information. Without the trisegment history, the code wrongly took the middle point again as seed.
This PR makes it so we keep this history in mind (it's simply a boost intrusive pointer) rather than just the triedge.
* Affected package(s): `Straight_skeleton_2`
* …
> Fix seed computation in SLS offset computation

- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
- Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_const_Del_triangulation_2.h
- Triangulation_2/test/Triangulation_2/test_const_del_triangulation_2.cpp
EPECK does not return a ref for example.
> Use deduced type for source/target of a segment

- Classification/examples/Classification/example_ethz_random_forest.cpp
- Classification/examples/Classification/example_opencv_random_forest.cpp
- Classification/examples/Classification/gis_tutorial_example.cpp
We have several examples that write the result in the same file. In case they are executed in parallel in a testsuite that may be a problem.
Reading the diff while creating this pull request I notice that the first two names were equal, but the third one (where we have the issue #7120) was not. So this won't fix the issue, but the PR makes nevertheless sense.  
It finally turned out that the real problem is that the fairing step done by filling a hole of a terrain led to a mesh that is no longer a terrain. We had to reduce the degree of the fairing continuity. 
> Classification: Write to different files and change degree of fair()

- SMDS_3/include/CGAL/SMDS_3/tet_soup_to_c3t3.h
add `if(verbose)` when needed in `tet_soup_to_c3t3()`
(tetrahedral remeshing uses this function and log is overwhelmed with these `std::cout`)
* Affected package(s): SMDS_3
> Tet_soup_to_c3t3 - reduce verbosity

- Spatial_searching/doc/Spatial_searching/examples.txt
- Spatial_searching/examples/Spatial_searching/CMakeLists.txt
- Spatial_searching/examples/Spatial_searching/iso_rectangle_2_query_projection.cpp
Added iso_rectangle_2_query example adapted for 2D spatial searching using 3D projected points. Follow-up on a discussion https://github.com/CGAL/cgal/discussions/7135
* Affected package(s): dD Spatial Searching
> Add an example for spatial searching with projection

- Convex_hull_2/doc/Convex_hull_2/Convex_hull_2.txt
- Convex_hull_2/doc/Convex_hull_2/examples.txt
- Convex_hull_2/examples/Convex_hull_2/ch_delaunay_2.cpp
Add an example where we extract the not necessarily strong convex hull from a triangulation.
* Affected package(s): CH2 
* Issue(s) solved (if any): fix #7113
> Convex_hull_2: Use of 2D Delaunay

- Polyhedron/demo/Polyhedron/include/CGAL/statistics_helpers.h
Clamp as `acos()` operates on `[-1,1]`.   Without that a single `nan` ruins the mean value.
> 3D Demo: Fix statistics on angles

- Intersections_3/test/Intersections_3/intersection_test_helper.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_aff_transformation_2.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_cls_sphere_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_points_implicit_sphere.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_mf_plane_3_to_2d.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/pmp_compute_normals_test.cpp
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_locate.cpp
- Spatial_searching/test/Spatial_searching/Orthogonal_incremental_neighbor_search.cpp
- Spatial_searching/test/Spatial_searching/Splitters.cpp
pmp_compute_normals_test: Computation of null vector as normal for degenerate faces is only verified for epeck
test_pmp_locate: Several predicates are only verified for epeck as they can fail with non-exact kernels
Should fix test on [this plateform](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-I-76/Polygon_mesh_processing/TestReport_gimeno_ArchLinux-clang-Release.gz).
* Issue(s) solved (if any): fix #6783
> Pmp tests only for epeck

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/measure.h
Factorize code in order to guarantee that the halfedge returned by  `longest_border()` is among those reported by `extract_boundary_cycles()`.   We might think about adding an overload of `longest_border()` that takes the range produced by `extract_boundary_cycles()`, because otherwise one traverses all halfedges twice.
> PMP: Make longest_border() extract_boundary_cycles() coherent

- Nef_3/include/CGAL/Nef_3/Binary_operation.h
- Nef_3/include/CGAL/Nef_3/binop_intersection_tests.h
Within `Nef_3/include/CGAL/Nef_3/binop_intersection_tests.h`, the current code calculates bounding boxes for intersecting elements multiple times when performing intersection tests. While calculating the bounding boxes is typically a very fast operation, it does impact performance, particularly when the number of elements is large. The current code implements two `std::vector<Nef_box>` called `a` and `b` which are repeatedly cleared and recomputed.
At first, it was considered it might be intentional to re-calculate because the SNC structure is updated via the callbacks. However, in the binary operation, the source operands are const, and the result is a new value. The code uses a `const_cast` to cast away constness from the parameters.  The first step was to make the necessary changes to …
> Nef_3: performance in binop_intersection_tests

- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/overlay_unbounded.cpp
- Arrangement_on_surface_2/test/Arrangement_on_surface_2/Traits_base_test.h
- Cone_spanners_2/examples/Cone_spanners_2/theta_io.cpp
- Cone_spanners_2/test/Cone_spanners_2/theta_exact.cpp
- Cone_spanners_2/test/Cone_spanners_2/theta_inexact.cpp
- Cone_spanners_2/test/Cone_spanners_2/yao_exact.cpp
- Cone_spanners_2/test/Cone_spanners_2/yao_inexact.cpp
- Intersections_3/include/CGAL/Intersections_3/internal/Plane_3_Triangle_3_intersection.h
- STL_Extension/include/CGAL/exceptions.h
- Replace use of lexical_cast&lt;std::string&gt; with std::to_string
- use std::prev in Plane_3_Triangle_3_intersection.h due to lack of implicit header include.
* Affected package(s): Arrangement_on_surface_2,Cone_spanners_2, Intersections_3, STL_Extension
* Issue(s) solved (if any): C++11 modernisation.
* License and copyright ownership: CGAL Authors
> Replace use of boost::lexical_cast<std::string> with std::to_string

- Polyhedron/demo/Polyhedron/Scene.cpp
Fix current context in the destroy of the Scene. Fixes the error:
> QOpenGLVertexArrayObject::destroy() failed to restore current context
that we can see at the exit of the demo.
> CGAL 3D demo: Fix current context in the destroy of the Scene

- Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_example.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/refine_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h
- Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
The criterion that takes the scalar_product of the cross products  is maybe adapted to minimize the curvature when triangulating faces,  but should_flip() is used in `PMP::isotropic_remeshing()`, `PMP::refine()`, and `PMP::remove_almost_degenerate_faces()`. These algorithms aim to produce well-shaped elements. The criterion is not adapted to these algorithms: for example, on a flat mesh the scalar product is meaningless so it will pick the diagonal which maximizes the product of the lengths and product of sines, but this might create very anisotropic elements since the sine of obtuse angles is still positive. In `PMP::isotropic_remeshing()`, we actually do not notice how bad the flip is because other operations (smoothing, collapsing, splitting) counter balance it.
The "new" criterion is …
> Modify flipping criteria in PMP::isotropic_remeshing and PMP::refine

- Intersections_2/include/CGAL/Intersections_2/Segment_2_Segment_2.h
Only applied with a Cartesian kernel with a FT being floating point.
> Add special case for intersection of a vertical segment with an horizontal segment

- Inscribed_areas/doc/Inscribed_areas/CGAL/Largest_empty_iso_rectangle_2.h
- Inscribed_areas/examples/Inscribed_areas/largest_empty_rectangle.cpp
- Inscribed_areas/include/CGAL/Largest_empty_iso_rectangle_2.h
Points that are on the boundary of the bounding iso rectangle led to wrong results. As such points have no influence on the result we can just ignore them.   
* Affected package(s): Inscribed_areas
* Issue(s) solved (if any): fix #7183
> Largest Empty Iso Rectangle: Ignore points on the border

- Polygon/include/CGAL/Polygon_2.h
- Polygon/test/Polygon/issue7228.cpp
When a vertex circulator pointing on the last element gets erased the erase function must return the circulator pointing to the first element.
* Affected package(s): Polygon
* Issue(s) solved (if any): fix #7228
> Polygon: Fix erase(Vertex_circulator)

- Triangulation_3/include/CGAL/Triangulation_3.h
`CGAL/Triangulation_3.h`: Rewrite/factorize remove functions. There is **a lot** of copy-pasting in that file, 620 lines were removed and I could have gone on.
New private sub-functions used to factorize code.
- `create_hole_outer_map`,
- `create_triangulation_inner_map`.
- `copy_triangulation_into_hole`, and
- `fill_auxiliary_triangulation_with_vertices_around_v`.
* License and copyright ownership: maintenance by GeometryFactory, copyrights unchanged
> Triangulation_3.h: Rewrite/factorize remove functions

- Circulator/include/CGAL/circulator.h
- STL_Extension/include/CGAL/Base_with_time_stamp.h
- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/Time_stamper.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
- Triangulation_2/include/CGAL/Triangulation_2/internal/Polyline_constraint_hierarchy_2.h
- Triangulation_2/test/Triangulation_2/issue_4405.cpp
- Triangulation_2/test/Triangulation_2/test_cdt_degenerate_case.cpp
This pull-request has three commits:
- Introduce `Base_with_time_stamp`, that introduces a real vertex base template class, instead of various ad-hoc solutions in various places.
- Use `Output_rep` to display debug info, that introduces a nice way to display the debug information about vertices in CDT_2 debug messages.
- `Circulator_from_container<const Container>` now works... because otherwise that was a hamper against adding `const`.
* Affected package(s): STL_Extension, Circulator (that should be merged into `STL_Extension`), and `Triangulation_2`
* License and copyright ownership: maintenance by GeometryFactory, ownership unchanged.
> STL_Extension/Triangulation_2: improve CDT_2 debug messages

- Installation/lib/cmake/CGAL/CGALConfig.cmake
With the current `master`, if one configure all CGAL with `-DWITH_examples=ON`, `-DWITH_tests=ON`... then the compiler warnings are disable for tests (but not for examples).
This pull-request fixes the situation, until I can find a better workaround.
This PR is a bug-fix... but it has conflicts with CGAL-5.4.x and 5.5.x. I have decided to push it to `master` only, given that the impact is probably quite limited to myself only.
> Fix CMAKE_NO_SYSTEM_FROM_IMPORTED

- Nef_2/include/CGAL/Nef_2/PM_checker.h
- Nef_S2/include/CGAL/Nef_S2/SM_const_decorator.h
- Optimal_transportation_reconstruction_2/demo/Optimal_transportation_reconstruction_2/scene.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
Address warnings in several packages in this [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.6-Ic-175.shtml) all similar to:
`include/CGAL/Nef_S2/SM_const_decorator.h:302:7: warning: variable 'iso_vert_num' set but not used [-Wunused-but-set-variable]`
Concerning SLS it is already fixed in another PR.
* Affected package(s):  Nef_2, Nef_S2,  Optimal_transport, PMP, Tetrahedral_remeshing,
> Use CGAL_assertion_code()

- Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_bounded_normal_change.cpp
The first improvement is to collapse half of the edges and not just one, as consequence of a typo.
We should also switch from `operator>>()`   to functions that can read formats different from `.off`.
> Surface Mesh Simplification: Improve Examples

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_function.h
When using the Mesh_3 plugin, one might see that message:
> USE SIZING FIELD!
It is now replaced by:
> Note: Mesh_3 is using a sizing field based on AABB tree.
> Polyhedron demo, Mesh_3 plugin: modify the criptic debug message "USE SIZING FIELD!"

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
Even if the c3t3 has no complex cells, there may be facets in complex, edges in complex, vertices in complex, or even just vertices of the underlying triangulation, possibly with weights.
Hence, the bbox should not be the default when `cells_in_complex()` is empty. This PR adds a fallback to the bbox of the underlying triangulation vertices.
* Affected package(s): Demo
> Polyhedron demo - fix the bbox of `scene_c3t3_item`

- .github/workflows/send_email.yml
- .github/workflows/wiki_notification.yml
Adding a workflow to send email notifications when a change is made on the wiki.
Sometimes the action is executed before the github api updates and therefore the email information does not match the last change.
* Issue(s) solved (if any): https://github.com/CGAL/cgal/issues/2000
Edit by @lrineau: note that this PR, as with all modifications to `.github/`, cannot be tested in `integration`.
> Email notifications about changes to the GitHub wiki

- .github/workflows/build_doc.yml
add the url to the job log in case of an error during build_doc
* Issue(s) solved (if any): cgal#7227
> Github Action build_doc Add URL to job log in case of an error

- Spatial_searching/doc/Spatial_searching/CGAL/Weighted_Minkowski_distance.h
- Spatial_searching/include/CGAL/Weighted_Minkowski_distance.h
As the power computation with an arbitrary number does not work for all number types we pass via  double arithmetic.
This might in the future be optimized, for example for integral powers.
* Issue(s) solved (if any): fix #7194
> Spatial searching: Make weighted Minkowski Distance working with Epeck

- Maintenance/test_handling/testresult.css
Fix missing the green color for the "y" square at the top of the column.
Testsuite improvements #2205
> Test suite Fix missing the green color for the y square at the top of the column

- Installation/CHANGES.md
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Smoothing/curvature_flow_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/smooth_shape.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_shape_smoothing.cpp
- STL_Extension/include/CGAL/STL_Extension/internal/parameters_interface.h
Add the possibility to not resize the mesh obtained with `smooth_shape()`.  This is done based on a private communication of a user.   Added the Boolean named parameter `scale` which defaults to `true`  in order to stay backward compatible. 
* Affected package(s): Polygon Mesh Processing
* Small feature: [link](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/smooth_shape_without_scaling) -- **pre-approved on 2023/02/24**
* Documentation:  [link](https://cgal.github.io/7276/v0/Polygon_mesh_processing/group__PMP__meshing__grp.html#ga57fa999abe8dc557003482444df2a189)
* Change log: _Added a named parameter to `CGAL::Polygon_mesh_processing::smooth_shape()` to disable scaling to compensate volume loss._
> PMP:  Add np for not scaling smoothed mesh

- Mesh_3/include/CGAL/Mesh_3/experimental/AABB_filtered_projection_traits.h
- Mesh_3/include/CGAL/Mesh_3/experimental/Sizing_field_with_aabb_tree.h
- Make `Sizing_field_with_aabb_tree` a lightweight object carrying a `shared_ptr`
- Use per-patch kd-trees to speed up distance queries
Note that `Sizing_field_with_aabb_tree` is for the moment an undocumented class from `<Mesh_3/experimental/Sizing_field_with_aabb_tree.h>`.
* License and copyright ownership: maintenance by GeometryFactory, unchanged
> Mesh_3: Improve Sizing_field_with_aabb_tree speed

- Number_types/include/CGAL/Sqrt_extension/Sqrt_extension_type.h
We have a compilation error in the [Number_type testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.6-I-195.shtml#Number_types) for VC2017 and VC2015.   It compiles locally with VC2017 when I move a friend function out of the scope of the class, Also no need to be friend.     Also I first I thought it is only in boost 1.70, but it it also in boost 1.74. 
> Number_types: Fix VC2017 bug with boost::mp

- Surface_mesh/examples/Surface_mesh/sm_iterators.cpp
This adds a very basic example how how to access the coordinates of a vertex. 
Latest source code.
* Issue(s) solved (if any): https://github.com/CGAL/cgal/discussions/7341
* License and copyright ownership: Freely released in the public domain.
> Add example of printing vertex coordinates

- BGL/doc/BGL/PackageDescription.txt
- BGL/include/CGAL/boost/graph/iterator.h
- Surface_mesh/doc/Surface_mesh/Surface_mesh.txt
- Surface_mesh/doc/Surface_mesh/dependencies
- Surface_mesh/doc/Surface_mesh/examples.txt
- Surface_mesh/examples/Surface_mesh/CMakeLists.txt
- Surface_mesh/examples/Surface_mesh/sm_points.cpp
As pointed out by @oleg-alexandrov the functions to access the coordinates of a vertex are rather hidden.
This PR at the same time adds the missing documentation for `Vertex_around_face_circulator`.
This PR does not replace #7342 but complements it.
* Issue(s) solved (if any): fix #7341
> Surface_mesh: Add example for accessing points

- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h
- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
- Triangulation_2/include/CGAL/Constrained_Delaunay_triangulation_2.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
- Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h
Improve the documentation of  the constrained triangulation classes to make clear what happens 
- when degenerate constraints are inserted, 
- when a sequence of points and index pairs are inserted.
* Issue(s) solved (if any): fix #7336
> Triangulation_2: Clarify what happens with degenerate constraints

- Arrangement_on_surface_2/include/CGAL/Arr_counting_traits_2.h
- Arrangement_on_surface_2/include/CGAL/Arr_topology_traits/Arr_unb_planar_construction_helper.h
- Arrangement_on_surface_2/include/CGAL/Arr_tracing_traits_2.h
- Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arr_traits_adaptor_2.h
- Arrangement_on_surface_2/include/CGAL/IO/Arr_text_formatter.h
Several fixes:
1. Fix of issue #7311: Fixed handling unbounded curves that are both infinite on the left and infinite at the top
2. Tracing and counting traits: Added a parameter pack to the constructor and passed it to the underlying traits; also disabled the copy constructors.
3. Replaced copy-constructor of traits with simple conversion in Arr_traits_adaptor_2
4. Properly set the data of extended records using setters in Arr_text_formatter.h
* Affected package(s): Arrangement_on_surface_2
* Issue(s) solved (if any): fix #7311
> Arrangement_on_surface_2 fixes

- Triangulation_2/include/CGAL/Triangulation_2/internal/Polyline_constraint_hierarchy_2.h
- Triangulation_2/test/Triangulation_2/issue_7328.cpp
While copying a polyline constraint the input status was not copied.
* Issue(s) solved (if any): fix #7328
> Triangulation_2: Fix copy of CDT_plus_2

- GraphicsView/doc/GraphicsView/CGAL/Qt/Converter.h
- GraphicsView/include/CGAL/Qt/Converter.h
Adds converter from `std::list<K::Point_2>` to `QPolygonF` that was documented but not implemented. Also fixes documentation for the converter in the opposite direction to match the actual implementation and adds documentation for the converter from `K::Circular_arc_point_2` to `QPointF`.
* Affected package(s): Qt
> Converter to qpolygon

- Polyhedron/demo/Polyhedron/Scene_triangulation_3_item.cpp
- Polyhedron/demo/Polyhedron/Triangle_container.cpp
- Polyhedron/demo/Polyhedron/Viewer.cpp
- Triangulation_3/include/CGAL/Triangulation_3.h
In order to improve the quality of the code, I have decided to always compile with `-fsanitize=address -fsanitize=undefined` (ASAN+UBSAN) when I compile in `Debug`. And the polyhedron demo triggers several UBSAN warnings. Here are the fixes.
* Affected package(s): Polyhedron/demo
> CGAL 3D demo: fix USBAN warnings

- Installation/cmake/modules/FindGMP.cmake
- Installation/cmake/modules/FindMPFR.cmake
- Installation/test/Installation/test_gmp_mpfr_dll.cpp
`gmp-10.dll` is the name of the library built by vcpkg for MSVC and installed on Christo MSVC 2019 testsuite.
> Installation - add new possible GMP lib name for MSVC

- Installation/CHANGES.md
- Minkowski_sum_2/include/CGAL/Minkowski_sum_2/Hole_filter_2.h
Fixed hole filtering. The code used to erroneously remove holes from an std::deque of holes that did not affect the Minkowski sum. Now it simply adds those that do affect it.
The error could be reproduced only with clang. (Apparently, g++ tolerated the erroneous condition.)
* Affected package(s): Minkowski_sum_2
* Issue(s) solved (if any): none submitted
* Feature/Small Feature (if any): na
> Minkowski_sum_2: fix hole filter

- Installation/include/CGAL/config.h
- Principal_component_analysis/include/CGAL/PCA_util.h
- Principal_component_analysis/include/CGAL/PCA_util_Eigen.h
The [PCA testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-211/Principal_component_analysis/TestReport_Christo_MSVC2017-Debug-64bits.gz) reveals a compilation problem when multiplying a  `boost::mp` with an Eigen matrix or expression.
* Affected package(s): Principal_component_analysis
> Installation: Workaround for boost::mp / Eigen problem

- Surface_mesh_deformation/doc/Surface_mesh_deformation/Surface_mesh_deformation.txt
Correcting usage usage of `iframe` tag:
- add value to `allowfullscreen`
- prevent warnings on dtd validation about usage of `center` tag inside a `p` tag
> Correcting usage of `iframe` tag

- Nef_3/include/CGAL/draw_nef_3.h
Draw only halffacet if(fc.is_shalfedge()).
TODO: do we need to draw something if (fc.is_shalfloop()) ?
* Issue(s) solved (if any): fix #7377
> Bug fix draw Nef_3

- BGL/include/CGAL/boost/graph/iterator.h
- STL_Extension/include/CGAL/Object.h
- Surface_mesh/include/CGAL/Surface_mesh/Properties.h
Replace safe-bool idiom with C++11 explicit operator bool.
logical checks:
`0` is `false`
`&this_type_does_not_support_comparisons` is `true`
`e ? true : false`  is the same as `e` 
`b == false` is the same as `!b`
* Affected package(s): BGL, Surface_mesh, STL_ext, 
* Issue(s) solved (if any): Modernisation C++11
* License and copyright ownership: CGAL authors
> Remove use of the safe-bool idiom, replace with explicit operator bool

- Installation/cmake/modules/CGALConfigVersion_binary_header_only.cmake.in
- Installation/cmake/modules/CGALConfig_binary_header_only.cmake.in
Imagine you have cloned CGAL in a local directory named `C:\Users\Laurent Rineau\cgal`, before this patch CMake would fail..., because of the space in the full path. Now it works.
* Affected package(s): CGAL (CMake)
* License and copyright ownership: na
> CMake: allow spaces in git working directory

- Bounding_volumes/examples/Rectangular_p_center_2/rectangular_p_center_2.cpp
- Bounding_volumes/include/CGAL/rectangular_3_center_2.h
- Bounding_volumes/test/Bounding_volumes/issue_2836.cpp
Fix issue in 3center brute-force base case: Don't check `rho_min` if `s == t`.
Make parameters consistent in example
* Affected package(s): Bounding_volumes
* Issue(s) solved (if any): fix #2836
> Bounding volumes fix 3center

- Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.h
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_function.h
PR #7280 highlighted the fact that the mesh refinement `one_step()` loop may crash if the C3T3 had been corrupted during the initialization step.
Now both `refine_mesh()` and the `one_step()` loop have the exact same behaviour.
This crash was first met in the demo :
- open cube.off
- "Tetrahedral mesh generation -> Generate surface mesh"
- keep all default parameters
- OK
> Mesh 3 - fix initialization

- Point_set_3/include/CGAL/Point_set_3/IO/PLY.h
- Stream_support/include/CGAL/IO/PLY/PLY_writer.h
- Surface_mesh/include/CGAL/Surface_mesh/IO/PLY.h
- Surface_mesh/test/Surface_mesh/sm_ply_io.cpp
Hi, I'd like to contribute the writing of PLY property lists.
This allows to directly write multi-texture PLY files with CGAL that can be opened directly in e.g. MeshLab, as well as other use cases that require `property list`.
> PLY: Support writing per-face/vertex property lists

- Triangulation_3/include/CGAL/Regular_triangulation_3.h
Fix a race-condition in `Regular_triangulation_3::insert(begin, end)`.
The race condition is in the batch insertion of a range of points, with or without info.
<details><summary><h3>Details...</h3> (click to open/close)</summary>
In the code of `insert(begin, end)`, after the spatial sorting, the points are inserted using a `tbb::parallel_for`. The insertion object used by the paraller-for inserts a sub-range of points, and maintain a thread-local `hint` of type `Vertex_handle`.
The problem is that one needs to call `hint->point()` **before** anything can be locked, and it is possible that the `hint` vertex is being modified by another thread.
The solution is to store the `Vertex_handle` *and its points* in the thread-local cache.
</details> 
* Affected package(s): Triangulation_3 
* …
> Triangulation_3: fix a race-condition in `Regular_triangulation_3::insert(begin, end)`.

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
Add the ability to read NIFTI `.nii.gz` labeled images, in addition to existing NIFTI `.nii` files.
> Polyhedron demo - read .nii.gz image files

- Polyhedron/demo/Polyhedron/Scene_triangulation_3_item.cpp
Before this PR, the histogram of dihedral angles displayed in the demo was the histogram of all angles of all tetrahedra.
With this PR, only the angles of tetrahedra with a non-zero Subdomain_index will be computed and used to build the histogram.
Note that the tetrahedra with Subdomain_index zero
* are not displayed at all, so it is made consistent
* are not treated (on purpose) by Delaunay refinement, so they usually are of bad quality
> Polyhedron demo - fix dihedral angles histogram

- Barycentric_coordinates_2/doc/Barycentric_coordinates_2/Barycentric_coordinates_2.txt
- Shape_regularization/doc/Shape_regularization/Shape_regularization.txt
Only on a few places the `\boldsymbol` is used in formulas, this has been removed to make it consistent with other packages.
> Remove usage of boldsymbol in formulas

- Shape_detection/doc/Shape_detection/Concepts/RegionType.h
- Shape_detection/examples/Shape_detection/region_growing_with_custom_classes.cpp
- Shape_detection/include/CGAL/Shape_detection/Region_growing/Point_set/Least_squares_circle_fit_region.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/Point_set/Least_squares_cylinder_fit_region.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/Point_set/Least_squares_line_fit_region.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/Point_set/Least_squares_plane_fit_region.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/Point_set/Least_squares_sphere_fit_region.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/Polygon_mesh/Least_squares_plane_fit_region.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/Region_growing.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/Segment_set/Least_squares_line_fit_region.h
Removed first unused parameter from X_region::is_part_of_region().
Small leftover from https://github.com/CGAL/cgal/pull/6702.
> Shape_detection: Removed unused parameter

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Smoothing/mesh_smoothing_impl.h
In CERES_SOLVER mode, a trailling 'l' was causing an invalid syntax, on the Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Smoothing/mesh_smoothing_impl.h file.
* Affected package(s): 
* PolygonMeshProcessing
* What do I need to do here ?
> Trailing 'l' on return statement

- Kernel_d/doc/Kernel_d/Concepts/Kernel--Contained_in_affine_hull_d.h
- Kernel_d/doc/Kernel_d/Concepts/Kernel--Contained_in_linear_hull_d.h
- Kernel_d/doc/Kernel_d/Concepts/Kernel--Contained_in_simplex_d.h
Reported by Michael Kerber: the concept https://doc.cgal.org/latest/Kernel_d/classKernel__d_1_1Contained__in__simplex__d.html documents a return type of Bounded_side but all implementations return bool instead. This is particularly confusing because Bounded_side could have made sense, and you can easily write code that compiles and gives nonsensical results.
* Affected package(s): Kernel_d
> Inconsistent return type in Kernel_d concepts

- SMDS_3/include/CGAL/IO/output_to_vtu.h
Currently the binary vtu file written out by CGAL doesn't contain a closing XML tag for AppendedData. Meshio is unable to parse the vtu file, failing instead with an xml.etree.ElementTree.ParseError. Once the missing tag is added, meshio is able to parse the file correctly.
This bug doesn't affect the ascii vtu, only the binary version.
> Add missing AppendedData closing tag, so vtu binary file contains valid xml

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/angle_and_area_smoothing.h
Add a function documentation
* Issue(s) solved (if any): fix #7487 
* Link to compiled documentation:  [link](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.6-Ic-264/output2/Polygon_mesh_processing/group__PMP__meshing__grp.html#ga6e971b85a933e194198218130ba98c0b) into doc testsuite
> PMP: Document overload of angle_and_area_smoothing()

- Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/point_set_with_planes.h
Remapping of plane_indices in input data to range [0..n-1] as required by method.
* Affected package(s): Polygonal Surface Reconstruction
* Issue(s) solved (if any): fix #7433
> Polygonal Surface Reconstruction: Remapping of plane_indices in input data to range [0..n-1]

- Solver_interface/include/CGAL/OSQP_quadratic_program_traits.h
- Solver_interface/include/CGAL/SCIP_mixed_integer_program_traits.h
`c_int` and `c_float` were renamed. See 'N' in this [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-266/Solver_interface_Examples/TestReport_lrineau_Ubuntu-Latest-CXX11.gz).
See the [PR](https://github.com/osqp/osqp/pull/456) in the QSOP project
* Affected package(s): Solver_interface, Shape_regularization
> Solver_interface: Rename QSOP Types

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp
The verbose version of  `build_triangulation_from_file` is really too verbose and slows down the file reader.
> CGAL Lab - disable verbosity of `.mesh` reader

- Point_set_processing_3/include/CGAL/wlop_simplify_and_regularize_point_set.h
While reading code so that I could answer #7421 I noticed that we should call `vector<T>::reserve()` and `vector<T>swap()`.
> PSP: wlop_simplify() performance improvement

- Alpha_shapes_2/include/CGAL/Alpha_shape_vertex_base_2.h
- Alpha_shapes_2/package_info/Alpha_shapes_2/dependencies
- Convex_hull_3/include/CGAL/Convex_hull_vertex_base_2.h
- Filtered_kernel/include/CGAL/Filtered_kernel.h
- Filtered_kernel/include/CGAL/Lazy_kernel.h
- NewKernel_d/include/CGAL/NewKernel_d/Lazy_cartesian.h
- Number_types/include/CGAL/Lazy_exact_nt.h
- Number_types/include/CGAL/Number_types/internal/Exact_type_selector.h
- Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_builder_traits_2_aux.h
- Stream_support/include/CGAL/IO/io.h
- Surface_mesher/test/Surface_mesher/implicit_surface_mesher_test.cpp
- Triangulation_2/include/CGAL/Regular_triangulation_vertex_base_2.h
- Triangulation_2/include/CGAL/Triangulation_vertex_base_2.h
- Triangulation_3/include/CGAL/Regular_triangulation_vertex_base_3.h
- Triangulation_3/include/CGAL/Triangulation_vertex_base_3.h
- Triangulation_3/test/Triangulation_3/CMakeLists.txt
- Triangulation_3/test/Triangulation_3/test_triangulation_serialization_3.cpp
Before the patch the points were written in double.
> EPECK Triangulation serialization

- Mesh_3/include/CGAL/Mesh_3/Image_plus_weights_to_labeled_function_wrapper.h
The translation `tx, ty, tz` of a labeled image was not taken into account in the weighted image oracle, leading to an output mesh that was shifted to origin, not aligned with input image.
This PR fixes this misalignment.
> Mesh_3 for weighted images - fix translated labeled image case

- Surface_mesh_parameterization/examples/Surface_mesh_parameterization/iterative_authalic_parameterizer.cpp
Remove an  `#include` and a wrong comment in an example.
* Affected package(s): Surface_mesh_parameterization
* Issue(s) solved (if any): fix #7507
> Parameterization: Cleanup of an example

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_image_item.cpp
- Polyhedron/demo/Polyhedron/Scene_image_item.h
Avoid trying to access a non-existing labeled image. That was crashing the demo when running the following steps :
* open a .off file
* Operations -> Tet mesh generation
* seg fault
> Polyhedron demo - fix Mesh_3 dialog initialization

- Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h
For the `less`  of a `std::set` use the `id`  of the halfedge instead of the pointer.
* Affected package(s): Surface_mesh_skeletonization
* Issue(s) solved (if any): fix #7511
> Skeletonization: Make it deterministic

- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Alpha_wrap_3.h
- Polyhedron/demo/Polyhedron/Plugins/Alpha_wrap_3/Alpha_wrap_3_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Alpha_wrap_3/alpha_wrap_3_dialog.ui
* Affected package(s): `Polyhedron`, `Alpha_wrap_3`
> Add stop button for AW3 demo

- Polyhedron/doc/Polyhedron/Concepts/PolyhedronItems_3.h
- Surface_mesh_segmentation/doc/Surface_mesh_segmentation/Surface_Mesh_Segmentation.txt
Hi @sloriot,
Unfortunately, I still don't think the changes in #7523 correctly describe the mesh segmentation algorithm.
I've checked the code, and it looks sound to me, it's doing what intuitively I'd expect it to. :)
Now the description matches that code and intuition.
I hope I'm not coming across as too annoying...
Cheers,
-Nuno
> Improve the manuals for the 3D Polyhedral Surface and Triangulated Surface Mesh Segmentation pkgs

- Classification/include/CGAL/Classification/Image.h
VC2022   with std17 and boost 1_82_0 have a `N`  in the Classification testsuite.
We reported an issue at [`boost/core`](https://github.com/boostorg/core/issues/148) 
The workaround is to make the copy constructor public.
See also the discussion on the [issue  ](https://github.com/boostorg/core/issues/148)in boost/core
> Classification: Workaround for VC++/std17/boost bug

- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/Periodic_2_Delaunay_triangulation_2.h
- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/PackageDescription.txt
- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/Periodic_2_triangulation_2.txt
- Periodic_2_triangulation_2/examples/Periodic_2_triangulation_2/p2t2_find_conflicts.cpp
- Periodic_2_triangulation_2/include/CGAL/Periodic_2_triangulation_2.h
- Periodic_2_triangulation_2/include/CGAL/Periodic_2_triangulation_iterators_2.h
- Periodic_2_triangulation_2/test/Periodic_2_triangulation_2/include/interface_test.h
- Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_3.h
- Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_3/internal/Periodic_3_triangulation_iterators_3.h
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/include/CGAL/_test_cls_periodic_3_iterator.h
- Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/include/CGAL/_test_cls_periodic_3_triangulation_3.h
Unique vertex iterators existed, but nothing for the other simplex types.
Some drive-by factoring / reorganization / cleaning.
* Affected package(s): `Periodic_2_triangulation_2`, `Periodic_3_triangulation_3`
* Feature/Small Feature (if any): N/A (undocumented)
> Add unique simplex iterators for periodic triangulations

- Documentation/doc/CMakeLists.txt
- Documentation/doc/resources/1.8.13/BaseDoxyfile.in
- Documentation/doc/resources/1.9.6/BaseDoxyfile.in
In the past it was possible by means of the option `-DCGAL_EXTRACT_ALL_NO_DETAILED_IF_EMPTY=OFF` with CMake to disable the specific CGAL setting though currently with the 1.8.13 version this didn't work (anymore). Also the setting has been renamed for the 1.9.6 version (and newer) to `NO_ADDITIONAL_DETAILS` this has now been made more flexible as well.
> Possibility to disable special CGAL documentation setting

- Convex_hull_3/include/CGAL/Convex_hull_3/dual/halfspace_intersection_interior_point_3.h
- Intersections_2/test/Intersections_2/test_intersections_2.cpp
- Number_types/include/CGAL/Exact_integer.h
- Number_types/include/CGAL/Exact_rational.h
- Number_types/include/CGAL/Number_types/internal/Exact_type_selector.h
Add missing partial specialization for boost's gmp wrapper.
Fixes https://github.com/CGAL/cgal/issues/7577
> add missing partial specialization

- Installation/CHANGES.md
Tetrahedral remeshing's vertex and cell base classes have had their API modified with the introduction of `SMDS_3` (https://github.com/CGAL/cgal/pull/5693).
The API is likely to be restored to its previous state with 6.0, but it's too late for 5.6.
* License and copyright ownership: no change.
> Add missing breaking change in 5.6 changelog

- Triangulation_3/test/Triangulation_3/CMakeLists.txt
The files `test_simplex_iterator_3.cpp` and `test_segment_simplex_traverser_3.cpp` require C++17. This pull-request fixes the CMake logic so that they are only compiled if the compiler is able to use C++17.
Fix Triangulation_3 test suite on a few compilers:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-I-277/Triangulation_3/TestReport_Christo_MSVC2017-Debug-64bits.gz
Not a blocker in my option.
* License and copyright ownership: n/a
> Triangulation_3: the testsuite of the simplex traverser needs C++17

- Apollonius_graph_2/doc/Apollonius_graph_2/CGAL/Apollonius_graph_2.h
- Apollonius_graph_2/doc/Apollonius_graph_2/CGAL/Apollonius_graph_vertex_base_2.h
Fix the return type.  Document the third template parameter of  `Apollonius_graph_vertex_base_2`.
* Issue(s) solved (if any): fix #7582 and #7579
* Link to compiled documentation: [link](https://cgal.github.io/7619/v0/Apollonius_graph_2/classCGAL_1_1Apollonius__graph__2.html#a6e6e1b20ab5018c96e4b0ed2c0f0ee00) and [here ](https://cgal.github.io/7619/v0/Apollonius_graph_2/classCGAL_1_1Apollonius__graph__vertex__base__2.html#acbabb6d26d4d8938bde5bbd6c6e467eb)for the vertex base.
> Apollonius_graph: Fix return type in the documentation

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/tangential_relaxation.h
> reproject barycenter to avoid boundary shrinking

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orient_polygon_soup.h
> Minor improvements to the documentation of `PMP::orient_polygon_soup()` 

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/locate.h
> Locate.h: Use Face_location / Barycentric_coordinates everywhere

- Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
`cgal_create_release_with_cmake.cmake` was terribly slow (in particular on Windows). In order to fix that:
- call Git only once, to get the Git hash of the repository, and
- Use `$Id: ${f} ${GIT_HASH} $` to replace `$Id$` (all files have the same hash).
That is sufficient to identify without any doubt the version is the original file.
@sloriot: do you agree with those changes?
Cc: @janetournois
> cgal_create_release_with_cmake.cmake: only call Git one

- Kernel_23/include/CGAL/Kernel/function_objects.h
Do not throw an error but return SMALLER
The collinearity check being already done in the predicate it would be more expensive to do it also before calling the predicate
> Be more permissive in Compare_dihedral_angle_3

- Straight_skeleton_2/examples/Straight_skeleton_2/extrude_skeleton.cpp
- Straight_skeleton_2/examples/Straight_skeleton_2/include/CGAL/input_helpers.h
- Straight_skeleton_2/test/Straight_skeleton_2/test_sls_weighted_polygons_with_holes.cpp
Fix warnings in [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-12/Straight_skeleton_2/TestReport_Christo_MSVC-2019-Community-Release.gz) 
* Affected package(s): Straight_line_skeleton
> SLS: Fix warnings

- BGL/include/CGAL/boost/graph/Face_filtered_graph.h
- BGL/test/BGL/test_Face_filtered_graph.cpp
- Stream_support/include/CGAL/IO/Color.h
The current doc says that the selection patch IDs need to be of type faces_size_type, but this requirement doesn't exist in the code.
The doc is generalized, and the actual requirement (the type must be `Hashable`) is added.
TODO:
* Affected package(s): `BGL`, `Stream_support`
* Issue(s) solved (if any): fix #7570
> Generalize documentation of Face_filtered_graph

- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/PackageDescription.txt
- Boolean_set_operations_2/doc/Boolean_set_operations_2/PackageDescription.txt
- Documentation/doc/resources/1.8.13/BaseDoxyfile.in
- Documentation/doc/resources/1.9.6/BaseDoxyfile.in
- Linear_cell_complex/doc/Linear_cell_complex/PackageDescription.txt
- Nef_3/doc/Nef_3/PackageDescription.txt
- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/PackageDescription.txt
- Point_set_3/doc/Point_set_3/PackageDescription.txt
- Polygon/doc/Polygon/PackageDescription.txt
- Polyhedron/doc/Polyhedron/PackageDescription.txt
- Surface_mesh/doc/Surface_mesh/PackageDescription.txt
- Surface_mesh_topology/doc/Surface_mesh_topology/PackageDescription.txt
- Triangulation_2/doc/Triangulation_2/PackageDescription.txt
- Triangulation_3/doc/Triangulation_3/PackageDescription.txt
- Voronoi_diagram_2/doc/Voronoi_diagram_2/PackageDescription.txt
- Weights/doc/Weights/PackageDescription.txt
Getting a better (and consistent) output for the include file to be used with some functions. Normally `#include` are sown as in a typewrite font, but the `#include` in these cases were shown in a code block way.
For e.g Weights/group__PkgWeightsRefUniformRegionWeights.htmlthe w`#include was shown as:
and will now be shown as:
> Better showing of `#include`

- Algebraic_foundations/doc/Algebraic_foundations/Algebraic_foundations.txt
- Algebraic_foundations/doc/Algebraic_foundations/Concepts/FieldNumberType.h
- Algebraic_foundations/doc/Algebraic_foundations/Concepts/RingNumberType.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Arrangement_on_surface_2.txt
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_circle_segment_traits_2.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_conic_traits_2.h
- Barycentric_coordinates_2/doc/Barycentric_coordinates_2/Concepts/BarycentricTraits_2.h
- Bounding_volumes/doc/Bounding_volumes/CGAL/Approximate_min_ellipsoid_d.h
- Bounding_volumes/doc/Bounding_volumes/CGAL/Min_ellipse_2_traits_2.h
- Bounding_volumes/doc/Bounding_volumes/CGAL/Min_sphere_of_spheres_d.h
- Kernel_23/doc/Kernel_23/CGAL/Filtered_predicate.h
- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
- Kernel_23/doc/Kernel_23/CGAL/Vector_2.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_d/doc/Kernel_d/CGAL/Epeck_d.h
- Kernel_d/doc/Kernel_d/Concepts/Kernel--CartesianConstIterator_d.h
- Nef_2/doc/Nef_2/Concepts/ExtendedKernelTraits_2.h
- Nef_3/doc/Nef_3/Nef_3.txt
- Number_types/doc/Number_types/NumberTypeSupport.txt
- Polygon_mesh_processing/doc/Polygon_mesh_processing/Concepts/PMPDistanceTraits.h
- Polynomial/doc/Polynomial/Concepts/PolynomialTraits_d--IsZeroAt.h
- Polynomial/doc/Polynomial/Concepts/PolynomialTraits_d--SignAt.h
- Shape_detection/doc/Shape_detection/Concepts/EfficientRANSACTraits.h
- Spatial_searching/doc/Spatial_searching/CGAL/Fuzzy_sphere.h
- Spatial_searching/doc/Spatial_searching/Concepts/FuzzyQueryItem.h
- Stream_support/doc/Stream_support/IOstream.txt
- Surface_mesh_deformation/doc/Surface_mesh_deformation/Concepts/RawPoint_3.h
- Surface_mesh_skeletonization/doc/Surface_mesh_skeletonization/Concepts/MeanCurvatureSkeletonizationTraits.h
Throw in `%` to avoid links.
* Affected package(s): Arrangements
> Arrangement: small doc fixes

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Snapping/snap.h
don't do collinear test for a triangle to be collapsed
> Fix collapse test in snap

- Nef_2/include/CGAL/Nef_2/PM_checker.h
- Nef_2/include/CGAL/Nef_2/PM_const_decorator.h
- Nef_2/include/CGAL/Nef_2/PM_decorator.h
- Nef_2/include/CGAL/Nef_2/PM_overlayer.h
- Nef_2/include/CGAL/Nef_2/PM_persistent_PL.h
- Nef_2/include/CGAL/Nef_2/PM_point_locator.h
- Nef_2/include/CGAL/Nef_2/Segment_overlay_traits.h
- Nef_2/test/Nef_2/issue7662.cpp
Show issue #7662 
Two fixes were needed: 
1. When merging faces in `simplify()`  at the end of the overlay, isolated vertices were lost.
2. When cloning, we did not iterate over the isolated vertices of the source object.
* Affected package(s): Nef_2
* Issue(s) solved (if any): fix #7662
> Nef_2: Deal with isolated vertices

- Circular_kernel_3/include/CGAL/Circular_kernel_3/internal_functions_on_sphere_3.h
There was a compilation error because the conversion from `Needs_FT<Uncertain<bool>>` to 'bool' requires two user-defined conversions. With an explicit conversion, that compiles and works.
* Affected package(s): Circular_kernel_3
* Issue(s) solved (if any): fix #7666
Note for @sloriot: there seems to be an unfortunate conflict with `master`, but it is quite trivial (because it only affects adjacent lines).
> fix issue #7666: Sphere_3 intersection with interval arithmetic fails on 5.6

- CGAL_ImageIO/include/CGAL/ImageIO_impl.h
Please see https://github.com/CGAL/cgal/issues/7664
> Fixes overflow when reading in large images

- Spatial_searching/include/CGAL/Kd_tree.h
Fixes  #7676
alternative fix to #7685
With this fix, `size()` stays `O(1)`
> Correct size() in case some points were removed

- Mesh_3/include/CGAL/Polyhedral_complex_mesh_domain_3.h
if p is on a face then Is_in_domain will loop infinitely.
Side point: `CGAL_USE_ALL_INTERSECTIONS` I'm not sure it makes sense to keep both implementation. It is even not usable as you need to modify the header to use it.
If we want an exact solution, we should use `Compare_distance()(p, t1, t2)`.
> Fix Is_in_domain potential infinite loop

- Documentation/doc/biblio/cgal_manual.bib
- Heat_method_3/doc/Heat_method_3/Heat_method_3.txt
A mollification function was added to the Heat method implementation in an earlier PR #5037 based on [A Laplacian for Nonmanifold Triangle Meshes](https://www.cs.cmu.edu/~kmcrane/Projects/NonmanifoldLaplace/index.html). 
A citation to this paper was missing. In this PR it has been added to `cgal_manual.bib` and a simple reference to this has been added to the documentation.
* Affected package(s): Heat_method_3
* Link to compiled documentation: [doc](https://cgal.github.io/7688/v0/Manual/index.html)
> Added missing reference to a paper in Heat method 

- Triangulation/doc/Triangulation/PackageDescription.txt
- Triangulation/doc/Triangulation/Triangulation.txt
Newer versions of doxygen are more restrictive (and following the rules) in respect to the end comment of a HTML type of comment, i.e. ``, so parts of the paragraphs were missing (Triangulation/index.html and Triangulation/group___pkg_triangulations_ref.html)
See also https://www.w3.org/TR/2006/REC-xml11-20060816/#sec-comments
> Incorrect closing HTML comment

- Triangulation/doc/Triangulation/Triangulation.txt
Remove gray background and get some indentation
(Note this proposed pull request needs the proposed pull request #7700)
> issue #7701 Appearance of "Set of Faces" in documentation.

- Documentation/doc/Documentation/Tutorials/Tutorial_hello_world.txt
Fix a typo in Tutorial_hello_world.txt:
https://github.com/CGAL/cgal/blob/8718201f3e8d0043d66dd5ba16602c4b8dfb022a/Documentation/doc/Documentation/Tutorials/Tutorial_hello_world.txt#L74-L76
`extract` -> `exact`
> fix a typo in Tutorial_hello_world.txt

- Polyhedron/demo/Polyhedron/Plugins/Isosurfacing_3/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Isosurfacing_3/Isosurface_3_plugin.cpp
_Added a dual contouring operation in the demo._
* Affected package(s): Isosurfacing_3 (https://github.com/CGAL/cgal/pull/6849)
> Polyhedron demo : dual contouring operation from isosurfacing_3 package

- Combinatorial_map/include/CGAL/Combinatorial_map_storages_with_index.h
- Linear_cell_complex/include/CGAL/CMap_linear_cell_complex_storages_with_index.h
Add 2 missing methods in dart_range in CMap and LCC_cmap with index.
Without these two methods, we cannot use a dart_range like a compact container with index which is a bug.
* Affected package(s): CMap and LCC
> Add missing functions capacity and upper bound in dart_range for cmap and lcc with index

- Stream_support/doc/Stream_support/File_formats/Supported_file_formats.txt
Correcting the link to the 3mf specification
(see: Stream_support/_i_o_stream_supported_file_formats.html)
> Link to the 3mf specification

- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Arrangement_on_surface_2.txt
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_algebraic_segment_traits_2.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_batched_point_location.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_conic_traits_2.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_point_location_result.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_polycurve_traits_2.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_vertical_decomposition_2.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arrangement_2.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arrangement_on_surface_2.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/CORE_algebraic_number_traits.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Concepts/ArrTraits--Intersect_2.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Concepts/ArrTraits--MakeXMonotone_2.h
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/PackageDescription.txt
- Arrangement_on_surface_2/examples/Arrangement_on_surface_2/batched_point_location.cpp
Fixes documentation issues in the Aos_2 package
* Affected package(s):  Arrangement_on_surface_2
* Issue(s) solved (if any): fix #7693 and #7659
* Link to compiled documentation (obligatory for small feature)
> Aos_2: doc fixes

- Straight_skeleton_extrusion_2/include/CGAL/extrude_skeleton.h
A faced with an compilation error while using CGAL::extrude_skeleton() with float kernel. The error was caused by std::max() function getting arguments of different types. My improvement should fix this problem.
* Affected package(s): Straight Skeleton
> Added type cast to preprocess_weights() to avoid compilation error

- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_widget.ui
- Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp
- Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.h
- Polyhedron/demo/Polyhedron/Scene_image_item.cpp
- Polyhedron/demo/Polyhedron/Scene_triangulation_3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_triangulation_3_item.h
- Polyhedron/demo/Polyhedron/resources/no_interpolation_shader.frag
- Polyhedron/demo/Polyhedron/resources/no_interpolation_shader.geom
- Polyhedron/demo/Polyhedron/resources/no_interpolation_shader.vert
- Polyhedron/demo/Polyhedron/resources/shader_c3t3.frag
- Polyhedron/demo/Polyhedron/resources/shader_c3t3.vert
- Polyhedron/demo/Polyhedron/resources/shader_c3t3_edges.frag
- Polyhedron/demo/Polyhedron/resources/shader_c3t3_edges.vert
The clip box plugin only set shader uniforms. We can add these uniforms in shaders where they were not added.
Tasks :
> Polyhedron demo : Add clip box plugin support for more items

- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Point_2.h
- Mesh_2/include/CGAL/IO/File_poly.h
- Mesh_3/examples/Mesh_3/CMakeLists.txt
- Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
- Point_set_processing_3/include/CGAL/IO/read_xyz_points.h
- Stream_support/include/CGAL/IO/PLY/PLY_reader.h
- Stream_support/include/CGAL/IO/STL/STL_reader.h
- Stream_support/include/CGAL/IO/VTK.h
- Triangulation_2/include/CGAL/Constrained_triangulation_2.h
- Triangulation_2/include/CGAL/Triangulation_2/internal/Polyline_constraint_hierarchy_2.h
The calls without the `IO::` namespace are deprecated.
Fixes https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-I-60/Mesh_3/TestReport_lrineau_Ubuntu-Latest-NO_DEPRECATED_CODE.gz and a lot more.
* Affected package(s): CGAL
> fix : iformat/oformat are in CGAL::IO

- Intersections_3/include/CGAL/Intersections_3/internal/Plane_3_Triangle_3_intersection.h
CGAL-5.5.x latest test results are completely broken.
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.5.4-I-166.shtml
That is not due to any code change (there was none since the previous testsuite for 5.5.x). The error are due to Boost 1.84. Probably something change in the includes of Boost. The error is about `boost::prior`.  The header `<boost/next_prior.hpp>` must be included.
> Add missing header

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
The compiler complains about potential out of bound access of the array
> Fix warning

- Documentation/doc/Documentation/windows.txt
- Documentation/doc/resources/1.8.13/BaseDoxyfile.in
- Documentation/doc/resources/1.9.6/BaseDoxyfile.in
All the dlls are now included in the main zip archive, so let's remove mentions of "common dlls" archive.
* Affected package(s): Doc
* Issue(s) solved (if any): fix #7721
> Doc of Windows precompiled demos - remove "common dlls"

- STL_Extension/include/CGAL/Base_with_time_stamp.h
Remove the copy constructor of `Base_with_time_stamp`. 
Otherwise we have 'N' in the [Triangulation_2 testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.5.4-I-169.shtml#Triangulation_2) for CGAL 5.5.
Note that the copy constructor is not in 5.6 and master. 
Note that this only concerns VC++.
* Affected package(s): STL_extension
> STL_extension: Fix Base_with_time_stamp

- Polygonal_surface_reconstruction/doc/Polygonal_surface_reconstruction/dependencies
- Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction.h
- Polygonal_surface_reconstruction/include/CGAL/Polygonal_surface_reconstruction/internal/point_set_with_planes.h
- Polygonal_surface_reconstruction/package_info/Polygonal_surface_reconstruction/dependencies
Changed the output from unoriented polygon soup to polygon mesh
* Issue(s) solved (if any): fix #7647, #7096
> Converting unoriented polygon soup to polygon mesh

- Classification/include/CGAL/Classification/ETHZ/internal/random-forest/common-libraries.hpp
CGAL requires boost 1.66 or higher since CGAL-5.6.
> No need for workaround for boost before version 1.47

- Point_set_processing_3/include/CGAL/mst_orient_normals.h
CGAL as of version 5.6 requires Boost 1.66 or higher so the warning is not valid anymore
> issue #7765 Problem with Boost 1.54 and a non reachable ticket

- Apollonius_graph_2/test/Apollonius_graph_2/include/test.h
Several test programs write and read back to a file with the same name, which may lead to errors when they are executed simultaneously.  This PR makes the  filenames unique.
* Affected package(s): Apollonius_graph
> Apollonius_graph: Make file names unique

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
- Tetrahedral_remeshing/include/CGAL/tetrahedral_remeshing.h
In the demo, tetrahedral remeshing is called directly on the C3t3. This PR fixes the default `cell_selector` when remeshing is called on a C3t3.
> Tetrahedral remeshing of a C3t3 - fix default cell selector

- Triangulation_3/include/CGAL/Regular_triangulation_3.h
The sanity value was not used so let's set it to 3.
> fix out-of-bound warnings

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair_self_intersections.h
Add a check before calling `remove_degerenate_faces()` to avoid removing patch border edges
> Prevent the removal of fixed boundary edges

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Tetrahedra_filtering_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_triangulation_3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_triangulation_3_item.h
- Polyhedron/demo/Polyhedron/resources/shader_c3t3.frag
- Polyhedron/demo/Polyhedron/resources/shader_c3t3_edges.frag
- STL_Extension/include/CGAL/Handle.h
When a triangulation 3 has many subdomains (more than 24), some will not be shown.
Changes done : 
Possible amelioration :
> Mesh 3: Fix demo tetrahedral filtering with a tetrahedral mesh having many subdomains

- Triangulation_2/doc/Triangulation_2/Triangulation_2.txt
Add  () to function names in the User Manual
* Affected package(s):  Triangulation_2
> Triangulation_2:   Add  () to function names in the User Manual

- Polyhedron/demo/Polyhedron/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/IO/VTK_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_item_with_properties.cpp
- Polyhedron/demo/Polyhedron/TextRenderer.cpp
- Stream_support/include/CGAL/IO/polygon_soup_io.h
- Three/include/CGAL/Three/Scene_item_with_properties.h
CGAL Lab: fix reading of VTK files
- fix a memory leak
- allow to read a polygon soup, in addition to surface meshes
- fix reading of vtp files
* Affected package(s): CGAL Lab
* License and copyright ownership: unchanged, maintenance by GF
> CGAL Lab: fix reading of VTK files

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
- Polyhedron/demo/Polyhedron/Scene_image_item.cpp
- Polyhedron/demo/Polyhedron/Scene_triangulation_3_item.cpp
- Polyhedron/demo/Polyhedron/Scene_triangulation_3_item.h
Fixes issue #7799 : Surface_patch_index are not colored anymore.
Now, Surface_patch_index are colored by default.
But when meshing from labelled images, the subdomain colors are used.
* Affected package(s): Polyhedral demo
* Issue(s) solved (if any): fix #7799 
> Polyhedron demo - Use subdomain's color only when meshing from labeled images

- Tetrahedral_remeshing/doc/Tetrahedral_remeshing/Tetrahedral_remeshing.txt
- Tetrahedral_remeshing/examples/Tetrahedral_remeshing/tetrahedral_remeshing_example.cpp
- Tetrahedral_remeshing/examples/Tetrahedral_remeshing/tetrahedral_remeshing_generate_input.h
- Tetrahedral_remeshing/examples/Tetrahedral_remeshing/tetrahedral_remeshing_of_one_subdomain.cpp
Improve documentation of `CGAL::tetrahedral_isotropic_remeshing()` about how to deal with `Subdomain_index` 0.
See [example 1](https://cgal.github.io/7801/v0/Tetrahedral_remeshing/index.html#ssecEx1) and [example 2](https://cgal.github.io/7801/v0/Tetrahedral_remeshing/index.html#ssecEx2) in the user manual.
* Issue(s) solved (if any): fix #7720
> Tetrahedral_remeshing - Doc improvements

- Cartesian_kernel/include/CGAL/predicates/kernel_ftC3.h
Make `collinear_3()` exploit uncertainty to make it faster. See discussion in PR #5207  
> Kernel_23: Exploit Uncertain in collinear_3()

- Mesh_3/test/Mesh_3/test_meshing_without_features_determinism.cpp
Tests of Mesh_3 in the daily testsuite (too) often end with timeouts, because of the test `test_meshing_without_features_determinism`. This happens on many different platforms.
This PR reduces the target dihedral angle from 10 degrees to 9 degrees for `CGAL::perturb_mesh_3()` to fit in the testsuite timeout.
My experiments showed that the perturber always succeeds to get to 10 degrees, but it may be long and go beyond the timeout, in particular in Debug mode. This test is not about the perturber itself, but about determinism, so it must not be considered as a regression.
* Affected package(s): Mesh_3 tests
> Mesh_3 - avoid a timeout in the testsuite

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
The internal C3T3 vertices may have badly defined `in_dimension` when the input triangulation/c3t3 has inconsistencies.
This may happen when a vertex is inserted by Mesh_3 on a surface, hence is tagged with dimension 2,
but has not incident facet in the restricted Delaunay.
This PR fixes the consistency of dimensions attached to vertices before starting tetrahedral remeshing.
> Tetrahedral remeshing - fix internal C3t3

- SMDS_3/test/SMDS_3/test_c3t3_io.cpp
Some test platforms are read-only, and SMDS_3 tests were writing output files on the test platforms. This PR avoids writing output files.
* Affected package(s): SMDS_3
> SMDS_3 - avoid output files for testing

- Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
When "Show cells not in complex" is enabled, turning the c3t3's visibility off will also set the cell not in complex visibility off.
Other upgrades : 
* Affected package(s): Mesh_3 : Polyhedron_demo
* Issue(s) solved (if any): fix #6187
> Polyhedron demo : Fix bug in "Show cells not in complex" of a C3t3

- Installation/CHANGES.md
> PMP - isotropic remeshing with sizing to CHANGES.md

- Scale_space_reconstruction_3/doc/Scale_space_reconstruction_3/dependencies
- Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Jet_smoother.h
- Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Weighted_PCA_smoother.h
Doc fixes.
I also noticed that the [concepts](https://doc.cgal.org/latest/Scale_space_reconstruction_3/group__PkgScaleSpaceReconstruction3Concepts.html) are in a namespace. Do we want to change that? What names? 
* Affected package(s): Scale_space_reconstruction
> Scale_space_reconstruction: Doc Fixes

- Installation/cmake/modules/CGAL_Macros.cmake
Fix incorrect use of `string(REGEX REPLACE...)`, that would lead to a CMake error if the CGAL source full path contains `++` (like in `dev/C++/`).
@gdamiand: it fixes #7866.
* Issue(s) solved (if any): fix #7866
> CMake: fix incorrect use of string(REGEX REPLACE...)

- Scripts/developer_scripts/add_toc_to_github_wiki_page.py
Improve the developer script `add_toc_to_github_wiki_page.py` that add a table-of-content (TOC) to a wiki page.
- reformat using `black`
- add an option `--max-level`
- quote anchors (for accentuated character)
- fix linter errors
* License and copyright ownership: unchanged (I am not sure what are licenses for Scripts/)
> Improve add_toc_to_github_wiki_page.py

- Polygon_mesh_processing/examples/Polygon_mesh_processing/compute_normals_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/compute_normals_example_Polyhedron.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/corefinement_LCC.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/extrude.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/hole_filling_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/hole_filling_example_LCC.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/interpolated_corrected_curvatures_PH.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/interpolated_corrected_curvatures_SM.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/interpolated_corrected_curvatures_vertex.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/orient_polygon_soup_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/point_inside_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/polyhedral_envelope.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/polyhedral_envelope_mesh_containment.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/random_perturbation_SM_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/refine_fair_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/remesh_almost_planar_patches.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/remesh_planar_patches.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/stitch_borders_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/stitch_borders_example_OM.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/triangulate_faces_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/triangulate_faces_split_visitor_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/volume_connected_components.cpp
Let's typedef it `Mesh`, whether it is a Surface_mesh, LCC, OpenMesh, Polyhedon_3
* Affected package(s):  PMP
> PMP Examples: Unify type names

- Poisson_surface_reconstruction_3/include/CGAL/Reconstruction_triangulation_3.h
- Triangulation_3/include/CGAL/Robust_weighted_circumcenter_filtered_traits_3.h
The algorithm performed exact locate all the time.  Activating structural filtering makes it faster.
* Affected package(s): Poisson Surface Reconstruction
> Poisson Surface Reconstruction: Enable Structural Filtering

- Polyhedron/demo/Polyhedron/CGAL_double_edit.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
With Qt6, scientific notation was used by default. This PR changes it to normal notation for doubles.
~~Note that I had to remove the call to `QDoubleValidator::fixup(input);` to make it work, otherwise I could not add a "." in the number I wanted to enter. I did not find any satisfying explanation for that, but it works...~~
> Polyhedron demo - fix `DoubleEdit`

- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_function.h
This PR changes the log that is displayed in the "Console" box of the demo after Mesh_3.
Now, only the criteria that are used (not the ones set to 0 or unchecked in the dialog) are displayed, to improve readability.
> Polyhedron demo - improve the Mesh_3 log

- TDS_3/include/CGAL/Triangulation_utils_3.h
Fixes warnings for example [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-121/Mesh_3/TestReport_lrineau_Fedora-rawhide-Release.gz)
> Prevent out-of-bound warnings

- Polygon_mesh_processing/test/Polygon_mesh_processing/triangulate_hole_Polyhedron_3_no_delaunay_test.cpp
As test programs may be executed in parallel we have to write in files with different names,
> PMP: Write into different files to avoid concurrent writing

- Nef_S2/include/CGAL/Nef_S2/Sphere_segment.h
Maybe we get rid of this [warning](https://cgal.geometryfactory.com/CGAL/testsuite/results-6.0-Ic-106.shtml#Nef_3)
* Affected package(s): Nef_S2
> Nef_S2: Move code to initializer list

- Polygon_mesh_processing/doc/Polygon_mesh_processing/Concepts/PMPSizingField.h
- Polygon_mesh_processing/examples/Polygon_mesh_processing/CMakeLists.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_with_custom_sizing_example.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/Adaptive_sizing_field.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/Uniform_sizing_field.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Sizing_field_base.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/tangential_relaxation.h
Add a sizing interpolating the size along the y-axis and also improve the concept.
> Isotropic remeshing: add example with custom dummy sizing

- Shape_regularization/include/CGAL/Shape_regularization/regularize_segments.h
Documented dependency to OSQP when default solver is used for regularize_segments.
* Affected package(s): Shape Regularization
* Issue(s) solved (if any): fix #7894
> Shape Regularization: Documented missing dependency to OSQP when default solver is used

- Polyhedron/doc/Polyhedron/CGAL/IO/Polyhedron_iostream.h
- Stream_support/doc/Stream_support/File_formats/Supported_file_formats.txt
- Stream_support/doc/Stream_support/IOstream.txt
- Stream_support/doc/Stream_support/PackageDescription.txt
- Stream_support/include/CGAL/IO/VTK.h
Add `read_VTK()` so that we can also read non-xml   *.vtk files.
* Affected package(s): Stream_support 
* Link to compiled documentation:  [overview](https://cgal.github.io/7826/v0/Stream_support/IOStreamSupportedFileFormats.html#IOStreamVTK)   and [function](https://cgal.github.io/7826/v0/Stream_support/group__PkgStreamSupportIoFuncsVTK.html#gaad7f1c5c10e8700a4a6de88294c5a620)
> Stream_support: Add read_VTK() 

- Polygon_mesh_processing/doc/Polygon_mesh_processing/examples.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/CMakeLists.txt
- Polygon_mesh_processing/examples/Polygon_mesh_processing/sample_example.cpp
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Point_set_from_sampling_plugin.cpp
Add a plugin that samples meshes and polygon soups
> Polyhedron Demo: Add sampling plugin

- Kernel_23/test/Kernel_23/include/CGAL/_test_io.h
Write and read back in a  `std::stringstream` to avoid simultaneous IO on the same file name.
Error seen in this [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-124/Circular_kernel_2/TestReport_gimeno_ArchLinux-clang-CXX17-Release.gz).
* Affected package(s):  Kernel_23, Circular_kernel_2
> Kernel_23: Deal with concurrent executions and IO

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/peel_slivers.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
This PR moves the "sliver peeling" function to its own internal header file.
> Tetrahedral remeshing - move sliver peeling to its own header file

- Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h
When the criterion `edge_min_size` is set, the graph of features is likely to be invalid or at least inconsistent with the input graph.
Checking its topology does not make any sense and could lead to hanging when trying to compute polyline feature lengths (because it's trying to walk on different curves, jumping from one to the other, etc).
This PR disables the check-features-after-protect step when `edge_min_size` is used, since we anyway do not expect the feature graph to be exactly matching the one of the input.
> Mesh_3 - `edge_min_size` may cause hanging

- Kernel_23/test/Kernel_23/test_approximate_dihedral_angle_3.cpp
The variable is not used as shadowed by the loop variable and the `maybe-unused` requires c++17
> Remove unused variable

- Documentation/doc/resources/1.10.0/header_package.html
The PR #7946 was withdraw because the `$cookie` was not necessary anymore in the `header...`  files as it was part of the of the `$treeview`. In `header_package.html` the `$treeview` has been disables and as such the `cookie.js` is not added/ Adding the `cookie.js` explicitly.
The effect was that there was a divider between the treeview and the textual documentation but it was on the far left (and thus invisible), it could be moved but after a refresh it was "gone" again.
> Treeview missing due to missing setting in `header_package.html`

- CGAL_ImageIO/include/CGAL/ImageIO/analyze_impl.h
- CGAL_ImageIO/include/CGAL/ImageIO/gis_impl.h
- CGAL_ImageIO/include/CGAL/ImageIO/inr_impl.h
- CGAL_ImageIO/include/CGAL/ImageIO/mincio_impl.h
- CGAL_ImageIO/include/CGAL/ImageIO/pnm_impl.h
`sprintf()` is deprecated so we replace it with `snprintf()`.
* Affected package(s): CGAL_Image_IO
* Issue(s) solved (if any): fix warnings in the testsuite for example for [Tetrahedral Remeshing](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-143/Tetrahedral_remeshing/TestReport_Taylor_macOS-Apple_M2-boost_backend-arm64.gz)
> Image_IO: sprintf -> snprintf

- Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_constrained_triangulation_2.h
- Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_regular_triangulation_2.h
- Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_triangulation_short_2.h
- Triangulation_3/test/Triangulation_3/include/CGAL/_test_cls_delaunay_3.h
Change file names to avoid interaction between test cases.
@MaelRL I noticed that the RT test does not read back. 
* Issue(s) solved (if any): fix [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-141/Triangulation_2/TestReport_gimeno_ArchLinux-clang.gz)
> Triangulation_2:  Make IO save by changing file names

- SMDS_3/include/CGAL/SMDS_3/tet_soup_to_c3t3.h
With a `.mesh` containing `Triangles` in a comment, like that one:
```
MeshVersionFormatted 1
Dimension
3
Vertices
121
-10.0402  -10.0402  -10.0402    0
-10  10  10    0
10  10  10    0
[...]
Triangles
609
98     76     65    0
98     81     76    0
65     81     98    0
[...]
Tetrahedra
244
81     65     76     98  0
28      1     37     34  0
69     25     70     94  0
[...]
End
```
then the code failed. It read `Triangles` in the second comment as the beginning of the triangles section.
This PR use `std::getline()` to read the comments and the keywords:
- `Vertices`
- `Triangles`
- `Tetrahedra`
* Affected package(s): SMDS_3
> Mesh_3/SMDS_3: Fix reading of .mesh files

- Kernel_d/include/CGAL/Kernel_d/Linear_algebraHd_impl.h
- Kernel_d/test/Kernel_d/Linear_algebra-test.cpp
- Kernel_d/test/Kernel_d/interface-test.cpp
- Kernel_d/test/Kernel_d/intersection-test.cpp
In case neither GMP or Leda are installed the Kernel_d testsuite shows a bug, namely a division using `/`.
We replace it with `integral_division`. 
There is more to do, as there are some testcases which define double as RT.   This leads to runtime errors
and may gloss over more errors for a number type without divisions.
* Affected package(s):  Kernel_d
> Kernel_d: Use integral_division()

- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/interpolated_corrected_curvatures.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/measure.h
- Polyhedron/demo/Polyhedron/Plugins/Display/Display_property_plugin.cpp
Remaining issue #7859 to be handled before 6.0 in order not to block the integration of the small feature branch on which two other PRs depend on.
Todos (taken from the issue)
> Interpolated Curvature remaining TODOs

- Polyhedron/demo/Polyhedron/MainWindow.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/GOCAD_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/Nef_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/OFF_to_nef_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/Polylines_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/VTK_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/IO/WKT_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_rib_exporter_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Repair_polyhedron_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
- Polyhedron/demo/Polyhedron/Plugins/PMP/Smoothing_plugin.cpp
A few bug fixes within #6690.
* License and copyright ownership: -
> Fix some demo bugs

- Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2.h
- Segment_Delaunay_graph_2/test/Segment_Delaunay_graph_2/issue7972.cpp
Using the exact construction kernel reveals a bug. A function returns a reference to a local variable. 
* Affected package(s): Segment_delaunay_graph_2
* Issue(s) solved (if any): fix #7972
> Segment_delaunay_graph_2:  Fix Issue 7972

- Apollonius_graph_2/include/CGAL/Parabola_segment_2.h
- Segment_Delaunay_graph_2/examples/Segment_Delaunay_graph_2/CMakeLists.txt
- Segment_Delaunay_graph_2/examples/Segment_Delaunay_graph_2/sdg-advanced-draw.cpp
Issue #7973 mentions improvements to do on the undocumented class `Parabola_segment_2`.  To get started we make it a struct. Mael will add an example with some better drawing implementation.
* Affected package(s):  Segment_Delaunay_graph_2
> Ease drawing of SDG duals

- .github/test.sh
- .github/workflows/build_doc.yml
Optimized GitHub Actions builds by replacing `-j2` with `-j$(nproc)`
* Issue(s) solved (if any): fix #7988
> Update build scripts to use the number of available processors for parallel compilation

- Number_types/include/CGAL/Quotient.h
Fixes issue mentioned in https://github.com/CGAL/cgal/pull/7927
`sentry` also eats end-of-line and arrangement formatter has a skip-until-eol after reading vertex coordinates
We decide to not allow whitespaces between `num` `/` `dum`
> Do not skip whitespace while reading quotient

- Point_set_3/test/Point_set_3/CMakeLists.txt
- Point_set_3/test/Point_set_3/issue7996.cpp
- Stream_support/include/CGAL/IO/PLY/PLY_writer.h
In the [ply file format](https://paulbourke.net/dataformats/ply/) one specifies in the header the type of properties. For a color one typically writes `property uchar red`, and then later writes a number between 0 and 255. We wrote a single char which is a mistake and was reported in issue #7996.   Note that even the CGAL ply reader cannot read it. And there is a [comment](https://github.com/CGAL/cgal/blob/96f698ca09b61b6ca7587d43b022a0db43519699/Stream_support/include/CGAL/IO/PLY/PLY_reader.h#L157) in the reader which explains that it reads an integer string and not a single char.
* Issue(s) solved (if any): fix #7996
* License and copyright ownership: unchanged.
> Point_set_3: property uchar refers to the range 0..255 not the char type

- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/CGAL/Periodic_2_triangulation_2.h
- Point_set_3/include/CGAL/Point_set_3.h
- Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h
- TDS_3/doc/TDS_3/Concepts/TriangulationDataStructure_3.h
- Triangulation/doc/Triangulation/CGAL/Triangulation_data_structure.h
- Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_plus_2.h
When running xmllint over the documentation output we get a number of waning's like:
```
save_Periodic_2_triangulation_2/class_c_g_a_l_1_1_periodic__2__triangulation__2.html:1420: parser error : Opening and ending tag mismatch: dd line 1420 and div
"This is an advanced function.">is_triangulation_in_1_sheet()</a></code>  </div>
^
```
they are a consequence of the fact that a a command is not properly ended in this case we have a `\pre` command and its documentation states:
> The `\pre` command ends when a blank line or some other sectioning command is encountered.
and in this case the command is followed by the `\cgalAdvancedEnd` command that does not properly end the `\pre` command. The same is valid in the other cases.
> Warnings in documentation when running xmllint

- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
On the page Kernel_23/group__bisector__grp.html we see for `bisector` with the `Point_3` type arguments in the precondition:
```
‘p != q’
```
instead of
```
p != q
```
due to the fact that there is not a backtick but a single quote as closing part
> Incorrect layout bisector precondition

- Documentation/doc/Documentation/Doxyfile.in
There is a space before the `=`-sign and in the newer version of doxygen this is not accepted anymore. (probably an unknown side effect).
> Space before equal sign in ALIASES

- Point_set_3/include/CGAL/Point_set_3/IO/LAS.h
- Point_set_3/include/CGAL/Point_set_3/IO/OFF.h
- Point_set_3/include/CGAL/Point_set_3/IO/PLY.h
- Point_set_3/include/CGAL/Point_set_3/IO/XYZ.h
- Point_set_processing_3/doc/Point_set_processing_3/PackageDescription.txt
- Point_set_processing_3/doc/Point_set_processing_3/dependencies
- Point_set_processing_3/examples/Point_set_processing_3/read_write_xyz_point_set_example.cpp
- Point_set_processing_3/include/CGAL/IO/read_las_points.h
- Point_set_processing_3/include/CGAL/IO/read_off_points.h
- Point_set_processing_3/include/CGAL/IO/read_ply_points.h
- Point_set_processing_3/include/CGAL/IO/read_xyz_points.h
- Point_set_processing_3/include/CGAL/IO/write_las_points.h
- Point_set_processing_3/include/CGAL/IO/write_off_points.h
- Point_set_processing_3/include/CGAL/IO/write_ply_points.h
- Point_set_processing_3/include/CGAL/IO/write_xyz_points.h
As these functions are deprecated since CGAL 5.3 we remove them from the documentation.
I am also wondering why we have no `CGAL::IO::read_XYZ()` [here](https://doc.cgal.org/latest/Point_set_processing_3/group__PkgPointSetProcessing3IOXyz.html), especially as we have an overload for `Point_set_3` [here](https://doc.cgal.org/latest/Point_set_3/group__PkgPointSet3IOXYZ.html).
* Affected package(s): Point_set_processing_3
> Point Set Processing: Remove documentation of deprecated functions

- Polyhedron/demo/Polyhedron/triangulate_primitive.h
Fixes the rendering for degenerate polygons. Bug was introduced by https://github.com/CGAL/cgal/pull/7898
* Affected package(s): Polyhedron/demo
> CGAL Lab: Fix rendering for degenerate polygons

- Installation/CHANGES.md
- Triangulation/doc/Triangulation/CGAL/Delaunay_triangulation.h
- Triangulation/doc/Triangulation/CGAL/Triangulation.h
- Triangulation/include/CGAL/Delaunay_triangulation.h
- Triangulation/include/CGAL/Triangulation.h
In Triangulation and Delaunay_triangulation (but not Regular_triangulation with equal weights), if we insert a point and locate notices that there is already a vertex for this point, we call `set_point` to set this point again. I don't understand why we do that. In most cases it should be useless but harmless. To notice a difference, we would need a `Point_d` type for which 2 objects may represent the same position but differ in some way (probably include extra data like a color). But even in that case, it isn't obvious to me that using the color of the last copy of this point that gets inserted is better than the color of the first copy. If someone was using this mechanism to store the index of points, having a vertex that changes what point it represents in the middle of the …
> Don't set the point again when reinserting the same point

- AABB_tree/include/CGAL/AABB_tree/internal/AABB_traversal_traits.h
- Arrangement_on_surface_2/demo/Arrangement_on_surface_2/Utils/IntersectCurves.cpp
- Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/gfx/Curve_renderer_internals.h
Add a default and copy constructor to fix [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-169/Arrangement_on_surface_2_Demo/TestReport_Taylor_macOS-Apple_M2-boost_backend-arm64.gz)
Initialize with `std::nullopt` to try to fix [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-169/Tetrahedral_remeshing/TestReport_lrineau_Debian-stable-Release.gz)
Also include a on-deprecated boost header.
* Affected package(s): AABB_tree, Arrangement_on_surface_2
> Aos_2, AABB_tree: Address warnings

- Triangulation/include/CGAL/Triangulation.h
On my system (x86_64, gcc), to compute `(i+1)%m`, the version with `if` is consistently faster than the version with a division (`%`). For instance, with `benchmark/Triangulation/delaunay.cpp`
master
> Delaunay triangulation of 25000000 points in dim 2:
>  Done in 29.5709 seconds.
PR
>   Done in 28.6321 seconds.
ISTR reading a comparison of all the variants that were tried in Triangulation_23, for the same purpose of cycling through the neighbors of a cell, but I cannot find it anymore. Whether the dimension is a constant known at compile-time may play a role here.
The other 2 changes are less important but don't really deserve their own PR.
* the compiler needs to know that i is nonnegative to replace `i%2` with `i&1`, so help it
* `is_infinite(Face)` appears quite high when profiling my …
> Use 'if' rather than %

- Installation/CHANGES.md
- Triangulation/doc/Triangulation/CGAL/Triangulation_ds_full_cell.h
- Triangulation/include/CGAL/TDS_full_cell_mirror_storage_policy.h
What dimensions do we want to support in the Triangulation package? The optional policy to store mirror indexes in the full cells of the TDS currently uses an `int` to store an index. Since indexes are bounded by the dimension (+1), that seems like a waste of memory. Using `uint8_t` is sufficient up to dimension ~250, reduces the memory overhead of this policy significantly, and improves performance a bit. Is it ok to assume that the dimension fits in 8 bits (with a bit of margin), or do I need to use some meta-programming so it uses different types depending on the dimension?
For a dynamic dimension, having a whole vector for the mirror indexes remains a large overhead even if it is a `vector<char>`. Since we only need to store ~ d numbers of log(d) bits, a single 64-bit integer should …
> Store index/dimension in 8 bits

- Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h
This PR completes PR #7863
The use of `curve_segment_length()` may be invalid when `edge_min_size` criterion is used, and hence the graph of features may be invalid.
With this PR, we make sure that the invalid-feature-graph-protected version of `curve_segment_length()` is used everywhere consistently.
> Mesh_3 with `edge_min_size` - make uses of `curve_segment_length()` consistent

- Mesh_3/include/CGAL/perturb_mesh_3.h
Fix `CGAL::perturb_mesh_3()` documentation, that had been mixed with the doc of the exuder since 5.6.
> Mesh_3 - fix perturber doc

- Polyhedron/demo/Polyhedron/File_loader_dialog.h
make sure pressing enter always pick the proposed loader by default (the behavior seemed to be platform specific, now it should be uniform).
> Set focus to the ok button

- NewKernel_d/include/CGAL/NewKernel_d/Cartesian_static_filters.h
NewKernel_d already had wrappers so it could call some 2d static filters. I blindly copy-pasted so it could also handle 3d.
IIRC, those static filters were just a proof of concept and could do with more work (I don't think they are used by Epeck_d for instance), but I don't have a lot of time for it, and this simple patch (minimal effort) immediately gave a nice speed-up when building a Delaunay triangulation with `Epick_d<Dimension_tag<3>>` (enough that it isn't worth having a special case for 3d using Delaunay_triangulation_3 in my application). I might add the weighted versions in another PR later...
The main issue with all those filters is that it isn't clear if the testsuite really tests all the layers, but for now it should be ok since Epeck_d does not use static filters.
* Affected …
> Call 3d static filters from NewKernel_d

- Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
- Kernel_23/include/CGAL/Kernel/global_functions_2.h
- Kernel_23/include/CGAL/Kernel/global_functions_3.h
- Kernel_23/include/CGAL/Kernel/global_functions_internal_2.h
- Kernel_23/include/CGAL/Kernel/global_functions_internal_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_segment_2.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_segment_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_vector_2.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_fct_vector_3.h
Add a free function.
TODO:
* Link to compiled documentation: [`CGAL::squared_length()`](https://cgal.github.io/8008/v0/Kernel_23/group__squared__length__grp.html#ga64edbde8622fec7f5af6338018d3d56f)
> Kernel_23:  Add function squared_length()

- Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_constrained_triangulation_2.h
- Triangulation_3/test/Triangulation_3/include/CGAL/_test_cls_delaunay_3.h
Several . cpp use the same .h which write in a stream with the same name, which leads to errors when executed in parallel by ctest.
See these testsuites of [Triangulation_3](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-6.0-Ic-173/Triangulation_3/TestReport_lrineau_ArchLinux-CXX14.gz) and  [Triangulation_2](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-6.0-Ic-173/Triangulation_2/TestReport_gimeno_ArchLinux-clang-CXX17-Release.gz)
* Affected package(s): Triangulation_2, Triangulation_3
> Triangulation 2/3:  fstream -> sstream

- Envelope_3/include/CGAL/Envelope_3/Envelope_element_visitor_3.h
Replace some auto to help VC++ 2017
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-176/Envelope_3_Examples/TestReport_Christo_MSVC2017-Debug-64bits.gz
* Affected package(s): Envelope_3
> Envelope: Replace auto

- Maintenance/test_handling/create_testresult_page
Fix the link to the summary page from the testsuite.
> Testsuite: Fix summary page link

- Intersections_3/include/CGAL/Intersections_3/internal/Triangle_3_Triangle_3_intersection.h
- Kernel_23/include/CGAL/Kernel_23/internal/Projection_traits_3.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/autorefinement.h
- Triangulation_2/include/CGAL/Constrained_Delaunay_triangulation_2.h
- Triangulation_2/include/CGAL/Triangulation_2.h
Collect intersection points on edges and in faces to use CDT dedicated functions.
Also add structural filtering with projection traits and restore "classical" projection traits for testing.
> Autorefinement: insert points in edge to avoid filter failures

- Tetrahedral_remeshing/examples/Tetrahedral_remeshing/mesh_and_remesh_c3t3.cpp
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_adaptive_remeshing_impl.h
- Tetrahedral_remeshing/include/CGAL/tetrahedral_remeshing.h
Following PR #7909, this PR introduces a new named parameter for tetrahedral remeshing : `vertex_is_constrained_map`.
This parameter allows to set input corners, that will not be modified throughout remeshing.
Corners can be collected from a C3t3 using its counterpart in `convert_to_triangulation_3()`.
* Affected package : Tetrahedral remeshing
> Tetrahedral_remeshing - add `vertex_is_constrained_map` to set input corners

- .github/workflows/reuse.yml
- Triangulation/include/CGAL/Triangulation_ds_full_cell.h
When using the mirror policy, `combinatorics_` ends with an array of dim+1 `int8_t`, and Triangulation_ds_full_cell wants to store an `unsigned char` after that. It seems natural for it to end up right after the array, however that's not what the Itanium ABI (used everywhere but windows) does, it leaves the padding at the end of `combinatorics_` alone and puts the extra member after that. If `Combinatorics` was a base class, reusing those padding bytes would work. With this ABI, `[[no_unique_address]]` precisely means to pretend that it is a base class, for the purpose of layout. I admit this is not the most common use for this attribute...
With this change, it becomes tempting to make the mirror-index policy the default for static dimensions. Unless the user adds cell data that would …
> [[no_unique_address]] to compact Triangulation_ds_full_cell

- CGAL_Core/examples/Core/CMakeLists.txt
- CGAL_Core/examples/Core/zero-one.cpp
- Number_types/include/CGAL/CORE_Expr.h
Accelerate comparison with zero
* Affected package(s):  Number_types
> Core: Use Expr::is_zero() of AST

- GraphicsView/include/CGAL/Qt/qglviewer_impl.h
The picking was no longer working reliably on my machine (Linux with Wayland). That was due to the handling of pixel ratio (Retina/HiDPI). On my machine I have a screen at 200% and another at 125%.
* Affected package(s): Polyhedron/demo
> Qt6: fix a bug with devicePixelRatio and picking

- Polyhedron/demo/Polyhedron/Scene_triangulation_3_item.cpp
With a c3t3 item, or a triangulation item, hide the tetrahedra, and then hide "cut edges". That triggered a segfault. Now fixed.
* Affected package(s): CGAL Lab (`Polyhedron/demo/`)
> CGAL Lab c3t3 item: fix a segfault

- Installation/cmake/modules/CGAL_SetupCGAL_Qt6Dependencies.cmake
Fixed the order of Qt6 components in the find_package(Qt6 COMPONENTS ....) 
* Issue(s) solved (if any): fix #8058
> Fixed order of Qt6 components in find_package(Qt6 ....)

- Stream_support/include/CGAL/IO/OBJ.h
The "OBJ" file format does not specify which whitespace to use, so be more tolerant about it.
This allows correct reading of OBJ files where only ```\t``` (tabulator) is used as a separator in the ```f``` lines.
> CGAL::IO::Internal::read_OBJ(): allow arbitrary whitespace in "f" lines

- Point_set_processing_3/include/CGAL/wlop_simplify_and_regularize_point_set.h
The documentation for the named parameter `require_uniform_sampling` is incorrect. It is a copy of the documentation written for `number_of_iterations`.
This PR fixes the issue described above by updating the default value and removing the irrelevant extra information.
* License and copyright ownership: I release this contribution to the public domain, for what that's worth.
> Update wlop_simplify_and_regularize_point_set.h documentation

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_faces.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/remeshing_with_isolated_constraints_test.cpp
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_pmp_clip.cpp
Triangulate quads the same way
> Make triangulate_faces deterministic

- Boolean_set_operations_2/doc/Boolean_set_operations_2/Boolean_set_operations_2.txt
- Boolean_set_operations_2/doc/Boolean_set_operations_2/CGAL/Boolean_set_operations_2.h
Add a "\\" after "resp." so that doxygen is not mislead by the "." as end of a brief description.
* Affected package(s): Boolean_set_operations_2
> Boolean Set Operations: Fix brief descriptions

- Spatial_searching/include/CGAL/Kd_tree.h
This
vector<const Point_d*> data;
is no longer needed after being `.clear()`ed at the end of `build()`. This can save a good amount of memory, a `Point_d*` on a 64-bit system is 8 bytes; almost as large as a typical 3-float `Point_d`.
There's no point keeping its capacity, since any call to `build()` will efficiently `.reserve()` it anyway.
_Describe what your pull request changes to CGAL (this can be skipped if it solves an issue already in the tracker or if it is a Feature or Small Feature submitted to the CGAL Wiki)._
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be …
> kd-tree: Deallocate Point pointer vector after build().

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h
The function `tangential_relaxation()` has a named parameter called `allow_move_functor` that enables the user to prevent and cancel some vertex moves.
With this PR, it is now possible to use the same parameter for the relaxation steps of `CGAL::Polygon_mesh_processing::isotropic_remeshing()`
* Issue(s) solved (if any): partially solves issue #8134
> PMP::isotropic_remeshing() - add NP `allow move functor`

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/intersection_impl.h
Speeds coref when meshes are not overlapping too much
> PMP corefinement: only allocate necessary bboxes

- CGAL_Core/include/CGAL/CORE/CoreDefs.h
- CGAL_ImageIO/include/CGAL/ImageIO/recline.h
- Cone_spanners_2/include/CGAL/Cone_spanners_2/Plane_scan_tree.h
- Convex_hull_d/include/CGAL/Regular_complex_d.h
> CGAL Core : fix typos in code comments

- Lab/demo/Lab/Color_map.h
- Lab/demo/Lab/Scene_image_item.cpp
- Lab/demo/Lab/Scene_triangulation_3_item.cpp
Fix the tetrahedrons colors not working on c3t3 with only one subdomain (no outside tetrahedron).
Open the mesh cube.off, create tetrahedral mesh with sharp edge protection, the tetrahedrons colors were black.
* Affected package(s): Lab
> Lab - Fix color from meshes with only one domain

- Polynomial/include/CGAL/polynomial_utils.h
Add code (a 3-liner) for a documented utility function.  I did not add it to the testsuite as I have no idea for the parameter.
* Affected package(s): Polynomial
* Issue(s) solved (if any): fix #8182
> Polynomial:  Add overload which is only documented

- Maintenance/test_handling/create_testresult_page
- Maintenance/test_handling/testresult.css
The summary page is now generated using a JSON file.
A search bar has been added to the summary page.
---
The version of this Pull Request can be reviewed at [this link](https://cgal.geometryfactory.com/~nsaillant/testsuite/TESTRESULTS/).
> Testsuite: enhanced summary page with JSON generation and search functionality

- CGAL_Core/include/CGAL/CORE/Expr.h
- Straight_skeleton_2/test/Straight_skeleton_2/test_sls_offset.cpp
Writing an `Expr`to as stream is slow. We make it faster by writing `Expr::doubleValue()` if the precision is smaller or equal to 17.
* Affected package(s): CORE
> CORE: Accelerate writing to a stream if precision <= 17

- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/smooth_vertices.h
- Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/tetrahedral_remeshing_helpers.h
Fix missing typedefs introduced by PR #7830
> Tet remeshing - missing typedefs

- Arrangement_on_surface_2/demo/Arrangement_on_surface_2_earth/CMakeLists.txt
Fix after #7678 was merge in `master`. There was an worrying CMake warning.
* Affected package(s): Arr_2
> AoS_2, earth demo: find_package(nlohmann_json...) must be QUIET

- Lab/demo/Lab/CGALlab_compile_all_plugins.cpp
- Lab/demo/Lab/CGALlab_macros.cmake
- Lab/demo/Lab/CMakeLists.txt
Fix a usability issue with Visual Studio Code. There is now a new target `CGALlab_compile_all_plugins` that compiles the executable `CGALlab` and all the plugins.
That target, as seen in the vscode Make Project Outline, is placed just below the `CGALlab` target.
If the executable `CGALlab_compile_all_plugins` is launched, it just displays:
```
This executable is not intended to be run.
Please run the CGALlab executable instead.
```
* Affected package(s): Lab
> CGAL Lab: Add a target CGALlab_compile_all_plugins

- Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Add a partial specialization for `CGAL::internal::exact_num_faces(const Surface_mesh&)`  to have an `O(1)` time.  This was pointed out as important for the `Face_count_stop_predicate`  in Issue #8158 
* Issue(s) solved (if any): fix #5720
> Surface_mesh:  Add exact_num_faces(const SM&)

- Lab/demo/Lab/Plugins/PMP/Selection_plugin.cpp
- Lab/demo/Lab/Plugins/PMP/Selection_widget.ui
- Lab/demo/Lab/Plugins/Surface_mesh_deformation/Deform_mesh.ui
- Lab/demo/Lab/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
- Lab/demo/Lab/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
- Lab/demo/Lab/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h
- Lab/demo/Lab/Scene_polyhedron_selection_item.h
- Lab/demo/Lab/Scene_surface_mesh_item.cpp
- Lab/demo/Lab/Travel_isolated_components.h
And remove CC selection from the deformation item, where it had limited use.
* Affected package(s): `Lab`
> Fix CC selection in selection item

- Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
Trivial, that adds a scope. Before it was:
```c++
if(surface)
fp =  Facet_properties(std::make_tuple(*surface,
std::get<1>(intersect),
std::get<0>(intersect)));
```
and now:
```c++
if(surface)
{
fp =  Facet_properties(std::make_tuple(*surface,
std::get<1>(intersect),
std::get<0>(intersect)));
}
```
> Mesh_3: add a scope after if(...)

- Triangulation_on_sphere_2/doc/Triangulation_on_sphere_2/Concepts/TriangulationOnSphereFaceBase_2.h
- Triangulation_on_sphere_2/include/CGAL/Delaunay_triangulation_on_sphere_2.h
- Triangulation_on_sphere_2/include/CGAL/Projection_on_sphere_traits_3.h
- Triangulation_on_sphere_2/include/CGAL/Triangulation_on_sphere_2.h
- Triangulation_on_sphere_2/include/CGAL/Triangulation_on_sphere_face_base_2.h
- Triangulation_on_sphere_2/test/Triangulation_on_sphere_2/CMakeLists.txt
- Triangulation_on_sphere_2/test/Triangulation_on_sphere_2/issue_8200.cpp
Add test case that illustrates Issue #8200.
* Affected package(s): Triangulation_on_sphere_2
* Issue(s) solved (if any): fix #8200
> Triangulation on Sphere: Fix I/O

- Combinatorial_map/include/CGAL/Combinatorial_map_storages_with_index.h
- Generalized_map/include/CGAL/Generalized_map_storages_with_index.h
- Linear_cell_complex/include/CGAL/CMap_linear_cell_complex_storages_with_index.h
- Linear_cell_complex/include/CGAL/Cell_attribute_with_point.h
- Linear_cell_complex/include/CGAL/Cell_attribute_with_point_and_id.h
- Linear_cell_complex/include/CGAL/GMap_linear_cell_complex_storages_with_index.h
- Linear_cell_complex/test/Linear_cell_complex/Linear_cell_complex_2_test.cpp
- Linear_cell_complex/test/Linear_cell_complex/Linear_cell_complex_3_test.cpp
- Linear_cell_complex/test/Linear_cell_complex/Linear_cell_complex_4_test.cpp
Bug fix
* Affected package(s): LCC
* Issue(s) solved (if any): fix #8251
> Bug fix: definition of Self and Base in class Cell_attribute_with_point when using index.

- Mesh_3/doc/Mesh_3/Concepts/MeshFacetCriteria_3.h
- Mesh_3/include/CGAL/Mesh_facet_criteria_3.h
The concept and class were missing `squared_min_radius_bound()` since PR #7754
> Mesh_3 - fix concept `MeshFacetCriteria_3`

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h
- Polygon_mesh_processing/test/Polygon_mesh_processing/test_corefinement_nm_bo.cpp
if `ID = unsigned int`, this can lead to an infinite loop
> Fix iteration on dynamic bit set

- Polygon_mesh_processing/examples/Polygon_mesh_processing/compute_normals_example.cpp
- Polygon_mesh_processing/examples/Polygon_mesh_processing/extrude.cpp
- Polygon_mesh_processing/test/Polygon_mesh_processing/pmp_compute_normals_test.cpp
When calling[ `compute_vertex_normals()`](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__normal__grp.html#ga74e6b247d7e28beb677076aad5614d8c) we better change the string associated to the property from `"v:normals"`  to `" v:normal"` as otherwise it will not be written by[ `write_PLY()`](https://doc.cgal.org/latest/Surface_mesh/group__PkgSurfaceMeshIOFuncPLY.html#ga50f0e9f2b293855d2c7f1a62939cbe8d).
Note that is not a change in CGAL code, but just in an example (that not even saves the file).
> PMP: Change the string of the property

- BGL/include/CGAL/boost/graph/iterator.h
Patch for CGAL-5.5.x to fix compilation issue in clang//llvm 19 (#8313).
Equivalent to #8330 (that is for `5.6.x-branch`).
> Fix clang/llvm 19 compilation issue in iterator.h (for 5.5.x-branch)

- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/Concepts/Periodic_2DelaunayTriangulationTraits_2.h
- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/Concepts/Periodic_2TriangulationTraits_2.h
- Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/Concepts/Periodic_3RegularTriangulationTraits_3.h
- Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/Concepts/Periodic_3TriangulationTraits_3.h
- Triangulation_3/doc/Triangulation_3/Concepts/DelaunayTriangulationTraits_3.h
- Triangulation_3/doc/Triangulation_3/Concepts/TriangulationTraits_3.h
In order to have links to classes in concepts we have to prefix with the namespace.
* Affected package(s): T3, T2, PT2
> T3/T2/PT: Add namespace to classes in concepts

- Shape_detection/include/CGAL/Shape_detection/Efficient_RANSAC/Octree.h
Removing leftover code referring to the deprecated Shape_detection_traits. 
* Issue(s) solved (if any): fix #8290, fix #7872
> Shape_detection: Removing leftover from deprecated Shape_detection_traits

- BGL/include/CGAL/boost/graph/iterator.h
Patch to fix compilation issue in clang//llvm 19 (https://github.com/CGAL/cgal/issues/8313)
> Fix clang/llvm 19 compilation issue in iterator.h (issue #8313)

- Documentation/doc/Documentation/Third_party.txt
> issue #8323 Incorrect link to https://github.com/norlab-ulaval/libpointmatcher/blob/master/doc/CompilationWindows.md

- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Kernel_23/include/CGAL/Kernel/function_objects.h
- Kernel_23/include/CGAL/Kernel/global_functions_3.h
- Kernel_23/include/CGAL/Kernel/global_functions_internal_3.h
- Kernel_23/test/Kernel_23/include/CGAL/_test_compare_angle_3.h
https://github.com/CGAL/cgal/pull/8170 added an overload, but the `Kernel` concept was not updated.
The PR adds the doc, tests, global functions, and an additional overload.
> Add Compare_angle_3 overload and missing global functions / doc

- Documentation/doc/Documentation/Developer_manual/create_and_use_a_cmakelist.txt
The problem surfaced between the releases CGAL 5.3.2 and CGAL 5.4.4. The "Documentation/doc/Documentation/Developer_manual/create_and_use_a_cmakelist.txt" had not been adjusted for the changes in "Surface_mesh/examples/Surface_mesh/CMakeLists.txt" i.e. the changes in its structure and also during the change Qt5 -> Qt6 this was not detected.
> issue #8334 Incorrect example in "Documentation/doc/Documentation/Developer_manual/create_and_use_a_cmakelist.txt"

- Lab/demo/Lab/Plugins/PCA/Basic_generator_plugin.cpp
- Lab/demo/Lab/Plugins/PCA/Basic_generator_widget.ui
We now have several options:
- 2d
- triangulate (kept even if it's not really a polyline)
- polygon
- one per line (within the same item)
> Improve generation of polylines

- Tetrahedral_remeshing/include/CGAL/Adaptive_remeshing_sizing_field.h
The assertion is invalid (at least) when the function takes a far vertex, inserted by parallel version of Mesh_3.
> Tet remeshing - remove assertion in Adaptive sizing field

- BGL/include/CGAL/boost/graph/copy_face_graph.h
Mostly when tm is not empty and almost make it less dependent on tm size
<s>Should probably be backported</s>
> Speed up copy_face_graph

- Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/Gps_on_surface_base_2.h
Fixes  #6840
@efifogel  I did not use expensive assertion as you mentioned because it is already done this way in intersection and symmetric_difference.
> add validation for the range case

- Shape_detection/include/CGAL/Shape_detection/Region_growing/Polygon_mesh/Least_squares_plane_fit_region.h
- Shape_detection/include/CGAL/Shape_detection/Region_growing/internal/utils.h
Polygonal faces are now triangulated and face normals are calculated using PMP::compute_face_normal.
The calculated face normals and triangulations are buffered in Least_squares_plane_fit_region. However, Least_squares_plane_fit_sorting is independent and does not benefit from that buffered data.
* Issue(s) solved (if any): fix #7992
> Shape_detection: using proper triangulated polygonal faces for linear_least_squares

- Intersections_3/include/CGAL/Intersections_3/internal/Line_3_Ray_3_do_intersect.h
- Intersections_3/test/Intersections_3/test_intersections_Line_3.cpp
- Intersections_3/test/Intersections_3/test_intersections_Ray_3.cpp
Some non intersection is wrongfully detected as an intersection for the Line_3 Ray_3 combination. Here is an illustration:
The base code is :
```cpp
if(!do_intersect(l, r.supporting_line()))
return false;
typename K::Coplanar_orientation_3 pred = k.coplanar_orientation_3_object();
CGAL::Orientation p0p1s = pred(l.point(0), l.point(1), r.source());
if(p0p1s == COLLINEAR)
return true;
CGAL::Orientation stp0 = pred(r.source(), r.second_point(), l.point(0));
if(stp0 == COLLINEAR)
return Ray_3_has_on_collinear_Point_3(r,l.point(0),k);
return (p0p1s != stp0);
```
The supporting line of the ray intersects the line, and then nothing is collinear, so we check L0,L1,R1 vs R0,R1,L0, which are of opposite sign so there is an intersection... but there is none.
This check is very similar to what is …
> Fix for Line_3 Ray_3 do_intersect

- Arrangement_on_surface_2/demo/Arrangement_on_surface_2/CurveInputMethods.cpp
- Arrangement_on_surface_2/demo/Arrangement_on_surface_2/GridGraphicsItem.cpp
- GraphicsView/include/CGAL/Qt/qglviewer.h
- GraphicsView/include/CGAL/Qt/qglviewer_impl.h
- Lab/demo/Lab/CGAL_Lab.cpp
- Lab/demo/Lab/MainWindow.cpp
- Lab/demo/Lab/Plugins/Mesh_3/Io_image_plugin.cpp
- Lab/demo/Lab/Plugins/PMP/Engrave_text_plugin.cpp
- Lab/demo/Lab/Plugins/Surface_mesh/Parameterization_plugin.cpp
- Lab/demo/Lab/Viewer.cpp
- Three/include/CGAL/Three/TextRenderer.h
- Three/include/CGAL/Three/Three.h
This PR removes outdated conditional blocks that check for specific Qt versions since CGAL now uses Qt6 exclusively.
* Issue(s) solved (if any): #8381
> Remove outdated Qt version checks

- Lab/demo/Lab/Plugins/Mesh_3/Mesh_3_plugin.cpp
- Lab/demo/Lab/Plugins/Mesh_3/Mesh_function.h
- Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h
- Mesh_3/include/CGAL/Mesh_domain_with_polyline_features_3.h
- Mesh_3/include/CGAL/Mesh_edge_criteria_3.h
While experimenting on self-intersecting polyhedral surfaces, I met two bugs:
* `edge_min_size` was not enough taken into account in `Protect_edges_sizing_field`,
* `edge_distance` was missing the information of which `curve_id` the edge belongs to (available using internal code)
causing crashes.
> Mesh_3 - bug fixes for `edge_distance` and `edge_min_size`

- Generator/include/CGAL/Generator/internal/Generic_random_point_generator.h
[sample_triangle_mesh](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__distance__grp.html#ga6307a4504382c46dc3b0e578ca1f7a3b) was passed a random seed but did not produce stable results.
Pass random instance to GeneratorOnObject in Generic_random_point_generator for consistency
> Pass random instance to GeneratorOnObject in Generic_random_point_generator for consistency

- Stream_support/test/Stream_support/data/simple_ascii.ply
- Stream_support/test/Stream_support/issue8155.cpp
Follow-up of #8155. Added test.
The issue was only merged into master, but it also should have been applied to cgal5.6
* Affected package(s): Point_set_processing_3 IO
* Issue(s) solved (if any): fix #8163
> added test for formerly unused OutputIteratorValueType

- GraphicsView/include/CGAL/Qt/qglviewer_impl.h
This should fix #8232. I have tested locally. I hope that does not 
* Affected package(s): GraphicsView, Qt6
* Issue(s) solved (if any): fix #8232
* License and copyright ownership: bug fix
> simple fix to remove the segfault with Qt>=6.7

- Ridges_3/doc/Ridges_3/Ridges_3.txt
Add a rep example/data with 2 off files
Solves issue 8327 
https://github.com/CGAL/cgal/issues/8327
> Ridges 3 bug fix doc pougetma

- Convex_decomposition_3/include/CGAL/Convex_decomposition_3/External_structure_builder.h
Change the order of delete in External_structure_builder.h to avoid a double free in the exception case
* Affected package(s): Convex_decomposition_3
* Issue(s) solved (if any): fix #422 
* Feature/Small Feature (if any): bugfix
> Fix exception double free in Convex decomposition

- Point_set_processing_3/examples/Point_set_processing_3/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt
- Stream_support/test/Stream_support/CMakeLists.txt
LASlib is not compatible with msvc 2017
* Affected package(s): Point_set_3, Point_set_processing_3, Stream_support, Polyhedron demo
> [LASlib] Prevent usage of LASlib with msvc 2017

- Point_set_processing_3/examples/Point_set_processing_3/CMakeLists.txt
- Polyhedron/demo/Polyhedron/Plugins/Point_set/CMakeLists.txt
Prevent compilation of registration examples using OpenGR with msvc2015
* Affected package(s): Point_set_processing_3
> [PSP3] OpenGR does not work with msvc2015

- Documentation/doc/Documentation/Third_party.txt
- Point_set_processing_3/examples/Point_set_processing_3/read_las_example.cpp
- Point_set_processing_3/include/CGAL/IO/write_las_points.h
Switching to the official LAStools repository
* Affected package(s): PSP3, Point_set_3, Stream_support
* Issue(s) solved (if any): fix #8111 
-----
Edit, @lrineau, 2024/05/24: depends on https://github.com/LAStools/LAStools/pull/194, that has been merged.
> [PSP3] Adapting to new LASTools version

- Stream_support/include/CGAL/IO/Color.h
The zero-th component is 0, and consequently the first is green,  the second is blue and the alpha component is the 3rd.
> Incorrect documentation of color components in Stream_support

- Three/include/CGAL/Three/Scene_item.h
- Three/include/CGAL/Three/Viewer_interface.h
Documentation of enums in Three package is incorrect due to usage of wrong doxygen comment signs
> Incorrect documentation for enums in Three package

- Documentation/doc/biblio/cgal_manual.bib
> Correcting permanent redirect in Algebraic_kernel_d

- Documentation/doc/biblio/cgal_manual.bib
The entry `cgal:l-lsqp-82` was twice, identical, in the bib file. (Found based on #8320 and proposed pull request https://github.com/doxygen/doxygen/pull/11157).
> Remove double entry from bib file

- Testsuite/test/post_process_ctest_results.py
This PR moves and adds some CMake logs to the test results.
The changes of this Pull Request can be viewed [here](https://cgal.geometryfactory.com/~nsaillant/CmakeLogsTestsuite/TestReport_cgal_tester_Fedora)
* Issue(s) solved (if any): #8165
> TESTSUITE: Extract cmake logs in testresults.

- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Curve_analysis_2.h
- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Curve_pair_analysis_2.h
- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Real_roots.h
- Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Status_line_CPA_1.h
- Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_impl.h
- Polytope_distance_d/doc/Polytope_distance_d/Concepts/WidthTraits_3.h
- STL_Extension/include/CGAL/assertions.h
We had `postcondition_code()`  followed by `precondition()` .  I saw it when I only switched off postconditions with a macro.
We might do that for an entire testsuite. 
* Affected package(s): Arrangement on Surface
> Arrangements:  Unify mix of pre and post condition macros

- Maintenance/test_handling/to_zipped_format
- Scripts/developer_scripts/run_testsuite_with_ctest
- Adds OS extraction for Windows and macOS in test script.
- Fixes TPL initialization.
> Testsuite: Add OS extraction for Windows and macOS, fix TPL init

- Mesh_3/examples/Mesh_3/mesh_3D_gray_vtk_image.cpp
Fixes example mesh_3D_gray_vtk_image.
Changed : Meshing all value **under** isovalue --> Meshing all values **over** isovalue.
> Fix example mesh_3D_gray_vtk_image

- Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h
An uninitialized variable gets assigned a value inside a `for` loop,
The compiler cannot know that we always enter the loop and [warns]( https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.1-Ic-15/Polygon_mesh_processing_Examples/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz) when we later use the variable.
We could use `[[assume(x)]]` to indicate that we always will enter the loop but just initializing does the job.
* Affected package(s): PMP 
> PMP: Initialize to avoid warning

- Number_types/include/CGAL/FPU.h
The only place where the function is call is in `Interval_nt::sqrt()` and that functions start with the creation of a protector.
Even worse, if we are using interval with no protection, we get an incorrect rounding mode after a call to sqrt.
> Remove extra rounding mode changes for sqrt for interval

- BGL/include/CGAL/boost/graph/IO/OM.h
In OpenMesh, the outgoing halfedge of a boundary vertex must be the boundary halfedge.
This PR fixes this orientation issue before writing the file, inside `write_OM()`
This PR completes #8427 and #8612 
> IO OpenMesh - fix boundary halfedges

- Documentation/doc/biblio/cgal_manual.bib
- Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
- The `&` in the bibliography has to be escaped
- the doxygen command `\f[` should not be used to directly change the environment, for this the doxygen command `\f{` exists.
> Errors in bibliography  and incorrect usage of `\f[` command

- Lab/demo/Lab/Plugins/PMP/Repair_polyhedron_plugin.cpp
Fix an action  not being in the correct menu.
Not done in https://github.com/CGAL/cgal/pull/8609 because that PR targets 5.6.
* Affected package(s): `Lab`
> Move "remove_almost_degenerate_faces()" to the correct repair menu

- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Arrangement_on_surface_2.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_intro.txt
- Documentation/doc/resources/1.10.0/CGAL_mathjax.js
- Documentation/doc/resources/1.8.13/CGAL_mathjax.js
- Documentation/doc/resources/1.9.6/CGAL_mathjax.js
- Kinetic_surface_reconstruction/doc/Kinetic_surface_reconstruction/Kinetic_surface_reconstruction.txt
- Weights/include/CGAL/Weights/authalic_weights.h
Correction of incorrect usage of LaTeX  in formulas and bibliography altough MatHJax and bibtex.pl doesn't always signal it.
- Incorrect biblio entry (missing `,` and `}`)
- Documentation/doc/biblio/geom.bib
- `&nbsp` is not correct LaTeX has to be `~`
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Arrangement_on_surface_2.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_intro.txt
- Incorrect formula regarding usage of `\left` and `\right` (also signaled by MathJax
- Arrangement_on_surface_2/doc/Arrangement_on_surface_2/Arrangement_on_surface_2.txt
- `DeclareMathOperator` is a command that should be in the preamble, alternatively the command `\operatorname` can be used explicitly (as done here as it is only used once)
- …
> LaTeX compliance for formulas and errors in bibliography

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h
- Surface_mesh_skeletonization/benchmark/Surface_mesh_skeletonization/mcf_scale_invariance.cpp
- Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_LCC_example.cpp
- Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_example.cpp
- Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_om_example.cpp
- Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_sm_example.cpp
- Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/simple_mcfskel_LCC_example.cpp
- Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/simple_mcfskel_example.cpp
- Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/simple_mcfskel_sm_example.cpp
Spelling correction
Note: we also have a similar spelling error in:
```
Surface_mesh_skeletonization/benchmark/Surface_mesh_skeletonization/mcf_scale_invariance.cpp:104:  output.open("correspondance.cgal");
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_example.cpp:68:  output.open("correspondance-poly.polylines.txt");
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_LCC_example.cpp:66:  output.open("correspondance-lcc.polylines.txt");
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_om_example.cpp:75:  output.open("correspondance-sm.polylines.txt");
Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_sm_example.cpp:67:  output.open("correspondance-sm.polylines.txt"); …
```
> Spelling correction

- Documentation/doc/resources/1.10.0/BaseDoxyfile.in
Due to an incompatibility change in doxygen (see https://github.com/doxygen/doxygen/commit/2a62c197550990a6346d826cf0644a52d5e03e9b#commitcomment-150534822) it is necessary to add the setting for `FULL_SIDEBAR` to the setup of the CGAL documentation.
> Doxygen incompatibility in respect to `FULL_SIDEBAR` setting

- Stream_support/include/CGAL/IO/WKT.h
- Stream_support/test/Stream_support/test_WKT.cpp
Fix in the documentation, namely that also 3D points may be used.
* Affected package(s): Stream_support
> Stream_support: Document that WKT can also handle 3D points

- Orthtree/include/CGAL/Octree.h
- Orthtree/include/CGAL/Orthtree.h
- Orthtree/include/CGAL/Orthtree/Split_predicates.h
- Orthtree/include/CGAL/Orthtree_traits_base.h
- Orthtree/include/CGAL/Orthtree_traits_point.h
Octree doc states requirement of RandomAccessIterator for point range
added missing _object types for functors in traits
* Affected package(s): Orthtree
> Orthtree: Doc and traits bugfixes

- Tetrahedral_remeshing/test/Tetrahedral_remeshing/test_tetrahedral_remeshing_of_one_subdomain.cpp
Ref:
```
------------------------------------------------------------------
- Tetrahedral_remeshing/ProgramOutput.execution   of  test_tetrahedral_remeshing_of_one_subdomain
------------------------------------------------------------------
CGAL::Random()::get_seed() = 1736397916
CGAL Random seed = 1736397916
valid data structure
valid triangulation
Tetrahedral remeshing (nb_iter = 1, protect = false)
Init tetrahedral remeshing...done.
Split long edges... done (2449 splits, in 0.0591981 sec).
Collapse short edges... done (0 collapses, in 0.077903 seconds).
Flip edges...
Flip edges... done (83/2946 surface/volume flips done, in 0.336761 seconds).
Smooth vertices... done (0/760/1915 vertices smoothed, average move = 0.083582, in 0.128201 seconds).
Flip edges...
Flip edges... done (32/2958 …
```
> Use the same generator for reproducible runs

- Number_types/doc/Number_types/CGAL/double.h
- Number_types/doc/Number_types/CGAL/float.h
- Number_types/doc/Number_types/CGAL/int.h
- Number_types/doc/Number_types/CGAL/long_double.h
- Number_types/doc/Number_types/CGAL/long_long.h
* Issue(s) solved (if any): fix #7781 #7782 
> Correct documentation mistakes in double.h and long_double.h

- Alpha_wrap_3/include/CGAL/Alpha_wrap_3/internal/Alpha_wrap_triangulation_cell_base_3.h
- Mesh_2/include/CGAL/Delaunay_mesh_face_base_2.h
- Mesh_2/include/CGAL/Delaunay_mesh_vertex_base_2.h
- Mesh_3/include/CGAL/Compact_mesh_cell_base_3.h
- Mesh_3/include/CGAL/Mesh_cell_base_3.h
- Mesh_3/include/CGAL/Mesh_polyhedron_3.h
- Mesh_3/include/CGAL/Mesh_vertex_base_3.h
- SMDS_3/include/CGAL/Compact_simplicial_mesh_cell_base_3.h
- SMDS_3/include/CGAL/Simplicial_mesh_cell_base_3.h
- SMDS_3/include/CGAL/Simplicial_mesh_vertex_base_3.h
- STL_Extension/include/CGAL/Compact_container.h
- STL_Extension/include/CGAL/Concurrent_compact_container.h
- STL_Extension/include/CGAL/Time_stamper.h
- STL_Extension/test/STL_Extension/test_Compact_container.cpp
- STL_Extension/test/STL_Extension/test_Concurrent_compact_container.cpp
- STL_Extension/test/STL_Extension/test_namespaces.cpp
It is not clear to me that this is the right thing to do:
- it is done for some classes
- but in some test, a comment mention that it should be uninitialized (the test works if init to -1 but not to 0).
- Base_time_stamper is doing an init to -2
> Always init time_stamp to -2

- Combinatorial_map/include/CGAL/Cell_iterators.h
- Combinatorial_map/include/CGAL/Compact_container_with_index.h
- Combinatorial_map/test/Combinatorial_map/CMakeLists.txt
- Combinatorial_map/test/Combinatorial_map/Combinatorial_map_empty_it_test.cpp
- Generalized_map/include/CGAL/GMap_cell_iterators.h
Solve a bug for CMap and GMap when we iterate on an empty map with an iterator that needs to mark cells, and when using index version.
* Affected package(s): CMap GMap
> Cmap add test gdamiand

- Documentation/doc/biblio/cgal_manual.bib
- Kernel_d/doc/Kernel_d/CGAL/Kernel_d/Aff_transformation_d.h
The formula in Documentation/doc/biblio/cgal_manual.bib
```
@article{cgal:cgm-fobbo-11,
title={Fast Oriented Bounding Box Optimization on the Rotation Group $\SO(3, \mathrm{R})$},
author={Chang, Chia-Tche and Gorissen, Bastien and Melchior, Samuel},
```
renders incorrectly (see Optimal_bounding_box/citelist.html) as there is no command `\SO` in LaTeX
The formula in doc/Kernel_d/CGAL/Kernel_d/Aff_transformation_d.h
```
\pre \f$ sin_num^2 + cos_num^2 = den^2\f$ and \f$ 0 \leq e_1 < e_2 < d\f$.
```
renders in an unexpected way (see Kernel_d/classCGAL_1_1Aff__transformation__d.html) as the `_` is seen as subscript operator in LaTeX
> Incorrect rendered formulas

- Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
We know that the variable `i` will be set by `is_edge()`, we try to indicate it with a `CGAL_assume()` but that does not help the compiler, so let's just initialize it.  We get the warning [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.1-I-95/Triangulation_2/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz).
I am wondering if the `CGAL_assertion()` I have put makes sense. 
> T2: avoid maybe uninitialized warning

- Mesh_2/doc/Mesh_2/CGAL/IO/write_VTU.h
- Stream_support/include/CGAL/IO/VTK/VTK_writer.h
Add warning that the stream must be opened with `std::ios::binary`.
Deal with a potentially empty vector of faces.
* Affected package(s): Mesh_2
> Mesh_2: Fixes of write_VTU()

- Arrangement_on_surface_2/include/CGAL/Arr_dcel_base.h
- Arrangement_on_surface_2/include/CGAL/Arr_extended_dcel.h
- Arrangement_on_surface_2/include/CGAL/Surface_sweep_2/Arr_basic_insertion_traits_2.h
- Installation/CHANGES.md
The changes fix a bug in the extensions of vertex and halfedge types of the DCEL when used to instantiate Arrangement_with_history_2 or similar arrangement classes that derive from Arrangement_2.
Typically, only the face type is extended or all the 3 types (vertex, halfedge, and face) are extended, and for such extensions we have dedicated class templates. The bug shows up when trying to extend any other subset of the 3 types, and apparently, this hasn't been used much with Arrangement_with_history_2.
* Affected package(s): Arrangement_on_surface_2
* Issue(s) solved (if any): NA
* Link to compiled documentation: NA
> Aos 2 dcel extension efif

- Installation/CHANGES.md
- Polygon_mesh_processing/doc/Polygon_mesh_processing/Concepts/PMPCorefinementVisitor.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h
Add a method in the corefinement visitor to collect the list of output faces corresponding to coplanar input faces
> Add a way to collect input coplanar faces after corefinement

- Installation/CHANGES.md
- Mesh_3/doc/Mesh_3/CGAL/Mesh_3/parameters.h
- Mesh_3/doc/Mesh_3/Mesh_3.txt
- Mesh_3/examples/Mesh_3/remesh_polyhedral_surface.cpp
- Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_gray_image.h
- Mesh_3/include/CGAL/Mesh_3/Construct_initial_points_labeled_image.h
- Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
- Mesh_3/include/CGAL/Polygon_mesh_processing/surface_Delaunay_remeshing.h
- Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h
- Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h
- Mesh_3/include/CGAL/make_mesh_3.h
- Mesh_3/include/CGAL/refine_mesh_3.h
- Mesh_3/test/Mesh_3/CMakeLists.txt
- Mesh_3/test/Mesh_3/test_remeshing_polyhedron.cpp
- STL_Extension/include/CGAL/STL_Extension/internal/mesh_option_classes.h
- STL_Extension/include/CGAL/STL_Extension/internal/mesh_parameters_interface.h
Add the option `surface_only()` to `make_mesh_3()`, to completely skip the "refine_cells" part of Mesh_3, and cancel perturbation and exudation.
@soesau and I noticed that scanning cells, even in the context of "Surface mesher", takes a lot of useless time.
@soesau you can use this branch for your benchmark
@lrineau do you think `surface_only` should be a member of `Mesher_3` or a parameter of `Mesher_3::refine_mesh()` (as done here)?
* [Small Feature](https://cgalwiki.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Mesh_3_surface_only()) Pre-approved by [User:Sloriot](https://cgalwiki.geometryfactory.com/CGAL/Members/wiki/User:Sloriot) -- 2025/03/17
* Link to compiled documentation [make_mesh_3()](https://cgal.github.io/8781/v0/Mesh_3/group__Pkg …
> Mesh_3 - add `surface_only()` named parameter

- BGL/doc/BGL/Doxyfile.in
- BGL/doc/BGL/PackageDescription.txt
- BGL/doc/BGL/examples.txt
- BGL/examples/BGL_surface_mesh/CMakeLists.txt
- BGL/examples/BGL_surface_mesh/shortest_path.cpp
- BGL/include/CGAL/boost/graph/dijkstra_shortest_path.h
- BGL/include/CGAL/boost/graph/shortest_path.h
- Installation/CHANGES.md
- Lab/demo/Lab/Scene_polyhedron_selection_item.cpp
- STL_Extension/include/CGAL/STL_Extension/internal/parameters_interface.h
computes the shortest path between two vertices, using Dijkstra algorithm
Todo
* [Small feature](https://cgalwiki.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_CGAL::shortest_path(vs,_vt))
* Link to compiled documentation [CGAL::shortest_path_between_two_vertices()](https://cgal.github.io/8724/v0/BGL/group__PkgBGLTraversal.html#ga5627dee8a6fe4d238cb5c91e123aa763)
> BGL - add `CGAL::dijkstra_shortest_path(vs, vt, mesh)`

- Lab/demo/Lab/Plugins/IO/OM_io_plugin.cpp
A `Scene_polyhedron_selection_item`  is created when loading an OpenMesh file. When there was no selection inside the file, this selection item was neither added to the scene nor deleted. Thus, it still received Qt signals and caused crashes when the actual mesh was removed.
* Affected package(s): CGALlab
> Lab - Fixed loading of OpenMesh files without selection

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh_planar_patches.h
function internally used not already exposed
> Restrict shared vertices on the boundary

- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/refine_with_plane.h
Spelling correction.
(Entire documentation here looks a bit incomplete seen the words `TODO`)
> Spelling correction.

- Documentation/doc/scripts/generate_how_to_cite.py
- Triangulation_on_hyperbolic_surface_2/doc/Triangulation_on_hyperbolic_surface_2/PackageDescription.txt
Based on #8320 and https://github.com/doxygen/doxygen/pull/11157 creating an assertion for builds from scratch when a citation name is used multiple times.
> Double use of citation name

- SMDS_3/examples/SMDS_3/tetrahedron_soup_to_c3t3_example.cpp
- SMDS_3/include/CGAL/Mesh_complex_3_in_triangulation_3.h
When loading a .mesh file to a `Triangulation_3`, and then a `C3t3`, as done in [this example](https://doc.cgal.org/latest/SMDS_3/SMDS_3_2tetrahedron_soup_to_c3t3_example_8cpp-example.html) leads to a `C3t3` for which `number_of_facets()` and `number_of_cells()` return 0, because the internal counters have not been updated by `c3t3.triangulation() = tr`.
It is not clear to the user why these numbers are 0, and the function `rescan_after_load_of_triangulation()` (which fixes the counters) is not documented.
~~Add the use of `rescan_after_load_of_triangulation()` in an example.~~
~~The other option would be to use it automatically in the functions that load a triangulation.~~
~~@lrineau @MaelRL do you have an opinion?~~
~~Todo : discuss the API~~
Add and document a function …
> SMDS_3 - add `c3t3.set_triangulation()`

- STL_Extension/include/CGAL/Named_function_parameters.h
`const` variables declared at global scope have internal linkage, and so if they are declared in a header file, they are replicated in every file that `#include` the header. They also can't be the target of `using` declarations that exports the variable into a C++20 module. This change marks a number of variables with `inline`, which gives these variables external linkage, allows the linker to unify all of these variables between different `.o` files, and also allows for their use in C++20 modules.
There is a separate question whether these variables could or should be `constexpr` instead of just `const`. The difference between `constexpr` and `const` has no effect on linkage, and so in the spirit of taking one step at a time, this patch does not address the `constexpr` vs `const` …
> Mark variables declared at global scope in headers as 'inline'.

- Bounding_volumes/doc/Bounding_volumes/CGAL/Min_sphere_annulus_d_traits_2.h
- Bounding_volumes/doc/Bounding_volumes/CGAL/Min_sphere_annulus_d_traits_3.h
- Bounding_volumes/doc/Bounding_volumes/CGAL/Min_sphere_annulus_d_traits_d.h
- Bounding_volumes/doc/Bounding_volumes/Concepts/MinQuadrilateralTraits_2.h
- Bounding_volumes/doc/Bounding_volumes/Concepts/RectangularPCenterTraits_2.h
- Bounding_volumes/doc/Bounding_volumes/dependencies
- Inscribed_areas/doc/Inscribed_areas/Concepts/ExtremalPolygonTraits_2.h
- Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h
- Periodic_2_triangulation_2/doc/Periodic_2_triangulation_2/Concepts/Periodic_2TriangulationTraits_2.h
- Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/Concepts/Periodic_3TriangulationTraits_3.h
- Polytope_distance_d/doc/Polytope_distance_d/Concepts/AllFurthestNeighborsTraits_2.h
When `CGAL::Weighted_point_3` was moved into `Kernel::` we forgot to switch to CamelCase, for  example [here](https://cgal.geometryfactory.com/CGAL/doc/master/Kernel_23/classKernel_1_1ConstructPoint__3.html).
The same for `Iso_rectangle_2`  and `Iso_cuboid_3`
> Kernel: Concepts are CamelCase

- Documentation/doc/Documentation/Developer_manual/Chapter_code_format.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_handles.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_iterators_and_circulators.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_namespaces.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_objects.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_portability.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_robustness.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_testing.txt
- Documentation/doc/Documentation/Developer_manual/Chapter_traits_classes.txt
- Documentation/doc/Documentation/Tutorials/Tutorials.txt
- Documentation/doc/Documentation/deprecated.txt
Fix that functions shall be written with  `()`.     
Removed an example with the no longer existing `Window_stream`
This part of the manual needs a real review, as a lot is now directly on github.
> Developer Manual: trivial fixes

- Point_set_processing_3/include/CGAL/poisson_eliminate.h
hide internal namespace in documentation
* Affected package(s): Point_set_processing_3
> PSP3: Hide internal of poisson_eliminate in documentation

- Triangulation_3/doc/Triangulation_3/CGAL/Delaunay_triangulation_3.h
- Triangulation_3/doc/Triangulation_3/CGAL/Delaunay_triangulation_cell_base_with_circumcenter_3.h
- Triangulation_3/doc/Triangulation_3/CGAL/Regular_triangulation_3.h
- Triangulation_3/doc/Triangulation_3/CGAL/Regular_triangulation_cell_base_3.h
- Triangulation_3/doc/Triangulation_3/CGAL/Regular_triangulation_cell_base_with_weighted_circumcenter_3.h
- Triangulation_3/doc/Triangulation_3/CGAL/Triangulation_3.h
- Triangulation_3/doc/Triangulation_3/Concepts/DelaunayTriangulationCellBase_3.h
- Triangulation_3/doc/Triangulation_3/Concepts/RegularTriangulationCellBase_3.h
Just typos  in the documentation (not even headers)
> Triangulation_3: Documentation fixes

- HalfedgeDS/include/CGAL/boost/graph/graph_traits_HalfedgeDS.h
- Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h
- STL_Extension/include/CGAL/In_place_list.h
This PR makes the function `CGAL::Polygon_mesh_processing::stitch_borders()`  deterministic.
It was already deterministic for `CGAL::Surface_mesh` but not for `CGAL::Polyhedron_3` as it compared pointers.
In case we do not want to change the code, we can also document the existing named parameter `halfedges_keeper`.
> PMP: Make stitch_borders() deterministic

- Alpha_wrap_3/examples/Alpha_wrap_3/volumetric_wrap.cpp
The default iteration number (1) is too few for the remeshing algorithm to produce something nice, given that we start from a rather nasty triangulation at the end of alpha wrap.
* Affected package(s): `Alpha_wrap_3`
> AW3: Use more iterations in tetrahedral remeshing example

- Documentation/doc/Documentation/Third_party.txt
We require at least 1.74, but we gave an example with 1.70
We did not give the path to the boost cmake config file.   
* Affected package(s): documentation
> Fix how to set BOOST_ROOT

- Polygon_repair/include/CGAL/Polygon_repair/Winding.h
- Polygon_repair/include/CGAL/Polygon_repair/repair.h
- Polygon_repair/test/Polygon_repair/CMakeLists.txt
- Polygon_repair/test/Polygon_repair/repair_polygon_non_zero_2_test.cpp
The repair function for the `Non_zero_rule`  was only implemented for `Polygon_with_holes`. This PR adds the overload for `Polygon_2`  and `Multipolygon_with_holes_2`.
* Affected package(s): Polygon_repair
> Polygon_repair: Add overloads for Non_zero_rule

- Maintenance/test_handling/Summary_Script.js
Add null checks and fallbacks for missing test_directories (white column) property to prevent crashes when processing platform data.
> TESTSUITE: Enhance error handling and default values in the Summary page

- Apollonius_graph_2/doc/Apollonius_graph_2/CGAL/Apollonius_site_2.h
Remove references to visualization that was removed earlier in class [`Apollonius_graph_site_2`](https://doc.cgal.org/latest/Apollonius_graph_2/classCGAL_1_1Apollonius__site__2.html).
* Affected package(s): Apollonius_graph
> Apollonius_graph: Clean Up Documentation

- Polygon_mesh_processing/include/CGAL/Side_of_triangle_mesh.h
Convenient for using only a subset of faces for example, or to force the building of the tree
> Allow Side_of_triangle to take ownership on an external AABB-tree
