Combinatorial_map/include/CGAL/Cell_const_iterators.h, Combinatorial_map/include/CGAL/Cell_iterators.h, Combinatorial_map/include/CGAL/Combinatorial_map.h, Combinatorial_map/include/CGAL/Combinatorial_map_iterators_base.h, Linear_cell_complex/demo/Linear_cell_complex/CMakeLists.txt, Linear_cell_complex/include/CGAL/Linear_cell_complex_constructors.h, Linear_cell_complex/include/CGAL/Linear_cell_complex_storages.h
Bug fix in size methods of range in Combinatorial map.
In the previous version, const iterator are constructed at each loop using the non const version. This is ok but leads to useless additional time.
This is corrected in this patch by modifying the loop used in size methods; and by modifying CMap_cell_iterator iterator in order to add the missing constructor using a dart in parameter.
Update also the undocumented function write_off to use the size function.
Tested in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.6-Ic-144.shtml
=> Lcc writeoff for 3 d gdamiand

Combinatorial_map/include/CGAL/Combinatorial_map_insertions.h
Add a missing #include in Combinatorial_map_insertions.h.
This is a trivial bugfix.
=> Add missing #include

BGL/include/CGAL/boost/graph/selection.h
Trivial bug fix in the polyhedron demo face selection erosion mechanism
=> handle when boundary of the selection is on the border

Installation/changes.html
We need to change the release month, because I will not managed to release 4.6 before 1st April.
I have modified `Installation/changes.html`, and forgot `Installation/CHANGES`.
=> Change the release month to April 2015

NewKernel_d/include/CGAL/NewKernel_d/Filtered_predicate2.h
The file was copied from Filtered_kernel and one class was renamed, but apparently the include guard was missed. This leads to missing types when code from Filtered_kernel is included first and vice versa.
=> Filter_predicate2.h has the wrong include guard

Linear_cell_complex/include/CGAL/Linear_cell_complex_constructors.h
I have tested this modification on a simple [code](https://gist.github.com/pranavkantgaur/9e928dc3fd5816cb891a#file-cubedtlccply-cpp), It:
* Preserves the coordinates of _finite vertices_ after import from Delaunay triangulation.
* (May not be important)Leaves coordinates of _infinite vertex_ in linear cell complex same as they were in corresponding Delaunay triangulation.
I have discussed this issue recently in CGAL [user forum](http://cgal-discuss.949826.n4.nabble.com/import-from-triangulation-3-Issue-in-number-of-vertices-stored-in-cell-complex-td4660599.html)
=> fixes issue of infinite vertex in import_from_triangulation_3

Documentation/biblio/cgal_manual.bib
If a note is simply a URL turn it into a url. Also turn all occurrences
of \path|http://www.cgal.org| into \url{http://www.cgal.org}.
=> Make the bibliography more uniform

Apollonius_graph_2/examples/Apollonius_graph_2/ag2_exact_traits.cpp, Apollonius_graph_2/examples/Apollonius_graph_2/ag2_exact_traits_sqrt.cpp
Add warnings in two example files in the form of comments. The warnings indicate that the exact kernel used in the examples are for inllustration purposes only and should not be considered as an option when performing efficiency-critical computations and/or benchmarking.
=> Apollonius graph 2: add warnings in examples

Principal_component_analysis/include/CGAL/eigen_2.h
Here's the stripped down test case to demonstrate the compilation error:
```c++
#include <iostream>
#include <CGAL/Exact_predicates_exact_constructions_kernel_with_sqrt.h>
#include <CGAL/Polygon_2.h>
#include <CGAL/linear_least_squares_fitting_2.h>
typedef CGAL::Exact_predicates_exact_constructions_kernel_with_sqrt K;
typedef CGAL::Polygon_2<K> Polygon_2;
int main( int argc, const char* argv[] )
{
K::Point_2 centroid = K::Point_2(0, 0);
K::Line_2 line;
CGAL::Dimension_tag<0> dt;
Polygon_2 p;
p.push_back(K::Point_2(0,1));
p.push_back(K::Point_2(0,2));
p.push_back(K::Point_2(2,2));
CGAL::linear_least_squares_fitting_2( p.vertices_begin(), p.vertices_end(), line, centroid, dt);
std::cout << centroid << std::endl;
}
```
Which gives:
```
In file included from cgal/sample/foo.cpp:4:
In file …
```
=> Switch eigen_2 from std::sqrt to CGAL::sqrt

Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Xy_coordinate_2.h, Arrangement_on_surface_2/include/CGAL/Arr_rat_arc/Base_rational_arc_ds_1.h, Arrangement_on_surface_2/include/CGAL/Arr_rat_arc/Rational_arc_d_1.h, Interval_support/include/CGAL/Bigfloat_interval_traits.h, Kernel_d/include/CGAL/Filtered_kernel_d.h, Mesh_3/applications/mesher_tester.h, Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h, Mesh_3/include/CGAL/Mesh_3/Mesh_global_optimizer.h, Mesh_3/include/CGAL/Mesh_3/Sliver_perturber.h, Surface_mesh/examples/Surface_mesh/sm_memory.cpp, Surface_mesher/include/CGAL/Surface_mesher/Polyhedral_oracle.h
While going through the list of [Boost libraries used](https://gist.github.com/bo0ts/dacb1a3100c49ea050d8) by CGAL I did a quick check of some suspicious includes and cleaned them up.
The most notable is the removal of Boost.Lambda code from Mesh_3.
=> Fix some Boost includes

Mesh_3/doc/Mesh_3/CGAL/Mesh_complex_3_in_triangulation_3.h, Mesh_3/doc/Mesh_3/CGAL/Mesh_constant_domain_field_3.h, Mesh_3/doc/Mesh_3/Concepts/MeshCellBase_3.h, Mesh_3/doc/Mesh_3/Concepts/MeshDomainField_3.h, Mesh_3/doc/Mesh_3/Concepts/MeshDomainWithFeatures_3.h, Mesh_3/doc/Mesh_3/Concepts/MeshDomain_3.h, Mesh_3/doc/Mesh_3/PackageDescription.txt, Point_set_processing_3/doc/Property_map/Property_map.txt, Point_set_processing_3/include/CGAL/property_map.h
After having introduced the concept <code>Index</code> we have to take care of wrong links.
=> Escape the word Index with '%'

Kernel_23/doc/Kernel_23/CGAL/Exact_predicates_exact_constructions_kernel.h, Kernel_23/doc/Kernel_23/CGAL/Exact_predicates_exact_constructions_kernel_with_kth_root.h, Kernel_23/doc/Kernel_23/CGAL/Exact_predicates_exact_constructions_kernel_with_root_of.h, Kernel_23/doc/Kernel_23/CGAL/Exact_predicates_exact_constructions_kernel_with_sqrt.h, Kernel_23/doc/Kernel_23/CGAL/Exact_predicates_inexact_constructions_kernel.h, Kernel_23/doc/Kernel_23/Kernel_23.txt, Kernel_23/include/CGAL/Exact_predicates_exact_constructions_kernel_with_kth_root.h, Kernel_23/include/CGAL/Exact_predicates_exact_constructions_kernel_with_root_of.h, Kernel_23/test/Kernel_23/Exact_predicates_exact_constructions_kernel.cpp
Adding new typedefs and documentation for 
- `CGAL::Exact_predicates_exact_constructions_kernel_with_kth_root`
- `CGAL::Exact_predicates_exact_constructions_kernel_with_root_of`
small feature:
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/EPEC_with_kth_root
not approved yet
=> Exact predicates exact constructions kernel with kth root hemmer

Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_filtered_traits_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_hierarchy_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_hierarchy_vertex_base_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_site_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_storage_site_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_traits_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/CGAL/Segment_Delaunay_graph_vertex_base_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/Concepts/SegmentDelaunayGraphDataStructure_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/Concepts/SegmentDelaunayGraphSite_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/Concepts/SegmentDelaunayGraphStorageSite_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/Concepts/SegmentDelaunayGraphTraits_2.h, Segment_Delaunay_graph_2/doc/Segment_Delaunay_graph_2/Segment_Delaunay_graph_2.txt, Segment_Delaunay_graph_2/examples/Segment_Delaunay_graph_2/sdg-red-blue-info.cpp, Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2.h, Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Filtered_traits_base_2.h, Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Oriented_side_C2.h, Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Segment_Delaunay_graph_2_impl.h, Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Segment_Delaunay_graph_hierarchy_2_impl.h, Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2/Traits_base_2.h, Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_hierarchy_2.h, Segment_Delaunay_graph_2/test/Segment_Delaunay_graph_2/test_sdg_2_et.cpp, Segment_Delaunay_graph_2/test/Segment_Delaunay_graph_2/test_sdg_hierarchy_2_et.cpp, Segment_Delaunay_graph_2/test/Segment_Delaunay_graph_2/test_sdg_hierarchy_info_2_no_up.cpp, Segment_Delaunay_graph_2/test/Segment_Delaunay_graph_2/test_sdg_hierarchy_info_2_up.cpp, Segment_Delaunay_graph_2/test/Segment_Delaunay_graph_2/test_sdg_info_2.cpp
The changes are in the sdg-generalize-philaris branch that can be merged to master.
Small feature page in the wiki:
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/SDG_support_for_Linf_metric
Already merged in integration and tested in testsuite-Wednesday, CGAL-4.7-Ic-19:
https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-19.shtml
In the above testsuite, I checked the rows for: Segment_Delaunay_graph_2, Segment_Delaunay_graph_2_Demo, Segment_Delaunay_graph_2_Examples.
There is a warning in Segment_Delaunay_graph_2_Examples, which was also been there in previous testsuites and it seems to me to be from an over-fastidious compiler:
https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-19/Segment_Delaunay_graph_2_Examples/TestReport …
=> small feature: prepare Segment Delaunay graph to support L_infinity metric

Kernel_d/doc/Kernel_d/CGAL/Epick_d.h, NewKernel_d/include/CGAL/NewKernel_d/Kernel_d_interface.h, NewKernel_d/include/CGAL/NewKernel_d/Types/Sphere.h, NewKernel_d/include/CGAL/NewKernel_d/function_objects_cartesian.h, NewKernel_d/include/CGAL/NewKernel_d/functor_tags.h, NewKernel_d/test/NewKernel_d/Epick_d.cpp
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Side_of_bounded_diametral_sphere
It isn't clear if this was tested in CGAL-4.7-Ic-29, CGAL-4.7-Ic-30 or both.
https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-29/NewKernel_d/TestReport_afabri_x64_Cygwin-Windows8_MSVC2010-Release-64bits.gz
does not show my branch in the log, but the absurd error message proves it was there.
https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-30/NewKernel_d/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-64bits.gz
Now my branch is listed in the log (and VS goes loopy)
=> New kernel d insphere glisse

Combinatorial_map/include/CGAL/Combinatorial_map_functors.h, Combinatorial_map/include/CGAL/internal/Combinatorial_map_copy_functors.h, Combinatorial_map/include/CGAL/internal/Combinatorial_map_group_functors.h, Combinatorial_map/include/CGAL/internal/Combinatorial_map_internal_functors.h, Linear_cell_complex/include/CGAL/Cell_attribute_with_point.h
(before they were in internal); add a missing void typedef.
For now, let the functor undocumented.
Tested in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-33.shtml.
=> Move functor that detect non void attributes and point in CGAL namespace.

BGL/include/CGAL/boost/graph/iterator.h
bug fix. The iterator did not dereference to opposite faces
=> Fix Face_around_face_iterator

Installation/CMakeLists.txt
While it might seem cleaner to simply add the -g0 argument, removing -g
is safer: -g0 would need to be added after any possible -g flags. Since
CMake makes no guarantees how the COMPILE_OPTIONS of a target are
actually initialized and we cannot change them on an individual basis
this is not easy to achieve. Hence we strip the CXX_FLAGS of -g. This
also still allows specifying it manually through CGAL_CXX_FLAGS.
=> Remove the -g flag in testsuites

Triangulation_2/include/CGAL/Triangulation_2_filtered_projection_traits_3.h, Triangulation_2/include/CGAL/Triangulation_2_projection_traits_3.h, Triangulation_2/test/Triangulation_2/test_cdt_2_projection_traits_special_case.cpp
There is a bug in the traits class for `Triangulation_2` that can use 3D points in an arbitrary plane (knowing the normal to the plane). The first commit  907201e shows a test case that fails. The second commit 5ea63b7 fixes the bug.
In CGAL, those traits classes are used only in the function that triangulates the faces of a non-triangle polyhedron.
=> Fix a bug in Triangulation_2_projection_traits.h and its filtered version

Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h, Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h
Should fix issue https://github.com/CGAL/cgal/issues/121
The error was that the "domain" class returns a `CGAL::Point_3<K>`, the
triangulation uses `CGAL::Weighted_point<CGAL::Point_3<K>, double>`, and
one piece of code from Mesh_3 in <CGAL/Mesh_3/Refine_facets_3.h> does an
implicit conversion from
tuple<something_A, something_B, CGAL::Point_3<K> >
to
tuple<something_A, something_B, CGAL::Weighted_point<P, double> >
and plug that into a `boost::optional`. For some reason, the g++-4.4
compiler does not like that, but recent g++ compilers do.
The fix is to explicit the conversion from `Point_3` to
`Weighted_point<Point_3, double>`.
=> Fix a compilation error with gcc44 -std=c++0x

Installation/src/CMakeLists.txt
Replaces #131 from Philipp:
> This caused a bug in CMake>=3.3.0 when file(GLOB) is not adding multiple
> slashes. The lack of trailing slashes is guaranteed and documented in
> `get_filename_component`.
> Verified against a build of Kitware/CMake@f4144af
The initial patch from #131 was not right, for CMake<=2.8.11. I have:
- rebased the branch onto `releases/CGAL-4.6-branch`,
- added a commit to use `PATH` instead of `DIRECTORY`.
=> Use get_filename_component to manipulate paths

Installation/CMakeLists.txt
If CMAKE_BUILD_TYPE is not set in the initial run, is only
defined *after* this code is run. Since the build type is cached this
seemed to work when a cmake cache was already present, but not without.
=> Do not check for the actual CMAKE_BUILD_TYPE

Documentation/doc/Documentation/Installation.txt, Scripts/developer_scripts/create_cgal_test, Scripts/scripts/cgal_create_CMakeLists, Scripts/scripts/cgal_create_cmake_script
Rationale:
cgal_create_CMakeLists and related scripts used to not consider files ending on anything else than .cpp or .C as C++ sources. This patch allows for the list of extensions considered as C++ source files as stated in the g++ man page.
=> make cgal_create_CMakeLists recognize all common C++ source file extensions

BGL/include/CGAL/boost/graph/graph_traits_Surface_mesh.h, BGL/include/CGAL/boost/graph/iterator.h, BGL/include/CGAL/boost/graph/properties_Surface_mesh.h, Surface_mesh/include/CGAL/Surface_mesh.h, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh_fwd.h
This PR removes Boost.Fusion as a dependency and removes the use of ADL in a special case to make Surface_mesh work with GCC4.4 and C++0x.
=> Fix two issues with Surface_mesh and GCC4.4 + C++0x

INSTALL.md
Following the old instructions I was getting this warning:
```
CMake Warning:
Manually-specified variables were not used by the project:
BUILD_TYPE
```
Based on [this comment](https://github.com/CGAL/cgal/issues/39#issuecomment-90476304) I was able to determine the correct value.
Since we're giving directions for creating a release build it probably makes sense to put it in a directory named `release` rather than `debug`.
=> git based installation instructions use incorrect variable name

CGAL_ImageIO/demo/CGALimageIO/CMakeLists.txt, CGAL_ImageIO/demo/CGALimageIO/image_to_vtk_viewer.cpp, CGAL_ImageIO/include/CGAL/Image_3_vtk_interface.h, CGAL_ImageIO/src/CGAL_ImageIO/CMakeLists.txt, CGAL_ImageIO/src/CGAL_ImageIO/Image_3.cpp, Surface_mesher/demo/Surface_mesher/volume.cpp, Surface_mesher/demo/Surface_mesher/volume.h
The VTK support in CGAL_ImageIO is not documented, but some users/customers actually use it.
Since VTK 6, that support was broken. With this pull-request, the support of VTK<6.0 is dropped in favor of 6.0 and later.
=> Update the CGAL_ImageIO-VTK support to VTK 6.x

Number_types/include/CGAL/sse2.h
__GNUC__ is missing its 'C'. This probably makes the test for __MINGW64__ useless. (I am testing the github interface for minor edits)
=> Typo in sse2.h

Installation/changes.html, Polyhedron/demo/Polyhedron/Polyhedron_demo_scale_space_reconstruction_plugin.cpp, Polyhedron/demo/Polyhedron/cgal_test_with_cmake
Only insert used points for polygon soups (speed-up and cleaner way of instanciating polygon soup).
Tested in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-64.shtml
=> Polyhedron demo scale space plugin speedup sgiraudot

Triangulation/include/CGAL/Triangulation_full_cell.h, Triangulation/include/CGAL/Triangulation_vertex.h
Avoid linking errors such as:
In function 'CGAL::operator>>(std::istream&,
CGAL::No_vertex_data&)':MeshSimplicial.cpp:(.text+0x490): multiple
definition of 'CGAL::operator>>(std::istream&, CGAL::No_vertex_data&)'
=> dD Triangulation: Make non-template methods inline

Combinatorial_map/doc/Combinatorial_map/Concepts/CombinatorialMap.h, Combinatorial_map/include/CGAL/Combinatorial_map.h, Combinatorial_map/test/Combinatorial_map/Combinatorial_map_2_test.h, Linear_cell_complex/test/Linear_cell_complex/Linear_cell_complex_2_test.h, STL_Extension/doc/STL_Extension/CGAL/Compact_container.h, STL_Extension/doc/STL_Extension/CGAL/Concurrent_compact_container.h, STL_Extension/include/CGAL/Compact_container.h, STL_Extension/include/CGAL/Concurrent_compact_container.h
Add is_used(const_iterator pos) functions in compact container and in concurrent compact container.
Comment two assertions, allowing to increment/decrement iterators on removed elements.
Small feature https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_is_used_handle
Tested in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-65.shtml
=> Add Compact_container::is_used(Handle)

Number_types/include/CGAL/Mpzf.h
The subject said it all... Well, I will develop anyway.
The [testsuite of CGAL, with clang-3.6,][t] is full of that warning (in the two columns `ArchLinux-clang`):
[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-85.shtml
```
/mnt/testsuite/include/CGAL/Mpzf.h:421:5: warning: unused typedef 'boost_static_assert_typedef_421' [-Wunused-local-typedef]
BOOST_STATIC_ASSERT(GMP_NUMB_BITS == 64);
^
/usr/include/boost/static_assert.hpp:170:16: note: expanded from macro 'BOOST_STATIC_ASSERT'
BOOST_JOIN(boost_static_assert_typedef_, __LINE__) BOOST_STATIC_ASSERT_UNUSED_ATTRIBUTE
^
/usr/include/boost/config/suffix.hpp:544:28: note: expanded from macro 'BOOST_JOIN'
#define BOOST_JOIN( X, Y ) BOOST_DO_JOIN( X, Y )
^
/usr/include/boost/config/suffix.hpp:545:31: note: expanded …
```
=> Add pragmas in clang to disable -Wunused-local-typedef, locally

Kinetic_data_structures/include/CGAL/Polynomial/CORE_Expr_root_stack.h, Kinetic_data_structures/include/CGAL/Polynomial/internal/CORE_polynomial.h
When including CGAL/Polynomial/CORE_Expr_root_stack.h in a header file
that in turn gets included in multiple .cpp files, code from
CORE_Expr_root_stack.h ends up in multiple object files and causes
linking problems:
multiple definition of `CGAL::POLYNOMIAL::operator<<(std::ostream&, CGAL::POLYNOMIAL::CORE_Expr_root_stack const&)'
multiple definition of `CGAL::POLYNOMIAL::internal::operator*(CORE::BigRat const&, CGAL::POLYNOMIAL::internal::CORE_polynomial const&)'
Work around this issue by declaring both operators inline.
=> Fix linking issue caused by violation of the one definition rule.

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h
Sometimes property maps don't have the operator[] available, so we need to use get() and put() everywhere.
This pull request fixes that in the Polygon_mesh_processing package.
This pull request also contains a documentation fix.
=> Polygon mesh processing - small fixes

Installation/CMakeLists.txt
That is temporary. See issue #189
=> Remove the warning about CMP0054

BGL/include/CGAL/boost/graph/properties_Surface_mesh.h, BGL/test/BGL/test_Euler_operations.cpp, BGL/test/BGL/test_Prefix.h, Surface_mesh/include/CGAL/Surface_mesh.h, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh_fwd.h
Boost.Fusion only improves the code marginally and comes with a large number of includes. Remove it and clean up some other, unrelated includes.
=> Drop Boost.Fusion from Surface_mesh

AABB_tree/demo/AABB_tree/AABB_demo.cpp, Alpha_shapes_3/demo/Alpha_shapes_3/Alpha_shape_3.cpp, Circular_kernel_3/demo/Circular_kernel_3/Circular_kernel_3.cpp, Linear_cell_complex/demo/Linear_cell_complex/Linear_cell_complex_3_demo.cpp, Mesh_3/demo/Mesh_3/Mesh_3.cpp, Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/Periodic_Lloyd_3.cpp, Polyhedron/demo/Polyhedron/Polyhedron_3.cpp, Triangulation_3/demo/Triangulation_3/T3_demo.cpp
`Qt::AA_UseDesktopOpenGL` is usable from Qt-5.3 only. With that patch we should be able to support Qt-5.2 (default for current latest Ubuntu version).
See CGAL/cgal-testsuite-dockerfiles#23
=> Support Qt-5.2

GraphicsView/src/CGAL_Qt5/CMakeLists.txt
Numerous alpha testers have complained about not knowing what Qt5 components are required. Improve the message and up the code quality a little.
=> Provide a better dependency check in GraphicsView

Cartesian_kernel/include/CGAL/Cartesian/Point_3.h, Kernel_23/include/CGAL/Point_3.h, Kernel_23/test/Kernel_23/issue_129.cpp
Add a testcase for #129 and fix it by making PointC3::FT public. Tested against clang 3.6.2.
=> Stop-gap solution for issue #129

Arrangement_on_surface_2/include/CGAL/Arr_polyline_traits_2.h
With gcc and -Wextra :
../CGAL/Arr_polyline_traits_2.h:2775: warning: enumeral and
non-enumeral type in conditional expression
../CGAL/Arr_polyline_traits_2.h:1596: warning: enumeral and
non-enumeral type in conditional expression
../CGAL/Arr_polyline_traits_2.h:1618: warning: enumeral and
non-enumeral type in conditional expression
=> Fix a warning in Arr_2 (version CGAL-4.6)

Jet_fitting_3/include/CGAL/Monge_via_jet_fitting.h
Speed up computation of Jet Fitting:
- `std::pow` is called on `int` instead of `double`
- `CGAL::orientation` is used to replace a call to linear_algebra
=> Jet fitting enhancement

Polyhedron/demo/Polyhedron/resources/shader_with_texture.f, Polyhedron/demo/Polyhedron/resources/shader_with_textured_edges.f
- Use texture2D instead of texture in the shaders to have it in glsl 1.2 and not 1.3. This should fix #308
=> Polyhedron demo, fix the use of texture2D in a shader

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
This enables the reset to work after a coloration per connected component
=> be more permissive for color reset

Filtered_kernel/include/CGAL/internal/Static_filters/Equal_3.h
Equal_3::operator()(Vector_3,Vector_3) will have a "static filter". That will remove the dynamic filtering using `Interval_nt`.
=> No need for a filtered predicate for Equal_3()(Vector_3, Vector_3)

Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h, Polyhedron/demo/Polyhedron/Polyhedron_demo_stl_plugin.cpp
In the polyhedron demo, before loading a stl file as a polyhedron, check whether it fits in a polyhedron
=> Polyhedron demo: first check that the STL file is a polygon mesh before loading it

CGAL_ipelets/include/CGAL/CGAL_Ipelet_base_v7.h
When CGAL_assertion is defined to the empty macro, then the variable
'ok' triggers a warning:
```
include/CGAL/CGAL_Ipelet_base_v7.h:848:14: warning: variable 'ok' set but not used [-Wunused-but-set-variable]
bool ok=true;
^
```
See for example
https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-136/CGAL_ipelets_Demo/TestReport_lrineau_x86-64_Linux-Fedora19_g++-4.8_Release.gz
Related to the merge PR #297.
=> Fix warning, after the replacement assert/CGAL_assertion

Installation/cmake/modules/FindTBB.cmake
msvc12 (2013) now handled
until now, msvc14 (2015) is not supported by TBB (<= 4.4)
this commit prevents the testsuite from looking for it and then trying to use if it automatically finds some version of TBB on the computer
=> FindTBB : deal with msvc12 and msvc14

Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h
- The test to detect the non manifold edges was wrong. It had an unnecessary condition.
- The function that fills the list of non manifold edges was not called anymore. It is
now called in compute_normals_and_vertices().
- I added the necessary code to display the non manifold edges.
This should fix #314
=> Polyhedron demo: fix display of non-manifold edges in polygon soup items

Polyhedron/demo/Polyhedron/Scene_combinatorial_map_item.cpp, Polyhedron/demo/Polyhedron/Scene_combinatorial_map_item.h, Polyhedron/demo/Polyhedron/Scene_edit_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_edit_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_transform_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_transform_item.h, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.h, Polyhedron/demo/Polyhedron/Scene_textured_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_textured_polyhedron_item.h
This should lower the RAM consumption for big items.
=> Polyhedron demo: save memory by clearing the vectors after they are sent to OpenGL

Triangulation_2/benchmark/Triangulation_2/Delaunay_remove.cpp, Triangulation_2/include/CGAL/Triangulation_2.h
Avoiding copies of lists makes `Delaunay_2::remove(Vertex_handle)`  considerably faster.
@janetournois   Can you please double check that my changes are correct (testsuite passes locally)
=> Triangulation_2: speed up fill_hole_delaunay()

BGL/doc/BGL/PackageDescription.txt, BGL/include/CGAL/boost/graph/Euler_operations.h, BGL/include/CGAL/boost/graph/iterator.h
* add missing iterator doc (function documented but not the iterator type)
* add missing entries in the classified reference manual
* hide deprecated function from doxygen
=> fix doc issues

Polyhedron/demo/Polyhedron/Polyhedron_demo_orient_soup_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_scale_space_reconstruction_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h
This pull request is a fix for a bug in the Polyhedron demo introduced with the fix for display manifold edges.
- fill_edges was called in a loop on the edges, which made the loading of big items extremely slow.
- fill_edges is now only called in compute_normals, when it was called several times when creating or converting a polygon_soup
- compute_normals_and_vertices is now const and called with initialized_buffers in the draw functions, which allows to reduce
the number of times it is called, in Scene_polygon_soup_item and in Scene_polyhedron_item.
=> Fix polygon_soup and optimize loading time

BGL/include/CGAL/boost/graph/graph_traits_PolyMesh_ArrayKernelT.h
I didn't merge it in integration.
I just realize that the branch name has nothing to do with Advancing Front Reconstruction
as it concerns the boost_graph_traits for OpenMesh.
=> set_halfedge(..) was called twice

Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h
Simon and I tested the reconstruction algorithm on several user data sets and only observed better results.  
The error makes that there is only an orange and red wedge, and that consequently only the criterium for faces in the orange wedge is applied.
=> acos makes that the green wedge in the user manual has an aperture of 0

Polyhedron/demo/Polyhedron/Polyhedron_demo_off_plugin.cpp
- Makes the WaitCursor disappear when the message "isolated vertices ignored" pops up,
so  that the user doesn't think something is still loading when it's not.
=> Polyhedron demo: WaitCursor fix in the OFF plugin.

Polygon_mesh_processing/examples/Polygon_mesh_processing/triangulate_faces_example.cpp, Polygon_mesh_processing/examples/Polygon_mesh_processing/triangulate_faces_example_OM.cpp
This is necessary, as faces are deleted and new faces created,
and as in OpenMesh deleted faces are not reused.
I at the same time, un-hardwired the output filename
=> Call openmesh.garbage_collection() before writing after triangulate_holes()

Polyhedron/demo/Polyhedron/CMakeLists.txt
That CMakeLists.txt was still using the old API of FindQt4.cmake. Since
then, we have switched to CMake>=2.8.11 and Qt5. Thus:
- Remove the uses of variables `QT_USE_QTXML` and similar.
- Remove the uses of `target_link_libraries(... ${QT_QTGUI_LIBRARY})`,
that is replaced by the function `qt5_use_modules`.
- Remove last occurrences of GLEW.
- The Qt5 ScriptTools module is an optional
component (`OPTIONAL_COMPONENTS`). And it is used only if the option
`POLYHEDRON_QTSCRIPT_DEBUGGER` is enabled.
=> Polyhedron demo: cleanup the CMakeLists.txt

Arrangement_on_surface_2/include/CGAL/Arr_dcel_base.h, Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_impl.h, Arrangement_on_surface_2/include/CGAL/Arrangement_on_surface_2.h, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_removal.cpp
This comes to optimize the following:
1. Moving all inner ccbs from one face to another, and
2. moving all isolated vertices from one face to another.
The above may take place when an edge incident to two different faces is removed; as a consequence all inner ccbs and all isolated vertices, if exist, need to be moved from one face to the other.
The inner ccbs and isolated vertices are maintained in linked lists.
Before the introduction of this optimization, the above was done one at a time for each inner ccb (resp. for each isolated vertex).
This optimization utilizes the splice() operation of a list, essentially, applying the move in an agregated fashion.
Test suit of the arrangement completes successfully locally,
=> Aos ccb removal optimization efif

Polyhedron/demo/Polyhedron/Polyhedron_demo_join_and_split_polyhedra_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_mean_curvature_flow_skeleton_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_mesh_segmentation_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_edit_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Corrected a bug in edit polyhedron with the Spheres that were not displayed.
- Added a boolean member to scene_item determining if the color should be handled by
a single value, which avoids having to re-compute the color of each vertex when
the color is changed through the UI, or by the buffers (only for certain plugins).
=> Optimazing color handling

Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h, Intersections_2/include/CGAL/Intersection_traits.h, Intersections_3/include/CGAL/Intersections_3/intersection_3_1_impl.h, Kernel_23/doc/Kernel_23/CGAL/intersections.h, Kernel_23/doc/Kernel_23/examples.txt, Kernel_23/examples/Kernel_23/intersection_get.cpp, Kernel_23/examples/Kernel_23/intersection_visitor.cpp, Kernel_23/examples/Kernel_23/intersections.cpp, STL_Extension/doc/STL_Extension/CGAL/iterator.h, STL_Extension/include/CGAL/iterator.h
This  at the same time fixes bugs as the examples where not 100 correct.
I have merged it into integration.
=> Convert <code> sections into cgalExamples

Polyhedron/demo/Polyhedron/GlSplat/Shader.cpp, Polyhedron/demo/Polyhedron/GlSplat/shaders/Finalization.glsl
- Moved an extension declaration at the beginning of the shader, before the
#define are added. The problem is that it enables the extension for splatting
shaders that don't require it, but I don't think it is really bad.
=> Splat Fix for mesa

Spatial_searching/examples/Spatial_searching/CMakeLists.txt, Spatial_searching/examples/Spatial_searching/searching_polyhedron_vertices_with_fuzzy_sphere.cpp, Spatial_searching/include/CGAL/Fuzzy_sphere.h
when both types `SearchTraits::Point_d` and `Base_traits::Point_d` are the same, both constructors are the same, leading to a compilation error
adding `boost::disable_if` solves this issue
=> Spatial_searching : fix Fuzzy_sphere constructors

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
The option "Show only feature edges" was no longer working. It seems that `invalidate_buffers()` must be called.
=> Fix Scene_polyhedron_item::show_only_feature_edges

Convex_hull_d/include/CGAL/Delaunay_d.h, Kinetic_data_structures/include/CGAL/Kinetic/Regular_triangulation_3.h
In KDS as well as Convex_hull_d I added   `CGAL_assertion_code( T v; )` so that we don't get a warning in a `CGAL_assertion(v ==.. )`
=> Use CGAL_assertion_code() to avoid warnings

Mesh_3/demo/Mesh_3/StdAfx.h
Bug fix: StdAfx.h is used for MSVC precompiled headers.
=> cstddef.hpp does not exist anymore in latest versions of Boost

Polyhedron/demo/Polyhedron/Viewer.cpp
- The axis system was representing the rotation of the camera, which was not
very clear. It now represents the mvp matrix, without the translation part
which is less disturbing.
=> Polyhedron demo: fix the display of axis

Polyhedron/demo/Polyhedron/Camera_positions_list.cpp, Polyhedron/demo/Polyhedron/Camera_positions_list.ui
- The preset camera positions are now centered on the revolveAroundPoint of
the camera, which makes it right when the item is not centered in the scene.
=> Polyhedron demo: fix camera presets

Polyhedron/demo/Polyhedron/Polyhedron_demo_trivial_plugin.cpp, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene_plane_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
- Using tools like the selection tool creates items that make the scene
re-center, and this can be annoying. To avoid that, I changed the default BBox
of those items from BBox(), which is (0,0,0,1,1,1) to scene->bbox() for
most of the cases. This way the scene bbox does not change and you don't
lose your position when they are added.
=> Default BBox returning changed for someitems

Number_types/include/CGAL/Test/test_root_of_traits.h
On Linux, 32 bits, the x87 Intel FPU can cause extended precision for
doubles. That complicates the comparison of double values that should be
equal.
I use the `CGAL_IA_FORCE_TO_DOUBLE` to force the non-extended double
precision for every value, even intermediate ones.
=> [32 bits] Fix test/Number_types/Root_of_traits

Polyhedron/demo/Polyhedron/Polyhedron_demo_cut_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_mesh_3_plugin_cgal_code.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_trivial_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_shortest_path_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_shortest_path_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_transform_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_transform_item.h, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.h, Polyhedron/demo/Polyhedron/Scene_textured_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_textured_polyhedron_item.h
- Some items called `compute_normals_and_vertices` several times in a row. The fact that they don't anymore makes the loading of OFF files almost twice faster.
=> OFF loading fix

Polyhedron/demo/Polyhedron/CGAL_demo/Viewer_interface.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h, Polyhedron/demo/Polyhedron/Viewer.cpp
- When a selection item is selected, shift+left click does not call information requests
for the selected point anymore. It makes the selection tool faster by far.
=> Mouse binding modification

Surface_mesher/demo/Surface_mesher/CMakeLists.txt, Surface_mesher/demo/Surface_mesher/VTK/CMakeLists.txt, Surface_mesher/demo/Surface_mesher/VTK/mesh_a_3D_image.cpp, Surface_mesher/demo/Surface_mesher/mainwindow.cpp, Surface_mesher/demo/Surface_mesher/mainwindow.h, Surface_mesher/demo/Surface_mesher/ui/mainwindow.ui, Surface_mesher/include/CGAL/IO/Complex_2_in_triangulation_3_to_vtk.h
This PR updates the CMakeLists to handle recent (>= 6.0) versions of vtk, and update Surface_mesher/demo/Surface_mesher/VTK examples to Qt5 and VTK6.
Also add a menu to the Surface_mesher demo to open a directory (previously one could only open a directory with drag-and-drop)
=> Surface mesher - Improve support of vtk files as input

Mesh_3/demo/Mesh_3/Volume_plane_intersection.cpp, Mesh_3/demo/Mesh_3/Volume_planes_plugin.cpp
Add casts to suppress warnings (not seen in the tessuite as too many 'R's)
=> Directly test against _MSC_VER to suppress a warning

Mesh_3/include/CGAL/internal/Mesh_3/check_weights.h, Mesh_3/include/CGAL/lloyd_optimize_mesh_3.h, Mesh_3/include/CGAL/odt_optimize_mesh_3.h, Mesh_3/include/CGAL/perturb_mesh_3.h
This precondition checks that global optimizers are not run on a triangulation with weights.
Running global optimizers on a triangulation with weights is not recomended. The behaviour is unknown and it usually leads to a crash.
Protecting balls are an exception and don't prevent global optimizers from running.
exude_mesh_3 is not concerned by this PR, since it's precisely its job to deal with weights.
=> Mesh_3 - add a precondition to global optimizers

Polyhedron/demo/Polyhedron/MainWindow.cpp
- Operations is now part of the item menu, so the first menu does not exists anymore.
It is quicker to get to an action.
=> Contextual menu changed

Polyhedron/demo/Polyhedron/Polyhedron_demo_mean_curvature_flow_skeleton_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_normal_estimation_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_point_inside_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_point_set_outliers_removal_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_point_set_selection_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_point_set_shape_detection_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_point_set_simplification_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_point_set_upsampling_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/include/Point_set_3.h, Polyhedron/demo/Polyhedron/include/UI_point_3.h
Change how selection is handled in Polyhedron point sets:
* _Current behavior_: each point object embeds a boolean __m_is_selected__
* _Proposed behavior_: a single iterator __m_first_selected__ for the point set object (=end() if nothing is selected) with reordering for selection
This is much more efficient in terms of storage and also of time for some common operations (__select_all__, __unselect_all__, __remove_selection__, etc. are done in constant time instead of linear time). In addition, the selection is mostly used by __Point_set_processing_3__ algorithms which change the order of the point set and return an iterator to the first point to remove (for example), so this is more consistent and more direct to use.
All related functions (in display, items and plugins) have been updated …
=> Polyhedron demo - Enhance selected points

Triangulation_3/include/CGAL/Delaunay_triangulation_3.h
This pull request enables parallel insertion for vertices with info.
It uses the same approach as the regular `insert` method, 
with some minor adaptions to add the attached info.
It uses a new `Insert_point_with_info` functor, which is also identical to the regular `Insert_point` functor, but with some additional data members to attach the info properly.
=> Enable parallel insertion of points with info

Polyhedron/demo/Polyhedron/Scene_edit_polyhedron_item.cpp
- When validating an edition of mesh, all the items of the scene became invisible.
This came from a setVisible(false) in the scene_polyhedron_edit_item's destructor
that was put there to fix a segfault taht has disappeared since.
- When validating an edition, the modifications were not displayed on the
polyhedron_item. This was because an invalidate_buffers() that was lacking.
=> Mesh edition fix

Polyhedron/demo/Polyhedron/Polyhedron_demo_convex_hull_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_corefinement_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_cut_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_edit_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_fairing_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_hole_filling_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_inside_out_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_intersection_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_jet_fitting_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_join_and_split_polyhedra_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_mean_curvature_flow_skeleton_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_mesh_3_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_mesh_segmentation_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_mesh_simplification_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_nef_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_orient_soup_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_parameterization_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_pca_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_point_inside_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_polyhedron_slicer_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_polyhedron_stitching_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_remeshing_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_self_intersection_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_shortest_path_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_subdivision_methods_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_triangulate_facets_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_trivial_plugin.cpp
Thanks to the new framework for sorting operations into subdirectories in the Polyhedron demo, we can produce a nicer layout of the list of available operations for each type of item.
After a local discussion at GF, I've decided to put every action in an "actions folder" that has the name of the corresponding CGAL package.
It is not absolutely perfect, because 
- some directories contain only one operation (which could easily be avoided by not creating this directory)
- some directories are big (nothing compared to how it was before)
but
- the "one operation directories" could/would easily be filled with operations available in the package
- it is easy for a developer to decide where to put his new operation : in the directory that has the same name as its corresponding package
- it is …
=> Polyhedron demo : sort operations by package

CGAL_ImageIO/include/CGAL/Image_3_impl.h, Combinatorial_map/include/CGAL/Combinatorial_map_save_load.h, Kinetic_data_structures/include/CGAL/Polynomial/internal/macros.h, Number_types/include/CGAL/Test/test_root_of_traits.h, Scale_space_reconstruction_3/include/CGAL/Scale_space_reconstruction_3/Scale_space_surface_reconstruction_3_impl.h
This is a fix for #295 
Replaces assert() by CGAL_assertion() in the non-test header files, and CGAL_assertion() by assert in test header files.
=> Cgal assert fix gf

Polyhedron/demo/Polyhedron/Polyhedron_demo_xyz_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h
Move the include of the UI file of statistics_on_polyhedron from _Scene_polyhedron_item.h_ to _Scene_polyhedron_item.cpp_ (this caused the bug https://github.com/CGAL/cgal/issues/438 when plugins were including the polyhedron item header).
Also remove some useless includes in _xyz_plugin_.
=> Polyhedron demo: Bugfix (missing UI include)

Polyhedron/demo/Polyhedron/Scene_polyhedron_item_k_ring_selection.h
- No more need to move the mouse to select a facet
- shift + right click doesn't block the shift_pressed state anymore.
=> Left click fix

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Triangulate_hole_polyline.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Hole_filling/Weights.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/refine_impl.h, Polygon_mesh_processing/test/Polygon_mesh_processing/triangulate_hole_Polyhedron_3_no_delaunay_test.cpp, Polygon_mesh_processing/test/Polygon_mesh_processing/triangulate_hole_Polyhedron_3_test.cpp
This is a fix for #436 
- replaces all the std::sqrt by CGAL::sqrt
=> Fix for std::sqrt in Mesh_processing

Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
New selection behavior in Polyhedron demo and PLY reader were developed in parallel branches and new selection behavior was not taken into account when merging PLY reader.
When reading a point set, _m_points->unselect_all()_ must be called (otherwise the selection iterator is undefined, causing a segfault). This was done for _off_ and _xyz_, this branch adds it to the _ply_ reader.
=> Bugfix: unselect all points when reading PLY files

CGAL_Core/include/CGAL/CORE/CoreDefs.h
This was a typo introduced by the header-only branch.
=> Fix warnings: use CGAL_CORE_EXPORT instead of CGAL_EXPORT

Polyhedron/demo/Polyhedron/CMakeLists.txt, Polyhedron/demo/Polyhedron/Polyhedron_demo_point_set_shape_detection_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo_point_set_shape_detection_plugin.ui
Additional option for the _point_set_shape_detection plugin_: for a plane, construct alpha shape of the points projected on the detected plane (stored in the form of a _Scene_polyhedron_item_). This is how RANSAC plane detection results are commonly displayed in literature.
This has not been tested yet (merged on _integration_ today).
=> Polyhedron demo: Enhance RANSAC display

Polyhedron/demo/Polyhedron/Scene_combinatorial_map_item.cpp, Polyhedron/demo/Polyhedron/Scene_combinatorial_map_item.h, Polyhedron/demo/Polyhedron/Scene_edit_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_edit_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_implicit_function_item.cpp, Polyhedron/demo/Polyhedron/Scene_implicit_function_item.h, Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_plane_item.cpp, Polyhedron/demo/Polyhedron/Scene_plane_item.h, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_shortest_path_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_shortest_path_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_transform_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_transform_item.h, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.h, Polyhedron/demo/Polyhedron/Scene_textured_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_textured_polyhedron_item.h, Polyhedron/demo/Polyhedron/resources/shader_with_light.f, Polyhedron/demo/Polyhedron/resources/shader_without_light.f
This is a fix for #449 
- Reduces the number of VBOs in the items
- Fixes a problem in the demo for the non triangulated items.
=> Polyhedron demo: optimisation for VBOs/VBAs

Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h, Mesh_3/include/CGAL/Mesh_domain_with_polyline_features_3.h
The Mesh_3 polylines protection algorithm incrementally inserts weighted points on input feature polylines. This PR deals with the limit case where protecting balls refinement attempts to insert a protecting ball very close (~10^-18) beyond the "endpoint/starting point" (arbitrarily chosen) of a cyclic polyline.
this PR fixes issue #416
=> Mesh 3 : fix limit case in polylines protection

Polyhedron/demo/Polyhedron/CMakeLists.txt, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
- The scene_c3t3_item now uses Enums for its VBOS and VAOs.
=> C3t3_item update

Arrangement_on_surface_2/include/CGAL/graph_traits_Arrangement_2.h, Arrangement_on_surface_2/include/CGAL/graph_traits_Dual_Arrangement_2.h, BGL/include/CGAL/boost/graph/dijkstra_shortest_paths.h, BGL/include/CGAL/boost/graph/graph_traits_Arrangement_2.h, BGL/include/CGAL/boost/graph/graph_traits_CombinatorialMap.h, BGL/include/CGAL/boost/graph/graph_traits_Delaunay_triangulation_2.h, BGL/include/CGAL/boost/graph/graph_traits_HalfedgeDS.h, BGL/include/CGAL/boost/graph/graph_traits_PolyMesh_ArrayKernelT.h, BGL/include/CGAL/boost/graph/graph_traits_Surface_mesh.h, BGL/include/CGAL/boost/graph/graph_traits_Triangulation_2.h, BGL/include/CGAL/boost/graph/named_function_params.h, Installation/include/CGAL/config.h, Mesh_2/include/CGAL/lloyd_optimize_mesh_2.h, Mesh_3/include/CGAL/Mesh_3/global_parameters.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h, Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/Alpha_expansion_graph_cut.h
It is a justified warning according to [connect.microsoft.com](https://connect.microsoft.com/VisualStudio/feedback/details/1425276/false-positive-error-c4172-returning-address-of-local-variable-or-temporary)
We push it away so that we only see CGAL related warnings in our testsuite.
=> suppress warning in boost as this has to be solved upstream

Operations_on_polyhedra/include/CGAL/intersection_of_Polyhedra_3_refinement_visitor.h, Polyhedron/demo/Polyhedron/Polyhedron_demo_point_set_shape_detection_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_combinatorial_map_item.cpp, Polyhedron/demo/Polyhedron/Scene_implicit_function_item.cpp, Polyhedron/demo/Polyhedron/include/Point_set_3.h
This PR intends to fix warnings spotted by MSVC2013 about implicit conversions between float and double, and between int and std::size_t (possible loss of data)
=> Polyhedron demo : fix conversion warnings

BGL/include/CGAL/boost/graph/iterator.h, BGL/test/BGL/test_circulator.cpp
As we want to circulate around the source, and as the implementation uses an around_target ciculator, we have to take the opposite input halfedge.
We fixed the bug and improved the testsuite.
=> Fix bug  in Halfedge_around_source_circulator

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/remesh_impl.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h, Polyhedron/demo/Polyhedron/Polyhedron_type.h
This PR fixes a bug in isotropic_remeshing, that could happen for some parameters when the surface patch to be remeshed was "thinner" (in terms of width in number of edges) than the target edge length.
=> PMP : fix a bug in isotropic remeshing

Point_set_processing_3/include/CGAL/IO/read_off_points.h
This PR addresses the following issue: https://github.com/CGAL/cgal/issues/515
Tested on some OFF files with comments. OFF files without comments are not affected.
=> Bugfix: OFF reader should accept comments and empty lines

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp
- remove two unused #include of `MainWindow.h`
- improve the restoring of dock widgets states, for dock widgets created by plugins.
=> Polyhedron demo: minor improvements

Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.ui
In the surface reconstruction plugin of the Polyhedron demo, only default parameters can be used for _advancing front_. This PR adds the two parameters (radius ratio bound and beta angle) to the dialog so that they can be user selected.
=> Add parameters to surface reconstruction plugin

Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_upsampling_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/include/Point_set_3.h
The new selection behavior introduced by PR https://github.com/CGAL/cgal/pull/410 uses an iterator to the first selected point. This forces the user to call _unselect_all()_ after inserting points so that the iterator remains valid. I forgot to change this behavior in some plugins, which resulted for example in this bug: https://github.com/CGAL/cgal/pull/455
I found out there are other similar bugs remaining (WLOP plugin or Polyhedron selection when creating a point set from selected vertices).
This PR fixes all these bugs by introducing a slight change of behavior: the point set now stores the _number_ of selected points. The correct iterator is recomputed when needed (the container is a vector so this is straightforward). This behavior is more robust as the user does not need to call …
=> Polyhedron demo: Fix point selection behavior

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_3.qrc, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.h, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/resources/shader_no_light_no_selection.f, Three/include/CGAL/Three/Scene_item.h, Three/include/CGAL/Three/Viewer_interface.h
- This PR fixes a color problem with the selection tool, and some warnings about Signals/Slots. There is currently a segfault remaining when trying to create a points set from a selection, but it should be solved by another PR(#498) from @sgiraudot
=> Selection tool : colors fix

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item_k_ring_selection.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
This PR is a fix for the Selection_plugin.
At some point the poly_item was updated along with the selection_item, which caused it to be re-computed when it should not.
=> Fix for the selection tool

Surface_modeling/include/CGAL/Surface_mesh_deformation.h
this makes sure that the control vertices are at the expected position
=> <CGAL/Surface_mesh_deformation.h>: do not update coordinates of control vertices

Polyhedron/demo/Polyhedron/MainWindow.cpp
This PR fixes the error message when loading an external plugin.
- Use a QFileInfo to get only the plugin name without its path.
=> External plugin loading fix

Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
In Polyhedron demo, when orienting a polygon soup, an additional test is performed to check if the resulting polyhedron is outward oriented: this should not be done if the polyhedron is not closed as it violates the precondition (and can lead to crashes).
=> Bugfix: Only check orientation of polyhedron if it is closed

Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h
Using Shift+wheel adjusts the zNear plane in the Frustum
=> Adjusting zNear with wheel and shift

Installation/include/CGAL/config.h, Mesh_2/include/CGAL/lloyd_optimize_mesh_2.h, Mesh_3/demo/Mesh_3/C3t3_type.h, Mesh_3/demo/Mesh_3/Mesh_3_plugin.cpp, Mesh_3/include/CGAL/Mesh_3/global_parameters.h, Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h, Polyhedron/demo/Polyhedron/C3t3_type.h
Instead of  setting it globally in include/CGAL/config.h   we set the value in the header files of Mesh_2 and Mesh_3.
=> Set BOOST_PARAMETER_MAX_ARITY only in the packages concerned

Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Mesh_3_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
This PR restores the multicolor aspect of the c3t3 items and smoothes the plane movements by using a timerEvent to avoid flooding events.
=> Polyhedron demo mesh 3 plugin fix and enhancement

Polyhedron/demo/Polyhedron/Scene.cpp
This PR fixes two bugs introduced by the hierarchic view:
- The selection tool stoped working because the signal newItem(int) was not called anymore
- The polylines from the Point_set_Selection_tool were not erased correctly
=> Polyhedron demo fixes for hierarchic bugs gf

Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h
When computing the priority of a facet in the _advancing front surface reconstruction_ algorithm, a test is performed to check if the facet forms a sliver with the surface (red wedge on [this figure](http://doc.cgal.org/4.7/Advancing_front_surface_reconstruction/index.html#title2)).
Currently, this test is only performed for the first and last facet visited around the current facet: although it is true that the chances of finding a sliver are higher when checking at the closest neighbors of the current facet, some other facets can form slivers too. Experimentally, this produced indeed slivers and badly shaped surfaces on some point sets (with double coverage in some parts).
It is unclear to me why this was done in the first place:
* Most probably for speed enhancement, but I can't imagine …
=> Bugfix: always check if facet is sliver

Polyhedron/demo/Polyhedron/Plugins/Surface_modeling/Edit_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_modeling/Scene_edit_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_modeling/Scene_edit_polyhedron_item.h
This PR introduces some bug fixes for mesh editing and remeshing in the Polyhedron demo :
- face_index map to be properly initialized before calling isotropic remeshing
this is needed by border_halfedges_impl
- display of the plane that constrains deformation has been fixed
- fix selection tool which was selecting only vertices
=> Polyhedron demo : fix deformation and remeshing

Polyhedron/demo/Polyhedron/Plugins/PMP/Point_inside_polyhedron_plugin.cpp
This fixes the bug https://github.com/CGAL/cgal/issues/552: I forgot to change the change of behavior of point set selection (https://github.com/CGAL/cgal/pull/410) to this plugin.
=> Bugfix: correct point set selection handling for point_inside_polyhedron

CGAL_ImageIO/src/CGAL_ImageIO/convert_impl.h, CGAL_ImageIO/src/CGAL_ImageIO/gif_impl.h, CGAL_ImageIO/src/CGAL_ImageIO/recbuffer_impl.h, CGAL_ImageIO/src/CGAL_ImageIO/recline_impl.h, CGAL_ImageIO/src/CGAL_ImageIO/reech4x4_impl.h, Circular_kernel_2/benchmark/parser/benchmark_lexer.cpp, Circular_kernel_2/benchmark/parser/benchmark_parser.cpp, Convex_hull_d/include/CGAL/Delaunay_d.h, Kinetic_data_structures/include/CGAL/Polynomial/internal/Turkowski_numeric_solvers_impl.h, Nef_S2/include/CGAL/Nef_S2/Sphere_geometry_OGL.h, Nef_S2/include/CGAL/Nef_S2/sphere_predicates.h, Surface_mesh_segmentation/include/CGAL/internal/auxiliary/graph.h
The keyword _register_ is deprecated since c++11 (and anyway probably not really useful as recent compiler know better than the user how to use the registers...). There are some in CGAL, raising lots of warnings in the testsuite.
This PR removes all the occurrences of _register_ in CGAL.
=> Remove deprecated "register" keyword

Cartesian_kernel/include/CGAL/Cartesian/Line_3.h
Bugfix for the following issues: https://github.com/CGAL/cgal/issues/49 and https://github.com/CGAL/cgal/issues/343
It turns out that in recent versions of C++ (c++11 and c++14), a pair cannot be instantiated on incomplete types. Therefore, using a pair of _Point_3_ would not compile for the following reason:
* _Point_3_ is based on _Vector_3_
* _Vector_3_ has a constructor taking a _Line_3_ as an argument
* Because of the new behavior of pair, all methods of _Vector_3_ are checked, including this constructor
* _Line_3_ is using a _std::pair_ of _Point_3_ and _Vector_3_, resulting in a loop and a compilation error
This bug is fixed by replacing the pair inside _Line_3_ by an internal _struct_ reproducing the same behavior as _std::pair_. This has been tested in …
=> Bugfix: pair not compatible with Point_3 (clang)

Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
This pull-request:
- fixes a display bug (display of balls: the display was corrupted, 78fe4f9) ,
- improves the efficiency of the display of balls: skip degenerated balls (3b8d7a0),
- tries to improve the buggy indentation (f1ce747),
- fix a bug (reset the cut plane in the constructor) (89bae41).
=> Polyhedron demo: fix the display of protecting balls in Scene_c3t3_item

Arrangement_on_surface_2/include/CGAL/Arr_point_location/Trapezoidal_decomposition_2_impl.h
A dag node contains a variant that amongst other can point onto a
Tr_active_trapezoid. This class inherits from Handle in order to
reference count the data (of type Tr_active_trapezoid::Data) that
contains 4 neightbors, each being of type Tr_active_trapezoid.
The problem is that if a dag node is no longer used and if it
holds a instance of a Tr_active_trapezoid which neighbors trapezoid
are not cleared, we might have objects of type Tr_active_trapezoid
pointing onto each others preventing them from being deleted.
=> fix a leak in the trapezoidal decomposition that occurs when a curve is removed

Mesh_3/include/CGAL/Mesh_3/config.h, Mesh_3/include/CGAL/exude_mesh_3.h, Mesh_3/include/CGAL/lloyd_optimize_mesh_3.h, Mesh_3/include/CGAL/make_mesh_3.h, Mesh_3/include/CGAL/odt_optimize_mesh_3.h, Mesh_3/include/CGAL/perturb_mesh_3.h, Mesh_3/include/CGAL/refine_mesh_3.h
Fix warnings with pragmas, like on Windows, with gcc>=4.6.
=> Remove Mesh_3 warnings in Boost.Parameters

Alpha_shapes_2/examples/Alpha_shapes_2/ex_weighted_alpha_shapes_2.cpp, Apollonius_graph_2/include/CGAL/Apollonius_site_2.h, Surface_mesh_parameterization/include/CGAL/LSCM_parameterizer_3.h, Surface_mesh_parameterization/include/CGAL/Param_mesh_patch_vertex.h, Surface_mesh_segmentation/include/CGAL/internal/auxiliary/graph.h
This PR fixes several trivial warnings that pollute the testsuite every day:
* Unused parameter in _Surface mesh parameterization_ (Param mesh patch vertex)
* Uninitialized variable in _Surface mesh parameterization_ (LSCM parameterizer)
* Uninitialized attributes in _Surface mesh segmentation_ (internal auxiliary graph)
* Uninitialized variable in _Alpha shapes 2_ (ex weighted alpha shapes 2)
* Uninitialized variable in _Apollonius graph 2_ (Apollonius site 2)
Merged in [4.8-Ic-85](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-85.shtml), impacted lines are now all green (some warnings in Polyhedron demo are removed too) without visible regression (see [4.8-I-84](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-I-84.shtml) for comparison). …
=> Fix several warnings

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/MainWindow.ui, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h, Three/include/CGAL/Three/Viewer_interface.h
When displaying a large point set, the number of FPS drops dramatically when moving the camera. This PR creates a "quick camera mode" that only displays a subset of points when moving if the number of points is higher than an arbitrary high value (hard coded). The full point set is only displayed when the camera stops.
This mode is on by default but can be disabled in the _View_ menu. So far it is only used for point sets, but it can be extended to other items provided a rational is found to simplify their display.
=> Polyhedron demo: quick moving display of point sets

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item_k_ring_selection.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h, Polyhedron/demo/Polyhedron/Viewer.cpp
When selecting a facet/vertex/edge of a zoomed object, another facet/vertex/edge was selected in addition. This PR fixes that bug.
=> Selection tool fix

Cartesian_kernel/include/CGAL/Cartesian/Line_3.h
This copy constructor is useless as noted by this comment: https://github.com/CGAL/cgal/commit/0e1c69619209041f9f5c577170bbe32bd80f04fb#commitcomment-15267864
This PR removes it.
Merged in [4.8-Ic-94](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-94.shtml).
=> Remove useless copy constructor

Polyhedron/demo/Polyhedron/C3t3_type.h, Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Mesh_3_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Mesh_3_plugin_cgal_code.cpp
Enable protection of polylines from a `Scene_polyline_item` for segmented image and polyhedral domains
=> Protect polylines from Scene_polyline_item in mesh_3_plugin

Mesh_3/include/CGAL/internal/Mesh_3/split_in_polylines.h
Detected [here](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-95/Polyhedron_Demo/TestReport_lrineau_ArchLinux-clang-CXX14.gz) in the testsuite.
=> std::ofstream is used without the header being included

Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/CMakeLists.txt
This was breaking the parallel build of plugins because dependency were incorrectly encoded
=> move ui files into the correct group

CGAL_ImageIO/include/CGAL/Image_3_impl.h, CGAL_ImageIO/include/CGAL/Image_3_vtk_interface.h
This PR fixes the compilation of CGAL libraries when `WITH_VTK:BOOL=ON` is in the CMake cache.
This re-adds the support of VTK6 that was broken by the header-only merge. Unfortunately,  `WITH_VTK:BOOL=ON` is not (yet) tested by our testsuite.
Cc: @afabri @janetournois @gdamiand
=> Fix compilation errors when WITH_VTK=ON in CMake

Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt, Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_example.cpp, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/border.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/remesh_impl.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h, Polygon_mesh_processing/test/Polygon_mesh_processing/remeshing_test.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_modeling/Scene_edit_polyhedron_item.cpp
To fit better in the PMP general framework, the order of variables in the following functions should be changed
- *border_halfedges*
- *isotropic_remeshing*
- *split_long_edges*
These functions are new in CGAL-4.8 so there is no breaking change.
=> PMP : reorder variables for API consistency

Mesh_3/test/Mesh_3/test_c3t3.cpp
this seems to be some debug code that should not have been committed there
@cjamin do you have any clue why you added this?
=> Mesh_3 - fix a memory leak in testsuite

Mesh_3/demo/Mesh_3/CMakeLists.txt, Polyhedron/demo/Polyhedron/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/CMakeLists.txt
- This PR cleans up the CMakelists of the Polyhedron and Mesh_3 demos, by removing the parts that have been commented during the upgrade to Qt5 (essentially about moc files).
=> CMakeLists clean up 

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Merge_point_sets_plugin.cpp
I found out that my [recently merged](https://github.com/CGAL/cgal/pull/605) plugin for merging point set items was generating a segfault when applied from a context menu (when right-clicking on one of the selected items to access the operation menu). The reason was that all items were merged in the first one (which was not necessarily the "main" selected) and the other ones - including the main selected - were destroyed, which caused trouble as the context menu is generated _from_ the main selected item.
This is fixed by two changes:
* Keeping track of the main selected item when calling the context menu
* Using this index inside the plugin
I also fixed a bug: when several items were selected, the function  `getSelectedSceneItemIndex` was returning -1 instead of a proper index (which …
=> Polyhedron demo: bugfix erasing items context menu

Combinatorial_map/include/CGAL/Combinatorial_map_iterators_base.h, Documentation/doc/Documentation/Developer_manual/Chapter_checks.txt, Installation/include/CGAL/config.h, Kinetic_data_structures/include/CGAL/Kinetic/Ref_counted.h, Polyhedron/include/CGAL/Polyhedron_incremental_builder_3.h, STL_Extension/include/CGAL/assertions.h, Surface_mesher/include/CGAL/builder.h
**The problem:**  Throwing an exception from a destructor can cause problems since the callee is unable to catch an exception raised while the stack is unwinding. The result is the application will terminate with a hard crash.
**Consequence:** Since the exception is uncatchable, the program will terminate, but also the real exception is hidden by the the destructor exception.
**Solution:** Its desirable to not throw exceptions from the destructor if and only if an existing exception has not been caught, and the stack is unwinding. For this purpose I propose  a new macro that can safely be called from a destructor, even when the stack is currently unwinding. The macro makes use of `std::uncaught_exception()` and results in a nop when this is the case.
Additional discussions about this …
=> Introduces a CGAL_destructor_assertion macro.

Mesh_3/include/CGAL/Mesh_3/Image_to_labeled_function_wrapper.h
That assertion verifies that the value `value_outside` is considered at
a value *outside* of the domain. Otherwise Mesh_3 will crash with an
assertion saying that "infinite cells should not be in the C3t3".
Relates to one of the the documentation bugs reported in #624.
=> Add an assertion in Image_to_labeled_function_wrapper

Scripts/developer_scripts/autotest_cgal
=> make the call to readlink earlier to prevent usage of incorrect CGAL_DIR

Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp, Polyhedron/demo/Polyhedron/cgal_test_with_cmake
This PR introduces the following functionality
when more than one Scene_polyhedron_items are selected, they are all meshed with *PMP::split_long_edges()* or *PMP::isotropic_remeshing()* following the common parameters chosen in the remeshing widget.
The branch is ready for testing
=> Polyhedron demo : isotropic remeshing of several items

CGAL_ImageIO/include/CGAL/ImageIO_impl.h
We have memory leaks in ImageIO which are detected by the VC++ testsuite that uses VLD.
There exists a function to release memory, but we do not want to call it explicitely before ending
our test/example/demo.
In order to call it at the end, I added a static singleton that calls the function in its destructor.
Can the header-only gurus ( @cjamin @gdamiand ) please check that I did it right?
=> Fix memory leak in ImageIO

Advancing_front_surface_reconstruction/doc/Advancing_front_surface_reconstruction/Advancing_front_surface_reconstruction.txt, Advancing_front_surface_reconstruction/examples/Advancing_front_surface_reconstruction/boundaries.cpp, Advancing_front_surface_reconstruction/examples/Advancing_front_surface_reconstruction/reconstruction_fct.cpp, Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h, Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction_vertex_base_3.h, Advancing_front_surface_reconstruction/include/CGAL/internal/AFSR/construct_polyhedron.h, Advancing_front_surface_reconstruction/include/CGAL/internal/AFSR/write_triple_indices.h, Installation/changes.html, Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp
Small feature: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Advancing_front-Generalize_filter
Tested in [4.8-Ic-67](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-67.shtml). Warnings have been fixed and errors are not related to this PR.
Pre-approved by @afabri who asked the following question on the wiki: "_Should `HUGE_VAL` be replaced with `std::numeric_limits<double>::max()` ?_"
I kept `HUGE_VAL` because that was what was used in the first place in the _Advancing front_ package, but indeed using the STD fashion seems more consistent with what is done in CGAL usually. Any opinions?
=> Advancing front: generalize filter

Operations_on_polyhedra/include/CGAL/intersection_of_Polyhedra_3.h, Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Corefinement_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Intersection_plugin.cpp
self-intersection tests are done prior to the call to the corefinement code, but only for faces involved in the corefinement
=> Polyhedron demo: robustify corefinement and intersection plugins

Installation/include/CGAL/atomic.h, Installation/include/CGAL/config.h
- Change the way the macros `CGAL_CAN_USE_CXX11_THREAD_LOCAL` and
`CGAL_CAN_USE_CXX11_MUTEX` are defined, so that other compilers are
also supported.
- Add the macro `CGAL_CAN_USE_CXX11_ATOMIC` and the header
`<CGAL/atomic.h>`.
=> Add <CGAL/atomic.h> and CGAL_CAN_USE_CXX11_ATOMIC

.gitignore, Operations_on_polyhedra/include/CGAL/intersection_of_Polyhedra_3_refinement_visitor.h
When `do_not_build_cmap_` is `true`, avoid even to construct the
default-constructed CMap, because that operation is not thread-safe.
See also issue #659.
CC: @sloriot, @gdamiand
=> Fix in intersection_of_Polyhedra_3: CMap default-constructor is not thread-safe

Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
This PR contains an additional commit that fixes PR #606 at runtime
`selection_item` is `NULL` in this statement
=> PMP in Polyhedron demo - wrong polyhedron used

Polyhedron/demo/Polyhedron/Viewer.cpp
- The axis system will no longer be clipped when dezooming, nor will it be hidden by an item, and the lighting of the axis will no longer change when moving the camera.
=> Enhancement of the axis system of the viewer

Mesh_3/examples/Mesh_3/mesh_3D_gray_image.cpp, Mesh_3/include/CGAL/Gray_image_mesh_domain_3.h
We cannot just use `boost::bind` or similar, since we need to get the type
of the binder (which is not easily possible without decltype).
=> Replace deprecated binder2nd

Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.ui
1/ Create the clipping plugin at the center of the scene, otherwise it cannot be used at all, if the scene objects are far from the origin.
2/ UI improvements:
- add a real title to the dock widget,
- add shortcuts to the checkbox and the buttons,
- and add a text explaining which side of the plane actually clip out.
CC: @maxGimeno
=> Polyhedron demo: fix clip plugin

Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h
Add the possibility to load Wavefront OBJ files in the polyhedron demo. The function is added to the OFF plugin, for simplicity.
=> Polyhedron demo: add load_obj

Installation/include/CGAL/config.h
`BOOST_HAS_VARIADIC_TMPL` and `BOOST_NO_CXX11_VARIADIC_TEMPLATES` can be
wrong, with Boost-1.57 and gcc>=5.0.
Fixes the following warnings with gcc>=5.0 in C++98 mode:
```
> CGAL-4.8-Ic-106/include/CGAL/array.h:78:31: warning: variadic templates only available with -std=c++11 or -std=gnu++11
> template< typename T, typename... Args >
>                               ^
> CGAL-4.8-Ic-106/include/CGAL/array.h:80:28: warning: variadic templates only available with -std=c++11 or -std=gnu++11
> cpp11::array< T, 1 + sizeof...(Args) >
>                            ^
> CGAL-4.8-Ic-106/include/CGAL/array.h:81:42: warning: variadic templates only available with -std=c++11 or -std=gnu++11
>  make_array(const T & t, const Args & ... args)
>                                           ^
```
Actually, I …
=> Fix a bug in Boost.Config<1.57 with gcc>=5.0

Mesh_3/doc/Mesh_3/CGAL/Gray_image_mesh_domain_3.h, Mesh_3/doc/Mesh_3/Mesh_3.txt, Mesh_3/doc/Mesh_3/examples.txt, Mesh_3/examples/Mesh_3/mesh_3D_gray_image.cpp, Mesh_3/include/CGAL/Gray_image_mesh_domain_3.h, Mesh_3/test/Mesh_3/test_meshing_3D_gray_image.cpp
This PR improves the gray level images oracle of Mesh_3, and its documentation.
In particular, the "inside" of the domain is now considered to be the side where the voxel values are higher than the isovalue. This makes more sense because it is intended to be used with medical images, where the "white" area is the area of interest.
This PR solves issue #624
This PR ships pull request #633
=> Mesh 3 - Improve Gray level images domain and fix warnings

Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/CMakeLists.txt, Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/poisson_reconstruction.cpp, Poisson_surface_reconstruction_3/test/Poisson_surface_reconstruction_3/CMakeLists.txt, Poisson_surface_reconstruction_3/test/Poisson_surface_reconstruction_3/poisson_reconstruction_test.cpp
The include_directories are from a time before we had branch builds.
=> Fix warnings instead of suppressing them; cleanup of the CMakeLists.txt

Bounding_volumes/include/CGAL/Approximate_min_ellipsoid_d/Khachiyan_approximation_impl.h, Circulator/include/CGAL/Circulator/Circulator_adapters.h, Kernel_23/include/CGAL/Kernel_checker.h, Kernel_d/include/CGAL/Kernel_d/Sphere_d.h, Kernel_d/include/CGAL/Kernel_d/Tuple_d.h, Kernel_d/include/CGAL/Kernel_d/function_objectsCd.h, Kernel_d/include/CGAL/Kernel_d/function_objectsHd.h, Kinetic_data_structures/include/CGAL/Kinetic/Regular_triangulation_3.h, Kinetic_data_structures/include/CGAL/Kinetic/Sort.h, Matrix_search/include/CGAL/sorted_matrix_search.h, Nef_2/include/CGAL/Nef_2/PM_point_locator.h, Nef_2/include/CGAL/Nef_polyhedron_2.h, Nef_3/include/CGAL/Nef_polyhedron_3.h, Nef_S2/include/CGAL/Nef_S2/Sphere_triangle.h, NewKernel_d/include/CGAL/NewKernel_d/Vector/array.h, NewKernel_d/include/CGAL/NewKernel_d/Vector/vector.h, Polynomial/include/CGAL/Polynomial/Polynomial_type.h, STL_Extension/include/CGAL/Circulator_identity.h, STL_Extension/include/CGAL/Circulator_on_node.h, SearchStructures/include/CGAL/Range_tree_d.h, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h, Visibility_2/include/CGAL/Triangular_expansion_visibility_2.h, Voronoi_diagram_2/include/CGAL/Voronoi_diagram_2.h
Warning issued on platform  Ubuntu-latest-GCC6-Release_?
=> Use CGAL_USE to avoid g++6.0 warning

GraphicsView/include/CGAL/Qt/SegmentsGraphicsItem.h
Adds a QPen in SegmentGraphicsItem to draw the InputSegment. The default Pen has changed in Qt5 : [Qt5 :](http://doc.qt.io/qt-5/qpen.html)
"The default pen is a solid black brush with 1 width, square cap style (Qt::SquareCap), and bevel join style (Qt::BevelJoin)."
[Qt4:](http://doc.qt.io/qt-4.8/qpen.html)
The default pen is a solid black brush with 0 width, square cap style (Qt::SquareCap), and bevel join style (Qt::BevelJoin).
Making the segment extra large. Manually adding a pen in the `paint()` function allows to set the width to 0 and get back to the original behavior.
=> Snap roundig fix 

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polygon_mesh_processing/test/Polygon_mesh_processing/remeshing_test.cpp
This PR fixes a bug in the isotropic remeshing edge collapse step.
The conditions under which patch border edges can be collapsed
are more the complicated than the conditions for inside-patch edges
=> PMP isotropic remeshing : fix collapse step with inside borders

Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/AABB_traits.h
ice_and is deprecated in boost 1.60
=> Surface mesh segmentation: boost 1.60 compatibility

Polyhedron/demo/Polyhedron/Plugins/IO/PLY_to_xyz_io_plugin.cpp
@sgiraudot  We have to check that with an Ascii file
=> When opening a binary ply file  we have to use std::ios_base::binary

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/MainWindow.h, Polyhedron/demo/Polyhedron/Plugins/PMP/Self_intersection_plugin.cpp, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene.h
- Fixes the segfault occurring when destroying a selection_item's poly_item
- Fixes the recurseExpand() behavior
- Fixes the Segfault occurring when adding a group to a selected group.
=> Fixes for the Polyhedron_demo

Snap_rounding_2/test/Snap_rounding_2/cgal_test_base, Snap_rounding_2/test/Snap_rounding_2/test_snap_rounding_2.cpp
The testscript compares the generated output with an expected output.
As VLD writes there too we write directly into the file instead of redirecting from std::cout to the file in the script.
=> Write to an ofstream and not to std::cout 

Arrangement_on_surface_2/demo/Arrangement_on_surface_2/ArrangementGraphicsItem.h, Arrangement_on_surface_2/demo/Arrangement_on_surface_2/ArrangementPainterOstream.h, Arrangement_on_surface_2/demo/Arrangement_on_surface_2/Utils.h, Arrangement_on_surface_2/include/CGAL/Arr_geodesic_arc_on_sphere_traits_2.h, Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Bezier_x_monotone_2.h, Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/IO/Polycurve_2_iostream.h, Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Polycurve_2.h, Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Polyline_2.h, Arrangement_on_surface_2/include/CGAL/Arr_non_caching_segment_basic_traits_2.h, Arrangement_on_surface_2/include/CGAL/Arr_point_location/Arr_simple_point_location_impl.h, Arrangement_on_surface_2/include/CGAL/Arr_point_location/Trapezoidal_decomposition_2.h, Arrangement_on_surface_2/include/CGAL/Arr_polycurve_basic_traits_2.h, Arrangement_on_surface_2/include/CGAL/Arr_polycurve_traits_2.h, Arrangement_on_surface_2/include/CGAL/Arr_topology_traits/Arr_spherical_topology_traits_2_impl.h, Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Arc_2.h, Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/Make_x_monotone_2.h, Arrangement_on_surface_2/include/CGAL/IO/Arr_iostream.h, Arrangement_on_surface_2/include/CGAL/IO/Arrangement_2_writer.h, Arrangement_on_surface_2/test/Arrangement_on_surface_2/cgal_test_base, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_do_intersect.cpp, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_io.cpp, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_iso_verts.cpp, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_removal.cpp, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_spherical_merge.cpp, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_spherical_overlay.cpp, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_spherical_removal.cpp, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_unbounded_removal.cpp, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_zone.cpp
The fixes are described by the small feature: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Arrangement_polycurve_fixes.
I'm not even sure that it deserves a small feature.
I've de-deprecated  some member functions of Polycurve_2 and fixed their names.
I also made the stream representation of polylines and polycurves of segments match the old representation (one version back) before polylines were enhanced.
This should also take care of the false warning of certain compilers about deprecated code being used (even though the relevant templates are not instantiated).
=> Aos 2 fixes efif

Envelope_2/include/CGAL/Envelope_2/Env_divide_and_conquer_2_impl.h, Filtered_kernel/include/CGAL/internal/Static_filters/Compare_squared_radius_3.h, Filtered_kernel/include/CGAL/internal/Static_filters/tools.h, Partition_2/include/CGAL/Partition_2/partition_approx_convex_2.h, Surface_mesher/test/Surface_mesher/test_c2t3_iterators.cpp
Various techniques.
- suppress with a pragma
- initialize
- initialize boost::optional with   make_optional(..,false)
=> Adress g++ -Wmaybe-uninitialized warnings

Algebraic_kernel_d/test/Algebraic_kernel_d/CMakeLists.txt, Algebraic_kernel_d/test/Algebraic_kernel_d/cyclic.cpp, Apollonius_graph_2/examples/Apollonius_graph_2/ag2_exact_traits_sqrt.cpp, CGAL_Core/include/CGAL/CORE/BigFloatRep.h, CGAL_Core/include/CGAL/CORE/BigFloat_impl.h, CGAL_Core/include/CGAL/CORE/BigInt.h, CGAL_Core/include/CGAL/CORE/BigRat.h, CGAL_Core/include/CGAL/CORE/ExprRep.h, CGAL_Core/include/CGAL/CORE/Expr_impl.h, CGAL_Core/include/CGAL/CORE/Impl.h, CGAL_Core/include/CGAL/CORE/MemoryPool.h, CGAL_Core/include/CGAL/CORE/RealRep.h, CGAL_Core/include/CGAL/CORE/Real_impl.h
The class `CORE::MemoryPool` now keeps track of allocated blocks and deletes them in `~MemoryPool()`.
This is stil a rather lazy approach, as memory gets only deleted when the program ends.
=> Fix memory leak in CORE

Combinatorial_map/include/CGAL/Combinatorial_map.h, Combinatorial_map/include/CGAL/Combinatorial_map_storages.h
Make the (internal and undocumented) variable null_handle const.
It is a bug fix (because the fact that this variable was non cost was a bug).
Tested in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-113.shtml.
=> CMap make null_handle const

Jet_fitting_3/examples/Jet_fitting_3/Mesh_estimation.cpp, Ridges_3/examples/Ridges_3/Compute_Ridges_Umbilics.cpp, Ridges_3/examples/Ridges_3/Ridges_Umbilics_SM.cpp, Surface_mesh_parameterization/examples/Surface_mesh_parameterization/polyhedron_ex_parameterization.cpp, Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/TestMesh.cpp
with `#ifndef DONT_USE_BOOST_PROGRAM_OPTIONS` 
This allows us to not use boost even if it is available in a testsuite (but broken as boost was not compiled as expected)
=> Replace #ifdef CGAL_USE_BOOST_PROGRAM_OPTIONS 

Combinatorial_map/include/CGAL/Combinatorial_map_storages.h, Linear_cell_complex/include/CGAL/Linear_cell_complex_storages.h
Fixing [these warnings](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-113/Combinatorial_map/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz)
=> Suppress warning in Combinatorial  Map for g++ >= 5

Jet_fitting_3/test/Jet_fitting_3/blind_1pt.cpp
The assertion in the test `blind_1pt` is incomplete: the coefficients are computed based on a PCA with 2 equal lower eigenvalues (leading to several possible solutions for eigenvectors). Because one case only was asserted, this lead to invalid assertion in the 32bit distributions:
* [CentOS6-32](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-I-114/Jet_fitting_3/TestReport_lrineau_CentOS6-32.gz)
* [Fedora-32-Release](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-I-114/Jet_fitting_3/TestReport_lrineau_Fedora-32-Release.gz)
* [Fedora-32](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-I-114/Jet_fitting_3/TestReport_lrineau_Fedora-32.gz)
This PR completes the assertions (and also makes them more easily readable).
Merged in …
=> Jet fitting 3: fix incomplete assertion

Point_set_processing_3/test/Point_set_processing_3/edge_aware_upsample_test.cpp
It is slow, because it uses ITERATOR_DEBUGGING, and because it is rather slow
=> Produce a smaller output to allow the VC++ testsuite to finish

AABB_tree/demo/AABB_tree/Scene.cpp, AABB_tree/demo/AABB_tree/Scene.h, AABB_tree/demo/AABB_tree/Viewer.cpp, GraphicsView/include/CGAL/Qt/CreateOpenGLContext.h, Linear_cell_complex/demo/Linear_cell_complex/MainWindow.cpp, Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp, Mesh_3/demo/Mesh_3/MainWindow.cpp, Mesh_3/demo/Mesh_3/Scene_c3t3_item.cpp, Mesh_3/demo/Mesh_3/Scene_polyhedron_item.cpp, Mesh_3/demo/Mesh_3/Volume_plane.h, Mesh_3/demo/Mesh_3/include/CGAL_demo/Scene.h, Mesh_3/demo/Mesh_3/include/CGAL_demo/Scene_draw_interface.h, Mesh_3/demo/Mesh_3/src/CGAL_demo/Scene.cpp, Mesh_3/demo/Mesh_3/src/CGAL_demo/Viewer.cpp, Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Scene.cpp, Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Scene.h, Polyhedron/demo/Polyhedron/GlSplat/GlSplat.cpp, Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene.h, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/resources/shader_with_light.v, Triangulation_3/demo/Triangulation_3/MainWindow.cpp, Triangulation_3/demo/Triangulation_3/Viewer.cpp
This PR repairs the 3D demos on OS X.
- Most of the problems were caused by the fact that on OS X, the paintGL function of an OpenGLWidget is called during the setupUi() call (in the MainWindow), when the viewer's scene is still pointing to NULL, which caused a segfault. 
- Some demos did not display 3D effects, this was caused by the fact that on OS X, OpenGL binds automatically the color attribute to 0 in the shaders, and OpenGL does not dipslay anything when a setAttributeValue is made on the attribute 0.
- There were some errors due to Shaders that were still written in GLSL 330 instead of 120.
=> Demo fix for OS X (fix for #437)

Filtered_kernel/include/CGAL/internal/Static_filters/Static_filter_error.h
The clang testsuite on OSX has an assertion with our self written  ` ulp()`  function. Let's see if boost does it better.
=> Use boost::math::float_next() to compute ulp

Mesh_3/include/CGAL/Mesh_3/Refine_facets_manifold_base.h
The compiler does not realize that the edge exists.
CGAL_assume does not help so let's initialize the variables.
I can't reproduce the error with g++ 4.9.3
This should fix this [test](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-116/Mesh_3/TestReport_lrineau_CentOS7-Release.gz)
=> initialize to avoid a warning

Nef_3/test/Nef_3/test_nef_3_io_Cartesian.cpp, Nef_3/test/Nef_3/test_nef_3_io_Cartesian_Lazy.cpp, Nef_3/test/Nef_3/test_nef_3_io_EPEC.cpp, Nef_3/test/Nef_3/test_nef_3_io_Homogeneous.cpp, Nef_3/test/Nef_3/test_nef_3_io_Homogenoeus_Lazy.cpp
This should fix this [testcase](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-116/Nef_3/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-32bits.gz)
=> Split testcase to see if it avoids an ICE for VC++

Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h, Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/function_objects.h
`TestMesh` in the Surface mesh shortest path tests cannot compile on platforms with an old version of boost ([CentOS5](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-I-114/Surface_mesh_shortest_path/TestReport_lrineau_CentOS5.gz), [CentOS6-32](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-I-114/Surface_mesh_shortest_path/TestReport_lrineau_CentOS6-32.gz) and [CentOS6](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-I-114/Surface_mesh_shortest_path/TestReport_lrineau_CentOS6.gz)).
The reason is a bug from Boost 1.47 with `get` called with 3 template arguments that is mistaken with the `get` from adjacency list (which leads to wrong requirements on the parameter of `get`).
This is solved by calling `get` only with the first template …
=> Surface mesh shortest path: fix for boost get bug

BGL/test/BGL/CMakeLists.txt, BGL/test/BGL/next.cpp, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
With the `Exact_predicates_exact_constructions_kernel` included gcc4.4 has a problem with ADL for for function `next`.  To help it we  provide the types needed for `std::iterator_traits<Surface_mesh::halfedge_index>`, although this descriptor is not an iterator. 
This should fix this [test](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-116/Surface_mesh_Examples/TestReport_lrineau_CentOS6-CXX11-Boost157.gz)
=> Help g++ to find the right version of next()

Polyhedron/demo/Polyhedron/CMakeLists.txt
This is a fix for #539 
- Adds the requested flags from the CMakeLists only if the compiler is CLang or gcc.
=> Fix for 539

BGL/include/CGAL/boost/graph/Graph_geometry.h, BGL/include/CGAL/boost/graph/graph_concepts.h, BGL/test/BGL/test_circulator.cpp, NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Hyperplane_d.h, NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Point_d.h, NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Ref_count_obj.h, NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Segment_d.h, NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Sphere_d.h, NewKernel_d/include/CGAL/NewKernel_d/Wrapper/Vector_d.h, NewKernel_d/include/CGAL/transforming_pair_iterator.h, Number_types/include/CGAL/Mpzf.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/fair.h, STL_Extension/test/STL_Extension/test_stl_extension.cpp, Spatial_searching/include/CGAL/Search_traits_adapter.h
Using `BOOST_STATIC_ASSERT` and `BOOST_CONCEPT_ASSERT` generates warning about unused typedef in many packages and platforms in the testsuite (example on [Point set processing](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-I-114/Point_set_processing_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release-cpp11.gz)).
One way to remove this warning is to append `__attribute__((unused))` after the assertion (as described [here](https://svn.boost.org/trac/boost/ticket/7242)). That was actually already included in CGAL with the macro `CGAL_UNUSED` (which is called when using `CGAL_static_assertion` instead of `BOOST_STATIC_ASSERT`). `BOOST_STATIC_ASSERT` shouldn't be used directly in CGAL code.
This PR replaces `BOOST_STATIC_ASSERT` by `CGAL_static_assertion` …
=> Fix boost warning (unused typedef)

CGAL_ImageIO/src/CGAL_ImageIO/analyze_impl.h, CGAL_ImageIO/src/CGAL_ImageIO/bmpendian.h
Replace `#include <string>` by `#include <cstring>` and also add `#include<cstdio>` to avoid compilation errors on some platforms (e.g. Ubuntu 14.04).
=> CGAL_ImageIO: fix missing include

Barycentric_coordinates_2/test/Barycentric_coordinates_2/MV_const_linear_precision_test.cpp
`MV_const_linear_precision_test` is performed with a required precision too high, making the assertion fail in 32b platforms ([CentOS](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-118/Barycentric_coordinates_2/TestReport_lrineau_CentOS6-32.gz) and [Fedora](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-118/Barycentric_coordinates_2/TestReport_lrineau_Fedora-32.gz)).
This PR reduces the precision so that this assertion succeeds.
=> Barycentric coordinates: precision too high for 32b processors

NewKernel_d/include/CGAL/NewKernel_d/KernelD_converter.h
For unknown reasons, computing directly the boolean expression inside the template of `boost::mpl::if_c` leads to warnings in some platforms ([CentOS](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-118/NewKernel_d/TestReport_lrineau_CentOS6-32.gz) for example). Adding parenthesis doesn't change anything (and is pointless as the right parenthesis are already there).
The only way to remove this warning seems to be using the expression `boost::mpl::if_<boost::mpl::bool_<>,,>` instead and computing the expression with `boost::mpl::or_`. The warning is gone, the test compiles and runs fine.
=> Fix warning in NewKernel_d: use boost::mlp::if_

Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/gfx/Curve_renderer_internals.h, Arrangement_on_surface_2/include/CGAL/Curved_kernel_via_analysis_2/gfx/Curve_renderer_traits.h, Bounding_volumes/include/CGAL/Min_annulus_d.h, Generator/include/CGAL/random_convex_set_2.h, NewKernel_d/include/CGAL/NewKernel_d/Vector/determinant_of_iterator_to_points_from_iterator_to_vectors.h, Polytope_distance_d/include/CGAL/Polytope_distance_d.h, QP_solver/include/CGAL/QP_solver/QP_basis_inverse.h, QP_solver/include/CGAL/QP_solver/QP_basis_inverse_impl.h, QP_solver/include/CGAL/QP_solver/QP_solver.h, QP_solver/include/CGAL/QP_solver/QP_solver_impl.h, QP_solver/include/CGAL/QP_solver/basic.h, STL_Extension/test/STL_Extension/test_composition.cpp
This should fix the deprecated warnings we get in, e.g., [this testcase](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-117/Min_annulus_d_Examples/TestReport_lrineau_Ubuntu-latest-GCC6.gz)
However I was surprised that we had other occurences of `std::bind`, e.g., in the QP_Solver package, which did not result in warnings.
=> Replace all std::bind with boost::bind

STL_Extension/include/CGAL/tuple.h
Workaround for this [testcase](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-116/Voronoi_diagram_2_Examples/TestReport_lrineau_CentOS6-CXX11-Boost157.gz)
=> Fix for gcc 4.4 with the option -std=c++0x

Mesh_3/doc/Mesh_3/CGAL/Polyhedral_mesh_domain_with_features_3.h
The angle bound for sharp features detection is a bound on facets normals, and not on the dihedral angle itself.
This PR fixes issue #747
=> Mesh_3 - fix documentation about detection of sharp features

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
This is a fix for #753.
- The checkboxes are updated when the menu is opened, not when it is created like before.
- The feature edges are always displayed, only their color change.
=> Polyhedron_demo : Fix for 753

CGAL_ImageIO/include/CGAL/Image_3_vtk_interface.h
when vtk is used, fix a conversion warning on windows
=> Surface mesher demo : fix conversion warnings

AABB_tree/demo/AABB_tree/Viewer.cpp, Alpha_shapes_3/demo/Alpha_shapes_3/Viewer.cpp, Circular_kernel_3/demo/Circular_kernel_3/Viewer.cpp, GraphicsView/include/CGAL/Qt/CreateOpenGLContext.h, Linear_cell_complex/demo/Linear_cell_complex/Viewer.cpp, Linear_cell_complex/examples/Linear_cell_complex/linear_cell_complex_3_viewer_qt.h, Mesh_3/demo/Mesh_3/src/CGAL_demo/Viewer.cpp, Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Viewer.cpp, Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/Viewer.h, Three/include/CGAL/Three/Viewer_interface.h, Triangulation_3/demo/Triangulation_3/Viewer.h
This reverts commit 552aaa159f50b34506bae97cb5afcd9fc3d79a9e to fix #761 
- The use of a parent induced a double delete of the context, which cannot be fixed.
- There were a missing call to create() front the QOpenGLContext, before it was passed to QGLContext::fromOpenGLContext, which made the application segfault when deleting the QOpenGLContext. 
- Now that create is called, it is possible to delete "context" after the QGLContext is created, which should fix the memory leak.
=> Fix for 761

Polyhedron/demo/Polyhedron/Scene_plane_item.h
This is a fix for #770 .
- The function Scene_plane_item::setNormal(double x, double y, double z) was giving a normal instead of a quaternion to the ManipulatedFrame::setOrientation();
=> Polyhedron_demo : Fix for #770

Mesh_2/include/CGAL/lloyd_optimize_mesh_2.h
This should fix this [testcase](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-118/Mesh_2/TestReport_lrineau_Fedora-strict-ansi.gz)
=> Mesh_2 suppress an "unused parameter" warning concerning boost

GraphicsView/include/CGAL/Qt/CreateOpenGLContext.h
Restoring the memory leak in order to keep the demo running on Mesa.
=> Polyhedron_demo : fix context for mesa

Polyhedron/demo/Polyhedron/Plugins/PMP/Polyhedron_slicer_plugin.cpp
This is a fix for #783 
- Changed Scene_item into CGAL::Three::Scene_item to connect the item_about_to_be_destroyed signal correctly. 
- When the plane is destroyed, it closes the plugin, as it was doing before.
=> Polyhedron_demo : Fix for 783

Stream_support/include/CGAL/IO/File_header_extended_OFF.h
This allows to load OFF files without an EOL after the last face.
Don't forget to recompile the CGAL lib after the pull.
=> If we are already at EOF we do nothing to skip until EOL

Point_set_processing_3/include/CGAL/hierarchy_simplify_point_set.h
In the function `hierarchy_simplify_point_set()`, at some point, the `ForwardIterator` is dereferenced directly instead of being accessed through the property map. This works in the testsuite as the object referenced by `ForwardIterator` is a always point, but this makes the function unusable with, for example, indices as input.
This PR fixes this.
=> Bugfix: use property map to access content on Input_type

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/named_function_params.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/named_params_helper.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h
This PR removes a lot of face normal computations to display the polyhedron item.
It also fixes the display of quad meshes when the boundary edges of a quad are intersecting (I think the quad is somehow folded)
=> Polyhedron item : improve computation of normals

Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/Mesh_3_plugin_cgal_code.cpp
when needed or requested, activate protection of polylines,
either provided as input polylines, or computed as intersections with image boundary
cc @lrineau
=> Polyhedron demo : Activate protection of feature polylines in labeled images

Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/OFF_to_xyz_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/PLY_to_xyz_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/STL_io_plugin.cpp
When loading a file ~/Foo/elephant.23.3.off   the scene polyhedron item was called elephant. With `completeBaseName`  only the last suffix gets stripped. 
TODO: Something programmatically for the suffix polylines.txt    (Or we should give up such double suffixes).
=> Use completeBaseName() as name of items (for some file name extensions)

Polyhedron/demo/Polyhedron/Plugins/IO/GOCAD_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/Nef_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/OFF_to_xyz_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/PLY_to_xyz_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/Polylines_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/XYZ_io_plugin.cpp
When opening geometric objects, applying operations of the Polyhedron demo and saving them back, some information may be lost: this is due to the fact the doubles are written in ASCII format without checking if the precision is high enough.
This PR increases the precision of the output stream to all IO plugins to the maximum value. The drawback is that files might get larger (as the numbers are written with additional digits) even if it is not needed, but the advantage of never losing information seems more important.
=> Polyhedron demo : Use maximum precision when writing files

Mesh_3/examples/Mesh_3/mesh_3D_gray_image.cpp, Mesh_3/examples/Mesh_3/mesh_3D_image.cpp, Mesh_3/examples/Mesh_3/mesh_3D_image_variable_size.cpp, Mesh_3/examples/Mesh_3/mesh_optimization_example.cpp, Mesh_3/examples/Mesh_3/mesh_optimization_lloyd_example.cpp, Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp, Mesh_3/examples/Mesh_3/mesh_polyhedral_domain_with_features.cpp, Mesh_3/examples/Mesh_3/mesh_polyhedral_edge_tolerance_region.cpp, Mesh_3/examples/Mesh_3/mesh_polyhedral_implicit_function.cpp, Mesh_3/examples/Mesh_3/mesh_polyhedral_surface_tolerance_region.cpp
At the same time allow to process argc[1] if present. 
This should fix #800 
Almost, as there is still an example with a domain where we call the constructor with a file name. See also  #488
=> Check that the input can be read in the Mesh_3 examples

Number_types/include/CGAL/GMP/Gmpfi_type.h, Number_types/include/CGAL/GMP/Gmpfr_type.h, Number_types/include/CGAL/GMP/Gmpq_type.h, Number_types/include/CGAL/GMP/Gmpz_type.h, Number_types/include/CGAL/Lazy_exact_nt.h, Number_types/include/CGAL/leda_rational.h, Stream_support/include/CGAL/IO/io.h, Surface_mesh/examples/Surface_mesh/CMakeLists.txt
The function `read_float_or_quotient() ` existed in non-template form as `operator(istream&, Gmpq&)` in Number_types/include/GMP/Gmpq_type.h and it is now as function template in CGAL/IO/io.h.
This PR should partially fix the issue #813. Partially, because it does not fix `operator(istream&, leda_real&)`   but `operator(istream&, Lazy_exact_nt<leda_real>&)`  as number type of EPEC
=> operator>>(Lazy_exac_nt) calls new function read_float_or_quotient()

Linear_cell_complex/include/CGAL/Linear_cell_complex_incremental_builder.h
This simplifies creation and initialization of LCC.
The modified functions are undocumented.
Tested in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-145.shtml.
=> Incremental builder: end_XXX functions now return one dart.

Filtered_kernel/include/CGAL/internal/Static_filters/Static_filters.h, Filtered_kernel/test/Filtered_kernel/Filtered_kernel.cpp, Filtered_kernel/test/Filtered_kernel/Static_filters.cpp
Regular triangulation was no longer using filtered predicates...
=> Filtered_kernel: EPECK uses static filters

Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h, Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h
Fix an undocumented behavior of Mesh_3: when the bounding polyhedron is empty, then the bounding tree should not be initialized at all (because an AABB tree cannot be empty).
=> Minor fix in Mesh_3

Three/include/CGAL/Three/Scene_group_item.h
Trivial fix of the return type of `Scene_item* clone() const { return 0; }`.
=> Fix this override of a virtual function

Polyhedron/demo/Polyhedron/Plugins/Mesh_3_plugin/C3t3_io_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
This is a fix for #851.
- A call to c3t3_changed() was missing in the end of the loading function.
=> Polyhedron_demo : Fix for the c3t3_items

Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
When calling `setColor` on a polygon soup item, the Polyhedron demo segfaults: `setColor` calls `invalidateOpenGlBuffers` which calls `compute_bbox`. This function computes the bounding box on points without checking if the container has been allocated (which is not the case if it is called before `init_polygon_soup`).
This bugfix adds a safety test at the beginning of `compute_bbox`.
=> Bugfix: check if polygon soup is not empty before attempting BBox computation

Polygon_mesh_processing/examples/Polygon_mesh_processing/polygon_soup_example.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
When reading a polygon soup with isolated vertices in the Polyhedron demo, it crashes on  the operation "Orient polygon soup".  The fix is to apply `remove_isolated vertices()`.  
It is maybe a mistake that the plugin tries to construct a polyhedral surface.
I fixed at the same time the example in PMP that deals with polygon soups.
=> Deal with isolated vertices when turning a polygon soup in a polyedral surface

Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/IO/VTK_io_plugin.cpp
This PR adds the ability to save a Polyhedron_item as .vtk and .vtp file,
for the vtkPolyData and vtkXMLPolyData types
to be consistent with the types available in `load()`
=> Polyhedron demo : vtk_io_plugin can save

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h
This PR adds requirements to the halfedge and face descriptors types in PolygonMesh.
They should be models of `Hashable`
this PR fixes issue #806
=> PMP doc : Isotropic remeshing requires faces and halfedges to be hashable

Mesh_3/include/CGAL/Mesh_vertex_base_3.h
When a C3t3:
* either was created using parallel Mesh_3,
* or has "special protecting balls", 
then the `dimension` of a vertex can be negative:
* `-1` for far points,
* `dimension_ = -2-dimension_;` for special vertices.
But there was an assertion `dimension >= 0` in `Mesh_vertex_base_3::operator>>`. This commit fixes the assertion (the verification is now on `v.in_dimension()` instead of checking the internal value. And the dimension -1 is allowed, for far points.
@sloriot, in my opinion that can go to CGAL-4.8. Tell me if you disagree.
CC @cjamin (because that involves far points)
=> Fix the I/O of C3t3 in <CGAL/Mesh_vertex_base_3.h>

Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
- The `isEmpty()` function was wrong: if the domain contains 2D surfaces
it cannot be considered as empty, even if the 3D volume is empty.
- The computation of the bbox was wrong too.
=> Fix the c3t3 item

Polygon_mesh_processing/doc/Polygon_mesh_processing/NamedParameters.txt, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/named_function_params.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h, Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
This PR makes 3 improvements to the management of constraints in `PMP::isotropic_remeshing`
- fix a bug that was loosing the corner vertices (incident to more than 2 constraints) during the remeshing process (because of some wrong collapse and relaxation steps)
- introduce the ability to choose constrained vertices, that are not allowed to be modified by remeshing
- keep the selection_item valid by updating the selection of constrained edges after remeshing (i.e. resampling for edges) 
edit : the deformation plugin also benefits of keeping its selection valid after remeshing
=> PMP::isotropic_remeshing() - improve management of constraints

Polyhedron/demo/Polyhedron/Plugins/Mesh_2_plugin/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/Mesh_2_plugin/Mesh_2_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_2_plugin/mesh_2_dialog.ui
This plugin enables the meshing of polylines (not necessarily in the same item) that are in the xy, yz or xz plane. Seeds are handled as well as nested domain definition.
Minor know issue: if run mesh_2 is switch off but run Lloyd was switch on, the spinbox for the number of iteration is not disabled.
cc @afabri @janetournois
=> Polyhedron demo: add cdt2 mesher

CGAL_ImageIO/include/CGAL/Image_3.h
We have an array of size 8, but only set the value for as many entries as there are different labels around.
We must only interpolate for so many values, and not for all the 8.
=> Only interpolate for existing labels

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
when colors_only is false, it does not mean that colors are not computed!
this commit fixes commit 0661c21ac073d6f550cd7d002b99bca1b5909475
=> Polyhedron_item : fix "colors_only'

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
The input triangles are only composed of the face_range to remesh.
This reduces the size of the aabb_tree for projection
and fixes the fact that the face range only should be triangulated, not the
entire polygon mesh.
This PR is a bug fix for 4.8
@sloriot can you please test it on the data on which you got issues with projections in the past?
=> PMP isotropic remeshing : reduce the internal aabb_tree to the input face_range

Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
This is a fix for #869.
The colors of a c3t3 are now computed using their facets surface patch indices in addition of their cells subdomain index.
=> Polyhedron demo : c3t3 color fix

Polyhedron/demo/Polyhedron/Scene.cpp
When an item's visibility changes, it changes the Viewer's Frustum.
=> Polyhedron_demo : Fix for the Scene Bbox

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp, Surface_mesh_deformation/include/CGAL/Surface_mesh_deformation.h
This PR fixes the list of roi_border edges collected before deformation.
The result is that the ROI area does not get wrong after isotropic remeshing
and adds a default constructor to ROI_border_pmap (will be needed by isotropic remeshing soon)
=> Polyhedron demo : fix deformation plugin

Installation/src/CMakeLists.txt
=> In the construction of all_files.cpp, avoid qrc files

Installation/cmake/modules/CGAL_SetupBoost.cmake
This catches errors early and provides a clear error message instead of waiting for something in a test or example to break.
=> Require correct Boost version through CMake

Installation/CMakeLists.txt
This allows installing the architecture-independent data outside the
prefix. This is particularly necessary on systems using a
multi-architecture layout where architecture-dependent files live in
/usr/${host_triple}/ and architecture-independent files in /usr/share.
=> Include GNUInstallDirs and use CMAKE_INSTALL_* variables

.gitignore
Just adding two rules in the .gitignore file to ignore moc files from Qt compilation.
=> Adding moc files to gitignore

Poisson_surface_reconstruction_3/include/CGAL/Poisson_reconstruction_function.h
Small feature: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Surface_reconstruction_return_infinity_out_of_domain
* Pre-approved
* Not tested yet (except locally, of course)
=> Poisson reconstruction: bugfix query outside convex hull

Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/resources/shader_c3t3.f, Polyhedron/demo/Polyhedron/resources/shader_c3t3.v
This PR improve the drawing of the c3t3 item three times, with three different commits. I copy below the text of the commit messages...
@afabri @maxGimeno
(Maxime, please have a careful look at the modifications.)
Fix a critical performance issue (3c7a5dd)
----------------------
As decided by `MainWindow`, the `Scene_c3t3_item::toolTip()` method is called by `MainWindow::updateInfo()` for each `modified()` event of the manipulated frame. While the frame is manipulated, that generates a lot of events, and a lot of calls to `toolTip()`.
Before this commit, the call to `Scene_c3t3_item::toolTip()` was `O(n)`. After this commit it is `O(1)`.
That speeds up a lot the drawing of the item while the frame is manipulated!
Do not draw the intersection while the plane is manipulated (1439796)
--- …
=> Polyhedron demo: better c3t3 item

Mesh_3/include/CGAL/Compact_mesh_cell_base_3.h, Mesh_3/include/CGAL/IO/File_binary_mesh_3.h, Mesh_3/include/CGAL/Mesh_3/Mesh_complex_3_in_triangulation_3_base.h, Mesh_3/include/CGAL/internal/Mesh_3/get_index.h, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp
And restore the possibility for the Polyhedron demo to load two types of
C3t3 (with `Patch_id` being `int` or `std::pair<int, int>`).
=> Fix issues in I/O of Mesh_complex_3_in_triangulation_3

Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.ui, Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_dialog.ui, Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp, Property_map/include/CGAL/property_map.h
Update the isotropic remeshing package so that when remeshing a bunch of polyhedra, you have the option to preserve the identical edges. This means that those edges will be automatically split to match the target edge length and those edges will be protected during the remeshing
cc @janetournois & @afabri
=> Polyhedron demo: isotropic remeshing preserves duplicated edges

BGL/include/CGAL/boost/graph/convert_surface_mesh.h
Until that PR, the code of convert_surface_mesh forgot to map boundary halfedges (incident to `null_face()`) and store them in the `h2h` map
Fixed.
=> BGL convert_surface_mesh : convert also boundary halfedges

Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Efficient_RANSAC.h, Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Octree.h
The `Efficient_RANSAC` algorithm in CGAL uses property maps to access points and normals from a container. But currently, there is a bug if the property maps use a resource (for example an index property map with an internal `std::vector`) that can lead to a segmentation fault.
The reason is that one of the structures used by the algorithm (the octree) is instantiated with the correct property map types _but_ without actually propagating the property maps (the default constructor of the maps is used). In practice, this works well in the examples as the property maps used are just functors (no attribute that would need copying or sharing), but crashes if the maps are more complex.
This PR corrects this. Tested on my computer (also with my own code that uses property maps with attributes …
=> Point set shape detection: bugfix default property maps

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polygon_mesh_processing/test/Polygon_mesh_processing/remeshing_test.cpp
This PR makes the remeshing_test complete.
(we mentioned that in the comments of PR #672)
It also fixes the degenerate-case bug mentioned in PR #948 and issue #927 
This bug actually comes from the computation of normals for degenerate faces.
It was normalizing even the NULL_VECTOR, resulting in NaN coordinates for the normal vector
=> PMP : improve remeshing_test

Installation/CMakeLists.txt, Random_numbers/include/CGAL/Random.h, Random_numbers/include/CGAL/Random_impl.h, Random_numbers/src/CGAL/Random.cpp, Random_numbers/test/Random_numbers/test_Random-CGAL_TEST_SUITE.cpp, Random_numbers/test/Random_numbers/test_Random-no-CGAL_TEST_SUITE.cpp
when CGAL_TEST_SUITE   or CGAL_PRINT_SEED is defined
Rationale: Again and again we get timeouts in the [testsuite](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-145/Point_set_shape_detection_3_Examples/TestReport_lrineau_CentOS5.gz),  and cannot reproduce them as we do not know the seed of `CGAL::default_random`.    
With this PR we dump the seed in the testsuite, and can advice users with a bug report to add a define.
=> Print the seed of CGAL::default_random

Polyhedron/demo/Polyhedron/Plugins/Mesh_2/Mesh_2_plugin.cpp
CGAL/lloyd_optimize_mesh_2.h  #defines it too late.
We just set it to the value needed at the beginning of the plugin code.
The solution is not really nice, but this is just a plugin.
=> #define BOOST_PARAMETER_MAX_ARITY early enough

Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
add verbosity to isotropic_remeshing_plugin,
when it's called on several polyhedra, possibly in parallel
this PR solves issue #941
=> Polyhedron demo : add verbosity to isotropic_remeshing plugin

Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
when remeshing a selection_item, use it instead of poly_item
it avoids using a NULL poly_item
@sloriot can you please confirm it has the behaviour you expect?
=> PMP : fix isotropic_remeshing plugin

Mesh_3/test/Mesh_3/test_meshing_3D_gray_image.cpp
One cannot run `make_mesh_3` without `no_exude()`, and then use
`verify_c3t3`, that runs `refine_mesh_3`.
Fixes that error:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-I-14/Mesh_3/TestReport_lrineau_ArchLinux-clang-Release.gz
=> Fix a test

Mesh_3/include/CGAL/Mesh_3/Mesh_complex_3_in_triangulation_3_base.h, Mesh_3/include/CGAL/Mesh_complex_3_in_triangulation_3.h, Mesh_3/include/CGAL/refine_mesh_3.h, Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_polyhedron_transform_item.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Polyhedron_3.qrc, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h, Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h, Polyhedron/demo/Polyhedron/resources/shader_c3t3_edges.f, Polyhedron/demo/Polyhedron/resources/shader_c3t3_edges.v, Polyhedron/demo/Polyhedron/resources/shader_c3t3_spheres.v
Followup to PR #962, in  	5a9d82e:
- the display of spheres was no longer correct,
- allow loading of c3t3 without any facets and cells (only vertices
with weights),
- fix the display of spheres, with better shaders,
- `Scene_c3t3_item`: do not draw edges, in FlatPlusEdges, during a
`drawWithNames()`, to optimize speed,
- `Viewer`: do not use anti-aliasing during `drawWithNames()`
Plus:
- Allow to pop the context menu with `Key_Menu` (910f17c), faster than shift+rightbutton
- Do not depend on `Viewer.h` (f267cfb)
Cc: @maxGimeno, have a look at the modifications please.
=> Polyhedron demo: fix c3t3 item, again

Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene.h, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h, Polyhedron/demo/Polyhedron/resources/shader_without_light.f, Three/include/CGAL/Three/Scene_draw_interface.h, Three/include/CGAL/Three/Viewer_interface.h
This is a fix for #976 .
- This PR replaces the QGLViewer picking, that uses the very low-performance `glPushNames` and `glRender(GL_SELECT)`, by a new one based on depth reading. This is significantly more efficient ( the old picking used on 1M facets took around 10 seconds to perform on my computer, when the new one is instant.)
=> Polyhedron_demo : New picking

Point_set_processing_3/include/CGAL/internal/Voronoi_covariance_3/voronoi_covariance_3.h
This PR fixes a hardly reproducible runtime error, spotted in issue #919
We need to skip the infinite vertex to avoid computing stuff on the associated point.
This could explain the fact that debug and release behaviour of the tests are not the same, even with the same random seed. The initialization of the infinite vertex coordinates may also be done differently depending on the platform.
it replaces PR #987
=> Point set processing : avoid using the infinite vertex as a finite vertex

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_widget.ui, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
This PR adds two features two the selection tool :
- A Clear all button, that clears all the primitives from the selection
- A Inverse selection button, that inverse the selection of the current HandleType.
=> Polyhedron_demo : selection tool enhancement

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h
fix access in color map of a polyhedron item, , in case we have a single patch with index > 0
Edit
re-introduce commit [7d1b31](https://github.com/CGAL/cgal/pull/928/commits/7d1b315fab3a602304848e0f2ce94ce9c91bc752) and fix its use in the new drawing framework
=> Polyhedron item : fix access in color map

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Three/include/CGAL/Three/Scene_item.h
This PR fixes two minor problems :
- It does some clean-up in Scene_item.h
- It fixes #864 by introducing a boolean function called has_stats(), which returns false by default. An item will not have an "Statistics" option displayed in its context menu if has_stats doesn't return true.
=> Polyhedron_demo:  Trivial fixes

Operations_on_polyhedra/include/CGAL/corefinement_operations.h, Operations_on_polyhedra/include/CGAL/internal/Polyhedron_plane_clipping_3.h, Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.ui, Polyhedron/demo/Polyhedron/Scene_plane_item.cpp, Polyhedron/demo/Polyhedron/Scene_plane_item.h
This is a fix for #932 .
This PR adds :
- a button to flip the plane
- a feature to split the polyhedra instead of clipping them. The choice is made with radio buttons.
=> Polyhedron_demo: Clip_polyhedron_plugin enhancement

Filtered_kernel/include/CGAL/internal/Static_filters/Compare_x_2.h, Filtered_kernel/include/CGAL/internal/Static_filters/Compare_y_2.h, Filtered_kernel/include/CGAL/internal/Static_filters/Static_filters.h, Triangulation_2/include/CGAL/Triangulation_2.h
If you look in Static_filters.h you see that less_x_2  does NOT use static filters and does not use Filtered_predicate, as all we do is to compare  two floating point numbers.   That is not the case for Compare_x_2, because this functor has an operator(Line_2,Line_2,Point_2), and hence makes constructions.
This PR first implemented `Triangulation_2::compare_xy()` with `less_x_2()` and `less_y_2()`. 
@lrineau then recalled that the proper way is to add static filters for these functors.
=> Ex-filtrate Compare_{x,y}_2::operator(Point_2,Point_2) and (re-gain) a factor of 2 in speed

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h
triangulating the face naively around v is much simpler and more accurate than
iterating on prev/curr/next vertices inside the face
note this is important for the demo's Scene_polyhedron_item too
=> PMP : improve computation of a face normal for non-triangular faces

CGAL_ImageIO/include/CGAL/ImageIO_impl.h
There was a problem:
- when using ZLIB, on all platforms, for files >2GB,
- and on Windows, for files >4GB.
=> Fix when operating on huge files (>2GB)

Polyhedron/demo/Polyhedron/MainWindow.cpp
When a Polyhedron_item has isolated vertices, the line "Number of isolated vertices" appears twice : once in the item all the time, and one in the MainWindow only when this number is positive.
This PR removes the one added by the MainWindow , but I wonder if it would be better to remove the one from the item and make the one from the MainWindow permanent, so all kinds of items can write their isolated vertices.
@sloriot is not sure if it makes sense for non Polyhedron_items to indicate that. @janetournois what do you think ?
=> Polyhedron demo : fix the item's Info

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
If the Polyhedron item is initialized with an empty Polyhedron object, then the values `min` and `max` in the test to compute color map keep their initial values (INT_MAX and 0), which leads to `(max+1-min)` being a negative number which leads to an overly large signed number which leads to allocating a huge number of colors which leads to a `std::bad_alloc`.
(This happened with the `Surface_reconstruction_plugin` for example.)
=> Bugfix: color map with empty Polyhedron

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
This PR modifies the function setColor() of the polyhedron_item, so it does not corrupt colors_ anymore, which fixes the segfault that currently occurs when using the Edit_polyhedron_plugin.
=> Fix for Scene_polyhedron_item::setColor.

BGL/include/CGAL/boost/graph/properties_Polyhedron_3.h, Point_set_processing_3/test/Point_set_processing_3/CMakeLists.txt, Point_set_processing_3/test/Point_set_processing_3/jet_pointer_as_property_map.cpp, Property_map/include/CGAL/property_map.h
When `jet_estimate_normals()` was used with a pointer to an array as property map VC++ finds ambiguities.
=> Add using get and put to help VC++; Add a testcase

Cartesian_kernel/include/CGAL/Cartesian/function_objects.h, Distance_3/include/CGAL/squared_distance_3_1.h, Distance_3/test/Distance_3/compare_distance_3.cpp, Kernel_23/include/CGAL/Kernel/interface_macros.h
As `squared_distance(Point_3, Segment_3)` makes a division, we cannot perform an exact computation with a ring type.  Therefore we add low level functions `compare_distance(Point_3,Segment_3,Segment_3)` and `compare_distance(Point_3,Point_3,Segment_3)` which are called by overloaded versions of the function operator of `Compare_distance_3`.
=> Add specializations for Compare_distance_3::operator() for points/segments

Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h, Triangulation_2/doc/Triangulation_2/CGAL/Constrained_triangulation_2.h, Triangulation_2/examples/Triangulation_2/constrained.cpp, Triangulation_2/examples/Triangulation_2/constrained_plus.cpp, Triangulation_2/examples/Triangulation_2/polylines_triangulation.cpp, Triangulation_2/include/CGAL/Constrained_Delaunay_triangulation_2.h, Triangulation_2/include/CGAL/Constrained_triangulation_2.h, Triangulation_3/doc/Triangulation_3/CGAL/Delaunay_triangulation_3.h, Triangulation_3/doc/Triangulation_3/CGAL/Regular_triangulation_3.h, Triangulation_3/doc/Triangulation_3/CGAL/Triangulation_3.h
[Small feature "Use Default"](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Use_Default)
This PR makes several typedefs in examples obsolete.
=> Introduce CGAL::Default for the TDS of 2D constrained triangulations

Mesh_3/doc/Mesh_3/CGAL/Mesh_triangulation_3.h, Mesh_3/examples/Mesh_3/mesh_3D_image.cpp, Mesh_3/examples/Mesh_3/mesh_3D_image_variable_size.cpp, Mesh_3/examples/Mesh_3/mesh_implicit_sphere.cpp, Mesh_3/examples/Mesh_3/mesh_implicit_sphere_variable_size.cpp, Mesh_3/examples/Mesh_3/mesh_optimization_example.cpp, Mesh_3/examples/Mesh_3/mesh_optimization_lloyd_example.cpp, Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp, Mesh_3/examples/Mesh_3/mesh_polyhedral_domain_with_features.cpp, Mesh_3/examples/Mesh_3/mesh_two_implicit_spheres_with_balls.cpp, Mesh_3/include/CGAL/Mesh_triangulation_3.h
[Small feature "Use Default"](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Use_Default)
This is related to #829 
I modified one example so that we can look at before/after.
@lrineau : What do you think?
=> Introduce CGAL::Default for the geometric traits of Mesh_triangulation_3

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/MainWindow.h
This is a fix for #911 (fixes #911).
- Moved the shared code between `loadPlugins` and `on_actionLoad_plugin_triggered` in a separate function
- Fixed the segfault when menus and submenus have the same name
=> Polyhedron demo : clean up for plugin loader and fix for menus segfault

Surface_mesh_deformation/test/Surface_mesh_deformation/Cactus_deformation_session_OpenMesh.cpp
By default the scalar used for coordinates in OpenMesh is float. When using the deformation algorithm with the native point type of OpenMesh, and not a point property map that converts between OpenMesh and CGAL points, it is better to use an OpenMesh traits class with double coordinates.
This PR should fix [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-25/Surface_mesh_deformation/TestReport_jtournois_x64_Cygwin-Windows8_MSVC2015-Release-64bits.gz)
=> Use double coordinates in the OpenMesh points and normals

Polygon_mesh_processing/doc/Polygon_mesh_processing/NamedParameters.txt, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/border.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/named_params_helper.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h
In `PMP::border_halfedges()` (and as a matter of facts `PMP::isotropic_remeshing()`,
one can provide a `face_index_map` as named parameter.
If it's not provided by the user, the internal `face_index` map (if it exists) is used.
It can happen that this internal property map exists, but is not initialized. It is for example the case for a `Polyhedron_with_items_3` for which the user does not set the face ids.
This PR
- documents the fact that the internal face index map, if it exists, should be initialized
- adds a warning (via `std::cerr`) before the face index map is used, and so before the crash happens, to help the user find the problem
See e.g. the issue #1017
=> PMP : deal with uninitialized face_index map in border_halfedges

Polyhedron/demo/Polyhedron/Plugins/IO/Add_point_set_dialog.ui, Polyhedron/demo/Polyhedron/Plugins/IO/Add_polylines_dialog.ui, Polyhedron/demo/Polyhedron/Plugins/IO/Polylines_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/XYZ_io_plugin.cpp
This PR adds the possibility to choose the name of the point_sets and polylines created on the fly, but keeps the same counter.
=> Polyline demo : names for items created on the fly

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
This is a fix for #1020 
When meshing a polyhedron, if it is not closed and/or not triangulated, an error box appears instead of letting the demo crash.
=> Polyhedron_demo : Fix for the mesh_3 plugin

Polyhedron/demo/Polyhedron/CMakeLists.txt, Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h, Polyhedron/demo/Polyhedron/Polyhedron_3.qrc, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene.h, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h, Polyhedron/demo/Polyhedron/Scene_group_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.h, Polyhedron/demo/Polyhedron/Scene_spheres_item.cpp, Polyhedron/demo/Polyhedron/Scene_spheres_item.h, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/resources/shader_spheres.v, Three/include/CGAL/Three/Scene_group_item.h, Three/include/CGAL/Three/Scene_item.h, Three/include/CGAL/Three/Viewer_interface.h
This PR transforms the c3t3_item, the polylines_item and the edit_item :
- They are now group_items
- When the user asks to draw the spheres of these items, a new item is created and added as a child to the item, that cannot be moved or suppressed like a normal group's child, but only with the contextual menu. 
- The same principle is applied to the intersection tetrahedra of the c3t3
- The way these items are displayed or hidden does not change, but this PR allows for example to change the renderingMode of these sub-items without altering the one from the original item.
- This PR also fixes some bugs and errors from the group_items and simplifies there API (for exemple, it is not necessary to call add_group() anymore).
=> Polyhedron demo : Create new items for the spheres and the intersection of the c3t3_item 

Polyhedron/demo/Polyhedron/MainWindow.cpp
Add a warning box when the user forgets to put an extension when saving a file.
=> Polyhedron_demo : Warning when save fails

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
fixes #1054 
With this PR, the edit_polyhedron_plugin only transforms the selected items into Scene_edit_polyhedron_items, and doesn't accept polyhedron_items that are not pure_triangle.
=> Polyhedron_demo : edit_polyhedron_plugin improvement

Polyhedron/demo/Polyhedron/Plugins/PMP/Point_inside_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/include/Point_set_3.h
There was a bug in the selection mechanism of the point set item that created a memory corruption (`std::swap` applied on `end()`), spotted in issue https://github.com/CGAL/cgal/issues/1049.
This PR also fixes another bug if no point was selected (missing brackets).
=> Polyhedron demo: fix select one point

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
This PR fixes the display of the fixed plane for the `edit_polyhedron_plugin`
This problem was happening only on windows 8 (at least msvc2013), but it spotted an actual bug.
cc @maxGimeno , thanks!
=> Polyhedron demo : fix the display of the fixed plane for the deformation plugin

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
It happens that the `PMP::isotropic_remeshing()` function results in non-manifold meshes, that cannot even be loaded in a `polyhedron_item` but only in a `polygon_soup_item`
This PR fixes this issue, related to the fact that edges incident to boundary cannot always be flipped
=> PMP : fix for isotropic_remeshing

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h
Fixes a bug introduced by #985 when computing sdf values
cc @janetournois
=> If the color vector was manually set, do not translate color ids

Point_set_processing_3/include/CGAL/bilateral_smooth_point_set.h, Point_set_processing_3/include/CGAL/wlop_simplify_and_regularize_point_set.h
In the _bilateral smoothing_ algorithm, the points and normals are modified by getting a non-const reference through the `get()` operator. Although this is not strictly forbidden by the [Boost API](http://www.boost.org/doc/libs/1_60_0/libs/property_map/doc/ReadablePropertyMap.html), this operation is usually done using the `put()` operator (this is the case in all the other algorithms of _Point set processing_).
More specifically, some property maps might not be able to provide a `get()` operator that returns a non-const reference but still provide a `put()` operator: this PR makes _bilateral smoothing_ compatible with such property maps.
=> Bilateral smoothing: use put() operator instead of using ref of get()

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_widget.ui, Polyhedron/demo/Polyhedron/Scene_polyhedron_item_k_ring_selection.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
(fixes #930)
This PR adds a feature to the selection tool : the path between vertices selection. It allows the user to select the shortest path between two vertices, and then to edit it by forcing the path to go through selected vertices.
=> Polyhedron demo : Path selection

Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
the `join_and_split_polyhedron_plugin` now derives from `Polyhedron_demo_plugin_helper` and does auto-connect its actions
This PR completes PR #1081
=> Polyhedron demo : auto-connect actions - missing plugin

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/Polylines_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/XYZ_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Merge_point_sets_plugin.cpp, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene.h, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.h
Fixes  #1084 
This PR fixes :
- The multi selection that was broken for some time
- The polyline_items that had problems with their BBox
- Re-connects some actions that were broken in plugins not inheriting from the plugin helper.
- The color of items in a group when they are selected.
Plus, after this PR, when a group is added to the scene, no matter the selection, no item will be added as a child, which will avoid problems with several plugins and all the scene_items that recently inherited from Scene_group_item, such as the polylines_item or the c3t3_item.
=> Fixes for Polyhedron_demo

Combinatorial_map/include/CGAL/Combinatorial_map.h, Combinatorial_map/include/CGAL/Combinatorial_map_storages.h
same command than in Combinatorial_map_storage.h
=> Remove array-bounds warning also in Combinatorial_map.h

BGL/include/CGAL/boost/graph/properties_Surface_mesh.h
This PR fixes `CGAL::get()` by making it SFINAE using lazy_disable_if. It also put all the `get()` overloads in the `CGAL` namespace.
=> Fix for CGAL::get()

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/AABB_filtered_projection_traits.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
This PR replaces #1086 
the collapse step was still creating self-intersections
when it happened in a particular configuration close to boundary
=> PMP isotropic remeshing : avoid creating self intersections near patch boundaries

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/MainWindow.h, Polyhedron/demo/Polyhedron/MainWindow.ui
Fixes the following warnings at the start-up of the demo
`QMetaObject::connectSlotsByName: No matching signal for on_actionloadScript_triggered()`
`QMetaObject::connectSlotsByName: No matching signal for on_actionMaxItemsDisplayed_triggered()`
At the same time I also renamed all actions in the MainWindow to use CamelCase style
Replaces #1120
=> Fix action connection

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/TextRenderer.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h, Three/include/CGAL/Three/TextRenderer.h
This PR allows the user to display the distance between two points in the scene by pressing D and clicking on the scene. It will display a line between the two points, print their coordinates on their position and the distance in the middle of the segment. Press D alone to erase it.
=> Polyhedron_demo: Display distance between points

Polyhedron/demo/Polyhedron/Scene.cpp
When the user clicked on the "minus" button in the scene, with no item selected, nothing was erased but the first item in the list was selected. With this PR, if no item is selected, nothing happens.
When doing the same after displaying sphere_items from a polylines, or any "child_item" from c3t3_item, polyline_item, etc. the demo crashed. This PR fixes this bug.
=> polyhedron_demo : Fix ChangeGroup

Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
With this PR:
- It is possible again to change the radii of the spheres in a polyline
- Reloading a group from file won't cause the demo to crash anymore.
=> Polyhedron_demo: Fix for the Spheres_item and the Scene_polyline_item

Installation/changes.html, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_faces.h, Polyhedron/demo/Polyhedron/Plugins/PMP/Triangulate_facets_plugin.cpp
(fixes #1093 )
This PR makes triangulate_face() and triangulate_faces() boolean values, and optimizes triangulate_face() for the quads by using split_face instead of a CDT.
Small feature : https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Robustify_triangulate_facets
=> Robustify triangulate facets

Installation/cmake/modules/CGAL_Common.cmake, Installation/cmake/modules/FindEigen3.cmake
ensure the use file is known even if the FindEigen3.cmake
shipped with Eigen is used
=> Set Eigen3 use file name in CGAL common

Triangulation_2/doc/Triangulation_2/CGAL/Constrained_Delaunay_triangulation_2.h, Triangulation_2/include/CGAL/Constrained_Delaunay_triangulation_2.h, Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h
(fixes #511 )
This PR Updates the CDT constructors to use insert() with a range of iterators instead of a for-loop. 
It also updates  the tests and the doc.
=> Improve the CDT constructors

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp
- Replaces updateGL() calls by update() calls. Before the viewer used a painter, updateGL() was ok, because it was the QGLViewer that painted the scene. But a QPainter can only update its painting through a paintEvent() function, which is called by update() but not by updateGL().
- Fixes the bug that made the selection empty when an item was erased.
- Fixes the background color.
=> Polyhedron_demo : Fix the update of the viewer

AABB_tree/include/CGAL/AABB_face_graph_triangle_primitive.h
`boost::get(vertex_point, graph)` may not compile, if the graph is not a CGAL face graph. Example: when it is an OpenMesh, in the `OpenMesh` namespace.
=> Fix a documentation bug

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron_IO/include/CGAL/IO/OBJ_reader.h
This PR fixes the Scene_polyhedron_item::Load_obj() function, that was only able to read the files with only vertex data, and no normal, texture, etc. 
Now it discards this unwanted information to avoid the crashing.
=> Fix for the OBJ reading.

Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/SDF_calculation.h
This PR uses get() instead of [] operator to access the VertexPointMap.
=> Fix property map access in SDF_Calculation

Straight_skeleton_2/include/CGAL/Straight_skeleton_converter_2.h
The warning was:
```
/mnt/testsuite/include/CGAL/Straight_skeleton_converter_2.h:177:10: warning: variable 'hit' is incremented both in the loop header and in the loop body [-Wfor-loop-analysis]
++ hit ;
^
```
=> Fix a warning in Straight_skeleton_2, with recent clang

Mesh_3/test/Mesh_3/test_meshing_polyhedron.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.h, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Meshing_dialog.ui, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Optimization_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
This PR adds to the Polyhedron demo a new operation that allows to remesh a polyhedral surface using `Mesh_3`
There are 3 ways `Mesh_3` can be called on a polyhedron in the demo now
* create a tetrahedral mesh from a closed polyhedral surface
* create a surface mesh from a closed polyhedral surface
* create a surface mesh from an open polyhedral surface
=> Polyhedron demo : add remeshing of a Polyhedron with Mesh_3

Polyhedron/demo/Polyhedron/Scene_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h, Polyhedron/demo/Polyhedron/triangulate_primitive.h
This PR fixes some bug in the triangulate_primitive.h file, in the workaround for the meshes with very close points.
@janetournois  can you please check my algorithm is right?
=> Polyhedron_demo: Fix triangulate primitive

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Deform_mesh.ui, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp
With this PR, it is possible to import a selection_item as ROI vertices in the Edit_polyhedron_plugin.
=> Polyhedron_demo : Deformation use selection item

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Parameterization_plugin.cpp
(fixes #1161)
This PR is an enhancement for the Parameterization_plugin. It adds a warning when it is used on a polyhedron without borders.
=> Polyhedron_demo : Enhancement of Parameterization_plugin

Polyhedron/demo/Polyhedron/Plugins/PMP/Repair_polyhedron_plugin.cpp
(This is part of the #1162 resolution.)
This PR removes the action Remove_degenerate_faces from the Repair_polyhedron_plugin.
The code is still here, so we won't have to rewrite it when the function is finished and documented.
=> Polyhedron_demo : Remove an action

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
This PR makes the `volumeGroup` visible for meshing segmented images, and renames the surface meshing operation.
fixes #1185 and implements @lrineau comment about action name of #1154 
the fix of @maxGimeno in `Fix_bug_display-GF` is necessary to have this PR working
=> Polyhedron demo - various small fixes for Mesh_3 plugin

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane.h, Polyhedron/demo/Polyhedron/Scene_image_item.cpp
This PR fixes #1182.
This is a fix for the Io_image_plugin:
- This corrects the naming style
- This fixes the Word type in the toolTip()
- This adds a waitCursor during the creation of the planes
- This adds a bbox to the volume planes
- This keeps the item from computing useless data for the gray-images display.
=> Polyhedron_demo: Fix images issues in mesh 3 plugin

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h
This PR is an enhancement for the Edit_polyhedron_plugin:
- It implements the propagation of the selected ROI and Control vertices
- It allows to keep the Control vertices when using remesh_after_deformation.
=> Polyhedron_demo: Enhance deformation

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Deform_mesh.ui
=> use tabs to reduce the size of the deformation widget

Polyhedron/demo/Polyhedron/Scene_item.cpp
This PR initializes the boolean member `is_selected` to false in Scene_item, so that the items that do not change their color according to their selection state won't see their color randomly change.
=> Polyhedron_demo: Fix the unjustified color changes

Polyhedron/demo/Polyhedron/MainWindow.cpp
This PR restores the normal selection behavior when an item is erased from the scene.
=> Polyhedron_demo: Fixes the selection after erasing items

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
This PR fixes #1202 .
It makes the mesh_3 plugin transmit the meshing parameters to the c3t3_item's tooltip so it is displayed in the Info widget. Those parameters are not saved by the Io_plugin.
=> Polyhedron_demo : Add the meshing parameters to the item's tooltip

Polyhedron/demo/Polyhedron/Color_map.h, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h
This fixes #1203 .
This PR saves the Colors_ vector of the polyhedron_item if it exists before the conversion to edit_item and restores it after the deformation is saved.
It also fixes a color bug in isotropic_remeshing_plugin that occurs when it is used with a polyhedron_selection_item;
=> Polyhedron_demo : Keeping colors after deformation

Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_bilateral_smoothing_plugin.cpp
This PR triggers a warning if the selected point set has no normals in the Point_set_bilateral_smoothing_plugin.
=> Polyhedron_demo: Fix bilateral_smoothing

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
fixes #1210 
- Creates a scene_polyhedron_selection_item for the currently selected scene_polyhedron_item if none exists and a button is clicked in the widget.
=> Polyhedron_demo: On the fly selection_item

Polyhedron/demo/Polyhedron/Scene_implicit_function_item.cpp
This PR fixes #1204 
- The translation was done twice : once in the position and once in the frame matrix. The fix computes the position of the plane and the grid centered on O(0,0,0), so only the frame's transformation is kept.
=> Polyhedron-demo : Fix display issue with Scene_implicit_function_item

Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h
This PR fixes #1208 .
It partially restores the snapshot feature, that used direct OpenGL code and no longer works.
=> Polyhedron_demo : Restore the Snapshot feature.

Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_smoothing_plugin.cpp
Fixes the SEGFAULT by defining mw in the plugin's `init()` function, as it was missing.
=> Polyhedron_demo: Fix Point_set_smoothing_plugin

Polyhedron/demo/Polyhedron/Plugins/PMP/Point_inside_polyhedron_widget.ui
This PR adds a spacer to the UI of Point_inside_polyhedron_plugin, so it stays compact when the widget is resized.
=> Polyhedron_demo : Trivial UI change in Point_inside_polyhedron_plugin

AABB_tree/include/CGAL/internal/AABB_tree/Halfedge_and_face_graph_property_maps.h
This PR fixes a bug in the property maps for AABB_Tree.
=> AABB_Tree: Fix for Source_point_from_edge_descriptor::get().

Polyhedron/demo/Polyhedron/MainWindow.cpp
This PR removes the std::cerr in the function message() of the mainwindow. This way, the console will not print html messages anymore, but all the messages printed using this function will only be readable from the Console widget of the application.
=> Polyhedron_demo: No std::cerr in `MainWindow::message()`

Polyhedron/demo/Polyhedron/CMakeLists.txt, Polyhedron/demo/Polyhedron/ImageInterface.ui, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h
This PR fixes #1208 .
It restores the non-vectorial snapshots of the demo the way they were in 4.6.
=> Polyhedron_demo: Restore snapshots 

Mesh_3/include/CGAL/Mesh_3/Dump_c3t3.h, Mesh_3/include/CGAL/Mesh_3/io_signature.h, Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h, Mesh_3/test/Mesh_3/test_meshing_polyhedron.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp, Polyhedron/demo/Polyhedron/cgal_test_with_cmake
`CGAL::dump_c3t3` was not working with:
- the parallel tag,
- the polyhedral mesh domain with its default `Surface_patch_index` (`pair<int, int>`),
It is fixed, and I have added a test and an assertion.
=> Mesh:3 improve dump_c3t3 (Parallel_tag, Polyhedra;_mesh_domain_3)

Cartesian_kernel/include/CGAL/Cartesian/Vector_2.h
That is a follow-up to the following commit:
> commit 6b51b12ab50ae9d2c0cd7afc3ce5e2d7cbb42608
> Author: Laurent Rineau <laurent.rineau@cgal.org>
> Date:   Fri Oct 4 16:42:13 2013 +0200
>
>     Fix the case when FT is mpq_class
>
>     If x and w are mpq_class objects, then the type of x/w is not mpq_class,
>     but only a proxy type that is implicitly convertible to
>     mpq_class. With the type deduction, CGAL::make_array(x/w, y/w,
>     z/w) will not create an array<mpq_class> but an array of the proxy type.
>
>     That creates the following compilation error, in a ternary operator:
>
>     - with clang:
>     include/CGAL/Cartesian/Vector_3.h:78:25: error: incompatible operand types ('array<__gmp_expr<[...], struct __gmp_binary_expr<class __gmp_expr<mpq_t, mpq_t>, class …
=> Fix compilation error with gmpxx

Polyhedron/demo/Polyhedron/Plugins/PMP/Triangulate_facets_plugin.cpp
This PR fixes #1159: it removes the function`untriangulate()` and the associated action in the triangulate_plugin of the demo.
=> Polyhedron_demo : Remove Untriangulate facets

Polyhedron/demo/Polyhedron/Scene_image_item.cpp
This PR fixes #950 :
It fixes the Bbox that was too big for the image.
=> Polyhedron_demo : Fix the image_item's Bbox

Optimal_transportation_reconstruction_2/examples/Optimal_transportation_reconstruction_2/otr2_simplest_example.cpp, Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h, Optimal_transportation_reconstruction_2/test/Optimal_transportation_reconstruction_2/test_basic.cpp
This PR adds 2 changes:
* Methods `run()` and `run_until()` now return a boolean instead of `void` that indicates if the required number of steps were performed or if the algorithm was prematurely ended;
* A new method `number_of_isolated_vertices()` counts vertices with mass that are not connected to any edge with mass.
=> OT reconstruction: return a boolean when running

Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
Fixes #1276
This PR fixes the segfault in the mcf skeleton plugin and the bug of color of the polyhedron_item points visualization, that became magenta when the skeleton was selected.
=> Polyhedron_demo: Fix MFC_Skeleton_plugin 

Installation/cmake/modules/FindTBB.cmake
TBB now supports MSVC 2015 (= VC14)
https://software.intel.com/en-us/articles/whats-new-intel-threading-building-blocks-44-update-1
=> Add TBB support for MSVC14

Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Scene_combinatorial_map_item.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Scene_polyhedron_shortest_path_item.cpp, Polyhedron/demo/Polyhedron/Scene_plane_item.h
this was preventing the buffer to be marked as initialized
(in Scene_combinatorial_map_item and Scene_polyhedron_shortest_path_item)
=> use the boolean are_buffers_filled from Scene_item

Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
fixes #1278 
This PR filters facets of polyhedrons to ignore the ones that are degenerated. It also makes the plugin print a warning and ignore the not pure triangle polyhedrons.
=> Polyhedron_demo: Fix the Cut_plugin

Optimal_transportation_reconstruction_2/demo/Optimal_transportation_reconstruction_2/scene.h, Optimal_transportation_reconstruction_2/demo/Optimal_transportation_reconstruction_2/window.cpp, Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h
This PR fixes some problems of the demo of the _OT Reconstruction_ package:
* When initializing the reconstruction with a subset of the points, this subset was also used to compute the transport cost, whereas the whole point set should be used for this computation (initializing with a subset means using less vertices in the initial triangulation), otherwise the point set should simply be simplified. Confirmed by @palliez. Now vertices and samples are initialized separately.
* There was a bug with percentages: they were alternatively used with `100, 50, 20, etc.` values and with `1.0, 0.5, 0.2, etc.` values.
* The user-defined percentage in the dialog option was never taken into account.
* The scene was not properly cleaned, leading to a crash when clearing and then trying to run the …
=> OT Reconstruction: some bugfixes in the demo

.gitignore, Installation/CMakeLists.txt, Installation/cmake/modules/CGAL_CreateSingleSourceCGALProgram.cmake, Kernel_23/test/Kernel_23/Cartesian.cpp, Kernel_23/test/Kernel_23/Filtered_cartesian.cpp, Kernel_23/test/Kernel_23/Filtered_homogeneous.cpp, Kernel_23/test/Kernel_23/Homogeneous.cpp, Kernel_23/test/Kernel_23/Lazy_kernel.cpp, Kernel_23/test/Kernel_23/Simple_cartesian.cpp, Kernel_23/test/Kernel_23/Simple_homogeneous.cpp, Kernel_23/test/Kernel_23/include/CGAL/_test_io.h
With that patch, that is so simple to build and run tests (in parallel) for a package.
From the build directory configured in CMake with `WITH_tests=ON` and/or `WITH_examples=ON`, that is as simple as:
```shell
cd test/Kernel_23
make -j6
ctest -j6
```
=> Add minimal support for CTest

Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_average_spacing_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_bilateral_smoothing_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_interference_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_normal_estimation_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_smoothing_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_upsampling_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_wlop_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin_impl.cpp, Polyhedron/demo/Polyhedron/include/Point_set_3.h
This PR addresses the following issue: https://github.com/CGAL/cgal/issues/1230
Point set processing algorithms are applied to the selection (or to the whole point set if the selection is empty), with the exception of algorithms that specifically use selection in a select/remove fashion (simplification algorithms) as this would most certainly add confusion.
=> Polyhedron demo: apply PSP algorithms to selection only

Operations_on_polyhedra/include/CGAL/internal/corefinement/Combinatorial_map_for_corefinement.h, Operations_on_polyhedra/include/CGAL/intersection_of_Polyhedra_3.h, Operations_on_polyhedra/include/CGAL/intersection_of_Polyhedra_3_refinement_visitor.h, Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Scene_combinatorial_map_item.cpp
this was responsible for bugs in the demo plugin where the cmap
is created in a library and used in another one
cc @gdamiand I think it is time to remove the old API code
=> use the latest CMap API

Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
This fixes #1288 
This PR prints a warning in the application console when an open polyhedron is found in the cut_plugin. In that case, the signed distance function for that plugin is not displayed. If there are only open polyhedra in the list, the plane's texture is uniformly dark red. Else, the open polyhedra are simply ignored and the closed ones are displayed as usual. (See pictures below)
=> Polyhedron_demo: Fix cut plugin

Polyhedron/demo/Polyhedron/Scene_image_item.cpp
This partly fixes #950 
This PR fixes the geometry of the Scene_image_items by shrinking all the border voxels. (All voxels with a coordinate equals to 0 or dimension has its corresponding dimension divided by 2). 
With this fix, a scene_image_item and its mesh are overlapsed. (Before the fix, the Scene_image_item was twice the size of the mesh).
The color bug is still there though.
=> Polyhedron_demo: Fix the image item

Mesh_3/doc/Mesh_3/CGAL/Mesh_criteria_3.h, Mesh_3/doc/Mesh_3/CGAL/Mesh_facet_criteria_3.h
This PR fixes the documentation of the meshing criterion `facet_distance`
fixes #1250
=> Mesh 3 - doc fix for facet_distance criterion

Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h
As `Polyhedral_mesh_domain_with_features_3` copies the polyhedra, the
aabb tree should used the copy (with the assigned patch ids!)
cc @janetournois
=> bugfix for master: used the copied polyhedron

Installation/CMakeLists.txt
Fix the [CMake bug #14006][bug]. It has been "fixed" in CMake>=3.2, with the [policy CMP0056][cmp]. If we want the bug be fixed in CGAL, we must set the policy because we use `cmake_policy(VERSION 2.8.11)`.
[bug]: https://cmake.org/Bug/view.php?id=14066
[cmp]: https://cmake.org/cmake/help/v3.2/policy/CMP0056.html
=> Set CMP0056 if CMake>=3.2

Installation/src/CMakeLists.txt
(I copy the text from acf339d27f708d14e4569e25b4a648501a8d15c6. The other commit is just a fix of the indentation.)
If a `CMakeCache.txt ` is first created without `CGAL_HEADER_ONLY`, and
then `CGAL_HEADER_ONLY` is set, then CMake displays error messages like:
```
CMake Error: Target CGAL has dependency information when it shouldn't.
Your cache is probably stale. Please remove the entry
CGAL_LIB_DEPENDS
from the cache.
```
The problem comes from the fact that the target `CGAL` was first created as
a library target, and then turned into an "interface library" target.
This patch fixes the error the simplest way: remove the aforementioned
variable from the cache if it is present.
=> Hack to fix a bug with CGAL_HEADER_ONLY

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h
fixes #1238 
doc improvement : self-intersections are not allowed in the input
=> PMP triangulate_hole : doc improvement

Number_types/include/CGAL/sse2.h
Fix for the issue https://github.com/CGAL/cgal/issues/382.
=> Fix warning for MinGW: check _MSC_VER instead of _WIN32

Polyhedron/demo/Polyhedron/ImageInterface.ui, Polyhedron/demo/Polyhedron/Viewer.cpp
Fixes #1313.
This PR gives the possibility to choose if the background of the snapshot  will be of the same color as the scene, transparent, or of the chosen color. In the latter case, when the user confirms his/her choices and closes the dialog, a color dialog opens and let him/her choose the wanted color.
=> Polyhedron_demo: Transparent background for snapshots

Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
fixes #1320.
This PR adds a slider controlling the points size to the Scene_points_with_normal_item's context menu (near the normals length slider). It allows the user to set this size between 1 and 25. Of course this value is depending of the item, so you can have one point set displayed in size 1 and another one in size 20 at the time.
=> Polyhedron_demo : make the point size of a point set editable.

Polyhedron/demo/Polyhedron/MainWindow.ui, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h
Fixes #1314.
This PR implements a way to take a snapshot and send it to the clipboard. 
It uses arbitrary values for every quality parameters that are supposed to be given through the Dialog when a snapshot is taken in the regular way. 
**Question :** Would it  be better to keep the dialog for those parameters ? IMHO this shortcut is supposed to be quick, so keeping a dialog makes no sense and if the user needs some specifics parameters, then he/she can use the regular snapshot feature.
The function is bound to "Ctrl+Print Screen".
Once coupled with #1338, it will be able to use a transparent background.
@lrineau This PR makes the Viewer_impl a friend class of the viewer, as I needed access to some protected functions and I found it curious that a D pointer was not a "friend" of its …
=> Polyhedron_demo: Snapshot to clipboard

AABB_tree/doc/AABB_tree/Concepts/AABBTraits.h, AABB_tree/include/CGAL/AABB_traits.h, AABB_tree/test/AABB_tree/aabb_test_is_ray_intersection_geomtraits.cpp
partially fixes #260 
The doc mentions `Compute_closest_point_3`, and code implements `Closest_point`
<< edit
First, `Compute_closest_point_3` should be `Construct_closest_point_3`.
<< end edit
since ~~`Compute_closest_point_3`~~ `Construct_closest_point_3` should move to the Kernel at some point, I prefer to keep this option
However, for backward compatibility with possibly existing user code, I keep Closest_point
in the non-documented code.
=> AABB_tree : fix doc vs code inconsistency

Polyline_simplification_2/test/Polyline_simplification_2/CMakeLists.txt, Polyline_simplification_2/test/Polyline_simplification_2/simplify_polyline_with_duplicate_points.cpp, Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h, Triangulation_2/include/CGAL/Polyline_constraint_hierarchy_2.h
Fixes a bug when a polyline returned on itself, that is if simplify(u,v,w) gets called with u == w.
This should go into the bug fix release of 4.9.  @sgiraudot  can you please take care of this.
=>  fix polyline simplification

Optimal_transportation_reconstruction_2/include/CGAL/OTR_2/Reconstruction_triangulation_2.h, Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h
There are currently 3 levels of verbosity:
* 0 = nothing is displayed
* 1
* >1
The level 1 is currently a bit too verbose, as some functions which are called several times per iteration display messages. Level 1 verbosity should only display state messages (initalization, preprocessing, etc.), extensive debug information should be reserved to level >1.
=> OT reconstruction: improve verbosity

Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h
The half of the bounding box was computed as `(xmax - xmin / 2)`, that is to say with a missing parenthesis…
This fixes that. Notice that I also changed the computation so that the maximum value between `xl` and `yl` is used: this avoid having a badly shaped domain when the point cloud is flat on an axis direction.
=> OT reconstruction: fix: loose bbox length computation

AABB_tree/doc/AABB_tree/Concepts/AABBTraits.h, AABB_tree/include/CGAL/AABB_traits.h, AABB_tree/test/AABB_tree/aabb_test_is_ray_intersection_geomtraits.cpp
Reverts CGAL/cgal#1340
This fix was not meant to be included in 4.9 but in 4.10
=> Revert "AABB_tree : fix doc vs code inconsistency"

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp
This fixes #1302. 
This PR restores the overridecursor before the meshing dialog appears so the Waitcursor set by the Mainwindow's code for loading a script disappears.
=> Polyhedron_demo : fix the WaitCursor in the Mesh_3 script

Arrangement_on_surface_2/include/CGAL/Arr_polycurve_basic_traits_2.h, Arrangement_on_surface_2/include/CGAL/Arr_polyline_traits_2.h
The code of `Compare_y_at_x_2` was assuming that xmonotone curves was oriented from <i>left-to-right</i> (meaning endpoints are lexicographically sorted), with is not the case for example for polylines.
@efifogel Do you agree with the fix?
=> Fix Compare_y_at_x_2 for polycurve traits

Spatial_searching/examples/Spatial_searching/searching_with_point_with_info_inplace.cpp, Spatial_searching/examples/Spatial_searching/searching_with_point_with_info_pmap.cpp
In some examples of the `Spatial Searching` package, there is a `typedef std::size_t Point`. This is extremely misleading and makes the example hard to understand (there is also a `typedef Kernel::Point_3 Point_3` which makes sense). That actually lead me to make some errors when writing my own property map, taking inspiration on this piece of code…
I suggest to simply remove this typedef (`std::size_t` is short and clear).
=> Spatial searching: fix misleading typedef in examples

Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
This PR adds an undocumented function, that allows to call `split_graph_into_polylines` on a given set of polylines to protect. This PR is used to reduce the diff with a development branch.
=> Mesh_3: add a function that allows to specify and process a given set of polylines to protect

Arrangement_on_surface_2/benchmark/Arrangement_on_surface_2/arr_bench.cpp, Arrangement_on_surface_2/include/CGAL/Arr_spherical_gaussian_map_3/Arr_spherical_gaussian_map_3.h, Convex_hull_d/include/CGAL/Regular_complex_d.h, Kernel_23/include/CGAL/kernel_to_kernel.h, LEDA/include/CGAL/LEDA_basic.h, Nef_2/include/CGAL/IO/Nef_polyhedron_2_PS_stream.h, Nef_2/include/CGAL/Nef_2/gen_point_location.h, Nef_S2/include/CGAL/Nef_S2/leda_sphere_map.h, Number_types/include/CGAL/leda_bigfloat.h, Number_types/include/CGAL/leda_bigfloat_interval.h, Number_types/include/CGAL/leda_coercion_traits.h, Number_types/include/CGAL/leda_integer.h, Number_types/include/CGAL/leda_rational.h, Number_types/include/CGAL/leda_real.h, Number_types/test/Number_types/leda_real.cpp, Polynomial/include/CGAL/Polynomial.h, STL_Extension/include/CGAL/Handle_with_policy.h
Now, LEDA version >= 6.0 is required if `CGAL_USE_LEDA` is toggled.
=> Remove all usage of CGAL_LEDA_VERSION

Polyhedron/demo/Polyhedron/Scene_item.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
This fixes messages `QCoreApplication::postEvent: Unexpected null receiver` when deleting an item.
=> Call deleteLater only if the object if not NULL

STL_Extension/doc/STL_Extension/STL_Extension.txt, STL_Extension/include/CGAL/assertions.h
- `CGAL_NO_ASSERTIONS` was used *before* it was potentially modified by
the `NDEBUG` macro.
- I have also added a macro `CGAL_DEBUG` that allows to disable `assert`
but not CGAL assertions, using:
-DNDEBUG -DCGAL_DEBUG
=> Fix CGAL_NO_ASSERTIONS

STL_Extension/include/CGAL/hash_openmesh.h
So we have to add it for OpenMesh version < 6.2  
@janetournois can you test this please.
=> hash_value is not defined inside an #ifdef OM_HAS_HASH

Polyhedron/demo/Polyhedron/MainWindow.cpp
This fixes #909 
With this PR, when a plugin is loaded, an action is removed from the Operations root menu before it is added to a submenu.
This way, it is not "already tracked" and unity does not discard it. (I guess it is unity that does it as the bug only appears when Unity is used)
=> Polyhedron_demo : Fix the menu bug with Unity

Point_set_shape_detection_3/doc/Point_set_shape_detection_3/Point_set_shape_detection_3.txt, Point_set_shape_detection_3/examples/Point_set_shape_detection_3/efficient_RANSAC_parameters.cpp
Documentation in the RANSAC package is missing an example to show how to recover specific parameters of shapes (using `dynamic_cast`).
=> Point set shape detection: improve example

Point_set_processing_3/include/CGAL/IO/read_ply_points.h
Documentation was wrong (copy-paste error), no template parameter can be omitted.
=> Ply interpreter: remove lines about tparam that can be omitted

Polygon_mesh_processing/test/Polygon_mesh_processing/remove_degeneracies_test.cpp
add a note on how to reproduce the bug, for later
this PR amends #1459
=> PMP : do not test `remove_degenerate_faces` (2/2)

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h, Polygon_mesh_processing/test/Polygon_mesh_processing/remeshing_test.cpp
We were testing Epic twice instead of Epic and Epec.
**Edit** : it does not seem very useful to make isotropic remeshing work with an exact constructions kernel.
So, we have decided to remove support of those kernels for this function, at least for the moment.
Later, we could modify `isotropic_remeshing` so that it guarantees that output vertices lie exactly on the input surface. A `@todo` has been added to the doxygen comments to detail how to do that
=> PMP isotropic remeshing does not support exact constructions

Polyline_simplification_2/include/CGAL/Polyline_simplification_2/simplify.h, Triangulation_2/include/CGAL/Constrained_triangulation_2.h
We had hardwired that we use Exact_predicates_tag which is slow for EPEC
in particular with Quotient<MP_float> or leda::real
We determine the appropriate tag using Algebraic_structure_traits<FT>::Is_exact
=> Fix bug in polyline simplification

NewKernel_d/test/NewKernel_d/Epick_d.cpp
... Avoids that Intel Compiler or Clang are detected as well.
Fix #1458.
=> Use Boost.Config to detect a real gcc<=4.4

Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.cpp
This PR fixes #1310.
After a shape detection, all points belonging to a detected plane will have their normal set to this plane's normal.
=> Polyhedron_demo : Set the points normals after a planar shape detection

CMakeLists.txt
The CMake variable `CGAL_BRANCH_BUILD` was an option. But if
the variable was set to `FALSE`, that lead to a CMake error
automatically. This commit fixes that situation by turning the
option into an internal cache value, that cannot be set to `FALSE`.
=> Fix CGAL_BRANCH_BUILD

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_faces.h
this PR intends to cleanup the extra "includes" that can be found in the PMP package.
=> PMP : remove useless includes

Installation/CMakeLists.txt, Installation/cmake/modules/CGAL_Macros.cmake
This allows clients to specify a minimum CGAL version in their CMake list files.
Eg.:
find_package(CGAL 4.9)
More info: https://cmake.org/cmake/help/v3.6/manual/cmake-packages.7.html#package-version-file
=> Adds CMake package version file generation

Documentation/conversion_tools/split_doxyassist.py, Documentation/doc/CMakeLists.txt, Documentation/doc/scripts/pkglist_filter.py
Add the possibility to build the doc simply by calling cmake using the cmake script in `Documentation/doc` in branch mode and `doc` in release mode.
The way to compile the doc stays the same:
```
> make doc -j
> make doc_with_post_processing -j
```
I tested the former behavior in the branch and release modes, as well as the new behavior in both modes.
=> Allow building the doc without configuring CGAL

Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h
This PR 
- Makes the resizing of the points real fast
- Makes the resizing of the normals applied on slider released instead of every tick when the point set size is bigger than 300 000
- sets the initial value of the point size to 2 instead of 5
=> Polyhedron_demo : Optimize the point_set visualization

NewKernel_d/include/CGAL/NewKernel_d/function_objects_cartesian.h
Fix for [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-2/NewKernel_d/TestReport_lrineau_x86-64_Linux-Fedora_IntelCompiler-17.gz)
`include/CGAL/NewKernel_d/function_objects_cartesian.h(1165): warning #3373: nonstandard use of "auto" to both deduce the type from an initializer and to announce a trailing return type`
This fix was suggested by @mglisse
=> Fix of warning for auto with Intel compiler

Polyhedron/demo/Polyhedron/Viewer.cpp
This PR fixes the transparency of the snapshots taken with Ctrl+C on Windows.
As the solutions for Linux and Windows are not compatible, it uses a #if defined.
@janetournois @afabri please test this PR and tell me if this works.
Steps to test : 
- open any kind of item in the demo
- press Control + C
- paste in Gimp and check if the background is transparent
=> Polyhedron_demo : fix the transparency in snapshots taken with Ctrl+C on Windows

Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
After isotropic remeshing of a polyhedron with a selection, and colors on surface patches (colored for example with the "color connected components" action) were lost.
It's fixed
note that if a `polyhedron_item` is already multicolor, it stays multicolor, otherwise it stays monocolor and the color is updated
=> Polyhedron demo : fix colors or the remeshed polyhedron

BGL/include/CGAL/boost/graph/internal/Has_member_id.h, BGL/include/CGAL/boost/graph/properties.h, BGL/include/CGAL/boost/graph/properties_CombinatorialMap.h, BGL/include/CGAL/boost/graph/properties_PolyMesh_ArrayKernelT.h, BGL/include/CGAL/boost/graph/properties_Polyhedron_3.h, BGL/include/CGAL/boost/graph/properties_Surface_mesh.h, BGL/include/CGAL/boost/graph/properties_TriMesh_ArrayKernelT.h, BGL/test/BGL/CMakeLists.txt, BGL/test/BGL/test_Has_member_id.cpp, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/bbox.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/border.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/compute_normal.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/connected_components.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/fair.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/named_params_helper.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/measure.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/orientation.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/refine.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/self_intersections.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/stitch_borders.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_faces.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/triangulate_hole.h
This PR is about internal property maps, in particular in PMP.
It implements a new tool that is able to detect whether a given BGL graph has an internal property map corresponding to a given property tag or not
`struct graph_has_property<Graph, PropertyTag>`
We use it in `PMP::isotropic_remeshing()`, and at the same time add `face_index_map` as an optional named parameter
fixes #1256 
@sloriot we should discuss if we want to generate a compilation error or something special when there is no internal pmap, nor a pmap given as a named parameter. It should not compile already.
=> BGL : detect internal property maps, and use it in PMP isotropic remeshing

Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp
Scale space and Advacing front reconstruction produced a mesh in magenta.
=> Surface reconstruction plugin: Change the color of the constructed mesh

Installation/include/CGAL/config.h
I expect you will eventually get rid of this list (Qt4 is obsolete and Qt5 fixed the bug), but as long as it is there, we might as well keep it in a working state.
Seen while compiling a project that hasn't moved to Qt5 yet and was relying on CGAL/config.h to avoid the issue with moc.
=> Update list of boost headers that break Qt4 moc

Documentation/doc/Documentation/Preliminaries.txt
The macro `CGAL_VERSION` is deprecated. `CGAL_VERSION_STR` must be used instead.
=> Deprecate the macro CGAL_VERSION

AABB_tree/include/CGAL/AABB_triangulation_3_triangle_primitive.h, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
This PR fixes #1456.
It  renames AABB_C3T3_triangle_primitive in AABB_triangulation_3_triangle_primitive and changes the documentation accordingly.
=> Renaming the AABB_C3T3_triangle_primitive

Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h
This PR hides the grid when the corresponding action is checked in the context menu of a c3t3_item. This allows the taking of more beautiful screenshots.
=> Polyhedron_demo : Add an action to hide the grid in mesh_3_plugin

Polyhedron/demo/Polyhedron/MainWindow.cpp
With this PR, there won't be anymore warning when the user hits cancel when saving an item.
=> Polyhedron_demo : Fix the save file error

Mesh_3/include/CGAL/Mesh_3/Sliver_perturber.h, Mesh_3/include/CGAL/Mesh_3/Slivers_exuder.h, Mesh_3/include/CGAL/Mesh_3/sliver_criteria.h, Mesh_3/test/Mesh_3/test_meshing_utilities.h, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Optimization_plugin_cgal_code.cpp
After discussion with @janetournois  we decided to remove the static variables. They are not documented.
This solves the fist six items of Issue #1391. 
The other items concern debugging and will not be made multi thread safe.
=> Mesh_3:  Remove static variables

Voronoi_diagram_2/include/CGAL/Voronoi_diagram_2.h, Voronoi_diagram_2/include/CGAL/Voronoi_diagram_2/Dummy_iterator.h
The usage of static was necessary for CGAL::Iterator_project
Dummy_iterator keeps its static, as the class is only used for concept checking
This solves Issue #1398
=> Voronoi_2  Switch to transform_iterator

BGL/include/CGAL/boost/graph/split_graph_into_polylines.h, CGAL_ImageIO/include/CGAL/ImageIO_impl.h, CGAL_ImageIO/include/CGAL/Image_3.h, CGAL_ImageIO/include/CGAL/Image_3_vtk_interface.h, Mesh_3/include/CGAL/Mesh_3/Mesh_global_optimizer.h, Mesh_3/include/CGAL/Mesh_3/vertex_perturbation.h, Stream_support/include/CGAL/IO/File_header_OFF_impl.h, Stream_support/include/CGAL/IO/File_header_extended_OFF_impl.h
There are conversion warnings that were not quieted. As usual, the
"solution" is to use an explicit cast.
Note that I avoid the C-style cast, because the later prevent the
compiler from any warning.
=> Mesh_3: fix conversion warnings

Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
in the isotropic remeshing plugin.
=> Polyhedron  demo: Fix displayed dimensions of a bbox

Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
Fix a [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-I-12/Polyhedron_Demo/TestReport_jtournois_x64_Cygwin-Windows10_MSVC2015-Debug-64bits.gz)  in the Cut_plugin of the Polyhedron demo
=> Polyhedron_demo::Cut_plugin: static cast to avoid warning

BGL/include/CGAL/boost/graph/split_graph_into_polylines.h, Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h, Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h, Mesh_3/include/CGAL/make_mesh_3.h, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp
- There is a new argument, `Less`, that allows to sort the `std::set` of
vertex descriptors with a deterministic sort functor.
- The header `<CGAL/Mesh_3/polylines_to_protect.h>` defines and use such
a functor.
=> Make split_graph_into_polylines deterministic

Installation/CMakeLists.txt
@sloriot: I have pushed my "fix" that deal with OpenMesh. It is now a non-required dependency for the target `packages_dependencies`.
=> `packages_dependencies`: deal with OpenMesh

Installation/cmake/modules/CGAL_SetupBoost.cmake, Installation/config/support/CGAL_test_cpp_version.cpp, Installation/include/CGAL/config.h
Before this PR, there was a complicated `if()` trying to detect the C++
version. That is simpler to use `try_run()` and read the version in
the value of `__cplusplus`.
=> try_run to detect the C++ version

Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
I discussed it with @janetournois and the table is not that useful, in particular since it is not always updated when functions are added to the package.
We think it should be removed as the information provided is already in the documentation of each function.
@palliez (as the reviewer who asked for that feature): are you OK with this change?
=> Remove the requirement table

Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp, Polyhedron/demo/Polyhedron/Scene_spheres_item.cpp, Polyhedron/demo/Polyhedron/Scene_spheres_item.h
Fix #1531.
It also fixes a memory leak in the way the CGAL::Sphere_3 were cleared.
=> Polyhedron_demo: Fix spheres in polylines

Installation/include/CGAL/config.h
Fixes #1127 
This PR adds a macro : CGAL_DEPRECATED_MSG that allows to display a custom message in the deprecation warnings.
=> Add a macro to customize deprecation warnings

Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Scene_combinatorial_map_item.h, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene_c2t3_item.h, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h, Polyhedron/demo/Polyhedron/Scene_item.cpp, Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_textured_polyhedron_item.h, Three/include/CGAL/Three/Scene_interface.h, Three/include/CGAL/Three/Scene_item.h
This PR fixes #1311.
It adds a renderingMode called ShadedPoints to distinguish between the points with lighting effects and the others.
=> Polyhedron_demo : Add a new RenderingMode for ShadedPoints

Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h
This PR fixes #1248 by moving the private members and most of the protected code from Viewer.h to the Viewer_impl struct in Viewer.cpp.
=> Polyhedron_demo : Viewer use a d-pointer

Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/IO/VTK_io_plugin.cpp
This PR makes the VTK_IO_plugin able to save a c3t3_item as a .ctu file. 
Those files can be read by ParaView, for example.
=> Polyhedron_demo : Save C3T3 items as vtu files

Combinatorial_map/include/CGAL/Combinatorial_map.h, Combinatorial_map/test/Combinatorial_map/Combinatorial_map_2_test.h, STL_Extension/include/CGAL/Compact_container.h, STL_Extension/test/STL_Extension/test_Compact_container_is_used.cpp
This function allows to retreive the index of a given handle. This is particularly usefull to debug code based on compact container. This allows to write index (small numbers) instead of pointers.
This function is undocumented because it is mainly for cgal developers; and thus there is no modification of api, and thus no small feature.
I used this function in CMap test in order to test it.
=> Add index function in Compact container

Combinatorial_map/include/CGAL/Combinatorial_map.h, Combinatorial_map/include/CGAL/internal/Combinatorial_map_internal_functors.h, Linear_cell_complex/doc/Linear_cell_complex/CGAL/Linear_cell_complex.h, Linear_cell_complex/include/CGAL/Linear_cell_complex.h, Linear_cell_complex/include/CGAL/Linear_cell_complex_constructors.h, Linear_cell_complex/include/CGAL/Linear_cell_complex_incremental_builder.h, Linear_cell_complex/include/CGAL/Linear_cell_complex_storages.h, Linear_cell_complex/test/Linear_cell_complex/Linear_cell_complex_2_test.h, Linear_cell_complex/test/Linear_cell_complex/Linear_cell_complex_copy_test.cpp, Polyhedron/include/CGAL/import_from_polyhedron_3.h, Triangulation_3/include/CGAL/import_from_triangulation_3.h
* Bugfix in Combinatorial_map::copy and Combinatorial_map::swap
* Bugfix in erase dart if automatic attribute are disabled
* Add missing operator= in Linear_cell_complex
* Remove deprecated code in Linear_cell_complex storage (code which was already removed in Combinatorial_map_storage and not in LCC)
* add const for isomorphic function
* add more tests
* fix #1405 
No API modification; thus no feature/small feature associated with this PR.
=> Some bugfixes in CMap and LCC

Number_types/include/CGAL/Interval_nt.h
It is only needed for a runtime test at the start of an execution.
This solves one line in Issue #1387
=> Interval_nt: Declare the static object const. 

CGAL_ImageIO/include/CGAL/ImageIO_impl.h, CGAL_ImageIO/include/CGAL/Image_3.h, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Raw_image_dialog.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Raw_image_dialog.h, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/raw_image.ui, Polyhedron/demo/Polyhedron/Scene_image_item.cpp
This fixes #1471  
This PR :
- won't let the user open a raw image if its size does not match the File's size
- takes the offset into account for the size's calculation
- adds tooltips to the fields of the dialog
- automates the Gray-image choice if the WORD_KIND is not WK_FIXED with a wsize of 1.
- makes it possible to save the selected rendered image to the format inr.gz
- converts all raw images to a meshable format when they are opened.
@lrineau please check if the tooltips are explicit enough.
=> Polyhedron_demo: Enhance the raw image management

Surface_mesh_simplification/test/Surface_mesh_simplification/test_edge_collapse_Polyhedron_3.cpp
This should fix a  'N' in the [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-16/Surface_mesh_simplification/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz)
=> Qualify optional with boost::  as GCC6 sees an ambiguity

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/MainWindow.ui, Polyhedron/demo/Polyhedron/Plugins/Camera_position/Camera_positions_list.ui, Polyhedron/demo/Polyhedron/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.ui, Polyhedron/demo/Polyhedron/Plugins/PMP/Hole_filling_widget.ui, Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.ui, Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_widget.ui, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_normal_estimation_plugin.ui, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_outliers_removal_plugin.ui, Polyhedron/demo/Polyhedron/Polyhedron_demo_plugin_helper.cpp
This PR fixes #1522 #1526 and #1546 
- Set all the plugins DockWidgets sizePolicy to `Fixed` so they won't expand when another one is killed
- Fix the Erase all action by selecting the first item before calling the while(erase()) loop.
- Fix #1522
- Fix #1526
- Fix #1546
=> Polyhedron_demo: Fixes for the UI behavior

AABB_tree/include/CGAL/AABB_tree.h, Spatial_searching/doc/Spatial_searching/CGAL/Kd_tree.h
and unify it with `AABB_tree::build()`.
The latter was in a Section _Advanced_ (not `\cgalAdvanced`, just a `\heading`).
They are now both in the Section _Creation_.
=> Add the documentation for Kd_tree::build() 

Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h
The bug was revealed in the [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-22/Visibility_2/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Debug-64bits.gz) for Visibility_2.
=> Constrained_triangulation_2: Deal with an empty range as input

Polyhedron/demo/Polyhedron/Plugins/IO/Polylines_io_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.h
This fixes #1504 by adding statistics to the Scene_polylines_item and adding two actions to the Polylines_io_plugin. Those two actions allow to join and split polylines_items:
- Split polylines splits a polylines_item in as many items as the number of polylines in the original, each new item containing only one polyline
- Join polylines merge all the polylines of the selected polylines_items in one unique item.
@afabri please test it and tell me if it does everything you wanted.
=> Polyhedron_demo : Polylines upgrades

Algebraic_kernel_d/test/Algebraic_kernel_d/include/CGAL/_test_algebraic_kernel_1.h
This should fix the warnings [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-21/Algebraic_kernel_d/TestReport_lrineau_CentOS7-Release.gz)
=> CGAL_USE_TYPE() to avoid warnings

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h, Three/include/CGAL/Three/Scene_item_with_properties.h
This PR introduces  a new interface for items that adds a virtual function, which is used to retrieve special properties from a scene_item. In this case, it is used in a c3t3_item to retrieve the spheres, grid, intersections and CNC from another c3t3_item. This allows to keep all of it in the same state when we reload a c3t3_item from file.
=> Polyhedron_demo : Keep the c3t3_item's state when reloading

Circular_kernel_2/include/CGAL/Circular_kernel_2/Intersection_traits.h, Circular_kernel_2/include/CGAL/Circular_kernel_2/internal_functions_on_line_arc_2.h, Circular_kernel_3/include/CGAL/Circular_kernel_3/Intersection_traits.h, Installation/include/CGAL/config.h
This should fix Issue #1581  which shows up as error in the [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-22/Circular_kernel_2/TestReport_lrineau_x86-64_Linux-Fedora_IntelCompiler-17.gz)
=> Circular_kernel_2: Add a dummy field to the variant to work around an ICL bug

Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Curve_analysis_2.h, Algebraic_kernel_d/test/Algebraic_kernel_d/Curve_analysis_2.cpp, Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_enums.h, Arrangement_on_surface_2/include/CGAL/Arr_enums.h, Kernel_23/doc/Kernel_23/CGAL/enum.h, Kernel_23/include/CGAL/enum.h
Introduce the `enum Box_parameterization_2` in `CGAL/enum.h`
Add a `typedef `and constants in the Arrangement package to stay backward compatible
This solves Issue #1495
=> Make Algebraic_kernel_d independent from CGAL/Arr_enum.h

Triangulation_2/include/CGAL/boost/graph/graph_traits_Triangulation_2.h
This should fix this [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-25/Hash_map/TestReport_lrineau_CentOS7-Release.gz)
=> Triangulation_2: initialize data members to avoid warning

Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_site_2.h
This should fix this [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-25/Segment_Delaunay_graph_2/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz)
=> SDG_2: Set the failbit if the operator>> for Site fails.

Kernel_23/include/CGAL/Circle_2.h, Kernel_23/include/CGAL/Direction_2.h, Kernel_23/include/CGAL/Direction_3.h, Kernel_23/include/CGAL/Line_2.h, Kernel_23/include/CGAL/Plane_3.h, Kernel_23/include/CGAL/Point_2.h, Kernel_23/include/CGAL/Point_3.h, Kernel_23/include/CGAL/Sphere_3.h, Kernel_23/include/CGAL/Vector_2.h, Kernel_23/include/CGAL/Vector_3.h
It might fix this [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-25/Kernel_23/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz)
=> Kernel_23:  Set the failbit in operator>> for Kernel objects

Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h
This PR re-introduces determinism of protection with protecting balls.
We use `vecS` instead of `setS` for vertices in `boost::adjacency_list`, to have a consistent order on the
list of vertices.
The edges must be unique to avoid parallel edges, so we keep the `setS` for edges. It has no incidence on determinism.
=> Mesh_3 : make features protection deterministic again

STL_Extension/include/CGAL/iterator.h
Fixes [this test](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-25/STL_Extension/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz) and [that example](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-25/Kernel_23_Examples/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz).
See also https://svn.boost.org/trac/boost/ticket/11285
=> Workaround a bug in boost 1.58 with c++14

Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/bbox.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/named_function_params.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h, Polygon_mesh_processing/test/Polygon_mesh_processing/measures_test.cpp, Polygon_mesh_processing/test/Polygon_mesh_processing/point_inside_helpers.h
It add `vertex_bbox_3()`, `edge_bbox_3()`, and `face_bbox_3()`.
I would prefer having 3 more `bbox_3()` overloads for  but since these functions have 2 arguments this would cause an ambiguity with the 2 argument version of `bbox_3()` for a halfedge list graph model.
=> More bbox 3 overloads for face graph models

CGAL_ipelets/demo/CGAL_ipelets/multi_delaunay.cpp, Filtered_kernel/include/CGAL/internal/Static_filters/Equal_2.h, GraphicsView/demo/Triangulation_2/Constrained_Delaunay_triangulation_2.cpp, Kernel_23/include/CGAL/Circle_2.h, Kernel_23/include/CGAL/Direction_2.h, Kernel_23/include/CGAL/Direction_3.h, Kernel_23/include/CGAL/Line_2.h, Kernel_23/include/CGAL/Plane_3.h, Kernel_23/include/CGAL/Point_2.h, Kernel_23/include/CGAL/Point_3.h, Kernel_23/include/CGAL/Sphere_3.h, Kernel_23/include/CGAL/Vector_2.h, Kernel_23/include/CGAL/Vector_3.h
When we do not do that, and after the reading access a coordinate
some versions of g++ warn on -Wmaybe-uninitialized  
See [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-21/Kernel_23/TestReport_lrineau_Debian-stable-Release.gz) in the testsuite
The initialization costs nothing compared to the IO operation itself.
I at the same time initialize doubles in a static filter. I have no idea  why the warning shows only up in one testsuite, namely [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-21/CGAL_ipelets_Demo/TestReport_lrineau_Debian-stable-Release.gz)
=> Kernel_23: Initialize numbers in operator>>(istream&, Point/Vector/..)

SearchStructures/include/CGAL/Segment_tree_d.h
=> SearchStructures: No need to make an allocator a static data member

Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp
This PR makes the demo create an empty scene_polyhedron_item if the OFF is empty, instead of crashing (in command line) or popping an error message.
=> Polyhedron_demo : Load empty OFF files

Algebraic_kernel_d/include/CGAL/RS/algebraic_1.h, Algebraic_kernel_d/include/CGAL/RS/algebraic_z_1.h, Algebraic_kernel_d/include/CGAL/RS/bisection_refiner_1.h, Algebraic_kernel_d/include/CGAL/RS/rs23_k_isolator_1.h, Algebraic_kernel_d/include/CGAL/RS/rs2_calls.h, Algebraic_kernel_d/include/CGAL/RS/rs3_k_refiner_1.h, Algebraic_kernel_d/include/CGAL/RS/rs3_refiner_1.h
Since RS does not work with MPFR versions 3.1.4 and 3.1.5, this pull request enforces the version check using a Boost static assertion.
The bug in MPFR is solved in version 3.2 (which did not yet come to light).
Moreover, some checks are added to the AK code in order to quickly identify this kind of bugs.
=> Check for the MPFR version in RS-based AK

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h
this internal property map is not needed anymore
=> Fix PMP::isotropic_remeshing doc bug

Mesh_3/include/CGAL/IO/File_medit.h
This PR is a small patch to the Medit IO functions of Mesh_3 to remove some redundant find() calls before using insert(). Does not change much from a speed point of view since there are in general few subdomain indices.
It was tested in integration... about a year ago, but I forgot to open a pull request afterwards.
=> Avoid some unnecessary set/map's find() calls in Mesh_3's medit output

Hash_map/include/CGAL/Unique_hash_map.h
This PR is a bugfix to the specialization of `boost::associative_property_map` using `CGAL::Unique_hash_map`. The latter uses four template parameters (last two having default values), but only the first two were used in the specialization, which created issues if one wished to use a `Unique_hash_map` that does not rely on the default parameters for `HashFunction` and `Allocator`.
I also included the improvements of commit f32b291, which seemed natural.
=> Fix the Unique_hash_map specialization of boost's associative property map

Installation/cmake/modules/FindIPE.cmake
If `IPE_FULL_VERSION` is missing, that leads to a CMake error in
`CMakeLists.txt` files using it.
=> Do not early exit if IPE_FULL_VERSION is not there

Spatial_searching/doc/Spatial_searching/Concepts/SearchGeomTraits_2.h, Spatial_searching/doc/Spatial_searching/Concepts/SearchGeomTraits_3.h, Spatial_searching/doc/Spatial_searching/Concepts/SearchTraits.h, Spatial_searching/examples/Spatial_searching/Point.h, Spatial_searching/examples/Spatial_searching/user_defined_point_and_distance.cpp, Spatial_searching/test/Spatial_searching/Building_kd_tree_with_own_pointtype.cpp, Spatial_searching/test/Spatial_searching/Point.h
Kernel_traits was needed for the random generator in the examples/tests
=> Remove a non needed requirement from concepts

STL_Extension/include/CGAL/Spatial_lock_grid_3.h
- replace `std::max` by `(std::max)` for windows
- same for min
=> STL_Extension : fix conflict with min and max macros of windows

Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.cpp, Polyhedron/demo/Polyhedron/include/CGAL/Point_set_3/IO.h
The shape detection plugin now segfaults when called. This is caused by a bad merge between PR #1324 and #1527 (`add_normal_map()` must be called before setting normal values).
This PR fixes that and also fixes a problem of precision when saving PLY input (also due to PR #1527).
=> Polyhedron demo: fixes point set 3

Installation/changes.html, Mesh_3/doc/Mesh_3/CGAL/Polyhedral_mesh_domain_with_features_3.h, Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp, Mesh_3/examples/Mesh_3/mesh_polyhedral_domain_with_features.cpp, Mesh_3/examples/Mesh_3/remesh_polyhedral_surface.cpp, Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h, Mesh_3/test/Mesh_3/CMakeLists.txt, Mesh_3/test/Mesh_3/test_mesh_3_issue_1554.cpp, Mesh_3/test/Mesh_3/test_mesh_polyhedral_domain_with_features_deprecated.cpp, Mesh_3/test/Mesh_3/test_meshing_determinism.cpp, Mesh_3/test/Mesh_3/test_meshing_polyhedron_with_features.cpp
@lrineau and @janetournois: I am not at all lucky with the `typedef` for `Polyhedron` in the example. 
With `Polyhedron_3<K>` it does not compile. Isn't that a contradiction to the sentence  "The only requirement ...." in the [ref man page](http://doc.cgal.org/latest/Mesh_3/classCGAL_1_1Polyhedral__mesh__domain__with__features__3.html#ac4fcfea3273e4a83b580386a3ea29da3) 
With `Mesh_polyhedron_3<K>` it does not compile neither, as it needs the `"::type` suffix -- looks as it was a traits class.
I thought that `Mesh_domain::Polyhedron` could be a good choice but it is not public.
=> Mesh_3: Do not construct from a string

STL_Extension/doc/STL_Extension/CGAL/assertions_behaviour.h, STL_Extension/doc/STL_Extension/STL_Extension.txt, STL_Extension/include/CGAL/vector.h
We document it, and don't try to make it thread safe.
@sloriot This should solve some, but not all items of  #1396
=> STL_extension: error/warning behavior/handler is not thread safe

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Detect_sharp_edges_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Hole_filling_polyline_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Point_inside_polyhedron_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_average_spacing_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_interference_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_normal_estimation_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_smoothing_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_simplification_plugin.cpp
This fixes #1645 .
On windows, the modal dialogs mess with the application of the Waitcursor when they are called too soon after the closure of the said dialogs. This commit adds a call to processEvents() after the waitcursor where it is needed to fix that.
=> Polyhedron_demo : Fix waitcursor for windows in some plugins

Optimal_transportation_reconstruction_2/include/CGAL/OTR_2/Reconstruction_triangulation_2.h
@sgiraudot  can you please check that there is no need to make the variable thread local.
This PR fixes Issue #1408
=> Optimal Transport Reconstruction: make a static variable of a member function class local

Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp
This PR is a fix for #1653 
It uses the QPainter 2D API instead of OpenGL to draw the selection lines, so there is no float-precision problems when the coordinates are large.
It also fixes a CGAL_assertion that appears every time we use the free form selection and makes the feature impossible to use in Debug mode. 
Fix #1653.
=> Polyhedron_demo : Fix point set selection

Profiling_tools/examples/Profiling_tools/Profile_counter.cpp, Profiling_tools/include/CGAL/Profile_counter.h
Improve the output of profiling tools
> [CGAL::Profile_branch_counter_3] 0 / 2983185092 / 2983185092 semi-static failures/attempts/calls to   : Orientation_3
becomes
> [CGAL::Profile_branch_counter_3] 0 / 2.983.185.092 / 2.983.185.092 semi-static failures/attempts/calls to   : Orientation_3
=> Profiling Tools: dot integers

Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/include/Point_set_3.h
Fix for https://github.com/CGAL/cgal/issues/1690.
(Point set was never copied.)
- Fix #1680.
- Fix #1690.
- Fix #1695.
=> Several bug fixes for point set in Polyhedron Demo

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_simplification_dialog.ui, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Mesh_simplification_plugin.cpp, Surface_mesh_simplification/doc/Surface_mesh_simplification/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/Edge_length_stop_predicate.h
This PR adds the following functionalities for the mesh simplification plugin:
- using a stop predicate on edge length in addition (or instead of) the current stop predicate on the number of edges
- applying simplification to a Polyhedron with selected edges as constraints
=> Polyhedron demo: mesh simplification on selection

Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_selection_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/include/Point_set_3.h
Currently, the demo only displays colors if they were found in the input as 3 `unsigned char` numbers (that's the usual way to store colors).
As colors can sometimes be stored on 3 `double` numbers, the demo might not display them: this PR adds the handling of colors as `double` numbers.
=> Polyhedron demo: open PLY with floating colors

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp, Polyhedron/demo/Polyhedron/Scene_spheres_item.cpp, Polyhedron/demo/Polyhedron/Scene_spheres_item.h
This fixes #1667.
The sphere_item now directly adds the values to its buffers when a sphere is added instead of storing the sphere/color pair into a list
The items now give a squared radius to the CGAL::Spheres, and the square root of this value is stored in the buffers.
=> Polyhedron_demo : Fix spheres item

Polyhedron/demo/Polyhedron/Viewer.cpp
This PR fixes the picking in the demo. 
After the" selection picking" used to find which item to select, the scene must be re-drawn before the point/facet picking is performed.
This is because pointUnderPixel() is called to do so, and the first pass erases an item before drawing the next one, so only the last item of the scene remains after it is done.
=> Polyhedron_demo : Fix the picking

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/MainWindow.ui, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h
This PR adds a switch in the MainWindow's View menu to make the projection matrix orthographic.
=> Polyhedron_demo: Make it possible to switch between projection modes

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/MainWindow.h, Polyhedron/demo/Polyhedron/Scene.cpp
This PR fixes #1319
With this PR, the header is always displayed, and the space for each column is fixed to its minimum, except for the Name column that is resizable and the RenderingMode column that fits its content.
=> Polyhedron_demo: Fix the header of the sceneView.

Envelope_3/include/CGAL/Env_sphere_traits_3.h
@efifogel, I do not understand why the variable is static. There are other functions in the same file, where an `Alg_kernel k`  is just a local variable.
This is a fix for Issue #1410
=> Envelope_3: make a static variable a data member

Hash_map/test/Hash_map/Unique_hash_map_test.cpp
This PR adds new tests for the overload of `boost::associative_property_map` when the container is a `CGAL::Unique_hash_map`.
Specifically, two `CGAL::Unique_hash_map`s are used, one based on handles and the other on a type that cannot be dereferenced and thus for which the default hash function option (`Handle_hash_function`) cannot be used. Before PR https://github.com/CGAL/cgal/pull/1612, this would not have compiled due to an issue in the default parameters of the overload of `boost::associative_property_map`.
These tests are put in the file `Unique_hash_map_test.cpp` for consistency.
=> Added additional tests for CGAL::Unique_hash_map

Installation/include/CGAL/config.h
I am a bit tired of typing -DCGAL_EIGEN3_ENABLED (and still allergic to cmake), and my compiler understands `__has_include`. For a header-only dependency, that seems safe enough. The header I am testing was absent in 2.0.17 and present in 3.0.0.
=> Auto-enable Eigen3 if detected

Polyhedron/demo/Polyhedron/MainWindow.cpp
this can happen when dlls are moved (in particular out of the msvc `Debug`/`Release` folders)
It gets (really) annoying when dock widgets are created twice
=> Polyhedron demo : avoid loading twice the same plugin

Poisson_surface_reconstruction_3/include/CGAL/Reconstruction_triangulation_3.h
To use a sphere around the bbox of points instead of min_sphere_of_spheres of points should make  no difference in practice.
=> Poisson_surface_reconstruction: Reduce dependency on min enclosing sphere

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp
When the `C3t3` was generated using concurrent code, `v->in_dimension()` returns -1 for "far points" used for parallelism, and this case was not handled, leading to a crash.
Note curly brackets around the code for `case 2` are needed to avoid compilation error [C2361](https://msdn.microsoft.com/fr-fr/library/dfbz90h6.aspx) (at least on visual studio)
=> Polyhedron demo : fix c3t3_io_plugin in the parallel framework

Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h
Before this patch, the assertion was "sp > 0". Now the message says that
the sizing field is null at point (or at the corner), with the
coordinates of the point.
=> Add an CGAL_error_msg when the sizing field if locally zero

Alpha_shapes_3/doc/Alpha_shapes_3/Alpha_shapes_3.txt, Alpha_shapes_3/doc/Alpha_shapes_3/CGAL/Alpha_shape_3.h, Alpha_shapes_3/include/CGAL/internal/Lazy_alpha_nt_3.h, Alpha_shapes_3/test/Alpha_shapes_3/include/CGAL/_test_cls_alpha_shape_3.h
Fixes #1704 
@mglisse  for the version with `static_vector`, I have to define the `operator=` myself as the default one was not fine. Any idea why?
=> Improve Lazy_alpha_nt_3

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/border.h
This PR fixes a bug in one of the implementations of PMP's `border_halfedges()` and in the documentation.
There was an inconsistency between the version where a face index map is passed and the one where it is not. Although the documentation indicated that `border_halfedges()` returned interior halfedges (halfedges on the patch), this PR changes the documentation and one of the implementations to return exterior halfedges (halfedges are not on the patch). This is more consistent with the basic definition of a border halfedge.
PMP's isotropic remeshing already used the version returning exterior halfedges, so no changes are required there.
=> Fixed an implementation of PMP's border_halfedges()

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
This PR introduces 2 fixes for `PMP::isotropic_remeshing`
- do not collapse an isolated constrained edge
- avoid all face inversions during collapse and relaxation steps
This PR replaces #1692 and is based on CGAL-4.9 instead of master
~~Note : this PR is not completely ready for testing. The no-inversion test should still be done surface patch per surface patch~~
=> PMP : fixes for isotropic remeshing

Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/edge_collapse.h
@afabri in  a comment you ask why `halfedge_index_map`. It is just to create a default named parameter and give it to the function. In PMP we have all_defaults() for that purpose.
=> Add missing namespace

Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/Filters.h, Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/SDF_calculation.h, Surface_mesh_segmentation/include/CGAL/internal/Surface_mesh_segmentation/Surface_mesh_segmentation.h, Surface_mesh_segmentation/include/CGAL/mesh_segmentation.h
The member function `is_pure_triangle()` was used and lvalue property map API was used instead of `rw`
=> Update code to match documented concepts

Polygon_mesh_processing/doc/Polygon_mesh_processing/NamedParameters.txt
Vertices can be changed because of edge collapse,
for which we don't always know if vkept will be source or target.
fixes #1716
=> PMP : fix documentation bug for `vertex_is_constrained_map`

Scripts/developer_scripts/create_cgal_test
`RUNNING_CGAL_AUTO_TEST` and `CGAL_DIR` are set on the command line by
our `cgal_test` scripts.
-> Add the option `--no-warn-unused-cli` to avoid warnings when the
variables are actually not used (for example if a dependency is not
satisfied).
=> Fix CMake warnings about unused variables set on command line

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/border.h
This PR fixes a compilation error in `border_halfedges()` of `PMP`, which appeared if a face index map was not provided in named parameters, nor as an internal property map.
Note that it still requires the Polygon mesh to have a dummy that matches `boost::property_map<PolygonMesh, boost::face_index_t>` otherwise the `property_map_selector` will not compile.
=> Fixed a compilation issue in PMP's border_halfedges()

Number_types/include/CGAL/Sqrt_extension/convert_to_bfi.h
Note that this code does not get tested.
This is the last item of Issue #1387
=> Number_types: Make convert_to_bfi() multithreading safe. 

Polyhedron/demo/Polyhedron/Plugins/PMP/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/PMP/Hole_filling_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Hole_filling_widget.ui
This PR fixes #1707 . It adds a way to fill a hole delimited by an edge selection.
It links the hole_filling_plugin to the Scene_polyhedron_selection_item and changes the applicable() function to return true in case the selected item is a polyhedron_item OR a selection_item.
=> Polyhedron_demo : Enhance Hole_filling_plugin

Point_set_processing_3/include/CGAL/internal/Voronoi_covariance_3/voronoi_covariance_3.h
Use halfspace intersection that produces better vertex coordinates (even if the topology of the CH3 might not be fully correct).
halfspace_intersections()  for a range of planes has a robustness problem when `intersection()` is called with three planes.  To `#define CGAL_VORONOI_COVARIANCE_USE_CONSTRUCTIONS` is a quick solution, and the problem wih the intersection must be investigated later.
=> Point_set_processing: define CGAL_VORONOI_COVARIANCE_USE_CONSTRUCTIONS

Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp, Polyhedron/demo/Polyhedron/Polyhedron_demo.cpp, Three/include/CGAL/Three/exceptions.h
- Fix the `Scene_edit_box_item` to avoid a temporary computation using
floats instead of doubles.
- Extend `--no-try-catch` to the try/catch used in handle C++ exceptions
from C++ code called from a Qt Script.
=> Add various fix to demo/Polyhedron

Polyhedron/demo/Polyhedron/Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
This PR fixes #1285.
If the selected item is multicolor, each connected component that will be extracted will have the corresponding color. Else, it will be the color of the original item.  Moreover, all connected components will be extracted in a group.
=> Polyhedron_demo : Enhance Split Polyhedra

Spatial_searching/include/CGAL/Fuzzy_sphere.h
When the query is a radius 0 sphere, we never enter the loop with ` distance < squared_radius`, and hence the real ` distance` does not get computed.
This fixes Issue  #1723
=> Spatial_searching: bug reported and fixed by Marc Glisse

Solver_interface/include/CGAL/Eigen_matrix.h
Should fix [this](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-76/Solver_interface_Examples/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz) and other warnings in packages using Eigen.
=> Eigen: Static cast to avoid warning

Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
Fix type in std::priority_queue. Spotted by VC2017
=> Surface_mesh_shortest_path: Fix type

Arrangement_on_surface_2/include/CGAL/Arrangement_2/Arrangement_on_surface_2_impl.h, Arrangement_on_surface_2/test/Arrangement_on_surface_2/Overlay_test.h, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_spherical_overlay.cpp, Sweep_line_2/include/CGAL/Sweep_line_2/Arr_default_overlay_traits_base.h
Looks like the misspelling got copy pasted a few other places.
#1756 has some other spelling corrections but it doesn't look like they noticed this.
=> Fix spelling of 'matches'

Installation/changes.html, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Scene_polyhedron_shortest_path_item.cpp, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Scene_polyhedron_shortest_path_item.h, Surface_mesh_shortest_path/benchmark/Surface_mesh_shortest_path/benchmark_shortest_paths.cpp, Surface_mesh_shortest_path/doc/Surface_mesh_shortest_path/Concepts/SurfaceMeshShortestPathTraits.h, Surface_mesh_shortest_path/doc/Surface_mesh_shortest_path/Concepts/SurfaceMeshShortestPathVisitor.h, Surface_mesh_shortest_path/doc/Surface_mesh_shortest_path/PackageDescription.txt, Surface_mesh_shortest_path/doc/Surface_mesh_shortest_path/Surface_mesh_shortest_path.txt, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_path_sequence.cpp, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_OpenMesh.cpp, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_multiple_sources.cpp, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_no_id.cpp, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_with_id.cpp, Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h, Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path_traits.h, Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/barycentric.h, Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_1.cpp, Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_2.cpp, Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_3.cpp, Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_4.cpp, Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_test_5.cpp, Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/Surface_mesh_shortest_path_traits_test.cpp, Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/TestMesh.cpp, Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/include/CGAL/test_util.h
As reported privately by @efifogel , coordinate should be plurial.
The rename comes with a fallback for deprecated code (I locally tested that example of 4.9 and previous compiles with updated headers).
CC @Hippocrates do you agree?
=> Barycentric coordinate -> Barycentric coordinates

Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
If the content of an OBJ file is not a correct polyhedron, but a polygon soups, then the current code cannot load the file.
This PR allows to load the file anyway, producing a polyhedron with self-intersections.
=> Allow to load OBJ files containing polygon soups

Arrangement_on_surface_2/test/Arrangement_on_surface_2/cgal_test_base, CGAL_ipelets/demo/CGAL_ipelets/cgal_test_with_cmake, Minkowski_sum_2/test/Minkowski_sum_2/cgal_test_with_cmake, Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/cgal_test_with_cmake, Poisson_surface_reconstruction_3/test/Poisson_surface_reconstruction_3/cgal_test_with_cmake, Polyhedron/demo/Polyhedron/cgal_test_with_cmake, Snap_rounding_2/test/Snap_rounding_2/cgal_test_base, Sweep_line_2/test/Sweep_line_2/cgal_test_base
Add `--no-warn-unused-cli` to avoid warnings.
In #1736, I covered only `cgal_test_with_cmake` files that were auto-generated. I forgot to deal with the versions that are committed. That is the purpose of this second PR.
=> Followup to #1736

Installation/changes.html, Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h, Kernel_23/doc/Kernel_23/Concepts/FunctionObjectConcepts.h, Kernel_23/doc/Kernel_23/Concepts/Kernel.h, Kernel_23/doc/Kernel_23/PackageDescription.txt, Kernel_23/include/CGAL/Kernel/function_objects.h, Kernel_23/include/CGAL/Kernel/global_functions_2.h, Kernel_23/include/CGAL/Kernel/global_functions_3.h, Kernel_23/include/CGAL/Kernel/global_functions_internal_2.h, Kernel_23/include/CGAL/Kernel/global_functions_internal_3.h, Kernel_23/include/CGAL/Kernel/interface_macros.h, Kernel_23/test/Kernel_23/include/CGAL/_test_fct_point_2.h, Kernel_23/test/Kernel_23/include/CGAL/_test_fct_point_3.h
Add the function  `FT  l_infinity_distance(Point_2, Point_2)` as well as the corresponding functor
This is a function where the implementation is in the file
`Kernel_23/include/CGAL/Kernel/function_objects.h`
When the implementation is different for Cartesian and Homogeneous coordinates
the code should go into the `function_objects.h` files
in the packages Cartesian_kernel and Homogeneous_kernel
This fixes the 2D version of the Issue #1624 
Small feature: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_L_Infinity_Distance()
Pre-approved: 18 November 2016
=> Kernel_23: Add the function  FT  l_infinity_distance() for 2D and 3D points

Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp
This PR is an enhancement to the Polyhedron demo's shortest path computation function.
The main change is that a visitor is passed to boost's Dijkstra shortest path algorithm, which stops the spreading process once the shortest path to the target has been found instead of computing the distance to all the vertices of the mesh. This change is especially noticeable when constructing small paths on large meshes.
Some minor improvements are also added (`map` > `unordered_map`, ...).
There is another instance where such visitor could be used: in the example `dijkstra.cpp` of `BGL`'s examples, but I don't think the loss of clarity is worth the speed gain in an example.
=> Improved the computation of shortest paths in the polyhedron demo

Installation/cmake/modules/FindGMP.cmake
fixes #439, needs #1759 in conjunction, also mpir must be patched to include https://github.com/wbhart/mpir/commit/b84e7e24ca24fd4a965017ff56c25728d2d10fdc (not included in latest 2.7.2 as of writing)
=> MPIR support

BGL/include/CGAL/boost/graph/split_graph_into_polylines.h, Mesh_3/include/CGAL/Mesh_3/Protect_edges_sizing_field.h, Mesh_3/include/CGAL/Mesh_3/polylines_to_protect.h, Mesh_3/include/CGAL/Mesh_domain_with_polyline_features_3.h, Mesh_3/include/CGAL/internal/Mesh_3/Handle_IO_for_pair_of_int.h
The main goal of this PR is to fix a bug introduced by #1524 (for CGAL-4.9.1). This PR also improves or adds minor fixes:
- in `polylines_to_protect`, change the split angle from 135° to 90°,
- improve debug messages,
- fix `CGAL_MESH_3_PROTECTION_DEBUG` with a mesh domain where the
`Surface_patch_index` is `pair<int, int>`.
=> Fix the patch from #1524

Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
This PR fixes #1754 . We use floats instead of doubles in the Scene_point_with_normals_item to reduce the needed memory.
This is a temporary fix, as we only gain a factor 2 in the acceptable memory size. A better fix could be to split the data into several VBOs.
=> Polyhedron_demo : Use floats in the Point_with_normals_item

Solver_interface/include/CGAL/Eigen_diagonalize_traits.h
Eigen provides [a faster implementation](https://eigen.tuxfamily.org/dox/classEigen_1_1SelfAdjointEigenSolver.html#afe520161701f5f585bcc4cedb8657bd1) for matrix diagonalization (if the dimension is 2x2 or 3x3 which is pretty much all that CGAL uses). This PR makes this implementation used by default.
There is indeed a noticeable gain of performance (from 4.5 to 3.0 seconds on my test computing covariance matrices on 6 nearest neighbors for each points on a sphere sampled by 10 million points).
I added a commentary and the possibility to fallback to the slower version for precision issues.
=> Use faster Eigen implementation for diagonalization

BGL/include/CGAL/boost/graph/helpers.h
These functions now produce a surface mesh with face normals directed outside the volume.
=> BGL reorient make_tetrahedron() and make_hexahedron()

Documentation/doc/biblio/cgal_manual.bib, Installation/changes.html, Point_set_processing_3/doc/Point_set_processing_3/PackageDescription.txt, Point_set_processing_3/doc/Point_set_processing_3/Point_set_processing_3.txt, Point_set_processing_3/doc/Point_set_processing_3/examples.txt, Point_set_processing_3/examples/Point_set_processing_3/CMakeLists.txt, Point_set_processing_3/examples/Point_set_processing_3/scale_estimation_2d_example.cpp, Point_set_processing_3/examples/Point_set_processing_3/scale_estimation_example.cpp, Point_set_processing_3/include/CGAL/estimate_scale.h
Pre-approved [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Automatic_Scale_Estimation), ready to be tested.
Note by @lrineau: the feature was pre-approved by @palliez, 4 November 2016, and nobody has objected since then. The small feature is thus de facto accepted.
=> Automatic Scale Selection

CGAL_Core/include/CGAL/CORE/ExprRep.h, CGAL_Core/include/CGAL/CORE/Expr_impl.h, CGAL_Core/include/CGAL/CORE/Impl.h, CGAL_Core/include/CGAL/CORE/RealRep.h
This PR allows to compile whole CGAL with `-fvisibility=hidden` with gcc and clang.
=> CGAL_Core: fix -fvisibility issues on Linux

Box_intersection_d/doc/Box_intersection_d/PackageDescription.txt, Convex_decomposition_3/doc/Convex_decomposition_3/PackageDescription.txt, Convex_hull_3/doc/Convex_hull_3/PackageDescription.txt, Jet_fitting_3/doc/Jet_fitting_3/PackageDescription.txt, Mesh_3/doc/Mesh_3/PackageDescription.txt, Minkowski_sum_3/doc/Minkowski_sum_3/PackageDescription.txt, Nef_3/doc/Nef_3/PackageDescription.txt, Point_set_3/doc/Point_set_3/PackageDescription.txt, Point_set_processing_3/doc/Point_set_processing_3/PackageDescription.txt, Point_set_shape_detection_3/doc/Point_set_shape_detection_3/PackageDescription.txt, Poisson_surface_reconstruction_3/doc/Poisson_surface_reconstruction_3/PackageDescription.txt, Polygon_mesh_processing/doc/Polygon_mesh_processing/PackageDescription.txt, Polyhedron/doc/Polyhedron/PackageDescription.txt, Principal_component_analysis/doc/Principal_component_analysis/PackageDescription.txt, Subdivision_method_3/doc/Subdivision_method_3/PackageDescription.txt, Surface_mesh_deformation/doc/Surface_mesh_deformation/PackageDescription.txt, Surface_mesh_parameterization/doc/Surface_mesh_parameterization/PackageDescription.txt, Surface_mesh_segmentation/doc/Surface_mesh_segmentation/PackageDescription.txt, Surface_mesh_shortest_path/doc/Surface_mesh_shortest_path/PackageDescription.txt, Surface_mesh_simplification/doc/Surface_mesh_simplification/PackageDescription.txt, Surface_mesh_skeletonization/doc/Surface_mesh_skeletonization/PackageDescription.txt
This PR fixes #1515.
It replaces all the link texts by "Polyhedron demo"
=> Unify the links to the Polyhedron demo in the package descriptions.

Advancing_front_surface_reconstruction/examples/Advancing_front_surface_reconstruction/CMakeLists.txt, Point_set_processing_3/examples/Point_set_processing_3/CMakeLists.txt, Point_set_processing_3/test/Point_set_processing_3/CMakeLists.txt
Suppress warnings for VC 32bit compilation in 2 CMakeLists.txt
This should fix a warning in the examples of Advancing Front and in Point Set Processing reported in Issue #1806.
(Fix #1806)
=> Point Set Structuring: Suppress warnings for VC 32bit

Point_set_processing_3/examples/Point_set_processing_3/property_map.cpp, Property_map/include/CGAL/property_map.h
Fixes  #1809 
I consider this as a bug and should target 4.10
=> make Nth_of_tuple_property_map compatible with std::tuple

Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Efficient_RANSAC.h
Fix for https://github.com/CGAL/cgal/issues/1818.
The problem comes from calling `get_default_random()(m_indices.size())` with `m_indices.size()==0`. The random number is picked in `(0,size-1)`, and `0-1` is not something we want to do with unsigned numbers...
=> Shape detection: fix segfault

Advancing_front_surface_reconstruction/include/CGAL/Advancing_front_surface_reconstruction.h
which had a division by 0 with 'flat' cells. 
Fix #1817 .
=> Advancing_front_reconstruction: Robustify a call to squared_radius 

Polyhedron/demo/Polyhedron/Plugins/PMP/Distance_plugin.cpp, Polyhedron/demo/Polyhedron/cgal_test_with_cmake
This PR removes a `typename` that causes a compilation error on msvc :
"C2899: typename cannot be used outside a template declaration"
The compilation error was introduced by PR #1578
=> Demo Distance_plugin : fix compilation error

Stream_support/include/CGAL/IO/io.h
VC 2017 is even a little bit faster than our code using scanf and parsing doubles.
=> Stream_support: No need for replacement of istream >> double for VC++

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_widget.ui, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item_k_ring_selection.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
This PR fixes #1775 
It adds conversion between edges selection and adjacent facet selection, and between facets selection and bounding edges selection.
It also adds a lasso selection.
=> Polyhedron demo : extend selection

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane.h, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp
This PR adds a slider to the polyline_item's context menu to make its width editable.
=> Polyhedron demo : make polylines width editable

Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h, Three/include/CGAL/Three/Scene_draw_interface.h, Three/include/CGAL/Three/Viewer_interface.h
This PR fixes #1706 :
Recomputes the ids in Scene_polyhedron_item::invalidateOpenGLBuffers()
=> Polyhedron_demo : Update the ids when the item's geometry is changed

Polyhedron/demo/Polyhedron/MainWindow.cpp
When Save as is called from menuFile, the sender is not an item. To fix it, use mainSelectionItem when no item is found as sender.
=> Polyhedron_demo: Fix the Save as option

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/Surface_mesh_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h
This PR :
- fixes various bugs in the selection_plugin
- Specifies the wanted extension of the file being saved in the IO Dialog
- Fixes the "Duplicate Filter" warning
- Makes all selection_item's simplices dependent of its selected color, to help distinguish between multiple selection_items.
=> Polyhedron demo : various fixes and enhancements

Filtered_kernel/include/CGAL/Lazy.h
Any const functor from Epeck defining the nested struct `result` could not call any `operator()`
* Affected package(s): Filtered kernel
=> Add missing const

AABB_tree/include/CGAL/internal/AABB_tree/AABB_ray_intersection.h
Fix a bug in `AABB_tree::first_intersection()` when the ray-primitive intersection is a segment, the relative distance is the min relative distance of its endpoints.
* Affected package(s): AABB-tree
* Issue(s) solved (if any): fix #1850
=> handle the case when the ray intersection is a segment

STL_Extension/doc/STL_Extension/CGAL/array.h
This fixes 2 documentation bugs:
- `make_array()` is currently documented as `CGAL::cpp11::make_array()` whereas it isn't actully in the `cpp11` namespace (it's just `CGAL::make_array()`)
- the template arguments for `CGAL::cpp11::array` are a type `T` and an `int`. This second argument should be a `std::size_t` (this is the case both in the [STL version](http://fr.cppreference.com/w/cpp/container/array) and in the [Boost version](http://www.boost.org/doc/libs/1_62_0/doc/html/boost/array.html)).
* Affected package(s): STL_Extensions (doc only)
=> Documentation bugfixes for arrays

Spatial_searching/doc/Spatial_searching/CGAL/Fuzzy_iso_box.h, Spatial_searching/doc/Spatial_searching/CGAL/Fuzzy_sphere.h, Spatial_searching/doc/Spatial_searching/Spatial_searching.txt, Spatial_searching/examples/Spatial_searching/circular_query.cpp, Spatial_searching/examples/Spatial_searching/searching_with_circular_query.cpp, Spatial_searching/include/CGAL/Fuzzy_iso_box.h, Spatial_searching/include/CGAL/Fuzzy_sphere.h, Spatial_searching/test/Spatial_searching/Circular_query.cpp, Spatial_searching/test/Spatial_searching/Iso_rectangle_2_query.cpp, Spatial_searching/test/Spatial_searching/Range_searching.cpp, Spatial_searching/test/Spatial_searching/iso_rectangle_2_query_2.cpp
This PR is a more exhaustive version of https://github.com/CGAL/cgal/pull/1773.
The core of the PR is the reversion of some old commits of mine that modified the behavior of Fuzzy query items such that points on the boundary of the inner approximation would always be reported (commits c0cbdab and 5ed7255). Additionally to introducing some bugs in Fuzzy sphere items (https://github.com/CGAL/cgal/issues/1723), these changes are not logically pleasing and are thus reverted. Along the way, related examples/tests are fixed and the documentation was clarified.
To make sure that points on the boundary of the inner approximation are always found, one should for now grow the query item (through its radius, and not epsilon!). That is not completely satisfying, but it's the lesser evil.
=> Spatial searching: Fix fuzzy query items

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/distance.h
Move a class with a generic name outside CGAL namespace
=> Avoid namespace pollution

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.cpp
This PR fixes the segfault that occurs when the Edit_polyhedron_plugin is called on an item without offset.
* Affected package(s): Polyhedron_demo
=> Polyhedron_demo: Fix Edit_polyhedron_plugin

.travis.yml
A lot of jobs randomly fail with:
```
The command "sudo -E apt-add-repository -y "ppa:kalakris/cmake"" failed and exited with 1 during .
```
Let's try to remove that PPA. If Travis can build our jobs without that PPA, that will remove one point of failure.
=> Try without the PPA kalakris-cmake

Mesh_3/include/CGAL/Mesh_3/tet_soup_to_c3t3.h, Polyhedron/demo/Polyhedron/C3t3_type.h, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/C3t3_rib_exporter_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Optimization_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_3.qrc, Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/resources/shader_c3t3.f, Polyhedron/demo/Polyhedron/resources/shader_c3t3.v, Polyhedron/demo/Polyhedron/resources/shader_c3t3_tets.v, Three/include/CGAL/Three/Scene_item.h, Three/include/CGAL/Three/Viewer_interface.h
This PR:
- provides a reader for the .mesh files
-  allows the c3t3_io_plugin of the Polyhedron_demo to load tetrahedron soups from .mesh files into "invalid" Scene_c3t3_items. 
- Adds statistics to the scene_c3t3_item
- Adds a slider to _shrink_ the facets of a scene_c3t3_item (by using the slider in the item's context menu or using + and - ).
* Affected package(s): Polyhedron_demo, Mesh_3
* Issue(s) solved (if any): fix #1851
=> Add a .mesh reader

Point_set_3/include/CGAL/Point_set_3.h, Polyhedron/demo/Polyhedron/Plugins/PMP/Orient_soup_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp, Surface_mesh/include/CGAL/Surface_mesh/IO.h, Surface_mesh/include/CGAL/Surface_mesh/Properties.h, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h, Surface_mesh/include/CGAL/boost/graph/properties_Surface_mesh.h, Surface_mesh/test/Surface_mesh/surface_mesh_test.cpp
The PR #1791 introduced `CGAL::Point_set_3`, and factorized the
`Property_map` implementation of `Surface_mesh` into a new class
template `CGAL::Properties::Property_map<Key, T>`.
The backward compatibility was supposed to be ensured by the fact that
`Surface_mesh<Point>::Property_map<Key,T>` had
`Properties::Property_map<Key, T>` as base class. But that compatibility
was only partial, and there could be ambiguities in the calls to `get`
and `put` with those property maps.
This commit/PR renamed `Properties::Property_map` to
`Properties::Property_map_base`, and added a third parameter, used as
the `Derived` class in the CRTP used by `boost::put_get_helper`. That
way, the `get` and `put` functions are defined directory on the real
class `Surface_mesh::Property_map<Key, T>` and not on its …
=> Fix <CGAL/Surface_mesh/Properties.h> introduced by #1791

Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h
This PR allows the Scene_points_with_normal_item to keep its point_size and normal_size if any when it is reloaded.
* Issue(s) solved (if any): fix #1889 
=> Polyhedron_demo: Keep the point's size when reloading

Polyhedron/demo/Polyhedron/Scene_polyhedron_item_k_ring_selection.h
This PR fixes a bug that happened when the brush size was not 0 with the highlighting in the selection_plugin.
* Affected package(s): Polyhedron_demo
=> Polyhedron_demo: Fix the highlighting in the selection_plugin

Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp
This PR fixes the display of degenerated polygon soups and avoids a crash when a face uses several times the same vertices.
* Issue(s) solved (if any): fix #1897
=> Polyhedron_demo: Discard degenerated faces in elements computation

Poisson_surface_reconstruction_3/include/CGAL/Reconstruction_triangulation_3.h, Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_hierarchy_2.h, Spatial_sorting/include/CGAL/hilbert_sort.h, Spatial_sorting/include/CGAL/hilbert_sort_on_sphere.h, Spatial_sorting/include/CGAL/spatial_sort.h, Spatial_sorting/include/CGAL/spatial_sort_on_sphere.h
Should fix that warning:
```
c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.24930\include\algorithm(1782): warning C4244: 'argument': conversion from '_Diff' to 'long', possible loss of data
c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.24930\include\algorithm(1796): note: see reference to function template instantiation 'void std::_Random_shuffle_unchecked<CGAL::Point_3<Kernel_>*,_RngFn>(_RanIt,_RanIt,_RngFn &)' being compiled
with
[
Kernel_=CGAL::Simple_cartesian<float>,
_RngFn=boost::random::random_number_generator<boost::random::rand48,long>,
_RanIt=CGAL::Point_3<CGAL::Simple_cartesian<float>> *
]
c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.24930\include\algorithm(1815) …
```
=> Fix  warnings with MSVC 2017

Point_set_processing_3/include/CGAL/wlop_simplify_and_regularize_point_set.h
WLOP gives different results in parallel and sequential versions. This is because the parallel version wrongly uses the radius instead of the squared radius. This PR fixes this.
* Affected package(s): Point Set processing
=> WLOP Bugfix: use radius2 in parallel version too

CGAL_Core/include/CGAL/CORE/ExprRep.h, Number_types/test/Number_types/CORE_Expr.cpp
The sign of a `CORE::Expr` is certified by computing approximations up to a given precision. The precision bound is computed thanks to a formula taking child nodes into account.
When evaluating the sign, the approximation with the full precision is not computed directly.
Instead, approximations with lower precision are computed while a certified answer is possible.
This patch makes sure that the approximation computed is larger than the theoretical bound.
In the test function added, the precision bound was 223 but the way the intermediate precision is increased was computing the approximation at 128, but the next one at 256 was ignored (since larger than 223). The patch the approximation precision is exceeded.
* Affected package(s): CORE
* Issue(s) solved (if any): fix #414
=> Make sure the approximation exceeds the separation bound

CGAL_Core/include/CGAL/CORE/ExprRep.h, CGAL_Core/include/CGAL/CORE/Expr_impl.h, Number_types/test/Number_types/CORE_Expr.cpp
When the lower bound of the Most Significant Bit (MSB) is too large or too small, the evaluation of ExprRep was not done.
From what I understand, the code is able to handling it.
This was reveled by the test added. What happen is that the lower bound of MSB, computed with:
```
/// lower bound on MSB
/** defined to be cel(lg(real value));
ilogb(x) is floor(log_2(|x|)). 
Also, ilogb(0) = -INT_MAX.  ilogb(NaN) = ilogb(+/-Inf) = INT_MAX */
extLong lMSB() const {
return extLong(ilogb(core_abs(fpVal)-maxAbs*ind*CORE_EPS));
}
```
is `INT_MAX` because of the operation _4.0000000000000000 - 4.0000000000000009_ that is close to 0.
Then, without the current patch the approximation was not refined and an erroneous decision was taken when computing a determinant (`Gmpq` is used as ground truth here …
=> Fix Expr computation when a Node in the tree has a large MSB bound

Mesh_3/include/CGAL/Mesh_3/Detect_features_in_polyhedra.h, Mesh_3/include/CGAL/Mesh_3/Detect_polylines_in_polyhedra.h, STL_Extension/include/CGAL/Compare_handles_with_or_without_timestamps.h, STL_Extension/include/CGAL/Time_stamper.h
Fix an old non-determinism bug in
`<CGAL/Mesh_3/Detect_features_in_polyhedra.h>`.
=> Fix non-determinism!

Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp, Polyhedron/demo/Polyhedron/Polyhedron_3.qrc, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h, Polyhedron/demo/Polyhedron/resources/shader_flat.f, Polyhedron/demo/Polyhedron/resources/shader_with_light.v, Three/include/CGAL/Three/Scene_item.h, Three/include/CGAL/Three/Viewer_interface.h
- Use indexed drawing for Edges and gouraud.
- Remove Edge_colors as it is never used
- Use only 3 coordinates for vertices (stop filling 1.0 everywhere)
- Add a toggle for the Flat shading and automatic detection for disabling it at item's creation
- Use special shader for flat rendering in which normals are computed inside the fragment shader.
- Factorize program creation in Viewer.cpp
- use shrink_to_fit() in Scene_surface_mesh_item
=> Polyhedron demo: OFF_plugin optimizations

Point_set_shape_detection_3/test/Point_set_shape_detection_3/test_regularization.cpp, STL_Extension/doc/STL_Extension/CGAL/Iterator_range.h, STL_Extension/include/CGAL/Iterator_range.h
Currently, our `CGAL::Iterator_range` has a method `size()` which returns a signed integer (`difference_type`). This is probably due to the fact that we use `std::distance()` to compute it, which does return a signed number.
However, it seems very counter-intuitive to have a signed size (a range where `begin()` is after `end()` souldn't be valid anyway) and it leads to warnings if a user does a comparison of `size()` with an unsigned integer (this is how I discovered this problem). In addition, the [boost::iterator_range](http://www.boost.org/doc/libs/1_55_0/libs/range/doc/html/range/reference/utilities/iterator_range.html) that we cloned (as the documentation says) uses an unsigned type.
This PR makes `CGAL::Iterator_range::size()` return a `std::size_t` number (with a static cast …
=> Fix iterator range size type

Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Efficient_RANSAC.h, Point_set_shape_detection_3/test/Point_set_shape_detection_3/test_regularization.cpp
The `clear()` method of `CGAL::Efficient_RANSAC` states that _all internal structures are cleaned, including formerly detected shapes_, but in practice it does not clear the shape factories. It seems rather counter-intuitive: a user reported a bug on the `cgal-discuss` list (he was looping on a RANSAC object, clearing and adding a shape factory everytime, so the number of shape factories became higher and higher). This PR makes the `clear()` function also call `clear_shape_factories()`.
* Affected package(s): Point set shape detection
* Issue(s) solved (if any): (see `cgal-discuss`)
=> Point set shape detection: Fix incomplete clear

Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h
Leading whitespace has semantics, so we remove it
* Affected package(s):  Kernel_23
=> Kernel_23:  fix typesetting in the manual.

Polyhedron/demo/Polyhedron/MainWindow.cpp
Fixes the bug that happend when trying to recenter an offseted scene and the offset had not change.
=> Fix offset bug in polyhedron_demo

BGL/test/BGL/test_Prefix.h
Strange that the assert(f2 !=null_face) was always true !!
Bug fix in test_Prefix
=> Bug fix in test_Prefix

BGL/include/CGAL/boost/graph/split_graph_into_polylines.h
The order used to sort vertex descriptors was not correct and ended up in some cases to identify the wrong vertex in the set. Using the default is fine since no vertex is removed.
See [_Iterator and Descriptor Stability/Invalidation_](http://www.boost.org/doc/libs/1_63_0/libs/graph/doc/adjacency_list.html), and more particularly the table at the end.
=> Fix bug in split_graph_into_polylines

Generator/doc/Generator/CGAL/point_generators_3.h
Fix phrasing in the ref manual of `Random_points_in_sphere_3`.
* Issue(s) solved (if any): fix #1978
=> Generator: doc fix

Polyhedron/demo/Polyhedron/include/CGAL/IO/read_surf_trianglemesh.h
This PR intends to fix the behavior of the `.surf` reader when the input surface is non-manifold.
Because `CGAL::Polyhedron_3` cannot handle a non-manifold surface, the built polyhedron has holes wherever the builder tries to make a non-manifold configuration.
We use `PMP::orient_polygon_soup` and `PMP::polygon_soup_to_polygon_mesh` to build a valid polygon mesh, which can be a `CGAL::Polyhedron_3` with duplicated vertices on geometrically non-manifold edges/vertices.
=> Polyhedron demo : fix surf reader

BGL/test/BGL/test_graph_traits.cpp, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h, Surface_mesh/test/Surface_mesh/surface_mesh_test.cpp
I added an assertion in the testsuite, that confirmed the bug report, fixed the bug and completed the documentation, as an isolated vertex is also considered as a border vertex.
* Issue(s) solved (if any): fix #1949
=> Surface_mesh: Fix #1949

Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_polycurve_traits_2.h, Arrangement_on_surface_2/doc/Arrangement_on_surface_2/CGAL/Arr_polyline_traits_2.h, Arrangement_on_surface_2/include/CGAL/Arr_polyline_traits_2.h
This is a pull request for a bug fix in the documentation of the Arr_polycurve_traits_2 class template, it's nested types Arr_polycurve_traits_2::Curve_2 and Arr_polycurve_traits_2::X_monotone_curve_2, the documentation of the Arr_polyline_traits_2 class template, and small fix to the Arr_polyline_traits_2 class template itself.
1. Documentation 
1.1. The documentation of Arr_polycurve_traits_2 did not reflect the code.
A polycurve is a sequence of curves, which do not need to be linear. In fact, they can even be algebraic. In the code we refer to them as subcurves, while in the documentation we used to refer to them as segments. The fix consist of replacing the string 'segment' with the string 'subcurve' in the name of the template parameters, nested types, nested functions, and variable …
=> Aos 2 polycurve efif

Polyhedron/demo/Polyhedron/Plugins/IO/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/IO/Surf_to_sm_io_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h, Polyhedron/demo/Polyhedron/include/CGAL/IO/read_surf_trianglemesh.h
- Add a plugin to read a surf in surface_meshes
- Add a constructor to the Scene_surface_mesh_item that takes a SMesh.
* Issue(s) solved (if any): Polyhedron_demo, fix CGAL/GeometryFactory#4
=> Polyhedron_demo: Surf_to_sm_io_plugin

Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
Iterators of Point_set_3 are invalidated when removing (selecting in the demo) one point. A remaining of the old API of the demo's Point_set_3 was producing a bug (not selecting all duplicate points). This is a fix for this.
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/1928
=> Polyhedron demo: fix duplicated points selection

Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h, Polyhedron/demo/Polyhedron/Scene_item.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h, Three/include/CGAL/Three/Scene_item.h
Add a function to Scene_item that allows to delete things when the signal aboutToBeDestroyed is called, and use it on the big-data items so the memory is freed when it must be.
* Affected package(s): Polyhedron_demo
* Issue(s) solved (if any): fix #1957
=> Polyhedron_demo: Enhance memory management in the demo

README.md
grammar error:
The compilation and installation of CGAL from a sources tarball **is described** in the CGAL installation
"is" -> "are"
Fix #2011
=> Fix grammar error in readme.md

.travis/build_package.sh, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h
Adds `Q_DECL_OVERRIDE` where it was missing to fix the clang warnings
* Issue(s) solved (if any): fix #2026
=> Polyhedron_demo : Add Q_DECL_OVERRIDE

Point_set_3/include/CGAL/Point_set_3.h
This PR fixes two problems:
1. The point set index violates the `Index` concept as the constructor using a `size_t` is private (this was done to avoid some mis-usage of the point set but should be removed)
2. The index map is using a `std::size_t` which can lead to an overly large memory usage when loading very big point sets. This PR makes it use `boost::uint32_t` which should be half the size and can still address more than 4 billion points. Anyway, loading more than 4 billion points requires at least 50GB of RAM with `CGAL::Simple_cartesian<float>`, which is not common at the moment. I added a `#ifdef` macro `CGAL_POINT_SET_3_USE_STD_SIZE_T_AS_SIZE_TYPE` which is undefined by default so that a user who actually needs to load more than 4 billion points can still do it.
* Affected …
=> Point set 3: fix index type

AABB_tree/doc/AABB_tree/aabb_tree.txt, Arrangement_on_surface_2/include/CGAL/Arr_geometry_traits/Circle_segment_2.h, Boolean_set_operations_2/examples/Boolean_set_operations_2/circle_segment.cpp, Kernel_23/doc/Kernel_23/CGAL/Filtered_kernel.h, Minkowski_sum_2/doc/Minkowski_sum_2/CGAL/Polygon_triangulation_decomposition_2.h
Just a few typo fixes that i have accumulated while reading the online documentation
* Affected package(s): AABB_tree, Arrangement_on_surface_2,  Boolean_set_operations_2,  Kernel_23 and  Minkowski_sum_2
=> Fix a few typos in the documentation

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h
splitted -> split  (see [wiktionary](https://en.wiktionary.org/wiki/splitted))
=> Polygon_mesh_processing: Fix documentation

Polyhedron/demo/Polyhedron/Plugins/PMP/Distance_plugin.cpp, Polyhedron/demo/Polyhedron/triangulate_primitive.h
If a facet is too small, a precision problem will cause it's triangulation to fail. This PR fixes the resulting segfault by stopping the triangulation process if there are too few points, and not display the facet. As it only happens for facets with a diagonal smaller than 0.0001 times the item's Bbox's diagonal, the user should not even notice it unless he(she) is looking for it. 
A message is displayed in the console in that case.
=> Polyhedron_demo: Fix segfault in distance_item 

Polyhedron/demo/Polyhedron/Scene.cpp
The `itemAboutToBeDestroyed()` signal is emitted in `replaceItem()`, so the d-pointer of some items gets deleted, but is called in `isEmpty()`, which is also called in `replaceItem()` when the Bbox is recomputed.
The fix is to move the call to `itemAboutToBeDestroyed()` after the item is used for the last time in `replaceItem()`.
* Issue(s) solved (if any): fix #2080
=> Polyhedron_demo: Fix segfault in Scene::replaceItem().

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/MainWindow.h
Add an action to the menuFile to reset the default_loaders_map, allowing the user to choose the loader for all items again, even if alwaysUse was checked.
This action appears if alwaysUse is checked, and disappears when it is clicked.
* Issue(s) solved (if any): fix #2008
=> Polyhedron_demo : Reverse alwaysUse

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h, Polyhedron/demo/Polyhedron/Plugins/IO/Surf_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/Surf_to_sm_io_plugin.cpp, Polyhedron/demo/Polyhedron/include/CGAL/IO/read_surf_trianglemesh.h
This PR introduces improvement to the `.surf` reader, and the corresponding plugins.
- deal with non-manifold surfaces (there were holes in the generated surfaces, next to non-manifold configurations)
- number materials from `0` (Exterior) to `n-1` to make sure Mesh_3 will not get into trouble
- ignore isolated vertices
- reduce memory footprint
* Affected packages : Polyhedron demo, PMP (internal code only)
=> Polyhedron demo : improve .surf reader

Principal_component_analysis/doc/Principal_component_analysis/CGAL/linear_least_squares_fitting_3.h, Principal_component_analysis/examples/Principal_component_analysis/CMakeLists.txt, Principal_component_analysis/include/CGAL/PCA_util_Eigen.h, Principal_component_analysis/include/CGAL/linear_least_squares_fitting_3.h, Principal_component_analysis/test/Principal_component_analysis/CMakeLists.txt, Principal_component_analysis/test/Principal_component_analysis/test_linear_least_squares_fitting_cuboids_3.cpp, Principal_component_analysis/test/Principal_component_analysis/test_linear_least_squares_fitting_segments_3.cpp, Principal_component_analysis/test/Principal_component_analysis/test_linear_least_squares_fitting_spheres_3.cpp, Principal_component_analysis/test/Principal_component_analysis/test_linear_least_squares_fitting_tetrahedra_3.cpp, Principal_component_analysis/test/Principal_component_analysis/test_linear_least_squares_fitting_triangles_3.cpp
- Specialization of `assemble_covariance_matrix_3()` when `CGAL::Eigen_diagonalize_traits` is used, so that we stop relying on `Linear_algebraCd` internally (which is very slow) and use the Eigen library instead (which is by definition available if `CGAL::Eigen_diagonalize_traits` is used)
- Addition of lines in the test files so that both the Eigen and internal CGAL versions are tested
- Addition of notes in the doc to advise the user to use Eigen (which is much faster)
* Affected package(s): Principal Component Analysis
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/2069
=> Principal component analysis: Enhance matrix assembly

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
Fix a bug when the face range to remesh is incident to the boundary of the mesh.
Vertices that are at the "corner" of the face range to be remeshed,
i.e. on the border of the face range, and also on the border of the mesh,
incident to both the selected and unselected faces, should be constrained,
to avoid making a "axe blow" in the border
=> PMP : fix isotropic remeshing of a selection

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp
The PROGRAM_FLAT allows to save memory by not keeping the flat normals and computing them in real time in the fragment shader, but it loses the orientation of the faces. To fix it, we decided to drop this enhancement in the case the draw_two_sides option is set, and keep computing the flat normals.
* Issue(s) solved (if any): fix #2103 
=> Polyhedron_demo: Fix draw two sides for Polyhedron

Mesh_3/include/CGAL/Mesh_3/Mesh_complex_3_in_triangulation_3_base.h
Provide an overload of tbb_hasher for a pair of CCC_iterators in the Concurrent_compact_container.
After a mail exchange on cgal-discuss, where @mglisse wrote:
> My first reaction was that hashing a std::pair should already do some mixing, but apparently TBB uses a simplistic implementation with just a XOR. This means for instance that the pairs (first, second) and (third, fourth) are likely to both have hash 1, and all pairs (x,x) have the same hash 0. Boost seems to combine hashes in a pair more cleverly, does that help?
It did help. thanks.
I did not do any benchmarking.  @cjamin do you know how important this concurrent_hash_map is?
* Issue(s) solved (if any): fix #2049
=> Mesh_3: Address TBB performance warning on hashing

Optimal_transportation_reconstruction_2/include/CGAL/Optimal_transportation_reconstruction_2.h
Fix unused variable.
* Affected package(s): Optimal_transportation_reconstruction_2
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/2111
=> OT Reconstruction: fix warning unused variable

Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Curve_analysis_2.h, Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Curve_pair_analysis_2.h, Algebraic_kernel_d/include/CGAL/Algebraic_kernel_d/Event_line_builder.h
=> Algebraic_kernel_d: Remove dynamic exception specification. Fix of #1886

Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp, Mesh_3/examples/Mesh_3/mesh_polyhedral_domain_with_features.cpp, Mesh_3/examples/Mesh_3/mesh_polyhedral_domain_with_lipschitz_sizing.cpp, Mesh_3/examples/Mesh_3/remesh_polyhedral_surface.cpp, Polygon_mesh_processing/examples/Polygon_mesh_processing/isotropic_remeshing_example.cpp, Polygon_mesh_processing/examples/Polygon_mesh_processing/mesh_slicer_example.cpp, Polygon_mesh_processing/examples/Polygon_mesh_processing/point_inside_example.cpp, Polygon_mesh_processing/examples/Polygon_mesh_processing/point_inside_example_OM.cpp, Polygon_mesh_processing/examples/Polygon_mesh_processing/refine_fair_example.cpp, Polygon_mesh_processing/examples/Polygon_mesh_processing/self_intersections_example.cpp, Surface_mesh_segmentation/examples/Surface_mesh_segmentation/sdf_values_example.cpp, Surface_mesh_segmentation/examples/Surface_mesh_segmentation/segmentation_from_sdf_values_OpenMesh_example.cpp, Surface_mesh_segmentation/examples/Surface_mesh_segmentation/segmentation_from_sdf_values_SM_example.cpp, Surface_mesh_segmentation/examples/Surface_mesh_segmentation/segmentation_from_sdf_values_example.cpp, Surface_mesh_segmentation/examples/Surface_mesh_segmentation/segmentation_via_sdf_values_example.cpp, Surface_mesh_segmentation/examples/Surface_mesh_segmentation/segmentation_with_facet_ids_example.cpp, Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_OpenMesh.cpp, Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_all_short_edges.cpp, Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrain_sharp_edges.cpp, Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrained_border_polyhedron.cpp, Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrained_border_surface_mesh.cpp, Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_enriched_polyhedron.cpp, Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_polyhedron.cpp, Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_surface_mesh.cpp, Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_example.cpp, Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/MCF_Skeleton_sm_example.cpp, Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/segmentation_example.cpp, Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/simple_mcfskel_example.cpp, Surface_mesh_skeletonization/examples/Surface_mesh_skeletonization/simple_mcfskel_sm_example.cpp
This PR improves the examples given in the packages `Polygon_mesh_processing` and `Surface_mesh_simplification` by adding a condition to run them : the input mesh needs to be a triangle mesh.
* Affected packages :  `Polygon_mesh_processing` and `Surface_mesh_simplification`
* Issue solved : fix #2050
=> PMP and SMS : improve examples with a (pre)condition

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/MainWindow.h, Polyhedron/demo/Polyhedron/MainWindow.ui, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene.h, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Polyhedron/demo/Polyhedron/Viewer.cpp, Three/include/CGAL/Three/Scene_draw_interface.h, Three/include/CGAL/Three/Scene_zoomable_item_interface.h
This PR adds two features to the demo :
- The possibility to set a different color for each item of the current selection, so they are easier to distinguish, (automatically used when loading several items at the same time)
- The possibility to zoom on a picked facet from a polyhedron_item, or the current selection of points in a scene_points_with_normal_item, using a fitting plane. This can be performed using Z + left click.
* Issue(s) solved (if any): fix #2037
=> Polyhedron_demo: color and camera

BGL/doc/BGL/PackageDescription.txt, BGL/include/CGAL/boost/graph/selection.h
For each group there is a line in a generated table of the entry page of the reference manual.
* Adding a sentence improves this table
* On the page of the group with functions I added the name of the header file, as when the functions only have a short dfescription, the line with the `#include` is not added automatically. 
=> BGL Add a description to doxygen groups

Polygon/include/CGAL/Polygon_2.h
Add a precondition that checks the index of the vertex is not out of bounds
* Affected package(s): Polygon
* Issue(s) solved (if any): fix #2073
=> add a precondition

Circular_kernel_2/test/Circular_kernel_2/test_Line_arc.cpp
With the value of the variable random_seed == 105214 the testsuite constructed a Line_2 from two identical points, which led to an assertion in CGAL-4.11-Ic5
* Affected package(s): Circular_kernel_2
=> Circular_kernel_2: Fix testsuite

BGL/examples/BGL_polyhedron_3/copy_polyhedron.cpp
Here we need to write S (and not T1 as in the current example).
=> Bugfix in copy face graph example

Combinatorial_map/test/Combinatorial_map/Combinatorial_map_test.cpp
Remove a warning in combinatorial map test.
* Affected package(s): Combinatorial map
* Issue(s) solved (if any): fix #2112
=> Remove a warning (unused variable)

Polyhedron/demo/Polyhedron/Scene_nef_polyhedron_item.cpp
When a facet of a nef_polyhedron have a hole, the triangulation for the visualization fills it. This PR changes the external targeting of the CDT facets.
* Issue(s) solved (if any): fix #1977 
=> Fix triangulation for nef facets with holes.

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_widget.ui
The selection plugin is overly long and usually makes the left column way to high.
__Note: this PR is not ready to merge, I'm creating it so we can discuss it.__
Using tab widgets and moving stuff around, I managed to reduce the height by about 50%. It's a bit wider than before, but as screens are mainly 16/9 now, I think it's less of an issue.
The main problem remaining is the Euler operations: because of the images, the height becomes really important when clicking on the tab. Note that before, there was a bug when switching back to selection mode (the widget was dropping to the bottom) that is fixed, but now there's a bug when switching to edition mode (the widget goes over the bottom bar).
Is there a reason why this Euler operation is not in a different widget? It seems to me that …
=> Polyhedron demo: Reorganize selection plugin

Kernel_23/include/CGAL/Kernel/function_objects.h
Fixes [these errors](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-I-194/Polygon_mesh_processing/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.1_Release-LEDA-without-GMP.gz).
=> force the usage of CGAL compare function

BGL/include/CGAL/boost/graph/helpers.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/border.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/remesh.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/repair.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp, Polyhedron/demo/Polyhedron/include/CGAL/statistics_helpers.h
* only insert non-degenerate faces in the AABB-tree for the reprojection step in isotropic remeshing
* handling case when target edge length is 0 in isotropic remeshing
* bug fix in undocumented header for removal of degenerate faces
=> Polygon Mesh Processing bug fixes

Number_types/include/CGAL/Exact_integer.h, Number_types/include/CGAL/internal/Exact_type_selector.h
This needs testing / benchmarking before merging. Last time I tried, all examples I ran were slightly faster with `mpq_class` than `Gmpq` or the same speed. Another advantage is that with `CGAL_DONT_USE_LAZY_KERNEL` and `CGAL_USE_GMPXX`, this makes Epeck thread-safe.
TODO
--------
=> Use mpq_class rather than Gmpq if gmpxx is available.

Arrangement_on_surface_2/include/CGAL/Arr_geodesic_arc_on_sphere_traits_2.h, Arrangement_on_surface_2/include/CGAL/Arr_spherical_gaussian_map_3/Arr_polyhedral_sgm.h, Arrangement_on_surface_2/include/CGAL/Arr_spherical_gaussian_map_3/Arr_polyhedral_sgm_polyhedron_3.h, Arrangement_on_surface_2/test/Arrangement_on_surface_2/cgal_test.cmake, Arrangement_on_surface_2/test/Arrangement_on_surface_2/cgal_test_base, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_sgm.cpp
Fixed the Spherical Gaussian Map (undocumented) feature.
Added a test that tests the feature.
Apparently, every data structure that derives from an instance of CGAL::Polyhedron_3 must be explicitly made a model of FaceGraph by adding the appropriate boost::graph_traits and boost::property_map templates. This bug-fix simply introduces the above two templates for CGAL::Arr_polyhedral_sgm_polyhedron_3.
=> Arrangment: Spherical Gaussian Map bug fix

BGL/doc/BGL/Concepts/EdgeListGraph.h, BGL/doc/BGL/Concepts/FaceGraph.h, BGL/doc/BGL/Concepts/FaceListGraph.h, BGL/doc/BGL/Concepts/HalfedgeGraph.h, BGL/doc/BGL/Concepts/HalfedgeListGraph.h, BGL/doc/BGL/Concepts/MutableFaceGraph.h, BGL/doc/BGL/Concepts/MutableHalfedgeGraph.h, BGL/doc/BGL/Concepts/VertexListGraph.h, BGL/doc/BGL/PackageDescription.txt, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Regroup the tables for valid expressions of the various graph concepts on one page, as it is done  on [boost.org](http://www.boost.org/doc/libs/1_64_0/libs/graph/doc/graph_concepts.html), and document the free function with `\relates` to the pages of the individual concepts. 
This is WIP in order to get feedback. 
* Issue(s) solved (if any): fix #1246
=> BGL:  doxygen doc for concepts

Surface_mesh_segmentation/doc/Surface_mesh_segmentation/Surface_Mesh_Segmentation.txt
The example for `Surface_mesh`  was not in the User Manual.
* Affected package(s):  Surface_mesh_segmentation
=> Surface_mesh_segmentation: Add a Surface_mesh example at the end of the user manual 

Installation/changes.html, Spatial_searching/doc/Spatial_searching/CGAL/Kd_tree.h, Spatial_searching/include/CGAL/Kd_tree.h, Spatial_searching/include/CGAL/Kd_tree_node.h, Spatial_searching/include/CGAL/Kd_tree_rectangle.h, Spatial_searching/include/CGAL/Weighted_Minkowski_distance.h, Spatial_searching/test/Spatial_searching/remove.cpp
This adds a function to remove points from a kd-tree. It also includes various unrelated optimizations to the kd-tree, so it would be good if you could have a quick look to check that you don't find one of them objectionable.
* Feature/Small Feature (if any): https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Remove_from_Kd_tree
=> kd-tree removal + misc improvements

Cartesian_kernel/include/CGAL/Cartesian/function_objects.h
Currently, the first base of a `Plane_3` object is computed by putting the Z coordinate to 0 (except if the normal vector of the plane is the vertical vector). This is usually fine except if the normal vector is almost vertical: in that case, the coordinates of the bases are all close to 0 and that leads to very unexpected behavior for the method `to_2d()` for example. Two 3D points on a line parallel to the plane become two 2D points on the plane domain that have huge coordinates and that can't be used (distances are all wrong).
Although it is true the distances are not guaranteed to stay the same (which makes sense as there is a projection) and that inexact kernel are documented to produce inexact constructions, this case is very disturbing and quite hard to justify. See what happens if …
=> Cartesian kernel: improve plane bases computation

Polyhedron/demo/Polyhedron/Scene_group_item.cpp
If a group_item is empty, supportsRenderingMode() must return true, not false, or else the scene will enter an infinite loop as it does not expect any item returning false to every renderingMode.
=> Polyhedron_demo: Fix empty group_item RenderingMode

Filtered_kernel/include/CGAL/internal/Static_filters/Is_degenerate_3.h
Avoid the usage of `Filtered_predicate` if possible.
=> Kernel_23: Add static filtering for Plane_3

Point_set_3/include/CGAL/Point_set_3/IO.h
The `operator>>` of the class `Point_set_3` uses the first line read (tag) to estimate the format. I just realized that using a simple string comparison could lead to bugs if the file read was not generated from the same platform (the usual differences of carriage return between `\n`, `\r\n`, etc.).
Using `std::string::find()` and checking if the line starts with the tag is enough and solves the bug.
=> Point set 3: Bugfix with carriage return

Installation/cmake/modules/CGAL_add_test.cmake
Improve the CTest support. For each target, there is a new test that builds the target. The real runtime test depends on it.
=> CTest support: now CTest will build targets before the tests

Linear_cell_complex/doc/Linear_cell_complex/PackageDescription.txt
Bug fix in the doc of Linear cell complex. Following a previous refactoring, constructions are not all in "CGAL/Linear_cell_complex_constructors.h" but are in different files (given in the doc of each function).
Thus this global include is now wrong.
* Affected package(s): Linear cell complex
=> Bug fix in doc of Linear cell complex

Surface_mesh/include/CGAL/Surface_mesh/IO.h
The new compiler g++-7 has change the C++ headers dependencies. `std::algorithm` is no longer found.
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-Ic-35.shtml#Polyhedron_Demo
=> Surface_mesher IO.h: Add missing headers

Installation/config/support/print_GMP_version.cpp, Installation/config/support/print_MPFR_version.cpp
Include `<cstdio>` and `<cstddef>` to avoid a compilation error.
```
include/c++/4.9.3/cstddef:51:11: error: '::max_align_t' has not been declared
using ::max_align_t;
^
```
See https://gcc.gnu.org/gcc-4.9/porting_to.html
=> Workaround for gmp-4.2 with gcc 4.9 and C++11

Nef_3/examples/Nef_3/nef_3_simple.cpp, Nef_3/include/CGAL/Nef_polyhedron_3.h
When the underlying SNCs are empty (but a volume) the marks are not correctly ported. This is fixed by a test prior to merging SNCs
=> Fix Booleen operations with full/empty space

Testsuite/test/run_testsuite_with_cmake
This should allow picasso to build the Polyhedron demo entirely. This is the first step for automatically generate a pre-compiled demo for windows.
=> Increase timeout for polyhedron_demo in testsuite

Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp, Polyhedron/demo/Polyhedron/Scene_c3t3_item.h, Polyhedron/demo/Polyhedron/Scene_spheres_item.cpp, Polyhedron/demo/Polyhedron/Scene_spheres_item.h, Polyhedron/demo/Polyhedron/resources/shader_c3t3.f
- Fix color in shader 
- Make spheres color depends on the in_dimension of their associated vertex.
* Issue(s) solved (if any): fix #2149
=> Polyhedron_demo: Change spheres colors in c3t3

Polyhedron/demo/Polyhedron/MainWindow.cpp
Add an automatically generated name to the 'Save as...' dialog.
* Issue(s) solved (if any): fix #2162
=> Polyhedron_demo: Enhance the 'Save as' dialog

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/OFF_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Self_intersection_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp
- Removes the save/load dialog displayed after validation of the path so it doesn't mess with the cursor.
- Restores the cursor before the `No self intersection` dialog appears
=> Polyhedron_demo: Fixes for the override cursor.

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Scene.cpp
Fixes the segmentation fault that occurs  when reloading a selection_item.
=> Polyhedron_demo: Fix selection_item reloading

.travis/build_package.sh, Polyhedron/demo/Polyhedron/Plugins/AABB_tree/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene_plane_item.h
The Cut_plugin is now able to work on a Scene_surface_mesh_item as well as on a Scene_polyhedron_item.
This PR is based on #1954 
=> Polyhedron_demo: Use surface mesh item in AABB_tree package

Triangulation_2/include/CGAL/Triangulation_2.h
Minimal program producing the error:
```C++
#define protected public
#include <CGAL/Triangulation_2.h>
#include <CGAL/Simple_cartesian.h>
int main()
{
CGAL::Triangulation_2<CGAL::Simple_cartesian<double> > T;
CGAL::Simple_cartesian<double>::Point_2 p(0,0);
T.has_inexact_negative_orientation(p,p,p);
}
```
* Issue(s) solved (if any): fix #2182
=> add missing include directive to use CGAL::to_double()

Interpolation/include/CGAL/Voronoi_intersection_2_traits_3.h
Fix an error introduced by the merge of #2198 in `master` and `releases/CGAL-4.10-branch`.
(fix the `check_pkg_Interpolation_headers` target)
* Affected package(s): all packages including `<CGAL/Triangulation_2.h>`
=> Fix a compilation error in Travis

Surface_mesh_shortest_path/doc/Surface_mesh_shortest_path/Surface_mesh_shortest_path.txt, Surface_mesh_shortest_path/doc/Surface_mesh_shortest_path/dependencies, Surface_mesh_shortest_path/doc/Surface_mesh_shortest_path/examples.txt, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/CMakeLists.txt, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_path_sequence.cpp, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths.cpp, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_OpenMesh.cpp, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_multiple_sources.cpp, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_no_id.cpp, Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_with_id.cpp
In the examples change from `Polyhedron` to `Surface_mesh`, but keep two examples that shows how to use `Polyhedron_3` either with items with id, or with an external  map for the indices. 
@sloriot I am wondering what the best choice for  the `typedef` of `Surface_mesh` or `Polyhedron_3` is.
* Affected package(s): Surface_mesh_shortest_path
=> Surface_mesh_shortest_path:  Use Surface_mesh

Installation/changes.html, Poisson_surface_reconstruction_3/doc/Poisson_surface_reconstruction_3/Poisson_surface_reconstruction_3.txt, Poisson_surface_reconstruction_3/doc/Poisson_surface_reconstruction_3/examples.txt, Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/CMakeLists.txt, Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/poisson_reconstruction_function.cpp, Poisson_surface_reconstruction_3/include/CGAL/poisson_surface_reconstruction.h
This adds a syntaxic sugar simple function for the Poisson reconstruction algorithm (which, at the moment, is pretty complicated to use as it lets the user do everything after computing the implicit function). This is a small feature.
* Affected package(s): Poisson Surface Reconstruction
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/1659
* [Small Features/Provide_simple_function_for_Poisson_Reconstruction](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Provide_simple_function_for_Poisson_Reconstruction) (pre-approved by Pierre Alliez, 2017/06/12)
=> Poisson reconstruction: Provide a simple function

BGL/include/CGAL/boost/graph/helpers.h, Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_3_plugin_cgal_code.h
fixes issue #1157 
<strike>I would like both input polyhedra to be hidden once the c3t3 is displayed, but I did not figure out how to do that until now... Any clue?</strike>
=> Mesh_3 plugin made able to mesh surfaces with border inside a closed polyhedral domain

Polyhedron/demo/Polyhedron/Scene_group_item.cpp
Fix the display of the Scene_group_item, that only displays the first of its children since #2147 .
=> Polyhedron_demo: Fix group_item draw().

.travis/build_package.sh
With the switch to clang-3.6, the `$CC` no longer matches "clang". This patch should re-add that the flag `-Werror=inconsistent-missing-override` to clang builds.
=> Travis: restore -Werror=inconsistent-missing-override

Polyhedron/demo/Polyhedron/Plugins/IO/Surface_mesh_io_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h, Surface_mesh/include/CGAL/Surface_mesh/IO.h, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
- Adds a Save_as in OFF and OBJ format for the Surface_mesh items
- Adds a color writing for the OFF format. As it does not seem to be officially supported by Wavefront OBJ format, I didn't think it was a good idea to add it, I don't want to break any compatibility.
* Affected package(s):Surface_mesh, Polyhedron_demo
* Issue(s) solved (if any): fix #2169
=> Polyhedron_demo: 'Save as' for Surface_mesh items

Interpolation/include/CGAL/Voronoi_intersection_2_traits_3.h, Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
Don't hide the groupbox when the edition mode is selected.
* Issue(s) solved (if any): fix #2215
=> Polyhedron_demo: Fix selection_plugin

Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp
Fixes the warnings about `std::size_t` to `unsigned int` conversion in Surface_reconstruction_plugin
=> Polyhedron_demo: Fix conversion warning in Surface_reconstruction_plugin

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/MainWindow.h, Polyhedron/demo/Polyhedron/MainWindow.ui, Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene.h, Polyhedron/demo/Polyhedron/Scene_item.cpp, Three/include/CGAL/Three/Scene_interface.h, Three/include/CGAL/Three/Scene_item.h
Fixes the clipping bug that occurs when the user recenters the scene and then changes its Bbox (by un-hiding an item for example)
=> Polyhedron_demo: Fix clipping bug

Surface_mesh_deformation/include/CGAL/Surface_mesh_deformation.h
It is now possible to discard changes when deforming a mesh even without ROIs.
* Issue(s) solved (if any): fix #2228
=> Polyhedron_demo: Fix discarding during deformation 

Mesh_3/include/CGAL/Mesh_3/properties_Surface_mesh.h, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Optimization_plugin_cgal_code.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
- Fix mesh_3_plugin with Surface_mesh 
- Make the optimization_plugin work with a c3t3 made from a surface_mesh
* Affected package(s):Polyhedron_demo, Mesh_3(the properties_Surface_mesh file)
=> Polyhedron_demo: Mesh_3_plugins for surface_mesh

.travis/build_package.sh, Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Shape_base.h
When a shape is detected, the largest connected component is sought after. In the implementation, it seems that a cache mechanism was partially implemented: there is a boolean that tells if the largest connected component was already computed. But this component is not saved (only its cardinality is saved), which produces the following bug: if a shape is discarded once but then tried again (it can happen that a shape is not discarded at the second trial because of a variation of probability), the largest connected component is not computed. Therefore, _all the points_ are considered part of the largest connected component (which is usually wrong).
I removed this boolean and the associated test: the bug is gone and there's no noticeable impact on the performances. …
=> Shape detection: bugfix on connected components

Point_set_3/include/CGAL/Point_set_3.h, Point_set_3/test/Point_set_3/point_set_test.cpp
The removal method that takes an indexed was not usable (and not tested) because the index was modified internally while being const. This fixes it.
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/2221
=> Point set 3: bug fix remove index

Boolean_set_operations_2/include/CGAL/Boolean_set_operations_2/Gps_on_surface_base_2_impl.h
`insert` method is broken. After validation `p_begin` point to the end of the iterator and actual insertion is not performed.
* Affected package(s): Boolean_set_operations_2
=> Boolean_set_operations_2: Fix insert to Gps

Polyhedron/demo/Polyhedron/Viewer.cpp
Restore the Orthogonal projection persistence and add a call to Viewer::update() so the change is instant.
* Issue(s) solved (if any): fix #2240
=> Polyhedron_demo: Fix Orthogonal projection

Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h, Polyhedron/demo/Polyhedron/include/CGAL/statistics_helpers.h
- SM items have statistics.
- Orthogonal zoom (O + Left Click) is fixed and works for SM items.
I wanted to add ID printing to the SM item too but I'd rather wait for #2204 to be integrated, it will make it better and much easier.
=> Polyhedron_demo: Add statistics and orthogonal zoom to SM item

Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h
I used Mathjax symbol instead of html symbol.
Tested locally, `documentation_parser.py` is now happy.
=> Workaround error in doxygen xml parsing

Polyhedron/demo/Polyhedron/Plugins/IO/VTK_io_plugin.cpp
Remove `typename` in non-template code.
Not spotted in the testsuite as for VC++ we do not have vtk installed.
* Affected package(s):  :Polyhedron demo
=> Polyhedron/Plugins/IO/VTK_plugin:  remove typename

Polyhedron/demo/Polyhedron/Plugins/Point_set/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Surface_reconstruction_plugin_impl.cpp, Surface_mesher/include/CGAL/IO/output_surface_facets_to_facegraph.h
The surface_reconstruction_plugin outputs Polyhedron or Surface_mesh items according to the Preferences.
Remark : The file used for BGLizing the poisson reconstruction is introduced in #2254 
=> Polyhedron_demo: Surface reconstruction plugin outputs Scene_surface_mesh_item

Surface_mesh_shortest_path/examples/Surface_mesh_shortest_path/shortest_paths_no_id.cpp, Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
The constructor of `Surface_mesh_shortest_path` took a reference to a `TriangleMesh`. I changed that to `const&`.
In the implementation we cast the constness away due to a problem with the vertex point pmap
* Affected package(s): Surface_mesh_shortest_path
* Issue(s) solved (if any): a mail on cgal-discuss
=> Make the reference to the TriangleMesh const. 

Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Instead of issuing a warning to `std::cout` we set the failbit in the  `operator>>(istream&, Surface_mesh&)`
* Affected package(s):  Surface_mesh
* Issue(s) solved (if any): fix #2195
=> Surface_mesh: Set the failbit instead of writing a warning message to std::cout

Documentation/doc/scripts/compare_testsuites.sh, Documentation/doc/scripts/test_doxygen_versions.sh, Scripts/developer_scripts/run_doxygen_testsuite
- Use rsync instead of a symbolic link,
- and exit earlier on errors.
If there is an error, then the rsync will not overwrite the current documentation.
=> doc.cgal.org/master: Try to be more robust on errors

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Parameterization_plugin.cpp
This PR should fix the warning in Parameterization_plugin taht occurs on SOSNO about a conversion from const double to float.
=> Polyhedron_demo: Fix warning on windows

Triangulation_2/include/CGAL/Constrained_Delaunay_triangulation_2.h, Triangulation_2/include/CGAL/Constrained_triangulation_2.h, Triangulation_2/include/CGAL/Constrained_triangulation_plus_2.h, Triangulation_2/test/Triangulation_2/include/CGAL/_test_cls_constrained_triangulation_2.h
The  `Constrained_edges_iterator` was documented but not implemented.
=> Triangulation_2: Add implementation and test of Constrained_edges_iterator

Convex_hull_3/doc/Convex_hull_3/examples.txt, Convex_hull_3/examples/Convex_hull_3/CMakeLists.txt, Convex_hull_3/examples/Convex_hull_3/dynamic_hull_OM_3.cpp, Convex_hull_3/examples/Convex_hull_3/quickhull_OM_3.cpp, Convex_hull_3/include/CGAL/convex_hull_3.h, Convex_hull_3/test/Convex_hull_3/CMakeLists.txt, TDS_3/include/CGAL/Triangulation_data_structure_3.h, Triangulation_3/include/CGAL/link_to_face_graph.h
Add examples for using 3D convex hull functions with open mesh.  And fix a bug in convex hull code as it does use more than in the concept `MutableFaceGraph`.
=> Convex_hull_3: Make it work for OpenMesh

NewKernel_d/test/NewKernel_d/CMakeLists.txt, Triangulation/examples/Triangulation/CMakeLists.txt, Triangulation/test/Triangulation/CMakeLists.txt
This PR will disable the CMake configuration of tests and examples for Epick_d and Triangulation (dD).
That will avoid compilation errors in the CentOS5 testsuite results.
Cc @mglisse
=> Epick_d: check gcc version and return() if < 4.4

Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h
Should fix [this compilation error][1]:
```
[100%] Building CXX object CMakeFiles/mesh_polyhedral_domain_with_surface_inside.dir/mesh_polyhedral_domain_with_surface_inside.cpp.o
/usr/bin/c++   -DCGAL_MESH_3_NO_DEPRECATED_C3T3_ITERATORS -DCGAL_MESH_3_NO_DEPRECATED_SURFACE_INDEX -DCGAL_TEST_SUITE -DCGAL_USE_GMP -DCGAL_USE_MPFR -DCGAL_USE_ZLIB -Wall -std=c++0x -frounding-math -I/home/cgal_tester/build/src/cmake/platforms/CentOS6-CXX11-Boost157/test/Mesh_3_Examples/../../include -I/home/cgal_tester/build/src/cmake/platforms/CentOS6-CXX11-Boost157/test/Mesh_3_Examples -I/home/cgal_tester/build/src/cmake/platforms/CentOS6-CXX11-Boost157/include -I/mnt/testsuite/include -isystem /usr/local/include    -o CMakeFiles/mesh_polyhedral_domain_with_surface_inside.dir/mesh_polyhedral_domain_with_surface_ …
```
=> Qualify call of is_empty() as CentOS6-CXX11 sees an ambiguity with struct std::is_empty

CGAL_ImageIO/test/CGAL_ImageIO/test_trilinear_interpolation.cpp
Tries to fix the runtime error:
```
test_trilinear_interpolation: /home/cgal_tester/build/src/cmake/platforms/Fedora-32-Release/test/CGAL_ImageIO/test_trilinear_interpolation.cpp:110: int main(): Assertion `value2 == value3' failed.
```
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.11-Ic-71/CGAL_ImageIO/TestReport_lrineau_Fedora-32-Release.gz
* Affected package(s): CGAL_imageIO
=> Force 53 bits of precision

Arrangement_on_surface_2/test/Arrangement_on_surface_2/Traits_base_test.h, Convex_hull_3/benchmark/Convex_hull_3/is_on_positive_side.cpp, Convex_hull_3/include/CGAL/convex_hull_3.h, Filtered_kernel/include/CGAL/Filtered_construction.h, Filtered_kernel/include/CGAL/Filtered_predicate.h, Filtered_kernel/include/CGAL/Filtered_predicate_with_state.h, Filtered_kernel/include/CGAL/Lazy.h, Kernel_23/test/Kernel_23/include/CGAL/_test_cls_object.h, Nef_2/include/CGAL/Filtered_extended_homogeneous.h, NewKernel_d/include/CGAL/NewKernel_d/Cartesian_filter_NT.h, NewKernel_d/include/CGAL/NewKernel_d/Filtered_predicate2.h, Number_types/test/Number_types/Interval_nt.cpp, Number_types/test/Number_types/Interval_nt_new.cpp, STL_Extension/test/STL_Extension/test_Uncertain.cpp, Skin_surface_3/include/CGAL/Skin_surface_base_3.h, Skin_surface_3/include/CGAL/triangulate_mixed_complex_3.h, Straight_skeleton_2/include/CGAL/Straight_skeleton_2/Straight_skeleton_builder_traits_2_aux.h
This PR takes references to exceptions instead of values to fix warnings on GCC 8;
* Issue(s) solved (if any): fix #2285
=> Fix new -Wcatch-value warnings (gcc>=8.0)

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item_decorator.cpp
Scene_selection_items had lost their name, this PR restores it. They also displayed Polyhedron in their tooltip, now it says Selection.
* Affected package(s):Polyhedron demo
=> Polyhedron demo: minor fixes for selection items

Mesh_3/include/CGAL/Mesh_3/experimental/Sizing_field_with_aabb_tree.h
Fix a bug in Mesh_3, that mades the Mesh_3 plugin of the polyhedron demo crash on `anchor.off`.
* Affected package(s): Mesh_3, Polyhedron demo
* Issue(s) solved (if any): fix #2284
=> Mesh_3 plugin: fix a bug that could lead to a size close to 0

Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Scene.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.h, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp, Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.h, Polyhedron/demo/Polyhedron/TextRenderer.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/include/id_printing.h, Three/include/CGAL/Three/Scene_draw_interface.h, Three/include/CGAL/Three/Scene_print_item_interface.h, Three/include/CGAL/Three/TextRenderer.h
With this PR, the polyhedron_item has new options in its context menu allowing to display all the vertex IDs and/or all the edge IDs and/or all the face IDs. It also adds an action to zoom to the wanted primitive by giving its Id (v0 for the vertex with Id 0, e0 for an edge and f0 for a face).
=> Polyhedron_demo: Enhance id printing

CGAL_Core/include/CGAL/export/CORE.h, CGAL_ImageIO/include/CGAL/export/ImageIO.h, GraphicsView/include/CGAL/export/Qt.h, Installation/include/CGAL/export/CGAL.h
On Windows (MSVC), compiling the Polyhedron demo, in Debug, with `CGAL_HEADER_ONLY` produces linker error on the `demo_framework` DLL. This PR fixes the issue.
=> Fix link error of demo/Polyhedron, in Debug and CGAL_HEADER_ONLY

Polyhedron/demo/Polyhedron/Plugins/IO/Selection_io_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/IO/VTK_io_plugin.cpp
This PR modifies the nameFilters of the affected IO plugins to avoid duplication.
* Issue(s) solved (if any): fix #2294
=> Polyhedron_demo: Fix Qt warning about duplicate filters

CGAL_Core/src/CGAL_Core/CMakeLists.txt, Installation/CMakeLists.txt
- The Debian package uses `-DCGAL_ENABLE_PRECONFIG=OFF` and
`WITH_GMPXX=ON`. In that setup, GMPXX must be in the "essential" 3rd
party libraries.
- The CGAL_Core library must be linked with its
dependencies (compilation error with `-zdefs`).
With CMake flags or linker flags that are not tested by our testsuite process.
* Affected package(s): all
=> Fix link errors in the building of the Debian packages

Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
Fix the crash that occurs if the point passed to the Surface_mesh_shortest_path::nearest_to_location function is located on a border edge.
It now returns directly the main face if the point is located on a border edge and it does not look anymore for a non-existent opposite face.
* Affected package(s): Triangulated Surface Mesh Shortest Paths
=> FIX: crash in Surface_mesh_shortest_path::nearest_to_location

Polyhedron/demo/Polyhedron/Plugins/PMP/Repair_polyhedron_plugin.cpp
This trivial PR adds waitcursors to the actions of the Repair_polyhedron_plugin
=> Polyhedron_demo: Add waitcursors to Repair_polyhedron_plugin

BGL/include/CGAL/boost/graph/copy_face_graph.h
The way the next halfedge of each border halfedge was set assumed that no vertex was non-manifold. With the following patch we use the connectivity of the input mesh for setting the next pointer.
=> Handle non-manifold vertices when copying a mesh

Convex_hull_3/include/CGAL/convex_hull_3.h, Convex_hull_3/test/Convex_hull_3/ch3_4points.cpp
The tetrahedron was always incorrectly oriented by construction.
* Issue(s) solved (if any): fix #2320
=> fix the orientation of convex hull polyhedron of 4 points

AABB_tree/examples/AABB_tree/AABB_cached_bbox_example.cpp, AABB_tree/include/CGAL/AABB_traits.h, Installation/changes.html
Add a template argument to `AABB_traits` for a property map from the primitive id to a `Bbox_3`.
The construction with a mesh with 1.637.579 triangles takes
* 4.574 sec. for a Polyhedron
* 2.591 sec. for a `Surface_mesh`
* 1.872 sec. for a `Surface_mesh` with a `Bbox_3` as property per `face_descriptor`.
We stay backward compatible. This is documented. The computation of the Bbox_3 could be done in a `tbb::parallel_for` loop.  Well, I gave it a try but there is no gain. 
* Affected package(s): AABB_tree
* Feature/Small Feature (if any): [Small_Features/AABB_traits: Add Bboxmap](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/AABB_traits:_Add_Bboxmap)
=> AABB_tree: Accelerate construction

Polyhedron/demo/Polyhedron/Plugins/PMP/Distance_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_to_mesh_distance_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_to_mesh_distance_widget.ui, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.h, Polyhedron/demo/Polyhedron/include/Point_set_3.h
This is a plugin that allows to colorize a point set according to the distance of each point to a selected mesh (polyhedron or surface_mesh.
* Issue(s) solved (if any): fix #2163
=> Polyhedron_demo: Point set to mesh distance plugin

Polyhedron/demo/Polyhedron/Plugins/PCA/Edit_box_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Scene_facegraph_item_k_ring_selection.h
Remove the need for shift to manipulate the Editable box, which avoids problems with a selection_item.
=> Polyhedron_demo: No shift for Edit_box

Polyhedron/demo/Polyhedron/CMakeLists.txt, Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Mean_curvature_flow_skeleton_plugin.ui, Polyhedron/demo/Polyhedron/Plugins/PMP/Scene_mcf_item.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Scene_mcf_item.h, Polyhedron/demo/Polyhedron/Scene.cpp
This PR is a rework of this plugin, using group items to store variables that were hold by the plugin before, allowing it to manage several items and avoiding segfaults. 
It also adds a label to wxplain how it works, so the user is not surprised anymore when he/she asks for a skeletonization before runing any iteration.
=> Polyhedron_demo: Robustify Mean_curvature_flow_skeleton_plugin

Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_outliers_removal_plugin.ui
Add greater precision to the distance spinbox of the dialog in point_set_outliers_removal_plugin.
=> Polyhedron_demo: Add decimals for smaller distance in outliers plugin

Generator/examples/Generator/random_points_in_tetrahedral_mesh_3.cpp, Generator/examples/Generator/random_points_on_tetrahedral_mesh_3.cpp, Mesh_3/doc/Mesh_3/CGAL/Polyhedral_mesh_domain_3.h, Mesh_3/include/CGAL/Mesh_3/experimental/Get_facet_patch_id.h, Mesh_3/include/CGAL/Polyhedral_complex_mesh_domain_3.h, Mesh_3/include/CGAL/Polyhedral_mesh_domain_3.h, Mesh_3/include/CGAL/Polyhedral_mesh_domain_with_features_3.h, Polyhedron/demo/Polyhedron/C3t3_type.h
This PR fixes issue #2084 by using `PMP::Side_of_triangle_mesh` and its public API from `Polyhedral_mesh_domain_3` in Mesh_3.
It also fixes some compilation issues for the use of Mesh_3 with `Surface_mesh` and `Graph_with_descriptor_with_graph`.
* Affected package : Mesh_3, Demo
* Issue solved : fix #2084
=> Mesh_3 : use PMP::Side_of_triangle_mesh

Polynomial/test/Polynomial/test_polynomial_Get_arithmetic_kernel.cpp
Fixes [this warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-9/Polynomial/TestReport_lrineau_CentOS7-Release.gz)
=> Fix a warning

Polyhedron/demo/Polyhedron/Plugins/IO/Selection_io_plugin.cpp
This PR changes the nameFilters and removes the parenthesis, which were messing with the regular expression used to apply the said nameFilters when a file is saved.
* Issue(s) solved (if any): fix #2337
=> Polyhedron_demo: Fix selection_io_plugin

BGL/examples/BGL_OpenMesh/CMakeLists.txt
BGL_OpenMesh examples require OpenMesh, and the testsuite should highlight that OpenMesh was not found
* Affected package(s) : BGL examples
* Issue(s) solved (if any): fix #2317 
@lrineau @sloriot Is this commit enough to fix the color of the testsuite result color?
=> Some BGL examples require OpenMesh : change CMakeLists

TDS_2/doc/TDS_2/Concepts/TriangulationDataStructure_2.h
Removed the macros `\cgalModifBegin` and `\cgalModifEnd` from the file `TDS_2/doc/Concepts/TriangulationDataStructure_2`.
Modified the comment of one of the overloads of the function `insert_in_hole()` to avoid line break.
* Affected package: documentation for TDS_2
* Issue solved: fix #2346 
* Small Feature: the documentation is relevant to [this small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_function_insert_in_hole_to_Triangulation_data_structure_2).
* The small feature was integrated in CGAL 4.10, so the base I used for the fix is `releases/CGAL-4.10-branch`.
=> Fix for doc bug, github issue #2346

Polyhedron/demo/Polyhedron/Plugins/PCA/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/PCA/Clipping_box_widget.ui, Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.cpp, Polyhedron/demo/Polyhedron/Plugins/PCA/Scene_edit_box_item.h, Polyhedron/demo/Polyhedron/Scene.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h, Polyhedron/demo/Polyhedron/resources/shader_flat.f, Polyhedron/demo/Polyhedron/resources/shader_no_light_no_selection.f, Polyhedron/demo/Polyhedron/resources/shader_spheres.v, Polyhedron/demo/Polyhedron/resources/shader_with_light.f, Polyhedron/demo/Polyhedron/resources/shader_with_light.v, Polyhedron/demo/Polyhedron/resources/shader_without_light.f, Polyhedron/demo/Polyhedron/resources/shader_without_light.v, Three/include/CGAL/Three/Scene_transparent_interface.h, Three/include/CGAL/Three/Viewer_interface.h
Adds a plugin that use a Scene_edit_box to define a zone of clipping. Only the content of the box is displayed. (Only work for items displayed with the most common shaders).
It also fixes some transparency problems, by defining and using a new interface for transparent items.
=> Polyhedron_demo: Clipping box plugin

Spatial_sorting/include/CGAL/Hilbert_sort_middle_2.h, Spatial_sorting/include/CGAL/Hilbert_sort_middle_3.h, Spatial_sorting/include/CGAL/Hilbert_sort_middle_d.h, Spatial_sorting/test/Spatial_sorting/test_hilbert.cpp
Avoid trying to sort a range that we just sorted.
Trying to sort a range of 2 identical points exhibits the infinite loop.
=> Fix infinite loop in spatial sorting

Installation/CMakeLists.txt
Paths were absolute while documented as relative.
=> Make install paths relative as documented

Bounding_volumes/doc/Bounding_volumes/CGAL/Min_sphere_of_spheres_d_traits_2.h, Bounding_volumes/doc/Bounding_volumes/CGAL/Min_sphere_of_spheres_d_traits_3.h, Bounding_volumes/doc/Bounding_volumes/CGAL/Min_sphere_of_spheres_d_traits_d.h, Bounding_volumes/doc/Bounding_volumes/Concepts/MinSphereOfSpheresTraits.h
The dimension is documented as a type (unspecified), which is wrong and does not make any sense. This PR makes it consistent with the code (dimension is `static const int` in every case).
* Affected package(s): Bounding Volumes
* Issue(s) solved: fix https://github.com/CGAL/cgal/issues/2225
=> Bounding volumes: Fix wrong dimension doc

Surface_mesher/doc/Surface_mesher/CGAL/Surface_mesh_traits_generator_3.h, Surface_mesher/doc/Surface_mesher/Concepts/SurfaceMeshTraits_3.h
=> Surface_mesher: Change `Type` to `type` in the type generator

Documentation/doc/resources/1.8.13/cgal_stylesheet.css, Documentation/doc/resources/1.8.13/header.html
Our custom CSS for Doxygen interferes badly with Doxygen internals. If we remove them, the result seems better, with Doxygen 1.8.13.
That should probably be backported to 4.11/4.10.
Fix #1995.
=> Remove our CSS hacks, to "fix" the compilation with Doxygen 1.8.13

Surface_mesh/include/CGAL/Surface_mesh/Properties.h, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
When removing simplices from a `CGAL::Surface_mesh` object, they are not deleted and their memory can be reused later on. The problem is that the connectivity structure of a newly added simplex is not reinitialized, which can lead to problems.
For example, if you remove an isolated vertex (which should not pose any structure issue) and add a new one, the new one will be considered adjacent to a random face because the connectivity structure was used to keep track of removed vertices. Although it is said in the manual that removing isolated vertices could leave the surface mesh in an invalid state, it seems counter-intuitive to get an invalid state after _adding_ a new vertex (especially if the previous removed vertex was isolated).
This PR adds a reinitialization step of the connectivity …
=> Surface mesh: reinit connectivies when reusing garbage memory

Point_set_processing_3/include/CGAL/IO/read_ply_points.h
Properties in PLY input were badly handled: all simple properties were assigned to points whereas face can have simple properties too (other properties than just the list of vertices). As a result, loading a PLY with colored _faces_ in the demo was leading to a crash. This fixes it.
* Affected package(s): Point_set_processing, Polyhedron_IO
=> PLY reader: Fix face properties bug

Polyhedron/demo/Polyhedron/include/CGAL/IO/read_surf_trianglemesh.h
There is no need to increment the material_id here, it is done in the calling function
=> Polyhedron demo - improve .surf reader

Point_set_processing_3/doc/Point_set_processing_3/Point_set_processing_3.txt, Polygon_mesh_processing/doc/Polygon_mesh_processing/Polygon_mesh_processing.txt
Fix some \ref  so that the links go to the package overview
=> PSP, PMP: Fix some \ref 

.travis/build_package.sh, Polyhedron/demo/Polyhedron/Polyhedron_3.qrc, Polyhedron/demo/Polyhedron/Scene_image_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_item.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp, Polyhedron/demo/Polyhedron/Viewer.h, Polyhedron/demo/Polyhedron/resources/no_interpolation_shader.f, Polyhedron/demo/Polyhedron/resources/no_interpolation_shader.g, Polyhedron/demo/Polyhedron/resources/no_interpolation_shader.v, Polyhedron/demo/Polyhedron/resources/shader_flat.f, Polyhedron/demo/Polyhedron/resources/shader_flat.g, Polyhedron/demo/Polyhedron/resources/shader_flat.v, Polyhedron/demo/Polyhedron/resources/shader_old_flat.f, Three/include/CGAL/Three/Scene_item.h, Three/include/CGAL/Three/Viewer_interface.h
Set an OpenGL 4.3 format if possible and create a QOpenGLFunctions_4_3_Compatibility in that case.
Use this recent context to link geometry shaders in order to use an efficient flat shading in polyhedron_item and to fix the visual problems remaining in #950.
* Affected package(s): Polyhedron_demo
* Issue(s) solved (if any): fix #2055
=> Polyhedron_demo: Use a recent OpenGL context if possible

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_widget.ui
There was one default button added by mistake.
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/2395
=> Polyhedron demo: remove pushButton from selection plugin

Installation/changes.html, Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Document that ` operator>>(std::istream, CGAL::Surface_mesh& sm)` does not call `sm.clear()`. 
This change was introduced to make it behave identical to ` read_off(..)`
=> Document breaking change

Subdivision_method_3/include/CGAL/Subdivision_method_3/internal/subdivision_hosts_impl_3.h
The code was assuming the graph as `clear()`, `reserve()`, and `is_valid()` member functions.
=> Use free functions as documented in the MutableFaceGraph concept

Solver_interface/include/CGAL/Eigen_matrix.h, Surface_mesh_parameterization/test/Surface_mesh_parameterization/CMakeLists.txt
The compiler option `/FR` leads to an [ICE in the testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-34/Surface_mesh_parameterization/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz) for just `#include <Eigen/Sparse>`.
I at the same time removed the line `#define EIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET`, as according to Gael Guennebaud this package is stable now. 
* Affected package(s): Surface_mesh_parameterization
=> Parameterization:  Remove VC++ compiler option; Remove a macro concerning Eigen

Operations_on_polyhedra/include/CGAL/internal/corefinement/Combinatorial_map_output_builder.h
Fix the class `Combinatorial_output_builder` used in old version of corefinement
=> Fix cmap output builder

Polyhedron/demo/Polyhedron/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/PMP/Orient_soup_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.cpp, Polyhedron/demo/Polyhedron/Scene_polygon_soup_item.h
This PR completes the Orient_polygon_soup_plugin by implementing the shuffling for surface_mesh and adds a load function to the polygon_soup_item that takes a surface_mesh_item as argument.
=> Polyhedron_demo: Shuffle_polygon_soup for Surface_mesh

Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
Fixes the display of duplicated surface_mesh_items.
* Issue(s) solved (if any): fix #2391
=> Polyhedron_demo: fix Surface_mesh_item clone()

Subdivision_method_3/doc/Subdivision_method_3/Concepts/PQQMask_3.h, Subdivision_method_3/doc/Subdivision_method_3/Concepts/PTQMask_3.h, Subdivision_method_3/doc/Subdivision_method_3/Concepts/Sqrt3Mask_3.h, Subdivision_method_3/include/CGAL/Subdivision_method_3/internal/subdivision_hosts_impl_3.h, Subdivision_method_3/include/CGAL/Subdivision_method_3/subdivision_masks_3.h
PQQ and PQT masks were actually expecting a non border halfedge. We documented it and ensure it. To be consistent we also change the function of the Sqrt3 mask so that a non border halfedge is taken (fixing at the same time a missing documentation an overload that is now merged).
=> Fix issues on the border of subdivided mesh

Polyhedron/demo/Polyhedron/Plugins/PCA/Basic_generator_plugin.cpp
At the beginning I simply wanted to upper case words but talking about widget sounds better to me as that's what the action is doing: points you to a dock widget where you can create an object
=> improving the object generator menu labels

Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Shape_base.h
With large u and v, the product u * v exceeds the capacity of an int.  The result when coerced to size_t can be an out of range index into bitmap.
Avoid this by casting u and v to size_t before multiplying.
* Affected package(s): Point set shape detection
* Issue(s) solved (if any): fix #2408
=> Shape Detection: avoid index out of range with large bitmap sizes

Point_set_2/include/CGAL/Point_set_2.h
One method of `Point_set_2` is recursive and may lead to stack overflow. Simply replacing it with an `std::stack` (with an additional check when destacking) solves the issue. I tested it locally.
* Affected package(s): Point Set 2
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/2410
=> Point set 2: make method dfs non-recursive

Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h
The package `SM_shortest_path` offers a locate function which builds an `AABB` tree to find the closest point on the face graph. It is possible to pass a custom Vertex Point Property map when calling `locate()`, but this map was not used when constructing the `AABB` tree.
Added an overload to `build_aabb_tree()` for convience (uses the default VPM).
* Affected package(s): `Surface_mesh_shortest_path`
* Issue(s) solved (if any): -- 
=> SM shortest paths: Fix locate with a custom VertexPoint Pmap

Installation/changes.html, Interpolation/doc/Interpolation/Concepts/GradientFittingTraits.h, Interpolation/include/CGAL/Interpolation_gradient_fitting_traits_2.h, Interpolation/include/CGAL/sibson_gradient_fitting.h, Interpolation/test/Interpolation/include/CGAL/_test_regular_neighbors_2.cpp
The interpolation's package offers a few gradient fitting functions. After the weighted/bare point implicit conversion change (PR https://github.com/CGAL/cgal/pull/2102), these functions do not compile anymore (being untested, they sneaked through...).
This PR fixes that and adds a test.
* Affected package(s): Interpolation
* Issue(s) solved (if any): -- 
=> Interpolation: Fix gradient fitting

Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp, Polyhedron/demo/Polyhedron/include/Point_set_3.h
In order to handle the quick display of point sets (only displaying a random fraction of the points when moving the camera), indices of points are shuffled. But as result, when saving a point set, even unaltered, the points have a different order than in the input file, which can be disturbing for users.
This PR resets the indices before saving.
=> Polyhedron demo: reset points order before saving

Polyhedron/demo/Polyhedron/Plugins/IO/PLY_io_plugin.cpp
For VC++ the stream must be opened in binary mode.
=> Polyhedron demo: bug fix for writing binary PLY

Polyhedron/demo/Polyhedron/Color_ramp.cpp, Polyhedron/demo/Polyhedron/Color_ramp.h, Polyhedron/demo/Polyhedron/Plugins/Display/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/Display/Display_property.ui, Polyhedron/demo/Polyhedron/Plugins/Display/Display_property_plugin.cpp, Polyhedron/demo/Polyhedron/Viewer.cpp, Three/demo/Three/Example_plugin/Dock_widget_plugin.cpp
Adds a widget that allows to colorize a surface_mesh according to the smallest angle of each of its faces, or according to their scaled jacobian.
=> Polyhedron demo: New widget for color computation

Mesh_3/include/CGAL/Mesh_3/Mesher_3.h
In issue #2453:
> I am trying to mesh in the demo a given Polyhedron (the problem is the same with Surface_mesh with a very small tetrahedron size, and the output mesh is always more or less the same, with very few simplices compared to what I expect.
Actually, the demo uses a loop:
```C++
while( !mesher->is_algorithm_done() )
mesher->one_step();
```
Because of that bug in `one_step()`, `is_algorithm_done()` could return
`true` even before the cells mesher level has scanned the triangulation
for bad cells. That will be fixed, now.
The bug is since CGAL-4.11.
* Affected package(s): Mesh_3, Polyhedron demo
* Issue(s) solved (if any): fix one point of #2453
=> Bug-fix for Mesher::one_step()

Number_types/include/CGAL/Lazy_exact_nt.h, STL_Extension/include/CGAL/type_traits.h
To work around a bug observed with boost 1.62 with c++11 ON.
Fixes [this error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-46/Surface_mesher/TestReport_lrineau_Debian-Testing.gz)
=> Use CGAL::cpp11::is_enum

Surface_mesh_simplification/test/Surface_mesh_simplification/test_edge_profile_link.cpp
Fix for VC  `warning C4800: 'void *' : forcing value to bool 'true' or 'false'`
* Issue(s) solved (if any): fix #2350
=> Fix VC performance warning

BGL/examples/BGL_surface_mesh/write_inp.cpp, BGL/include/CGAL/boost/graph/io.h
Add a function that generates an Abaqus `*.inp` file for a `FaceGraph`.
I am not sure if the parameter for `type` is needed. `S4R` means quad mesh but not sure what the `R`means.  See [here](http://imechanica.org/files/l2-elements.pdf).
=> Add write_inp(FaceGraph)

Mesh_2/include/CGAL/Mesh_2/Clusters.h, Mesh_2/include/CGAL/Mesh_2/Refine_edges_with_clusters.h
When two clusters share a subsegment, the subsegment is split at its
middle, instead of using the length imposed by the clusters. If the
clusters were partially refined before that subsegment is split, one
must reset the clusters, because the minimal length may have changed.
This PR:
- fixes the bug,
- add more debug output, in conditionals `CGAL_MESH_2_DEBUG_CLUSTERS`.
* Affected package(s): Mesh_2
* Issue(s) solved (if any): fix #2456 
=> Mesh 2: fix clusters (issue #2456)

Arrangement_on_surface_2/include/CGAL/graph_traits_Arrangement_2.h, Arrangement_on_surface_2/include/CGAL/graph_traits_Dual_Arrangement_2.h, Convex_hull_2/test/Convex_hull_2/ch2_point_with_info.cpp, NewKernel_d/include/CGAL/NewKernel_d/Types/Hyperplane.h, NewKernel_d/include/CGAL/NewKernel_d/Types/Sphere.h, NewKernel_d/include/CGAL/NewKernel_d/Types/Weighted_point.h, Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Efficient_RANSAC.h, Polyhedron/demo/Polyhedron/Plugins/PMP/Distance_plugin.cpp, Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2.h, Segment_Delaunay_graph_Linf_2/include/CGAL/Segment_Delaunay_graph_Linf_2.h, Spatial_searching/benchmark/Spatial_searching/nearest_neighbor_searching_inplace_50.cpp, Spatial_searching/examples/Spatial_searching/searching_with_point_with_info_inplace.cpp, Spatial_searching/examples/Spatial_searching/searching_with_point_with_info_pmap.cpp, Spatial_sorting/examples/Spatial_sorting/sp_sort_using_property_map_3.cpp, Spatial_sorting/examples/Spatial_sorting/sp_sort_using_property_map_d.cpp, Triangulation_2/include/CGAL/Triangulation_2/insert_constraints.h
Fix for https://github.com/CGAL/cgal/issues/2468. As I was getting tired of this warning, I wrote a file `CGAL/counting_iterator.h` that just does the inclusion surrounded by the warning deactivation, but then I realized that it already existed (for the very same reason, I guess), see in `Installation/include/CGAL/boost/iterator/counting_iterator.h`. It was already used by some CGAL headers.
So this PR replaces all occurrences of the boost inclusion in CGAL files by this one, which should fix the problem everywhere and prevent it from happening again. We should always use it from now on.
- Arrangement on Surface 2
- Convex hull 2
- NewKernel D
- Point Set Shape Detection 3
- Polyhedron demo
- Segment Delaunay Graph 2 (+ Linf 2)
- Spatial Searching
- Spatial Sorting …
=> Fix counting iterator warnings

Polyhedron/demo/Polyhedron/Scene_surface_mesh_item.cpp
ResetColors removes all the color maps, not just patch_ids.
=> Polyhedron demo: Reset Colors for Surface_mesh_items.

Polyhedron/demo/Polyhedron/Plugins/Point_set/Merge_point_sets_plugin.cpp
Fix segfault by using `selectionIndices().first()` instead of `mainSelectionIndex()`.
* Issue(s) solved (if any): fix #2451
=> Polyhedron demo: fix Merge_point_sets_plugin

Surface_mesh/examples/Surface_mesh/sm_do_intersect.cpp
`boost::addressof` has changed in a recent version of boost and overloads have been added. Instead of a static cast to the appropriate overload I just added a three-liner for a free function that returns the address.
* Affected package(s): only in an example code.
* Issue(s) solved (if any): fix #2493
=> Fix Surface_mesh example

Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/Midpoint_placement.h
Add `typedef .. ECM` so that one can wrap the `Midpoint_placement`, for example in a `Bounded_normal_change_placement`
=> Surface_mesh_simplification: Add a missing typedef

BGL/include/CGAL/boost/graph/graph_traits_PolyMesh_ArrayKernelT.h, STL_Extension/include/CGAL/hash_openmesh.h
There was a missing const in `operator==()` and the hash function/specialization was not available.
=> Fix hashing of edge_descriptor for OpenMesh

Solver_interface/include/CGAL/Eigen_matrix.h
This is a small fix to add missing _get_coef_ method from the Eigen_sparse_matrix struct. It already exists in the doc of the SparseLinearAlgebraTraits_d concept.
=> Eigen_sparse_matrix: add missing method

GraphicsView/include/CGAL/Qt/debug_impl.h, Installation/include/CGAL/gl.h
If we compile CGAL with having Qt present on arm, Qt will use OpenGL ES
headers. But CGAL/gl.h includes specifically include <GL/gl.h> which are
the desktop headers. They cannot be mixed.
However I am not sure whether there should be a differentiation between OpenGL ES 2 and 3 though. I just used 3 since that what I have here. Please give feedback in case you want me to change something.
* Affected package(s): cgal 4.11
* Feature/Small Feature (if any): let compile on arm(v7) with Qt present
=> Include OpenGL ES for arm

Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/CMakeLists.txt, Polyhedron/demo/Polyhedron/Plugins/Surface_mesh/Offset_meshing_plugin.cpp, Polyhedron/demo/Polyhedron/cgal_test_with_cmake
This is a minimal plugin working with Surface_mesh and the polyhedron item that can generate naive inset and offset meshes.
=> Add a plugin for inset and offset of a polyhedron

BGL/doc/BGL/PackageDescription.txt, BGL/include/CGAL/boost/graph/selection.h, BGL/test/BGL/test_Manifold_face_removal.cpp, Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
In the other functions the range is the first argument and the graph the second (while it was the converse for the new function introduced in 4.12).
At the same time I add a missing reference in the classified reference manual.
=> Change argument order to be consistent with other selection functions

Polyhedron/demo/Polyhedron/include/id_printing.h
The algorithm that collects primitives around the clicked point was not checking if the found faces are null. That caused a segfault in the case of a border edge clicked.
The viewer offset was also misisng in the test for hiding ids, which meant that an offseted scene could not get rid of the displayed ids.
* Issue(s) solved (if any): fix #2525
=> Polyhedron demo: Fix ids displaying 

BGL/doc/BGL/Concepts/HalfedgeGraph.h, Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
This PR fixes `PMP::isotropic_remeshing()`, that can now deal with data that include isolated vertices.
* Issue(s) solved (if any): fix #2488
=> PMP - fix isotropic remeshing with isolated vertices

CMakeLists.txt, cmake_uninstall.cmake.in
This features reduces the pain of having to remove the installed libraries and headers in /usr/local/ one by one.
Before this change, after sudo make install there is no easy ways to remove these files, but with this change we can simply type sudo make uninstall to remove these files.
=> support sudo make uninstall for cmake

Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Region_growing.h
The first point of the first shape detected was assigned index `-1`, which is the value used for unassigned points, which lead to unexpected behavior (duplicate indices). The class index should be initialized to `0`, not `-1` (increment _before_ assigning to point).
* Affected package(s): Point Set Shape Detection
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/2483
=> Region Growing: fix badly initialized class_index (lead to duplicate indices)

Polyhedron/demo/Polyhedron/Plugins/AABB_tree/Cut_plugin.cpp
Delete trees whenever invalidateOpenGLBuffers is changed, as it deletes the item's tree.
* Issue(s) solved (if any): fix #2520
=> Polyhedron demo: Fix Cut_plugin

Surface_mesh/include/CGAL/Surface_mesh/Surface_mesh.h
Constructors of the index classes of `Surface_mesh` should be explicit (to avoid dangerous implicit conversions!).
* Affected package(s): `Surface_mesh`
=> Surface_mesh: Added missing 'explicit' on SM_Edge_index constructor

README.md
GitHub renders a `#` sign beneath the logo because images cannot be headings.  See [new rendering here](https://github.com/svenevs/cgal/blob/patch-2/README.md) :smile:  Current [`REAMDE.md` from `master`](https://github.com/CGAL/cgal/blob/master/README.md) for comparison.
* Affected package(s): N/A
* Issue(s) solved (if any): N/A
=> remove extra `#` beneath logo in README.md

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h, Polyhedron/demo/Polyhedron/Plugins/PMP/Isotropic_remeshing_plugin.cpp
In the `isotropic_remeshing_plugin`, the `Patch_id_map` that `get(..., pmesh)` returns was given as a parameter to `PMP::isotropic_remeshing()`, however it had been initialized or not.
The consequence was that `PMP::isotropic_remeshing()` "thought" it was using a valid `face_patch_map` and hence failed to make valid collapisibility/topology checks next to constrained edges.
The proper behavior when the face patch map is not provided (or invalid) is to compute the connected components from constrained edges. This is automatically done inside the remeshing function.
Now we use the face_patch_map only when it is valid, i.e. with not all its values `== 1` (because `1` is the default value both for `Polyhedron_3` and `Surface_mesh`.
* Affected packages : Polyhedron demo (and minor changes in …
=> Polyhedron demo - fix isotropic remeshing plugin

Installation/changes.html, Mesh_3/doc/Mesh_3/CGAL/make_mesh_3.h, Mesh_3/doc/Mesh_3/CGAL/refine_mesh_3.h, Mesh_3/doc/Mesh_3/PackageDescription.txt, Mesh_3/examples/Mesh_3/mesh_polyhedral_domain.cpp, Mesh_3/include/CGAL/Mesh_3/Mesher_3.h, Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h, Mesh_3/include/CGAL/Mesh_3/Refine_facets_manifold_base.h, Mesh_3/include/CGAL/Mesh_3/global_parameters.h, Mesh_3/include/CGAL/make_mesh_3.h, Mesh_3/include/CGAL/refine_mesh_3.h, Mesh_3/test/Mesh_3/test_meshing_3D_gray_image.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Mesh_function.h
This PR documents the manifold criterion for `Mesh_3`
It is not a "simple" mesh criterion as the others, and can be combined with the others, including the topology criterion for facets.
* Affected package : Mesh_3
* Issue solved : fix #2009
* Feature/Small Feature : [Mesh_3 manifold criterion](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Mesh_3_manifold_criterion)
pre-approved --Laurent Rineau 17:03, 3 October 2017 (CEST)
=> Mesh 3 : document manifold criterion

Mesh_3/include/CGAL/Mesh_3/C3T3_helpers.h, Mesh_3/include/CGAL/Mesh_3/Sliver_perturber.h
The `facet_surface_center` of facet was not always restored correctly,
after an aborted move, and that eventually led to use of uninitialized
memory... and a crash.
* Issue(s) solved (if any): fix #1944
=> Fix a perturber bug

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Three/include/CGAL/Three/Scene_group_item.h
This PR fixes some bugs in the demo:
- Removing a child from a group now sets its parent_group to NULL, which avoids segfault when testing parentGroup() after the deletion of the said group.
- Switching the selection type (selection/edition) tab in the selection plugin does not cause a Segfault when there is no existing selection item anymore.
=> Polyhedron demo: minor fixes

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Isotropic_remeshing/remesh_impl.h
The internal test `collapse_does_not_invert_face(he)` was not able to deal with more than 2 surface patches incident to the end vertices of `he`. This was causing a bug when one of the end vertices of `he` is a corner vertex (incident to more than 2 surface patches in the non-boundary case).
This PR fixes this issue, and modifies the `check_normals(v)` test that had the same issue.
* Affected package : PMP
* Issue(s) solved (if any): fix #2464
=> PMP - fix isotropic_remeshing() collapsibility checks

Polyhedron/demo/Polyhedron/Scene.cpp
The signal redraw() was connected only in addItem() but not in replaceItem(), which means that after a reload or a deformation, all the actions that called redraw() and not itemChanged() were not updating the viewer.
=> Polyhedron demo: Fix some missing redraw

Surface_mesh_skeletonization/include/CGAL/Mean_curvature_flow_skeletonization.h
Surface mesh skeleton code was expecting the vertices of the copied meshed to be in the same order as the input mesh.
Bug reported on cgal-discuss by Adrien Lefieux
=> Cope with the change of order of the vertices in copy_face_graph

Mesh_3/include/CGAL/Mesh_3/Mesher_3.h, Mesh_3/include/CGAL/Mesh_3/Refine_cells_3.h, Mesh_3/include/CGAL/Mesh_3/Refine_facets_3.h, Mesh_3/include/CGAL/Mesh_3/Refine_facets_manifold_base.h, Mesh_3/include/CGAL/Mesh_3/global_parameters.h, Mesh_3/include/CGAL/Mesh_domain_with_polyline_features_3.h, Mesh_3/include/CGAL/Mesh_error_code.h, Mesh_3/include/CGAL/refine_mesh_3.h
This PR imports from the old branch `Mesh_3-experimental-GF` the feature that allows to set a maximal number of vertices. That maximal number will end-up the refinement process forcibly, and an error code is set.
* Affected package(s): Mesh-3
* Feature/Small Feature (if any): none... that is not yet documented.
Question for @cjamin: for the moment it only works if the `Parallel_tag` is not used. Do you see a way to implement something similar in the parallel mode?
=> Mesh_3: the "maximal number of vertices" feature

Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/corefinement.h
This PR improves the doc of the corefinement functions 
- add a precondition that `tm` is closed in `does_bound_a_volume()`
- move the piece of doc about filling `face_index_map` property maps to the corefinement operators
* Issue(s) solved (if any): fix #2543
=> PMP corefinement : improve doc

Surface_mesher/include/CGAL/IO/facets_in_complex_2_to_triangle_mesh.h
Iterate only finite vertices to avoid adding the infinite vertex.
* Fix of #2254, (integrated in `master` for 4.12)
* Affected package(s):Surface_mesher
=> Fix facets_in_complex_2_to_triangle_mesh

Triangulation_2/doc/Triangulation_2/Triangulation_2.txt
Fix spelling mistake in the documentation, however, there are a few more occurrences of the same spelling mistake here: https://github.com/CGAL/cgal/search?q=Constaints
=> Correction to spelling Constaints -> Constraints

Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Octree.h, Polygon_mesh_processing/examples/Polygon_mesh_processing/point_inside_example.cpp, Polygon_mesh_processing/examples/Polygon_mesh_processing/point_inside_example_OM.cpp, Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Two_vertices_parameterizer_3.h
Second part of #2564, because `SMP` was restructured with CGAL-4.11.
* Affected package(s): `SMP`
* Issue(s) solved (if any): fixes  #2563.
=> Fix wrong uses of std::numeric_limits::min() (4.11)

Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Octree.h, Polygon_mesh_processing/examples/Polygon_mesh_processing/point_inside_example.cpp, Polygon_mesh_processing/examples/Polygon_mesh_processing/point_inside_example_OM.cpp, Surface_mesh_parameterization/include/CGAL/Two_vertices_parameterizer_3.h
Various packages wrongly assumed that `min()` returns the lowest possible value.
* Affected package(s): `Point_set_shape_detection_3`, `PMP`, `SMP`
* Issue(s) solved (if any): Partial fix of #2563 
=> Fix wrong uses of std::numeric_limits::min() (4.10)

Polyhedron/demo/Polyhedron/Plugins/IO/VTK_io_plugin.cpp
The VTK name filters are messed up because of the parenthesis around Polyhedron and Surface_mesh in their description. This PR fixes it.
=> Polyhedron demo: fix VTK plugin name filters

Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Efficient_RANSAC.h, Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Octree.h, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.ui
This PR makes the RANSAC algorithm more robust, especially in the case of very large scenes with small details (that currently lead to many missed detections):
* The depth limit of the octree is now computed dynamically with respect to the ratio between the bbox diagonal and the cluster epsilon parameter (to make sure the smallest level's cells are small enough)
* The hard limit of failed candidates that could lead to mistakingly early termination is now computed dynamically too with respect to the size of the input ([this was already reported and closed](https://github.com/CGAL/cgal/issues/2119) because I couldn't reproduce, but now I had the chance to experiment on this)
* One parameter used to compute the termination criteria was badly computed compared to what was done in the original …
=> Shape detection: robustify RANSAC

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp
This PR changes the signal emitted when a pixel is picked so it displays either an integer or a double according the the isovalue type of the image
* Issue(s) solved (if any): fix #2588
=> Polyhedron demo: Fix pixel value in Io_image_plugin

Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Efficient_RANSAC.h, Point_set_shape_detection_3/include/CGAL/Shape_detection_3/Octree.h, Polyhedron/demo/Polyhedron/Plugins/Point_set/Point_set_shape_detection_plugin.ui
(Same as https://github.com/CGAL/cgal/pull/2568 but for CGAL 4.11 release.)
Fixes #2119.
=> Shape detection: robustify RANSAC (for 4.11)

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp
- Change the names of the action and widget according to the facegraph type.
- If the selected item is not of the right type, just say it and don't select the first correct item in the scene entries like before.
=> Polyhedron demo: Split selection plugins

Polyhedron/demo/Polyhedron/Plugins/PMP/Selection_plugin.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.cpp, Polyhedron/demo/Polyhedron/Scene_polyhedron_selection_item.h, Polyhedron/demo/Polyhedron/Scene_polylines_item.cpp, Polyhedron/demo/Polyhedron/Statistics_on_item_dialog.ui
In the polyline_item's tooltip, if there is only one polyline, add the length of this polyline.
* Issue(s) solved (if any): fix #2556
=> Polyhedron demo: add length of polylines

Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Io_image_plugin.cpp, Polyhedron/demo/Polyhedron/Plugins/Mesh_3/Volume_plane.h
Disable the sliders and hide the handles if the loaded/selected image has one dimension with value = 1.
* Issue(s) solved (if any): fix #2573
=> Polyhedron demo: Add 2D image management.

Triangulation/doc/Triangulation/CGAL/Regular_triangulation.h, Triangulation/doc/Triangulation/CGAL/Regular_triangulation_traits_adapter.h
2 small fixes to the doc:
* Remove the non-existing type `Regular_triangulation::Bare_point`
* Document `Regular_triangulation_traits_adapter::Base`
=> Triangulation - fix doc

Installation/CMakeLists.txt
If you look in https://github.com/CGAL/cgal/tree/master/Installation, you will realize the file "CHANGE" does not exist, hence if `sudo make install` there will be errors like
```
-- Installing: /home/ubuntu/cgal/install/share/doc/CGAL-4.12-I-900/AUTHORS
CMake Error at Installation/cmake_install.cmake:41 (file):
file INSTALL cannot find "/home/ubuntu/cgal/Installation/CHANGES".
Call Stack (most recent call first):
cmake_install.cmake:42 (include)
Makefile:107: recipe for target 'install' failed
```
Change "CHANGE" to "changes.md" solves the problem
=> fix sudo make install error because of incorrect file name

Documentation/doc/resources/1.8.13/header_package.html
Remove:
```javascript
$(window).load(resizeHeight);
```
from our Doxygen javascripts.
I have verified in the template in Doxygen 1.8.13 and that line no longer exists.
... And it makes the script crash and report an error in the browser
console.
Check for example:
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.12-Ic-103/master/Mesh_2/index.html
(update the CGAL version if needed)
and open the browser console to see the javascript error. For example, on Chrome:
This PR #2637 deals with the error, and the warning is the subject of the issue #2633, for which we still do not have a pull-request.
=> resizeHeight no longer exist

BGL/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h
Since faces were not triangulated in the conversion from Nef_3 to FaceGraph, faces with more than one boundary where not correctly represented.
Fixes issues reported on [cgal-discuss](https://sympa.inria.fr/sympa/arc/cgal-discuss/2017-11/msg00022.html)
=> Correctly handle faces with more than one cc of the boundary

Periodic_3_triangulation_3/include/CGAL/Periodic_3_Delaunay_triangulation_3.h
Offsets should be obtained via `get_offset()` to have valid offsets even in a 27-sheeted periodic triangulation.
* Affected package(s): Periodic_3_triangulation_3
=> P3DT3: Fix `Is_Gabriel` (4.10)

Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Detail/Edge_collapse_impl.h
This is a real issue for example when using  `Surface_mesh` with some garbage edges not collected.
cc @afabri
=> Use a tight count for the number of edges

Periodic_3_triangulation_3/include/CGAL/Periodic_3_Delaunay_triangulation_3.h, Periodic_3_triangulation_3/include/CGAL/Periodic_3_regular_triangulation_3.h
Offsets should be obtained via get_offset() to have valid offsets even in a 27-sheeted periodic triangulation. This is the same as #2612, but for regular triangulations, which were introduced with CGAL 4.11. 
* Affected package(s): Periodic_3_triangulation_3
* Issue(s) solved (if any): fix #2610
=> P3RT3: Fix `Is_Gabriel` (4.11)

Arrangement_on_surface_2/include/CGAL/Arr_curve_data_traits_2.h, Arrangement_on_surface_2/test/Arrangement_on_surface_2/cgal_test.cmake, Arrangement_on_surface_2/test/Arrangement_on_surface_2/cgal_test_base, Arrangement_on_surface_2/test/Arrangement_on_surface_2/test_data_traits.cpp, Installation/changes.html
This cleans the code of the `Arr_curve_data_traits_2<Tr, ...>` class template and fixes a bug in the code. Any instance of this template is a model of the `ArrangementTraits_2` concept and serves as a decorator class that allows the extension of curves defined by the base traits-class (the `Tr` parameter). The fix adds a wrapper to the `Construct_opposite_2` functor required by the concept `ArrangementDirectionalXMonotoneTraits_2`. The `()` operator of this functor accepts an x-monotone curve and returns its opposite curve. The wrapper attaches the data attached to the input curve to the output curve.
The implementation uses a helper class to detect the presence of a functor with the same name in the base geometry class. While at it, I've changed the code of the Are_mergeable_2 and …
=> Aos_2: data traits construct opposite

Number_types/include/CGAL/Gmpq.h, Number_types/include/CGAL/Gmpz.h, Number_types/include/CGAL/double.h, Number_types/include/CGAL/mpq_class.h, Number_types/include/CGAL/mpz_class.h
Make conversion to interval through MPFR3 faster. Keep old code for compatibility with centos with mpfr-2.2 or 2.4.
=> Faster to_interval(Gmpq)

Polyhedron/demo/Polyhedron/MainWindow.cpp, Polyhedron/demo/Polyhedron/Scene_points_with_normal_item.cpp
This PR fixes some points :
- Don't use the native menuBar because it is buggy on MacOs
- Check if a file is empty before reading it as we know it won't work
- Update the viewer when we change the background
- Increase the initial point size of a point item when there are less than 30 points in it.
=> Polyhedron demo: CGAL meeting fixes 

Surface_mesh/doc/Surface_mesh/examples.txt, Surface_mesh/examples/Surface_mesh/CMakeLists.txt, Surface_mesh/examples/Surface_mesh/sm_derivation.cpp
Add an example that shows that one has to provide specializations for `boost::graph_traits` and `boost::property_map` so that BGL-style algorithms work on a class derived from `Surface_mesh`.
* Affected package(s): Surface_mesh   (no code change, only an example)
* Issue(s) solved (if any): Question was raised by a user in a private mail
=> Surface_mesh: Derivation, boost::graph_traits and boost::property_map

Spatial_searching/include/CGAL/Kd_tree_node.h
This is purely a performance patch. For my use case, in 2D, using a custom point type with a custom distance (sup norm), this is measurably faster. And intuitively it makes sense that checking if a subtree is entirely contained in the query is more useful for search (report all points) than search_any (report one arbitrary point). But if someone else uses search_any, they are welcome to benchmark this on their testcase. It is certainly possible to find types and distributions for which the patch makes performance worse, but I expect them to be rather contrived.
=> Kd_tree::search_any_point: don't check outer_range_contains
